### PR TITLE
Docker buildkit

### PR DESCRIPTION
**Pull request by GoFightNguyen**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by GoFightNguyen** [comment]
Fixes 13992

**Comment by GoFightNguyen** [comment]
Since the change in `create-app` is only comments in the Dockerfile, does this need a changeset?

**Comment by jizusun** [comment]
Hi all,

I guess I came across with the same problem days before https://github.com/backstage/backstage/pull/13702
And I'm wondering why do we need this `WORKDIR /app`?
What if we use the default `WORKDIR` which is `/home/node`?

**Comment by GoFightNguyen** [comment]
`WORKDIR /app` is where I commonly see applications placed in a container. That's not scientific, just anecdotal

**Comment by GoFightNguyen** [comment]
@jhaals @freben can we get 👀 on this since it is about to go stale?

**Review by freben — APPROVED** [review]

**Pull request merged**
