### PR TITLE
Unified Theme Doc Updates & Exported `defaultTypography`

### LINKED ISSUE #22606: 🐛 Bug Report: Update app-custom-theme docs
### 📜 Description

The documentation for [`creating a custom theme`](https://backstage.io/docs/getting-started/app-custom-theme/)  is using deprecated imports, hence needs to be updated with the new correct method for creating a custom theme. 

### 👍 Expected behavior

Documentation for [app-custom-theme](https://backstage.io/docs/getting-started/app-custom-theme/) is up to date with current imports.

### 👎 Actual Behavior with Screenshots

The tutorial imports `createTheme `and `lightTheme `which are both deprecated. 

### 👟 Reproduction steps

1. Go to [https://backstage.io/docs/getting-started/app-custom-theme/](https://backstage.io/docs/getting-started/app-custom-theme/)
2. Follow the tutorial for creating a custom theme
3. See that some imports are deprecated and should not be used

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Updated the theme docs to reflect the changes over the last several months in this area. Also, exported `defaultTypography` to make adjusting these values in a custom theme easier.

Closes #22606 and #22354

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
FYI @reece-stephenson and @DSmedley

**Comment by awanlin** [comment]
@tudi2d, could use your eyes on this one, please? 👀

**Comment by awanlin** [comment]
@camilaibs @benjdlambert any chance you can give this a look? Would be great to have these up to date!

**Review by benjdlambert — APPROVED** [review]
Looks good to me, @tudi2d do you wanna have the final +1?

**Review by Rugvip — APPROVED** [review]
:shipit: 🎉

**Comment by tudi2d** [comment]
sorry - missed this. thanks for fixing this andré - appreciate it!!

**Comment by awanlin** [comment]
Thanks @benjdlambert @Rugvip 🚀 

No worries @tudi2d 👍

**Pull request merged**
