### PR TITLE
changesets: add entry for /api change to create-app

### PR DESCRIPTION
**Pull request by Rugvip**
Want to get this into master to see what kinda PR the changeset workflow gives us :grin:

### CODE REVIEW

**Review by taras — APPROVED** [review]
👍

**Review by stefanalund — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]

**Review by freben — APPROVED** [review]
they will have to have some structure to the names, right? with like a date or a number or something at the start

**Comment by Rugvip** [comment]
@freben you don't get that from the CLI at least, unless there's a way to configure it. Agree it would be nice to find a changeset you're searching for, but you're also really supposed to add it together PR and then forget about it until the next release.

**Comment by freben** [comment]
just feels like an unnecessary chore to make up names for them :)

**Pull request merged**
