### PR TITLE
Documentation Update

### LINKED ISSUE #2146: Yarn install fails with acceptable node version
Following the [Getting Started > Running Backstage Locally](https://github.com/spotify/backstage/blob/master/docs/getting-started/index.md) instructions fail with error when node version greater than minimum required.

## Expected Behavior
When running `yarn install`, I should see the install process continue past the validation step when my node version meets the minimum required.

## Current Behavior
`yarn install` fails validation and task exits without completing successfully.

```zsh
✔︎ backstage % yarn install                                                                             (master)backstage
yarn install v1.22.1
[1/5] 🔍  Validating package.json...
error root@1.0.0: The engine "node" is incompatible with this module. Expected version "12". Got "14.7.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
✘[1] backstage % 
```

## Possible Solution
1) Adjust the package.json's engine node version specified to accept anything greater than the minimum required.
or
2) Adjust the [Getting Started > Running Backstage Locally](https://github.com/spotify/backstage/blob/master/docs/getting-started/index.md) documentation's verbiage.

> _First make sure that you have ~~at least~~ node version 12 installed locally_
> _First make sure that you have node version **12** installed locally_

## Steps to Reproduce

1. run `yarn install` with node version greater than 12.

## Context

Stops me from exploring Backstage

## Your Environment

- Yarn (1.22.1)
- NodeJS Version ( v14.7.0 ):
- Operating System and Version ( macOS 10.15.6 (19G2021) ):
- Shell (zsh)
- Browser Information: n/a

### PR DESCRIPTION
**Pull request by johnson-jesse**
fixes #2146 

Because `yarn install` is limited to the node version 12 family only, making that clear to evaluators is necessary. I thought it would also be helpful to add a tidbit in on how to quickly add another node version for the non power users. The main difference here is the removal of verbiage saying, _"at least node version 12"_ and instead saying _"Active LTS Release, currently v12"_ followed up with example.

Being verbose with documentation here is better than updating the four package files specifying engine node ">= 12" which opens the codebase to instability.

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### Screenshot ⬇️

Screen Shot 2020-08-27 at 4 22 00 PM

### CODE REVIEW

**Comment by freben** [comment]
Hey! The issue with windows builds on github has been resolved. You may want to update this PR on top of the latest master.

For reference: https://github.com/spotify/backstage/pull/2152

**Comment by johnson-jesse** [comment]
@freben upstream merged in. But failing on `Cannot find module '@backstage/cli-common'`

**Comment by johnson-jesse** [comment]
@freben All checks passed!

**Review by stefanalund — APPROVED** [review]
Thanks 🙏

**Pull request merged**
