### PR TITLE
Add an API to catalog-backend exposing contents of refresh state table.

### PR DESCRIPTION
**Pull request by Xantier**
## Hey, I just made a Pull Request!

 Add an API to catalog-backend exposing contents of refresh state table.

* Exposing additional information to users about their locations for debugging purposes
* Implementing without a UI for now so power users can take advantage of the API directly

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [n/a] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [n/a] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hehe, we had a lot of discussions related to this just yesterday - as a result of https://github.com/backstage/backstage/pull/7208 . We thought that it might be a good idea to expose something like this (instead of using the relations mechanism), but for that use case we wanted to expose the `refresh_state_references` entries going in and out of the entity.

I think your PR is a good start. For our needs we'd have liked it to be centered around an entity, so perhaps `/entities/by-name/:kind/:namespace/:name/internals` or so, and then the returned object could have one key `refresh` that holds some info out of `refresh_state`, one key `references` that shows incoming and outgoing references to other entities by ref. This way we can use the returned info to traverse the hidden internal graph of things. It also makes the returned data more generic and open to extension for more info in the future, and less "hardcoded raw dump" of a table

**Comment by Xantier** [comment]
Yeah, that would make sense to center it around an entity. A lot of the cases we are seeing are something where newly added entities 'just don't show up' since a lot of the errors are made on newly added locations. Would we able to get such information if we would center this info around an entity itself?

**Comment by freben** [comment]
Actually I think that particular case will be well covered by another thing I've been wanting to add for a long time: an (outgoing) event system.

You know we log info in a lot of places in the backend, as things happen. I want to instead (or, also) emit labeled events. For example, completely hand-waved and not thought through at all:

```ts
events.emit({
  type: 'catalog.validation_failed',
  title: 'Failed to validate entity',
  message: 'The field `spec.owner` is missing',
  severity: 'warning',
  labels: {
    locationRef: 'url:https://github.com/x/y/z.yaml',
    locationHost: 'github.com',
    locationOrg: 'x',
    locationRepo: 'y',
    entityRef: 'component:default/my-entity',
    taskId: 'e72397f8-9f5f-421d-a3f2-8d72157dc7bd',
    task: 'catalog.processing_loop',
    impl: 'BuiltinKindsEntityProcessor',
    hostname: 'localhost',
    pid: 12345
  }
})
```

and then most of the decoration is handled by passing things down using an explicit ctx argumnt through the call stacks similar to how golang does it. Eg there's a root ctx that comes from the backend itself with some env info and then as you descend into various processes and functions you amend more granular data onto the context.

The point of all this is, we'd then have a firehose event stream explaining all of the ongoings inside the system. And we could both persist that in the db and make it queryable along ANY label axis and stream it out like we do with scaffolder logs, and we could make it possible to tap into the firehose and emit it to e.g. kafka or cloud logging or whatevever fits your org.

So that's a long way of saying, your use case might be served by the user being able to filter out exactly what's going on _in all ways imaginable_ under their particular org, live.

**Comment by Xantier** [comment]
:+1:

We'll do a separate solution internally for now to continue upkeep our UI to expose catalog processing information and modify to conform these streams when the eventing is added in. Closing this one.

**Pull request closed without merging**
