### PR TITLE
feat(backend-commmon): Change debug color to grey

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

Change the debug log color to make them more easily visible in the console.

| Before | After |
| --- | --- |
| image | image |
| |  image |

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by freben** [comment]
But how does that look with light mode consoles? Insane people are people too! ;)

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4687-kjniqkxpqxwe5ogetybadbgwm45zj158.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6036a36265f8176441f951d5

**Review by freben — APPROVED** [review]

**Comment by adamdmharvey** [comment]
Eh, not too bad?

image

I suppose allowing them to be fully overwritten, maybe from `app-config.yaml`, could be a later refactor?  This ends up making the debug look very similar to the dimmed timestamp.

**Comment by freben** [comment]
Haha nooo, I was just joking :)

**Pull request merged**
