### PR TITLE
fix: scaffolder action catalog:write not working in nested folders

### PR DESCRIPTION
**Pull request by Teo-ShaoWei**
## Hey, I just made a Pull Request!

From the design of `catalog:write`, it is meant to support writing to a nested file path, e.g. `backstage/catalog-info.yaml`.

However, if the directory doesn't exists, then `fs.writeFile` will throw an error. This commit fixed the issue by using `fs.outputFile` instead which will create the parent directory if it does not exist: https://github.com/jprichardson/node-fs-extra/blob/master/docs/outputFile.md

The test `'should support a custom filename'` in `write.test.ts` did not catch this issue because `fs` is mocked. It is better to use fake instead of mock, e.g. create a throwaway temp folder for the tests since the file operations are part of the feature. However fixing of the tests as a whole is out of scope for this PR.

EDIT: updated to reflect the latest code

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
I think it might be worth using `fs.outputFile` instead, as this will create the directory if it doesn't already exist. 

https://github.com/jprichardson/node-fs-extra/blob/master/docs/outputFile.md

**Comment by Teo-ShaoWei** [comment]
Oooh nice it's a TIL for me. Made the change and rebased to the latest master.

**Comment by Teo-ShaoWei** [comment]
@benjdlambert catch your attention again. You might have skipped over the PR as it failed tests previously. Have fixed them accordingly. Let me know if there's any further concern so I can get them resolved 💪 Else I would hope to get this merged into Backstage soon as my company's templating convention relies on this 🙏

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks! :pray:

**Pull request merged**
