### PR TITLE
Added the Readme plugin to the Directory.

### PR DESCRIPTION
**Pull request by fridajac**
## Hey, I just made a Pull Request!

The new Readme plugin has been added to the plugin Directory at backstage.io.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Just something I noticed and some optional feedback:

- On the NPM package page the images are broken for me: https://www.npmjs.com/package/@axis-backstage/plugin-readme
- There are a few `README` card plugins, I know there are ones for GitHub, AzureDevOps, and I think GitLab. Maybe adding where yours has additional benefits would help. Like one unique feature I saw was support for `rst` or 'txt' files

**Comment by awanlin** [comment]
To fix the build failure in the `/microsite` folder run `yarn install` and then `yarn prettier --write .`, that will fix the file. I didn't check what the issue is but what I suggest here will fix it 👍

**Comment by awanlin** [comment]
Just need another approval so we can merge @freben @tudi2d

**Review by tudi2d — APPROVED** [review]
let's go!

**Pull request merged**
