### PR TITLE
Added agent in RouterOptions to enable setting http agent in proxy

### PR DESCRIPTION
**Pull request by jboeijenga**
## Hey, I just made a Pull Request!

We run Backstage behind a corporate proxy. Some of the services we incorporate run behind the proxy as well and some services, like OpsGenie, are SaaS and run outside our network. The connection to these services needs to got through the corporate proxy.

The OpsGenie plugin we use, requires the http-proxy-middleware plugin proxy for their traffic:
https://github.com/K-Phoen/backstage-plugin-opsgenie/blob/master/docs/setup.md
To configure this correctly we need provide a custom `http.agent`:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/corporate-proxy.md
This pull request allows the user to configure a custom agent in the consuming application and provide this as configuration to the plugin-proxy-backend like:
```
import { createRouter } from '@backstage/plugin-proxy-backend';

import { Router } from 'express';
import { ProxyAgent } from 'proxy-agent';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const agent = new ProxyAgent();

  return await createRouter({
    logger: env.logger,
    config: env.config,
    discovery: env.discovery,
    agent,
  });
}
```

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — APPROVED** [review]
nice! 🚀

**Comment by freben** [comment]
Hm. Is there no hope of making it a better type than `any`?

**Comment by jboeijenga** [comment]
@freben 

That was what I was hoping for as well. But the internal typing of `agent` in http-proxy-middleware is any so I decided to stay compatible with that.

It's possible to strongly type it to http.Agent though..

```
import http from 'http';
...
export interface RouterOptions {
  logger: Logger;
  config: Config;
  discovery: PluginEndpointDiscovery;
  skipInvalidProxies?: boolean;
  reviveConsumedRequestBodies?: boolean;
  agent?: http.Agent;
}
```

Please let me know what you think of this!

**Comment by jboeijenga** [comment]
@freben Any reaction to my comment?

**Comment by benjdlambert** [comment]
Hey :wave: before we move forward with this, are these docs not enough to get this working without creating additions to the API?

https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md

**Comment by jboeijenga** [comment]
@benjdlambert: I tried setting global-agent for my application, however when I do this my authentication flow ends-up in a 403. Is this a familiar issue? If we could go ahead with successfully setting the global-agent we can close this MR for sure

**Comment by benjdlambert** [comment]
@jboeijenga is it possible that some requests are going through the proxy that shouldn't? Can you find some more information about what is calling that 403 and why? And what endpoint it's hitting and add it to the `NO_PROXY` env or something to test?

**Comment by jboeijenga** [comment]
@benjdlambert I took another look at my global-agent no_proxy configuration and got it to work. Thanks for the suggestion, I'll close this MR

**Comment by benjdlambert** [comment]
@jboeijenga great to hear! Thanks! :tada:

**Pull request closed without merging**
