### PR TITLE
chore(docs): Replace deprecated imports

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

One of my colleagues @tcnaganath noticed that we still had collators imported from deprecated imports, and at first we had some challenges figuring that out.  This fixes the Search TechDocs How To which currently suggests users to use the same deprecated imports, and replaces them with the new imports. (turns out the deprecated imports anyway just export the new ones)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @adamdmharvey, this is a sidebar but wanted to share: you can use `yarn backstage-cli repo list-deprecations` to list out all the deprecations. We have this run in our CI to catch these and we also have the Demo site doing the same. Here's an example of that: https://github.com/backstage/demo/actions/runs/4961279165/jobs/8877870734#step:9:10. We keep up with the `next` release line and so far have not run into this being a problem where we could not fix the deprecations to get the CI going

**Review by awanlin — APPROVED** [review]
LGTM! 🚀

**Comment by adamdmharvey** [comment]
bump so doesn't go stale :)

**Review by pjungermann — APPROVED** [review]

**Comment by adamdmharvey** [comment]
Bump

**Comment by adamdmharvey** [comment]
Bump

**Comment by adamdmharvey** [comment]
May have hit the summer holidays on this one :) 🏖️ @emmaindal not sure since you're a member of this CODEOWNER team if you'd be able to take a peek?  thx!

**Comment by adamdmharvey** [comment]
Bump on this one, one more time 😁

**Comment by awanlin** [comment]
Sorry to ping you but any chance you can help with this @Rugvip or @benjdlambert, it's just documentation corrections but having a hard time getting the final approval :(

**Review by freben — APPROVED** [review]
Sure! I can merge this.

**Pull request merged**
