### PR TITLE
Auth0 provider type is incompatible with SignInPage#providers prop

### PR DESCRIPTION
**Pull request by taras**
## Hey, I just made a Pull Request!

I'm trying to use Auth0 provider for authentication. It works at runtime but fails when I run `yarn tsc` because of the following error:

image

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by Rugvip** [comment]
@taras How do you intend to implement the full sign-in flow? As in how would the profile received from auth0 actually be connected to a useful identity in the auth backend?

Thinking around auth with both `Auth0Auth` and the generic `OAuth2` provider is that they may serve better as classes exposed to implement concrete auth flows, kind of like some of the other providers are now implemented with the `OAuth2` one internally. The issue is that there's no real contract between the app and plugins that use the `auth0` provider and it would make more sense to e.g. use `Auth0Auth` as a possible implementation of Google auth.

It ends up being slightly different for sign-in, where you instead need a contract in the backend that is able to map whatever profile you get as part of sign-in, to a user entity in backstage, i.e. `BackstageIdentity`. So what I'm thinking we'd want to do in the case of using `Auth0` for identity is to just export the `Auth0Provider` class from the `auth-backend` and allow it to be hooked up with a custom profile -> identity mapping. In the app you'd then create a custom `ApiRef` for that custom identity flow, and the add it to the app and use as the sign-in provider.

... after typing out the above, I realized that `Auth0Auth` is just a tiny wrapper around `OAuth2`, so I think we should just remove it altogether.

**Comment by taras** [comment]
> As in how would the profile received from auth0 actually be connected to a useful identity in the auth backend?

The identities that Auth0 provides are not complete but they are complete enough on their own. Auth0 can be an identity store itself and allows storing metadata. In that sense, it can server a backend itself. 

Whats not very clear is how to extend an `OAuth2` provider to retrieve user specific data. If you can give me some direction on how I could convert the "incompatible" provide into a proper provider then I can write up a tutorial.

**Comment by Rugvip** [comment]
@taras The goal of the sign-in providers, and along with that the implementers of the `BackstageIdentityApi` interface, is to tie a user identity from an external system to a user identity within Backstage. The goal is to have the Backstage user identities be part of the catalog, but that's not in place yet.

The place where the two identities are tied together is inside the provider in the auth backend, e.g. https://github.com/spotify/backstage/blob/6f2d720a416833f82bed9d804b5d62efff1f7b00/plugins/auth-backend/src/providers/google/provider.ts#L142. As you can see that's a very basic implementation and needs to be extended to properly look up user entities in the catalog, most likely matching by email.

A generic auth0 implementation could take the profile email or some form of user ID and try to match it to users in the catalog, but most likely the logic that ties the two together needs to be custom. Although tbh that logic doesn't necessarily need to reside in the auth provider, it can also be a mapping to the correct annotations when user entities are ingested into the catalog. Either way the intention is that most of the user data resides in the user entity itself, with the auth provider just tying things together.

The tricky bit is that there's a bit of a chain required to enable this, #1847, #1401, #2001, and #1964 all have to be somewhat settled, along with #1807 or similar to have some concrete use-case to work with.

If you have ideas for the way forward, perhaps some shortcuts, shoot! In general the sign-in page is a bit useless until we can get these pieces in place.

**Comment by benjdlambert** [comment]
@taras I think there was some discussion on discord around this, do you mind updating this ticket with the feedback from there and any other info?

**Comment by Rugvip** [comment]
Gonna close as this was fixed in #2555

**Pull request closed without merging**
