### PR TITLE
add how to section for using other mkdocs plugins

### PR DESCRIPTION
**Pull request by agentbellnorm**
## Hey, I just made a Pull Request!

Adding some guidance on how to use other mkdocs plugins besides the ones provided by `mkdocs-techdocs-core`. We get a lot of PR:s wanting to add plugins to the set of plugins provided by the core, but that's not really viable.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
This is really great, thanks @agentbellnorm 🚀

**Review by pjungermann — APPROVED** [review]

**Review by squid-ney — APPROVED** [review]

**Comment by awanlin** [comment]
Hi @Rugvip, @freben, this didn't get tagged with a core maintainer, any chance you can give this a quick look and a merge? This is really helpful and would be great to have in place

**Comment by awanlin** [comment]
@agentbellnorm, looks like a conflict crept in, can you fix that, please?

**Comment by awanlin** [comment]
@agentbellnorm this is a great addition and would be great to see this merged in, any chance you can fix the conflict?

**Review by Rugvip — APPROVED** [review]

**Comment by awanlin** [comment]
Thanks @Rugvip this is hugely helpful for the community using TechDocs, thanks for getting this merged! 🚀

**Pull request merged**
