### PR TITLE
Implement `NextCatalogBuilder.addEntityProvider`

### PR DESCRIPTION
**Pull request by freben**

### CODE REVIEW

**Review by jhaals — APPROVED** [review]
🥇

**Comment by benjdlambert** [comment]
Can we have some tests for this? Particularly the replacing by name part?

**Comment by freben** [comment]
Hmm the entire builder is untested right now and maybe takes a fair bit of mocking ... I could try

**Review by Rugvip — APPROVED** [review]
:shipit:, with or without tests :grin:

**Comment by freben** [comment]
Yyyeah looked at it a bit and short of breaking out the merging function - which will be very low value - it's pretty damn opaque right now. Given the discussion that we might choose to break this builder apart completely later, will hold off on the test

**Pull request merged**
