### PR TITLE
core: implement optional external routes and use to toggle "Create Component" button

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Adds support for

```tsx
const myRouteRef = createExternalRouteRef({ id: 'my-ref', optional: true })

// ...

const MyComponent = () => {
  const myLink = useRouteRef(myRouteRef)
  if (myLink) {
    return <a href={myLink()}>Link</a>
  } else {
    return <span>No link :( </span>
  }
}
```

+ optional "Create Component" button!

out

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4700-ganv3xteolgfatzdojfhyjsf5ysti7q6.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037d920fcb22dbc446075c8

**Review by freben — APPROVED** [review]
Yep. Dat TS wizardry doe. Almost wondering if it would fit to be placed in a separate typeUtils.ts just to not pollute the main concerns (and "hide" the inner util-utils)

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4700-ganv3xteolgfatzdojfhyjsf5ysti7q6.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037d920fcb22dbc446075c8

**Comment by Fox32** [comment]
Very nice, I like that. 

I guess I have to resolve some conflicts in #4628 afterwards 😆

**Pull request merged**
