### PR TITLE
Update dependency rollup to v4

### PR DESCRIPTION
**Pull request by szubster**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by yedidyar-ni** [comment]
WOW thanks very much for your effort💪

**Comment by szubster** [comment]
I need to figure out what is wrong with e2e...

**Review by yedidyar-ni — APPROVED** [review]
Thanks I really needed it to my project

**Comment by szubster** [comment]
Rebasing, to restart tests. Seem to be flakiness.

**Comment by yedidyar-ni** [comment]
Is it pass now?

**Comment by yedidyar-ni** [comment]
> Rebasing, to restart tests. Seem to be flakiness.
LMK if you need any help🤓

**Comment by szubster** [comment]
All tests pass. Just need review from maintainers now :)

**Comment by freben** [comment]
This may be best for after the mainline release. Pinging @benjdlambert and @Rugvip on this too

**Pull request merged**
