### PR TITLE
Moved Storybook from package to root of the project

### PR DESCRIPTION
**Pull request by snehaljos**
## Hey, I just made a Pull Request!

Moved the `storybook` folder from the `package` to the `backstage` directory.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Great work thanks for this! I think there's some workflows that we're going to need to update now. So maybe look for `packages/storybook` in the `.github` workflows, and adjust the paths. You'll also probably need to add an additional step also, which would be to run a `yarn install` inside that directory too now as the `storybook` packages will not longer be in installed part of the default flow.

There should hopefully also now be no more `storybook` dependencies in the `yarn.lock` so you should be able to commit the updated `yarn.lock` too and and extra `yarn.lock` inside the `storybook` directory=.

**Review by snehaljos — COMMENTED** [review]
Updated the action files

**Comment by freben** [comment]
This needs a rebase and still has some issues, it seems.

**Comment by Rugvip** [comment]
Merged as part of #9089

**Pull request closed without merging**
