### PR TITLE
Changed IdentityClient to DefaultIdentityClient in Permissions Docs

### PR DESCRIPTION
**Pull request by Parsifal-M**
Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>

## Hey, I just made a Pull Request!

I changed the `IdentityApi` to `DefaultIdentityClient` as I believe in the docs (after following it) it doesn't seem to work if you use `IdentityApi` and I only got it to work using `DefaultIdentityClient`

If I am mistaken, then I apologize and we can close this :+1: 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Parsifal-M** [comment]
Just noticed I missed a bit further down 😕, will correct this and come back 👍

**Comment by awanlin** [comment]
@Parsifal-M are you sure this is correct for the latest version - 1.6.0? I just made some of these changes to correct them: https://github.com/backstage/backstage/pull/13654

**Comment by awanlin** [comment]
The release notes on this I think are not super clear and I can't seem to link to them directly: https://github.com/backstage/backstage/blob/master/docs/releases/v1.6.0-changelog.md#patch-changes-36, if you scroll down from this linked section you should see it

**Comment by Parsifal-M** [comment]
> @Parsifal-M are you sure this is correct for the latest version - 1.6.0? I just made some of these changes to correct them: #13654
> 
> But looking at our code I missed that `import { IdentityClient } from '@backstage/plugin-auth-node';` is not needed anymore so that can get pulled out :(

Hey @awanlin :wave:, you are absolutely right on this, let me correct that, sorry it took me a moment to find what you meant :smile: in permissions.ts you don't need to import `DefaultIdentityClient` and can leave `identity` as `identity: env.identity` right? this is what you are referring to?

**Comment by Parsifal-M** [comment]
Hey, I followed the documentation with the latest version of Backstage as @awanlin mentioned and It was my fault for using an older version.

In 1.6.0 you do not face any issues when following the docs :+1: 

I will close this as its not needed.

Thanks!

**Comment by awanlin** [comment]
Hi @Parsifal-M, thanks for double checking sorry that this wasn't clear around the assumption that you should be on the latest version, totally fair. I would have done the same thing

**Pull request closed without merging**
