### PR TITLE
fix: retry directory removal 

### PR DESCRIPTION
**Pull request by ourchitectureio**
This adds support to retry directory removal in case the file system is busy.

Node "fs" ships with support for directory removal retries:
<https://nodejs.org/api/fs.html#fspromisesrmdirpath-options>

And, "fs-extra" also ships with support for file removal retries with `fs.rm(...)`.

However, "fs-extra" directory removal with `fs.remove(...)` does not.

Signed-off-by: Eric Swanson <ericis@users.noreply.github.com>

### CODE REVIEW

**Review by jhaals — CHANGES_REQUESTED** [review]
Hi!

Thanks for the suggestions!

I'm interested to know more about the reasoning for adding retries for these file system operations. Is there some issue that you run into or that someone else reported that you can refer to?

This PR also suggests adding a makefile and updates the contribution guide. I don't think we want to go proceed with that change as it's primarily wrapping `yarn` which is our make equivalent in this project. It's recommended to separate multiple suggestions into separate PRs to make discussions easier

**Comment by Rugvip** [comment]
QQ: could we switch these to `.rm` and use the built-in retries instead?

**Comment by ericis** [comment]
> Hi!
> 
> Thanks for the suggestions!
> 
> I'm interested to know more about the reasoning for adding retries for these file system operations. Is there some issue that you run into or that someone else reported that you can refer to?
> 
> This PR also suggests adding a makefile and updates the contribution guide. I don't think we want to go proceed with that change as it's primarily wrapping `yarn` which is our make equivalent in this project. It's recommended to separate multiple suggestions into separate PRs to make discussions easier

Thank you for the feedback.

Yes, on Windows my development team is getting "EBUSY: resource busy or locked" errors during backend builds that bundle the frontend. We could reproduce it on every build. We traced the errors to this line of code: https://github.com/backstage/backstage/blob/e7ce581513864aa32443e24fbeb84c11b34d704c/packages/cli/src/commands/build/buildBackend.ts#L83

We edited that line of code to use the retry logic and it worked, so I reviewed the codebase for every direct use of directory deletion rather than only fixing this one area.

**Comment by ericis** [comment]
> QQ: could we switch these to `.rm` and use the built-in retries instead?

Possibly. It seems so.

- [fs-extra `remove`](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/remove.md)
- [fs `rm`](https://nodejs.org/api/fs.html#fspromisesrmpath-options)

The `rm` behavior from "fs" will need to be tested:

- Missing directories *this "should" work if it works like POSIX `rm` by ignoring them
- Empty directories *this "should" work if it works like POSIX `rm`
- Recursion *documented and "should" work if it works like POSIX `rm`

**Comment by acierto** [comment]
Hey, @ourchitectureio, will you have time to incorporate suggestions given above? 🙏

**Pull request closed without merging**
