### PR TITLE
Add Firebase Functions plugin integration

### PR DESCRIPTION
**Pull request by mcalus3**
## Add Firebase Functions plugin integration

- Adds a widget to component overwiew that shows function details.
- Adds a new firebase functions plugin tab.

Screenshot_2020-10-01 sample-service Overview Backstage
Screenshot_2020-10-01 sample-service Firebase Functions Backstage

https://www.loom.com/share/459eb92d9d3e4d1ea650ae3397bfffd2

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated (none in this case)
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Wonder if it makes sense to add a marketplace entry for this plugin too similar to https://github.com/spotify/backstage/pull/2692/files @alund?

**Review by stefanalund — CHANGES_REQUESTED** [review]
I actually think this is a pretty niche use-case that shouldn't be part of the example app. 

If people want to install it to their own Backstage installations, they should find it through the [Plugin Marketplace](https://backstage.io/plugins).

@dtuite may want to chip in.

**Comment by benjdlambert** [comment]
@stefanalund (right tag this time) raises a valid point. Maybe it would be best served as a plugin in the marketplace with clear instructions on how to bring it in your version of backstage

**Comment by dtuite** [comment]
@stefanalund Not having it in the example app is fine. Not everyone will use firebase functions.

The use case here is to support teams who deploy their Backstage components using Firebase Functions. If you deploy your components to Kubernetes then it is useful to see the deployments in the Backstage Kubernetes plugin. Same thing for Firebase Functions.

It will only be useful to teams who use firebase functions, but that applies to any plugin which wraps a third-party tool.

**Comment by mcalus3** [comment]
Submitted a separate PR with plugin marketplace entry for this plugin: https://github.com/spotify/backstage/pull/2696

**Comment by stefanalund** [comment]
@dtuite thanks for the clarification. I would suggest adding that additional context to the plugin documentation.

@mcalus3 great, reviewed and merged!

Closing this PR then.

**Pull request closed without merging**
