### PR TITLE
fix: annotations

### PR DESCRIPTION
**Pull request by markussiebert**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Rugvip** [comment]
Thank you! 👍 Gonna mark this as ready for review as it looks like that's the case. Heads up that this will need a changeset though, see https://github.com/backstage/backstage/pull/23298#issuecomment-1967543140 for details on that

**Comment by markussiebert** [comment]
will finish this soon and will create changeset

**Review by Edje-C — COMMENTED** [review]
Can you leave a description explaining these changes and why you feel they're needed?

**Comment by markussiebert** [comment]
sorry - I am a gitlab guy - sometimes struggling with the github workflow... but this would fix #23387

**Pull request closed without merging**
