### PR TITLE
Fix typo in devtools plugin readme

### PR DESCRIPTION
**Pull request by tomasmota**

### CODE REVIEW

**Review by adamdmharvey — APPROVED** [review]

**Comment by adamdmharvey** [comment]
(Odd e2e test error; just re-ran it in case it may go clean, but may require a rebase off main. Let's see what it does!)

**Comment by tomasmota** [comment]
Thanks @awanlin, I had in fact not installed :D 

Hope it looks right now.

**Review by Rugvip — APPROVED** [review]
Nice, thanks! 👍

**Review by awanlin — APPROVED** [review]
LGTM! 🚀

**Comment by awanlin** [comment]
@Rugvip good to merge now 👍

**Comment by awanlin** [comment]
Thanks again for this fix @tomasmota 🚀

**Pull request merged**
