### PR TITLE
Added Remove Button Near To Edit Button In Shortcut Items On hover Three Dots Icon

### PR DESCRIPTION
**Pull request by AmbrishRamachandiran**
## Hey, I just made a Pull Request!

When a user uses the Add Shortcut button to create several shortcuts, a list will be created; however, under the current functionality, a user must first click on Edit before they may delete a shortcut.
So placed the remove button and edit button close on hover on the Three dots icon so that users can quickly remove the shortcut.

This PR is for https://github.com/backstage/backstage/pull/18726

image

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by AmbrishRamachandiran** [comment]
@Rugvip @freben @benjdlambert  This PR changes are done as per your suggestion in https://github.com/backstage/backstage/pull/18726

image

ISSUE LINK :  https://github.com/backstage/backstage/issues/18706

**Comment by AmbrishRamachandiran** [comment]
@Rugvip Please review and let me know if any changes required

**Comment by AmbrishRamachandiran** [comment]
@freben @ahhhndre can also take a look , improved it as per your suggestions

**Review by Rugvip — CHANGES_REQUESTED** [review]
Sorry I don't feel that this is an improvement. The edit action is now 3 clicks away, and the delete action I feel is already quite accessible as is, in fact that didn't really change much.

**Comment by AmbrishRamachandiran** [comment]
> Sorry I don't feel that this is an improvement. The edit action is now 3 clicks away, and the delete action I feel is already quite accessible as is, in fact that didn't really change much.

Previously i kept it near edit button
image

 but as per maintainer @freben  suggestion implemented in this way and i  haven't removed delete action in editform also so there are now two ways to delete the shortcuts.
 
 
image

**Comment by AmbrishRamachandiran** [comment]
@freben can you please take a look implemented as per your suggestions 
FYI @ahhhndre @benjdlambert

**Comment by Rugvip** [comment]
@AmbrishRamachandiran we discussed this a bit in the maintainer team and settled on keeping the sidebar item buttons as they are, but that it would be helpful to change the color of the "Remove" button to red, like you do here.

**Comment by AmbrishRamachandiran** [comment]
> @AmbrishRamachandiran we discussed this a bit in the maintainer team and settled on keeping the sidebar item buttons as they are, but that it would be helpful to change the color of the "Remove" button to red, like you do here.

@Rugvip color changes added for delete icon please review

**Comment by Rugvip** [comment]
Oh sorry, got myself confused because I was comparing to an older version of Backstage. The remove button is actually already red.

Sorry but that leaves nothing to be done at this point so I'm going to close this PR. We're happy with the way the shortcuts are styled already and aren't looking to make any changes. The vertical `...` menu icon might've made sense in some other context but since the items themselves might have trailing `...` it looks very confusing. The popup menu is also good as is, no need to add an intermediate menu.

**Pull request closed without merging**
