### PR TITLE
Add option to truncate title to bar chart tooltips

### PR DESCRIPTION
**Pull request by brendasukh**
## Hey, I just made a Pull Request!
Fixes issue where there's no way to see the full id for entities with looong names. This mainly surfaces in alerts, where there's no breakdown modal (unlike the product panels) where we surface the full name. The solution here is to add an optional `truncateTitle` prop to bar chart tooltips which defaults to false. We should only truncate in the tooltip if there's an alternate way to view the full name (i.e. product panels for entities w/ sub-entities).

Alternate
Also considered making it so that alerts could have a breakdown modal similar to product panels, but decided against it since we wouldn't actually be surfacing any extra information other than the full entity name. 
**Before** 
Screen Shot 2021-02-10 at 3 11 11 PM

**Long title - no cost indicator or entity breakdown** 
Screen Shot 2021-02-10 at 3 49 46 PM

**Long title - w/ cost indicator + entity breakdown**
Screen Shot 2021-02-10 at 3 50 08 PM

**Long title - w/ cost indicator, no entity breakdown**
Screen Shot 2021-02-10 at 3 50 00 PM

**Normal title - no cost indicator or entity breakdown** 
Screen Shot 2021-02-10 at 3 51 55 PM

**Normal title - w/ cost indicator + entity breakdown**
Screen Shot 2021-02-10 at 3 52 07 PM

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4477-6zavah4wdpfy09tg4oikrna4sbxstka9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6024496a98552d34125c2d2b

**Comment by ryanvazquez** [comment]
My three and a half cents: I think the tooltip is somewhat limited in its ability to handle this problem given its current implementation - a small, fixed width component that renders dynamic content and multiple child components.

Ideally, implementors should be spared this level of granularity - the component really should gracefully handle whatever content its given without any configuration or breaking the uniformity of the UI - which is difficult to do currently. As it is now, it's not even entirely clear to users that clicking on an entity with a breakdown modal _will_ show them the full id - they just find that out after the fact. 

In the case of our default alerts, where users are not able to configure the tooltip (and don't render modals), we would be disabling truncation by default - which may or may not make sense for an implementor depending on the nature of their entity ids. Internally, entity ids can get up to around 50 chars long, longer than in the above examples, which currently wrap around 4x :(  In an effort to improve the experience of some users, we could break it for others.

Enabling truncation also doesn't help completely either - in some cases a tooltip that truncates the id displays _less_ content than the chart label does, which makes rendering it somewhat pointless. 

I feel like we shouldn't double down on the entity-id-in-tooltip approach if it isn't really working.

**Comment by adamdmharvey** [comment]
Very similar to this
https://github.com/backstage/backstage/pull/4372

**Comment by ryanvazquez** [comment]
@adamdmharvey Ah, thanks. I think we could do something similar. Since chart labels already truncate entity ids - we could remove ids from the chart tooltip and add a MUI tooltip (without a max width) to the labels which display the full id on hover. Something roughly along the lines of:

Screen Shot 2021-02-10 at 9 21 45 PM

**Comment by kiranpatel11** [comment]
@ryanvazquez PR #4372 does include reusable component OverflowTooltip, that truncates longer text and shows tooltip.

**Comment by brendasukh** [comment]
hmm, yeah I'm a bit torn. I think the main issue is that we don't currently link users to the actual entity (unlike in [#4372](https://github.com/backstage/backstage/pull/4372)), so what we display in the tooltip is the entirety of the information the user gets about that entity. 
If we remove the title from the tooltip, the user has to navigate to the bar to see cost data (+ contextual data such as retention suggestions for our data endpoint alerts). If they want to see which entity those costs map to (in the case of long entity names), they have to hover over the label and lose access to the contextual data. As an end-user, I'd prefer a bulkier tooltip that contains all the information I need over that extra step, especially if I'm looking at several looong entities that are very similar in name. 

I think the long-term solution is to re-think the tooltip completely. The tooltip worked for our initial implementation for product panels, but it feels like we've outgrown it now that we're already squeezing quite a bit of information in there (cost data, breakdown data, change indicator, alert suggestions). Something similar to the entity breakdown modal could work ? It would allow users to easily copy/paste the entity name, cost and other contextual information.

**Comment by timbonicus** [comment]
I agree that removing the entity name from the tooltip isn't ideal, then you have two tooltips to cross-reference to get a full picture.

We could try to shrink the text when it's super long (e.g. with [variable fonts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide)) to avoid excessive wrapping.

It does seem like we're pushing a bit too much into the tooltip; I would argue for removing the change indicator - at the risk of only band-aiding the problem, I don't think this is super useful when the bar chart visualization gives you a visual approximation of the same ratio.

Perhaps reclaiming that change indicator space + adjusting font size is enough to make this palatable. Or we could always marquee-scroll the entity name across the tooltip 😂

**Comment by ryanvazquez** [comment]
Dualing tooltips isn't optimal but it seems like there is an emerging precedent for pairing text truncation with tooltip in Backstage writ large. It'd be bit jarring for users to see this fairly common behavior implemented differently across plugins.

**Comment by ryanvazquez** [comment]
Variable font size I think is best suited for content that's fixed in size but needs to scale up/down depending on the viewport, like how plugin titles scale currently. If we did implement it, we could still end up in an even uglier scenario where text content is very small and also wraps around, which users could find just as unpalatable. 

I'm feel strongly that we should lead with whatever precedent Backstage sets, and then work around whatever limitations come from that, rather than trying to work around the limitations of our own implementation.

**Comment by brendasukh** [comment]
Closing since we no longer have an internal need for this change and since we also have re-design work planned in the near future :)

**Pull request closed without merging**
