### PR TITLE
Realign Template schema (parameters > input)

### LINKED ISSUE #5586: The `Template` `v1beta2` schema doesn't match the implementation
The [Scaffolder documentation](https://backstage.io/docs/features/software-templates/writing-templates) gives the following examples (note the `$.spec.steps.input` property):

```yaml
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: v1beta2-demo
  title: Test Action template
  description: scaffolder v1beta2 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
  - title: Fill in some steps
    # ...

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:cookiecutter
    input:
      url: ./template
      values:
        name: '{{ parameters.name }}'
        owner: '{{ parameters.owner }}'
```

However, the schema of the `Template` entity, doesn't contain an `input` field, but instead specifies `$.spec.steps.parameters`:

https://github.com/backstage/backstage/blob/4ac335883bef655e4e6f97af5c923ffac1e8f9e5/packages/catalog-model/src/kinds/TemplateEntityV1beta2.ts#L41

https://github.com/backstage/backstage/blob/4ac335883bef655e4e6f97af5c923ffac1e8f9e5/packages/catalog-model/src/schema/kinds/Template.v1beta2.schema.json#L128-L131

Since `input` is the one that is also used in the implementation, the schema should be fixed so the entity validation works correctly.

### PR DESCRIPTION
**Pull request by julian-mp**
Signed-off-by: Julian Pearce <git@julian.mp>

## Hey, I just made a Pull Request!

Resolves #5586 

#### :heavy_check_mark: Checklist

- [☑️] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [☑️] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @julian-mp,

Looks like you need to regenerate the new API docs. 

If you look in the log lines you can see the following:
```
*************************************************************************************
* You have uncommitted changes to the public API of a package.                      *
* To solve this, run `yarn build:api-reports` and commit all api-report.md changes. *
*************************************************************************************
```

**Comment by julian-mp** [comment]
thanks, @benjdlambert! I've regenerated the new API docs, just need the approval to run the workflows

**Review by jhaals — APPROVED** [review]
Looking good 👍

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks!

**Pull request merged**
