### PR TITLE
Implement auth handler and sign-in resolvers for okta

### PR DESCRIPTION
**Pull request by Symbianx**
## Hey, I just made a Pull Request!

Implement auth handler and sign-in resolvers for Okta auth providers, as described in #6245

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Tests for new functionality and regression tests for bug fixes
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
LGTM, but @Rugvip will have final say

**Comment by Symbianx** [comment]
@freben thanks, I ran the command and added the file change. I'm not sure if I should do something about the generated warning.

**Comment by freben** [comment]
No, those are fine - we haven't started addressing those at a larger scale yet so it's fine to hold off on that. However, it seems you forgot to DCO sign your commit.

**Comment by Symbianx** [comment]
Oops, should be good now 👍

**Comment by Symbianx** [comment]
I'm not sure what's causing prettier to fail in CI. I can not reproduce the prettier check error by running `yarn prettier:check`.

Any pointers on what could be causing this?

**Review by Rugvip — APPROVED** [review]
Thank you, looks good! 👍 :shipit: 

Prettier issues should be fixed by bringing in latest changes from master, running `yarn install`, and then running prettier

**Comment by Symbianx** [comment]
Alright, rebased and ran prettier. 
Should be good to go now

**Comment by freben** [comment]
@tomwwright Releases usually happen Thursdays, during Europe business hours. So you're in luck!

**Comment by regicsolutions** [comment]
@Symbianx assuming this Okta handler only supports OAuth2 and not SAML?

**Pull request merged**
