### PR TITLE
Condense Kubernetes UI plugin components to fit more on screen

### PR DESCRIPTION
**Pull request by dmckernanacv**
## Hey, I just made a Pull Request!

Changes: `plugins/kubernetes`
* Removes `Grid` components when `groupedResponse` does not contain relevant items.
* Removes empty rows when `Table` page contains fewer rows than requested page-length.
* Gives Pod Table rows a unique id (uuid).
* Modifies components in order to condense the UI, and add more visual distinction between Resource types:
  * Updates all `Accordion` components to use the 'outlined' variant (except Cluster), making the grouping stand out more when nested. 
  * Updates all `Drawer` components to use 'body1' typography for the Resource name and 'subtitle1' typography for the Resource type, to be more condensed within the UI for instances with a larger base font-size. 
  * Updates all `Accordion` headers to remove unnecessary `Divider` between Resource info and Resource detail summary.
  * Expands `Accordion` header `Grid` items to utilize more space when `Grid` content is likely to be long (Resource names). Removes spacing on `Grid` in `Accordion` header to further reduce used space.

### Screenshots
Screenshot 2023-01-24 at 10 36 36 AM
Screenshot 2023-01-24 at 10 37 02 AM
Screenshot 2023-01-24 at 10 37 12 AM
Screenshot 2023-01-24 at 10 37 21 AM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by mclarke47 — APPROVED** [review]
looks great! Thank you!

**Comment by dmckernanacv** [comment]
@mclarke47 had to fix a missing sign-off, could you 👍 again? 🙇

**Comment by mclarke47** [comment]
@dmckernanacv I think you've changed something as this is now changing 315 files?

**Comment by dmckernanacv** [comment]
Hmm... I'm not sure what happened.... it looks like [this commit](https://github.com/backstage/backstage/pull/15920/commits/d8928ed2caac2296abe7790adddd0e68ac98b455) came from github-actions[bot]? 

I'm not entirely familiar with the backstage workflows, I did have to force push to get a commit signed...

**Comment by dmckernanacv** [comment]
@mclarke47 all fixed, sorry about that

**Review by benjdlambert — COMMENTED** [review]
Thanks for this :pray: nice work!

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
