### PR TITLE
Score-card plugin integrated to example-app

### PR DESCRIPTION
**Pull request by jvilimek**
## Hey, I just made a Pull Request!

I have prepared integration of Score Card plugin to backstage. It's something I have developed to support our system scoring review process in Oriflame. Previous version was integrated to backstage repo (#12488), this version is just about sample app + plugin is [elsewhere](https://github.com/Oriflame/backstage-plugins/tree/main/plugins/score-card).

In Backstage there is this Score board (overview of all reviews):

image

and also a detailed review for each system:

image

You may drill down to the details of each score together with explanation why it has such score & also a TODO for the team:

image

There is also a process suggested how to do the reviews

- self assessment in the SharePoint (script to create the list fields based on template is part of the PR)
- review with an architect
- integration with the git & storage account via Azure DevOps pipelines (part of the PR)
- visualization in the Backstage

More information you can see in [README](https://github.com/Oriflame/backstage-plugins/tree/main/plugins/score-card).

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jvilimek** [comment]
test on node.js 14 failed because of `Failed to connect to the database to make sure that 'backstage_plugin_dbb245ae6508a5072406e7f2cc4d4ed1c5' exists, KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`  ...needs retry I guess?

**Comment by freben** [comment]
Hi! Just noting in passing-by that this has merge conflicts. The retriggered builds worked though!

**Comment by jvilimek** [comment]
> Hi! Just noting in passing-by that this has merge conflicts. The retriggered builds worked though!

I know. It was created few days back. Before merging I wanted to have at least confirmed with you this PR is OK. But anyway I have merged the yarn.lock file now, so .. let's see how long this branch lasts without conflicts

**Review by Rugvip — APPROVED** [review]
Thank you, let's :shipit:!

Bit of a heads up that we may temporarily comment out any of the external plugins if they end up breaking the example app. It would typically happen if we've got some form of migration happening and we want to get the example app moved over sooner rather than later.

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻

**Comment by jvilimek** [comment]
> Thank you, let's :shipit:!
> 
> Bit of a heads up that we may temporarily comment out any of the external plugins if they end up breaking the example app. It would typically happen if we've got some form of migration happening and we want to get the example app moved over sooner rather than later.

Thanks for accepting the change. Do I understand right that this will be part of the 1.7 version? How this will be "announced"? I mean will this be in the release notes? I guess not as the changeset I have created was not accepted by some github action so I have to [remove](https://github.com/backstage/backstage/pull/13847/commits/a2c7a91f5640c08e83731a7c130a7679ade20814) it.

**Pull request merged**
