### PR TITLE
Fixes #25954 Replace postcss rollup plugin with styles plugin

### LINKED ISSUE #25954: 🐛 Bug Report: Possibly wrong import path in plugin dist files when using both css and svg
### 📜 Description

We've noticed that the import path for an imported svg file in the `dist` output of `yarn build` is relative to the source code tree and not the dist tree when importing both a `css` and `svg`. As a result the svg is not found when using the plugin in a front-end app.

### 👍 Expected behavior

If we define (and export) the following React component from a plugin that uses an `svg` file within the same directory:
```
import React from 'react';
import logo from './logo.svg';

export function Example(): JSX.Element {
    return (
        <div>
            <img src={logo} />
        </div>
    );
}
```
upon `yarn build`, the file looks like:
```
import React from 'react';
import logo from './logo.svg';

function Example() {
  return /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("img", { src: logo }));
}

export { Example };
//# sourceMappingURL=ExamplePage.esm.js.map
```
**(note the path of the relative import for `logo`)**

### 👎 Actual Behavior with Screenshots

Instead, if the React component includes both a `css` and `svg` like such:
```
import React from 'react';
import logo from './logo.svg';
import styles from './Example.css';

export function Example(): JSX.Element {
    return (
        <div className={styles.NoMargin}>
            <img src={logo} />
        </div>
    );
}
```
the compiled file in the `dist` directory is instead:
```
import React from 'react';
import logo from '../../plugins/example/src/components/ExamplePage/logo.svg';
import css_248z from './Example.css.esm.js';

function Example() {
  return /* @__PURE__ */ React.createElement("div", { className: css_248z.NoMargin }, /* @__PURE__ */ React.createElement("img", { src: logo }));
}

export { Example };
//# sourceMappingURL=ExamplePage.esm.js.map
```
**(note the relative directory for the `logo` import).**

### 👟 Reproduction steps

1. In a plugin, create a simple React component as above, export the component from the plugin
2. Run `yarn build`
3. Observe the import path in the compiled file in the `dist` directory.

### 📃 Provide the context for the Bug.

This was against 1.28.4. We do not believe this happens in 1.26.4. I know this seems like an unusual bug, so many thanks for your help!

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by jslott2sigma**
## Hey, I just made a Pull Request!

Use the `styles` rollup plugin instead of the `postcss` rollup plugin. This fixes issues seen when importing svg (and other) image files where the `postcss` plugin would generate the wrong relative path.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jslott2sigma** [comment]
Is there anyway to override the type checking for the `rollup-plugin-styles` dependency when doing a `yarn tsc:full`? (I'm slightly confused since it would be quite a feat that the full type checking with skipLibCheck=false passes for _all_ of the other dependencies in the project?)

See: https://github.com/backstage/backstage/actions/runs/10480805232/job/29029186804?pr=26111

**Review by Rugvip — CHANGES_REQUESTED** [review]
Nice! 👍 

I've verified the output locally it looks good, provided we use the default mode rather than `extract`. Now the bad news is that this brings back the original issue of the SVG path being incorrect in the build output, so it doesn't really fix anything unfortunately 😓. It's actually the case that if we switch the `postcss` mode to `extract` it's fix the SVG path issue too, but that breaks that styles.

The CI failures seem to be due to a bad release, being tracked in https://github.com/Anidetrix/rollup-plugin-styles/issues/249, so we'll need to wait for that to be resolved.

**Comment by jslott2sigma** [comment]
@Rugvip Thanks so much for taking a look! And ugh -- let me dig deeper into the `rollup-plugin-styles` to see what's actually going on with `extract` versus `inject`.

**Comment by jslott2sigma** [comment]
This is no longer necessary as it has been fixed by #26401.

**Pull request closed without merging**
