### PR TITLE
catalog: Allow transforming entity namespace in UrlReaderProcessor

### PR DESCRIPTION
**Pull request by mspiegel31**
## Hey, I just made a Pull Request!

This PR modifies the configuration for `UrlReaderProcessor` and defines a new method on the `CatalogProcessingExtensionPoint`.  It allows an operator to define a mapping function for modifying an entity's `namespace` before it is written to the entity database.

### Sample Usecase
Your company has acquired another company (hooray!).  This company has a github org you'd like to add to backstage.  However, several repositories between the organizations have the exact same name.  This will result in the `conflictingEntityRef` message if `orgA/Repo` and `orgB/Repo` are both added to the `default` namespace.  This PR aims to solve that

### Example usage
```ts
import {
  coreServices,
  createBackendModule,
} from '@backstage/backend-plugin-api';
import {
  catalogProcessingExtensionPoint,
} from '@backstage/plugin-catalog-node/alpha';
import { getDefaultProcessors, NamespaceTransformer, UrlReaderProcessor } from '@backstage/plugin-catalog-backend';
import { parseGithubOrgUrl } from '../lib';

export const exampleCatalogModule = createBackendModule({
  pluginId: 'catalog',
  moduleId: 'example',
  register(env) {
    env.registerInit({
      deps: {
        catalog: catalogProcessingExtensionPoint,
        config: coreServices.rootConfig,
        logger: coreServices.logger,
        reader: coreServices.urlReader,
      },
      async init({
        catalog,
        config,
        logger,
        reader,
      }) {
        const namespaceTransformer: NamespaceTransformer = result => parseGithubOrgUrl(result.location.target).org;
        const customUrlReader = new UrlReaderProcessor({logger, reader, namespaceTransformer});  
        const defaultProcessors = getDefaultProcessors({ logger, config, reader })
          .map(p => {
            if (p.getProcessorName() === customUrlReader.getProcessorName()) {
              return customUrlReader;
            }
            return p
          })

        catalog.replaceDefaultProcessors(defaultProcessors);
      },
    });
  },
});
```

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] (N/A) Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey sorry! Been a busy few weeks with vacations, will try and get a review in for the release on Tuesday!

**Comment by mspiegel31** [comment]
> Hey sorry! Been a busy few weeks with vacations, will try and get a review in for the release on Tuesday!

oh, sorry!  Please enjoy your vacation.

**Review by benjdlambert — CHANGES_REQUESTED** [review]
hey @mspiegel31!

Sorry it's taken a while to get round to reviewing this!

So I'm thinking that the best way for you to achieve what you want to do is to provide your own `EntityDataParser` instead. You can do this by using the `setEntityDataParser` method on the `CatalogModelExtensionPoint`.

The default implementation of `parseEntityYaml` is already exported too, and what this is going to let you do is to use the default implementation to parse it, and then you can make the modifications necessary depending on the location and return it there.

I'd advise going down this route to begin with, as there's a lot of other things in this PR which we want to get to, but we're not ready for yet, or requires more thought. Thinks like the `replaceDefaultProcessors` and `getDefaultProcessors` etc in particular, these are things that will likely be replaced with some other API in the future.

Here's the default implementation of the `EntityDataParser` which you can use for reference: https://github.com/backstage/backstage/blob/d8593ce0e6cd21c0ec61056dbb47d7a7c6b5ebf7/plugins/catalog-backend/src/modules/util/parse.ts#L62-L67

**Comment by mspiegel31** [comment]
@benjdlambert thanks for your feedback here!  I'm going to be juggling some vacation of my own, but I'll take a stab at this soon.

I don't believe the ` defaultEntityDataParser` is an exported member of the `catalog-backend` package.  I can probably just copy -> paste the implementation to see if this solution works for us though!

**Comment by benjdlambert** [comment]
@mspiegel31 you're right it's not, but `parseEntityYaml` and you'll need to copy some of the original for the signature anyways, it's pretty small :)

**Pull request closed without merging**
