### PR TITLE
Updating new headers #1232

### PR DESCRIPTION
**Pull request by benjaminr**
Adds new colour scheme for updated headers to improve accessibility.

### CODE REVIEW

**Comment by benjaminr** [comment]
I realise the colours are wrong here at the moment, will wait to hear more back from @katz95 and @Rugvip regarding the opacity and gradients.

**Comment by stefanalund** [comment]
Thanks a lot! Any particular reason you are not follow the colors for Library and Other in?

Colors

**Comment by stefanalund** [comment]
Oh, sorry I did not see your comment :)

**Comment by katz95** [comment]
@benjaminr hi! thanks for picking this up! according to my colleague @nikek, the color confusion in figma "was a miscommunication, as looking at the svg code of the designs exported from figma there are several linear gradients with sometimes slightly different colors"

if you click on the gradient shapes themselves in figma (rather than looking at the SVG code), you should be able to see the colors (2 of them, not 4). let me know if that works for you, and if it doesn't, I can send them to you here!

**Comment by emmaindal** [comment]
Hello @benjdlambert and @katz95 this looks great, would it be possible to squeeze in a header for documentation in this PR as well? 😄

**Comment by benjaminr** [comment]
> Hello @benjaminr and @katz95 this looks great, would it be possible to squeeze in a header for documentation in this PR as well? 😄

Sure thing, sounds fine to me, just let me know what to include 😄

**Comment by benjaminr** [comment]
> @benjaminr hi! thanks for picking this up! according to my colleague @nikek, the color confusion in figma "was a miscommunication, as looking at the svg code of the designs exported from figma there are several linear gradients with sometimes slightly different colors"
> 
> if you click on the gradient shapes themselves in figma (rather than looking at the SVG code), you should be able to see the colors (2 of them, not 4). let me know if that works for you, and if it doesn't, I can send them to you here!

Awesome, sounds good @katz95, will take a look and let you know if i need any more pointers. Thanks for clarifying! 😄

**Comment by benjaminr** [comment]
> > @benjaminr hi! thanks for picking this up! according to my colleague @nikek, the color confusion in figma "was a miscommunication, as looking at the svg code of the designs exported from figma there are several linear gradients with sometimes slightly different colors"
> > if you click on the gradient shapes themselves in figma (rather than looking at the SVG code), you should be able to see the colors (2 of them, not 4). let me know if that works for you, and if it doesn't, I can send them to you here!
> 
> Awesome, sounds good @katz95, will take a look and let you know if i need any more pointers. Thanks for clarifying! 😄

@katz95 I've just had a quick look in Figma and I'm not sure I'm seeing the same options as you. Might just be easier to send the colour pairs over here if that's okay with you?

**Comment by emmaindal** [comment]
> > Hello @benjaminr and @katz95 this looks great, would it be possible to squeeze in a header for documentation in this PR as well? 😄
> 
> Sure thing, sounds fine to me, just let me know what to include 😄

@benjaminr Sounds good. I'll get back to you when we sync about colors for the Documentation header. 

Maybe this image can guide you to find the 2 colors for each header? 
Screen Shot 2020-07-06 at 9 40 28 AM

@katz95 FYI only the first header seems to export the gradient CSS.

**Comment by benjaminr** [comment]
> > > Hello @benjaminr and @katz95 this looks great, would it be possible to squeeze in a header for documentation in this PR as well? 😄
> > 
> > 
> > Sure thing, sounds fine to me, just let me know what to include 😄
> 
> @benjaminr Sounds good. I'll get back to you when we sync about colors for the Documentation header.
> 
> Maybe this image can guide you to find the 2 colors for each header?
> Screen Shot 2020-07-06 at 9 40 28 AM
> 
> @katz95 FYI only the first header seems to export the gradient CSS.

Thanks for the pointer! Glad I wasn't being silly 😄 that's where I was getting values from originally. 

Apologies for my slowness, not all that familiar with Figma, but happy to be learning!

**Comment by benjaminr** [comment]
@katz95 @stefanalund I've updated the colours to reflect the changes to the gradients. I noticed on a couple of the themes there are multiple linear gradients for the wave shapes within a theme. I've only add one for the moment to keep it simple. 

Do you want the multiple gradients, for example on the App theme, there's a 100% -> 0% FF784E and 72% -> 0% FFE175. Might just be I've misinterpreted the info!

**Comment by katz95** [comment]
@benjaminr let me know if this is helpful! i've broken out the colors for the bases and waves here 😊

Colors

**Comment by benjaminr** [comment]
> @benjaminr let me know if this is helpful! i've broken out the colors for the bases and waves here 😊
> 
> Colors

I've updated the colors and opacities as per your details. Let me know if it's as expected in the Storybook 😀

**Review by Rugvip — COMMENTED** [review]
Could we break the colors into `colors: ['#181818', '#404040'], waveColor: '#757575'`, so that we have a bit of a clearer separation between what's for the gradient and the wave?

With that change I think we should get this merged and look at https://github.com/spotify/backstage/issues/393 separately

**Comment by benjaminr** [comment]
> Could we break the colors into `colors: ['#181818', '#404040'], waveColor: '#757575'`, so that we have a bit of a clearer separation between what's for the gradient and the wave?
> 
> With that change I think we should get this merged and look at #393 separately

No problem, see the latest commit.

**Review by stefanalund — APPROVED** [review]

**Comment by stefanalund** [comment]
Thanks a lot!

**Pull request merged**
