### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by backstage-service**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and publish to npm yourself or [setup this action to publish automatically](https://github.com/changesets/action#with-publishing). If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
### Minor Changes

-   aaeb7ecf3: When newer documentation available but not built, show older documentation while async building newer
    TechDocs backend: /sync endpoint added to support above, returns immediate success if docs don't need a build, returns delayed success after build if needed
    TechDocs backend: /docs endpoint removed as frontend can directly request to techdocs.storageUrl or /static/docs
-   3139f83af: Add sticky sidebars and footer navigation links to TechDocs Reader

### Patch Changes

-   ea9d977e7: Introduce workaround for admonition icons of MkDocs.
-   2aab54319: TechDocs: links at sidebar and bottom reset scroll position to top
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-techdocs-backend@0.7.0

### Minor Changes

-   aaeb7ecf3: When newer documentation available but not built, show older documentation while async building newer
    TechDocs backend: /sync endpoint added to support above, returns immediate success if docs don't need a build, returns delayed success after build if needed
    TechDocs backend: /docs endpoint removed as frontend can directly request to techdocs.storageUrl or /static/docs

 ## @backstage/cli@0.6.6

### Patch Changes

-   598f5bcfb: Lock down the version of webpack-dev-server as it's causing some nasty bugs someplace
-   4d248725e: Make the backend plugin template use the correct latest version of `express-promise-router`

 ## @backstage/core@0.7.3

### Patch Changes

-   fcc3ada24: Reuse ResponseErrorList for non ResponseErrors
-   4618774ff: Changed color for Add Item, Support & Choose buttons with low contrast/readability in dark mode
-   df59930b3: Fix PropTypes error with OverflowTooltip component
-   Updated dependencies [76deafd31]
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [4618774ff]
    -   @backstage/core-api@0.2.15
    -   @backstage/theme@0.2.5

 ## @backstage/core-api@0.2.15

### Patch Changes

-   76deafd31: Changed the signature of `createRoutableExtension` to include null
-   01ccef4c7: Introduce `useRouteRefParams` to `core-api` to retrieve typed route parameters.
-   Updated dependencies [4618774ff]
    -   @backstage/theme@0.2.5

 ## @backstage/create-app@0.3.15

### Patch Changes

-   2c525f85e: (fix) Adds locationAnalyzer to default-app template

    The locationAnalyzer was missing from the default-app template.
    This resulted in 404 errors in newly bootstrapped backstage applications,
    when adding components without configuration.

    To fix this in an existing backstage application, the locationAnalyzer needs
    to be carried from the builder to the router in the
    `packages/backend/src/plugins/catalog.ts` file.

    ```diff
       const builder = new CatalogBuilder(env);
       const {
         entitiesCatalog,
         locationsCatalog,
         higherOrderOperation,
    +    locationAnalyzer,
       } = await builder.build();
       // ...
       return await createRouter({
         entitiesCatalog,
         locationsCatalog,
         higherOrderOperation,
    +    locationAnalyzer,
         logger: env.logger,
       });
    ```

-   f88fe9dd9: Adds plugin-org and more capability to the default EntityPage to display Users, Groups and Systems.

    To update an existing application, add the org plugin:

    ```shell
    cd packages/app
    yarn add @backstage/plugin-org
    ```

    Then add the example systems locations to your `app-config.yaml`:

    ```diff
    catalog:
      rules:
    -    - allow: [Component, API, Group, User, Template, Location]
    +    - allow: [Component, System, API, Group, User, Template, Location]
      locations:
        # Backstage example components
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

    +    # Backstage example systems
    +    - type: url
    +      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml
    +
        # Backstage example APIs
    ```

    Additionally, the default app sidebar was updated to parity with the Backstage
    repo. You can see these changes in the template
    [App.tsx](https://github.com/backstage/backstage/blob/8817a87cdd5c881fbe8a43557ba7f9df0f9e3258/packages/create-app/templates/default-app/packages/app/src/App.tsx#L70)
    referencing a new `Root` component.

    Finally, compare your `packages/app/src/components/catalog/EntityPage.tsx` to
    [EntityPage](https://github.com/backstage/backstage/blob/8817a87cdd5c881fbe8a43557ba7f9df0f9e3258/packages/create-app/templates/default-app/packages/app/src/components/catalog/EntityPage.tsx)
    from the `@backstage/create-app` default template to pick up additional
    changes there.

-   4d248725e: Update the create-app template to use the correct latest version of `express-promise-router`.

    To apply the same change in your own repository, update all of your repo's dependencies on `express-promise-router` to `"^4.1.0"`.

-   Updated dependencies [9f2e51e89]

-   Updated dependencies [01ccef4c7]

-   Updated dependencies [4d248725e]

-   Updated dependencies [aaeb7ecf3]

-   Updated dependencies [449776cd6]

-   Updated dependencies [91e87c055]

-   Updated dependencies [ea9d977e7]

-   Updated dependencies [fcc3ada24]

-   Updated dependencies [687f066e1]

-   Updated dependencies [2aab54319]

-   Updated dependencies [113d3d59e]

-   Updated dependencies [f47e11427]

-   Updated dependencies [4618774ff]

-   Updated dependencies [3139f83af]

-   Updated dependencies [598f5bcfb]

-   Updated dependencies [c862b3f36]

-   Updated dependencies [4d248725e]

-   Updated dependencies [df59930b3]
    -   @backstage/plugin-scaffolder-backend@0.9.3
    -   @backstage/plugin-github-actions@0.4.2
    -   @backstage/plugin-catalog@0.5.1
    -   @backstage/plugin-techdocs@0.7.0
    -   @backstage/plugin-techdocs-backend@0.7.0
    -   @backstage/plugin-auth-backend@0.3.6
    -   @backstage/core@0.7.3
    -   @backstage/plugin-catalog-backend@0.6.7
    -   @backstage/theme@0.2.5
    -   @backstage/cli@0.6.6

 ## @backstage/theme@0.2.5

### Patch Changes

-   4618774ff: Changed color for Add Item, Support & Choose buttons with low contrast/readability in dark mode

 ## @backstage/plugin-auth-backend@0.3.6

### Patch Changes

-   449776cd6: The `auth` config types now properly accept any declared auth environment. Previously only `development` was accepted.

    The `audience` configuration is no longer required for GitLab auth; this will default to `https://gitlab.com`

 ## @backstage/plugin-badges@0.1.2

### Patch Changes

-   687f066e1: Update badge dialog formatting
-   4d248725e: Get the current entity using `useEntity` from `@backstage/plugin-catalog-react`
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-catalog@0.5.1

### Patch Changes

-   4d248725e: Temporarily add `UNSTABLE_extraContextMenuItems` to the entity layout, so that we could detach the catalog plugin from the dependency on the badges plugin
-   687f066e1: Add icon for entity badge menu
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-catalog-backend@0.6.7

### Patch Changes

-   f47e11427: Log how many repositories were actually matching in `GithubDiscoveryProcessor`

-   c862b3f36: Introduce pagination in the /entities catalog endpoint.

    Pagination is requested using query parameters. Currently supported parameters, all optional, are:

    -   `limit` - an integer number of entities to return, at most
    -   `offset` - an integer number of entities to skip over at the start
    -   `after` - an opaque string cursor as returned by a previous paginated request

    Example request:

    `GET /entities?limit=100`

    Example response:

        200 OK
        Content-Type: application/json; charset=utf-8
        Link: </entities?limit=100&after=eyJsaW1pdCI6Miwib2Zmc2V0IjoyfQ%3D%3D>; rel="next"
        <more headers>

        [{"metadata":{...

    Note the Link header. It contains the URL (path and query part, relative to the catalog root) to use for requesting the next page.
    It uses the `after` cursor to point out the end of the previous page. If the Link header is not present, there is no more data to read.

    The current implementation is naive and encodes offset/limit in the cursor implementation, so it is not robust in the face of overlapping
    changes to the catalog. This can be improved separately in the future without having to change the calling patterns.

-   Updated dependencies [4d248725e]
    -   @backstage/plugin-search-backend-node@0.1.2

 ## @backstage/plugin-catalog-react@0.1.3

### Patch Changes

-   01ccef4c7: Introduce `useRouteRefParams` to `core-api` to retrieve typed route parameters.
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/core@0.7.3

 ## @backstage/plugin-cost-insights@0.8.4

### Patch Changes

-   d10ea17c9: fix missing type exports of public components
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-github-actions@0.4.2

### Patch Changes

-   01ccef4c7: Introduce `useRouteRefParams` to `core-api` to retrieve typed route parameters.
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-jenkins@0.4.1

### Patch Changes

-   01ccef4c7: Introduce `useRouteRefParams` to `core-api` to retrieve typed route parameters.
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-kubernetes@0.4.2

### Patch Changes

-   a2a3c7803: Bump `@kubernetes/client-node` from `^0.13.2` to `^0.14.0`.
-   Updated dependencies [a2a3c7803]
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-kubernetes-backend@0.3.2
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-kubernetes-backend@0.3.2

### Patch Changes

-   a2a3c7803: Bump `@kubernetes/client-node` from `^0.13.2` to `^0.14.0`.

 ## @backstage/plugin-scaffolder-backend@0.9.3

### Patch Changes

-   9f2e51e89: Fixes bug in the `github:publish` action causing repositories to be set as private even if the visibility is set to internal
-   91e87c055: Add inputs for action `fetch:cookiecutter`: copyWithoutRender, extensions, imageName
-   113d3d59e: Added a `publish:file` action to use for local development. The action is not installed by default.

 ## @backstage/plugin-search-backend@0.1.2

### Patch Changes

-   4d248725e: Bump to use the in-repo latest `backend-common`, and the correct version of `express-promise-router`

 ## @backstage/plugin-search-backend-node@0.1.2

### Patch Changes

-   4d248725e: Bump to use the in-repo latest `backend-common`, and the correct version of `express-promise-router`

 ## @backstage/plugin-sonarqube@0.1.15

### Patch Changes

-   322e01a95: Support SonarQube project keys containing special characters like colons.
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [4618774ff]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5

 ## @backstage/plugin-todo-backend@0.1.2

### Patch Changes

-   36d933ec5: Forward authorization on todo backend requests

 ## example-app@0.2.21

### Patch Changes

-   Updated dependencies [a2a3c7803]
-   Updated dependencies [687f066e1]
-   Updated dependencies [d10ea17c9]
-   Updated dependencies [01ccef4c7]
-   Updated dependencies [4d248725e]
-   Updated dependencies [4d248725e]
-   Updated dependencies [aaeb7ecf3]
-   Updated dependencies [ea9d977e7]
-   Updated dependencies [fcc3ada24]
-   Updated dependencies [687f066e1]
-   Updated dependencies [2aab54319]
-   Updated dependencies [4618774ff]
-   Updated dependencies [3139f83af]
-   Updated dependencies [598f5bcfb]
-   Updated dependencies [4d248725e]
-   Updated dependencies [df59930b3]
    -   @backstage/plugin-kubernetes@0.4.2
    -   @backstage/plugin-badges@0.1.2
    -   @backstage/plugin-cost-insights@0.8.4
    -   @backstage/plugin-catalog-react@0.1.3
    -   @backstage/plugin-github-actions@0.4.2
    -   @backstage/plugin-jenkins@0.4.1
    -   @backstage/plugin-catalog@0.5.1
    -   @backstage/plugin-techdocs@0.7.0
    -   @backstage/core@0.7.3
    -   @backstage/theme@0.2.5
    -   @backstage/cli@0.6.6

 ## example-backend@0.2.21

### Patch Changes

-   Updated dependencies [a2a3c7803]
-   Updated dependencies [9f2e51e89]
-   Updated dependencies [4d248725e]
-   Updated dependencies [aaeb7ecf3]
-   Updated dependencies [449776cd6]
-   Updated dependencies [91e87c055]
-   Updated dependencies [36d933ec5]
-   Updated dependencies [113d3d59e]
-   Updated dependencies [f47e11427]
-   Updated dependencies [c862b3f36]
    -   @backstage/plugin-kubernetes-backend@0.3.2
    -   @backstage/plugin-scaffolder-backend@0.9.3
    -   @backstage/plugin-search-backend@0.1.2
    -   @backstage/plugin-search-backend-node@0.1.2
    -   @backstage/plugin-techdocs-backend@0.7.0
    -   @backstage/plugin-auth-backend@0.3.6
    -   @backstage/plugin-todo-backend@0.1.2
    -   @backstage/plugin-catalog-backend@0.6.7
    -   example-app@0.2.21

### CODE REVIEW

**Comment by benjdlambert** [comment]
@backstage/silver-lining @backstage/techdocs-core I can haz +1 here?

**Review by benjdlambert — APPROVED** [review]

**Review by freben — APPROVED** [review]

**Review by emmaindal — APPROVED** [review]

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5020-mj8g1fnqhvikzgzhriyz7ffo4iokjfsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/605cb9ee437dd1ad99f749dc

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5020-mj8g1fnqhvikzgzhriyz7ffo4iokjfsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/605cb9ee437dd1ad99f749dc

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5020-mj8g1fnqhvikzgzhriyz7ffo4iokjfsx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/605cb9ee437dd1ad99f749dc

**Pull request merged**
