### PR TITLE
Fetch relations in batches in `useRelatedEntities`

### PR DESCRIPTION
**Pull request by WillSewell**
## Hey, I just made a Pull Request!

Rather than making a request per relation, filter multiple relations in a single request.

To avoid the query string getting very large, make multiple requests on batches of 100 relations.

The function is currently untested. Let me know if you think this needs some.

Resolves https://github.com/backstage/backstage/issues/5475.

A potentially nicer solution for the longer term would be https://github.com/backstage/backstage/issues/4499.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5558-jil7pzxgatlqto9g8bihb9mjnewixrmb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608fda7ee1c6000705efeeec

**Review by freben — COMMENTED** [review]
Hi! Thanks for writing this up.

A few ideas:

- It's a pretty large batch size since this gets encoded into the query string. Maybe pull it down to like 20 or so.
- If we first group by kind and namespace, then break down batches within those groups, each call to the backend can have a single `kind` and `metadata.namespace` but an array of `metadata.name` candidates. Could make the query string shorter, and the backing db requests faster. If you find this code tricky to get going, the lodash library helps, and here's [an example](https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/plugins/catalog-backend/src/catalog/DatabaseEntitiesCatalog.ts#L105).
- All of the batches are issued in parallel, which also would be a source of congestion at the browser level - it'll saturate the outgoing connection limit all by itself. One quick and easy way of limiting the parallelism is to slap a `p-limit` of for example 2 around it, example [here](https://github.com/backstage/backstage/blob/2ec993027ec798ffe1c6c256650fdc692e3bdb49/packages/techdocs-common/src/stages/publish/googleStorage.ts#L120).

I know this is a tall order, and if you would prefer to have this merged as is and let us do the final tweaking, just let me know.

**Comment by WillSewell** [comment]
Thanks for the feedback! In terms of the batch size and request parallelism, it's tricky to know what to set them to without testing on large numbers of relations. Given I don't think it's worth the effort at this stage, I'm happy to set them to what you suggest. They can always be tweaked at a later stage.

Good point about grouping by kind and namespace. I'll give that a go.

**Comment by WillSewell** [comment]
I'm concerned about limiting the parallelism to 2. We have some entities with ~2000 relations. If we assume the roundtrip time of a batch request is 0.2 seconds, a max parallelism of 2, and batch size of 20, then it could take 0.2*2000/20/2=10 seconds to load all relations. This is higher latency than the current implementation, where 2000 requests are made in parallel.

What about a max parallelism of 10?

Interestingly in the version of Chrome I'm using (90.0.4430.93), the browser seems quite happy to fire off 2000 requests in parallel and stall some of them until it's ready.

**Comment by WillSewell** [comment]
One more thing: are you suggesting pulling in the lodash library into the catalog-react plugin? Or were you suggesting I use the implementation of the lodash function for inspiration? I feel like pulling in a whole library just for 2 functions is quite extreme, but I'm happy to do it if you think it'll get used more in the future.

**Comment by freben** [comment]
I think if you look at actual socket usage, you'll find that the network tab shows 2000 concurrent things but the network does [only six](https://blog.bluetriangle.com/blocking-web-performance-villain#:~:text=Chrome%20has%20a%20limit%20of,host%20at%20the%20same%20time.) because almost all of them are waiting for access to that shared resource.

What I'm concerned with is that a backend won't be able to serve that kind of parallelism without saturating anyway. There's a connection pool going back to the database as well that is bounded. And then imagine hundreds or thousands of concurrent users of the frontend that visit these pages :) Some of the adopting orgs are pretty large, including Spotify!

I see what you mean about the speed, and we want to be mindful of that too, just keep in mind the browser has to deal with the instantaneous json parsing and memory handling of the huge payloads as well when doing it in one big request. And bear in mind also the mobile clients trying to use the interface in oncall situations etc :)

Regarding lodash, we are using it pretty pervasively (currently `"^4.17.15"`) in the core repo, including the `catalog-model` package. So for most, this will hardly make any difference in practice.

**Comment by freben** [comment]
In any case, the proper solution to this is to get the relations filtering in place server-side so we don't have to do this at all. Some day in a not too distant future! Then you'll get it all in one rapid small request.

**Comment by WillSewell** [comment]
Ok, I'll have a got at using the helpers in lodash :)

As for the resource saturation. I see your concern, however I'm tempted to leave setting "max parallelism" for follow-up work for a few reasons:

- This PR is already going to reduce the number of requests by an order of magnitude (N/20 instead of N).
- Given it's big improvement already. I'm tempted to merge as-is, and optimise in the future based on real world performance requirements
- As you say, you have an idea for a significantly more efficient longer-term solution (server side filtering)

**Comment by freben** [comment]
Yep as I mentioned I tend to agree, no rush to make this absolutely perfect but had some ideas.

**Comment by WillSewell** [comment]
I think the implementation is done now. I'll investigate the failing tests tomorrow. I suspect it's related to mock expectations that are now out of date, but it's tricky to tell from the test failure output.

**Review by freben — APPROVED** [review]
Looks good!

**Pull request merged**
