### PR TITLE
chore: add apollo explorer to plugin marketplace

### PR DESCRIPTION
**Pull request by unredundant**
## Hey, I just made a Pull Request!

Just adds apollo explorer plugin to the marketplace as per [these](https://backstage.io/docs/plugins/add-to-marketplace) instructions 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@unredundant, question on the logo. Do you know if it's fine for us to keep the logo in here too? What license is it?

**Comment by unredundant** [comment]
Hmm good question.  I poked around their GitHub a bit and their code seems to range from MIT to Elastic in terms of licensing, but as for the logo I'm not quite sure how to figure that out.  

Maybe best to just be safe and swap it for the same logo as GraphiQL? Or if you have suggestions on how to verify that we can use this logo I'm happy to go investigate

**Comment by benjdlambert** [comment]
Hmm I think that if the icons are in the same repo that's MIT then I think it's fine, but IANAL. Hmm previously we've just been able to find docs about usage. How about you raise an issue on their repo asking and we just use the default GraphQL one for now, and then we can switch it if we get the approval? I'm pretty sure it's going to be fine to use their logo anyways, but better to be safe than sorry :pray:

**Comment by unredundant** [comment]
I'm cool waiting a couple days to see if they get back to us on the issue I just opened up (referenced above) 

If we don't hear anything let's go w/ the default GraphQL logo :)

**Comment by benjdlambert** [comment]
Perfect! nice work! thanks :pray:

**Comment by unredundant** [comment]
@benjdlambert Got permission in https://github.com/apollographql/embeddable-explorer/issues/151 we should be all good to go 🎉

**Review by benjdlambert — APPROVED** [review]
Nice! :pray:

**Pull request merged**
