### PR TITLE
Updated to Node 20 and 22

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

This updates everything as best I can find to at Node 20 and 22. ~~This would ideally get merged after the September `1.31.0` release so it can be test with the first `1.32.0-next` release.~~

**Note:** Node.js v22 goes into active LTS on 2024-10-29, which means this will need to be merged after the 1.32 release at the earliest: https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule

Used https://github.com/backstage/backstage/pull/19565 as a guide.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by acierto — APPROVED** [review]

**Review by camilaibs — APPROVED** [review]
🙌🏻

**Comment by benjdlambert** [comment]
I think that we want to make sure that we do this after 22 has been pushed to LTS https://nodejs.org/en/blog/announcements/v22-release-announce.

This should be October time, so I think we might just want to sit on this until it's announced, and then the next mainline release will officially drop support for 18.

**Comment by awanlin** [comment]
Did some more digging into this today, seems that adding a resolution for `nan` to version `2.20.0` seems to fix the errors for `canvas`, `cpu-features`, `tree-sitter-json`, `tree-sitter-yaml`, and `tree-sitter`.  This is what lead me to try this: https://github.com/nodejs/nan/issues/936.

`isolated-vm` still has issues and I'm digging into that one now.

**Comment by awanlin** [comment]
OK, looks using `5.0.1` for `isolated-vm` gets a successful `yarn install`. This issue helped me with this: https://github.com/laverdet/isolated-vm/issues/425. Hat tip to @webark 🎩

**Comment by awanlin** [comment]
`canvas` is working for me locally during `yarn install`, taking a look at why it's failing here.

**Review by Rugvip — CHANGES_REQUESTED** [review]
As discussed we'll want to wait before merging this, but it's good to get the work started to iron out any issues now 👍 

Node.js v22 goes into active LTS on 2024-10-29, which means this will need to be merged after the 1.32 release at the earliest: https://github.com/nodejs/Release?tab=readme-ov-file#release-schedule

**Comment by awanlin** [comment]
Not stale, will pick this up again at the end of the week.

**Comment by awanlin** [comment]
Closing as work for this will be done in https://github.com/backstage/backstage/pull/27286 🚀

**Pull request closed without merging**
