### PR TITLE
[MUI v5] Suggestion to remove PaletteOptions & ThemeOptions override

### PR DESCRIPTION
**Pull request by tudi2d**
> This is a suggestion - not super sure I'm on point with this thought

## What

Remove override of `PaletteOptions` & `ThemeOptions` types in `@backstage/theme`.

## Why 

The `...Options` type indicate the optionality of all nested parameters. The TypeScript Guide to Customisation also highlights that for adding new variables to the palette (https://mui.com/material-ui/customization/palette/#typescript) 

MUI uses those types to allow overriding certain values in the theme/palette through deep-merging the Options with the Palette/Theme (https://github.com/mui/material-ui/blob/master/packages/mui-material/src/styles/createPalette.js#L272-L313). With overwriting those types we will prevent this usage of e.g. `createTheme(...)` with `ThemeOptions` **without** the `BackstageThemeAdditions`.

On the other hand - the only usage of those `PaletteOptions`/`ThemeOptions` & `createTheme/createPalette` should be to create nested palettes/themes as their will always be a top level `ThemeProvider`. Inner `ThemeProvider` will then override outer `ThemeProvider` if they don't use a functions (https://mui.com/system/styles/advanced/#theme-nesting). So this actually could be an opportunity to avoid overrides of themes with static defaults & encourage the consumption on outer themes when creating inner themes.

## Action

Removing those types now would allow a usage of the current Material UI behaviour - but without the capability of overriding Backstage Variables without passing a full theme in.

Alternatives:
- Keep it as it is, making it a bit harder to create inner themes & maybe have a higher consciousness around what is overwritten
- Add `BackstageThemeAdditionOptions` types and making all Backstage additions to the theme optional for `createTheme`/`createPalette`

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Rugvip** [comment]
Is this ready for review?

**Comment by tudi2d** [comment]
back & ready for review. dropping this discussion for context as this might affect custom themes https://discord.com/channels/687207715902193673/1110599124954394694/1112474736560189540

**Comment by awanlin** [comment]
@Rugvip @benjdlambert just some additional background, right now I'm a bit stuck getting the Demo site's `aperture` theme working with the various `1.15.0-next` releases. We, well @tudi2d who has a better handle on this, think this might be the solution though. I'm really hoping to be able to use the demo site as an example for people to look at that are trying to upgrade to MUI v5 so getting it working would be really great!

**Review by Rugvip — COMMENTED** [review]
Not quite understanding this change tbh. With these palette options removed we no longer include our required palette options when creating a new theme? Without those colors in the palette we the app might break.

I think it's safe for the theme options though, since we're defaulting all of those bits in `createUnifiedTheme`

**Review by Rugvip — APPROVED** [review]
Let's figure out a way to make the unified themes type-safe, but for now I think the safest way forward is to ship this. I've realized that augmenting the theme options like this risks having a pretty big impact on existing apps in a way that we should avoid.

Skipping changeset since this is all new stuff anyway.

Thank you for digging into this! 👍

**Pull request merged**
