### PR TITLE
Techdocs - Don't Copy docs/README.md -> index.md if it is provided

### PR DESCRIPTION
**Pull request by ryanmrodriguez**
MkDocs allows you to use a `README.md` in place of an `index.md`:

> Many repository hosting sites provide special treatment for README files by displaying the contents of the README file when browsing the contents of a directory. Therefore, MkDocs will allow you to name your index pages as README.md instead of index.md. In that way, when users are browsing your source code, the repository host can display the index page of that directory as it is a README file. However, when MkDocs renders your site, the file will be renamed to index.html so that the server will serve it as a proper index file.

> If both an index.md file and a README.md file are found in the same directory, then the index.md file is used and the README.md file is ignored.
- https://www.mkdocs.org/user-guide/writing-your-docs/

As the above mentions, if an `index.md` is detected, the `README.md` is ignored. https://github.com/mkdocs/mkdocs/pull/1582

If a `docs/README.md` is provided, TechDocs should not copy this file over to an `index.md` file, as this breaks rendering of the docs. (Using `README.md` as a reference in `mkdocs.yaml`)

Since all of the fallbacks are variants of `README.md(docs/readme.md, README.md, readme.md)`, I was considering copying this file over to `docs/README.md` instead of `docs/index.md`. However, this would further break the implementations of user's who are referencing `index.md` in their `mkdocs.yaml` files, and relying on the patch/copy. To be clear, this will break any implementations that supply a `docs/README.md`, expect the patch/copy to happen, and use a reference to `index.md` in their `mkdocs.yaml` file. For example:

`ls docs/ -> README.md` (No `index.md` file provided)

mkdocs.yaml
```
site_name: Hello
site_description: Hello World 
nav:
  - Home: index.md
  - User Guide': user-guide.md
plugins:
  - techdocs-core
```

^ That would break with this change. But I think it makes sense to enforce the reference of `README.md` for these cases, as that is what is expected in the MkDocs documentation.

mkdocs.yaml
```
site_name: Hello
site_description: Hello World 
nav:
  - Home: README.md
  - User Guide': user-guide.md
plugins:
  - techdocs-core
```
^ Works

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by ryanmrodriguez** [comment]
To try and further illustrate this issue:

Here is the example `mkdocs.yaml` file running locally:
```yaml
site_name: Random
site_description: Random Documentation
nav:
  - 'Home': 'README.md'
  - 'User Guide': 'user-guide.md'
plugins:
  - techdocs-core
```

`/docs` contains -> `README.md` `user-guide.md`

When viewing the Docs page for the related component:
Screen Shot 2021-12-20 at 12 49 01 PM

^ As you can see, the README.md contents load in fine, because they were copied over into an `index.md`. But you can also see that the nav-link is referencing 'README.md', which MkDocs has now discarded (because an `index.md` was found alongside `README.md` in the `docs/` directory). 

Clicking on that link:
Screen Shot 2021-12-20 at 12 49 29 PM

If you load the Docs initially, and click the 'Pencil' to edit them, it will direct you to `https://github.com/{ORG}/{REPO}/edit/{BRANCH}/docs/index.md`, which won't exist because an explicit `index.md` was not provided, and thus lead to a 404.

**Comment by freben** [comment]
Leaving this to @backstage/techdocs-core to review, but noting that you're missing a changeset for this.

**Comment by ryanmrodriguez** [comment]
Changeset has been added

**Review by iamEAP — COMMENTED** [review]
Thanks @ryanmrodriguez!

I'm having a little trouble thinking through the need / consequences for this change, so let me try and confirm my understanding (let me know if I'm thinking of this the wrong way):

- **Background**: There is a valid mkdocs configuration/use-case in which one could specify `- Home: README.md` in `mkdocs.yml`, have a `docs/README.md` file, and the generated site works as expected.  It renders `docs/README.md` as the index file and any referential links (in nav or content) behave normally.
- **Problem**: The `patchIndexPreBuild` function in TechDocs Common assumes that a `docs/index.md` file is required; if no such file exists, but a `docs/README.md` (or similar) file _does_ exist, it will copy it to `docs/index.md`.

  This is okay if and only if your `mkdocs.yml` also happens to point to, e.g. `- Home: index.md` (and you therefore implicitly rely on this copy behavior).  But if your configuration matches the one described in **background** above, this file copying behavior breaks the site.  ...The index page will still render as expected (because mkdocs will see the `index.md` file, render it, and ignore/discard the `README.md` file), but the nav will be broken (because it points to a now-discarded `README.md` file).

- **Proposed solution**: The fix here basically updates the (incorrect) assumption in `patchIndexPreBuild` so that it does nothing if _either_ an `index.md` _or_ a `README.md` is present.

  However, this becomes a breaking change for those with, e.g. `- Home: index.md` in their `mkdocs.yml` file, but `docs/README.md` in their directory.

---

If all of that checks out!  I wonder if there's a path forward that doesn't involve a breaking change.

My understanding of the reasoning behind the addition of that `patchIndexPreBuild` function was to improve the "getting started" experience with TechDocs.  It's very common for folks to use `README.md` for index files, but all of the skeletons/documentation we have for TechDocs has folks setting up their `mkdocs.yml` file and having it point to `index.md`.  ...Consequently, we got a lot of reports of sites being broken when loaded (because we assume the index is set when linking to a doc's homepage).

We already parse/validate/modify the `mkdocs.yml` file as part of the generation process (see [this section from the relevant change](https://github.com/backstage/backstage/commit/bca27b366253f7cfd632d65e4bf402d04d14f414#diff-ddd013876d02c04e8ddaad2ac791a0310e9694046c3f8db9235afd648cd86054L93-L105))...  Perhaps we could make this `patchIndexPrebuild` step a little smarter by passing it the configured home `.md` file and intelligently copying (or not) based on it?  e.g.

- Home points to `index.md` and `docs/index.md` exists. Do nothing.
- Home points to `README.md` and `docs/README.md` exists. Do nothing.
- Home points to `index.md` and `docs/index.md` doesn't exist.  Try copying from fallbacks to `index.md`.
- Home points to `README.md` and `docs/README.md` doesn't exist. Try copying from fallbacks to `README.md`.

Whaddya think?

**Comment by ryanmrodriguez** [comment]
@iamEAP Your understanding of the problem is spot-on.

> If all of that checks out! I wonder if there's a path forward that doesn't involve a breaking change.

Let me see what I can come up with. Thanks for the review!

**Comment by camilaibs** [comment]
> @iamEAP Your understanding of the problem is spot-on.
> 
> > If all of that checks out! I wonder if there's a path forward that doesn't involve a breaking change.
> 
> Let me see what I can come up with. Thanks for the review!

Hi guys, did you come up with any other ideas? I'd like to follow along, please let us know when you're ready for review again 🙂

**Review by Rugvip — APPROVED** [review]
Just a 🟢 for the changeset :grin:

**Pull request closed without merging**
