### PR TITLE
Add Festive Fun plugin to microsite

### PR DESCRIPTION
**Pull request by benjmac**
Signed-off-by: Ben <mccain.ben2@gmail.com>

## Hey, I just made a Pull Request!

Add yaml file to microsite data to register the new Festive Fun plugin. Details about the plugin in the readme

https://github.com/benjmac/backstage-plugin-festive-fun

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Interesting plugin idea @benjmac, thanks for submitting it to the Plugin Directory! 🚀 

One totally optional comment: in the docs it would be nice to see a small video of it in action and not just the isolated images to get a feel for how it would look actually being used

**Comment by benjmac** [comment]
> Interesting plugin idea @benjmac, thanks for submitting it to the Plugin Directory! 🚀
> 
> One totally optional comment: in the docs it would be nice to see a small video of it in action and not just the isolated images to get a feel for how it would look actually being used

Agreed, working on building it out and adding a bit more!

**Comment by benjmac** [comment]
@awanlin I'm checking with prettier locally and not seeing the same error as the microsite workflow.

**Comment by awanlin** [comment]
> @awanlin I'm checking with prettier locally and not seeing the same error as the microsite workflow.

Same here, can you add a newline to the end of the file? A sample of the other files have one and it's the only thing I could think of that might make the build unhappy

**Comment by benjmac** [comment]
> > @awanlin I'm checking with prettier locally and not seeing the same error as the microsite workflow.
> 
> Same here, can you add a newline to the end of the file? A sample of the other files have one and it's the only thing I could think of that might make the build unhappy

Looks like that did the trick!

**Comment by awanlin** [comment]
This is good to go @tudi2d or @Rugvip 🚀

**Review by tudi2d — APPROVED** [review]
Love the idea! Thanks for adding this plugin ✨

**Comment by benjmac** [comment]
Awesome, thank you! What's the process like for merging in this directory?

**Pull request merged**
