### PR TITLE
scaffolder-backend: attempt to fix windows test errors in master

### PR DESCRIPTION
**Pull request by freben**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4320-zejl2znrsucwtpgigogg3adzi5ggnufz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6015b07698552d2371530335

**Review by jhaals — APPROVED** [review]
Thanks for taking a stab at fixing this 👍 
Looks like the tests in linux fail with unreachable code however o_O

**Comment by freben** [comment]
V8_Fatal 😱

**Comment by freben** [comment]
seems it was transient...

**Comment by OrkoHunter** [comment]
Ran the tests on this branch for `plugins/scaffolder-backend` on Windows. Here is the log https://pastebin.com/UCH2KnLz if that helps!

**Comment by freben** [comment]
Yes indeed that's helpful! Ok the absolute one I understand, just a missing slash in the original test - not sure about the other ones, will have to look into them later.

(Or if you manage to fix and push to this branch, that's fine too :))

**Comment by OrkoHunter** [comment]
Sure, yes! Let me give this a shot. 😁

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4320-zejl2znrsucwtpgigogg3adzi5ggnufz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6015b07698552d2371530335

**Comment by OrkoHunter** [comment]
All tests passing on Windows for scaffolder-backend. 💯 

(Sorry about the failing azure test in the logs. It just needed a `yarn install` to use the latest `git-url-parse` version having the feature to parse branch names for Azure URLs.)

**Comment by freben** [comment]
Yay!!

**Comment by jhaals** [comment]
Thanks for assisting @OrkoHunter ⭐ 

download

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4320-zejl2znrsucwtpgigogg3adzi5ggnufz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6015b07698552d2371530335

**Review by jhaals — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
