### PR TITLE
Add Nobl9 plugin to the Directory

### PR DESCRIPTION
**Pull request by skrolikiewicz**
## Hey team, I just made a Pull Request!

This PR lists the Nobl9 Backstage plugin in the Plugin Directory.

[Nobl9 Reliability Center](https://nobl9.com) promises a common understanding of service performance from business to technical stakeholders alike. Our SaaS-based platform sits on top of your current monitoring environment, allowing you to set service level objectives (SLOs) and track error budgets across all your platforms and applications.

We recently introduced a plugin that allows customers to view their SLOs directly in their Backstage installation.

Here is how the changes are rendered inside the Plugin directory:
image

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
This is a great plugin @skrolikiewicz - nice features and well written docs 🚀

**Comment by skrolikiewicz** [comment]
Awesome! Thanks for the fast response @awanlin

**Comment by awanlin** [comment]
You're welcome! Just need to get one more review and then we can merge, that might not come as fast. I tend to jump on new plugin PRs as I like to see what's being built out there 👍

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks! :tada:

**Pull request merged**
