### PR TITLE
Support dark/light mode in Storybook

### LINKED ISSUE #543: Support dark/light mode in Storybook
## Feature Suggestion

Make it possible to toggle dark/light mode inside Storybook. This will allow for easier verification that components behave correctly in both themes. 

## Possible Implementation

https://medium.com/encode/setting-up-storybook-with-material-ui-and-styled-components-5bdacb6db866

### PR DESCRIPTION
**Pull request by OrkoHunter**
## Hey, I just made a Pull Request!

Toggle between Backstage light and dark theme for the Storybook.

Closes https://github.com/spotify/backstage/issues/543

# Screenshots

Dark mode
Screen Shot 2020-04-20 at 17 20 16
Light mode
Screen Shot 2020-04-20 at 17 20 00

The toggle button is on the top.
Screen Shot 2020-04-20 at 17 22 33

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Let's use the deploy preview and test this. 🎉

**Comment by katz95** [comment]
@OrkoHunter thanks for your work on this! is it possible to make the background behind the components dark as well? if you could make the background color #181818, that would be amazing! also, do you know if it's possible to change the percentage type color to #FFFFFF?

**Comment by OrkoHunter** [comment]
Hi @katz95 !

> is it possible to make the background behind the components dark as well?

Yes, I hope so. That must belong to Storybook color configuration. Let me find a way to make Storybook use Backstage theme for its background.

> do you know if it's possible to change the percentage type color to #FFFFFF for accessibility?

Sure! I believe, this requires changes to the Progress card component.

The deploy preview is ready [here](https://deploy-preview-599--goofy-bose-cf594c.netlify.app/). Can you take a look and let me know if there are more issues? Thank you.

**Comment by OrkoHunter** [comment]
I updated the CircleProgress component to use a `textContrast` color which is white (#FFF) for dark background, and black (#000) for white background.

Screen Shot 2020-04-20 at 17 59 37 

Screen Shot 2020-04-20 at 17 59 43

**Review by Rugvip — COMMENTED** [review]
👍 , imo the background in dark mode is the only fix needed in this PR.

Would be good to merge this and fix the component styles in followup PRs / issues.

**Comment by katz95** [comment]
@OrkoHunter NICE thank you!

**Comment by OrkoHunter** [comment]
@katz95 As with the color of Storybook background, I am afraid I don't have a quick fix. The method in this PR, wraps the components in Storybook and changes their colors. But the background color (white in the screenshots) is beyond these themes' scope.

I will create another issue to handle it.

**Comment by Rugvip** [comment]
> @katz95 As with the color of Storybook background, I am afraid I don't have a quick fix. The method in this PR, wraps the components in Storybook and changes their colors. But the background color (white in the screenshots) is beyond these themes' scope.
> 
> I will create another issue to handle it.

Can we add a decorator that wraps every page with a themed background?

**Comment by OrkoHunter** [comment]
> Can we add a decorator that wraps every page with a themed background?

Oh, interesting! I will give that a try. I'll note this as a `Possible Implementation` for the new issue. :)

**Review by stefanalund — APPROVED** [review]

**Review by Rugvip — APPROVED** [review]
:shipit:

**Comment by OrkoHunter** [comment]
Thanks for the review @Rugvip @katz95 @stefanalund :)

**Pull request merged**
