### PR TITLE
Adopting metrics page

### PR DESCRIPTION
**Pull request by Rymania**
Added a metric on Actions minutes to display a trend in automation - template adoption and reuse being the main driver. Added another on template reuse to show if Backstage if giving teams what they need.

Signed-off-by: Adam Ryman <adam.j.ryman@gmail.com>

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @Rymania it looks like there's a few things failing here in the workflows, could you fix them up :pray:

**Review by Rugvip — COMMENTED** [review]
Some CI checks that need to be taken care of indeed. In this case DCO + formatting of the document

**Comment by Rymania** [comment]
Hi @Rugvip @benjdlambert - sorry for the slow response here. I have just been looking at options to revert.

Both commits have the sign-off in the commit message, unless I have misread the instructions. I can see that code styling needs be corrected, so I'll take a look and send another commit.

**Comment by benjdlambert** [comment]
Looking at the error message it looks like the signing is wrong with the wrong email? https://github.com/backstage/backstage/pull/10324/checks?check_run_id=5611191583

**Comment by benjdlambert** [comment]
And I think you will want to run `yarn prettier ./docs/overview/adopting.md --write` and commit the change from that command too.

**Pull request closed without merging**
