### PR TITLE
Fixed typo in 05-extension-overrides.md

### PR DESCRIPTION
**Pull request by marleypowell**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Good catch @marleypowell 🚀

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
oh it wants you to run prettier on the file first - it looks good but maybe something had slipped in from a previous PR? I'll enable automerge for now, but it does need a prettier run

**Comment by marleypowell** [comment]
> oh it wants you to run prettier on the file first - it looks good but maybe something had slipped in from a previous PR? I'll enable automerge for now, but it does need a prettier run

I've actually fixed a few other things in the docs which might need review.

**Review by awanlin — APPROVED** [review]
Thanks for these additional corrections 👍

**Pull request merged**
