### PR TITLE
Auth types fix + GitLab audience is optional

### PR DESCRIPTION
**Pull request by timbonicus**
Signed-off-by: Tim Hansen <timbonicus@gmail.com>

Minor fix to auth config types, `development` was hard-coded as the only auth environment. Also makes GitLab `audience` optional, since it's defaulted in the auth-backend code. Working on documentation that I can update with the change.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Don't forget the changeset!

**Review by Rugvip — APPROVED** [review]
:shipit:! (with a changeset)

**Comment by freben** [comment]
so apparently the last commit was of such poor quality that it made the documentation quality check build step explode.

**Comment by benjdlambert** [comment]
https://github.com/errata-ai/vale-action/issues/33

**Comment by timbonicus** [comment]
@freben Someone's got to lower the bar around here, to code quality is too damn high!

**Pull request merged**
