### PR TITLE
Added documentation for debugging with WebStorm

### PR DESCRIPTION
**Pull request by jrtaylorJH**
## Hey, I just made a Pull Request!

Added some simple documentation about enabling of debugging the Backstage backend with the WebStorm IDE.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by benjdlambert — APPROVED** [review]
Nice, thanks! :tada:

**Comment by benjdlambert** [comment]
Looks like you'll need to run prettier on the `docs/local-dev/debugging.md` file in order to get this to pass.

**Comment by benjdlambert** [comment]
Nevermind - I went ahead and fixed this up for you 👍

**Comment by jrtaylorJH** [comment]
> Nevermind - I went ahead and fixed this up for you 👍

Great, thank you!

**Pull request merged**
