### PR TITLE
Draft: Preliminary additions to allow passing of Swagger UI plugins

### PR DESCRIPTION
**Pull request by whitemanthedj**
Signed-off-by: awhiteman <awhiteman@qualtrics.com>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — CHANGES_REQUESTED** [review]
Is there some additional context to this contribution? 
We are not able to add `swaggerPlugins` directly on the API entity type as it's too specific, you could use your own custom kind if you use this internally or rely on annotations instead.
There's also close to 7k changes to yarn lock currently.

**Comment by whitemanthedj** [comment]
Yes sorry, this is still a draft, I have to refactor these changes for the typing to allow for the swagger plugins to be sent properly (using annotations). The context is in this [issue](https://github.com/backstage/backstage/issues/14824), but I was unable to add the issue to the PR.

**Comment by jhaals** [comment]
> Yes sorry, this is still a draft, I have to refactor these changes for the typing to allow for the swagger plugins to be sent properly (using annotations). The context is in this [issue](https://github.com/backstage/backstage/issues/14824), but I was unable to add the issue to the PR. Also the E2E tests seem to be failing at yarn tsc on files I have not touched, is this typical?

Thanks for the context, I believe you want these to be provided as annotations as we're not able to add these directly on the Entity type. Are these plugins specific to each Entity or are we able to provide/configure a static set of plugins instead?
Looks like there's a yarn.lock merge conflict, It could be the reason for the unrelated type errors.

**Comment by whitemanthedj** [comment]
I made a less generic [PR](https://github.com/backstage/backstage/pull/15247) for the specific plugins I have a use case for using the annotations and without the merge conflicts. And adding a static configuration for a plugin is probably not a bad idea, but the use case for me is to have each API set whether or not to disable the try-it / authorize buttons on the API's Swagger page, so that would be at the Entity level I believe.

**Pull request closed without merging**
