### PR TITLE
Change AWS Cloud Accounts from Component to Resource

### PR DESCRIPTION
**Pull request by backjo**
## Hey, I just made a Pull Request!

Change output of AWS Organization Processor from Component -> Resource. 

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [X] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by freben** [comment]
Nice. I wonder what the blast radius of this is, in terms of number of people affected that are using the old classification. Hopefully very small, since this is a relatively new addition.

**Comment by freben** [comment]
Any entities emitted by an old version of this will stay around in the database. Just noting. So there will be a period of doubles.

**Comment by backjo** [comment]
Yep - I imagine usage is quite small since it's only been around a few weeks -

**Review by Rugvip — APPROVED** [review]
👍 

I'd say the fact that the old entities stick around in the catalog is a general issue with the catalog and shouldn't block this PR

**Comment by freben** [comment]
Merge?

**Pull request merged**
