### PR TITLE
fix: remove hardcoded min height in page header

### PR DESCRIPTION
**Pull request by ryanvazquez**
Signed-off-by: Ryan Vazquez <ryanv@spotify.com>

## Hey, I just made a Pull Request!

The `min-height` property set on the `<Header />` component in `@backstage/core-components` is causing the header to overflow into the page content area. This value is currently hardcoded 🙀 

## Before
Screen Shot 2021-09-10 at 5 42 58 PM

## After
Screen Shot 2021-09-10 at 5 43 11 PM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
OK - So I think I'm pretty happy to let this be a non-fixed height, I tried to trace back through the history to find if there was some reason why, but It doesn't look that way.

But I think we should drop the margins off the title and the title wrapper if that's possible to make sure the height is driven by the content and the content is centered, otherwise it looks a little strange as the header is never gonna be in the middle.

When the height was fixed the header doesn't change height based on it's children, so you don't really notice but with a non fixed height it's somewhat noticeable when it's sized on the children. I know it's technically the current behaviour, but I think we should fix at the same time if that's ok? 👍 

**before**
before

**after**
after

**Comment by ryanvazquez** [comment]
> But I think we should drop the margins off the title and the title wrapper if that's possible to make sure the height is driven by the content and the content is centered, otherwise it looks a little strange as the header is never gonna be in the middle.

Ah, good eye, we def want to keep that centered. One gotcha though is that removing the bottom margin on the title may not leave much breathing space if a subtitle prop is provided:

### No Bottom Margin, With Subtitle
Screen Shot 2021-09-11 at 10 29 16 AM

### Bottom Margin, With Subtitle
Screen Shot 2021-09-11 at 10 31 18 AM

But we could simply enable the bottom margin if the subtitle prop is provided.

**Comment by benjdlambert** [comment]
Think that works yep!

**Comment by freben** [comment]
Or give the subtitle a top margin? :) Since that one should never appear without the main title.

I think I have some background for why this had a min height. It was to prevent jank/reflow, and to provide a consistent experience in some corner cases.

In pre-`useEntity` days, the page was rendered before the entity was fully loaded. The header was initially drawn basically empty. Then when the entity data arrived, it was redrawn with the correct info whose occupied space now typically pushed down the bottom of the header. And since some fields were optional and only appeared if certain conditions were met, it was tough to know how large to make it. Some min size was picked that worked for 99% of the cases without changing size unexpectedly. It was pretty jarring before the fix.

Well now we have the data beforehand, so this probably no longer applies. :) Unless one places stuff in it again which loads in asynchronously

**Comment by freben** [comment]
Oh and one more thing. Some pages always had a subtitle (entity pages for example), and some didn't. When navigating around the interface across various page types, the header bottom jumped up and down a lot. I guess it will again, after this fix. Maybe that's not a big deal though

**Comment by ryanvazquez** [comment]
> Or give the subtitle a top margin? :) Since that one should never appear without the main title.

👍 

> When navigating around the interface across various page types, the header bottom jumped up and down a lot. I guess it will again, after this fix.

Hm, yeah. I don't like the idea of trading one bug for another. But in our case, the fixed height literally obscures our tab menu, which is pretty breaking UX-wise.

**Comment by freben** [comment]
Yeah to be clear i stil think you're doing the right thing here.

**Review by benjdlambert — APPROVED** [review]

**Comment by freben** [comment]
bit late to the game, but here's one example of a header that janks (even before this change) https://demo.backstage.io/docs/default/component/backstage

It bugs me a little even though it does kinda fall into nitpick territory

**Comment by ryanvazquez** [comment]
> It bugs me a little even though it does kinda fall into nitpick territory

@freben Happy to take a second pass at this. Maybe theres a CSS workaround that isn't too funky.

**Pull request merged**
