### PR TITLE
fix(website): update links and package names for plugins we migrated from janus-idp to community-plugins

### PR DESCRIPTION
**Pull request by christoph-jerolimov**
## Hey, I just made a Pull Request!

This updates a bunch of plugin entries on https://backstage.io/plugins/ from Janus-IDP to Backstage community plugins after we (Red Hat) migrated these plugins and deprecated the old links.

~~I'll keep that as a draft until I've checked whether we want to link the READMEs on GitHub or any other publicly available documentation.~~

I confirmed with our team/pm that the READMEs in Backstage community plugins are fine for now.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thank you!  :+1:

**Comment by christoph-jerolimov** [comment]
@Rugvip thanks for review. I confirmed with our team/pm that the READMEs in Backstage community plugins are fine for now.

**Comment by christoph-jerolimov** [comment]
@Rugvip, thanks for approving it, but what's next or missing? Do you want merge it or will someone else take a look?

**Comment by christoph-jerolimov** [comment]
Sorry @Rugvip @freben, I know you are all busy, but can you merge this?

**Comment by benjdlambert** [comment]
Sorry for the delay! :tada:

**Pull request merged**
