### PR TITLE
Removal of RSC-Labs plugins from public preview

### PR DESCRIPTION
**Pull request by radoslaw-sz**
## Hey, I just made a Pull Request!

Due to different direction of development of RSC-Labs, we need to remove Backstage plugins from public preview and archive them.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @radoslaw-sz, I have a feeling this is NOT what you intended, you're deleting a lot of files here.

I think you just want to delete the single file you added here: https://github.com/backstage/backstage/pull/20728/files

**Comment by radoslaw-sz** [comment]
hi @awanlin - oh my god, sorry for that - the last commit did not suppose to land in this pull request, I will revert it. Only two single files needs to be removed.

**Comment by radoslaw-sz** [comment]
hi @awanlin  - fixed :)

**Comment by radoslaw-sz** [comment]
> Thanks for the contribution! All commits need to be DCO signed before they are reviewed. Please refer to the the [DCO section in CONTRIBUTING.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) or the [DCO](https://github.com/backstage/backstage/runs/32027521728) status for more info.

I have added signed-off to the last commit, I hope it is ok now.

**Review by Rugvip — APPROVED** [review]
Alright! 👍

**Pull request merged**
