### PR TITLE
exported DEFAULT_SCAFFOLDER_FIELD_EXTENSIONS

### PR DESCRIPTION
**Pull request by ionition**
## Hey, I just made a Pull Request!

I exported DEFAULT_SCAFFOLDER_FIELD_EXTENSIONS.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@ionition what's the use case here? We've avoided exporting these as the `Extension` form is exported, and in order to use those you could do something like this: 

```ts
const customFieldExtensions = useCustomFieldExtensions<FieldExtensionOptions>(
  <ScaffolderFieldExtensions>
    <RepoUrlPickerFieldExtension />
    ...
  </ScaffolderFieldExtensions>
);
```

**Comment by ionition** [comment]
Hi @benjdlambert , I aim to enable the modification of an Entity using the template that was initially used to create it. To achieve this, I plan to use the component backstage/plugins/scaffolder-react/src/next/components/Workflow/Workflow.tsx. I can autofill the form by using the initialState prop. However, the extensions prop is also required. This prop represents a combination of customFieldExtensions and DEFAULT_SCAFFOLDER_FIELD_EXTENSIONS. Unfortunately, DEFAULT_SCAFFOLDER_FIELD_EXTENSIONS is not currently exported, making it impossible to use the Workflow component with the default extensions.

**Comment by acierto** [comment]
Hey @ionition, you can provide your custom Workflow like this:

```

    <Route
      element={
        <ScaffolderPage
          components={{
            EXPERIMENTAL_TemplateWizardPageComponent: CustomTemplateWizardPage
           }}
          ...
      />
```

**Comment by ionition** [comment]
I will check acierto version and come back with an update

**Comment by ionition** [comment]
@acierto thank you, your solution worked for me.

**Pull request closed without merging**
