### PR TITLE
Making the scaffolder template more dynamic.

### PR DESCRIPTION
**Pull request by acierto**
Signed-off-by: bnechyporenko <bnechyporenko@bol.com>

## Hey, I just made a Pull Request!

As a user I would like to have some steps to be visible/hidden based on the values provided in another fields (togglers). 

Example of template using this feature: https://github.com/acierto/software-templates/blob/main/scaffolder-templates/docs-template-experiment/template.yaml:

Screenshot 2022-10-27 at 15 50 36

Screenshot 2022-10-27 at 15 50 30

Enabling/disabling the checkbox reflects the change in the form immediately. 

A bit more of context about that request.

We would like in bol.com to give a possibility to provision new services in GCP with a bunch of pre-configured resources. 
But which exactly resources will be included to the service will be decided in the wizard. 

So that when the user wish to include for example PubSub, this checkbox has to be checked and the appropriate step will be present to fill in details about PubSub. But if it's not required for this service to include PubSub, it's possible to exclude it, and no need to feel in those details, and even see unnecessary steps/fields in the wizard. 

https://react-jsonschema-form.readthedocs.io/en/latest/usage/dependencies/ supports only dynamic fields inside the same step. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Is this not available through jsonschema directly using dependencies? I think there’s examples on react-jsonschema-form playground? Not really sure we want to grow the api surface in this way if we can do it already.

**Comment by acierto** [comment]
@benjdlambert What i see from examples, it allows to hide the properties of the same schema only (so at case of software template -> properties inside one step). But I don't see a way to hide the whole step, as it's across the schema's. So yeah, that case can be removed from PR, but hiding step still relevant.

Please point me if i'm wrong.

**Comment by acierto** [comment]
Cleaned the PR: 
* Removed hiding of properties inside the step supported by https://react-jsonschema-form.readthedocs.io/en/latest/usage/dependencies/ 
* Left only the possibility to hide the steps.

**Comment by acierto** [comment]
Ok, I'd better wait for a new UI release. 
As an interim I can copy paste the full scaffolder folder to the project and do that modification.

**Comment by benjdlambert** [comment]
OK - do you mind if we close this PR for now until we have v2 shipped and we can come back to it?

**Pull request closed without merging**
