### PR TITLE
color change for like and dislike icons in entity feedback

### PR DESCRIPTION
**Pull request by AmbrishRamachandiran**
## Hey, I just made a Pull Request!

 Added colors for like dislike icons so that it will cover user attention more.
     
image

image

image

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by camilaibs — CHANGES_REQUESTED** [review]
Thanks for the suggestion, 
For now we are not sure if we should proceed this change, because we cannot assume that the primary and secondary colors can be used in this way. To be honest,  we want to keep the icons colors as they are for now.

**Comment by AmbrishRamachandiran** [comment]
> 



> Thanks for the suggestion, For now we are not sure if we should proceed this change, because we cannot assume that the primary and secondary colors can be used in this way. To be honest, we want to keep the icons colors as they are for now.

@camilaibs Yes ! many place it is used like this FYI! [check here](https://github.com/backstage/backstage/blob/06e50f7381acb3a8a849d455ef24672f43b69db7/plugins/playlist/src/components/PlaylistPage/PlaylistHeader.tsx#L204)


To be honest, we want to keep the icons colors as they are for now
it is good to keep the icons color for example check the screenshot of same like,dislike screen in material ui 

image

image

**Comment by Rugvip** [comment]
@AmbrishRamachandiran in the example you linked the color of the delete button isn't necessarily what conveys the intent of the button, it's just a separate accent to put it apart from the rest. The indicator of the destructive action is really that it says "delete".

Even in the MUI docs you see that the 👍 / 👎  buttons are not colored by default. The color is used as an indicator for which option is selected. In our case we do that using the outline vs filled icon. The MUI buttons do use the `palette.error.main` color for the button, which I think would be the correct choice if we want to use some color.

In the end we don't want the UI to be overly colorful, especially not for actions like these that don't really need to pop out. These are cards that present an optional action to the user, I don't think we should bring additional attention to it.

**Comment by camilaibs** [comment]
> > 
> 
> > Thanks for the suggestion, For now we are not sure if we should proceed this change, because we cannot assume that the primary and secondary colors can be used in this way. To be honest, we want to keep the icons colors as they are for now.
> 
> @camilaibs Yes ! many place it is used like this FYI! [check here](https://github.com/backstage/backstage/blob/06e50f7381acb3a8a849d455ef24672f43b69db7/plugins/playlist/src/components/PlaylistPage/PlaylistHeader.tsx#L204)
> 
> To be honest, we want to keep the icons colors as they are for now it is good to keep the icons color for example check the screenshot of same like,dislike screen in material ui
> 
> image
> 
> image


Hi @AmbrishRamachandiran, I will be sharing your points with our team again 🙂 . What concerned us the first time we looked at the PR is that the [secondary colors are intended to sparingly highlight parts of the UI ](https://m2.material.io/design/color/the-color-system.html#color-theme-creation) and this might not be the case with a dislike button. We ask ourselves, do we want to highlight the dislike action? And the answer was, we don't have a reason for highlighting it. The "cancel" button you shared is a secondary action that I more clearly see the point of highlighting, in this case, we want to bring the user's attention to the deletion as something they really need to be sure of before they click. But the like and dislike buttons seem to have the same weight, in the sense that we don't want to highlight one in comparison to the other... That was our initial thoughts, I'll talk to the team again and get back to you 🙌🏻

**Comment by camilaibs** [comment]
> > > 
> > 
> > 
> > > Thanks for the suggestion, For now we are not sure if we should proceed this change, because we cannot assume that the primary and secondary colors can be used in this way. To be honest, we want to keep the icons colors as they are for now.
> > 
> > 
> > @camilaibs Yes ! many place it is used like this FYI! [check here](https://github.com/backstage/backstage/blob/06e50f7381acb3a8a849d455ef24672f43b69db7/plugins/playlist/src/components/PlaylistPage/PlaylistHeader.tsx#L204)
> > To be honest, we want to keep the icons colors as they are for now it is good to keep the icons color for example check the screenshot of same like,dislike screen in material ui
> > image
> > image
> 
> Hi @AmbrishRamachandiran, I will be sharing your points with our team again 🙂 . What concerned us the first time we looked at the PR is that the [secondary colors are intended to sparingly highlight parts of the UI ](https://m2.material.io/design/color/the-color-system.html#color-theme-creation) and this might not be the case with a dislike button. We ask ourselves, do we want to highlight the dislike action? And the answer was, we don't have a reason for highlighting it. The "delete" button you shared is a secondary action that I more clearly see the point of highlighting, in this case, we want to bring the user's attention to the deletion as something they really need to be sure of before they click. But the like and dislike buttons seem to have the same weight, in the sense that we don't want to highlight one in comparison to the other... That was our initial thoughts, I'll talk to the team again and get back to you 🙌🏻

@Rugvip just replied to us [here](https://github.com/backstage/backstage/pull/19491#issuecomment-1687983467) 🙌🏻 , let us know if the answer makes sense to you too  @AmbrishRamachandiran 🙂 . And thanks again for the questions!

**Comment by AmbrishRamachandiran** [comment]
@camilaibs @Rugvip Make sense Thank you closing this PR!

**Pull request closed without merging**
