### PR TITLE
fix(GithubLocationAnalyzer): support github app auth & authenticated backends

### PR DESCRIPTION
**Pull request by kuangp**
Signed-off-by: Phil Kuang <pkuang@factset.com>

## Hey, I just made a Pull Request!

This fixes the way the `GithubLocationAnalyzer` was grabbing tokens for Github requests to be able to support either PAT or Github App auths. This change also adds support for authenticated backends by forwarding server tokens. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by kuangp** [comment]
cc: @kissmikijr since you introduced this in https://github.com/backstage/backstage/pull/13800

**Review by freben — COMMENTED** [review]
Nice!

**Comment by kuangp** [comment]
@freben updated based on your comments, thanks for the tip!

**Review by freben — APPROVED** [review]
Alright!

**Pull request merged**
