### PR TITLE
Fix overflow issue for mic drop 404 image

### PR DESCRIPTION
**Pull request by sblausten**
Signed-off-by: sblausten <sam@roadie.io>

## Hey, I just made a Pull Request!

On an embedded Tech Docs page that has a height below ~800px the Mic Drop image starts overflowing into headers and can obscure tabs in certain views. 

The image also flows over the top of the page on a normal 404 page when the height is below 550px.

### Before:
Screenshot 2022-09-12 at 11 27 22
Screenshot 2022-09-12 at 13 05 09

### After:
Screenshot 2022-09-12 at 11 28 41
Screenshot 2022-09-12 at 11 39 06

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by sblausten** [comment]
The tests probably just need a rerun as they failed to fetch `Error: fatal: unable to access 'https://github.com/backstage/backstage/': Failed to connect to github.com port 443: Connection refused` ?

**Review by freben — APPROVED** [review]
Thanks!

**Comment by freben** [comment]
Oh, let me just ask a question first. Did you try to play with the window width after this fix? The old code kind of reads like it tried to avoid some extreme cases for small windows, such that the image ended up completely overwriting all the textual content next to it. I'd appreciate if you could just report back with having tried all window widths from extremely narrow up to full screen, and it looking OK for all those cases

**Comment by sblausten** [comment]
> Oh, let me just ask a question first. Did you try to play with the window width after this fix? The old code kind of reads like it tried to avoid some extreme cases for small windows, such that the image ended up completely overwriting all the textual content next to it. I'd appreciate if you could just report back with having tried all window widths from extremely narrow up to full screen, and it looking OK for all those cases

Yes I did but let me grab some screenshots and re-check.

**Comment by freben** [comment]
@sblausten Alright, would appreciate that!

**Comment by sblausten** [comment]
Screenshot 2022-09-19 at 14 17 45
Screenshot 2022-09-19 at 14 17 45
Screenshot 2022-09-19 at 14 18 32

Looks good

**Comment by freben** [comment]
@sblausten Alright. Only tweak I can see in there, is that the text elements ("Looks like ..." etc) have line breaks unnecessarily which leads to a lot of whitespace to the right. The grid cell that they are constrained by should probably be full width at that point.

And there's probably room for making the image scale to fit its container. Imagine that it'd all be wrapped by a Grid layout, and that in xs size, the text cell is 12 items large and so is the image cell. But in lg size, the text cell is 4 wide and the image cell 8 wide.

But not a huge deal. This is still an improvement and we can tweak more later

**Pull request merged**
