### PR TITLE
Added alert popup whenever user link/unlink entity with project

### PR DESCRIPTION
**Pull request by AmbrishRamachandiran**
## Hey, I just made a Pull Request!

Added alert popup whenever user link entity to the project

Screenshot 2023-10-26 160214

Added alert popup whenever user unlink entity from the project

Screenshot 2023-10-26 160505

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by AmbrishRamachandiran** [comment]
@Rugvip @tudi2d  please review

**Comment by freben** [comment]
@AmbrishRamachandiran You really shouldn't ping people, especially at the beginning. There's no reason to since we use review queues and work as fast as we can anyway at getting through our review queues.

**Comment by AmbrishRamachandiran** [comment]
Please reopen @freben

**Comment by AmbrishRamachandiran** [comment]
Dont stale @freben

**Review by freben — APPROVED** [review]

**Pull request merged**
