### PR TITLE
Jenkins plugin

### PR DESCRIPTION
**Pull request by timja**
## Hey, I just made a Pull Request!

This creates an initial Jenkins plugin based off of the scaffolding done by @dtuite in https://github.com/spotify/backstage/pull/1386

build-details
folder-results
last-master-build

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality <- Haven't added any new ones yet, will take a look at CircleCI / GitHub actions for some inspiration, <- checked, this has just as many tests as those 🤷 
- [na] Regression tests added for bug fixes

### CODE REVIEW

**Review by splisson-altair — APPROVED** [review]
lgtm

**Comment by stefanalund** [comment]
This is awesome! I’m sure this is going to be one of the more popular plugins 😍

**Comment by stefanalund** [comment]
@timja looking forward to getting this merged! Needs to be rebased though.

**Comment by timja** [comment]
> @timja looking forward to getting this merged! Needs to be rebased though.

the conflicts are trivial and I've already rebased a couple of times.
Would appreciate a review before I spend time on it,

or anyone else is welcome to rebase before merge

thanks :)

**Comment by freben** [comment]
I have it rebased and am looking at it overall right now. Not sure I would be able to push to your fork though.

**Comment by timja** [comment]
@freben you have access to my fork I would just suggest pushing there

**Comment by freben** [comment]
build failing due to a missing dep in master, being fixed in https://github.com/spotify/backstage/pull/1920 , will rebase again after that

**Comment by timja** [comment]
@freben this waiting on anything now?

**Comment by freben** [comment]
Nope! Am in a meeting is all :)

**Review by freben — APPROVED** [review]

**Comment by timja** [comment]
Thanks!

**Pull request merged**
