### PR TITLE
#643 - Include @types/react-helmet@^5.0.15 to backstage 

### PR DESCRIPTION
**Pull request by riginoommen**
## Hey, I just made a Pull Request!

In relation to #643. I have included the package ```@types/react-helmet@^5.0.15``` to resolve this issue 
#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Relevant documentation updated
- [x] Prettier run on changed files

### CODE REVIEW

**Review by Rugvip — CHANGES_REQUESTED** [review]
Hi! Looks like you're trying to do an install with npm instead of yarn. package-lock.json shouldn't be in this repo.

**Comment by riginoommen** [comment]
> Hi! Looks like you're trying to do an install with npm instead of yarn. package-lock.json shouldn't be in this repo.

Just fixed it

**Comment by freben** [comment]
We don't want to add dependencies to the root though; the packages should be standalone and claim all their respective needs themselves.

I don't have a fix at hand right now (am not at my computer), but indeed it seems you were able to fetch that package that the initial error said it couldn't, right?

**Comment by riginoommen** [comment]
> We don't want to add dependencies to the root though; the packages should be standalone and claim all their respective needs themselves.
> 
> I don't have a fix at hand right now (am not at my computer), but indeed it seems you were able to fetch that package that the initial error said it couldn't, right?

The actual error was ```yarn install``` was ```error Couldn't find package "@types/react-helmet@^5.0.15" required by "@backstage/core@0.1.1-alpha.4" on the "npm" registry.
```

**Comment by freben** [comment]
I believe this was fixed by #645

**Pull request closed without merging**
