### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by backstage-service**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and publish to npm yourself or [setup this action to publish automatically](https://github.com/changesets/action#with-publishing). If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
### Minor Changes

-   21fddf452: Make `techdocsStorageApiRef` and `techdocsApiRef` use interfaces instead of the
    actual implementation classes.

    This renames the classes `TechDocsApi` to `TechDocsClient` and `TechDocsStorageApi`
    to `TechDocsStorageClient` and renames the interfaces `TechDocs` to `TechDocsApi`
    and `TechDocsStorage` to `TechDocsStorageApi` to comply the pattern elsewhere in
    the project. This also fixes the types returned by some methods on those
    interfaces.

### Patch Changes

-   6fbd7beca: Use `EntityRefLink` in header and use relations to reference the owner of the
    document.
-   15cbe6815: Fix TechDocs landing page table wrong copied link
-   39bdaa004: Add customization and exportable components for TechDocs landing page
-   cb8c848a3: Disable color transitions on links to avoid issues in dark mode.
-   17915e29b: Rework state management to avoid rendering multiple while navigating between pages.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/core@0.7.7

### Patch Changes

-   9afcac5af: Allow passing NavLinkProps to SidebarItem component to use in NavLink
-   e0c9ed759: Add `if` prop to `EntityLayout.Route` to conditionally render tabs
-   6eaecbd81: Improve owner example value in `MissingAnnotationEmptyState`.

 ## @backstage/create-app@0.3.20

### Patch Changes

-   73f3f5d78: Updates the end to end test in the app to match the new catalog index page title. To apply this change to an existing app, update `packages/app/cypress/integration/app.js` to search for `"My Company Catalog"` instead of `"My Company Service Catalog"`.
-   Updated dependencies [1ce80ff02]
-   Updated dependencies [4c42ecca2]
-   Updated dependencies [c614ede9a]
-   Updated dependencies [9afcac5af]
-   Updated dependencies [07a7806c3]
-   Updated dependencies [f6efa71ee]
-   Updated dependencies [19a4dd710]
-   Updated dependencies [a99e0bc42]
-   Updated dependencies [dcd54c7cd]
-   Updated dependencies [da546ce00]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6fbd7beca]
-   Updated dependencies [15cbe6815]
-   Updated dependencies [39bdaa004]
-   Updated dependencies [cb8c848a3]
-   Updated dependencies [21fddf452]
-   Updated dependencies [17915e29b]
-   Updated dependencies [a1783f306]
-   Updated dependencies [6eaecbd81]
-   Updated dependencies [23769512a]
-   Updated dependencies [1a142ae8a]
    -   @backstage/plugin-api-docs@0.4.12
    -   @backstage/plugin-github-actions@0.4.4
    -   @backstage/plugin-catalog-import@0.5.4
    -   @backstage/plugin-explore@0.3.4
    -   @backstage/plugin-lighthouse@0.2.15
    -   @backstage/core@0.7.7
    -   @backstage/plugin-scaffolder@0.9.2
    -   @backstage/plugin-catalog@0.5.6
    -   @backstage/plugin-catalog-backend@0.8.1
    -   @backstage/plugin-search@0.3.5
    -   @backstage/plugin-techdocs@0.9.0
    -   @backstage/plugin-scaffolder-backend@0.10.1

 ## @backstage/techdocs-common@0.5.1

### Patch Changes

-   f4af06ebe: Gracefully handle HTTP request failures in download method of AzureBlobStorage publisher.

 ## @backstage/plugin-api-docs@0.4.12

### Patch Changes

-   1ce80ff02: Resolve issues with AsyncAPI rendering by updating `@asyncapi/react-component`
    to `0.23.0`. The theming of the component is adjusted to the latest styling
    changes.
-   c614ede9a: Updated README to have up-to-date install instructions.
-   07a7806c3: Added fields filtering in get API entities to avoid the requesting of unused data
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-bitrise@0.1.2

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-catalog@0.5.6

### Patch Changes

-   19a4dd710: Removed unused `swr` dependency.
-   da546ce00: Support `gridItem` variant for `EntityLinksCard`.
-   e0c9ed759: Add `if` prop to `EntityLayout.Route` to conditionally render tabs
-   1a142ae8a: Switch out the time-based personal greeting for a plain title on the catalog index page, and remove the clocks for different timezones.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-catalog-backend@0.8.1

### Patch Changes

-   a99e0bc42: Entity lifecycle and owner are now indexed by the `DefaultCatalogCollator`. A `locationTemplate` may now optionally be provided to its constructor to reflect a custom catalog entity path in the Backstage frontend.
-   Updated dependencies [e1e757569]
    -   @backstage/plugin-search-backend-node@0.1.4

 ## @backstage/plugin-catalog-import@0.5.4

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-circleci@0.2.13

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-code-coverage-backend@0.1.3

### Patch Changes

-   d47c2628b: Include migrations

 ## @backstage/plugin-cost-insights@0.8.5

### Patch Changes

-   b98de52ae: Support a `name` prop for Projects for display purposes
-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-explore@0.3.4

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-fossa@0.2.6

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-github-actions@0.4.4

### Patch Changes

-   4c42ecca2: Wrap EmptyState in Card
-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-github-deployments@0.1.4

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-graphiql@0.2.10

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-jenkins@0.4.2

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-lighthouse@0.2.15

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-pagerduty@0.3.3

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-register-component@0.2.14

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-rollbar@0.3.4

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-scaffolder@0.9.2

### Patch Changes

-   f6efa71ee: Enable starred templates on Scaffolder frontend
-   19a4dd710: Removed unused `swr` dependency.
-   23769512a: Support `anyOf`, `oneOf` and `allOf` schemas in the scaffolder template.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-scaffolder-backend@0.10.1

### Patch Changes

-   a1783f306: Added the `nebula-preview` preview to `Octokit` for repository visibility.

 ## @backstage/plugin-search@0.3.5

### Patch Changes

-   dcd54c7cd: Use `RouteRef` to generate path to search page.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-search-backend-node@0.1.4

### Patch Changes

-   e1e757569: Introduced Scheduler which is responsible for adding new tasks to a schedule together with it's interval timer as well as starting and stopping the scheduler processes.

 ## @backstage/plugin-sentry@0.3.9

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## @backstage/plugin-sonarqube@0.1.17

### Patch Changes

-   c614ede9a: Updated README to have up-to-date install instructions.
-   Updated dependencies [9afcac5af]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6eaecbd81]
    -   @backstage/core@0.7.7

 ## example-app@0.2.26

### Patch Changes

-   Updated dependencies [1ce80ff02]
-   Updated dependencies [b98de52ae]
-   Updated dependencies [4c42ecca2]
-   Updated dependencies [c614ede9a]
-   Updated dependencies [9afcac5af]
-   Updated dependencies [07a7806c3]
-   Updated dependencies [f6efa71ee]
-   Updated dependencies [19a4dd710]
-   Updated dependencies [dcd54c7cd]
-   Updated dependencies [da546ce00]
-   Updated dependencies [e0c9ed759]
-   Updated dependencies [6fbd7beca]
-   Updated dependencies [15cbe6815]
-   Updated dependencies [39bdaa004]
-   Updated dependencies [cb8c848a3]
-   Updated dependencies [21fddf452]
-   Updated dependencies [17915e29b]
-   Updated dependencies [6eaecbd81]
-   Updated dependencies [23769512a]
-   Updated dependencies [1a142ae8a]
    -   @backstage/plugin-api-docs@0.4.12
    -   @backstage/plugin-cost-insights@0.8.5
    -   @backstage/plugin-github-actions@0.4.4
    -   @backstage/plugin-catalog-import@0.5.4
    -   @backstage/plugin-circleci@0.2.13
    -   @backstage/plugin-explore@0.3.4
    -   @backstage/plugin-graphiql@0.2.10
    -   @backstage/plugin-jenkins@0.4.2
    -   @backstage/plugin-lighthouse@0.2.15
    -   @backstage/plugin-pagerduty@0.3.3
    -   @backstage/plugin-rollbar@0.3.4
    -   @backstage/plugin-sentry@0.3.9
    -   @backstage/core@0.7.7
    -   @backstage/plugin-scaffolder@0.9.2
    -   @backstage/plugin-catalog@0.5.6
    -   @backstage/plugin-search@0.3.5
    -   @backstage/plugin-techdocs@0.9.0

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5447-1bq92ynm1duxxkhb5xfh5e6zpbtmn7ak.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608a76f38e7af62972cbcf62

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5447-1bq92ynm1duxxkhb5xfh5e6zpbtmn7ak.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608a76f38e7af62972cbcf62

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5447-1bq92ynm1duxxkhb5xfh5e6zpbtmn7ak.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608a76f38e7af62972cbcf62

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5447-1bq92ynm1duxxkhb5xfh5e6zpbtmn7ak.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608a76f38e7af62972cbcf62

**Review by freben — APPROVED** [review]

**Review by realandersn — APPROVED** [review]

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5447-1bq92ynm1duxxkhb5xfh5e6zpbtmn7ak.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608a76f38e7af62972cbcf62

**Pull request merged**
