### PR TITLE
Fix techinsights docs: replaced DefaultTechInsightsBuilder with buildTechInsightsContext

### PR DESCRIPTION
**Pull request by goenning**
## Hey, I just made a Pull Request!

Just changing README docs for tech-insights as the documented func does not exist.

@Xantier this one might be for you to review?

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Xantier — APPROVED** [review]
This seems to fit the bill. Thanks for updating those!

**Comment by Xantier** [comment]
Do we want to bump versions with these changes to get the new docs up to npmjs as well?

**Comment by goenning** [comment]
Will do that now, I see no harm in bumping it.

**Comment by goenning** [comment]
while using the jsonfc module also noticed that `factRefs` was renamed to `factIds`, so I updated that as well on this PR.

**Comment by Xantier** [comment]
@goenning Let's add changesets for these with these PRs. Since a lot of the implementations depend on these docs before tech insights moves further, it's probably good to keep npmjs.com up to date with these.

**Comment by goenning** [comment]
added patch changeset

**Review by Xantier — APPROVED** [review]
LGTM

**Review by Rugvip — APPROVED** [review]
Thank you @goenning 👍  and @Xantier!

Let's :shipit:

**Pull request merged**
