### PR TITLE
chore: run tests on macosx

### PR DESCRIPTION
**Pull request by benjdlambert**
Does this work without 💳

### CODE REVIEW

**Comment by benjdlambert** [comment]
Let's not merge this as this changes the name of the actions which will probably need the required branches updating.

**Comment by freben** [comment]
gonna be interesting to see how the timings differ

**Comment by benjdlambert** [comment]
@freben the linux stuff is heavily cached at least. so might be a bit for the first few runs :joy:

**Comment by freben** [comment]
so no docker on macos ... pity

**Pull request closed without merging**
