### PR TITLE
feat: add partner

### PR DESCRIPTION
**Pull request by mario-mui**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
It's not evident how this relates to Backstage on the current landing page imo. Do you have a page to link to that talks more about how Backstage is part of your solution?

**Comment by mario-mui** [comment]
> It's not evident how this relates to Backstage on the current landing page imo. Do you have a page to link to that talks more about how Backstage is part of your solution?

@Rugvip Had update the link, showing more about how Backstage is part of our solution

**Comment by mario-mui** [comment]
ping

**Comment by mario-mui** [comment]
@Rugvip @freben PTAL

**Review by Rugvip — APPROVED** [review]
yep looks good, thanks! :+1:

**Pull request merged**
