### PR TITLE
Update configuring-ci-cd.md

### PR DESCRIPTION
**Pull request by jaroslawgajewski**
## Hey, I just made a Pull Request!

Seems there is still reference to v2 checkout in documentation. Example is fine

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jaroslawgajewski** [comment]
@techdocs-maintainers 
If you think that change is not needed just close it

**Review by awanlin — APPROVED** [review]
Thanks for the contribution @jaroslawgajewski, I think the TechDocs Maintainers are just really busy as of late. This looks good to me though! 🚀

**Comment by awanlin** [comment]
@agentbellnorm or @emmaindal, any chance you can give this a quick look, it's just a small docs change. Thanks in advance!

**Review by freben — APPROVED** [review]
I can do this one!

**Pull request merged**
