### PR TITLE
fix(docs): fixing/simplifying new backend system search imports

### PR DESCRIPTION
**Pull request by jrkt**
## Hey, I just made a Pull Request!

This just simply fixes and simplifies the imports within the how-to guide for migrating search to the new backend installation.

#### :heavy_check_mark: Checklist

- [x] Added or updated documentation
- [x] All your commits have a `Signed-off-by` line in the message

### CODE REVIEW

**Comment by jrkt** [comment]
Not sure why it's saying I didn't add the "Signed-off-by" line to my commit. It's clearly there.

**Review by awanlin — APPROVED** [review]
Thanks for this @jrkt 🚀

**Comment by jrkt** [comment]
Could I get a review on this?

**Review by freben — APPROVED** [review]
Yeah that build step seems to just be confused.

**Pull request merged**
