### PR TITLE
feat(techdocs-cli): check Docker status before running mkdocs server

### LINKED ISSUE #20886: 🐛 Bug Report: docker/mkdocs failed to start, but techdocs-cli keeps waiting
### 📜 Description

While trying to test my docs, I found `techdocs-cli` and I'm looking forward to it. Unfortunately, I haven't gotten it to work yet. 

I kept getting `info: Waiting for mkdocs server to start...` and sometimes it waits forever, sometimes not.

### 👍 Expected behavior

I enabled the verbose mode and discovered the error, but I'm wondering if it's possible to do better. In the logs, you can see `verbose: [docker/mkdocs] Aborted with 1 Configuration Errors!`. That means, the mkdocs will never start, no need to keep waiting.

### 👎 Actual Behavior with Screenshots

```
❯ npx @techdocs/cli serve -v
(node:1926) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Starting mkdocs server.
verbose: [docker/mkdocs] ERROR    -  Config value 'docs_dir': The path 'docs' isn't an existing directory.
verbose: [docker/mkdocs] Aborted with 1 Configuration Errors!
info: Waiting for mkdocs server to start...
info: Waiting for mkdocs server to start...
info: Waiting for mkdocs server to start...
info: Waiting for mkdocs server to start...
```

### 👟 Reproduction steps

Based on the verbose log output, I think it's clear to see and reproduce. Apologies if that is not the case.

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by hainenber**
## Hey, I just made a Pull Request!

Fixes #20886

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by squid-ney** [comment]
This looks great! 
I tried this change out locally. Below our screenshots of starting up the cli. What do you think about having the same behavior for `techdocs-cli serve:mkdocs`?
Screenshot 2023-11-08 at 1 32 40 PM

**Comment by hainenber** [comment]
Hi there, thanks for the review!

I've refactored the snippet to check Docker's operational status into an utility function and made its way for the `serve:mkdocs` commad as well :D

Let me know if this is sufficient to you too :D

**Review by squid-ney — APPROVED** [review]
Nice! Love that the check is reusable. Thank you for your contribution!

**Review by Rugvip — APPROVED** [review]
Thank you! 👍 

I'm assuming that this is good to go from the TechDocs side so gonna :shipit: for today's release

**Pull request merged**
