### PR TITLE
Addressing Security Concerns Raised by OpenSSF Scorecard

### PR DESCRIPTION
**Pull request by NishkarshRaj**
## Hey, I just made a Pull Request!

Added:

- Pinned Dependency to SHA level
- Permissions defined for GitHub Actions following PoLP

Note: This PR is modified version of #19249 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by NishkarshRaj** [comment]
cc/ @adamdmharvey @Rugvip

**Comment by adamdmharvey** [comment]
Nice one!

As you can probably see, numerous E2E failures for the pipeline.  I'm not familiar with the exact steps that the harden runner performs, but perhaps it's removing something the tests depend on?  I wonder if you want to try maybe removing the harden step (like commenting it out) for the E2E action maybe causes it to run clean? if so then you can at least identify the root cause of the failure to focus more on what it does. (and then potentially split the PR into one that just does the version pin/permissions and another for harden?  not sure!)

**Comment by NishkarshRaj** [comment]
Cheers for the inputs @adamdmharvey - was stuck in travelling hell past few days!

I'll rebase with master and let's see how it looks.

Post that will comment out harden runners changes.

**Comment by NishkarshRaj** [comment]
Wow! @adamdmharvey As soon as I tried commenting out the Harden runners, the docker registries are seemingly facing downtime!? 😭 

Logs: 

- https://github.com/backstage/backstage/actions/runs/6344165810/job/17233682142?pr=20090
- https://github.com/backstage/backstage/actions/runs/6344165814/job/17233682786?pr=20090

I'll recheck in a while!

**Comment by adamdmharvey** [comment]
Triggered a re-run of the failed actions; definitely passed the Docker step...

**Comment by NishkarshRaj** [comment]
> Triggered a re-run of the failed actions; definitely passed the Docker step...

Cheers, 5xx must have been resolved - I'll re-trigger all pipelines and take it from there.

**Comment by NishkarshRaj** [comment]
@adamdmharvey Both E2E Testing failing due to this [application level issue](https://github.com/backstage/backstage/actions/runs/6357194647/job/17267997716?pr=20090#step:9:215). This is outside scope of this PR as I've only updated the workflow files.

Any nudges on how to proceed?

**Comment by freben** [comment]
took the liberty of rebasing to see if builds are happier

**Comment by NishkarshRaj** [comment]
> took the liberty of rebasing to see if builds are happier

Thanks @freben  - only 2 failures remain but I can't make sense of these logs. Can you nudge what shall I change to proceed?

**Comment by freben** [comment]
We still have some remaining windows build issues, don't worry about those.

Why is the harden runner commented out everywhere?

**Comment by NishkarshRaj** [comment]
> We still have some remaining windows build issues, don't worry about those.
> 
> Why is the harden runner commented out everywhere?

Was just checking if the failed pipelines are caused by Harden Runner - not really so I will be uncommenting them now.

Will commit and leave it to you guys for best next steps :)

**Comment by benjdlambert** [comment]
Looks like something has gone awry here with the rebase, could you rebase again to just have your commits in here @NishkarshRaj? :pray:

**Comment by NishkarshRaj** [comment]
> Looks like something has gone awry here with the rebase, could you rebase again to just have your commits in here @NishkarshRaj? 🙏

Oh snap! I am on it :)

**Comment by NishkarshRaj** [comment]
@freben @benjdlambert : Fixed the stupid rebase mistake, hope this works now.

**Comment by freben** [comment]
we've put a "merge after release" label on this so we can revisit merging it after the mainline release out of an abundance of caution against getting into release problems.

**Pull request merged**
