### PR TITLE
Added sorted prop to EntityTypePicker

### PR DESCRIPTION
**Pull request by matdtr**
## Hey, I just made a Pull Request!
This is my first PR hope that i did all good. 
This add the possibility to sort the values inside `EntityTypePicker`. 

Default behaviour:

Screenshot 2024-11-17 alle 16 58 41

With   `<EntityTypePicker sorted />`  (the value `all` is always first):

Screenshot 2024-11-17 alle 17 15 14

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by matdtr** [comment]
not stale

**Comment by matdtr** [comment]
@Rugvip @vinzscam for visibility

**Review by awanlin — CHANGES_REQUESTED** [review]
Thanks for this @matdtr, I'd like to get feedback from the Catalog Maintainers but my thinking is to avoid the prop entirely and this should be the default. As someone who is generally pro "opt-in" I think in this case it's not the right direction and having them sorted by default will be a better experience for everyone.

**Comment by freben** [comment]
Oh sorry I hadn't seen this. Indeed - `all` at the top followed by sorted server side entries would be great as the default without a prop. Thanks! We can treat it as a bug that it wasn't sorted in the first place.

**Comment by matdtr** [comment]
Hi @freben @awanlin removed the prop and sorted by default. Let me know if needed something else

**Review by freben — APPROVED** [review]
Thanks! Gonna force this one through so it gets in today's release, hope that's ok @ahhhndre

**Comment by awanlin** [comment]
Fine with me, thanks for merging @freben and for the contribution to fix this @matdtr 🚀

**Pull request merged**
