### PR TITLE
Added helm chart

### PR DESCRIPTION
**Pull request by toonsevrin**
I've added templates for Kubernetes helm. 

This will become a lot more useful once backend support is released but why not have it now :)

### CODE REVIEW

**Comment by toonsevrin** [comment]
/hold
Please do not merge this just yet until a proper plugin workflow is added :+1:

**Comment by Rugvip** [comment]
Thanks for the PR!

Sorry for the delay in the response, busy times :grin:

Wondering what the benefit of adding the chart to this repo is, given that the only container built here is just an example and not really useful outside the project.

As you mention we're in the works of adding backends as well, and that might make it more clear, but should we hold off on this for now to avoid noise?

Perhaps it makes sense to do something similar to the heroku deployment instructions in [DEPLOYMENT.md](https://github.com/spotify/backstage/blob/master/DEPLOYMENT.md)?

**Comment by toonsevrin** [comment]
@rugvip, hmm, I think nowadays managing the helm templates (or k8s templates) within the repository itself is not that bad of an idea. But yeah, right now this is really not that spectacular :)

Just to be certain: Will plugins be backed into the Docker image or will you add them as volumes?

In the case that plugins are baked in, with this pr, I'm able to deploy my Backstage frontend, including all plugins, onto k8s with just one command (assuming the baked image is in my registry): 

```bash
helm install backstage backstage --set frontend.image.repository=$REPO
```
In case plugins should be mounted as volumes, this approach does not yet work.

Anyways, to answer your question, I believe simply dumping this into the repository doesn't hurt. Even if it just provides as an inspiration for how to write your k8s manifests. I'm sure you guys at spotify are transitioning to k8s as well ;)

**Comment by stefanalund** [comment]
Closing this for now. Let’s reopen if we see a need for this down the line. 

Thanks for the time you put into it.

**Pull request closed without merging**
