### PR TITLE
feat(catalog): introduce a new config for processing interval multiplier

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

this allows changing the default processing interval multiplier with the new backend system as there is no access to CatalogBuilder anymore.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
What makes you want to change this one?

**Comment by drodil** [comment]
@freben we have some processors that take some time to finish and with 15k+ entities we would like to spread the workload a bit more. With `processingInterval` of 1 hour it means all entities will have the `next_update_at` between `now() + 60mins` and `now() + 90mins`. Having all those entities in a 30-minute time range is a bit much so having the possibility to change the multiplier for example to 2, makes it much more bearable without the need to set the minimum to more than 1 hour. Does it make sense? 😆

**Comment by drodil** [comment]
@freben, could you elaborate a bit on what you mean by `data changes gradually`? When a provider creates an entity with `full` mutation, does it mean it is a bulk change? Or does the catalog core detect somehow which entities have changed since last time and only pass those to the processors? The functionality is very hard to understand and the docs don't really cover this deep enough.

**Comment by freben** [comment]
It [computes a delta](https://github.com/backstage/backstage/blob/a5b13601332b20e99ef1b8e7c4446c8baff5ee16/plugins/catalog-backend/src/database/DefaultProviderDatabase.ts#L205) based on previous and new hashes of the contents. Only actually changed entities _should_ be sent for processing. It should be safe to `full` mutate the exact same set of entities over and over again while leading to zero reprocessing (except for those that naturally are due for regular processing of course).

Maybe your processing loop is just overburdened? As in, it can't keep up with the number of entities in there so it's constantly behind because processing them all takes longer than the processing interval?

**Comment by drodil** [comment]
Ok, so basically if the `provider` changes some information in the entity, it will go through the processing again. That makes sense. Have to check that there are no such fields that change constantly for some reason like timestamps or something else. Right?

Also, the overburden might also be an issue. Maybe have to try with a longer interval too to see if it has any effect.

**Comment by freben** [comment]
exactly, timestamps and versions are typical culprits

**Comment by drodil** [comment]
@freben sure, though no idea where this magic number came from here and why it shouldn't be configurable 😄 Got our instance working with _quite big_ refactoring of processors and providers, but I think this is something that should be documented somewhere so that people implementing catalog extensions would be aware and not shoot themselves in the foot like we did.

**Comment by freben** [comment]
Yeah the thing is, it's just some fudge factor to ensure that load doesn't get too "spiky" (everything in the universe due for re-processing at the exact same instant)

**Pull request closed without merging**
