### PR TITLE
Update Integration Gitlab OrgData

### PR DESCRIPTION
**Pull request by rolandsgs**
## Hey, I just made a Pull Request!

Just an update to Documentation in the section Integrations Gitlab OrgData, once it's not defined the necessary addition to `packages/backend/src/plugins/catalog.ts` as in all others

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Think you'll need to run prettier on the changed files 👍  You can go into the `microsite` directory and run `yarn prettier --write` and commit the changes :)

**Comment by benjdlambert** [comment]
Looks like the DCO check is failing for this PR, you might want to follow the instructions in the comment and the status check to fix up this PR 👍

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Hey @rolandsgs, it looks like [e914ac](https://github.com/backstage/backstage/pull/17685/commits/1e914ac9a6b4b35d416ca787f9986634d16d885f) is the commit that needs signing. You can use the instructions under this message https://github.com/backstage/backstage/pull/17685/checks?check_run_id=13657007683 which should help you get this fixed :)

**Comment by rolandsgs** [comment]
Thank you [benjdlambert](https://github.com/benjdlambert) for guiding me and sorry for delayed response.

**Pull request merged**
