### PR TITLE
feat(scaffolder-backend): allow to create Gerrit project using default owner

### PR DESCRIPTION
**Pull request by tcardonne**
## Hey, I just made a Pull Request!

The `gerrit:publish` actions throws an `InputError` if the repoUrl doesn't have the owner param.
However this field is optional in the Gerrit REST API ([documentation reference here](https://gerrit-review.googlesource.com/Documentation/rest-api-projects.html#project-input)).

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] ~Added or updated documentation~
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] ~Screenshots attached (for UI changes)~
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Will there need to be a similar change to the `RepoUrlPicker` to support missing owner?

**Comment by benjdlambert** [comment]
I think we will need to update this validator here: https://github.com/backstage/backstage/blob/2c1a2eeccee1b9c8ae6159c961b44fbf83d71ac7/plugins/scaffolder/src/components/fields/RepoUrlPicker/validation.ts#L58-L64 to add another case that if it's gerrit.

**Comment by benjdlambert** [comment]
And of course you could update the `GerritRepoPicker` to maybe have a better description that if you leave it blank it will default to the default owner? :)

**Comment by tcardonne** [comment]
Done :+1: WDYT?

**Review by benjdlambert — APPROVED** [review]
Nice work! Thanks! 👍

**Pull request merged**
