### PR TITLE
Docs: Update references to "service catalog"

### PR DESCRIPTION
**Pull request by joeporpeglia**
Signed-off-by: Joe Porpeglia <josephp@spotify.com>

Closes https://github.com/backstage/backstage/issues/3065 and relates to https://github.com/backstage/backstage/issues/2148.

## Hey, I just made a Pull Request!

Addresses the inconsistencies in how we refer to the Software Catalog (previously named Service Catalog). I updated the readme, docs, microsite copy, code comments, and image names. There are some references to Service Catalog embedded in images, but I can't change those without the original assets. 

References I **did not change** to preserve historical info and links:
- blog post titles/urls/content
- changelog
- adopters descriptions

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by OrkoHunter — COMMENTED** [review]
Thanks for doing this! 💯 

Let's add a changeset for all the packages and plugins we have updated (except for example-app and example-backend i.e. packages/app and packages/backend).

> There are some references to Service Catalog embedded in images, but I can't change those without the original assets.

Just giving a public shoutout to using more images which can be updated easily, like [these `.draw.io.svg` diagrams](https://github.com/backstage/backstage/tree/master/docs/assets/techdocs) :)

**Review by benjdlambert — APPROVED** [review]

**Comment by adamdmharvey** [comment]
This MIGHT close my old reported issue here? :) https://github.com/backstage/backstage/issues/3065 I know at the time the former product owner wasn't so sure we should do it, but happy it'll get some visibility/alignment!! 🎉

**Review by freben — APPROVED** [review]

**Review by camilaibs — APPROVED** [review]

**Comment by benjdlambert** [comment]
🚢

**Comment by joeporpeglia** [comment]
Looks like the search index needs to be updated as a result of this change (search for "service catalog" and some results 404). Is that a manual process or should that happen automatically?

**Comment by OrkoHunter** [comment]
Oh weird. I'd imagine docusaurus would create the search index upon generation of the site. Are the indexes broken when you run the microsite locally as well?

**Comment by joeporpeglia** [comment]
Yeah the index wasn't updated while running locally, but I figured that was normal because it was fetching results from algolia.net instead of some local endpoint

**Comment by freben** [comment]
Oh. Hm i do not know of how that works, we haven't worried about any search indices in previous pull requests here afaik.

**Comment by OrkoHunter** [comment]
Looking at https://docsearch.algolia.com, it says "we'll scrape your website every 24 hours and build indexes".

I didn't know about the algolia setup before either, I thought the indexes were taken care of "locally".

**Pull request merged**
