### PR TITLE
[Tech radar] Allow to set additional links to the entry description

### PR DESCRIPTION
**Pull request by legendik**
Signed-off-by: Marek Šneberger <marek@sneberger.cz>

## Hey, I just made a Pull Request! 👋

It allows to set additional links for the radar entry, not only "LEARN MORE" link - for example some external documentation etc. See the screenshot.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
Screenshot 2023-01-17 at 16 07 41

### CODE REVIEW

**Comment by legendik** [comment]
Rebased to master.

**Comment by efenner-cambia** [comment]
Is there a doc change in this PR to indicate how one should add these additional links? Looking forward to this functionality!

**Comment by legendik** [comment]
@efenner-cambia You can take a look into `sample.ts`, there is an example how to add additional links.

https://github.com/backstage/backstage/blob/a86d0d24e1b708e28039030c5359f5aadb89fe77/plugins/tech-radar/src/sample.ts#L48-L61

**Review by Rugvip — APPROVED** [review]
Nice idea, makes sense, thank you! 👍 :shipit:

**Pull request merged**
