### PR TITLE
chore: add new Coder plugins to microsite

### PR DESCRIPTION
**Pull request by Parkreiner**
## Hey, I just made a Pull Request!

This PR updates the Plugin microsite to list the new Backstage plugins that Coder just published.
[You can find the main repo for all our plugins here](https://github.com/coder/backstage-plugins).

#### Itemized list of changes
- Added `coder.yaml` to `/microsite/data/plugins/` and added corresponding icon to `/microsite/static/img`
- Added `devcontainers.yaml` to `/microsite/data/plugins/` and added corresponding icon to `/microsite/static/img`

#### Screenshots
Both screenshots were taken by building and running the microsite locally.

Screenshot 2024-03-15 at 4 00 13 PM
Screenshot 2024-03-15 at 4 00 22 PM

#### :heavy_check_mark: Checklist
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message.

None of the other items were applicable, and were removed from this section.

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Great additions @Parkreiner 🚀

**Comment by awanlin** [comment]
Honestly, I don't get too caught up on this but I also haven't built a `x-react` package myself.

Here's my opinion and understanding: the `x-react` package should just have react components and/or hooks and nothing else. So based on that I would not expect to see a `plugin.ts` or `routes.ts` files in these packages. Those to me are items you would find in a `x` package.

@freben or @vinzscam , what are your thoughts on this?

**Comment by freben** [comment]
I'd broaden it to "anything that other plugins are interested in importing". So routes and shared components and types etc could fit the bill.  A plugin declaration, no.

**Comment by vinzscam** [comment]
>  I'm wondering if we should actually update backstage-plugin-coder to have it, too

no, `backstage-plugin-coder` looks good!

**Comment by Parkreiner** [comment]
That makes sense. Is there anything else I need to do to get this approved by a code owner?

**Comment by awanlin** [comment]
> That makes sense. Is there anything else I need to do to get this approved by a code owner?

No, we are just a bit busy, the most recent release has some items we need to handle and we are also all slowly getting back home from BackstageCon/KubeCon EU.

@freben when you have time can you give this a look? Everything looks good to me!

**Review by freben — APPROVED** [review]
Alright!

**Pull request merged**
