### PR TITLE
Improve MS Graph Performance

### PR DESCRIPTION
**Pull request by afscrome**
Extracted from #15648, and builds upon #15883

## Hey, I just made a Pull Request!

This PR improves the performance of the Microsoft Graph Plugin
1. Increases the page size in general used by MS Graph, up to the maximum of 999 records per page, rather than the default 100.
2. Improves the performance when loading users by batch loading the user objects, rather than making a call to list all group members, then loading each user one by one.
   - This also fixes a bug that could cause a user to temporarily disappear from the catalogue if there was a transient failure loading that one user.  (The user would be missing fromt he entity provider's full data, so would be removed, then the next run successfully restores the user)
     https://github.com/backstage/backstage/blob/9c37b7c000c8a029b072640d921ca904af20877a/plugins/catalog-backend-module-msgraph/src/microsoftGraph/read.ts#L204-L210

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
Nice!

**Comment by freben** [comment]
Oh. I see there's a conflict with a file now.

**Comment by benjdlambert** [comment]
Does the merging of this final PR close #15648?

**Review by freben — APPROVED** [review]
thanks!

**Pull request merged**
