### PR TITLE
fix: export currencies from useConfig hook

### PR DESCRIPTION
**Pull request by abhishekjakhar**
## Hey, I just made a Pull Request!

**Fixes:** https://github.com/spotify/backstage/issues/3134

The cost insights page is not loading because we are getting currencies as undefined and we are trying to loop over the undefined using map method in CurrencySelect component, now we will only show CurrencySelect component if currencies area available from config.

#### Before

cost-insights-page-bug

#### After

cost-insights-page-fix

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/spotify/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by ryanvazquez** [comment]
Oof. Nice catch @abhishekjakhar. Currencies should never be undefined as we ship a set of currencies "pre-configured" (loaded in state but not actually derived from the config itself). These are initialized in the default state of the `useConfig` hook.

Seems like there is a bug related to the import resolution of `defaultCurrencies` from its type file, as well as enums and other non-type definitions writ large, as all of these imports are now returning `undefined`. This can be reproduced for other non-type definition imports in other files.

**Comment by abhishekjakhar** [comment]
> Oof. Nice catch @abhishekjakhar. Currencies should never be undefined as we ship a set of currencies "pre-configured" (loaded in state but not actually derived from the config itself). These are initialized in the default state of the `useConfig` hook.
> 
> Seems like there is a bug related to the import resolution of `defaultCurrencies` from its type file, as well as enums and other non-type definitions writ large, as all of these imports are now returning `undefined`. This can be reproduced for other non-type definition imports in other files.

If set of currencies are always "pre-configured" then I don't think we require this check. I was confused between adding this check or using defaultCurrencies from types as fallback.

**Comment by ryanvazquez** [comment]
The feature should still be behind a feature flag but yes, the nullish checks aren't necessary as config.currencies should always be defined.

**Comment by abhishekjakhar** [comment]
> The feature should still be behind a feature flag but yes, the nullish checks aren't necessary as config.currencies should always be defined.

In the useConfig hook we are exporting products, metrics, engineerCost and icons. But, are not exporting currencies. We have imported currencies from types but I guess we forgot to export them from the hook. I will export the currencies form hook and remove the nullish checks.

**Comment by ryanvazquez** [comment]
@abhishekjakhar The useConfig hook exports the hook, context and type definition. Products, metrics, etc. are properties of the config context. `defaultCurrencies` is defined and exported in `Currency.ts`.

The underlying issue seems to be that the export of `defaultCurrencies` from `Currency.ts` is returning undefined in `useConfig` - in fact, all non-type exports from type definition files are returning undefined - so the config state which is defined outside of the component, is being initialized incorrectly. At runtime when the component mounts, these references resolve but the Provider mounts with an incorrect state. 

It appears this issue affects components who have similar dependencies on these non-type exports. Exports should always resolve, so the remediation for this will likely require migrating these non-types (enums, consts, etc.) to their own files.

**Comment by abhishekjakhar** [comment]
> @abhishekjakhar The useConfig hook exports the hook, context and type definition. Products, metrics, etc. are properties of the config context. `defaultCurrencies` is defined and exported in `Currency.ts`.
> 
> The underlying issue seems to be that the export of `defaultCurrencies` from `Currency.ts` is returning undefined in `useConfig` - in fact, all non-type exports from type definition files are returning undefined - so the config state which is defined outside of the component, is being initialized incorrectly. At runtime when the component mounts, these references resolve but the Provider mounts with an incorrect state.
> 
> It appears this issue affects components who have similar dependencies on these non-type exports. Exports should always resolve, so the remediation for this will likely require migrating these non-types (enums, consts, etc.) to their own files.

Could I take sometime and work on this?

**Comment by abhishekjakhar** [comment]
This issue is being take care of in https://github.com/spotify/backstage/pull/3147 PR

**Comment by abhishekjakhar** [comment]
Closing this PR because this issue is being take care of in #3147 PR

**Pull request closed without merging**
