### PR TITLE
Refactor CopyTextButton to use new navigator clipboard api

### LINKED ISSUE #6566: Refactor CopyTextButton to use Clipboard API
## Feature Suggestion

The `CopyTextButton` in `backstage/core-components` uses the deprecated `document.execCommany('copy');` functionality. The implementation currently requires a workaround creating a non-visible textarea with the visible text, which should be copied:
```jsx
<textarea
  ref={inputRef}
  style={{ position: 'absolute', top: -9999, left: -9999 }}
  defaultValue={text}
/>
``` 
and manually triggering a select on the non-visible textarea:
```ts
inputRef.current.select();
document.execCommand('copy');
``` 
This leads to issues related to a11y & creates an unnecessary overhead (rendering the same text in 2 elements & using refs). Furthermore the new Clipboard API provide more flexibility & will be future proof approach.

## Possible Implementation

In `CopyTextButton.tsx`:

`handleCopyClick` - use the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
): 
```ts
navigator.clipboard.writeText("<empty clipboard>").then(() => {
  /* clipboard successfully set */
}, () => {
  /* clipboard write failed */
});
```

`render`: 
```diff
-<>
-   <textarea
-      ref={inputRef}
-      style={{ position: 'absolute', top: -9999, left: -9999 }}
-      defaultValue={text}
-   />
    <Tooltip ...>
      ....
    </Tooltip>
-</>
```

## Context

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
https://dequeuniversity.com/rules/axe/4.3/label?application=axeAPI
https://backstage.io/storybook/?path=/story/inputs-copytextbutton--default

### PR DESCRIPTION
**Pull request by vcapretz**
Signed-off-by: Vitor Capretz <vcapretz@spotify.com>

## Hey, I just made a Pull Request!

closes #6566 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by mtlewis** [comment]
Looks great, nice improvement! Did you double check that it works correctly in Firefox? It looks like this API is only available inside event handlers in FF - it looks like that restriction won't be an issue here, but seems to me to be worth checking to make sure :).

**Comment by freben** [comment]
I'd like it tested in mobile browsers too!

**Comment by vcapretz** [comment]
will do! I'll let you know how it goes 👍

**Comment by freben** [comment]
Could also use a well tested wrapper too...

https://github.com/streamich/react-use/blob/master/docs/useCopyToClipboard.md

We use this lib a lot already for other purposes. So seems like a low hanging fruit to me

**Comment by Fox32** [comment]
> Could also use a well tested wrapper too...
> 
> https://github.com/streamich/react-use/blob/master/docs/useCopyToClipboard.md
> 
> We use this lib a lot already for other purposes. So seems like a low hanging fruit to me

Just wanted to suggest using that one 😆

**Comment by vinzscam** [comment]
After a quick discussion with @vcapretz we're going to continue this PR here #6869

**Pull request closed without merging**
