### PR TITLE
[TechDocs] Restore 404 behavior

### PR DESCRIPTION
**Pull request by iamEAP**
## Hey, I just made a Pull Request!

The refactoring of the reader page to support Addons introduced some regressions related to 404 states.  ...This ensures 404 behavior today matches 404 behavior prior to Addon support being added (and adds some regression tests to that end).

| Scenario                         | Before | After |
|----------------------------------|--------|-------|
| Entity Not Found                 | bug-404-entity-does-not-exist | fixed-404-entity-does-not-exist |
| Content Not Found                | bug-404-content-not-found | fixed-404-content-not-found |
| Content Not Found (Entity Page)  | bug-404-entity-page-content-not-found | fixed-404-entity-page-content-not-found |

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jeremyguarini** [comment]
What should happen when a component exists but there is no documentation at the location pointed to by backstage.io/techdocs-ref? Or to ask another way, what should happen when using storage bucket for holding compiled docs and there are no docs to retrieve from the bucket? Applying this change I get a partially rendered header with the skeleton bars and the page not found message.
Screen Shot 2022-04-21 at 11 04 00 AM

**Comment by iamEAP** [comment]
Thanks @jeremyguarini!  Was able to reproduce the problem and the solution via your suggested fix!  Updated.

**Review by emmaindal — APPROVED** [review]
Nice!

**Comment by jeremyguarini** [comment]
> Thanks @jeremyguarini! Was able to reproduce the problem and the solution via your suggested fix! Updated.

Glad I could help here.

Thanks for restoring the old 404 behavior.

**Pull request merged**
