### PR TITLE
Fixed : Color of Hyperlinks in dark mode

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

## Hey, I just made a Pull Request!

Fixes Issue #4615 

Screenshot_2021-03-06 Home Services Backstage

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4849-zul1dhgtd1nddfcx8tomr6x8cirnixnf.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60434666f285af7a08a24900

**Comment by benjdlambert** [comment]
Related to https://github.com/backstage/backstage/pull/4747

**Comment by benjdlambert** [comment]
Thanks for this work, but I think it's a duplicate of what we have going on in #4747. I think we should continue the work over there, so will close this PR. Apologies!

**Comment by chinmaym07** [comment]
No problem @benjdlambert sir .. Thanks for the info 👍🏻  😀

**Pull request closed without merging**
