### PR TITLE
document how to override the default port

### PR DESCRIPTION
**Pull request by asoorm**
Port 3000 is a common port in the development environment.

This documents how you can start backstage with a different port to the default.

### CODE REVIEW

**Review by Rugvip — DISMISSED** [review]
👌

**Review by stefanalund — DISMISSED** [review]

**Comment by stefanalund** [comment]
What do you think about moving this to a separate file and instead link from the README? Somewhat concerned of increasing the length.

**Comment by asoorm** [comment]
@stefanalund You mean creating a server page or similar in `/docs/reference` directory?

**Comment by stefanalund** [comment]
Yes, exactly. And linking to it from the README.

**Comment by asoorm** [comment]
@stefanalund @Rugvip PTAL

**Review by stefanalund — APPROVED** [review]
Perfect. Thanks a lot!

**Pull request merged**
