### PR TITLE
chore: update Bitbucket Cloud OpenAPI specification

### PR DESCRIPTION
**Pull request by pjungermann**
There were no changes impacting the codebase.

Signed-off-by: Patrick Jungermann <Patrick.Jungermann@gmail.com>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by agentbellnorm** [comment]
@pjungermann I'm not so familiar with the bitbucket modules, but I have one thought: If we change the api spec, which will result in new generated code, do we not have to bump the version of _some_ module for this new code to reach whoever might be interested in this change?

Seems like there are two users of `@backstage/plugin-bitbucket-cloud-common`, both using `workspace:^`:
* `@backstage/plugin-catalog-backend-module-bitbucket-cloud`
* `@backstage/plugin-catalog-backend-module-bitbucket`

is the idea that that whenever those two are released next time, they will just get this change automatically? 

I'm thinking that it's a bit risky to not mention this change in any changeset.

1. Have I understood correctly? 😛
2. What's your take?

**Comment by akundrock** [comment]
I was wondering how this might work with building out a scaffolder plugin for Bitbucket cloud. The OpenAPI spec would need to have a few items added (which appear to be here) such as the repository workspace, and a few others. Related RFC can be found here:
https://github.com/backstage/backstage/issues/14501

I think in this case a changeset might be needed to make sure those objects or changes are picked up by dependent modules.

Also how might this work with an external plugin/module? The OpenAPI spec would need to be updated but I'm not sure how the 'reduce' stage would work if the common module doesn't know what pieces to keep from external plugins with dependencies.

**Comment by pjungermann** [comment]
@agentbellnorm sorry, I think I should have provided more context.

The OpenAPI spec file is basically just a copy of the online version available and represents the version we used to generate the code.

In order to reduce the API surface to the minimum the decision was made to remove everything unnecessary. This is maintained via scripts/yarn tasks inside of the module.

Actually, I wanted to upgrade the generator to the latest version. However, I thought it might be cleaner to have this change as no-op change first. As there is no code change, no change to the API surface of the module, I believe there is no version bump necessary.

I have another change ready to upgrade generator-cli of @openapitools/openapi-generator-cli from 6.0.0-beta to the latest 6.2.1.
I could combine both in one PR though if you think this makes more sense.

That change will not change the API surface, too. Only bumps the generator incl. some required adjustments at the scripts.

If preferred, I can still add a changeset even if there is no effective change.

Let me know what you think about it.

**Comment by pjungermann** [comment]
@akundrock the "reduce" stage (`scripts/reduce-models.js`) uses AST transformations (abstract syntax tree) by using `ts-morph` and uses the non-generated class `BitbucketCloudClient` as starting point to find what is actually used (incl. all of their (transitive) dependencies).

If you want to add something new, you can omit that "reduce" step, extend the client class and then run it again without omitting it.

Feel free to reach out if you need any help.

**Review by Rugvip — APPROVED** [review]
Alright, thanks! 👍 

And yep, no changeset needed if the generated code didn't change

**Pull request merged**
