### PR TITLE
Add Mia Platfom plugin to directory

### PR DESCRIPTION
**Pull request by epessina**
## Hey, I just made a Pull Request!

Added files needed to list [Mia Platform plugin](https://github.com/mia-platform/backstage-plugin) to Backstage plugin directory.

Following [these instructions](https://backstage.io/docs/plugins/add-to-directory/) we added a yaml manifest and an icon to the appropriate directories.

### CODE REVIEW

**Review by awanlin — CHANGES_REQUESTED** [review]
Thanks for submitting your plugin @epessina 

This PR itself is good but looking over the plugin itself the backend doesn't look to support the new backend system yet and this will be a blocker for many adopters. It currently the default when creating a new Backstage instance.

**Comment by epessina** [comment]
> Thanks for submitting your plugin @epessina
> 
> This PR itself is good but looking over the plugin itself the backend doesn't look to support the new backend system yet and this will be a blocker for many adopters. It currently the default when creating a new Backstage instance.
> 
> Docs that will help: https://backstage.io/docs/backend-system/building-plugins-and-modules/index Example module: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/module/githubCatalogModule.ts

Hi @awanlin , we are working on adapting the plugin to the new Backend system. Is it something blocking for this PR or could it be merged while we close things on our side?

Thank you very much!

**Comment by awanlin** [comment]
Hi @epessina, I would say yes, the new backend system has been the default for nearly a month now, many Adopters have already migrated to it as it has been our recommendation to do so since about November of 2023. But I'm not the final say, I just wanted to give it an early look as it was mentioned on Discord and I know the Maintainers can be pretty busy.

**Comment by epessina** [comment]
Hi @awanlin , we have updated the plugin to support both the new and the legacy backend systems. Do you reckon we can move on with the PR?

**Review by awanlin — APPROVED** [review]
Thanks for adding your plugin to the directory @epessina 🚀

**Review by benjdlambert — APPROVED** [review]
Nice! Thanks for this and thanks @awanlin :pray:

**Pull request merged**
