### PR TITLE
Adaptors/trendyol

### PR DESCRIPTION
**Pull request by erdoganoksuz**
## Hey, I just made a Pull Request!
Adding Trendyol to adopters

Here an overview

Screen Shot 2021-03-05 at 12 13 18

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4832-rem22yznodhuidt04wtdqnvbzgop2vz3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6041f6adfcb22ddf8f693dfa

**Comment by benjdlambert** [comment]
Vale apparently doesn't like names! Think you need your surname too, sorry! 🙏

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4832-rem22yznodhuidt04wtdqnvbzgop2vz3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6041f6adfcb22ddf8f693dfa

**Comment by erdoganoksuz** [comment]
> Vale apparently doesn't like names! Think you need your surname too, sorry! 🙏

I add 😄

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
Welcome!

**Pull request merged**
