### PR TITLE
fix: export createGithubProvider

### PR DESCRIPTION
**Pull request by estahn**
## Hey, I just made a Pull Request!

I am trying to use [auth/identity-resolver](https://backstage.io/docs/auth/identity-resolver) with GitHub. Unfortunately `createGithubProvider` is currently not available.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
Thanks for fixing this 👍

**Comment by jhaals** [comment]
Please run run `yarn build:api-reports` and commit the api report :)

**Review by freben — APPROVED** [review]
I added the report file :) Let's see if it builds, then 🚢

**Comment by estahn** [comment]
@jhaals @freben Thanks for the quick turnaround 👍🏼

**Pull request merged**
