### PR TITLE
integration: Fix commit and branch API urls for hosted bitbucket server

### PR DESCRIPTION
**Pull request by OrkoHunter**
Noted in https://github.com/backstage/backstage/issues/4121#issuecomment-764735647

Docs https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp184

I think there are more problems that exist with hosted bitbucket server and URL Reader. Thinking about deploying a trial version soon to test it all out. _sigh_

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by jhaals — APPROVED** [review]
Thanks for sorting this out @OrkoHunter! I agree that it would be nice with an installation to properly test our integrations

**Comment by benjdlambert** [comment]
@regicsolutions if it's possible, I know you're on Bitbucket Server too, could you test this PR?

Can you add files that are in bitbucket server into the `catalog-import` plugin?

**Comment by OrkoHunter** [comment]
@benjdlambert What should we do about this?

I am running a Bitbucket server using their [docker image](https://hub.docker.com/r/atlassian/bitbucket-server/). And have spotted more errors. e.g. The commits URL
https://github.com/backstage/backstage/blob/664dd08c95801870a9434ec8d4b76b979a3bd4e0/packages/backend-common/src/reading/BitbucketUrlReader.ts#L148

is wrong for Bitbucket server and will only work for `bitbucket.org`.

It should be this (docs: https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp222)
```
http://custombitbucket.com/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/commits 
```
for Bitbucket server.

I think I can continue to push the changes to this branch.

**Comment by regicsolutions** [comment]
Is the latest nightly build a good version to test?> @regicsolutions if it's possible, I know you're on Bitbucket Server too, could you test this PR?
> 
> 
> 
> Can you add files that are in bitbucket server into the `catalog-import` plugin?

**Comment by OrkoHunter** [comment]
> Is the latest nightly build a good version to test?

@regicsolutions Since the PR hasn't been merged, it is not available in any nightly release. So, please test on this branch `orkohunter/default-branch-bitbucket-server` in this repository. :)

**Comment by benjdlambert** [comment]
> @benjdlambert What should we do about this?
> 
> I am running a Bitbucket server using their [docker image](https://hub.docker.com/r/atlassian/bitbucket-server/). And have spotted more errors. e.g. The commits URL
> https://github.com/backstage/backstage/blob/664dd08c95801870a9434ec8d4b76b979a3bd4e0/packages/backend-common/src/reading/BitbucketUrlReader.ts#L148
> 
> is wrong for Bitbucket server and will only work for `bitbucket.org`.
> 
> It should be this (docs: https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp222)
> 
> ```
> http://custombitbucket.com/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/commits 
> ```
> 
> for Bitbucket server.
> 
> I think I can continue to push the changes to this branch.

I guess we need to check what the hostname is and do different things depending on if it's bitbucket.org or on prem bitbucket. We do something similar in the publisher to create repo's but it's nasty.

**Comment by OrkoHunter** [comment]
> I guess we need to check what the hostname is and do different things depending on if it's bitbucket.org or on prem bitbucket. We do something similar in the publisher to create repo's but it's nasty.

@benjdlambert Indeed. That is how it's being done here as well. `host === bitbucket.org`.

**Comment by OrkoHunter** [comment]
@backstage/maintainers A gentle reminder that we should have this before tomorrow's release. 🙏

**Comment by benjdlambert** [comment]
@regicsolutions can you confirm that this works for you?

**Comment by regicsolutions** [comment]
> @regicsolutions can you confirm that this works for you?

Just tested this, I imported the springboot template, created a component and get this when i try to view docs: 

`Error: No preparer registered for type: "bitbucket" at Preparers.get (webpack-internal:///../techdocs-common/src/stages/prepare/preparers.ts:68:13) at new DocsBuilder (webpack-internal:///../../plugins/techdocs-backend/src/DocsBuilder/builder.ts:70:31) at eval (webpack-internal:///../../plugins/techdocs-backend/src/service/router.ts:139:27) at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by OrkoHunter** [comment]
> > @regicsolutions can you confirm that this works for you?
> 
> Just tested this, I imported the springboot template, created a component and get this when i try to view docs:
> 
> `Error: No preparer registered for type: "bitbucket" at Preparers.get (webpack-internal:///../techdocs-common/src/stages/prepare/preparers.ts:68:13) at new DocsBuilder (webpack-internal:///../../plugins/techdocs-backend/src/DocsBuilder/builder.ts:70:31) at eval (webpack-internal:///../../plugins/techdocs-backend/src/service/router.ts:139:27) at processTicksAndRejections (internal/process/task_queues.js:97:5)`

Hey @regicsolutions ! Can you add files that are in bitbucket server into the `catalog-import` plugin? Or register an existing component using a URL that is from bitbucket server (on the Catalog Create New Component page)?

The TechDocs error is expected. What is the `backstage.io/techdocs-ref` value in the Entity's metadata annotation? TechDocs does not support bitbucket directly if the URL looks like `bitbucket:...`. You can see [here](https://github.com/backstage/backstage/blob/e0d495dc5209c338cba15d3847ba737f103417b0/packages/techdocs-common/src/stages/prepare/types.ts#L33-L39). Instead try using the URL Reader in TechDocs to support Bitbucket. https://backstage.io/docs/features/techdocs/how-to-guides#how-to-use-url-reader-in-techdocs-prepare-step. But I am afraid, for TechDocs, there is another PR https://github.com/backstage/backstage/pull/4231 which you will need to be merged into this branch for URL Reader to work with bitbucket server. Hence, please don't worry about TechDocs when testing this branch here.

**Comment by OrkoHunter** [comment]
For what it's worth, I have tested it by running Bitbucket server using their [docker image](https://hub.docker.com/r/atlassian/bitbucket-server/) and executing `readTree` when the backend starts.

```ts
    const bitbucketServer = await reader.readTree(
      'http://localhost:7990/projects/PROJ/repos/techdocs-test/browse',
    );
    console.log(bitbucketServer.etag);
    console.log(await bitbucketServer.files());
```

in `packages/backend/src/plugins/techdocs.ts` backend file where an instantiated `reader` is passed from `createPlugin`.

And I have added documentation reference for the API endpoint changes - which are really just two

1. Default branch URL.
2. Commits URL was non-existent for bitbucket server.

**Review by benjdlambert — APPROVED** [review]

**Comment by regicsolutions** [comment]
> For what it's worth, I have tested it by running Bitbucket server using their [docker image](https://hub.docker.com/r/atlassian/bitbucket-server/) and executing `readTree` when the backend starts.
> 
> ```ts
>     const bitbucketServer = await reader.readTree(
>       'http://localhost:7990/projects/PROJ/repos/techdocs-test/browse',
>     );
>     console.log(bitbucketServer.etag);
>     console.log(await bitbucketServer.files());
> ```
> 
> in `packages/backend/src/plugins/techdocs.ts` backend file where an instantiated `reader` is passed from `createPlugin`.
> 
> And I have added documentation reference for the API endpoint changes - which are really just two
> 
> 1. Default branch URL.
> 2. Commits URL was non-existent for bitbucket server.

@OrkoHunter  i just re-tested, The **catalog-info.yaml** file in my template is using `url:{{cookiecutter.storePath}}` when i try creating a component with that template the output in the repo becomes this 

_(my project ID in this example is PID and repo name is BACKSTAGE)_

```
  annotations:
    backstage.io/techdocs-ref: url:https://mybitbuckerserver.com/PID/BACKSTAGE
```

Which is not correct as i get a 404 when i try reaching that url the correct url should resolve to: `https://mybitbucketserver.com/projects/PID/repos/BACKSTAGE/browse `(browse isn't really required as if i just end it with /BACKSTAGE it will resolve to /BACKSTAGE/browse.... am i missing something?

**Comment by OrkoHunter** [comment]
@regicsolutions Wow, thanks for the detailed input. You raise two issues and I think they are valid

1. Scaffolder: {{cookiecutter.storePath}} is set incorrect in case of Bitbucket Server. It should be complete URL like `https://mybitbucketserver.com/projects/PID/repos/BACKSTAGE/browse` instead of `https://mybitbuckerserver.com/PID/BACKSTAGE`

2. Looking at Bitbucket Server documentation https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp184

`/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/default-branch`

`https://mybitbucketserver.com/rest/api/1.0/projects/HOOV/repos/123/default-branch` should have resolved if `HOOV` and `123` exist.

Could this be a version issue, what is the version of your Bitbucket server?

**Comment by regicsolutions** [comment]
> @regicsolutions Wow, thanks for the detailed input. You raise two issues and I think they are valid
> 
> 1. Scaffolder: {{cookiecutter.storePath}} is set incorrect in case of Bitbucket Server. It should be complete URL like `https://mybitbucketserver.com/projects/PID/repos/BACKSTAGE/browse` instead of `https://mybitbuckerserver.com/PID/BACKSTAGE`
> 2. Looking at Bitbucket Server documentation https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp184
> 
> `/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/default-branch`
> 
> `https://mybitbucketserver.com/rest/api/1.0/projects/HOOV/repos/123/default-branch` should have resolved if `HOOV` and `123` exist.
> 
> Screenshot 2021-01-29 at 08 26 11
> 
> Could this be a version issue, what is the version of your Bitbucket server?

I am running version 7.4.1 which should be using the same v1 API

**Comment by OrkoHunter** [comment]
Aha, thanks @regicsolutions!

The 7.4.1 version does not have the latest `/default-branch` endpoint.
https://docs.atlassian.com/bitbucket-server/rest/7.4.1/bitbucket-rest.html

cc @kaparwan for #4322 since you are running a 5.x version of Bitbucket server.

As @freben suggests, let's support both the endpoints - request `/default-branch` first, if it returns 404, try `/branches/default`.

**Comment by regicsolutions** [comment]
> Aha, thanks @regicsolutions!
> 
> The 7.4.1 version does not have the latest `/default-branch` endpoint.
> https://docs.atlassian.com/bitbucket-server/rest/7.4.1/bitbucket-rest.html
> 
> cc @kaparwan for #4322 since you are running a 5.x version of Bitbucket server.
> 
> As @freben suggests, let's support both the endpoints - request `/default-branch` first, if it returns 404, try `/branches/default`.

Great, Thanks 

One Question: You mention as Scaffolder: {{cookiecutter.storePath}} is not correct for the scaffolder and https://mybitbucketserver.com/projects/PID/repos/BACKSTAGE/browse is correct, this isnt clear to me given i want to auto generate a catalog-info.yaml once the repo is generated and wont know what the project name and repo name is and need to read it from the cookiecutter input variable.

**Comment by OrkoHunter** [comment]
@regicsolutions Hey! The `catalog-info.yaml` should indeed be auto generated and filled in by cookiecutter variables.

https://github.com/backstage/backstage/blob/a034569199aa59830aad18e2b6ea91253d8dbc70/plugins/scaffolder-backend/sample-templates/docs-template/%7B%7Bcookiecutter.component_id%7D%7D/catalog-info.yaml#L8

This `cookiecutter.storePath` is a full URL to the newly created repository -

- `https://github.com/org/repo`
- `https://gitlab.com/org/repo`
- `https://mybitbucketserver.com/projects/PID/repos/BACKSTAGE/browse`
- ...etc

You mentioned that in your case, `cookiecutter.storePath` resolved to `https://mybitbuckerserver.com/PID/BACKSTAGE` which is unexpected. If you are using the latest scaffolder plugins or if you are on the master branch, `cookiecutter.storePath` should have been the full Bitbucket URL. Please create an issue if this is not what happened. 🙏 I'll cc @benjdlambert for extra eyes.

**Pull request merged**
