### PR TITLE
✨feat(homePlugin): changed list view of starredEntities to facilitate…

### PR DESCRIPTION
**Pull request by antoniobergas**
… distinguish entities with same name

## Hey, I just made a Pull Request!

I change the list view of the Starred Entities to group them by kind so in case of having entities with different kind but same name it easier to distinguish

image

Also moved the star icon to the left side before the entity name for make easier to remove them from preferred

image

This is included as an optional `groupByKind` property for the `StarredEntities` component 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

#16909

### CODE REVIEW

**Review by adamdmharvey — APPROVED** [review]
Definitely a step in the right direction; thx!

**Comment by antoniobergas** [comment]
Hi , still interested if it is valuable for the users of the Home plugin 😁

**Comment by antoniobergas** [comment]
Still interested! @freben it is #17474 ready or make sense to merge this one?

**Comment by freben** [comment]
@antoniobergas Thanks for your patience. #17474 is now merged. Would you mind rebasing this on latest master, and checking out

1. what's the experience like _without_ your change, and
2. _with_ your change, does it look _worse_ to have the iconography and custom formatting that #17474 added

Let's see where to take this PR, with this new background!

**Comment by antoniobergas** [comment]
Hey @freben ! Thanks for taking a look at this, will try your suggestions when I find a free spot. I let you know!

**Comment by creecree10** [comment]
Hi @antoniobergas 

I'm a designer working on Backstage 👋 One of the engineers shared your post and I have a few comments - hope you find them useful.

A few things to bear in mind:

- I can see that you've ordered the groups alphabetically, however, if my most used/visited item is a System, that could be quite annoying and result in a poor experience for the user to have to scroll to the end of the list to select that each time, especially if it's a long list. I'm not sure whether you're planning on limiting the number of starred items. If there isn't a limit to the number of starred items, the scanability of the list and subsequently the findability of the link someone's looking for is greatly reduced the longer the list is. To increase the user's success rate of scanning the content and finding what they're looking for, I would recommend introducing tabs to the card, so a user can select which group they want to access and be presented with a more focused list to scan and select from.

- Each star is quite far away from the title, creating a large gap. I assume a user can 'un-star' a URL from here. If so, I would highly recommend moving the stars to the left of the title. It will make it easier for a user to be confident that they're selecting (or rather de-selecting) the correct star.

Hope you find my comments useful.

**Comment by antoniobergas** [comment]
Hi @creecree10 !

Thanks a lot for your thoughtful feedback! I agree with your suggestions, make a lot of sense to improve more the user experience.

Once I've made these adjustments, I'll post in the original issue to gather feedback from the rest of people that were discussing this improvement in the `Home Plugin`. 

If you have any further suggestions or if there's anything specific you'd like me to consider during the implementation, please feel free to let me know.

**Comment by emmaindal** [comment]
Awesome, thank you so much @creecree10 @antoniobergas just one additional thing that came to my mind - can we make this grouping optional so that others can decide to make the grouping different if they want or keep as it is?

**Comment by antoniobergas** [comment]
That sounds like a good way to go @emmaindal , but actually not sure were we should specify this optional grouping, I'm guessing in the properties of the HomePage component in the routes?

Maybe @freben can you maybe guide me a little bit on this? Thanks!

**Comment by emmaindal** [comment]
I was thinking a property on the component similar to the [noStarredEntitiesMessage prop](https://github.com/backstage/backstage/pull/20121/files#diff-2584c9e5120adeca18446f47066623708fee1a0c5d822edd0751760b3b2597a9R50) and then maybe separate the rendering of grouped vs non-grouped entities

**Comment by antoniobergas** [comment]
Yeah @emmaindal you are totally right, I just get confused because of a custom wrapper we did in our internal instance. 😅

Thanks for the guidance! Will try to make some free spot this weekend if I can to work on this!

**Comment by antoniobergas** [comment]
@emmaindal @creecree10 I modify the code with your suggestions! Let me know if this is what you got on mind or if there's anything else to care about 😁

@freben I would like to know what you think with this new changes? Maybe its just enough? Not sure If this anwser properly to your suggestions.

**Review by emmaindal — APPROVED** [review]
Amazing, thank you so much for the contribution and the changes based on feedback from design. Would love to get @creecree10's look at it just one last time but approving to unblock the merge! (also thanks a lot for making the grouping by kind optional ⭐ ) and also a rebase is needed!

**Comment by creecree10** [comment]
Looking good to me @antoniobergas

**Comment by djamaile** [comment]
hi @antoniobergas could you rebase on top of master for me? 😄

**Comment by antoniobergas** [comment]
Hi @djamaile , yes , will do when I have a free spot, thanks 😁

**Comment by antoniobergas** [comment]
@djamaile done! everything should be fine now 😁

**Pull request merged**
