### PR TITLE
Allow customisation of create button in the scaffolder templates

### PR DESCRIPTION
**Pull request by punkle**
## Hey, I just made a Pull Request!

Allow customisation of create button in the scaffolder templates.

To use it:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-action-template
  title: Test Action template
  description: Test Action Template
spec:
  owner: backstage/techdocs-core
  type: service

  actionButtonText: Begin

  parameters: []
  steps:
    - ...
```

This will result in the button being marked as "Begin".

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thanks! Before diving in, could you provide a bit more information and motivation for why this needed and why it should be implemented as part of the template entity spec?

**Comment by OrkoHunter** [comment]
@punkle I want to ask - are you also thinking `Begin` vs `Create` can serve two different functionalities? Maybe the "Create" button is for creating something new but "Begin" is triggering a workflow that is powered by Software Templates? If they are doing this same things then perhaps, this layout config is polluting the template spec?

**Comment by punkle** [comment]
@OrkoHunter @Rugvip my thinking here is that in some cases a scaffolder template will result in the "creation" of something e.g. (pull a template, populate the template and create a new code repository) but in other cases it is pulling down an existing repo, editing or creating files and creating a pull request. In this case, the action button "Create" does not make as much sense.

By exposing this field to the template writer it allows them to decide what the button should show.

Does that make sense?

**Comment by OrkoHunter** [comment]
@punkle That sounds fair - especially when thinking about the new Embedded scaffolder page inside Catalog entity tabs.

As Software Templates/Scaffolder is evolving, my gut feeling is that it is becoming more of a workflow engine. Service Onboarding is where it all started, but it can actually execute any workflow e.g. create a new deployment pipeline, send a Slack notification, etc. All driven by a community of scaffolder actions.

Maybe it should always say "Start" for all such templates/workflows? But then agaub "Create" has been the go-to marketing keyword for this side of the house - letting developers create anything they want to e.g. service, pipelines, gcp projects, github teams, etc.

**Comment by acierto** [comment]
@punkle You can also achieve your customisation with the use of `ReviewStepComponent`. It allows you to override complete `ReviewStep`.

You can achieve it with


```

<ScaffolderPage
   components={{ReviewStepComponent: CustomStep}}
/>
```

```
export const CustomStep = (props: ReviewStepProps) => {
  const {
    disableButtons,
    formData,
    handleBack,
    handleCreate,
    handleReset,
    steps,
  } = props;
  return (
    <Content>
      <Paper square elevation={0}>
        <Typography variant="h6">Review and create</Typography>
        <StructuredMetadataTable
          dense
          metadata={getReviewData(formData, getUiSchemasFromSteps(steps))}
        />
        <Box mb={4} />
        <Button onClick={handleBack} disabled={disableButtons}>
          Back
        </Button>
        <Button onClick={handleReset} disabled={disableButtons}>
          Reset
        </Button>
        <Button
          variant="contained"
          color="primary"
          onClick={handleCreate}
          disabled={disableButtons}
        >
          Begin
        </Button>
      </Paper>
    </Content>
  );
};
```

**Comment by punkle** [comment]
@OrkoHunter I think if the button always showed "Start" it would catch all scenarios that I can think of.

@acierto I had been hoping it would be possible for the person writing the template could decide what the button would show. Your approach would allow us to set it globally for all templates which is useful but not quite as flexible.

**Comment by benjdlambert** [comment]
@punkle - given that - let's add the ability to grab the selected template in the `ReviewStep` component then, and then you can implement this however you please without having this a standard in the template spec just yet.

I'm not sure how best to do this yet, as there's a few ways, maybe #11819 or `__experimentalConfigure` or some standard in the template schema, so maybe to unblock you we could do that?

**Comment by benjdlambert** [comment]
Basically thinking that we could create a `useSelectedTemplate` hook that would be available to any `FieldExtension` or any `component` rendered in the `<Form />` to grab the template that you're currently rendering?

**Comment by punkle** [comment]
@benjdlambert that sounds like a good approach. I will close this for the moment. I may get cycles to revisit soon. :)

**Comment by benjdlambert** [comment]
@punkle nice thanks! Think that's a decent approach and sounds like a pretty useful hook that can be used for other things too

**Pull request closed without merging**
