### PR TITLE
docs: update tech insight usage

### PR DESCRIPTION
**Pull request by tanguyantoine**
## Hey, I just made a Pull Request!

- updates tech insight doc so that it does not reference old classes

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Xantier** [comment]
Thanks @tanguyantoine!

We'd need few items from you before we can merge this in:
1. Could you rebase and sign your commit
2. We'd need a changeset file to make a new release of this package (README.md files are shipped to npmjs so it's good to keep that up to date as well)

**Comment by tanguyantoine** [comment]
I've rebased and my commits are signed. Should I create a changeset for doc changes?

**Comment by benjdlambert** [comment]
@Xantier @tanguyantoine I went ahead and added a changeset for you. Lets get this shipped when it goes green 🟢

**Review by benjdlambert — APPROVED** [review]

**Comment by suuus** [comment]
Hey @tanguyantoine, congrats on your first merged PR 🎉 Nice work 👍 Please let me know if we can be helpful in any way.

**Pull request merged**
