### PR TITLE
do less renovate pinning - starting out with docker images

### PR DESCRIPTION
**Pull request by freben**
tried it out for a bit, not liking it unless we can rewrite our automerge tooling to deal with pulling them through - which i feel we don't have time for now

these damn things update like every single day

Another strategy might be to lock down to an exact version instead of eg just "12", and let THAT be pinned to a hash ... as long as it doesn't try to also be helpful and update that version with every release. Happy for feedback on that one

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hmm, I think that this could lead to a security issue. The pinning is not just versions, it's the sha256 digest validation as well too right?

**Comment by freben** [comment]
Well yeah sure the version number is in there too (and it is still in there after this PR). Thing is, if we keep "12" in there as the version number, renovate gives us PRs at an unsustainably high throughput to update that hash. Feels like I'm just chasing my own tail merging and merging those all the time by hand. So something needs to change somewhere. Either we stop pinning these (like it used to be), or we try out perhaps choosing a more precise version and see if that's better

**Comment by benjdlambert** [comment]
> Feels like I'm just chasing my own tail merging and merging those all the time by hand

I wonder if we can just update our automerge tooling for this like we do other rennovate PR, considering a lot of these containers are mostly used in CI workflows, it's pretty sure to assume that if the build passes - we're good.

The release tooling flow is a little trickier of course.

**Review by Rugvip — APPROVED** [review]
Yep it's too much for sure 👍 

If we were to completely automate the merge of these it would defeat the purpose too really. Not that there is much of a purpose to begin with tbh, since we're not manually reviewing these changes in any way.

**Comment by freben** [comment]
Also seems like there's only minor version numbers on the pg images - `16.2` is the closest you get? Hmmm

**Pull request merged**
