### PR TITLE
docs: features/software-catalog/external-integrations

### PR DESCRIPTION
**Pull request by freben**

### CODE REVIEW

**Comment by Fox32** [comment]
Very good. One topic we have internally is to implement some kind of federation between multiple Backstage instances and implementing a custom processor was exactly what we also had in mind!

**Comment by freben** [comment]
@Fox32 Hmmmm. Federation is actually an interesting approach to achieving security boundaries. Is that why you are looking into it? #3218

**Comment by Fox32** [comment]
@freben Access rights is one reason, but the topic is a bit bigger:

Beside our internal instance we want to help our customers to build up their own instances. They won't be able to use our instances, as they want to connect their CI/CD environment and their custom tooling. CI/CD might be quite different between each other. However we want to share stuff like documentation and entity definitions of selected components we share with them (especially APIs). Think about them like other teams in the same company were we want to transparently share components and their APIs, but the teams use a different tooling.

**Review by Rugvip — APPROVED** [review]
Awesome, much needed stuff! 😁

**Pull request merged**
