### PR TITLE
Update locations.md

### PR DESCRIPTION
**Pull request by johnrkriter**
The purpose of this change is to highlight the style of API access token required to enable the Bitbucket Cloud integration as it was not previously clear. The existing error will not distinguish between an Atlassian Account key(which wont work) and a Bitbucket App Password(which will.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Thanks for this contribution @johnrkriter, this looks good to me 🚀 

@pjungermann any chance you can give this a look too?

**Comment by awanlin** [comment]
Hi @johnrkriter, if you can rebase that should get the builds green 🚀

**Comment by johnrkriter** [comment]
Item should now just be pending review @awanlin

**Comment by awanlin** [comment]
@benjdlambert or @vinzscam, can you give this PR a quick look, please? Just a simple but helpful docs update 🚀

**Review by pjungermann — APPROVED** [review]
The field itself is called `appPassword` and there is a mention of app password in the documentation for that field as well. However, a reference to the related external documentation sounds like a good idea.

I'm not aware that you can use an Atlassian Account API key for Bitbucket Cloud APIs. 🤔 
I'm only aware of the app password and OAuth options.

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice thanks :tada:

**Pull request merged**
