### PR TITLE
Added alert popup in the bazaar plugin (Add ,Update , Delete project)

### PR DESCRIPTION
**Pull request by AmbrishRamachandiran**
## Hey, I just made a Pull Request!

Adding alert popup in the bazaar plugin whenever project  created , updated , delete 
this will improve user experience similar to shortcut, playlist plugins  (where popups are added similar to this)

ADD PROJECT:
ADD PROJECT

UPDATE PROJECT:
UPDATE PROJECT

DELETE PROJECT:
DELETE PROJECT

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by AmbrishRamachandiran** [comment]
@camilaibs @freben This feature is similar to shortcuts plugin & playlist plugin please review

**Comment by AmbrishRamachandiran** [comment]
Please reopen it

**Comment by AmbrishRamachandiran** [comment]
@freben @camilaibs please review

**Review by freben — APPROVED** [review]
Sure.

**Pull request merged**
