### PR TITLE
permission-node: remove references from backend-common

### LINKED ISSUE #24869: [Permissions] Get rid of the `backend-common` dependencies used by the `PermissionService`

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

`tokenManager` definition is now imported from `@backstage/backend-plugin-api`.

Closes #24869

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — COMMENTED** [review]
needs changeset

**Review by freben — COMMENTED** [review]
Are you skipping the changeset because considering them to be type compatible?

**Comment by vinzscam** [comment]
> or are you skipping the changeset because considering them to be type compatible?

Screenshot 2024-05-23 at 16 54 19

**Review by Rugvip — APPROVED** [review]
Nice! :+1:

**Pull request merged**
