### PR TITLE
feat: add documented component to uffizzi environment

### PR DESCRIPTION
**Pull request by pjungermann**
So far, none of the components at the uffizzi environment have techdocs.
Hence, there are no docs available within this environment
and related features are not covered.

This change will add an example from techdocs-backend plugin
to the deployed examples.

It was possible to register this catalog file manually,
however the build of the docs fail due to missing Docker.

To allow the generation of docs, we use the local generator
(no docker in docker) and install required dependencies.

As we don't want all dependencies for all (default) extensions
to be installed at this environment, the original example at
techdocs-backend plugin was copied and reduced
(PlantUML extension example was removed).

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by pjungermann** [comment]
Not sure if you prefer docker in docker for the techdocs generator at the uffizzi environment.

**Comment by pjungermann** [comment]
ok, seems like it would require some more deps without docker (for that example).

**Review by freben — APPROVED** [review]
Thanks!

**Comment by freben** [comment]
@pjungermann you saying that this isn't ready to merge yet?

**Comment by pjungermann** [comment]
@freben yeah.. I've checked it at the created environment and it still fails to generate the docs. The error complains about missing plantuml. The example file seems to use it.

I see two options:

1. add the other dependencies to the packages/backend/Dockerfile as well as contained at the techdocs container image
2. use docker in docker -- but I'm not sure if this is supported by uffizzi and I couldn't find anything about it at their docs.

Do you have any preferences?

**Comment by pjungermann** [comment]
I could convert it into a draft until this is solved.

**Comment by freben** [comment]
I'm not sure honestly. Ideally it'd be some docs that require as little as possible. Maybe other, simpler, docs can be added elsewhere or so?

**Comment by pjungermann** [comment]
not stale

**Comment by freben** [comment]
@pjungermann just to double check, you'd look into adding some little doc that better fit the need right?

**Comment by pjungermann** [comment]
@freben at the moment, I consider to rather use the default container image instead so we can test the full thing 🤔 

I just came back from vacation, though. Give me a few more days 😅

**Comment by freben** [comment]
Aight I'll just await it to go out of draft essentially

**Comment by pjungermann** [comment]
@freben I've checked with folks at uffizzi re the option on dind. (I assumed, it is available, just wanted to be sure.) They told me that they consider adding this option.

In the future, it may make sense to use the default techdocs-container.

As I have to prepare a different example or modify the existing one, I tried to find a way to make it usable here.

Using a commit hash instead of the branch failed at the UrlReader and the uffizzi preview deploy step at the GitHub actions uses the master branch for the execution so far.

It is possible to pass a git-ref to the "preview-action" and we could use data from the event payload.

example:

```
      "head": {
        "label": "Bonial-International-GmbH:pjungermann/uffizzi-techdocs",
        "ref": "pjungermann/uffizzi-techdocs",
         "sha": "1f849a34149340bf0e832ac31c94ae6aea98455e",
# ...
```

Replacing `master` with `$.head.ref` wouldn't work. We could also replace the `backstage/backstage` part, however we couldn't pass it as `git-ref` to the action.

I will continue in the next days.

**Comment by pjungermann** [comment]
Correction:
```
info: Step 1 of 3: Preparing docs for entity component:default/documented-component {"timestamp":"2023-04-06T07:42:54.334Z"}
error: Failed to build the docs page: Request failed for https://api.github.com/repos/backstage/backstage/branches/4cb4c6afd8e15d02e737b6c43a83685b1066eff8, 404 Not Found {"timestamp":"2023-04-06T07:42:54.661Z"}
```

Loading the catalog file via UrlReader works fine with the commit hash, however the techdocs builder (or prepared) fails while using the GithubUrlReader.readTree which starts with trying to `getRepoDetails`. And that one attempts to look up branch details assuming the value is a branch name which fails with 404 as the branch does not exist.

The repo details are used to get

- the commitSha from the branch details response
- archive_url from the repo details response

At GithubUrlReader.search, it uses repo.trees_url on top.

No other data is needed from both response objects.

One option is to add support for commit hashes at GithubUrlReader.readTree

**Comment by pjungermann** [comment]
I found that the API `/repos/backstage/backstage/commits/{ref}/status` can be used as replacement for both API calls for repo and branch and can be used with a branch name like `master` as well as a commit sha.

This would reduce the API calls from 2 to 1 for that method and add support for commit hashes for readTree + allows to use commit hashes here for the catalog locations instead of fixed to `master`.

**Comment by pjungermann** [comment]
Another news to that: It seems to resolve the use of slashes in branch names as well - at least for readTree then.

I tried the "get combined commit status" API with one of the active branches: `/repos/backstage/backstage/commits/rugvip/confload/status` and it worked fine and provided the sha, etc.

**Comment by pjungermann** [comment]
As the other PR was just merged, I will continue later today.

**Comment by pjungermann** [comment]
Unfortunately, the previous attempt to add the git-ref to the uffizzi action was buggy and I need to wait for the bugfix PR to be merged first to be able to continue here with the testing.

**Comment by pjungermann** [comment]
not stale

**Comment by pjungermann** [comment]
no stale

**Comment by pjungermann** [comment]
You can find the tech doc integration at https://pr-16721-deployment-25038-backstage.app.uffizzi.com/docs/default/component/documented-component-uffizzi/

_(I've realized a little styling bug with warn admonition.)_

**Comment by pjungermann** [comment]
@freben @agentbellnorm the PR is ready for review now.

**Review by freben — APPROVED** [review]
Nice!

**Review by agentbellnorm — APPROVED** [review]
Very nice! Thanks @pjungermann!

**Pull request merged**
