### PR TITLE
chore: Exporting KubernetesClientProvider as requested in issue #10457

### PR DESCRIPTION
**Pull request by luchillo17**
Signed-off-by: Carlos Esteban Lopez <luchillo17@gmail.com>

## Hey, I just made a Pull Request!

As requested in issue #10457 the KubernetesClientProvider is now exported as well from the `@backstage/plugin-kubernetes-backend` package.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@mclarke47 one for you :pray:

**Comment by menehune23** [comment]
@luchillo17 Thank you! Could you also include all the backend auth providers as well as the auth provider generator?

**Comment by mclarke47** [comment]
You'll need to generate a new api report

**Comment by menehune23** [comment]
> You'll need to generate a new api report

@mclarke47 Could you clarify:
- What is an API report and how is it generated?
- Who that was directed toward? (was it in response to my ask, or a task for the OP?)

Thanks :)

**Comment by luchillo17** [comment]
> @luchillo17 Thank you! Could you also include all the backend auth providers/translators as well as the auth provider generator? This PR, plus those changes will really enable custom backend plugins to authenticate consistently with the rest of backstage.
> 
> See: https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/kubernetes-auth-translator/KubernetesAuthTranslatorGenerator.ts

Do you want me to include the cluster locators and the routes? It would be great if you give me a precise list of which ones to export.

**Comment by menehune23** [comment]
> Do you want me to include the cluster locators and the routes? It would be great if you give me a precise list of which ones to export.

Sure thing! The list is essentially everything in this directory: https://github.com/backstage/backstage/tree/master/plugins/kubernetes-backend/src/kubernetes-auth-translator

**Comment by mclarke47** [comment]
Could you mark them as alpha instead of public?

**Comment by luchillo17** [comment]
Hi @mclarke47, the MR was marked as stale, anything left todo?

**Review by Rugvip — COMMENTED** [review]
Sorry this one slipped off my radar a bit.

I have a concern with the `@alpha` tags, which is that `kubernetes-backend` doesn't have the experimental types build enabled, meaning the `@alpha` tags don't really do much at all. At the moment they're just a very weak indicator and it is not obvious to a consumer that these types might change. As long as you're aware of that and feel it's alright @mclarke47 I feel this is good to merge.

Another option is to enable the experimental types build, meaning these symbols will only be available from `@backstage/plugin-kubernetes-backend/alpha`, but that is likely to have a pretty big impact, and might not be possible at this point either.

**Review by Rugvip — APPROVED** [review]

**Review by mclarke47 — APPROVED** [review]

**Pull request merged**
