### PR TITLE
Add Via as a backstage adopter

### PR DESCRIPTION
**Pull request by vagnerguedes**
Add Via as a backstage adopter

Signed-off-by: Vagner Guedes vagnerguedes@gmail.com

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vagnerguedes — COMMENTED** [review]
Signed-off-by: Vagner Guedes <vagnerguedes@gmail.com>

**Comment by freben** [comment]
@vagnerguedes Sorry - the signoff goes inside the commit body. The text you put in the comment looks correct (when editing it - so that the `<>` are there), but it needs to be in git's history.

If you are doing this change by editing the file in GitHub's web page, a tip is that you can put that signoff line in the second edit box here, BEFORE pressing Propose changes:

Screen Shot 2022-03-09 at 17 05 47

**Review by benjdlambert — APPROVED** [review]
Welcome! I went ahead and fixed up the signed-off declaration for you, you were missing the brackets on the email :)

**Comment by vagnerguedes** [comment]
tks a lot @benjdlambert

**Pull request merged**
