### PR TITLE
plugin: introduce gitlab ci/cd statistics module

### PR DESCRIPTION
**Pull request by djamaile**
## Hey, I just made a Pull Request!

Hello! I started on the implementation for the gitlab ci/cd statistics module based on the  ci/cd statistics plugin. It's still not done but I think it's ready for the first round of review 😸 . Also, currently `packages/app/src/apis.ts`  and the `EnittyPage` has some code that shouldn't be there, but I am leaving it there for now to make it easier to test locally! 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x ] Screenshots attached (for UI changes)
- [x ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

Screenshot 2022-03-11 at 19 53 45

### CODE REVIEW

**Comment by djamaile** [comment]
my yarn.lock looks really weird and probably why `tsc` is failing. Am I pulling in something weird? 😓

**Comment by freben** [comment]
Hm did you just generate that package using `yarn backstage-cli create`? It looks pretty anemic in its package.json; very few scripts, not a single devDependency... I would guess your dependencies there are not in sync with what's in the rest of the repo, making it pull in the world twice

**Comment by djamaile** [comment]
@freben yeah it's happy now, took a few tries though lol 😁

**Comment by jhaals** [comment]
Is development still ongoing or is it ready for a "regular" PR? 😁

**Comment by djamaile** [comment]
@jhaals still ongoing! Was recovering from chicken-pox, will continue on Monday 🌝

**Comment by jhaals** [comment]
Oh snap, I heard the news but forgot 😓 Just wanted to double check that you wasn't waiting on us.

**Comment by djamaile** [comment]
@jhaals any idea why I get these type of errors? Locally I don't seem to get them so it's hard to debug

**Review by freben — COMMENTED** [review]
Hey @djamaile - I rudely rebased this on master because it has a neat helper script to update all dependency versions for us so that your package.json got a little cleanup. So you'll have to pull the latest changes from remote now. It typechecks locally for me now, let's see if it goes green in CI too

**Comment by freben** [comment]
Yep now it seems to be down to failing tests in this code - progress! Handing back to you then :)

**Comment by djamaile** [comment]
@freben green now! thanks for the help btw 🙏

**Review by freben — APPROVED** [review]

**Pull request merged**
