### PR TITLE
plugins should not depend on core-api

### PR DESCRIPTION
**Pull request by freben**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by OrkoHunter — APPROVED** [review]
💯

**Comment by mfrinnstrom** [comment]
Would it make sense to write a test that checks this? Just a thought 🙂

**Comment by freben** [comment]
Yep, this should totally be part of the backstage-cli `lint` command I think.

**Comment by OrkoHunter** [comment]
I have seen folks importing the frontend Discovery API types in the backend plugins and vice-versa. Sounds like `backstage-cli lint` can really have some comments on the project dependencies!

Should I create an issue about this?

**Comment by freben** [comment]
Sure, go ahead

**Review by jhaals — APPROVED** [review]

**Review by Rugvip — APPROVED** [review]

**Pull request merged**
