### PR TITLE
Corrects dynatrace plugin README.md

### PR DESCRIPTION
**Pull request by ionSurf**
## Dynatrace pluguin proxy configuration fix

Provides correction to dynatrace plugin proxy configuration instructions. When attempting setup, the backstage proxy service for dynatrace will return a 404 error due to trying to retrieve a missing parameter in the configuration. 

### Current documentation
Screenshot 2024-01-24 at 1 26 22 PM

While the readme instructions advise to setup proxy configurations like this: 

```js
proxy:
  '/dynatrace':
    target: 'https://example.dynatrace.com/api/v2'
    ...
```

The parent key "endpoints" is missing and should be added like the following: 

```js
proxy:
  endpoints:
    '/dynatrace':
      target: 'https://example.dynatrace.com/api/v2'
      ...
```

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Thanks for this, good fix @ionSurf 🚀

**Review by awanlin — CHANGES_REQUESTED** [review]
Sorry, was too fast the other day, as this is a `README` in a package it needs a changeset. The `README` ends up on NPM and we would want it corrected there as well, the changeset tells the release process that a new version of this package needs to be created. It's pretty easy to do, here more details: https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets

**Comment by awanlin** [comment]
@ionSurf, any chance you still plan to see this PR get merged? Just need a changeset?

@tudi2d @Rugvip this is a correction that's needed, not sure what we can do to still get this in?

**Comment by tudi2d** [comment]
as this PR was closed I took the freedom to pick the commits & create a new one and added a changeset.

**Pull request closed without merging**
