### PR TITLE
fix: Added missing k8s common dependency to aws catalog module

### LINKED ISSUE #16380: 🐛 Bug Report: plugin-catalog-backend-module-aws missing dependency in 1.11.0
### 📜 Description

Since upgrading to backstage `1.11.0` the `@backstage/plugin-catalog-backend-module-aws` module is missing an explicit required dependency `@backstage/plugin-kubernetes-common`. Presumably this was coming along for the ride via another package's deps or transitives.

### 👍 Expected behavior

backend starts correctly.

### 👎 Actual Behavior with Screenshots

```sh
Starting backstage with config app-config.yaml and app-config.local.yaml
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '@backstage/plugin-kubernetes-common'
Require stack:
- /app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/index.cjs.js
- /app/packages/backend/dist/index.cjs.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:81:25)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/index.cjs.js:5:30)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@backstage/plugin-catalog-backend-module-aws/dist/index.cjs.js',
    '/app/packages/backend/dist/index.cjs.js'
  ]
}
Backstage stopping
```

### 👟 Reproduction steps

- create a fresh app
- yarn add @backstage/plugin-catalog-backend-module-aws
- configure the aws module in the catalog.ts
- start the backend 

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jgrigg**
## Hey, I just made a Pull Request!

Since upgrading to backstage 1.11.0 this dependency needs to be explicit.

resolves #16380 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jgrigg** [comment]
Scratching my head as to why it would not be failing in CI here but i guess if we're `yarn` installing the entire universe for the tests rather than just on a per-plugin basis it could explain the issue.

**Comment by Rugvip** [comment]
This is caused by a bug in our lint rule, we should be checking internal deps too but filter them out [here](https://github.com/backstage/backstage/blob/d29ccca36b30a75a7a3cceee539536422441085f/packages/eslint-plugin/rules/no-undeclared-imports.js#L154). Fix is free for anyone to pick up as I've got a few days off, but otherwise I'll fix it in a bit.

**Review by freben — APPROVED** [review]

**Comment by benjdlambert** [comment]
Fixed over in #16413

**Comment by freben** [comment]
Hey @jgrigg I am super grateful that you added this fix, but it seems we're actually in need of a larger sweeping fix for the same reason, and as @benjdlambert said above there's a patch release coming out today that hopefully addresses them all in one go. So I'll close this off so as not to get unintended overlaps, but again, thank you for taking the time to make this PR.

**Pull request closed without merging**
