### PR TITLE
add metadata column on notification payload object

### PR DESCRIPTION
**Pull request by esw-afabiano**
## Hey, I just made a Pull Request!

As described in the documentation at [Backstage Notifications System](https://github.com/backstage/backstage/blob/master/beps/0001-notifications-system/README.md) the metadata column which was anticipated, is being added in this PR.
     
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by esw-afabiano** [comment]
Hey @Rugvip 

I'd like to make the entire folder public: [notifications-backend/src/database](https://github.com/backstage/backstage/tree/master/plugins/notifications-backend/src/database).

For example, I'm implementing a piece of code where I need to fetch notifications to integrate with an external tool. This tool does not work in real-time, so using processors is not suitable. Instead, it's a job that fetches notifications once a week, aggregates the data, and sends notifications via Slack.

What do you think?

**Comment by freben** [comment]
We never expose database details. They are always private to a plugin, so that plugins can iterate freely on their underlying models and apply both fixes and optimizations without breaking integrations.

The public REST and event APIs are always the only integration points.

**Comment by esw-afabiano** [comment]
> We never expose database details. They are always private to a plugin, so that plugins can iterate freely on their underlying models and apply both fixes and optimizations without breaking integrations.
> 
> The public REST and event APIs are always the only integration points.

No problem. I have already created a private wrapper.

I would be wonderfully grateful if my changes to this PR made sense and were merged.

**Comment by freben** [comment]
pinging @backstage/notifications-maintainers

**Comment by esw-afabiano** [comment]
> pinging @backstage/notifications-maintainers

Hey, do you have any updates. I'm looking forward to this PR being merged

**Comment by mareklibra** [comment]
I saw implementing multiple features in parallel even before. In my opinion, it's wasting of  time and effort.
New ideas can be brought during review or a preceding discussion in a feature request or BEP or discord.

For sure, contributions are highly appreciated. Thanks everyone pushing their PRs.  
By increasing PR acceptance ratio, the contributors will be kept encouraged to contribute more in the future.

**Comment by esw-afabiano** [comment]
@mareklibra nothing specific. I originally created this code for my internal product and then externalized it here. I noticed that there was already a similar PR before mine. We can disregard this one and focus specifically on what has already been created by @acierto.

**Comment by acierto** [comment]
@mareklibra [My PR](https://github.com/backstage/backstage/pull/25066) is following the agreed changes based on discussion and modified BEP https://github.com/backstage/backstage/pull/24562

**Comment by mareklibra** [comment]
Per clarification above, closing.

**Pull request closed without merging**
