### PR TITLE
Change tsc output dir to dist-types

### PR DESCRIPTION
**Pull request by feiming**
## Change tsc output-dir to `build`
conflicting `dist` dir usage, it's preventing the plugin from being built outside of backstage monorepo

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by Rugvip** [comment]
Yep, this is an issue indeed, but tbh I don't using a separate folder is what we want to do in this case.

I'm imagining it would be possible to switch the behaviour a bit for single-plugin repos, where we put the types inside `dist/.types` or something like that, and then exclude that folder when publishing.

Do you want to take a stab at that? Or perhaps open an issue where we can discuss different approaches.

**Comment by feiming** [comment]
`yarn build` will delete `dist` on run. We'll still face the same issue where `yarn build` can't find types

**Comment by Rugvip** [comment]
@feiming Right, we'd have to do some changes to the build process in the CLI that makes it aware of whether it's executing in single-plugin or monorepo mode, and then act accordingly. Afaik a safe way to check whether we're in a monorepo or not is to check `paths.targetDir === paths.targetRoot`.

**Comment by Rugvip** [comment]
Another option would be to do this, and change the build accordingly, but I would prefer a name like `dist-types` or something like that. `build` and `dist` are just two names for the same concept, and we settled on using `dist` and should stick to that imo. Prefixing with `dist-` (instead of something like `types-dist`) ensures that the folder is located next to the `dist` folder in directory views, which I think is conventient.

**Comment by feiming** [comment]
I'm fine with any name. I'm new to typescript, I have no preference. I'll switch to `dist-types`.

btw, is E2E test broken? I tried running it on master and got the same result.

**Comment by Rugvip** [comment]
e2e tests require that you run `yarn tsc` and `yarn build` in the root first. That should be working fine in master afaik.

**Review by Rugvip — APPROVED** [review]
Looks good, thanks! :grin:

**Pull request merged**
