### PR TITLE
feat(backend-plugin-api): provide a utility to bundle several features in one package.

### PR DESCRIPTION
**Pull request by davidfestal**
## Hey, I just made a Pull Request!

This PR provides an utility function in the alpha API to bundle several backend features (plugin or module) as a single `BackendFeature` exported as the default export in one package.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Sweet! :+1: 

Do you want to take a stab at hooking this up to the dependency injection as well? Our idea has been to introduce this alongside the ability to depend on services to decide on and configure the exact features. Of course most notably it's the access to config that's important, but already thinga like logging and future discovery service might be useful too.

One limitation we'd put in place is that you can not provide any services that have already been instantiated

**Comment by davidfestal** [comment]
> Sweet! 👍
> 
> Do you want to take a stab at hooking this up to the dependency injection as well? Our idea has been to introduce this alongside the ability to depend on services to decide on and configure the exact features. Of course most notably it's the access to config that's important, but already thinga like logging and future discovery service might be useful too.
> 
> One limitation we'd put in place is that you can not provide any services that have already been instantiated

Not sure I see what precisely you mean.
Would you have some code example of what you have in mind ?

**Comment by Rugvip** [comment]
@davidfestal yep! something like this:

```ts
export default createBackendFeatureBundle({
  // Dependencies, only supports root-scoped services
  deps: {
    config: coreServices.rootConfig,
    logger: coreServices.rootLogger,
  },
  // This factory is called as soon as possible at startup, blocking initialization of other services
  // until it has completed. It's because we don't know exactly what features it might provide, and
  // we want it to be able to add as many features as possible. If this factory provides any service
  // that has already been initialized, the backend will fail to start.
  async *factory({ config, logger }) {
    if (config.getOptionalBoolean('backend.enableFoo')) {
      yield import('@internal/backstage-plugin-foo-backend');
    } else {
      logger.info('Foo backend is not enabled, skipping');
    }
  }
})

Make it an async generator because this might be convenient, but very much open to just keeping it a simple array return too.
```

**Comment by Rugvip** [comment]
Tiny bit of history here too is that we used to have "shared environments" that could be installed in a backend instance, but [we decided to remove](https://github.com/backstage/backstage/pull/18834) those in favor of something like this.

**Pull request closed without merging**
