### PR TITLE
Both Authorization patterns are valid for both versions of Bitbucket

### LINKED ISSUE #4554: [Scaffolder] Component creation failing in publish stage after #4489 fix...
## Expected Behavior

Creating bitbucket repo using `/create `by choosing one of the template.

## Current Behavior

```
Component Id	nodejs
Owner	<Owner>
Store Path	https://mybitbuckthost.com/PRJ/repo11
Access	<Owner>
Failed to create component
info: Will now store the template {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:20.929Z"}
error: Stage failed with error: Not a valid response code {"errors":[{"context":null,"message":"You are not permitted to access this resource","exceptionName":"com.atlassian.bitbucket.AuthorisationException"}]} {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:21.041Z"}

```
## Possible Solution

I was trying to debug this in local but getting error in Templator stage in local . due to Docker dependency. It is looking for mkdocs docker container download. Though, I have mkdocs installed locally. It should have  picked up mkdocs binary directory and not to go for docker for mkdocs. So couldn't debug it further as I couldn't reach to publish stage in local. 

## Steps to Reproduce

1.  create mono-repo 
2. yarn install; yarn tsc; yarn build 
3. run docker for both frontend and backend 
4. register template ( nodejs/java/..) using /create 
5. fill template values 
6. `storagePath: https://<mybitbucket_host>/<PRJ>/repos  `  #PRJ -> my project in bitbucket 
7. Click next 
8. and getting above error 

```
Failed to create component
info: Will now store the template {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:20.929Z"}
error: Stage failed with error: Not a valid response code {"errors":[{"context":null,"message":"You are not permitted to access this resource","exceptionName":"com.atlassian.bitbucket.AuthorisationException"}]} {"id":"c20f9d36-9955-41f8-af71-7cf19889ac87","stage":"Publish template","timestamp":"2021-02-16T23:42:21.041Z"}
```

## Your Environment

NodeJS Version (v12): v14.15.4
Operating System and Version (e.g. Ubuntu 14.04): UBuntu14
Browser Information:: Chrome
Atlassian Bitbucket v5.11.1 (own-hosted)

### PR DESCRIPTION
**Pull request by benjdlambert**
Fixes #4554

Both the combination of `appPassword` and `username`, or `token` is valid for both `onprem` and `cloud` versions of Bitbucket. Previously you needed to have both forms of authentication for it to work properly. But this isn't the case.

Updated the publisher to generate the Authorization header from config, and use that in the proper places.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4651-ovgiq62ospnmvlrqioypnn2qcnsvlmbq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6034b81a65f8175958f766ed

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4651-ovgiq62ospnmvlrqioypnn2qcnsvlmbq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6034b81a65f8175958f766ed

**Review by freben — APPROVED** [review]
Nice!

**Comment by kaparwan** [comment]
thank you @blam @freben  
:-)

**Comment by BlaM** [comment]
Wrong BlaM ;) - That "Thank you" is for you, @benjdlambert

**Comment by kaparwan** [comment]
Thank you.   :-)
Sorry  about that.
-- 
Sent from iPhone

**Comment by benjdlambert** [comment]
@blam wanna trade github handles? 😂

**Comment by kaparwan** [comment]
😂 --
Sent from iPhone

**Comment by BlaM** [comment]
Sorry, this is the ONE page where I was early enough to get the handle I wanted ;) - I guess you know the feeling :D

**Pull request merged**
