### PR TITLE
skip entities if location returns multiple similar entities.

### PR DESCRIPTION
**Pull request by punkle**
- previously if a location returned a whole lot of entities some
   of which were duplicated, then the whole batch were failing.
 - this changes to to instead log an error where there are duplicates
   and continue to load the remaining good enities.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4720-ohaav3cjjldavkg29iahjhtz55msxn93.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60391ef5fcb22d277161bd0c

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4720-ohaav3cjjldavkg29iahjhtz55msxn93.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60391ef5fcb22d277161bd0c

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4720-ohaav3cjjldavkg29iahjhtz55msxn93.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60391ef5fcb22d277161bd0c

**Comment by freben** [comment]
This sounds very dangerous, and can lead to a "takeover" where a near-duplicate of an entity is put in place by a malicious user, so that the new entity "competes" for the slot taken by the old one.

The actual problem, rather, may be that the batch writes fail at a too large granularity. There should be logic that when a batch write fails, it instead tries to write the individual entities one by one. Right?

@Rugvip foe visibility

**Comment by punkle** [comment]
@freben thanks for the feedback. I wonder if the batch sizes were smaller, and if the first duplicate makes it into into an earlier batch, then it might succeed and the second might fail.

How can it be known which of the duplicates is valid?

I may be misundering the context fully. But I wonder, in the absence of knowing which is the true valid entity,  would it be safer to reject all the duplicates.

**Comment by Rugvip** [comment]
Discussed this a bit more, and thinking that it's likely best to skip this for now and instead consider it as part of the upcoming catalog work. We'll be splitting the processing up into much smaller chunks, so the reasoning around this will likely get a bit clearer. This change is also a lil bit scary as mentioned above.

Do you want to create an issue for this instead and we'll add it to https://github.com/backstage/backstage/milestone/23 ?

**Comment by Rugvip** [comment]
@punkle Thanks! 👍 , added to the milestone

**Pull request closed without merging**
