### PR TITLE
adr plugin - Added support for new backend system

### PR DESCRIPTION
**Pull request by angeliski**
## Hey, I just made a Pull Request!
Moving ADR to use new backend system (#18301)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by kuangp — APPROVED** [review]
Looks good to me! Thanks for helping update this! 

cc: @benjdlambert to take a look as well since I haven't had a chance to play with the new backend system yet

**Comment by benjdlambert** [comment]
@angeliski  @kuangp looks good to me - needs a rebase though 👍

**Comment by angeliski** [comment]
Done :)

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Oops - this needs a rebase again 😅 sorry!

**Comment by benjdlambert** [comment]
@angeliski do you have time to fix this up?

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice thanks :tada:

**Pull request merged**
