### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by JimHaughwout**
Swapping our lead developer for my name

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @JimHaughwout! We need a DCO signoff on this commit! You can read the bots comment and find the relevant documentation to help you out!

**Comment by freben** [comment]
@daftgopher I'll ping you in here as well, regarding the DCO.

If you guys want, we can reconstruct this PR for you and ping you in that one, to get the DCO legalese arranged properly.

**Comment by daftgopher** [comment]
@freben No worries, I'll get you a new commit with a DCO signoff in a few. Assuming it's the same DCO process (involving  a signed commit) used by all cross-repo PRs to Backstage or is there something else for this type of change specifically?

**Comment by freben** [comment]
Same process as always!

**Comment by daftgopher** [comment]
I opened a PR that should have the with the DCO signoff commit at #10727. I think we can close this one after that's merged.

**Comment by freben** [comment]
Superseded by #10727

**Pull request closed without merging**
