### PR TITLE
Fix for registering entity via scaffolder catalog:register action results in warnings

### LINKED ISSUE #17818: 🐛 Bug Report: registering entity via scaffolder `catalog:register` action results in warnings
### 📜 Description

When I create a new catalog file via scaffolder, and use `catalog:register` to make this entity immediately visible to the catalog, a postponed catalog discovery results in a warning like:

> catalog warn Source GitlabDiscoveryEntityProvider:dev detected conflicting entityRef location:default/generated-5c9b5c02590664368c4333429612cbcf4c6573ff already referenced by url:https://git.example.com/repos/fooo/bar/-/blob/main/catalog-info.yaml and now also GitlabDiscoveryEntityProvider:dev type=plugin

### 👍 Expected behavior

The manual registered location does not result in conflict warnings

### 👎 Actual Behavior with Screenshots

see description.

### 👟 Reproduction steps

Use a scaffolder template ike: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml

1.  create repo via scaffolder
2. wait for the `EntityProvider` (e.g. `GithubEntityProvider` or `GitlabDiscoveryEntityProvider`) to find the created location entity

### 📃 Provide the context for the Bug.

**app-config.yaml**

```yaml
catalog:
  rules:
    - allow: [API, Component, Group, Location, Resource, System, Domain, User, Template]
  providers:
    gitlab:
      dev:
        host: git.example.com
        branch: main
        group: repos/root
```

With this config we scan periodically for newly added / updated entities.

With the scaffolder action `catalog:register` a new location is added to the catalog with the `locationKey` set to `url:https://git.example.com/repos/fooo/bar/-/blob/main/catalog-info.yaml` (for the example from the description):

https://github.com/backstage/backstage/blob/93daeb898f77076049c4862b0c24a94721344671/plugins/catalog-backend/src/modules/core/DefaultLocationStore.ts#L65-L69

The `EntityProvider` tries to register the discovered location with `locationKey`  set to `GitlabDiscoveryEntityProvider:dev`:

https://github.com/backstage/backstage/blob/93daeb898f77076049c4862b0c24a94721344671/plugins/catalog-backend-module-gitlab/src/providers/GitlabDiscoveryEntityProvider.ts#L204-L210

this results in conflicting keys:

https://github.com/backstage/backstage/blob/93daeb898f77076049c4862b0c24a94721344671/plugins/catalog-backend/src/database/operations/refreshState/checkLocationKeyConflict.ts#L40-L48

and

https://github.com/backstage/backstage/blob/93daeb898f77076049c4862b0c24a94721344671/plugins/catalog-backend/src/database/DefaultProviderDatabase.ts#L177-L186

### 🖥️ Your Environment

backstage 1.13.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Andy2003**
resolves #17818

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Andy2003** [comment]
Do not close. Still waiting for review.

**Comment by freben** [comment]
I disagree with this fix.

I'd say that explicit manual registration of an individual file (either via Create on the Backstage page, or via scaffolder actions) is a very strong signal that we now claimed "ownership" of this entity and we absolutely do not want anybody else to be able to mess with it.

With your change, an unsuspecting admin user might register a very core piece of infrastructure or whatnot believing that their action is permanent, and then some malicious (or unwitting) actor manages to stampede over that registration by just throwing a yaml file anywhere that is subject to discovery, overwriting that same entity ref, without any warnings or notifications to anyone that it's been attempted.

It's almost to the point that I'm not sure what a good fix would even be. If you mix the world of registration and discovery, you are bound to get collisions. I'd argue that the registrations should always win - they are the primary mode of operation and the most intentful one.

**Comment by Andy2003** [comment]
I seem to have misunderstood the purpose of the catalog:register scaffolder action. Our intention was to have the catalog updated immediately after creating a new catalog file, instead of waiting for the next discovery. This would enhance usability and allow for better testability through integration tests.

What would be the right way to have an entity visible in the backstage immediately after running a scaffolder?

**Comment by freben** [comment]
`catalog:register` adds a singular URL (into the new repo you just created) into the `locations` table, which in turn gets picked up instantly by an entity provider which creates a corresponding `kind: Location` entity out of it. Some time later, when that location gets processed, the URL it actually pointed to is read and turned into the final entities that were in that YAML file.

This is not perfectly instantaneous; it's a kind of asynchronous process behind the scenes.

This way of getting entities into the catalog is also completely separate from the "competing" process of instead using a discovery provider (they are two different provider implementations that don't overlap in any way with each other).

If I understand things correctly you are already using discovery and would like to continue using discovery, is that correct? If so, what you would need is some way of signalling to that provider that there's new data for it to discover, so that it runs sooner than its next scheduled interval. Some providers [implement event listening](https://github.com/backstage/backstage/blob/02f06907a68660be914bed3fb1900bb0d3bd17d1/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts#L280) such that they can react to webhooks of files getting created in the VCS. That's the ideal path forward, but the events system is still fairly young and not all providers implement support for it.

**Comment by Andy2003** [comment]
> If I understand things correctly you are already using discovery and would like to continue using discovery, is that correct?

Yes we use the `GitlabDiscoveryEntityProvider`

> If so, what you would need is some way of signalling to that provider that there's new data for it to discover, so that it runs sooner than its next scheduled interval. Some providers [implement event listening](https://github.com/backstage/backstage/blob/02f06907a68660be914bed3fb1900bb0d3bd17d1/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts#L280) such that they can react to webhooks of files getting created in the VCS. That's the ideal path forward, but the events system is still fairly young and not all providers implement support for it.

Ok this means that the VCS is required to support webhooks for the relevant events AND that every backstage instance is registered for these webhooks (making development much harder in terms of `localhost`)

What do you think about a mechanism, to trigger each EntityProvider via a new scaffolder action (e.g. `catalog:promote`). This will:

1. iterate through each known `EntityProvider`
2. ask this provider if it can handle the promoted URL
3. if so the provider starts discovery for the new URL

So we need a new interface, which can be implemented by the EntityProviders which support promotion of newly created catalog descriptors. Since each EntityProviders will know how to handle an URL and so can trigger the relevant discovery.

**Comment by freben** [comment]
It'd be a new mechanism and one that'll take a fair bit of consideration.

First, messages need to reach the consumers somehow. Remember also that the consumers are distributed. We could invent an HTTP endpoint in the catalog service itself that then fans it out to all of the entity providers it knows of. But that is a fairly tight coupling and a narrow interface. I'd prefer if we could instead make it so that this relies on the event bus, just a new message.

Second, the semantics of the message sent needs to be settled. It may seem simple but there are different sets of parameters that make sense for different sets of providers. How do you notify the LDAP provider and the GitLab provider uniformly, as well as any complex provider out there that we don't even know what it looks like because it's closed source? It'll fairly likely turn out to be provider specific for better or worse.

Third, remember that these are distributed, asynchronous workers. They often run on horizontally scaled nodes across datacenters. If host A in the US receives the message and does a small delta update, while host B in Asia is doing the full scan and then issues a full update, B will destroy the result that A posted.

It's tricky. We highly value discussion like this and want to find great cohesive solutions for sure, so don't be too discouraged. But it may need to start in the form of some RFC and then notifying the catalog SIG about it and seeing where it goes.

**Comment by Andy2003** [comment]
@freben please can you add / notifying the catalog SIG to / about #18160

**Comment by Andy2003** [comment]
As pointed out by @freben, this PR does not solve the underlying problem. It would only deactivate the warning and thus cause even more problems due to entity conflicts. A potential solution to my problem is defined in #18160, so I close this PR now.

**Pull request closed without merging**
