### PR TITLE
fixed: Expose a configuration option for the oidc scope

### PR DESCRIPTION
**Pull request by bleathem**
## Hey, I just made a Pull Request!

In release 0.3.0, the default oidc scope was removed.  The changelog includes sample code to set the scope using a factory, but this is cumbersome.  

This PR introduces a app-config parameter that can be used to set the scope.  The new config is optional, so this change is backwards compatible.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4635-bd84qq9bqct9g6d2uun10ryimtzhtfqy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/603417eb65f817c715f71d37

**Review by Rugvip — APPROVED** [review]
Yep, makes sense to add this for now, but as mentioned elsewhere we're looking to move some of the customization and creation of auth providers away from config. Direction we're headed can be seen here: https://github.com/backstage/backstage/pull/4532

Idea for oidc and oauth is to remove the default providers and instantiate more deliberate providers for a specific IdP. For example you might create an `acmecorp` auth provider using the OIDC provider implementation, and in addition setting default scopes to `'openid email'`.

```ts
// when instantiating the auth backend plugin
createRouter({
  providers: {
    acmecorp: createOidcProvider({
      defaultScopes: ['openid', 'email'],
      // ...
    })
  }
})
```

**Review by Rugvip — COMMENTED** [review]
... oh and needs a changeset for this to be released 😅

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4635-bd84qq9bqct9g6d2uun10ryimtzhtfqy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/603417eb65f817c715f71d37

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4635-bd84qq9bqct9g6d2uun10ryimtzhtfqy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/603417eb65f817c715f71d37

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4635-bd84qq9bqct9g6d2uun10ryimtzhtfqy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/603417eb65f817c715f71d37

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4635-bd84qq9bqct9g6d2uun10ryimtzhtfqy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/603417eb65f817c715f71d37

**Review by freben — APPROVED** [review]
Yep!

**Pull request merged**
