### PR TITLE
Fix: Added ARIA Attributes to SearchModal Component

### PR DESCRIPTION
**Pull request by JeevaRamanathan**
## Hey, I just made a Pull Request!

Added aria-label attribute to DialogTitle element and set aria-modal attribute to true for improved accessibility in the search modal and added a change set.
Closes: https://github.com/backstage/backstage/issues/22906

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by JeevaRamanathan** [comment]
Hi [camilaibs](https://github.com/camilaibs), can you please review this PR

**Review by tikabom — APPROVED** [review]

**Comment by JeevaRamanathan** [comment]
Hi @tikabom is this required any further approval to be merged?

**Comment by awanlin** [comment]
Hi @JeevaRamanathan you CI is failing right now, interestingly it's on the Accessibility stage. Can you take a look, please?

https://github.com/backstage/backstage/actions/runs/8619084805/job/24556906405?pr=24133

**Comment by JeevaRamanathan** [comment]
Hi @awanlin, it's been fixed now

**Pull request merged**
