### PR TITLE
documentation update: LdapOrgReaderProcessor is not registered by default

### PR DESCRIPTION
**Pull request by lalit774**
Update documentation for env.config and logger

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jhaals** [comment]
Thank you!

The commit needs a DCO signoff. You can amend the last commit with `git commit --amend --no-edit --signoff` and then `git push --force` to update the branch.

**Comment by lalit774** [comment]
@jhaals 

it seems like, i don't have access to push. is the any process to get the access.

image

**Comment by freben** [comment]
No contributor has push access directly to the repo - you want to push to your fork instead.

**Comment by lalit774** [comment]
Thank you @freben. I committed successfuly.

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
Thank you!

**Comment by benjdlambert** [comment]
Did you mean to merge this @jhaals? 😊

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
