### PR TITLE
Bumped esbuild version from 0.6.3 to 0.6.9 to support win32

### PR DESCRIPTION
**Pull request by JohnShahawy**
## Hey, I just made a Pull Request!

Bumped esbuild version to 0.6.9 to support win32.

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Windows should already be supported in the current version afaik?

Why not bump to a more recent version?

**Comment by freben** [comment]
Note also that `package.json.hbs` in the create-app template has

```json
  "resolutions": {
    "esbuild": "0.6.3"
  },
```

**Comment by benjdlambert** [comment]
@JohnShahawy seems like the build is failing for this could you take a look?

**Comment by benjdlambert** [comment]
Closing this in favour of #2639 which supersedes this to a later version

**Pull request closed without merging**
