### PR TITLE
Set 001-notifications BEP to "implementable"

### PR DESCRIPTION
**Pull request by mareklibra**
Moving the `001-BEP` forward, almost all features set are already implemented.
We need to stabilize the API and refer future changes to separate BEPs.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by mareklibra** [comment]
I believe the `implementable` is a good state for now.

To reach `implemented`, we need to resolve/agree on the https://github.com/backstage/backstage/pull/25066.

If anyone see another blocker towards `implemented`, please feel free to list it here.

Cc @freben , @Rugvip

**Comment by drodil** [comment]
I think we should also implement the user specific settings for notifications as there are going to be multiple different processors available in the upcoming releases

**Comment by awanlin** [comment]
This is a more general comment around BEPs but we should have some sort of gate at this point that there must be documentation in place before we make this change. For initial stages using `README`s is fine but at this point having it on backstage.io/docs is a must.

Notes: there are docs for this in the PR to add this to create-app so my comment here isn't intended to block anything. 👍

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
@awanlin Documentation before even setting it to implement**able**? Implement**ed** I agree, but not probably for this status right?

**Pull request merged**
