### PR TITLE
docs: remove alpha from import in techdoc addons

### PR DESCRIPTION
**Pull request by kurtaking**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Thanks for the corrections @kurtaking 🚀

**Comment by kurtaking** [comment]
@awanlin, this appears to be in a stuck state.

**Comment by awanlin** [comment]
> @awanlin, this appears to be in a stuck state.

Sorry, I'm not sure what you mean? All the builds have passed and now we just need review from the @backstage/techdocs-maintainers

**Comment by kurtaking** [comment]
> now we just need review from the @backstage/techdocs-maintainers

I thought I'd see the team added under the Reviewers section.

**Comment by awanlin** [comment]
Oh, odd, you don't see them here? 
image

**Comment by kurtaking** [comment]
> Oh, odd, you don't see them here?

Interesting, this is what I see. 

image

**Comment by awanlin** [comment]
Hi @squid-ney, any chance you can give this a quick look? Just some helpful doc updates

**Comment by awanlin** [comment]
Hi @freben @Rugvip any chance you can merge this? Just some docs updates to remove the alpha import for TechDocs addons which have been out for a long time now.

**Review by johnphilip283 — APPROVED** [review]

**Comment by awanlin** [comment]
Many thanks @johnphilip283 🙏 🚀

**Pull request merged**
