### PR TITLE
inclusive terminology

### PR DESCRIPTION
**Pull request by Braundo**
## Hey, I just made a Pull Request!

Replaced some terms with inclusive terminology (VMware initiative).

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hi! This is a very nice initiative. Thank you. Let us know if we can help somehow. The CI output mentions needing to apply `prettier` formatting on files, maybe you have the ability to enable auto formatting in your editor for example.

**Comment by freben** [comment]
Regarding the Vale checks you see - complaining about valid words like "allowlisted" that Vale doesn't yet know of - you can just add those words to `.github/vale/Vocab/Backstage/accept.txt` as part of the pull request to silence the check.

**Comment by freben** [comment]
Oh and allow me to note that you'll want to add some text at the bottom of the changeset file, something short like "Tweaked wording to use inclusive terminology" is fine.

You also don't need to declare things in the changeset, whose changes are entirely within like comments that aren't public. As in, if it's just a word in a `//` comment somewhere, then that won't affect the built package at all, so it's fine to not "ship" that noop-change to npm. If you happen to have one too many in the changeset it's no huge deal though, so don't worry too much about it.

**Comment by freben** [comment]
Oh merging master "backwards" is notoriously hard to solve the DCO checks for. I'd recommend rewinding that commit and instead rebasing.

**Review by Braundo — COMMENTED** [review]
Signed-off-by: aaronbraundmeier@gmail.com <aaronbraundmeier@gmail.com>

**Pull request closed without merging**
