### PR TITLE
Architecture overview docs

### PR DESCRIPTION
**Pull request by dtuite**
[Direct link to the docs](https://github.com/RoadieHQ/backstage/blob/arch-docs/docs/overview/architecture-overview.md)

I see a number of people in Discord looking for a basic architecture overview, or trying to figure out what might be involved in getting Backstage running in their environment. I also spent some time trying to understand this by working through the docs and code.

I thought a document which gives a quick high-level overview might be useful.

This is pretty raw right now, and things like Auth are not started at all, but I wanted to get some early feedback before spending too much time on it.

Let me know if you think this is useful and I will finish it out. It also needs a technical review by an engineer on the core team.

https://github.com/spotify/backstage/issues/1645 and https://github.com/spotify/backstage/issues/1169 are related.

### CODE REVIEW

**Review by stefanalund — COMMENTED** [review]
😍

Could you please also link up these docs to the /mkdocs.yml and /docs/README.md?

**Comment by dtuite** [comment]
Does anyone else have any thoughts? Are there any glaring mistakes?

**Review by stefanalund — APPROVED** [review]
I’ve already seen people being helped by it. I’m happy to ship any improvements to docs right now 😳😜

**Comment by dtuite** [comment]
All yours @stefanalund

**Review by stefanalund — APPROVED** [review]

**Pull request merged**
