### PR TITLE
Add Git actions to Plugins Marketplace

### PR DESCRIPTION
**Pull request by arhill05**
Signed-off-by: Drew Hill <me@andrewhill.io>

## Hey, I just made a Pull Request!

This adds a Git actions plugin to the Plugin marketplace. The plugin allows for easily running git CLI commands from a scaffolder template.

A note about the usage of the Git logo: their [trademark policy](https://git-scm.com/about/trademark) states that it can be used in this manner, but I can find a different logo if you interpret it differently.

Thanks!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets)) (N/A)
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes) (N/A)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Bit torn on this tbh, actions that are able to execute arbitrary commands is something we discourage due to security concerns. Do you think it would make sense to expose a more narrow set of git actions and perhaps also using a library to call out to git?

**Comment by arhill05** [comment]
Thanks for taking a look!

I could get on board with exposing a more narrow set of git actions, but I'm not sure how using a library to call git would address any security concerns. Both my implemetation and something like [simple-git](https://www.npmjs.com/package/simple-git) end up calling the git executable that is installed on the host machine, which means the only capabilities it would have are what is installed by the integrator, right?

I don't think this has any more security implications than something like the [http-request utility plugin](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/scaffolder-actions/scaffolder-backend-module-http-request/README.md), but I could be wrong :D

**Review by jhaals — APPROVED** [review]
Let's git this merged.

**Comment by suuus** [comment]
Hey @arhill05, congrats on your first merged PR 🎉 Nice work GITting this in  👍 Please let me know if we can be helpful in any way.

**Pull request merged**
