### PR TITLE
chore(scaffolder): Update loading/error messaging and remove unused deps

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

* Removes two unused dependencies
* Updates the loading/error messaging.  When your database was down, it was displaying that you had no templates and error.
* Now it will show the processing bar only while it loads, and if the database is down then only show the error warning.
* For either zero templates in your database, or none matching the filter, shows the same message.
* Removes linkage of "here" and replaces it with active wording.

image

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4606-hhprjfkshu4e7ybb9hworsdnbxndje1l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60300f4b65f817618cf50d08

**Comment by adamdmharvey** [comment]
Ah.... looks like a failure for one of the deps I removed:

> [Check Failed] package.json is missing field dependencies[@material-ui/lab], set to "4.0.0-alpha.45"?

Is this some sort of global requirement we're enforcing to always have lab available to all plugins?  Happy to put it back.

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4606-hhprjfkshu4e7ybb9hworsdnbxndje1l.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60300f4b65f817618cf50d08

**Review by freben — APPROVED** [review]
Awesome! I guess the lab stuff was actually in use somehow...

**Pull request merged**
