### PR TITLE
add refresh action to TemplateCard

### PR DESCRIPTION
**Pull request by kissmikijr**
Signed-off-by: Kiss Miklos <miklos@roadie.io>

## Hey, I just made a Pull Request!
Adds a refresh entity button to the TemplateCard to make sure you are using the latest template before you run it.
| Before | After |
|-------|------|
| image| image|

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Is this not possible through the entity page route for the template itself? I wondered if it's worth adding this to the default component or we just let people pass in their own `TemplateCard` which we can do already. It's a little unfortunate to have to duplicate the functionality of the `EntityPages` across the `scaffolder` too.

**Comment by kissmikijr** [comment]
Oh it is possible for sure, however I think it is not really good user experience that if I want to refresh my template first I'll need to go the template entity page, then refresh and after come back to the scaffolder page and run my template. 
During development when I'm working on a template I just use a github repo where I edit my templats and when I want to try it out I always need to do the dance to entitypage -> refresh -> scaffolder page -> template -> run. I think it would be nice to be able to schedule a refresh directly from the scaffolder page. Not sure if this is the correct place.

**Comment by kissmikijr** [comment]
Alright, I can accpet it ! :) I didn't know I can use my own `TemplateCard`, that pretty much solves it for my usecase. I'll close this one.

**Comment by benjdlambert** [comment]
Thanks @kissmikijr! Yep, you should be able to pass it into the `Router` and it will use the `TemplateCard` that you provide :pray:

**Pull request closed without merging**
