### PR TITLE
Upload test coverage to codecov

### PR DESCRIPTION
**Pull request by OrkoHunter**
Add CI task to upload test coverage to codecov.

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@Rugvip Can I ask a question?

When the CI runs `yarn lerna -- run test -- --coverage` and asks codecov cli to find the coverage reports, it can not find it.
But when it runs `yarn test:all`, all the coverage reports are found.

To me it looks like, our CI workflow can be updated with simpler commands (it will solve my problem of creating an extra `yarn test:all` task.
`yarn lerna -- run test --since origin/master -- --coverage` -> `yarn test`
`yarn lerna -- run test -- --coverage` -> `yarn test:all`

What do you think?

**Comment by Rugvip** [comment]
@OrkoHunter opted for using more lower level commands for setting up the workflows, keeping `yarn test` etc more dedicated for user interaction.

Regarding the PR, thinking we want to use https://github.com/codecov/codecov-action?

**Comment by OrkoHunter** [comment]
@Rugvip Reverted to lower level command. Makes sense to me. I checked and the CLI is working.
I wouldn't go for the codecov action for the similar reasons, it adds complexity. Plus we don't need any of the flags (as of now).

**Comment by OrkoHunter** [comment]
The comment will be more meaningful once there is a coverage report for the master branch. 😄

**Review by stefanalund — APPROVED** [review]
Nice!

**Pull request merged**
