### PR TITLE
techdocs: modify documentation header

### LINKED ISSUE #1764: TechDocs: Documentation Header
The header for documentation currently use the standard "home" color. 
Screen Shot 2020-07-28 at 4 30 10 PM

Screen Shot 2020-07-28 at 4 33 21 PM

We would like to change this to a specific color to use for documentation. 
Screen Shot 2020-07-28 at 4 32 33 PM

* Add new gradient to the [page theme provider](https://github.com/spotify/backstage/blob/e2ff11f77716d94e8cbf5b421a7b9ba09b07a5a0/packages/core/src/layout/Page/PageThemeProvider.ts) from [Figma sketch](https://www.figma.com/file/JE7l5zas8NEHv9VgPzOSeS/Backstage-Design-System-Community?node-id=2%3A396).
* Use new gradient for [documentation](https://github.com/spotify/backstage/blob/e2ff11f77716d94e8cbf5b421a7b9ba09b07a5a0/packages/core/src/layout/Page/PageThemeProvider.ts#L74).
* Use the page component with the new page theme type in [TechDocsPageWrapper](https://github.com/spotify/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsPageWrapper.tsx#L33). 
* Add new documentation header example to [Storybook](http://storybook.backstage.io/?path=/story/header--home). in [Header.stories.tsx](https://github.com/spotify/backstage/blob/master/packages/core/src/layout/Header/Header.stories.tsx)

### PR DESCRIPTION
**Pull request by twishasaraiya**
### Description

Resolves #1764 

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Prettier run on changed files

Screenshot from 2020-07-30 14-38-03
Screenshot from 2020-07-30 14-38-09

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thanks, looks good! 👍

**Comment by hooloovooo** [comment]
Thank you @twishasaraiya !

**Comment by emmaindal** [comment]
Have been on vacation, just took a look, it looks GREAT. Thank you so much @twishasaraiya 😄

**Comment by twishasaraiya** [comment]
Thanks @emmaindal and @hooloovooo 
PS: Backstage is amazing :100: looking forward to contributing more!! :smile:

**Pull request merged**
