### PR TITLE
Map username to azure user id for plugin msgraph

### PR DESCRIPTION
**Pull request by wangzheng422**
## Hey, I just made a Pull Request!

Original, plugin msgraph will import azure user data by using mail as key, but azure/microsoft sso login will use user id as key, thus the login user can not link to imported user correctly. By changing to using user id as key, azure sso will work smoothly with azure org data import.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @wangzheng422, there's several unrelated changes, can you please take a look?

This code has been like this for more than a year, it would be great to better understand why it isn't working for you before we make changes? Given that, we should probably add some tests as well (they are currently failing so you'll be updating them anyway).

@afscrome would be good to get your eye on this when you have the chance, please.

**Comment by afscrome** [comment]
HI @wangzheng422 could you elaborate a bit more on why you're making this change and what you're trying to achieve?

Changing how the default entity name is generated is a significant breaking change I'd be loathed to do without a very strong reason. 
1.Changing the entity name may break any relationships with other or other custom code other users have.  
2. This will change usernames from being friendly names.  So anytime anyone needs to provide a relationship of an entity to a user (e.g. `spec: { owner: 22b8a5f3-617a-4f10-a890-439d197776e8 }` will become `spec: { owner: john.smith }`.  Having to look up these guids is not particularly user friendly.

**Comment by wangzheng422** [comment]
What I try to fix, is when user login through azure sso, in the setting view, the 'user entity' will point to a link using guid. When user click the link, it will report 'entity not found', which is normal because azure org import user entity using email as username.

I agree this is breaking change, but to resolve this, some part of the system needs to be change, [maybe the azure sso part, needs to use azure email as username](https://github.com/janus-idp/backstage-showcase/blob/main/packages/backend/src/modules/authProvidersModule.ts#L225). 

Comparing to change the core auth login logic, I think changing the msgraph is related a small change.

**Comment by afscrome** [comment]
Hi @wangzheng422, in the example you provide, you are using a custom sign in resolver, not the built in one
https://github.com/janus-idp/backstage-showcase/blob/f9d19266f294b69149d75206a72e1ea366e78086/packages/backend/src/modules/authProvidersModule.ts#L227-L233

Sign in resolvers can look up users by any property on the entity, you do not have to change the entity name to match your chosen authentication scheme.  For example to look up a user by the Microsoft Graph object id, you can do so by providing some custom providers - https://backstage.io/docs/integrations/azure/org/#customizing-transformation

```ts
  return ctx.signInWithCatalogUser({
    annotations: {
      'graph.microsoft.com/user-id': id,
    },
  });
```

The "entity not found" behavior is an expected design of the custom sign in resolver you linked to - when it doesn't find a match in the catalogue, it falls back to a fake entity (for which not found is totally correct)
https://github.com/janus-idp/backstage-showcase/blob/f9d19266f294b69149d75206a72e1ea366e78086/packages/backend/src/modules/authProvidersModule.ts#L227-L233



If you still want to change the entity name for your specific backstage instance to be an id rather than a friendly name, you may be able to do so with a custom user transformer on the Microsoft Graph Module - https://backstage.io/docs/integrations/azure/org/#customizing-transformation .  Although I would strongly advise against this as the entity name often gets shown in the UI, so it's far preferable to have something human readable, than a meaningless guid.

**Review by Rugvip — CHANGES_REQUESTED** [review]
Please use the annotation with the ID to look up users on sign-in instead. User names should be human readable, a UUID is not a good representation of a user in the UI.

**Pull request closed without merging**
