### PR TITLE
Remove explicit alg check for user tokens in verifyToken

### PR DESCRIPTION
**Pull request by freben**
Background: https://discord.com/channels/687207715902193673/687235481154617364/1232688816737878067

As long as the auth backend has provably issued the token according to the JWKS, there's no reason for there to be any hard coded `alg` claim checks in the receiving end. That just adds friction when evolving the set of possible algorithms in the future.

### CODE REVIEW

**Review by Rugvip — CHANGES_REQUESTED** [review]
:+1:, could we add a test to make sure some bad algs aren't supported? In particular `none` :sweat_smile:

**Comment by freben** [comment]
`JOSENotSupported: alg none is not supported either by JOSE or your javascript runtime`

Hm it refuses to even make a token for that. jwt.io isn't helpful either. Not sure what to do about testing this :)

**Comment by freben** [comment]
Never mind, made the token by hand

**Review by Rugvip — APPROVED** [review]
:shipit:

**Pull request merged**
