### PR TITLE
Fixing truncate issue in blog post

### PR DESCRIPTION
**Pull request by AmbrishRamachandiran**
Fixing truncate issue in blog post
https://github.com/backstage/backstage/issues/23891

### CODE REVIEW

**Review by freben — APPROVED** [review]
I mean let's try it at least?

**Review by vinzscam — CHANGES_REQUESTED** [review]
but this won’t provide a fix for future content. I think the issue was proposing to fix the docusaurus config

**Comment by tico88612** [comment]
@vinzscam I think you're right. #23901

**Comment by npiyush97** [comment]
i think meant this ?
```
        blog: {
          path: 'blog',
          truncateMarker: /<!--\s*truncate\s*-->|\{\/\*\s*truncate\s*\*\/\}/,
        },
```
https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-blog#truncateMarker

**Review by awanlin — COMMENTED** [review]
Hi @AmbrishRamachandiran, thanks for taking a try at this. Unfortunately I think the solution in https://github.com/backstage/backstage/pull/23901 is the better path as we want to be able to use MDX for the blog and potentially other places as well in the future.

**Pull request closed without merging**
