### PR TITLE
catalog-backend: Refuse to remove the bootstrap location

### PR DESCRIPTION
**Pull request by freben**
Partly addresses #3398

This is a backend-only change. We could be helpful and make frontend changes as well, but this will do as an initial fix to avoid breaking customers' installations.

### CODE REVIEW

**Review by jhaals — APPROVED** [review]
LGTM 👍

**Review by Rugvip — APPROVED** [review]
:shipit:

**Comment by joscha** [comment]
\o/ @freben how do I know which version of `@backstage/plugin-catalog-backend` this made it (will make it?) into? Cheers! //cc @uri-canva

**Comment by adamdmharvey** [comment]
@joscha Each time a PR is merged, it gets added to pending changes for the next full release which occurs Thursday.  But you can see the pending CHANGELOG here:
https://github.com/backstage/backstage/pull/4084
(just look for an open PR with "Version Packages" in the title)

So for now, there's a `nightly` tag you can pull which will include the latest merged code, before it hits an "official" release. Once that Version Packages PR is merged, the new `@backstage/plugin-catalog-backend@0.5.4` will be published.

https://www.npmjs.com/package/@backstage/plugin-catalog-backend

Hope this helps!

**Comment by joscha** [comment]
It does, thank you!

**Pull request merged**
