### PR TITLE
Scalprum experimental implementation

### PR DESCRIPTION
**Pull request by Hyperkid123**
Continues #20102 

### Why

Based on the conversations we had, I am leaving a minimal build configuration and application sample of dynamic frontend plugins using Webpack module federation and Scalprum (the OpenShift package is part of the Scalprum project).

Dynamically loaded plugins will allow parts of the Backstage instances to be updated without having to rebuild and redeploy the shell application. Plugins can be developed independently and have independent release schedules.

In this example, I've rebuilt the tech radar alpha plugin and loaded it via the `loadFeatures` callback. There are no changes in the tech radar plugin code.

### How to run
1. go to `plugins/dynamic-frontend-plugin-sample` dir
2. run `yarn build` to create the dynamic output (located in `plugins/dynamic-frontend-plugin-sample/dist-scalprum`)
3. run a simple dev server to expose the build assets `npx http-server ./dist-scalprum/ -p 8004 --cors=* --cache=-1`
4. start the app-next package with `yarn start`
5. in the browser, click the `Tech radar` link or go directly to `http://localhost:3000/tech-radar`

You should see this page:

screenshot-localhost_3000-2023 10 17-09_57_56

The UI in the content section has been loaded dynamically at runtime, It is not bundled into the actual `app-next` output.

### Things to figure out
- the eager module sharing config should be removed, but this seem to be some issues related specifically to the project Webpack config and how it is wired
-  there is a bug with styling overrides, I am probably missing some module sharing config for the MUI styles (the brand image loses its margin on this page)

### CODE REVIEW

**Comment by Hyperkid123** [comment]
I know there are a lot of commits, but once we have something acceptable I'll clean it up.

**Comment by Hyperkid123** [comment]
@Rugvip I've moved forwards and addressed some of your comments. Mainly removing the requirement of the ScalprumProvider and also removing the requirement of explicit scalprum configuration in package.json (https://github.com/backstage/backstage/pull/20642/commits/a2579f7eeb141de45ded6490e0d747b7f10e3b26).

The issue with styling (missing margin in the menu) is unfortunately something that we can fix only by sharing MUI modules in the shared scope. The problem is rooted in the fact that it uses JSS and the components (in this case Typography) are initialized multiple times. Once from the "shell" app and once from the plugin. When the plugin is initialized its injected style tag overrides the shell app. I am looking at the conflicts right now. Hopefully, there will be a nice and simple solution.

**Comment by Rugvip** [comment]
Marked this as ready so that it gets on our radar, I think that was the intention anyway 😅

**Comment by freben** [comment]
@Hyperkid123 I unstaled this but the build was red (needs API reports at least) and there are conflicts now. Probably needs a rebase and some fixes.

**Pull request closed without merging**
