### PR TITLE
chore(catalog): remove deprecated catalog-backend-module-bitbucket plugin

### PR DESCRIPTION
**Pull request by pjungermann**
The package `@backstage/plugin-catalog-backend-module-bitbucket` was replaced by

- `@backstage/plugin-catalog-backend-module-bitbucket-cloud`
- `@backstage/plugin-catalog-backend-module-bitbucket-server`

in April 2022.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by pjungermann** [comment]
Not sure whether there is any specific procedure to follow for removing packages/plugins.

**Review by tudi2d — COMMENTED** [review]
Thanks for creating this PR - looks valid to me. The only previous case of plugin removal / deprecation I know of was the PagerDuty plugin: https://github.com/backstage/backstage/pull/21436. There the plugin was only marked as deprecated with instructions on how to use the new version (which already is the case here). Do we need further migration guidance for people still depending on this? Otherwise it should not be a problem to remove it.

**Comment by pjungermann** [comment]
@tudi2d I don't think we need more. However, I'm open to suggestions. :-)

**Comment by benjdlambert** [comment]
@pjungermann can you rebase this? Github won't let me merge until the merge conflicts are fixed, although I can't see them in this PR yet.

**Comment by pjungermann** [comment]
sure, on it!

**Comment by pjungermann** [comment]
@benjdlambert ready, you can have a look again

**Review by benjdlambert — APPROVED** [review]
Nice :tada: thanks for this!

**Pull request merged**
