### PR TITLE
add @backstage/eslint-plugin

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Broke this out of #15816 as it was getting a bit out of hand.

This now adds 3 new rules:

| Rule                                                                                    | Description                                                                                                              |
| --------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------ |
| [@backstage/no-forbidden-package-imports](https://github.com/backstage/backstage/blob/rugvip/rules/packages/eslint-plugin/docs/rules/no-forbidden-package-imports.md) | Disallow internal monorepo imports from package subpaths that are not exported.                                          |
| [@backstage/no-relative-monorepo-imports](https://github.com/backstage/backstage/blob/rugvip/rules/packages/eslint-plugin/docs/rules/no-relative-monorepo-imports.md) | Forbid relative imports that reach outside of the package in a monorepo.                                                 |
| [@backstage/no-undeclared-imports](https://github.com/backstage/backstage/blob/rugvip/rules/packages/eslint-plugin/docs/rules/no-undeclared-imports.md)               | Forbid imports of external packages that have not been declared in the appropriate dependencies field in `package.json`. |

All in all it adds support for the `"exports"` field in package.json, bakes in the relative `../*/src` check, and replaces the `monorepo` plugin with our own that works regardless of cwd, fixing #16074.

Custom rules also let us provide more accurate error messages, for example:

```plain
lodash must be declared in dependencies of packages/app/package.json, run 'yarn --cwd packages/app add lodash' from the project root.
```

The replacement of the `import/no-extraneous-dependencies` rule also comes with a decent speed boost, as it was by far the slowest rule.

before:

```plain
yarn lint:all  101.85s user 9.80s system 639% cpu 17.463 total
yarn lint:all  101.67s user 9.93s system 638% cpu 17.491 total
yarn lint:all  100.20s user 9.98s system 644% cpu 17.089 total

Rule                              | Time (ms) | Relative
:---------------------------------|----------:|--------:
import/no-extraneous-dependencies |  1320.333 |    21.0%
@typescript-eslint/no-redeclare   |   798.291 |    12.7%
monorepo/no-relative-import       |   458.716 |     7.3%
notice/notice                     |   318.667 |     5.1%
react/no-multi-comp               |   184.161 |     2.9%
jest/expect-expect                |   181.801 |     2.9%
monorepo/no-internal-import       |   159.004 |     2.5%
react/sort-comp                   |   126.132 |     2.0%
jest/no-standalone-expect         |   118.181 |     1.9%
jest/no-conditional-expect        |   115.060 |     1.8%
```

after:

```plain
yarn lint:all  98.91s user 7.84s system 622% cpu 17.152 total
yarn lint:all  92.07s user 8.19s system 617% cpu 16.229 total
yarn lint:all  97.77s user 7.90s system 634% cpu 16.664 total

Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
@typescript-eslint/no-redeclare         |   981.920 |    17.7%
notice/notice                           |   458.716 |     8.3%
@backstage/no-undeclared-imports        |   273.522 |     4.9%
@backstage/no-relative-monorepo-imports |   264.021 |     4.8%
jest/expect-expect                      |   230.718 |     4.2%
react/no-multi-comp                     |   190.179 |     3.4%
jest/no-standalone-expect               |   134.748 |     2.4%
no-restricted-globals                   |   133.390 |     2.4%
jest/no-conditional-expect              |   115.549 |     2.1%
react/sort-comp                         |   113.047 |     2.0%
```

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]

**Comment by torsami77** [comment]
Hi @Rugvip, job well done, I'm having issue with `Disallow internal monorepo imports from package subpaths that are not exported.` since this update despite exporting package from internal monorepo. Please can you provide a code snippet example or reference

**Comment by Rugvip** [comment]
@torsami77 thanks! Could you show an example where you get that error? The rule is there to forbid importing of subpaths like `@internal/my-plugin/components` where `/components` is the subpath that will only be allowed if it's listed in the package.json exports field.

**Comment by Rugvip** [comment]
@torsami77 that's all over here https://backstage.io/docs/local-dev/cli-build-system#subpath-exports

**Comment by torsami77** [comment]
okay thanks, let me take a look

**Comment by torsami77** [comment]
@Rugvip , thank you for your help, the reference you provided above helped me resolve the lint error, but now I'm trying to run the app and I'm getting similar issues as on this thread 

https://github.com/backstage/backstage/issues/13982

**Pull request merged**
