### PR TITLE
bep(0008): adjustments following initial review

### PR DESCRIPTION
**Pull request by aramissennyeydd**
## Hey, I just made a Pull Request!

Following up on some comments in #23692. 

1. Renamed `Administrator` to `Operator`.
2. Renamed `Integrator` to `Builder`.
3. Added myself as an owner (and anyone else if they're interested 👀 )
4. Changed project area to documentation (hoping we can get #24657 in 🤞)
5. Moving towards Developer Portal docs as the main entry point. Adjusted table of contents and content in the doc in line with this.

cc: @dwelsch-esi @Rugvip 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Rugvip** [comment]
Ah, I'll pick this one up!

**Comment by aramissennyeydd** [comment]
@awanlin @Parsifal-M (do we have a GH group yet for documentation?) Curious your thoughts here?

**Review by awanlin — APPROVED** [review]
This looks good to me, sorry I did not look at this till now. 👍

**Comment by aramissennyeydd** [comment]
@Rugvip When you get a chance 🙏 , discussed this in the Docs SIG - we'd like to move this to implementable and I think this is the last piece.

**Comment by aramissennyeydd** [comment]
gentle ping @Rugvip, this would be awesome to get in ASAP!

**Pull request merged**
