### PR TITLE
Adding StatusNeo as Commercial Partners on Community Page

### PR DESCRIPTION
**Pull request by NishkarshRaj**
## Hey, I just made a Pull Request!

Adding StatusNeo as the commercial partner for Backstage.io - We at StatusNeo have been part of the Backstage community since 2020 and have contributed multiple plugins and done over 130+ contributions to core Backstage.io project: https://statusneo.com/backstage/

Plugins contributed include New Relic Dashboard, Microsoft Outlook Calendar and GitHub StatusNeo Homepage widgets listed on the Backstage Plugins page.

We would love to be listed on this Community page to motivate ourselves further and also use it to promote ourselves as advocates of Backstage community. 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @NishkarshRaj, just curious but who are the members of StatusNeo that have been making these contributions? Would be great to know who they are and express thanks for their hard work, 130+ contributions is a massive accomplishment.

**Comment by NishkarshRaj** [comment]
@awanlin - thanks for asking..

Our friends @mufaddal7 @shvmbisht @Abhay-soni-developer lead the way for most of these contributions.

**Comment by NishkarshRaj** [comment]
@awanlin and @Rugvip - can you please review 🙏

**Review by Rugvip — APPROVED** [review]
Looks good, and thank you!

**Pull request merged**
