### PR TITLE
Making scaffolder template's title customizable

### PR DESCRIPTION
**Pull request by acierto**
## Hey, I just made a Pull Request!

As an engineer of software templates I would like to be able to customise the title of a template. 
Therefore we can add actionable items on the title panel. 
We see a value of having a feedback panel for certain group of templates, so that user reach a proper docs and channel of support.

Screenshot 2023-02-28 at 10 27 53
Screenshot 2023-02-28 at 10 28 02

The solution is implemented for both versions of software templates.
The code example how to achieve the result is added to a documentation, as it might be useful for others as well.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hi! Sorry for the slow response here.

I think we want to avoid making this change. It's always tricky to inject this type of customizability all over the place with "ad hoc" interfaces that hopefully fit each use case. Makes things hard to maintain and evolve.

Going forward, our goal is to instead break out this entire page as a composable thing. We want you to be able to put your own wrapper and header as regular JSX with the entire "body" of the page just placed inside - and a host of other possible customizations. We're not quite there yet but moving toward that model. This is for example [what the catalog page offers](https://backstage.io/docs/features/software-catalog/catalog-customization).

So for now, I suggest backtracking on this because we'll need to revert/redesign it some time fairly soon down the line anyway. Ping @benjdlambert here too.

**Comment by benjdlambert** [comment]
@acierto yep, I think overall we've realised that the need for customization in plugins has kind of outgrown the prop approach as it's just so much API surface to manage. We're looking at spinning up and issue to work out how we can solve these issues in a cleaner way with a dedicated API for replacing components in plugins so you can bring your own. Will try and get around to drafting up this issue today and keep you in the loop. I wonder if for now it makes sense to convert this PR into a `TemplateWizardPage` prop where you can provide you own page instead, similar to how we've done the `OngoingTaskPage` and have people copy the implementation for now. Feels a little nuclear, but it's at least going to save us adding props for everything in the short term.

**Comment by acierto** [comment]
> @acierto yep, I think overall we've realised that the need for customization in plugins has kind of outgrown the prop approach as it's just so much API surface to manage. We're looking at spinning up and issue to work out how we can solve these issues in a cleaner way with a dedicated API for replacing components in plugins so you can bring your own. Will try and get around to drafting up this issue today and keep you in the loop. I wonder if for now it makes sense to convert this PR into a `TemplateWizardPage` prop where you can provide you own page instead, similar to how we've done the `OngoingTaskPage` and have people copy the implementation for now. Feels a little nuclear, but it's at least going to save us adding props for everything in the short term.

@benjdlambert It could be a solution, but `TemplateWizardPage` has a reference to `routes`, but by some reasons (which i don't understand now) they are never exported out of plugins

**Comment by benjdlambert** [comment]
Yeah they should be exported on the `scaffolderPlugin.routes` object. We probably have a little bit of work to remove the `routeRef` duplication and we should be able to export them from there.

**Comment by benjdlambert** [comment]
@acierto I went ahead and did the `routeRefs` work too #16942

**Comment by benjdlambert** [comment]
Actually I guess now we can close this ticket in favour of @minkimcello's work right #16915?

**Comment by acierto** [comment]
> Actually I guess now we can close this ticket in favour of @minkimcello's work right #16915?

@benjdlambert Only if routers will be exposed, as basically it means that i have to copy paste full `TemplateWizardPage`

**Comment by benjdlambert** [comment]
@acierto not sure i'm following, what you do you mean `Routers`?

**Comment by acierto** [comment]
> @acierto not sure i'm following, what you do you mean `Routers`?

Oh I'm sorry. 

```
const rootRef = useRouteRef(nextRouteRef);
const taskRoute = useRouteRef(nextScaffolderTaskRouteRef);
const scaffolderApi = useApi(scaffolderApiRef);
```

They are all in file `routers.ts` but this file is visible only inside the plugin.

**Comment by benjdlambert** [comment]
Ah but since #16942 they don't exist as `next*` anymore. They're using the same `routeRefs` as the other plugin. So that you can only run one and once, and they're available on the plugin export.

`scaffolderPlugin.routes.x` should have all the `routeRefs` for you.

**Comment by acierto** [comment]
> Ah but since #16942 they don't exist as `next*` anymore. They're using the same `routeRefs` as the other plugin. So that you can only run one and once, and they're available on the plugin export.
> 
> `scaffolderPlugin.routes.x` should have all the `routeRefs` for you.

Cool, then yeah, we can close in favour of another PR.

**Pull request closed without merging**
