### PR TITLE
fix: use Material UI vs. MUI where relevant

### PR DESCRIPTION
**Pull request by oliviertassinari**
MUI is an organization. Same as https://github.com/algolia/docsearch/pull/1953

### CODE REVIEW

**Comment by oliviertassinari** [comment]
This should be ready now

**Review by awanlin — CHANGES_REQUESTED** [review]
Thanks for the contribution @oliviertassinari, I went though all the files and it looks good to me! 🚀 

You will need a changeset for `@backstage/plugin-ilert` seeing as there is an actual code change for that one

**Comment by oliviertassinari** [comment]
Ok, I have reverted this change. I don't know how to do these changeset, I would rather not know.

**Review by awanlin — APPROVED** [review]

**Comment by awanlin** [comment]
> > You will need a changeset for @backstage/plugin-ilert seeing as there is an actual code change for that one
> 
> Ok, I have reverted this change. I don't know how to do these changesets, I would rather skip it.

Sure that works too ;)

FYI - the build failures are not related to your changes so don't worry about them for now

**Review by benjdlambert — APPROVED** [review]
Thanks @oliviertassinari :tada:

Just added a changeset too for the packages that need it for republishing the jsdocs to the public types.

**Pull request merged**
