### PR TITLE
Implement EntityKindPicker for the catalog

### PR DESCRIPTION
**Pull request by Crevil**
This change implements the `EntityKindPicker` as discussed in https://github.com/backstage/backstage/issues/9616#issuecomment-1255149636.

It is much the same as the `CatalogKindHeader` but follows the picker models instead to make it more visible.

The selected filter is propagated between `CatalogKindHeader` and `EntityKindPicker` with an effect on the filters both places.

image

image

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — DISMISSED** [review]
Thanks for taking a look at this! Could you please make sure that new API reports are generated :)

**Review by freben — COMMENTED** [review]
Awesome stuff!

**Comment by Crevil** [comment]
Thank you @freben . I have updated per your suggestions. PTAL.

**Review by freben — APPROVED** [review]
Nice!

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻

**Pull request merged**
