### PR TITLE
chore(mui5): Migrate devtools plugin to Material UI 5

### PR DESCRIPTION
**Pull request by deejay1**
Relates to #7094

## Hey, I just made a Pull Request!

Migrate devtools plugin to mui v5

### Screenshots after change
Zrzut ekranu 2024-11-12 o 18 24 08
Zrzut ekranu 2024-11-12 o 18 23 57
Zrzut ekranu 2024-11-12 o 18 23 47

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — APPROVED** [review]

**Comment by sebalaini** [comment]
looks like you have the same error as I'm having in my PR https://github.com/backstage/backstage/pull/27572, you said I should fix the `peerDependencies` for `mui 5` but by looking at the code [here](packages/repo-tools/src/commands/peer-deps/peer-deps.ts) there is this const that I assume is the one responsible to make the CI failing:

```js
const peerDependencies = {
  '@types/react': '^16.13.1 || ^17.0.0 || ^18.0.0',
  react: '^16.13.1 || ^17.0.0 || ^18.0.0',
  'react-dom': '^16.13.1 || ^17.0.0 || ^18.0.0',
  'react-router-dom': '6.0.0-beta.0 || ^6.3.0',
};
```

**Comment by deejay1** [comment]
@sebalaini ok, I've mentioned the issue with react versions in the related ticket and will bring back 16 here again

**Comment by LegendSebastianoL** [comment]
> @sebalaini ok, I've mentioned the issue with react versions in the related ticket and will bring back 16 here again

hey @deejay1, I saw, I was subscribed to that issue :) I'll revert my PR tonight or later on during the day with my personal GH account.

Yesterday I was also exploring the removal of the `Theme` type, as the doc you pointed in my PR say:

> You can follow the [migration of the GraphiQL plugin](https://github.com/backstage/backstage/pull/17696) as an example of a plugin migration.

I saw that they don't use the `type` but tests still fails.
image

**Comment by awanlin** [comment]
Thanks for the contribution, as I already had a [PR open](https://github.com/backstage/backstage/pull/27420) for this I'm going to close this one. 👍

**Comment by deejay1** [comment]
@awanlin ahh, sorry I didn't notice it

**Pull request closed without merging**
