### PR TITLE
scaffolder: Fix issue with circular JSON whilst templating

### PR DESCRIPTION
**Pull request by benjdlambert**
- fix: don't passthrough all of task
- chore: added changeset

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by dagda1 — APPROVED** [review]
👍 

I'll approve, would a test be appropriate here?

**Comment by benjdlambert** [comment]
@dagda1, most probably but it's pretty tricky to test. The tests were already in place we were just spreading in too much. Might add a small one :)

**Comment by dagda1** [comment]
> @dagda1, most probably but it's pretty tricky to test. The tests were already in place we were just spreading in too much. Might add a small one :)

no point if it does not add anything or is potentially flakey

**Comment by heyLu** [comment]
Looks like this is actually already in `1.20.2`: https://github.com/backstage/backstage/releases/tag/v1.20.2

**Pull request merged**
