### PR TITLE
Add input to adjust time window for the newrelic-dashboard plugin and minor bug fix

### PR DESCRIPTION
**Pull request by jakecrews74**
In the New Relic Dashboard plugin I (and other members of my company) wanted the ability to customize the time window of data that is shown on the dashboard. To do this, I added another entity metadata field that will allow the user to specify the time window of data to be shown in the snapshot.

While doing this, I also found a bug where the default time window of the snapshot was ~43 weeks. It appears this is not the intended functionality as [shown here](https://github.com/backstage/backstage/commit/996120684fef8e888a8bda2b0600cc50cf5dfe1c).

If the user does not add the new annotation field, it will default to the original 30 day view.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hm! While I appreciate the end user need here, I am not sure that configuration like that best lives in the catalog files themselves. Imagine having tons of settings like this for all of the services you interact with, typing that all out and getting the syntax right, etc.

Might I suggest looking at making this frontend driven instead? If the time window was a dropdown selection on the frontend control instead, it could save that changed setting on a per-entity basis, and load them up again next time you visit that page. There's a [`storageApiRef` in the core plugin API](https://github.com/backstage/backstage/blob/4ef64446717b824dc63a182fe8fd46fc4dbfeacb/packages/core-plugin-api/api-report.md?plain=1#L690) that is meant to use for this kind of thing. Just select a distinct unique bucket name.

**Comment by jakecrews74** [comment]
Screenshot of changes. I add the select input as an action on the card header.
newrelicDashboardChanges

**Review by Rugvip — CHANGES_REQUESTED** [review]
Nice, thank you! 👍 

Just some change management stuff

**Review by Rugvip — APPROVED** [review]
Nice, thank you! :+1:

**Comment by mufaddal7** [comment]
@jakecrews74 Thanks for this, I had kept a static date and thought I would improve on it later.

**Pull request merged**
