### PR TITLE
[Scaffolder] Add custom validation for dependencies

### PR DESCRIPTION
**Pull request by tritri251214**
Signed-off-by: Minh Tri <tritri251214@gmail.com>

## Hey, I just made a Pull Request!

https://user-images.githubusercontent.com/32475934/182524756-f29f95b0-d76c-4657-ae34-c52022f656d8.mp4

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by tritri251214** [comment]
Related issue: [#12378](https://github.com/backstage/backstage/issues/12378)

**Comment by benjdlambert** [comment]
Thanks for this! :pray: I actually want to see if I can get this to work by using a similar method that is in #7868 as it makes this entire code block much nicer. Will try and get a PR together today, and if you wouldn't mind trying it out and we can do that instead?

**Comment by tritri251214** [comment]
hi @benjdlambert ,
Do you want me help about this issue?

**Comment by benjdlambert** [comment]
I didn't get chance yesterday, will try and get something up over the weekend.

**Comment by benjdlambert** [comment]
Closing this in favour of #13017 - thanks @tritri251214! :pray:

**Pull request closed without merging**
