### PR TITLE
[TechDocs] Fix large headings

### LINKED ISSUE #12891: Techdocs: Headings are displayed too large
## Expected Behavior

Headings in techdocs are not that large.

## Actual Behavior

With version 1.4.0 the headings in the techdocs are comically large (worked with 1.3.0)

## Steps to Reproduce

Open any Techdocs page and have a look at the headings

## Context

At this size the headlines distract from the content

## Your Environment

- Browser Information: Any Browser, tested on Firefox, Chrome and Microsoft Edge

```text
- Output of `yarn backstage-cli info`: 
- OS:   Windows_NT 10.0.19044 - win32/x64
node: v16.15.1
yarn: 1.22.19
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.4
  @backstage/backend-common                        0.14.1
  @backstage/backend-plugin-api                    0.1.0
  @backstage/backend-tasks                         0.3.3
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.0
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.4
  @backstage/core-components                       0.10.0
  @backstage/core-plugin-api                       1.0.4
  @backstage/dev-utils                             1.0.4
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.2
  @backstage/integration                           1.2.2
  @backstage/plugin-api-docs                       0.8.7
  @backstage/plugin-app-backend                    0.3.34
  @backstage/plugin-auth-backend                   0.15.0
  @backstage/plugin-auth-node                      0.2.3
  @backstage/plugin-azure-devops-common            0.2.4
  @backstage/plugin-azure-devops                   0.1.23
  @backstage/plugin-catalog-backend-module-azure   0.1.5
  @backstage/plugin-catalog-backend                1.3.0
  @backstage/plugin-catalog-common                 1.0.4
  @backstage/plugin-catalog-graph                  0.2.19
  @backstage/plugin-catalog-import                 0.8.10
  @backstage/plugin-catalog-node                   1.0.0
  @backstage/plugin-catalog-react                  1.1.2
  @backstage/plugin-catalog                        1.4.0
  @backstage/plugin-gcalendar                      0.3.3
  @backstage/plugin-github-actions                 0.5.7
  @backstage/plugin-home                           0.4.23
  @backstage/plugin-org                            0.5.7
  @backstage/plugin-permission-backend             0.5.9
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.3
  @backstage/plugin-permission-react               0.4.3
  @backstage/plugin-proxy-backend                  0.2.28
  @backstage/plugin-scaffolder-backend             1.4.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.4.0
  @backstage/plugin-search-backend-module-pg       0.3.5
  @backstage/plugin-search-backend-node            1.0.0
  @backstage/plugin-search-backend                 1.0.0
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.0
  @backstage/plugin-search                         1.0.0
  @backstage/plugin-stack-overflow                 0.1.3
  @backstage/plugin-tech-radar                     0.5.14
  @backstage/plugin-techdocs-backend               1.2.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.2
  @backstage/plugin-techdocs-node                  1.2.0
  @backstage/plugin-techdocs-react                 1.0.2
  @backstage/plugin-techdocs                       1.3.0
  @backstage/plugin-todo-backend                   0.1.31
  @backstage/plugin-todo                           0.2.9
  @backstage/plugin-user-settings                  0.4.6
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Fixed the large TechDocs headings and closes #12891 

Before:

Screen Shot 2022-08-10 at 10 11 40 AM

After:

Screen Shot 2022-08-10 at 10 12 07 AM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by emmaindal — COMMENTED** [review]
cc @camilaibs as you have more context around why this was put in place in the first place. I'm happy to roll back to this, to solve the problem, I'm just curious to know why this is needed. I understand the headings get larger in TechDocs than other headings in Backstage, but why is that the case?

**Comment by camilaibs** [comment]
> cc @camilaibs as you have more context around why this was put in place in the first place. I'm happy to roll back to this, to solve the problem, I'm just curious to know why this is needed. I understand the headings get larger in TechDocs than other headings in Backstage, but why is that the case?

It might be worth investigating if there are any in-between contexts changing theme values and making them different from others on TechDocs pages. If they use the same values defined [here](https://github.com/backstage/backstage/blob/master/packages/theme/src/baseTheme.ts), I would say try to decrease the font size in the default theme instead of here.

**Comment by awanlin** [comment]
@camilaibs I'll take a look at your suggestion, thanks

**Comment by awanlin** [comment]
OK, I played around with changing the value of `htmlFontSize` to 10 from 16 and this actually made all the text larger (odd?). I also tried setting the value of `htmlFontSize` to 24 from 16 this made everything smaller. The following results are without the fix in this PR

Results with `htmlFontSize` set to 10:

Screen Shot 2022-08-15 at 2 11 08 PM

Results with `htmlFontSize` set to 24:

Screen Shot 2022-08-15 at 2 11 44 PM

**Comment by awanlin** [comment]
@emmaindal and @camilaibs with the `1.5.0` release tomorrow it would be wonderful to see this get in, I'm happy to do more investigation to see if there's something better that can be done as a follow up to this

**Review by camilaibs — APPROVED** [review]

**Comment by camilaibs** [comment]
> @emmaindal and @camilaibs with the `1.5.0` release tomorrow it would be wonderful to see this get in, I'm happy to do more investigation to see if there's something better that can be done as a follow up to this

Sure, let's dive deeper in a separate pull request, thanks for helping us!

**Comment by awanlin** [comment]
Thanks @camilaibs and @iamEAP!

**Pull request merged**
