### PR TITLE
fix(cost-insights): Update instruction examples to fix links and rewording

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

On the sample cost-insights instruction page, fix the links to display using the Material-UI theme, one typo, and minor rewording.

| Before | After |
| --- | --- |
| image | image |

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by timbonicus — APPROVED** [review]
Great fixes, thank you! 🙇‍♂️

**Comment by adamdmharvey** [comment]
Looks like in future, Code Insights changesets should have a prefix, is that right @timbonicus ? otherwise, this PR has tagged core maintainers because of the changeset:

https://github.com/backstage/backstage/blob/84aa6f4a009b26989dadd8f21b3d5325340f4adf/.github/CODEOWNERS#L15

**Comment by timbonicus** [comment]
@adamdmharvey Right, bit of a manual workaround to not require `maintainers` approval just due to changesets. Ideally we wouldn't need to manually rename the file, maybe there's some better monorepo/workspaces way to do this?

**Comment by adamdmharvey** [comment]
PS: what's `silver-lining` mean?  name of your squad within Spotify, perhaps? or just you and a group of people who are also interested in cost insights are super optimistic 😁

**Review by freben — COMMENTED** [review]
@adamdmharvey Yep it's a Spotify team. Relevant choice of name!

Could you use the Backstage core Link component instead? At this moment all it does is render the mui link so it seems unnecessary, but for consistency it's nice - and as we add more things to the Link (click tracking, optional force-open in new tab when it's an external link, automatic addition of things like noopener and noreferrer, ...) it becomes even more relevant.

**Comment by adamdmharvey** [comment]
good call, @freben; thx!

**Review by freben — APPROVED** [review]

**Pull request merged**
