### PR TITLE
set PropsWithChildren as explicit type on components

### PR DESCRIPTION
**Pull request by RobotSail**
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

## Hey, I just made a Pull Request!

This PR aims to prime the codebase for upgrading to React 18 by setting `PropsWithChildren` as an explicit type for components.

Part of #12252
Part of #17414

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by RobotSail** [comment]
This PR is definitely incomplete since it's hard to find all of the props needed to be wrapped in `PropsWithChildren` without upgrading to React 18. I will need to port over the changes from #17414 into this PR.

**Comment by freben** [comment]
Nice. Would you say it's still a work in progress then? Should it even be marked as a draft?

Remember to make a complete changeset then, too!

**Review by camilaibs — APPROVED** [review]
LGTM on the discovery plugins side, thank you!

**Comment by awanlin** [comment]
Is there anything pending on this @RobotSail? Can it get reviewed? Sorry, we'd like to see this get in so doing some tracking

**Comment by freben** [comment]
Alright, rebased to fix the little conflict and will review

**Review by freben — APPROVED** [review]
Alright I made a minor fixup to the types, and think this is ready to go!

**Comment by awanlin** [comment]
Excited to see this merged in many thanks @RobotSail! 🚀

**Pull request merged**
