### PR TITLE
docs: Search arch diagram catalogue -> catalog

### PR DESCRIPTION
**Pull request by OrkoHunter**
🙈 
Even if both are correct, sticking to the plugin's real name.

### CODE REVIEW

**Review by emmaindal — APPROVED** [review]

**Comment by emmaindal** [comment]
Yes, agree, thank you @OrkoHunter

**Comment by adamdmharvey** [comment]
🥔 => 🥔 
🍅 => 🍅

**Comment by OrkoHunter** [comment]
> 🥔 => 🥔
> 🍅 => 🍅

I totally pronounced all these differently. 😂

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
cat

<3

**Comment by iamEAP** [comment]
😬  Whoops. Pardon my completely inconsistent use of regional English variants........

**Pull request merged**
