### PR TITLE
Update contribute docs

### PR DESCRIPTION
**Pull request by JeevaRamanathan**
## Hey, I just made a Pull Request!
Made changes in `docs/contribute`

#### :heavy_check_mark: Checklist

- [x] Added or updated documentation

### CODE REVIEW

**Review by camilaibs — COMMENTED** [review]
Hi @JeevaRamanathan, would you mind giving more context regarding the changes?

**Comment by JeevaRamanathan** [comment]
Hi @camilaibs, The double hyphens (--) were replaced with an em dash (—) to improve readability and clarity in the sentence.

**Comment by JeevaRamanathan** [comment]
Hi @camilaibs, The double hyphens (--) were replaced with an em dash (—), and added `,` after therefore to improve readability and clarity in the sentence. [docs/contribute](https://github.com/backstage/backstage/blob/master/docs/contribute/index.md)
image

**Review by camilaibs — APPROVED** [review]
Thank you 🙌🏻

**Pull request merged**
