### PR TITLE
scaffolder-backend: remove legacy sample-templates based on cookiecutter

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes https://github.com/backstage/backstage/issues/6415

Along with the introduction of `fetch:template` based templates, we moved out the sample software templates which are used in the example app over to https://github.com/backstage/software-templates for added visibility and collaboration with the community.

As planned in https://github.com/backstage/backstage/issues/6415, we decided to wait for some time before removing the cookiecutter based templates from the mono-repo. 1 month has passed, and it should be safe to remove these now.

**Once again, if you are using these templates in your Backstage app using direct URLs to github.com/backstage/backstage locations, you should copy over the templates inside your org and import from there.**

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
We should probably still have a changeset here I think, just explaining the migration path for the last time too. Even though they're not part of the shipped API and package, there was still a time that people were relying on the files that were under the `scaffolder-backend` `git` repo.

**Comment by freben** [comment]
We'll hold off a little bit on merging this. The new `fetch:template` action is fairly young and it's likely that there still exist some remote references around to these actual templates on github.

**Comment by mtlewis** [comment]
Another option we considered was updating the templates themselves with some extra text (either in a description somewhere or a new field) to warn users that they're going to be removed. That way any users that are pointing directly at them on GitHub will see a warning when they try to use them.

**Comment by OrkoHunter** [comment]
@backstage/maintainers How about we do this in two steps

- Introduce a warning in the templates containing a future date when the templates will no longer be available.
- Clean the templates on the particular date.

**Review by Rugvip — APPROVED** [review]
I think it's time to merj :shipit:

**Comment by Rugvip** [comment]
These are of course also sample templates, so while I could see that this change might ruin a demo, hopefully there's no production breakages out there.

If we want to be even more careful we change the descriptions to all these templates to include a `DO NOT USE - WILL BE REMOVED`

**Comment by benjdlambert** [comment]
Let's merge and notify of the upgrade path if anything comes up in Discord or Github. :)

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
