### PR TITLE
Export permission schemas

### PR DESCRIPTION
**Pull request by Joonpark13**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by mtlewis — APPROVED** [review]
Love it!

**Comment by freben** [comment]
Hi @Joonpark13! Remember to DCO sign all commits (see the comment above or build details below)

**Comment by freben** [comment]
A general question on this. How is it intended to be used by consumers?

It ties the contract to a certain version of zod, and of course also indeed to specifically the zod library. If it's only validation we're after for example, I was wondering if it could instead be hidden behind a more agnostic checker function or so.

In the new frontend system we invented a wrapping schema type for this very reason.

**Comment by Joonpark13** [comment]
> A general question on this. How is it intended to be used by consumers?

This is a fantastic point. It looks like the wrapping schema type you linked isn't quite ready for stable use yet - perhaps the best thing to do is wait until it is, and then utilize that type here to export a validator that is library-agnostic. Will close for now!

**Pull request closed without merging**
