### PR TITLE
Kubernetes plugin: Read cluster config from api

### LINKED ISSUE #3590: Kubernetes plugin is reading clusters config on the frontend
The [KubernetesContent.tsx](https://github.com/backstage/backstage/blob/master/plugins/kubernetes/src/components/KubernetesContent/KubernetesContent.tsx#L112) file, which is part of the frontend of the Kuberentes plugin, reads cluster config directly from the `app-config.yaml` file.

```
  const clusters: Config[] = configApi.getConfigArray('kubernetes.clusters');
```

This has at least two negative effects:

 1. It turns kubernetes config into a build time config. You have to set a static kubernetes config when building the frontend container. Changing the config later, perhaps to add or remove a cluster, requires rebuilding the container.
 2. It's insecure because the service account token is exposed to the browser.

Instead, I would expect that the cluster config is held by the Kubernetes backend plugin and returned to the frontend, as required, via an API.

### PR DESCRIPTION
**Pull request by ayshiff**
## Hey, I just made a Pull Request!

Closes #3590

This PR adds a new method `getClusters` to the Kubernetes backend which returns the clusters config to the frontend.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4791-zxeyhqkekiwaiusyzu6sckjmotmasfmv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604024e5fcb22d0ea1675c7f

**Review by Rugvip — APPROVED** [review]
Thanks! Think this makes sense, wanna have a look too @mclarke47

**Review by mclarke47 — APPROVED** [review]

**Comment by benjdlambert** [comment]
@ayshiff this was missing a changeset, so I created it for you. Good to merge when it passes +1

**Review by benjdlambert — APPROVED** [review]

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4791-zxeyhqkekiwaiusyzu6sckjmotmasfmv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604024e5fcb22d0ea1675c7f

**Comment by benjdlambert** [comment]
Thanks for fixing prettier! 👍

**Pull request merged**
