### PR TITLE
fix: bitbucket server edit url resolves correctly

### LINKED ISSUE #20042: 🐛 Bug Report: Bitbucket Server Integration does not resolve edit url correctly
### 📜 Description

Hi everyone,

After the processing of an entity registered on bitbucket server, I found out that the annotation `ANNOTATION_EDIT_URL` (`backstage.io/edit-url`) created is not correct if the entity resides on a branch different from `master`.

In fact, all the query parameters of the catalog-info repository url are cut off, and so the correct branch (`at` query param).

The method involved states this: 

> // Bitbucket Server doesn't support deep linking to edit mode, therefore there's nothing to do here.
    // We just remove query parameters since they cause issues with TechDocs edit button.

### 👍 Expected behavior

Return the correct url, without cutting the branch

### 👎 Actual Behavior with Screenshots

image

`view-url` is displaying correctly, while `edit-url` cuts the query params

### 👟 Reproduction steps

Register a `catalog-info.yaml` file in a branch different from `master`, in a bitbucket server repo for example
```
localhost:7990/projects/WIT/repos/test_dp_bitbucket/browse/catalog-info.yaml?at=release_5
```

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

@backstage/app-defaults                               1.0.8
  @backstage/backend-app-api                            0.2.3
  @backstage/backend-common                             0.16.0
  @backstage/backend-plugin-api                         0.1.4
  @backstage/backend-tasks                              0.3.7
  @backstage/backend-test-utils                         0.1.30
  @backstage/catalog-client                             1.1.2
  @backstage/catalog-model                              1.2.1
  @backstage/cli-common                                 0.1.10
  @backstage/cli                                        0.21.1
  @backstage/config-loader                              1.1.6
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.2.0
  @backstage/core-components                            0.12.5
  @backstage/core-plugin-api                            1.5.0
  @backstage/dev-utils                                  1.0.8
  @backstage/errors                                     1.1.5
  @backstage/integration-react                          1.1.6
  @backstage/integration                                1.4.0
  @backstage/plugin-api-docs                            0.8.11
  @backstage/plugin-app-backend                         0.3.38
  @backstage/plugin-auth-backend                        0.17.1
  @backstage/plugin-auth-node                           0.2.7
  @backstage/plugin-catalog-backend-module-msgraph      0.4.4
  @backstage/plugin-catalog-backend                     1.5.1
  @backstage/plugin-catalog-common                      1.0.8
  @backstage/plugin-catalog-graph                       0.2.23
  @backstage/plugin-catalog-import                      0.9.1
  @backstage/plugin-catalog-node                        1.2.1
  @backstage/plugin-catalog-react                       1.2.1
  @backstage/plugin-catalog                             1.6.1
  @backstage/plugin-github-actions                      0.5.11
  @backstage/plugin-org                                 0.6.1
  @backstage/plugin-permission-backend                  0.5.13
  @backstage/plugin-permission-common                   0.7.1
  @backstage/plugin-permission-node                     0.7.1
  @backstage/plugin-permission-react                    0.4.7
  @backstage/plugin-proxy-backend                       0.2.32
  @backstage/plugin-scaffolder-backend                  1.8.0
  @backstage/plugin-scaffolder-common                   1.2.2
  @backstage/plugin-search-backend-module-elasticsearch 1.0.4
  @backstage/plugin-search-backend-module-pg            0.4.2
  @backstage/plugin-search-backend-node                 1.0.4
  @backstage/plugin-search-backend                      1.1.1
  @backstage/plugin-search-common                       1.1.1
  @backstage/plugin-search-react                        1.2.1
  @backstage/plugin-search                              1.0.4
  @backstage/plugin-shortcuts                           0.3.3
  @backstage/plugin-tech-radar                          0.5.18
  @backstage/plugin-techdocs-backend                    1.4.1
  @backstage/plugin-techdocs-module-addons-contrib      1.0.6
  @backstage/plugin-techdocs-node                       1.4.2
  @backstage/plugin-techdocs-react                      1.0.6
  @backstage/plugin-techdocs                            1.4.0
  @backstage/plugin-user-settings                       0.5.1
  @backstage/release-manifests                          0.0.7
  @backstage/test-utils                                 1.2.2
  @backstage/theme                                      0.2.18
  @backstage/types                                      1.0.1, 1.0.2
  @backstage/version-bridge                             1.0.3

(it is not the last version but I checked on master and the bug is still there)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by fedy97**
## Hey, I just made a Pull Request!

from this:
image

to this:
image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

Closes #20042

### CODE REVIEW

**Review by freben — COMMENTED** [review]
This needs a changeset to get shipped.

The comment above states that there is no edit mode to link to. Is that not true?

Also, hm. The comment that got removed is interesting. I wonder if that impact is still relevant. Does perhaps @backstage/techdocs-maintainers know? Either way, that sounds like something that should be fixed in the TechDocs end rather than here.

**Comment by fedy97** [comment]
> This needs a changeset to get shipped.
> 
> The comment above states that there is no edit mode to link to. Is that not true?
> 
> Also, hm. The comment that got removed is interesting. I wonder if that impact is still relevant. Does perhaps @backstage/techdocs-maintainers know? Either way, that sounds like something that should be fixed in the TechDocs end rather than here.

Thanks @freben for your reply. The edit button in techdocs redirects you always to the master branch and not to the correct branch (the query params are cut also there), so it is another bug to be fixed.

**Comment by awanlin** [comment]
Some what related: https://github.com/backstage/backstage/issues/12892

@pjungermann any feedback or thoughts on this one?

**Comment by fedy97** [comment]
We could maybe keep only the `at` query param and remove the others (like `mode`)?

**Comment by pjungermann** [comment]
@fedy97 This change was done by another Bitbucket Server consciously in order to make "edit URL" work for Tech Docs. By removing the truncation of query parameters, you will break the "edit" button feature at Tech Docs.

I worked on a change at PR #16699 which will make it work without removing the query parameters, also for other systems like Bitbucket Cloud. However, it still requires some changes to mkdocs-techdocs-core and mkdocs-monorepo-plugin before it could be merged.

**Comment by fedy97** [comment]
> @fedy97 This change was done consciously by another Bitbucket Server user in order to make "edit URL" work for Tech Docs. By not removing the query parameters, you will break the "edit" button feature at Tech Docs.
> 
> The reason for this is mkdocs itself and how it supports edit_uri there.
> 
> I worked on a change at PR #16699 which will make it work without removing the query parameters, also for other systems like Bitbucket Cloud. However, it still requires some changes to mkdocs-techdocs-core and mkdocs-monorepo-plugin before it could be merged.

I am not able to reproduce the breaking of the edit button, it always redirect me to the `index.md` on master branch (not in edit mode). It seems there is no difference if query params are set or not. Maybe a specific query params breaks it?

**Comment by pjungermann** [comment]
I just found the original PR #12857 for context.

**Comment by pjungermann** [comment]
@omerfarukdogan as the original author of the aforementioned PR, maybe you can have a look at this change.

**Comment by omerfarukdogan** [comment]
@fedy97 Which version of Backstage are you using? I have just tested on ours (1.13.0) and the edit button still works correctly. It opens the source of the current page (`https://<host>/projects/<project>/repos/<repo>/browse/docs/sub-page.md`)

Are you setting up techdocs-url like this?

    "backstage.io/techdocs-ref": "url:https://<host>/projects/<project>/repos/<repo>/browse/"

**Comment by fedy97** [comment]
> @fedy97 Which version of Backstage are you using? I have just tested on ours (1.13.0) and the edit button still works correctly. It opens the source of the current page (`https://<host>/projects/<project>/repos/<repo>/browse/docs/sub-page.md`)
> 
> Are you setting up techdocs-url like this?
> 
> ```
> "backstage.io/techdocs-ref": "url:https://<host>/projects/<project>/repos/<repo>/browse/"
> ```

the issue is this #20042 : I have  this catalog info `localhost:7990/projects/WIT/repos/test_dp_bitbucket/browse/catalog-info.yaml?at=release_5` which has `backstage.io/techdocs-ref: dir:.`. When I import it, the edit-url is wrong, it is missing the `at` query param that specifies the branch. The edit button always redirects to master doc.

**Comment by omerfarukdogan** [comment]
@fedy97 I don't think the function you are modifying is related to the annotation (`backstage.io/edit-url`) you have an issue with. This is a function under **techdocs** plugin and it is executed during the document generation step. The annotation is not generated here and should not be affected by this change. The annotation is for editing the entity definition itself, not the document. Please correct me if I'm wrong @freben, @pjungermann.

On the other hand, the parameters on the document URL are indeed removed from the "edit document" button. Otherwise mkdocs generates an incorrect URL for editing (IIRC `https://<host>/projects/<project>/repos/<repo>/browse/?at=release5/docs/sub-page.md` instead of `https://<host>/projects/<project>/repos/<repo>/browse/docs/sub-page.md?at=release5`).

**Comment by fedy97** [comment]
> @fedy97 I don't think the function you are modifying is related to the annotation you have an issue with (`backstage.io/edit-url`). This is a function under **techdocs** plugin and it is executed during the document generation step. The annotation is not generated here and should not be affected by this change. The annotation is for editing the entity definition itself, not the document. Please correct me if I'm wrong @freben, @pjungermann.
> 
> On the other hand, the parameters on the document URL are indeed removed from the "edit document" button. Otherwise mkdocs generates an incorrect URL for editing (IIRC `https://<host>/projects/<project>/repos/<repo>/browse/?at=release5/docs/sub-page.md` instead of `https://<host>/projects/<project>/repos/<repo>/browse/docs/sub-page.md?at=release5`).

The change I made in this PR affects only the annotation `backstage.io/edit-url` and so if you go in the inspect entity you can see the entire url with the `at` query param. The problem to be fixed is the edit button that in this case will redirect me to `http://localhost:7990/projects/WIT/repos/test_dp_bitbucket/browse/docs?at=release_5/index.md` which is a wrong url, but with the actual code it would redirect me to `http://localhost:7990/projects/WIT/repos/test_dp_bitbucket/browse/docs/index.md` which is wrong too because I do not want to go to master branch

**Comment by omerfarukdogan** [comment]
@fedy97 I would imagine most people to use the main branch for documentation so it wouldn't cause a problem for most cases. Our options are:

1. Generate a correct URL with a possibly incorrect branch
2. Generate an incorrect URL
3. Generate a correct URL (by making mkdocs handle the query parameters)

This PR is going with 2 (unless we also fix mkdocs), I would prefer 1 rather than 2, but it's up to the maintainers IMO.

**Comment by fedy97** [comment]
@omerfarukdogan I fixed the edit button link, now it redirects always to master, but the annotation `backstage.io/edit-url` now points to the right url

**Comment by pjungermann** [comment]
@omerfarukdogan I've started to work on  option 3 at the PR I've referenced above. There is a way on newer mkdocs versions. However, still a few things to adjust at backstage's own plugins.

**Pull request closed without merging**
