### PR TITLE
bep(auth-arch): propose a new routerFactory pattern

### PR DESCRIPTION
**Pull request by sennyeya**
## Hey, I just made a Pull Request!

reopens #22642, but this time against master. @Rugvip 👀 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by sennyeya** [comment]
@Rugvip I'd assumed the middleware on the sub router wouldn't apply to subsequent sub routers. Makes sense to use a more declarative approach then! I'll close this.

**Comment by sanderaernouts** [comment]
@Rugvip, is there an ongoing effort to make authentication part of the new backend system, even if it's moving the responsibility to the plugins instead of enforcing it by default? Right now, we have made our implementation based on #17558, but it has some issues, specifically with TechDocs static assets.

**Comment by Rugvip** [comment]
@sanderaernouts yep! See the discussion in https://github.com/backstage/backstage/issues/22605 and the linked proposal. We're working on it atm

**Comment by sanderaernouts** [comment]
> @sanderaernouts yep! See the discussion in #22605 and the linked proposal. We're working on it atm

Thanks, I'll keep an eye on that issue :+1:

**Pull request closed without merging**
