### PR TITLE
feat: support Bearer auth header at git commands

### PR DESCRIPTION
**Pull request by pjungermann**
Support Bearer-based Authorization header for auth
with token only (no username).

Signed-off-by: Patrick Jungermann <Patrick.Jungermann@gmail.com>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
I like this. Would this supersede @12711?

**Comment by pjungermann** [comment]
@benjdlambert at the moment, it was more to demo how it could work.

I think I will complete this PR and it will not supersede the other one, but allow for a different use case.

There are 3 options for auth here: (username, password) OR (username, token) OR (token).
The first two will use Basic Auth as provided by the other PR (token as password).
This change would allow token to be used which already works for UrlReader, etc, but not for Git operations as e.g. used at the scaffolder.

**Comment by pjungermann** [comment]
I think I will just merge this into the other PR

**Comment by pjungermann** [comment]
included at PR #12711

**Pull request closed without merging**
