### PR TITLE
feat: add errors to Pod Drawer

### PR DESCRIPTION
**Pull request by mclarke47**
This PR adds Errors detected in the error detection section to the pod drawer

Screenshot 2023-04-28 at 2 30 58 PM
Screenshot 2023-04-28 at 2 30 52 PM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jamieklassen — CHANGES_REQUESTED** [review]
All looks pretty sensible, but maybe we don't need to put the pod name as the primary text for every error, since that would be repetitive?

**Comment by mclarke47** [comment]
Done @jamieklassen 🙏

**Review by jamieklassen — APPROVED** [review]
lgtm

**Comment by mclarke47** [comment]
@jhaals 🙏

**Review by jhaals — APPROVED** [review]

**Pull request merged**
