### PR TITLE
Add support for json schema to API docs

### PR DESCRIPTION
**Pull request by Fox32**
This PR adds support for displaying API docs in the JSON schema format. 

image

If first thought about reusing existing stuff from the config schema viewer, but that code is very targeted to its specific use case. Instead, the viewer is based on [stoplightio/json-schema-viewer ](https://github.com/stoplightio/json-schema-viewer). It's currently in beta, but already quite nice.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Fox32** [comment]
I will try to resolve the build error upstream first.

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5532-9rltzbuzr3e4txj7esvojinnkh2x0nfk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abb6da55c9a7d0ea4f89a

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5532-9rltzbuzr3e4txj7esvojinnkh2x0nfk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abb6da55c9a7d0ea4f89a

**Review by freben — APPROVED** [review]
Cool.

So many dependencies 😓

**Comment by Fox32** [comment]
> Cool.
> 
> So many dependencies 😓

I actually thought about it for two weeks, but couldn't find a better option that brings less friends...

**Pull request merged**
