### PR TITLE
Fix GitHub OAuth format

### LINKED ISSUE #2964: TechDocs: Cannot view document from Github private repository
## Expected Behavior

I should be able to view the documented-component page.

## Current Behavior

- Received an ERROR 404: Documentation not found.
- Browser console shows a CORS error at the end.

imagen

## Steps to Reproduce

Navigate to `my.backstage.com/docs` on browser and click Read Docs under documented-component

## Context

Trying to view Techdocs

## Your Environment

I've deployed Backstage on our internal Kubernetes cluster. 
I've built docker images based on what is on master@ac8d5d5c74bbc073d6d1f372ce15b8b2cffb3e52
I run the following on the building process:
```
yarn install
yarn tsc
# frontend
yarn run docker-build:app
# backend
yarn docker-build -f contrib/docker/kubernetes-example-backend/Dockerfile
```
Resulting in [frontend](https://hub.docker.com/r/saltosystems/backstage) and [backend](https://hub.docker.com/r/saltosystems/backstage-backend) images, being tag `676f49ea6fe0266a170b755397ddb808c5fc6961` the tag currently I'm using. 

Techdocs relevant app-config:
```
techdocs:
  storageUrl: https://my.backstage.com/api/techdocs/static/docs
  requestUrl: https://my.backstage.com/api/techdocs
  generators:
    techdocs: local
```
Kubernetes relevant config:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backstage-backend
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - my.backstage.com
    secretName: backstage-production-letsencrypt
  rules:
  - host: my.backstage.com
    http:
      paths:
      - backend:
          serviceName: backstage-backend
          servicePort: backend
        path: /api(/|$)(.*)

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backstage-frontend
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - my.backstage.com
    secretName: backstage-production-letsencrypt
  rules:
  - host: my.backstage.com
    http:
      paths:
      - backend:
          serviceName: backstage
          servicePort: frontend
        path: /
```
I'm not sure if this is a bug or if this is related to a misconfiguration on my side, since I can see requests to `localhost:3003` inestead to `my.backstage.com`. Any ideas?

Related issue #2736

### PR DESCRIPTION
**Pull request by steelrooter**
## Hey, I just made a Pull Request!

GitHub expects the OAuth token to be used, in the repo url, in a slightly different manner from GitLab and Azure.
[GitHub expects just the token](https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/#using-oauth-with-git), whereas GitLab and [Azure](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#use-a-pat) expect a colon before the token.

Fixes #2964 

#### Points to note
- If someone can verify this with GitHub and/or Azure, it would be great. I have tested it only on GitLab and it works.
- I noticed that code to support BitBucket integration is missing. That will need to be added in future.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/spotify/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by steelrooter** [comment]
@amarruedo Can you please verify if this works in your setup?

**Comment by emmaindal** [comment]
Hi @steelrooter Thanks for your contribution 😄 Will take a look!

**Comment by emmaindal** [comment]
Just gave your changes in this PR a try with Github and private repo, I could register the component but viewing the docs gives me this. 

Screen Shot 2020-10-22 at 11 02 56 AM

It doesn't give me the errors for documentation that are from a public repo.

Will continue investigate but just wanted to update you

**Comment by asaintsever** [comment]
@emmaindal FYI I have the exact same issue trying to view the doc for a service in a public repo (so this issue does not only happen on private ones)

**Comment by emmaindal** [comment]
@asaintsever great, thanks for letting me know that! I'll update you when I find the problem!

**Comment by amarruedo** [comment]
@emmaindal @steelrooter I'm also getting the same error (`Invalid type in config for key 'integrations.github' `) both for public and private repos.

**Comment by steelrooter** [comment]
@emmaindal @asaintsever @amarruedo The error you are facing seems to be because of this PR: #3004 
Pushing a fix for this

**Comment by steelrooter** [comment]
@emmaindal @asaintsever @amarruedo Pushed the fix. Please verify.

**Comment by asaintsever** [comment]
@steelrooter I can confirm it works fine now (tested on public repo only)

**Comment by emmaindal** [comment]
@steelrooter I can confirm it works fine on public repos as mentioned above but for private repo 
Screen Shot 2020-10-22 at 12 45 49 PM

**Comment by steelrooter** [comment]
Creating a private repo and testing it.

**Comment by steelrooter** [comment]
@emmaindal @amarruedo Fixed it. Turned out that `nodegit` cannot clone the repo with just the token (while it works command using git on command line). `nodegit` require that token be provided with `:x-oauth-basic` appended to it in the url. I have tested it with a private GitHub repo and it works.

**Review by emmaindal — APPROVED** [review]
@steelrooter Woho, thanks so much! Can confirm it works and will approve this PR! 🎉

**Pull request merged**
