### PR TITLE
[Rollbar]: Fix camel case keys type errors

### PR DESCRIPTION
**Pull request by camilaibs**
## Hey, I just made a Pull Request!

Fix type errors when running `tsc:full`.
image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by andrewthauer** [comment]
Curious how these started. I initially thought it was a bump in `camelcase-key` that introduced this, but that dependency doesn't seem to have changed any time recently.

**Review by Rugvip — COMMENTED** [review]
I'm not able to reproduce this on latest master, `76b838a`, doing `yarn install && yarn tsc:full`. Not seeing this in CI either.

Could it be some local install state for you perhaps? I'd wonder if it persists if you clean out all `node_modules` and re-run `yarn install`.

**Comment by camilaibs** [comment]
> I'm not able to reproduce this on latest master, `76b838a`, doing `yarn install && yarn tsc:full`. Not seeing this in CI either.
> 
> Could it be some local install state for you perhaps? I'd wonder if it persists if you clean out all `node_modules` and re-run `yarn install`.

I can reproduce on the `master` branch if I clear the`yarn` cache. Could you try clearing the cache to see if this only happens in my local environment?
```sh
yarn clean && rm -rf node_modules && yarn cache clean && yarn install && yarn tsc:full
```

**Comment by andrewthauer** [comment]
I can confirm, I'm now getting these errors as well. Still confused how this started though.

**Comment by benjdlambert** [comment]
Hmm @camilaibs I can't reproduce this either with your command 😢

**Comment by camilaibs** [comment]
It seems that it is happening only to me 💁🏻‍♀️, thanks for testing everybody, closing this pull request!

**Comment by sennyeya** [comment]
I just had this issue happen to me, I had to delete the `node_modules` folders under `plugins/rollbar-backend` and in my case `plugins/techdocs-react` as well. Just `yarn clean && rm -rf node_modules && yarn cache clean && yarn install && yarn tsc:full` didn't work for me.

**Pull request closed without merging**
