### PR TITLE
fix(template tags): fixes issues with tags specified with uppercase

### PR DESCRIPTION
**Pull request by emmaindal**
## Hey, I just made a Pull Request!

While running `yarn lerna run mock-data` an error appeared around tags specified with uppercase. This PR changes how tags are validated using a new introduced `isValidMetadataTag` instead of `isValidDnsLabel` to allow uppercased tags. 

Feel free to suggest any other fix to this but right now its not possible to mock templates. 

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by emmaindal** [comment]
We can also change how tags are specified in the templates if it should follow the dns label validations.

**Comment by Fox32** [comment]
Right now it is build to only allow lowercase tags. We should update the spec documentation, too if we want uppercase tags. There is also a test that explicitly checks that only lowercase tags are allowed.

**Comment by emmaindal** [comment]
@Fox32 Thanks for fast response. Did you see the tags in the metadata on templates when you changed this? And was there any reason you restricted it to lowercase?

**Comment by Fox32** [comment]
No I didn't see that the template entity specifies additional fields in metadata (but I know what you mean https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml/#L7-L9). That an entity kind defines own fields in metadata isn't something I expected.

I choose lowercase based on the comment by @stefanalund here: https://github.com/spotify/backstage/issues/1997#issuecomment-675523456

**Comment by emmaindal** [comment]
@Fox32 Alright, I see! We added a new suggested validator to use for metadata tags but @spotify/backstage-core let us know if this is unwanted and we will just update the template configs.

**Comment by emmaindal** [comment]
@spotify/backstage-core before I continue this, any comments?

**Comment by freben** [comment]
Hey! So,

At the _very least_, tags must be either equal to, or a subset of, what can be put in `metadata.name`. This is because we may extend the tag model some day into actually be references to `Tag` kind entities that contain more info about the tag.

I honestly do not have a super strong opinion on the casing etc. It can be argued that lowercase-only plus dashes gives less space for mistakes. The drawback is of course that they are rendered verbatim in front of users so it may look less pleasing with forced dashified words etc.

Still I think that the argument about mistakes, and the possible future where these are "just references", wins in the long run. If we keep forcing them to be lowercase-and-dashes, we can make them prettier sometime down the line instead.

I like that you did break out the `isValidMetadataTag` validator, we should keep that. But maybe it should per default just call out to `CommonValidatorFunctions.isValidDnsLabel`.

Does that make sense? Or does this cause problems somewhere the uppercasedness was strongly desired or even needed?

**Comment by hooloovooo** [comment]
> Hey! So,
> 
> At the _very least_, tags must be either equal to, or a subset of, what can be put in `metadata.name`. This is because we may extend the tag model some day into actually be references to `Tag` kind entities that contain more info about the tag.
> 
> I honestly do not have a super strong opinion on the casing etc. It can be argued that lowercase-only plus dashes gives less space for mistakes. The drawback is of course that they are rendered verbatim in front of users so it may look less pleasing with forced dashified words etc.
> 
> Still I think that the argument about mistakes, and the possible future where these are "just references", wins in the long run. If we keep forcing them to be lowercase-and-dashes, we can make them prettier sometime down the line instead.
> 
> I like that you did break out the `isValidMetadataTag` validator, we should keep that. But maybe it should per default just call out to `CommonValidatorFunctions.isValidDnsLabel`.
> 
> Does that make sense? Or does this cause problems somewhere the uppercasedness was strongly desired or even needed?

I don't think it's really needed, but it's something we noticed when we tried to run the mock scripts for templates. They already have their own implementation of tags which allows uppercase which caused a validation error when trying to add them to the catalog.

**Comment by freben** [comment]
Sure, and this is the internal example ones right? In that case we should probably fix those to the lowercase-and-dashes form but keep the nice dedicated validation code.

**Comment by freben** [comment]
Again, maybe I don't have 100% context, so this is a gut feeling based response :) Let me know if the response helped or not.

**Comment by emmaindal** [comment]
Thanks @freben yeah as @hooloovooo mentioned we don't have a strong opinion on whether to allow uppercase tags or not. More us trying to find a fix for the errors that are logged when running `yarn lerna run mock-data` for the templates since all of them includes Tags with uppercase. And when looking into a solution the "isValidDnsLabel" looked like a validator that would be great to use for dns related things but for this one, nothing related (as far as I know) to dns validation is needed. But can also be me not knowing much about how the dns label validation should be used. xD

We will then update this PR and make a change of the templates that contains uppercased tags.

**Review by stefanalund — APPROVED** [review]

**Comment by freben** [comment]
Oh you removed the new nice code for explicitly checking tags - well ok, we can reintroduce that some other time. Thank you for fixing!

**Comment by emmaindal** [comment]
> Oh you removed the new nice code for explicitly checking tags - well ok, we can reintroduce that some other time. Thank you for fixing!

Yesss I actually did, because I felt a further discussion were needed about what the `isValidDnsLabel ` should be used for. To have a validator `isValidTag` that uses  `CommonValidatorFunctions.isValidMetadataTag` that then calls `CommonValidatorFunctions.isValidDnsLabel` in the end anyway sounded like `isValidTag` could instead just use the `isValidDnsLabel` directly. But yes we can introduce it again if needed in the future. Thanks for feedback 😄

**Pull request merged**
