### PR TITLE
Filter Updates Upon Navigation - Fix for Issue #8432

### PR DESCRIPTION
**Pull request by danielsamet**
## Hey, I just made a Pull Request!

Implemented a fix for Issue #8432. 

The issue was that the type filter in the catalog was not being updated when using a sidebar submenu. 

The fix was adding the URL search parameter as a prop for EntityTypePicker.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@timbonicus I wonder if there's a better way to implement this, so that we can read the filters from the query string already on change. Do you have any other ways that would be cleaner?

**Comment by timbonicus** [comment]
react-router's `useLocation` is probably the right fix, but it should be inside the `useEntityListProvider` hook and update the `queryParameters` on `outputState`. Then `useEntityTypeFilter` will probably need an update too since it only uses `queryParameters` for the default value in the `setState` call.

It's a bit tricky since it's easy to get into a loop when you're both reading query params and pushing updates to them. Since `useEntityListProvider` is using `replaceState` though I think `useLocation` should be safe. I'm out for a couple days but can help with this next week if needed.

**Comment by freben** [comment]
Also remember to DCO sign your commits!

**Comment by danielsamet** [comment]
Thanks @timbonicus, I've just spent some time having a look at what you've referenced and I think I understand what you're saying. I'm going to try and implement a solution for it beginning of next week. I'll reach out if I get stuck. Thanks again!

P.S. @freben, I realised my mistake and followed the instructions for adding signatures but it just created 3 new commits with signatures on top of the ones without signatures. Does that make sense? Or have I missed something? Lmk please.

**Comment by freben** [comment]
@danielsamet Sorry no - every single commit is a unit of work, and it's the commits _themselves_ that need to be declaring that whatever goes in that particular commit has been waived to the project.

**Comment by danielsamet** [comment]
@freben I'm struggling to sign those commits that were already pushed. When I follow the instructions suggested by the DCO check (`git rebase HEAD~7 --signoff`) it just adds duplicates of the commits to the branch but doesn't amend the existing commits that are lacking signatures. Please advise.

**Comment by danielsamet** [comment]
@timbonicus I'm trying wrap my head around it but to be honest I think I'm a little stuck. Could you please elaborate further on what you've mentioned? Thanks in advance!

**Comment by Rugvip** [comment]
@danielsamet regarding DCO I think it's because of the final merge commit. It could be worth rolling the branch back to `b04f733` and then try to apply the `--signoff`. In general I find it simpler to keep feature branches up to date by rebasing them rather than merging in the main branch, perhaps unless you're several people collaborating on the same branch.

**Review by Rugvip — COMMENTED** [review]
@timbonicus do you have any additional pointers that might help? :grin:

I'll throw in that I think we want to target a fix that doesn't change the `DefaultCatalogPage`, as that would require people to update their custom catalog pages. It'd be better to have it baked into the components and hooks that are used there instead

**Comment by timbonicus** [comment]
I made #9247 with a proposed fix that updates `useEntityListProvider` and the UI pickers.

**Comment by danielsamet** [comment]
@timbonicus, thanks for that. I was struggling to understand how certain parts worked together. I've read through your changes and I think they make sense now, so thanks!

**Pull request closed without merging**
