### PR TITLE
docs: submitting Library Check plugin to marketplace

### PR DESCRIPTION
**Pull request by accezar**
## Hey, I just made a Pull Request!

Submitting [Library Check Plugin](https://github.com/anakzr/backstage-plugin-library-check) to marketplace microsite.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you, looks like a useful plugin! 👍 

Where is the source code for it? can't find it in the repo

**Comment by accezar** [comment]
> Thank you, looks like a useful plugin! 👍
> 
> Where is the source code for it? can't find it in the repo

Hi @Rugvip first, thanks a lot for the feedback. Nice to know it will be useful. 

About the code, since it's the very first version (published last night), there could be some improvements needed, and I'm waiting for feedback. But my plan is to share the code once I get initial feedback and tackle any early issues. Would that be a problem for submitting?

**Comment by vinzscam** [comment]
> About the code, since it's the very first version (published last night), there could be some improvements needed, and I'm waiting for feedback. But my plan is to share the code once I get initial feedback and tackle any early issues. Would that be a problem for submitting?

I think you should be proud of showing off your work! The plugin looks amazing and I'm sure a lot of people will benefit from that 😄

**Comment by accezar** [comment]
Hello @vinzscam and @Rugvip 

The code is now open 🙏

**Review by vinzscam — APPROVED** [review]

**Comment by accezar** [comment]
@Rugvip is there anything else needed to submit?

**Review by Rugvip — CHANGES_REQUESTED** [review]
Hi! Couple of pieces I think it's best to fix before listing:

* Could you replace usage of `config.get('backend.baseUrl')` with `discovery.getBaseUrl(...)` in the backend?
* Please review https://github.com/backstage/backstage/blob/master/SECURITY.md#coding-practices and update the implementation to be in line with those recommendations

**Comment by accezar** [comment]
> Hi! Couple of pieces I think it's best to fix before listing:
> 
> * Could you replace usage of `config.get('backend.baseUrl')` with `discovery.getBaseUrl(...)` in the backend?
> * Please review https://github.com/backstage/backstage/blob/master/SECURITY.md#coding-practices and update the implementation to be in line with those recommendations

Thank you very much for taking the time to review @Rugvip.

I have created a [new branch](https://github.com/anakzr/backstage-plugin-library-check/tree/fix/backstage-code-review/plugins/library-check-backend) with the implemented changes. Do you believe it aligns well with the guidelines?

**Comment by Rugvip** [comment]
@acc yep, looks good 👍

**Comment by accezar** [comment]
> @accezar yep, looks good 👍

@Rugvip 

New [release](https://github.com/anakzr/backstage-plugin-library-check/releases) published with the [changes](https://github.com/anakzr/backstage-plugin-library-check/pull/4) 😉

**Comment by accezar** [comment]
> @accezar yep, looks good 👍

Is there anything else left for submission?

**Review by Rugvip — APPROVED** [review]
All good, thank you! 👍

**Pull request merged**
