### PR TITLE
feat: allow signing git commits from scaffolder

### LINKED ISSUE #25934: 🚀 Feature: allow signing git commits from scaffolder action
### 🔖 Feature description

For example, Github scaffolder action `github:repo:push` uses the helper function here to make a commit using isomorphic-git underneath: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-node/src/actions/gitHelpers.ts#L23 

The other git related scaffolder actions use the same helper but it doesn't support signing the commit.

### 🎤 Context

Some repositories might require that the commit is signed with a GPG key and using scaffolder actions to create these commits will fail in the pre-receive hook if signing support is missing. 

### ✌️ Possible Implementation

We need a new secret value to config/scaffolder that Backstage users can insert their private GPG key to be used for signing. Additionally, all scaffolder actions using the helper need to support a new parameter that determines whether the commit should be signed or not.

Integrating this to isomorphic-git is quite straightforward (https://github.com/backstage/backstage/blob/master/plugins/scaffolder-node/src/scm/git.ts#L145)

```ts
// @ts-ignore
import { pgp } from '@isomorphic-git/pgp-plugin';

return git.commit({ fs, dir, message, author, committer, signingKey, onSign: pgp.sign });
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

adds support to sign git commits with configured PGP key in scaffolder actions. configuration can be done either by integration or by using the default signing key in the scaffolder config. note that this pgp-plugin is used for signing and that it is limited to using RSA keys and signatures made with SHA1 hashing algorithm.

closes #25934

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by acierto** [comment]
@drodil Code-wise looks good. There are some conflicts atm.

Did you test all providers that it really works after the change? 😅

**Comment by drodil** [comment]
Thanks, will do a rebase. Actually, I could only test GitHub and Bitbucket that those work so probably have to get some more eyes and testers 🤔

**Review by acierto — APPROVED** [review]

**Comment by drodil** [comment]
Could the following people take a look  at this if it looks ok as you are one of the latest contributors to these modules:

- @lukasfruntke-extern 
- @sanderaernouts  
- @tcardonne 
- @kenzliang 
- @cmoulliard 

Sorry if I pinged the wrong people!

**Review by tcardonne — APPROVED** [review]
LGTM for the Gerrit integration.

I did some testing and the resulting commit is properly signed with the `publish:gerrit` action.
I didn't manage to test successfully the `publish:gerrit:review` action but the error I have doesn't seem related to your changes (it fails to do the `git fetch` somehow before commiting and pushing).

**Comment by drodil** [comment]
@tcardonne thanks for verifying!

**Comment by acierto** [comment]
@drodil some conflicts here too

**Comment by drodil** [comment]
@sanderaernouts thanks for the comment. I learned that this actually does not work with Github apps either. So closing this for now and will see if this can be done some other way. For gerrit/gittea/bitbucket the functionality would work so those could be done in a separate PR.

**Pull request closed without merging**
