### PR TITLE
fix: add resource icon

### PR DESCRIPTION
**Pull request by dweber019**
## Hey, I just made a Pull Request!

Add resource default icon, looking like
Screen Shot 2023-11-20 at 22 09 14 PM

Reused the work icon as this is the default one in all Backstage demos, as seen here
Screen Shot 2023-11-20 at 22 04 06 PM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hmm, I wonder if the `StorageIcon` might be a better fit for default resources?

image

**Comment by dweber019** [comment]
Agree that this icon would be nicer but currently we use the work icon to represent resources by default.

Should we change this overall?

**Comment by freben** [comment]
Indeed it's the work icon at this point, we can change it consistently later right if we want to @benjdlambert?

**Comment by freben** [comment]
Oops, misclick

**Review by freben — APPROVED** [review]

**Comment by benjdlambert** [comment]
Yeah - OK, let's revisit.

**Review by benjdlambert — APPROVED** [review]

**Comment by dweber019** [comment]
If you like I can tackle this right away in a new PR.
What would be the icon you like?
I suggest database or storage.

**Pull request merged**
