### PR TITLE
feat: scaffolder Github repo drop down

### PR DESCRIPTION
**Pull request by dev-geddy**
## Feature: Github repositories select populated using apps config to call Github API

This PR adds Github repositories dropdown functionality that is handled by `ui:options` within `template.yaml` template.
Field example:
```yaml
    - title: Choose Github Repository
      required:
      - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedOwners: ['organisation-name-1', 'organisation-name-2']
            allowedHosts: ['github.com']
            showRepoDropdown:
              github: true
            pullReposFromBackend:
              github: true
```
- `showRepoDropdown` - converts free form text input to a select field with Github repos pre-populated, uses `smcAuthApi.getCredentials()` to get Github token to fetch Github repos by default.
- `pullReposFromBackend` - pre-populates drop down values using new API endpoint within Scaffolder Backend. Uses **Octokit** to make calls to Github, `appId` and `privateKey` config items used from Github integrations configuration defined in your `app-config.yaml`
- When `showRepoDropdown` option is not present, functionality should be intact as per original implementation.

Repository select drop-down preview below:
image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by rr-peter-chen** [comment]
This is brilliant!  Thank you for the contribution.

> dropdown functionality that is handled by ui:options within catalog-info.yaml template.

Quick fix here, do you mean `template.yaml` instead.

**Comment by benjdlambert** [comment]
Hey :wave: sorry it's taken a while to get back to you here. I've been off for a bit, and being stewing over this.

So, we've got two things that I think we need to think about here in terms of user experience.

**Listing organizations and repositories available to the user**
- So this would use the signed in users oauth token which we can retrieve in the frontend
- Make some requests using octokit in the frontend with a token

**Listing organization and repositories available to the backend**
- This would use the github app, or PAT that you have registered in your `integrations` config in the `app-config.yaml` to call the octokit API's

So I think we could basically move this logic all to the backend, but I'm not sure that the place for this is under the `scaffolder-backend` plugin. It's almost like we need to have a backend plugin for these field extensions, but not sure the best way to solve that right now.

I'm leaning towards maybe having an `integrations-backend` plugin that would have this logic that you could pass through an oauth token from the frontend too, and it would use that token in favor of the token that it could generate using the `integrations` config. And then the `repoUrlPicker` could call out to that backend if available to grab a list of things available to it. There's also additional security concerns here, that maybe everything that is available to the Github App shouldn't be visible to the user, like say you have a super secret department in your company, should I be able to see the repo name and org of some important stuff in your company?

Need some more input here from some other maintainers I think, @backstage/maintainers

**Comment by Rugvip** [comment]
@benjdlambert  Yep I think either an integrations backend or perhaps even a GitHub backend is gonna be the way to go here. May also be the thing that in the end is responsible for receiving GH webhook events as well.

**Review by Rugvip — COMMENTED** [review]
@benjdlambert  Yep I think either an integrations backend or perhaps even a GitHub backend is gonna be the way to go here. May also be the thing that in the end is responsible for receiving GH webhook events as well.

**Comment by dev-geddy** [comment]
Having an issue with generating changeset
```
🦋  Summary · New endpoint and front-end dropdown with repos
🦋  
🦋  === Summary of changesets ===
🦋  minor:  @backstage/plugin-scaffolder, @backstage/plugin-scaffolder-backend
🦋  
🦋  Note: All dependents of these packages that will be incompatible with
🦋  the new version will be patch bumped when this changeset is applied.
🦋  
🦋  Is this your desired changeset? (Y/n) · true
🦋  error Error: Cannot find module '@spotify/prettier-config' from '/Users/gediminas/WEB/payment-sense/contribute-open-source/backstage'
🦋  error     at Function.sync (/Users/gediminas/WEB/payment-sense/contribute-open-source/backstage/node_modules/prettier/index.js:15946:13)
🦋  error     at Object.transform (/Users/gediminas/WEB/payment-sense/contribute-open-source/backstage/node_modules/prettier/index.js:22820:36)
🦋  error     at /Users/gediminas/WEB/payment-sense/contribute-open-source/backstage/node_modules/prettier/third-party.js:4550:32
🦋  error     at async Promise.all (index 0)
🦋  error     at async Object.writeChangeset [as default] (/Users/gediminas/WEB/payment-sense/contribute-open-source/backstage/node_modules/@changesets/write/dist/write.cjs.dev.js:78:26)
🦋  error     at async add (/Users/gediminas/WEB/payment-sense/contribute-open-source/backstage/node_modules/@changesets/cli/dist/cli.cjs.dev.js:508:25)
🦋  error     at async run$2 (/Users/gediminas/WEB/payment-sense/contribute-open-source/backstage/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1244:5) {
🦋  error   code: 'MODULE_NOT_FOUND'
🦋  error }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Gediminass-MacBook-Pro:backstage gediminas$ 
```

**Comment by Rugvip** [comment]
Tbh I feel that this addition is a bit too large to start up without knowing that we have someone to help guide the contribution. I'm not able to take on more things at the minute so checking if anyone else in @backstage/maintainers wants to guide this? If not I'm feeling that we'll have to wait a bit with this addition until we've got some of our other things shipped.

**Comment by benjdlambert** [comment]
I'm happy to support building this and going down having an `integrations-backend` plugin that can perform tasks for certain things wrt integrations, like listing the repositories for a given token or using the installation that ships with the github app. Might have some free time over summer I believe to help support this 🤞

**Comment by benjdlambert** [comment]
@dev-geddy I'm gonna close this issue for now, but I've started work on an `integrations-backend` plugin where this logic is going to move to, will link them together when it's done, but hopefully should have something this week.

**Pull request closed without merging**
