### PR TITLE
feat(GithubMultiOrgEntityProvider): implement provider

### PR DESCRIPTION
**Pull request by kuangp**
## Hey, I just made a Pull Request!

Implement provider version of [`GithubMultiOrgReaderProcessor`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/processors/GithubMultiOrgReaderProcessor.ts)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by ConnorDY — APPROVED** [review]
Looks great!
Looking forward to seeing this released so my team can start using it. 🙂

**Comment by ConnorDY** [comment]
My team could really use this.
Any chance we could get a formal review from the Backstage team soon?

**Comment by alexcurtin** [comment]
Hi @kuangp can you add examples of what the `catalog.ts` would look like when using this multi org provider? as well as the config.yaml? Similar to how this doc covers the non-multi org provider? https://backstage.io/docs/integrations/github/org/#installation-without-events-support

**Comment by kuangp** [comment]
> can you add examples of what the `catalog.ts` would look like when using this multi org provider? as well as the config.yaml? Similar to how this doc covers the non-multi org provider?

Sure - I'm currently working on adding events support to this provider as well so I can look into adding docs along with that change once I'm done. Stay tuned!

**Comment by alexcurtin** [comment]
@kuangp any update on the docs? :) thanks for your hard work!

**Comment by kuangp** [comment]
> @kuangp any update on the docs? :) thanks for your hard work!

hot off the presses: https://github.com/backstage/backstage/pull/17565

**Comment by johnsungunity** [comment]
@kuangp I've been trying this out and had a few findings. Perhaps best if I open these as a new issue.

After switching from the entity `GithubOrgReaderProcessor` to the `GithubMultiOrgEntityProvider`  we see github users are dropped into the `default` namespace.
However groups appear to be namespaced properly.

The effect is I see a new user created (2 in the pic) for the same user but with a default namespace (original was blank).

image

Also do you have an example of app-config.yaml and what it should look like now?
Previously we were using this - is there an equivalent for the new multi org provider?
```
  processors:
    githubMultiOrg:
      orgs:
        - name: org1
          groupNamespace: example1
          userNamespace: example1
        - name: org2
          groupNamespace: example2
          userNamespace: example2

```

**Comment by kuangp** [comment]
@johnsungunity you can configure this provider by passing in config options in code (this provider is not driven by the `app-config.yaml` options unlike the previous processor). For example to specify which orgs and to replicate specifying the `userNamespace` options similar to what you had before you can set the following:
```ts
import { 
  ...
  defaultUserTransformer, 
  GithubUser, 
  TransformerContext,
} from '@backstage/plugin-catalog-backend-module-github';

...

GithubMultiOrgEntityProvider.fromConfig(env.config, {
  ...
  orgs: ['org1', 'org2'], // List the GitHub orgs you wish to ingest from
  userTransformer: async (item: GithubUser, ctx: TransformerContext) => {
    const result = await defaultUserTransformer(item, ctx);

    if (result) {
      // namespace users according to their org
      result.metadata.namespace = ctx.org.toLocaleLowerCase('en-US');
    }

    return result;
  },
}),
```

By default, this provider will namespace groups according to their source org so you won't have to customize that behavior. You can also learn more about the available options [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts#L87-L148).

**Comment by johnsungunity** [comment]
Great many thanks Phil for clarifying!

**Pull request merged**
