### PR TITLE
Added support for externalId when assuming role in AwsS3EntityProvider

### PR DESCRIPTION
**Pull request by Charge71**
Signed-off-by: Diego Bardari <diego.bardari@klarna.com>

## Hey, I just made a Pull Request!

Added support for externalId when assuming role in AwsS3EntityProvider

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
I wonder if there's an opportunity to integrate the awesome work that @clareliguori did over here: https://github.com/backstage/backstage/pull/14125 seems to support the `externalId` stuff there I believe.

**Comment by Charge71** [comment]
Hello, we needed a quick patch for this so I took the occasion to file this small PR while creating our custom fixed version of the provider. I agree that every code interacting with AWS should use the new configuration but unfortunately I cannot volunteer for it at the moment. Anyone feel free to update the PR accordingly!

**Comment by benjdlambert** [comment]
OK - Ill create a followup ticket to address this 👍

**Review by benjdlambert — APPROVED** [review]
Thanks for this! Sorry for the delay!

**Pull request merged**
