### PR TITLE
Restore original casing for `kind`, `namespace` and `name` in `DefaultTechDocsCollator`

### PR DESCRIPTION
**Pull request by Fox32**
During the migration to lower case path names in TechDocs, one places was changed that didn't need changing. While the path is all lower case, it doesn't have to hold true for the fields `kind`, `namespace` and `name` in the indexed documents. In this PR the original behavior is restored. This keeps the behavior of `DefaultTechDocsCollator` in line with the behavior of [`DefaultCatalogCollator`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts#L98-L99).

We notice that this causes issues, if the search engine doesn't implement field filters in a case insensitive manner.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by andrewthauer** [comment]
I'm noticing that `TechDocsSearch` component does not work inline anymore if you have lowercased kind in the route (which is default). Search works in the reader if the route is `/docs/default/Component/foo`, but if it's `/docs/default/component` search doesn't work. The document is stored in the search index as a `Titlecased` kind so this kind somewhat explains why the behaviour is occurring. I have a feeling this PR introduced this change in behaviour unintentionally.

**Comment by Fox32** [comment]
Do you now whether you search index is up-2-date? Actually the strings used here are not coming from the route I think 🤔

**Comment by andrewthauer** [comment]
So, I'm using the PG search engine. The db document fields are using `kind: Component`. The search filter looks like it takes the kind as-is from the route (e.g. `/api/search/query?term=&filters[kind]=component`). I'm guessing the search engine itself is case sensitive. I'm not 100% sure the issue is directly related to this PR or not, but it does seem to be related.

**Comment by Fox32** [comment]
Sounds exactly like the problem that we had and why I created this PR 🤔

**Comment by andrewthauer** [comment]
Out of curiosity are you setting `techdocs.legacyUseCaseSensitiveTripletPaths` to `true` in the `app-config.yaml`? We've migrated over to use the new lowercase convention.

**Comment by andrewthauer** [comment]
I think this is the problem. You can replicate this in backstage/backstage repo. Spin it up and the search bar does not work for `http://localhost:3000/docs/default/component/backstage`. The `app-config.yaml` does not set `legacyUseCaseSensitiveTripletPaths` anymore. If you set `techdocs.legacyUseCaseSensitiveTripletPaths` to `true` the search bar starts working.

**Comment by Fox32** [comment]
> @Fox32 - Out of curiosity are you setting `techdocs.legacyUseCaseSensitiveTripletPaths` to `true` in the `app-config.yaml`? We've migrated over to use the new lowercase convention and no longer set this.

No, we already migrated to the lowercase paths. Let me check in Backstage.

**Comment by Fox32** [comment]
Ok, I can reproduce it in Backstage, with the settings I used to write this PR 🤔  (Postgres, no legacy casing).

So the main problem is that the postgres search isn't case sensitive for field filters. Therefore the collator should be corrected to work the same way as the Catalog Collator (done in this PR). I think we should take a look again at the techdocs pages, they should just take the parameters from the path but use the entity instead.

**Comment by andrewthauer** [comment]
So if I understand correctly, the other search engines (lunar & elastic) are case insensitive for field filters and this is only a PG a engine issue?

What your suggestion for a fix would be to update the techdocs code that builds the entity ref/name from the route to use the fetched entity instead?

**Comment by Fox32** [comment]
It's also a UI issue. If you display the entity name in the results, you don't want to display a normalized name, but the real name with the casing that is present in the catalog. All search engines preserve the data in the casing it was inserted.

**Comment by emmaindal** [comment]
Hello @andrewthauer and @Fox32, I've missed this discussion and it came to mind now when a question got asked about this on Discord. Did anyone open a new issue for this? Or is this still a problem that we should look into? Thanks!

**Comment by andrewthauer** [comment]
@emmaindal - No I did not create an issue yet and frankly haven't had a chance to follow up on this or check if it's still an issue in the latest releases. I believe we documented a quick way to reproduce in this thread.

**Comment by jasonhadi** [comment]
I've still got this issue - manually changes the URL to a cased entity eg. `/docs/default/Component` allows search to return results in the TechDocs context document search. Running with the PG search engine. 

```
yarn run v1.22.10
$ /home/jason/code/sre/score-backstage/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.4.72-microsoft-standard-WSL2 - linux/x64
node: v14.17.3
yarn: 1.22.10
cli:  0.9.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.1
  @backstage/backend-common                                0.9.12
  @backstage/catalog-client                                0.5.2
  @backstage/catalog-model                                 0.9.7
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.10.0, 0.9.1
  @backstage/config-loader                                 0.8.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.1.24
  @backstage/core-components                               0.7.6
  @backstage/core-plugin-api                               0.2.2
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.14
  @backstage/integration                                   0.6.10
  @backstage/plugin-api-docs                               0.6.16
  @backstage/plugin-app-backend                            0.3.19
  @backstage/plugin-auth-backend                           0.4.10
  @backstage/plugin-catalog-backend                        0.19.0
  @backstage/plugin-catalog-graph                          0.2.2
  @backstage/plugin-catalog-import                         0.7.4
  @backstage/plugin-catalog-react                          0.6.4
  @backstage/plugin-catalog                                0.7.3
  @backstage/plugin-github-actions                         0.4.25
  @backstage/plugin-org                                    0.3.29
  @backstage/plugin-proxy-backend                          0.2.14
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.5
  @backstage/plugin-scaffolder-backend                     0.15.15
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.13
  @backstage/plugin-search-backend-module-elasticsearch    0.0.5
  @backstage/plugin-search-backend-module-pg               0.2.1
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.7
  @backstage/plugin-search                                 0.5.0
  @backstage/plugin-tech-radar                             0.4.12
  @backstage/plugin-techdocs-backend                       0.11.0
  @backstage/plugin-techdocs                               0.12.8
  @backstage/plugin-user-settings                          0.3.12
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.10.8
  @backstage/test-utils                                    0.1.23
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.0
```

**Comment by emmaindal** [comment]
Thanks @jasonhadi confirming you still see this issue. Can I ask you to open a new issue with the details of your problem and I'll have a closer look at it tomorrow. As this PR is closed it does not get the same visibility.

**Comment by jasonhadi** [comment]
> Thanks @jasonhadi confirming you still see this issue. Can I ask you to open a new issue with the details of your problem and I'll have a closer look at it tomorrow. As this PR is closed it does not get the same visibility.

Done! https://github.com/backstage/backstage/issues/8390 created.

**Pull request merged**
