### PR TITLE
Fix incorrect knex migration logic

### PR DESCRIPTION
**Pull request by DavidZemon**
## Hey, I just made a Pull Request!

Hopefully this PR is pretty obvious. The comment right above this line clearly indicates that we are NOT supposed to attempt column alternations with sqlite, but instead this logic applies _only_ to sqlite databases.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by DavidZemon** [comment]
I don't think this PR needs any tests or changesets updated, but please let me know if that's incorrect.

**Review by freben — APPROVED** [review]
Thanks, good eye! It actually needs a changeset, these get shipped with the package (and therefore affect the runtime). But it's OK, I added one, let's wait for it to go green!

**Comment by freben** [comment]
And after some discussion internally, we realized that this means we'll have to reapply the fix to non-sqlite databases as well, so there's a bit of additional work on top of yours here now. Sorry about the noise, and thanks again for starting this!

**Comment by freben** [comment]
And making a real patch release out of it too :) https://github.com/backstage/backstage/pull/10338

**Comment by DavidZemon** [comment]
Thank you for taking this over! I can recognize that this would have taken a lot longer to coach me through all of the steps of the release process than one you guys just picking it up and adding the necessary polish. You guys were able to get this merged in before I could even get our internal PR patch approved and merged :)

**Pull request closed without merging**
