### PR TITLE
Add Booz Allen Hamilton to adopters list

### PR DESCRIPTION
**Pull request by JasonMiller-BAH**
I added Booz Allen Hamilton's use case to the adopters list.  I also suggest this list be alphabetized, but don't want to overstep by doing so without asking.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hey, happy to see you in the list! Two things are red.

First the style check - the columns are misaligned on the table which makes `prettier` go cranky. You could run `yarn prettier --write ADOPTERS.md` if you have this locally on a dev machine, or I can help out if you like.

Secondly, DCO asks for a signature. The [check link](https://github.com/backstage/backstage/pull/5728/checks?check_run_id=2621476030) has some more info, or you could manually add a line on the following form to your actual commit message:

`Signed-off-by: Your Name <your@email.com>`

Sorry for the noise. Again, let me know if I can help out.

**Comment by JasonMiller-BAH** [comment]
> Hey, happy to see you in the list! Two things are red.
> 
> First the style check - the columns are misaligned on the table which makes `prettier` go cranky. You could run `yarn prettier --write ADOPTERS.md` if you have this locally on a dev machine, or I can help out if you like.
> 
> Secondly, DCO asks for a signature. The [check link](https://github.com/backstage/backstage/pull/5728/checks?check_run_id=2621476030) has some more info, or you could manually add a line on the following form to your actual commit message:
> 
> `Signed-off-by: Your Name <your@email.com>`
> 
> Sorry for the noise. Again, let me know if I can help out.

Sorry, I'm editing this directly on GitHub—this isn't a dev machine and I can't run `prettier`.  I submitted a new commit to both try to satisfy `prettier` (which probably failed) and to add a signature... which I then had to re-do because I pasted the signature template without editing it.  Derp.

No worries about the noise on my end; *I'm* sorry for causing noise for *you*.

**Comment by freben** [comment]
I very rudely did a force push with the layout changes to this pull request - but now DCO disagrees with the signature.

The error message says

```
Expected "JasonMiller-BAH 73496127+JasonMiller-BAH@users.noreply.github.com", but got "Jason Miller miller_jason@bah.com".
```

Bah.

To make it possible to sign with the corporate address, I'm afraid you'd probably have to be configuring a local git to use that email identity. However I think that this is just unnecessary complication and frustration for something that doesn't even touch the code - so I will for now just appease it by choosing the email you committed as (the `73496127+JasonMiller-BAH@users.noreply.github.com` automatically generated identity) and call it a day.

**Comment by JasonMiller-BAH** [comment]
I didn’t realize it wanted my GitHub username, not my actual name; that’s on me, sorry.  Thank you for taking care of this!


--
Jason Miller
Lead Technologist | Sr. Scrum Master
Strategic Innovation Group

M: 917.584.7931 | O: 917.305.8170
***@***.******@***.***>
Charleston, SC

Booz | Allen | Hamilton
BoozAllen.com<http://www.boozallen.com/>

From: Fredrik Adelöw ***@***.***>
Sent: Wednesday, May 19, 2021 1:24 PM
To: backstage/backstage ***@***.***>
Cc: Miller, Jason [USA] ***@***.***>; Author ***@***.***>
Subject: [External] Re: [backstage/backstage] Add Booz Allen Hamilton to adopters list (#5728)


I very rudely did a force push with the layout changes to this pull request - but now DCO disagrees with the signature.

The error message says

Expected "JasonMiller-BAH ***@***.******@***.***>", but got "Jason Miller ***@***.******@***.***>".

Bah.

To make it possible to sign with the corporate address, I'm afraid you'd probably have to be configuring a local git to use that email identity. However I think that this is just unnecessary complication and frustration for something that doesn't even touch the code - so I will for now just appease it by choosing the email you committed as (the ***@***.******@***.***> automatically generated identity) and call it a day.

**Review by freben — APPROVED** [review]

**Pull request merged**
