### PR TITLE
docs: Adopter spotlight about Dynatrace adopting Backstage

### PR DESCRIPTION
**Pull request by johannes-b**
## Hey, I just made a Pull Request!

Dear Backstage community, I would love to get this blog post published on https://backstage.io/blog/ to tell Dynatrace`s story about Backstage. 

### Blog post about Dynatrace adopting and extending Backstage

To enhance the developer experience, Dynatrace adopted Backstage as its central developer portal and enhances Backstage entities with real-time data. This decision, along with the symbiosis between the Dynatrace platform and Backstage, has unlocked two significant opportunities.

* First, centralizing all development-related artifacts and democratizing ownership have reduced onboarding time for our teams.
* Second, we enhanced the developer experience by integrating observability and security data into Backstage, offering seamless entry points to Dynatrace for in-depth analysis.

:point_right: This blog post reveals how and why Dynatrace started to use Backsage. 
:point_right: Additionally, it lays out how Dynatrace extended Backstage to bring real-time data in context of service catalog entities in Backstage.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by johannes-b** [comment]
Hello @freben and @camilaibs :raising_hand:

Yesterday, I created this PR to contribute a blog post to the Backstage blog. I hope this is the right process therefore. :) 
* May I kindly ask you for your support to get this blog post published. 
* Would it be possible to get a Backstage-branded image like in this blog: https://backstage.io/blog/2024/06/27/backstage-engineer-journey

Thanks in advance.

**Comment by freben** [comment]
Alright! Content wise we're happy! Were you still having an ask on hero image or similar, or shall we merge this as is?

**Comment by johannes-b** [comment]
Thanks for the review! 
Correct, I`m wondering how I can get such a nice hero image (those Backstage-branded once) the other blog posts have in place, e.g., The adopter spotlight for CTC (https://backstage.io/blog/2023/09/29/chicago-traiding-company-adopter-spotlight) 

Can some create such an image?

**Comment by freben** [comment]
Alright, we'll look into that and get back to you!

**Comment by AlleyWei** [comment]
com0027 Dynatrace Adopter
@johannes-b here's the image!

**Comment by johannes-b** [comment]
@freben and @AlleyWei many thanks for your help!

I have added the image and fixed an issue with references. 
I would be ready now. Can you approve it?

**Review by freben — APPROVED** [review]
Alright!

**Pull request merged**
