### PR TITLE
feat(home): Show relative time for recent visits from today

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

This PR changes the time display when showing recently visited items to show relative time, even when displaying items which were visited today.  This is an opinionated end-user change, and welcome dialog or disagreement on it.  Adds on to the great work @aitherios did originally, and welcome any background if you recall the history of this.

On the demo site, if you view the custom homepage with the recent visits card, it looks something like this:

image

I had to do a double take, and then check my clock, to make sure if these were recent or not.  (recent in the sense of, I appreciated they were today but I couldn't remember what time is was at first :) )

Personally, I think it would be easier to the end user to show these fully relative if they are today, i.e. "35 minutes ago" or "3 hours ago" as well?  On my local, it now looks like this which I personally prefer:

image

In this way we fully use the Luxon library both for any change prior to today, as well as today, and it also slightly simplifies the code.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by adamdmharvey** [comment]
View from Uffizi:

image

**Comment by adamdmharvey** [comment]
Bump

**Comment by efenner-cambia** [comment]
This change makes sense to me

**Comment by adamdmharvey** [comment]
Another bump on this one; any chance to peek @backstage/discoverability-maintainers ? Thanks! 🙏🏻

**Review by djamaile — APPROVED** [review]

**Review by aitherios — APPROVED** [review]

**Comment by aitherios** [comment]
Thanks @adamdmharvey , looks great =]

**Pull request merged**
