### PR TITLE
16307:Fixed icon url

### PR DESCRIPTION
**Pull request by Sonu875**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by adamdmharvey** [comment]
Definitely fixes the broken image, but TBH not sure it looks the best?  The raw image is a long, wide one which gets squeezed into this plug-ins format.

image

What're your thoughts @Sonu875 ? Is there one which is just the New Relic logo maybe?

**Comment by Sonu875** [comment]
@adamdmharvey  Another image we can use is https://newrelic.com/themes/custom/erno/assets/mediakit/new_relic_logo_vertical.svg 
image

**Comment by freben** [comment]
That does seem better.

Also, remember to DCO sign every commit. See the instructions in the bot comment above :)

**Comment by freben** [comment]
@Sonu875 Need DCO on that one too please! They can be fixed and force-pushed as per the above instructions. We can't for legal reasons accept contributions that aren't signed.

**Pull request closed without merging**
