### PR TITLE
Fix '.set()' quest mode in user settings 

### PR DESCRIPTION
**Pull request by ivangonzalezacuna**
Signed-off-by: ivgo <ivgo@spreadgroup.com>

## Hey, I just made a Pull Request!
While trying to test the newly created `user-settings` plugin, I found out the frontend was making a request to the storage even in guest mode. After checking the code, I found out a `return` was missing.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Makes sense, thank you! 👍 

Are you up for adding a regression test for this as well? Always nice when catching a bug

**Comment by ivangonzalezacuna** [comment]
> Makes sense, thank you! +1
> 
> Are you up for adding a regression test for this as well? Always nice when catching a bug

Currently trying that. At least adding one test to be sure what happens when the `guest` mode is being used

**Comment by ivangonzalezacuna** [comment]
Added a test for the fallback. I hope it's fine enough. I haven't worked with observers before and maybe the test should be done in a different way

**Comment by Rugvip** [comment]
Yep looks good, thanks! 👍

**Pull request merged**
