### PR TITLE
Update roadmap about Backstage Community Sessions

### PR DESCRIPTION
**Pull request by OrkoHunter**
The first Backstage Community Session is next week (Feb 17). See agenda and more details  https://github.com/backstage/community/issues/2

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4426-axbqwh9x7hqqso6eprrqpe9n7qzngdpx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60214cd7353bbb53e0a2a568

**Comment by joaomilho** [comment]
🎉

**Review by adamdmharvey — APPROVED** [review]

**Review by leemills83 — APPROVED** [review]

**Comment by OrkoHunter** [comment]
Small ping @backstage/maintainers :)

**Review by Rugvip — APPROVED** [review]
Small 🟢  :>

**Pull request merged**
