### PR TITLE
Bump react router

### PR DESCRIPTION
**Pull request by freben**
This is actually the work of @bresmith-wayfair, but with an additional fix on top to add the `history` peer dependency in the app.

### CODE REVIEW

**Comment by freben** [comment]
replaces #1475

**Review by Rugvip — APPROVED** [review]
Could skip the bonus commit tho? :grin: Or just squash it when merging

**Comment by freben** [comment]
Haha, yeah ok i guess i cba then, done :)

**Comment by bresmith-wayfair** [comment]
great!  thanks @freben !

**Pull request merged**
