### PR TITLE
Show error on task page if task does not exist

### PR DESCRIPTION
**Pull request by Fox32**
The rest of the code is already designed to handle the error, the response is just not evaluated.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
Nice, approved - would you even have the opportunity to do the same in the other methods? :D

**Comment by Fox32** [comment]
> Nice, approved - would you even have the opportunity to do the same in the other methods? :D

I thought about it for a seconds, but I'm not sure about the impact.

* `getTemplateParameterSchema` is throwing a plain error, changing to `ResponseError` should be fine.
* `scaffold` has special handling, I wouldn't change it to use `response.ok` but throwing a `ResponseError` instead should be safe.
* `streamLogs` is using an observable, so we should skip it.
* `listActions` has no error handling, so adding one would be good. 

Give me a second 😉

**Comment by Fox32** [comment]
Oh no, that will not work for `scaffold()` as the endpoint returns some other error format https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/service/router.ts#L364-L367

I will revert that part but keep the others. I don't want to dig into the backend 😉

**Review by freben — APPROVED** [review]
Understandable. Reapproved!

**Pull request merged**
