### PR TITLE
chore(deps) bump git-url-parse from 11.4.4 to 11.6.0

### PR DESCRIPTION
**Pull request by goober**
Signed-off-by: Mathias Åhsberg <mathias.ahsberg@resurs.se>

## Hey, I just made a Pull Request!

This pull request will upgrade the git-parse-url library to the latest release that includes a fix for a regression when parsing paths located in subfolders. See https://github.com/IonicaBizau/git-url-parse/pull/131

This will also unlock the work on https://github.com/backstage/backstage/issues/6033

I have skipped the changeset since I saw that other dependency upgrades did not have a changeset. Please let me know if I should add a changeset or not.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
@goober Thank you! 👍 

We do actually need a changeset as the bumped version is outside of the current range, meaning that without a changeset to trigger each of these packages to be released, users won't get this update.

If it makes sense we should also unlock the version query to just use a `^` instead of `~`, as that's preferable as long as the dependency in question isn't misbehaving 😅

**Comment by goober** [comment]
Thanks for the info @Rugvip. I have updated the PR accordingly.

**Review by jhaals — APPROVED** [review]
Nice, looks good to me 🌮 👍

**Comment by Rugvip** [comment]
From my understanding this doesn't fix anything that's currently broken right? So we could skip it in todays release and merge it after

**Comment by goober** [comment]
You are correct. merge it after todays release and I can continue the work on the Jenkins issue during the upcoming week

**Review by OrkoHunter — APPROVED** [review]

**Pull request merged**
