### PR TITLE
Plugin Scaffolder-Backend: GitHub Pull Request Action fix

### PR DESCRIPTION
**Pull request by tviaud**
## Hey, I just made a Pull Request!

Fixing the URL submitted to `credentialsProvider` to get a GitHub App installation token + adding documentation for GitHub permissions.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5545-egd1sskd3fifz07qsw54neddbrj3vxi3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608bd9b8a55c9a43b5a5ac28

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5545-egd1sskd3fifz07qsw54neddbrj3vxi3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608bd9b8a55c9a43b5a5ac28

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5545-egd1sskd3fifz07qsw54neddbrj3vxi3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608bd9b8a55c9a43b5a5ac28

**Comment by jhaals** [comment]
Thanks for the PR @tviaud!

This is indeed a problem since owner will be parsed to `github.com/backstage` given `github.com/backstage/foobar`. I wonder if it's worth looking into either requiring or appending a `https` to malformed urls. Something for a separate PR anyway. The current implementation "works" for most since few are using Github apps at this point and the provider will default to the configured token.

**Review by freben — APPROVED** [review]
Yeah this is all slightly awkwardly wired up - but this is probably the right fix at this point without refactoring. Thanks.

**Pull request merged**
