### PR TITLE
Bump `passport-saml` to version 3

### PR DESCRIPTION
**Pull request by freben**
DO NOT MERGE until after September 16th, since it is a breaking change.

Note that this is on top of #7014, and needs to lie waiting for at least two weeks after that one is merged.

### CODE REVIEW

**Comment by benjdlambert** [comment]
Can we merge this now @freben?

**Comment by freben** [comment]
If we are OK to break stability index in the name of security - then yes

**Comment by benjdlambert** [comment]
Is it 2 weeks though? As when this gets released it will have been two weeks right?

**Review by benjdlambert — APPROVED** [review]
🚀

**Pull request merged**
