### PR TITLE
feat: change default icon for unknown entities

### PR DESCRIPTION
**Pull request by dweber019**
## Hey, I just made a Pull Request!

Raised in https://github.com/backstage/backstage/pull/21900.

Here some screenshots of the implementation.
Screen Shot 2023-12-21 at 09 03 06 AM
Screen Shot 2023-12-21 at 09 30 58 AM
Screen Shot 2023-12-21 at 09 31 08 AM
Screen Shot 2023-12-21 at 09 48 15 AM
Screen Shot 2023-12-21 at 09 57 52 AM
Screen Shot 2023-12-21 at 09 58 05 AM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Not for this PR, but thinking that we should drop the double Icon in some of the screenshots :)

**Comment by dweber019** [comment]
I will remove the double icons, they look odd 😉

**Comment by dweber019** [comment]
Updated the entity inspect screens to remove double icons. Now they only use the presentation api.
Screen Shot 2023-12-21 at 14 27 40 PM
Screen Shot 2023-12-21 at 14 28 00 PM

**Review by tudi2d — CHANGES_REQUESTED** [review]
Just a first feedback. I'm curious why you prefer rendering an empty icon with `SVGIcon` rather than conditionally rendering it or returning `null`, when there is no Icon set. Is it because of keeping the type consistend or avoiding breakages in case someone uses those components somewhere else? :)

**Comment by dweber019** [comment]
Thanks @tudi2d 
> Is it because of keeping the type consistend or avoiding breakages in case someone uses those components somewhere else?

Actually both, if someone is using EntityKindIcon it should not break and behave consistent.

**Comment by benjdlambert** [comment]
@dweber019 I think this needs a rebase, we had to make some fixes to mainline branch yesterday and some PR's might have got caught up in the change.

**Comment by dweber019** [comment]
@benjdlambert did the rebase but e2e tests still failing.
Can I do something?

**Comment by benjdlambert** [comment]
@dweber019 yeah we've hit a bit a rough patch with some upstream dependencies breaking our e2e test with some typescript issues - we're thinking about how we can make this a little better. I think that this is looking pretty good - just wanna get some eyes from @backstage/catalog-maintainers.

**Review by alde — APPROVED** [review]
LGTM

**Comment by freben** [comment]
rebased this to see if we can get it merged

**Pull request merged**
