### PR TITLE
Add is TechDocs available

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

This adds a check that can optionally be used in the EntityPage to determine if the entity has the TechDocs annotation.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thank you, looks good! Just needs an update of the API report. There are some instructions if you dig through the logs of the failing CI check, but essentially just run `yarn build:api-report` and commit the result :grin:

**Comment by awanlin** [comment]
API Report has been updated

**Review by Rugvip — APPROVED** [review]
👍, will leave final call whether this makes sense to @backstage/techdocs-core

**Review by camilaibs — APPROVED** [review]

**Comment by awanlin** [comment]
Thank @Rugvip and @camilaibs 🚀

**Pull request merged**
