### PR TITLE
feat: :sparkles: add fields option in useEntityList hook

### PR DESCRIPTION
**Pull request by Nilay1999**
## Hey, I just made a Pull Request!

Ref: https://github.com/backstage/backstage/issues/25927

Add `fields` option in `useEntityList` hook.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Nilay1999** [comment]
Have made useEntityList hook changes according to https://github.com/backstage/backstage/issues/25927

**Review by camilaibs — APPROVED** [review]
Thanks for opening a pull request 🙌🏻 . It seems fine to forward the filter as it is a valid catalog get entities request option. However, I would like to ask @freben's opinion as he has some pagination concerns 🙂 .

**Comment by camilaibs** [comment]
Hi @Nilay1999 could you sync your branch with master, please?

**Comment by Nilay1999** [comment]
@camilaibs sure

**Comment by Nilay1999** [comment]
Apologies for force pushing several times because of api-doc check failure :sweat_smile:.

**Review by vinzscam — CHANGES_REQUESTED** [review]
As I mentioned in #25927, I don't think we will gain much by having this feature, given that we fetch a small number of entities.

**Pull request closed without merging**
