### PR TITLE
[NBS Docs] Updated the Azure and Microsoft Graph Integration Docs

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Updated the Azure and Microsoft Graph Integration Docs with examples using the new backend system

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
Alright! Heads up though that we're generally moving the new backend system stuff to the top or even moving old-system docs to separate hidden pages

**Comment by awanlin** [comment]
I'm fine with following the pattern, will work on updating this PR in that direction 🚀

**Review by Rugvip — APPROVED** [review]
Excellent :ok_hand: 

Let's :shipit: :tada:

**Comment by awanlin** [comment]
YES! Thanks @Rugvip 🚀

**Pull request merged**
