### PR TITLE
Update the authentication setting of proxy

### PR DESCRIPTION
**Pull request by ncattuong**
The auth is used for BASIC authentication (username:password). For token, we need to use Authorization headers.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by dschwank** [comment]
Thanks @ncattuong !

It looks a little bit odd, but the `colon` suffix is actually required to make use of user tokens. Read this from the [Sonarqube docs](https://docs.sonarqube.org/latest/extend/web-api/) :

```
# note that the colon after the token is required in curl to set an empty password 
curl -u THIS_IS_MY_TOKEN: https://sonarqube.com/api/user_tokens/search
```

Can you confirm that @ncattuong ? Or could you link some docs / use cases which you have in mind?

**Comment by ncattuong** [comment]
Thank you @dschwank !
I have checked it and the setting `auth: '${SONARQUBE_TOKEN}:'` is working. I missed the `:` when I configured it. Therefore, I came up with another way to configure it.
The document could be left as is or may be we should add a note that the `:` is required?

**Comment by dschwank** [comment]
> The document could be left as is or may be we should add a note that the : is required?

Improving the docs is always a good idea, so it is more clear for the next person! 👍 If you have time, then feel free to add a line to the docs. Otherwise I will have a look in the afternoon! 😃👍

**Comment by dschwank** [comment]
@ncattuong I just added this small docs updated - is that fine for you? https://github.com/backstage/backstage/pull/8873

**Comment by jhaals** [comment]
Closing this as it looks like it's solved now :) Thanks everyone!

**Pull request closed without merging**
