### PR TITLE
catalog-backend: Drop support for deprecated location types

### PR DESCRIPTION
**Pull request by jhaals**
Signed-off-by: Johan Haals <johan.haals@gmail.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
YAS @jhaals

**Comment by benjdlambert** [comment]
Do you want to create a follow up PR whilst I have it on my mind to make `next` default and remove all the legacy code also if you're feeling in a springcleaning mood 💐

**Comment by jhaals** [comment]
> Do you want to create a follow up PR whilst I have it on my mind to make `next` default and remove all the legacy code also if you're feeling in a springcleaning mood 💐

I was just about to take out the 🧹 and clean before the winter but I just got to my attention that Fox and friends are not upgraded due to lacking support to trigger refreshes. Let's see if we can fix that first and then nuke the old code.

**Comment by benjdlambert** [comment]
OK so in that case maybe we should add this to the board and have a look at taking it over and fixing it up https://github.com/backstage/backstage/pull/6441

**Review by freben — APPROVED** [review]

**Pull request merged**
