### PR TITLE
[Catalog] Location url was incorrect in tests

### PR DESCRIPTION
**Pull request by taras**
## Hey, I just made a Pull Request!

It was brought to my attention that my test examples were incorrect. Actual validation was always failing because location has to be in url location format with `url:` prefix.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
So just so I understand this a little more, this still works because the validation isn't run and we're mocking that out or? Or am i missing something?

**Comment by taras** [comment]
Yes, it works because we're mocking out the actually validation. If someone uses these tests as a reference, they'll get the wrong idea about the payload they must use.

**Review by Rugvip — APPROVED** [review]
Thanks! 👍 

I think we should update the catalog client docs as well? It currently calls it "URL location", probably better to have it be `locationRef: string` and call it a location ref

**Comment by taras** [comment]
@Rugvip I changed the argument name to locationRef, updated the typedoc and rebased.

**Review by benjdlambert — APPROVED** [review]
Thanks 👍

**Pull request merged**
