### PR TITLE
update docker.md to add git

### PR DESCRIPTION
**Pull request by freben**
Replaces #20836 (see discussion there for rationale)

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
We'd also need to copy over `.git` as well for this to be useful right? Not sure we wanna do that btw

**Comment by freben** [comment]
Hm not sure about that. In theory yes but 🤔 I think this is only used to `git rev-parse HEAD` etc to inspect the current repo state.

**Review by awanlin — APPROVED** [review]

**Comment by freben** [comment]
Yeah indeed, silencing the warning is an option. Maybe even permanently for everyone, instead of somehow detecting when to warn and not to?

Am I right in understanding that this basically only is useful for showing the current build info in the frontend or whatnot? Then maybe we can devise other ways of passing that through in these corner cases ... like through the env passed into the build or whatever. Closing this anyway

**Comment by Rugvip** [comment]
Yep thinking it might make sense to completely remove the warning tbh

**Pull request closed without merging**
