### PR TITLE
TechDocs: Pass user and group ID when invoking docker container

### PR DESCRIPTION
**Pull request by OrkoHunter**
When TechDocs invokes Docker, docker could be run as a `root` user which results in generation of files by applications run by non-root user (e.g. TechDocs) will not have access to modify. This PR passes in current user and group ID to docker so that the file permissions of the generated files and folders are correct.

Literally copy pasted from scaffolder. To be replaced very soon by a utility function from @backstage/backend-common https://github.com/backstage/backstage/issues/4560

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@adamdmharvey When you find time, please let us know if this solves your problem? 🙏

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4562-nwxxooausqsd0ta8qpoaiqovflsgoxfc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602d0f32fcb22dc3eb57b48a

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4562-nwxxooausqsd0ta8qpoaiqovflsgoxfc.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602d0f32fcb22dc3eb57b48a

**Comment by OrkoHunter** [comment]
Affirmation of fix by @ebarriosjr in Discord https://discord.com/channels/687207715902193673/687235481154617364/811635306000023593

**Comment by ebarriosjr** [comment]
This solves the issue for me. :+1:

**Review by iamEAP — APPROVED** [review]

**Comment by adamdmharvey** [comment]
Also fixed for me! 🎉 🎉 🎉 cheers @OrkoHunter

**Pull request merged**
