### PR TITLE
Index openapi specs for search

### PR DESCRIPTION
**Pull request by Irma12**
Signed-off-by: irma12 <irma@roadie.io>

## Hey, I just made a Pull Request!

At the moment one is not able to search through APIs using endpoint, in order to find one which contains that endpoint. With this we would be able to expose that.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hm. I'm not sure it's a good idea to bake this into the default collation, for everybody. My gut tells me that these are full of textual data that will severely pollute search results. This most likely deserves a separate collator of its own and dedicated handling (maybe a distinct user intent / tab in search, separate weighting ...)

Ping @emmaindal @iamEAP

**Comment by emmaindal** [comment]
> This most likely deserves a separate collator of its own and dedicated handling (maybe a distinct user intent / tab in search, separate weighting ...)

@Irma12 @freben what do you think about creating this as a separate [decorator](https://backstage.io/docs/features/search/concepts#decorators)? that adopters can use if wanted? So its a CatalogDecorator which can decorate the documents with the api spec?

**Comment by iamEAP** [comment]
Hmm...  I guess it's a bit nicer in that it's more configurable as a decorator, but it still feels a little bit like a foot-gun (as freben implied).  An API definition may not even be human readable (could be JSON, could be a proto definition, or even just straight up code).  ...Could have very weird effects on the whole catalog index depending on how the search engine splits apart "words" and what effect that has on term frequency for ranking, etc.

Like freben, I wonder if it's its own collator, and perhaps the text entered varies per type of API...  Something that boils it down to something almost human readable, or at least something that strips it down to just the important keywords (method names, endpoint path parts, parameter names, etc)

**Review by Rugvip — CHANGES_REQUESTED** [review]
@Irma12 what are your thoughts on the way forward, separate collator that is able to refine the text a bit? Is it specifically endpoints that you're interested in searching, in that case perhaps something that achieves just that for some known API types?

I agree with the above concerns that this is too risky to ship as default, and probably even as an option.

**Comment by Irma12** [comment]
> @Irma12 what are your thoughts on the way forward, separate collator that is able to refine the text a bit? Is it specifically endpoints that you're interested in searching, in that case perhaps something that achieves just that for some known API types?
> 
> I agree with the above concerns that this is too risky to ship as default, and probably even as an option.

I do see its downsides, I was mostly aiming at  endpoints though, but valid point of not shipping it as default. Will rework a bit and add some collators and update PR accordingly

**Pull request closed without merging**
