### PR TITLE
Bump Helmet to 6.0.0

### PR DESCRIPTION
**Pull request by stefanalund**
#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by shmidt-i — APPROVED** [review]

**Comment by shmidt-i** [comment]
The only thing here is maybe have an ADR in place to wait for the patch version after major release of the packages for the future bumps?

**Comment by stefanalund** [comment]
@shmidt-i tests are failing. Any suggestions? 

Feels like it could be related to this no longer working as expected:

```ts
jest.mock('react-helmet', () => {
  return ({ defaultTitle }: any) => <div>defaultTitle: {defaultTitle}</div>;
});
```

Error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
          in Unknown
          in ThemeProvider
          in Wrapper (created by Context.Consumer)
          in Route
          in Router (created by MemoryRouter)
          in MemoryRouter

      173 |   return (
      174 |     <Fragment>
    > 175 |       <Helmet titleTemplate={titleTemplate} defaultTitle={defaultTitle} />
          |       ^
      176 |       <Theme.Consumer>
      177 |         {theme => (
      178 |           <header style={style} className={classes.header}>
```

**Comment by Nek** [comment]
Could be as simple as this:
``` javascript
//There is no longer a default export:
//use
import { Helmet } from "react-helmet"
//instead of
import Helmet from "react-helmet"
```

https://github.com/nfl/react-helmet/wiki/Upgrade-from-5.x.x----6.x.x-beta

**Comment by stefanalund** [comment]
@Nek I've added those changes.

**Comment by Nek** [comment]
I'll give it a try.

**Comment by shmidt-i** [comment]
Yeah, but I think needs to be changed as well ```
jest.mock('react-helmet', () => ({ Helmet: ({ defaultTitle }: any) => <div>defaultTitle: {defaultTitle}</div>
});
```

**Pull request merged**
