### PR TITLE
Hacky kubernetes pod metrics in Kubernetes UI

### PR DESCRIPTION
**Pull request by mclarke47**
## Display Pod metrics from the metrics API in the Kubernetes Plugin

This was a hack I was experimenting with and it turns out it is possible with a few implementation caveats which aren't ideal but we can probably manage.

Screenshot 2021-09-18 at 15 29 18

### Problems

* The nodejs Kubernetes client doesn't support the metrics API(https://github.com/kubernetes-client/javascript/pull/415)
  * **solution**: write our own client for now, replace it when the node client does support it
* There is limited filtering in the metrics API (I think just namespace)
  * **solution**: namespace scoped clients (https://github.com/backstage/backstage/issues/4810), or aysnc lookup of all the metrics on a cluster and we can filter in `kubernetes-backend`
* I don't think you're really supposed to use the metrics server for non-autoscaling [it says in the README](https://github.com/kubernetes-sigs/metrics-server#kubernetes-metrics-server)
  * **solution**: maybe just asterix the metrics in the UI by saying they are approximate 🤷 

This needs lots of refactoring and tests before it is ready to be merged.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by mclarke47** [comment]
Still working on the kubernetes client changes, see https://github.com/kubernetes-client/javascript/issues/719 for more details

**Comment by adamdmharvey** [comment]
Note, seems the relevant git tags which included your contribs do exist, Matt, there's just no "GitHub Release" but there are related sever-aligned git tags it seems?  Your last work on this may thus be at least PARTIALLY unblocked, not 100% tho.

https://github.com/kubernetes-client/javascript/issues/740

**Comment by mclarke47** [comment]
Yes, the new version of the library is out. I just need some time to finish this up 😂

**Comment by mclarke47** [comment]
Closed in favour of https://github.com/backstage/backstage/pull/8248

**Pull request closed without merging**
