### PR TITLE
Updated Prometheus and OpenTelemetry Guides

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Updated Prometheus guide to note the metrics have been deprecated and to use the OpenTelemetry guide instead.

Updated the OpenTelemetry guide to list all the currently available metrics.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @SonilPro, not a big change here but wanted your feedback on this when you have time, please?

**Review by freben — APPROVED** [review]
🥳

**Comment by kim-tsao** [comment]
Hi @awanlin, are there plans to migrate the scaffolder and catalog metrics to use OpenTelemetry?  I believe they are still dependent on the deprecated `prom-client`

**Comment by awanlin** [comment]
Hi @kim-tsao, they were just added and merged today and will be part of the `1.30.0` release next week - https://github.com/backstage/backstage/pull/26020. That's part of why I submitted this PR. 👍

**Comment by SonilPro** [comment]
> Hi @SonilPro, not a big change here but wanted your feedback on this when you have time, please?
@awanlin Was on vacation, sorry. Looks good however.

**Comment by awanlin** [comment]
No worries @SonilPro, thanks for follow ing up and hope you had a good vacation! 🚀

**Pull request merged**
