### PR TITLE
Add GitHub pull requests plugin

### LINKED ISSUE #1808: Github open pull request count widget
## Feature Suggestion

Show the count of open pull requests for a repository (maybe even a breakdown with open/closed as well)

## Possible Implementation

A new annotation will likely be needed,
something like:

```
backstage.io/github-repo-slug: timja-org/my-repo
```

## Context

Surface more information in backstage, along with healthy repo indicators, i.e. less open PRs is better.

### PR DESCRIPTION
**Pull request by dtuite**
See pull requests against your entities/services, and see statistics for your last N pull requests.

For now, everything is available on `/github-pull-requests`. We will move the CI table to the tabs on the entities page once a tabs implementation is merged. We will also move the statistics widget to the overview page.

[Code here.](https://github.com/RoadieHQ/backstage-plugin-github-pull-requests) The readme will be updated with install instructions today.

Screenshot 2020-08-17 at 15 09 49

Closes #1808

### CODE REVIEW

**Comment by bih** [comment]
This would be SO awesome to have even internally at Spotify!

**Review by stefanalund — APPROVED** [review]
Needs rebasing, but 👍

**Comment by stefanalund** [comment]
I would love to see this plugin connecting to the Service Catalog once we sort out the tabs properly.

**Comment by dtuite** [comment]
> I would love to see this plugin connecting to the Service Catalog once we sort out the tabs properly.

That's exactly the plan.

**Comment by dtuite** [comment]
@stefanalund Rebase complete. Should be good to go once the checks run.

**Comment by dtuite** [comment]
Btw, I would love to link from PRs to the GitHub actions plugin and vice versa in the future if we can figure out how to do that.

**Comment by timja** [comment]
> I would love to see this plugin connecting to the Service Catalog once we sort out the tabs properly.

Wasn't tabs sorted in the docs PR?

**Comment by freben** [comment]
Partially - it's work in progress to get deep links sorted properly etc.

**Comment by vdevishri07** [comment]
@dtuite, will this plugin also work for Bitbucket PRs?

**Pull request merged**
