### PR TITLE
docs(openapi): document JAVA requirement for client generation

### PR DESCRIPTION
**Pull request by secustor**
## Hey, I just made a Pull Request!
Document the need for JAVA on shell PATH, for generating clients using OPENAPI tooling. 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@aramissennyeydd :eyes:

**Review by aramissennyeydd — APPROVED** [review]
🙇 good catch! We discussed this a little bit in the original issue, but I missed adding it to the documentation.

**Comment by secustor** [comment]
Bump. As this has no code changes I think it is ready for merge.

**Review by freben — APPROVED** [review]
Aight!

**Pull request merged**
