### PR TITLE
Allow relative backend.baseUrl at webpack build time.

### PR DESCRIPTION
**Pull request by ara6893**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

For: #13872

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thank you for the suggestion! 👍 

I feel it's a bit dangerous to encourage keeping a relative `backend.baseUrl` in config, as the full external URL is needed for the backend itself. The other option is temporary or slim frontend-only configs, which I don't feel is a nice pattern.

I've been considering whether we should add both a `--public-url` and `--backend-url` option to the CLI app build. With that we'd allow both of them to be relative URLs, and they would override whatever is in config so that it's ignored. You can then potentially do separate build scripts or just throw on extra args in CI for different environments if needed. What do you think about that direction?

**Comment by ara6893** [comment]
Thanks for the quick response!

> I've been considering whether we should add both a --public-url and --backend-url option to the CLI app build. With that we'd allow both of them to be relative URLs, and they would override whatever is in config so that it's ignored. You can then potentially do separate build scripts or just throw on extra args in CI for different environments if needed. What do you think about that direction?
What would the `backend-url` usage look like? I'd want to use it like `yarn build --backend-url /api` or `yarn build --backend-url /`. 
Why would we need public url? Shouldn't we be pulling that from document.location.origin?

**Comment by Rugvip** [comment]
@ara6893 Yep, exactly that. The public URL is important if hosted under a path. Tbh it should probably be `--public-path` instead. So for example `https://mycompany.com/backstage`

**Comment by ara6893** [comment]
@Rugvip Gotcha, that makes sense to me. Is this something that I could take a stab at? This is a blocker for my team using/testing Backstage in pre-prod environments.

**Comment by Rugvip** [comment]
@ara6893 Sure, would be great! Let me know if there's anything else to clear up or help out with

**Comment by ara6893** [comment]
@Rugvip Sorry, got pulled into something else. I took a look at it and had a few questions/requests for pointers.
1. Should this be a repo or script level command? I would think repo level but we can support multiple backends and front ends.
2. I'm guessing this is going to need to touch app-backend and cli, is there anywhere else you can think of?
3. Should this only be supported for ejected front ends/during build? Or should we support hot module reloading as well? (I would probably need more help if we supported module loading.)

**Comment by ara6893** [comment]
Opened #13927 to handle the new CLI options we spoke about.

**Pull request closed without merging**
