### PR TITLE
Add missing reader property

### PR DESCRIPTION
**Pull request by jmezach**
As discussed in #14831 this is needed for the README.md feature to work properly

Signed-off-by: Jonathan Mezach <jonathan.mezach@rr-wfm.com>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — CHANGES_REQUESTED** [review]
Thanks for the fix!
To make the readme update show up on npm this change also need a `patch` changeset saying `Updated installation documentation`. You can generate one with `yarn changeset`. The change is not formated correctly currently, you can run `yarn prettier` to format the file.

**Comment by jmezach** [comment]
@jhaals I've made the request changed.

**Review by jhaals — APPROVED** [review]
Thank you 👏

**Comment by awanlin** [comment]
Many thanks @jmezach @jhaals 🚀

**Pull request merged**
