### PR TITLE
Updated Software Template docs with New Backend System examples

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Updated Software Templates docs with New Backend System examples

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
As I made this PR it just dawned on me that I could just update the docs with steps on how to add this. I'll let the maintainers review this and give me feedback on the right way forward 👍

**Comment by benjdlambert** [comment]
@awanlin I'm thinking that it's going to be more beneficial to update the docs a little bit, with some info and how to install the module and add it, rather than defaulting this to be installed. It's just more work to clean up for end users, and adding this to documentation makes it a little clearer on how to install other modules too.

What do you think?

**Comment by awanlin** [comment]
Hi @benjdlambert, I'm fine with that. I'll refactor this PR in that direction, might take me a few days to get to it though 👍

**Review by aramissennyeydd — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice :tada: thanks @awanlin!

**Comment by awanlin** [comment]
Thanks @benjdlambert and @aramissennyeydd 🚀

**Pull request merged**
