### PR TITLE
add support for React 17 in plugins

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

This is work towards #6910, it's the first out of two steps to migrate. This steps allows plugin integrators to select whether they want the app to be running on React 16 or 17, as plugins now allow both.

The next step of the migration is to move over to using React 17 by default in apps, which we can do once these plugin changes are rolled out more broadly (👋 @dtuite :grin:). It's not until that point that we'll actually be using React 17.

The main change to make this migration smooth is to move the React dependencies to `peerDependencies`, which makes it so that it's up to the app to select the React version to use.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
Oooh nice! Also, that `act` thing has been confusing for some time, good

**Comment by jhaals** [comment]
nice

**Comment by dtuite** [comment]
Thanks for the ping. I've shared this with the team and we'll make some space on tbe roadmap to upgrade.

**Comment by jhaals** [comment]
@backstage/techdocs-core would love to get your 👀/review on this :)

**Review by emmaindal — APPROVED** [review]

**Pull request merged**
