### PR TITLE
Fixing incorrect path in the custom action example

### PR DESCRIPTION
**Pull request by worldtiki**
## Hey, I just made a Pull Request!

Fixing incorrect path in import in the custom action example.

#### :heavy_check_mark: Checklist

- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by OrkoHunter — COMMENTED** [review]
Umm, is this right? Looking at the [docs](https://backstage.io/docs/features/software-templates/writing-custom-actions#writing-your-custom-action) it seems like both the files are inside `packages/backend/src/plugins/scaffolder` directory.

**Comment by worldtiki** [comment]
> docs

I guess that's also incorrect then. See [here](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/packages/backend/src/plugins/scaffolder.ts)

**Review by Rugvip — APPROVED** [review]
Yep, thanks! 👍 

I think it can be discussed whether this is the file layout we want to encourage, but let's have the example be correct at least 😁

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻

**Pull request merged**
