### PR TITLE
chore: add new QS filters to GET v2/tasks endpoint

### PR DESCRIPTION
**Pull request by digogid**
## Hey, I just made a Pull Request!

Added the hability to list tasks for three new filters (`createdAt`, `lastHeartbeatAt` and `status`) on query string.
To give more details, the endpoint will search for tasks `createdAt > {param}`, `lastHeaartbeatAt > {param}`or `status = {param}`.
In query string the values for `createdAt` and `lastHeartbeatAt` must be a timestamp.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages.
- [ ] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message.

### CODE REVIEW

**Comment by freben** [comment]
What's the goal of this in the end?

Reason I'm asking is, the more we directly expose of internals (like the heartbeat), the harder it gets to evolve them. Maybe we want to rewrite how that stuff works entirely some day.

**Comment by digogid** [comment]
We add this so we can do some metrics about the tasks that get stuck in the middle of scaffolding process.

**Comment by awanlin** [comment]
@digogid, would it then make more sense to have these as OpenTelemetry metrics like what was done with the Catalog (https://github.com/backstage/backstage/pull/15145), then could be exported to be used by tools like Prometheus (https://github.com/backstage/backstage/pull/18000) and then displayed in something like Grafana?

**Comment by digogid** [comment]
I don't know if this is the same thing we want to achieve.
Can you help me get there, please?

As I understand from the issues, opentelemetry and prometheus only gather "general" information about tasks and resources.
We want to check how many tasks got stuck, in which step and for how long. So we need to check each task.
And from what I understood, those plugins do not address this type of data. Or am I wrong?

**Comment by benjdlambert** [comment]
@digogid I think I'm leaning probably leaning to an approach where we can do similar to what @awanlin is suggesting. OpenTelemetry and being able to add tracing for these things sounds like we would get much more benefit out of the overall addition as it's not just going to solve one use case. You can use it to trace what steps get stuck, and how long they take, but with tracing you can also do so much more to link these actions to outgoing requests for instance, and see if it's upstream services that are throwing errors or what not.

Alternatively, with the new Backend System, it will be possible for you to write a module which you can run alongside your own code that can provide this functionality using the raw DB and adding a route to the scaffolder router to fulfil your own purpose. Similar to how the [unprocess entities module](https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-unprocessed) works for the Catalog.

You can query the db yourself in that module to surface this data how you like, but it's probably not something that we would add to the tasks interface here as @freben mentions it's leaking implementation details out to the API. 

Maybe we could also consider dropping the `lastHeartbeatAt` and that could perhaps be fine, but maybe that doesn't solve all of your use case?

**Pull request closed without merging**
