### PR TITLE
Revert "chore(deps): bump @material-table/core from 3.1.0 to 4.3.19"

### PR DESCRIPTION
**Pull request by Rugvip**
Turns out that's a nope for now

### CODE REVIEW

**Review by mufaddal7 — COMMENTED** [review]
Would it be wise to shift to MUI Core v5.0 gradually?

**Comment by freben** [comment]
See https://github.com/backstage/backstage/issues/7094 for some details

**Review by freben — APPROVED** [review]

**Review by jhaals — APPROVED** [review]

**Comment by webark** [comment]
> Turns out that's a nope for now

@Rugvip what was the issue that came up for it to be a "nope for now"?

**Comment by Rugvip** [comment]
@webark not sure tbh

**Comment by webark** [comment]
Ahh. Ok. We just got around to customizing our catalog index and were going to be looking into seeing if we could help identify some table performance improvements soon. So was curious as to that.

**Comment by freben** [comment]
Sounds great though - there's for sure some room for improvement regarding speed. Let us know how it goes!

**Pull request merged**
