### PR TITLE
Fix support for cookies bigger than 4KB in size in plugin-auth-node

### PR DESCRIPTION
**Pull request by allegro-dbargowski**
## Hey, I just made a Pull Request!

Browsers silently drop cookies that exceed 4KB, which can be problematic for refresh tokens and other large cookies. This pull request ensures that large cookies, like refresh tokens, are not dropped by browsers, maintaining the integrity of the authentication process. The changes include both the implementation of the cookie splitting logic and corresponding tests to validate the new functionality.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by allegro-dbargowski** [comment]
This pull request is an alternative solution to a problem described in [this](https://github.com/backstage/backstage/pull/25529) pull request.

**Comment by allegro-dbargowski** [comment]
hey, @Rugvip @camilaibs - could we get an estimate when we could get feedback/review of this solution? Much appreciated.

**Comment by adminy** [comment]
Rather than slicing 4k characters. wouldn't it be better if we hashed it and the client had the hash as a lookup to the real refresh token?

**Comment by allegro-dbargowski** [comment]
@adminy 
> Rather than slicing 4k characters. wouldn't it be better if we hashed it and the client had the hash as a lookup to the real refresh token? Then local storage could store the refresh token.

It certainly would work - but in my opinion it's better to store refresh token (chunked or not) as an HttpOnly cookie as it is safer (localStorage can be accessed via javascript (i.e. XSS) - but HttpOnly cookie cannot). It also would require a lot more changes to achieve that (frontend auth code or perhaps the whole current auth flow would need to be modified) - what I'm aiming to do with this PR is to produce a small fix for situation that we've encountered in our organization (currently we had to fork entire `plugin-auth-node` package to introduce similar fix - it's not a feasible long term approach).

**Comment by adminy** [comment]
your PR looks great to me! I hope someone on the backstage team takes a look soon.

**Comment by bsiedleckiallegro** [comment]
Hey @Rugvip @camilaibs! Could we get some rough estimate on when we can expect some actions from your side on this pull request? While this is rather critical for us and our organisation, we would highly appreciate any input so we can plan future work and potentially move forward with our project.

Thanks in advance!

**Review by deejay1 — APPROVED** [review]

**Review by bgalek — APPROVED** [review]

**Comment by bgalek** [comment]
@benjdlambert could you take a look? :)

**Comment by freben** [comment]
For anyone following along: We had a chat on discord about some of the details here. It's unfortunate that the upstream service in this case is causing undesired complexity by generating "unreasonably" (for some definition of the word) large tokens. But, it's also true to say that the Backstage framework chose to put third party data in cookies instead of a separate session store, and didn't handle scaling up to larger data sizes because of that choice. So us handling those larger data points for _any_ reason (for example a large number of custom scopes being granted, or so), is not necessarily a bad thing. It's an internal concern of ours, and it has a bug/limitation. So we'll have to choose whether we accept to have that limitation and cut off some integration abilities (to save on complexity), or to accept this change, or switch to a different less limited session data store.

Added to the board for discussion with the team.

**Review by jandrzejczak — APPROVED** [review]

**Comment by deejay1** [comment]
anyone?

**Review by adowsky — APPROVED** [review]

**Review by marcin-biernacki — APPROVED** [review]

**Comment by bsiedleckiallegro** [comment]
Hey backstage team! @Rugvip @camilaibs @freben , while we are struggling with forked auth-node plugin for almost 10 weeks now, it seems like there has been no progress in this PR. Could you please take a moment to review those changes? They make absolutely no harm to the existing ecosystem, but make it viable for all users to authenticate with no issues :)

**Comment by allegro-dbargowski** [comment]
To build on what @bsiedleckiallegro wrote: even if you choose to switch to a different (less limited) session data store in the future (as per @freben comment) changes in this PR are (in my opinion) acceptable stopgap solution for fixing some of edge cases. And while it's true that they introduce a bit of additional complexity - for 99% cases this implementation behaves exactly like old one would.

**Review by Rugvip — APPROVED** [review]
Alright, thank you! 👍 

Gonna go ahead and ship this, since while this isn't great (the solution, implementation looks solid), we're not seeing any other path forward to fix this in the short term.

**Pull request merged**
