### PR TITLE
Switch md5 to sha256

### PR DESCRIPTION
**Pull request by szubster**
For FIPS compliance

## Hey, I just made a Pull Request!

This can have side-effect of invalidating cache entries with keys >250 characters.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by szubster** [comment]
E2E seem to be unrelated to the change.
Same cause as [here](https://github.com/backstage/backstage/pull/21804#issuecomment-1851992144)

**Comment by freben** [comment]
Yeah the errors are not your fault. The verification one can be solved with a rebase on fresh master. Marked it as needing discussion because I want to be sure that it doesn't have any unintended side effects

**Comment by szubster** [comment]
> Yeah the errors are not your fault. The verification one can be solved with a rebase on fresh master.

Rebase did not help

>Let's ship it after the next main-line release though, which is tomorrow. Especially the cache change we'd like to not ship straight into main-line.

Awesome :)

**Comment by freben** [comment]
It did help with the CI/Verify errors! But the e2e ones remain because those are different.

**Review by freben — APPROVED** [review]

**Pull request merged**
