### PR TITLE
Added validations to feedbackform dislike popup page

### PR DESCRIPTION
**Pull request by AmbrishRamachandiran**
## Hey, I just made a Pull Request!

This PR is for https://github.com/backstage/backstage/pull/18666  
ISSUE https://github.com/backstage/backstage/issues/18661
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by AmbrishRamachandiran** [comment]
@kuangp This PR is for https://github.com/backstage/backstage/pull/18666

As per your suggestions i have made the changes please review 

Feature link :  https://github.com/backstage/backstage/issues/18661

**Review by kuangp — CHANGES_REQUESTED** [review]
I think I may need to clarify my comments from the previous PR - 

I see two issues with this change:

- I don't think validation should be mandatory. Not every consumer of this plugin may want validation enforced in this dialog and the current behavior doesn't include any so we don't want to break current consumers unless we provide a way to opt in/out of the changed behavior. Therefore, it's recommended to implement this in a way that validation can be enabled/disabled as desired.
- We can't rely on the "other' response being defined. A consumer is free to pass in whatever feedback responses they want to appear in this dialog and this might be different from the `defaultFeedbackResponses` ie. it might not have an 'other' option. We can't force this option in either if it doesn't exist since that's not what the consumer wants and so we can't hide/show the "Additional comments" textbox based on this option. A consumer might not want the "other" option but still want to show the "Additional comments" textbox. Unfortunately, for more complex UI/UX customization like this, it might be better to fork this dialog instead if it can't be implemented in a generic way

**Comment by AmbrishRamachandiran** [comment]
@kuangp Did following changes
1.Kept validations optional
2.Handling other response possiblty

**Review by kuangp — CHANGES_REQUESTED** [review]
It looks like there are unrelated changes in this PR? I think something might've went wrong with rebasing ?

**Pull request closed without merging**
