### PR TITLE
fixed gapi types

### PR DESCRIPTION
**Pull request by alexrybch**
Signed-off-by: Alex Rybchenko <arybchenko@box.com>

## Hey, I just made a Pull Request!

In this PR @types/gapi moved from devDependencies to dependencies as they are exported.
Related to #10508  

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by szubster** [comment]
@freben @benjdlambert Can you help with CODEOWNERS? I would like to approve the PR, but I cannot do it.

Here is some GH help: https://github.community/t/is-there-any-way-to-add-people-that-dont-have-write-permissions-fo-the-repository-as-codeowners/2015

**Comment by szubster** [comment]
Also, we would like your advice on the build failure. If we do not move the dependencies, `tsc:full` on user apps fails. If we move them, CI on backstage fails.

**Comment by szubster** [comment]
@freben @Rugvip @benjdlambert Pinging for help :)

**Comment by szubster** [comment]
I think I have figured out what is happening.
The script allows `@types/*` packages that are also present in `dist/index.d.ts`.
This is not the case for `gapi` types. At least not directly.
`gapi.calendar.client` has only reference to an external package with types: `@maxim_mazurok/gapi.client.calendar`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gapi.client.calendar/index.d.ts#L12
which is a dependency of `@types/gapi.calendar.client`
The types package is not mentioned in api report or d.ts file, but `@maxim_mazurok` package. 

@Rugvip as a main auth of check-type-dependencies.js do you think it is possible to extend logic and include dpenedencies of `@types` package in the check? Or should we copy the types to the plugin directly, instead of depending on npm package??

**Comment by Rugvip** [comment]
Created https://github.com/backstage/backstage/pull/10693 to help out here. Once that's in it should be possible to express this in a safe way. You'll need to reference the `@maxim_mazurok/gapi.client.calendar` types directly though

**Comment by Rugvip** [comment]
With #10693 merged it should be possible to move this forward now 🎉

**Comment by benjdlambert** [comment]
@Rugvip is this what you meant by referencing the types directly?

**Comment by Rugvip** [comment]
This incorrectly passing atm 😅 , #10997 should fix that

**Comment by alexrybch** [comment]
I missed last commits before push, so reverted my changes (it's about my last 2 pushes :) )
@benjdlambert thanks for looking into!

**Comment by Rugvip** [comment]
The type deps checking script needs some more work, so let's just get this in shape without that for now. The way it should be afaik is to remove any of the gapi type deps, and add `@maxim_mazurok/gapi.client.calendar` as a dependency.

**Review by Rugvip — APPROVED** [review]
👍

**Comment by jhaals** [comment]
Thank you!

**Comment by jhaals** [comment]
Thank you!

**Pull request merged**
