### PR TITLE
feat(techdocs-backend): adds a Publish Strategy

### PR DESCRIPTION
**Pull request by amadkinnon**
This feature will allow customization of the techdocs publishing location

## Hey, I just made a Pull Request!

This allows users to override the default publishing location. 
Uses the same pattern as the DocsBuildStrategy.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by agentbellnorm** [comment]
Hey @amadkinnon, thanks for the contribution! For my understanding, can you describe your use case a bit?

I also have a couple of questions:
- Is the idea that the metadata endpoint can be used as a source of truth to determine the path of where to publish something, at the time of publishing (with e.g. `techdocs-cli`)?
- Do you see any risks with having a non-trivial path to the files, having to always query the backend to know where the files are located?
- When I first saw the name `publishStrategy`, I thought it was something related to the actual uploading of files. Do you think something like `publishLocationStrategy` or `publishLocationProvider` would be less ambigous?

**Comment by amadkinnon** [comment]
> Hey @amadkinnon, thanks for the contribution! For my understanding, can you describe your use case a bit?
> 
For our implemenation of techdocs, we are publishing to an awsS3 bucket from our github CI workflow. The security for this is handled by OIDC. In [order to harden](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token) the request we are using the repository name (from the OIDC token) to ensure this specific workflow runner can only write to its own path eg. `<namespace>/<kind>/<reponame>` (as opposed to `<namespace>/<kind>/<name>`. Our issue arises when the `entity.metadata.name != reponame`. So this solution allows us to override the _techdocs only_ metadata to create the custom triplet.
> I also have a couple of questions:
> 
> * Is the idea that the metadata endpoint can be used as a source of truth to determine the path of where to publish something, at the time of publishing (with e.g. `techdocs-cli`)?

Not exactly, this would simply allow overrides to resolve the _final location_, The idea is that a custom publish location can be implemented using the data provided by the `alternateName` config. Though I'm not sure if `alternateName` is a great key.
`techdocs-cli` takes the publishing location as an argument and would not be affected by this change.

> * Do you see any risks with having a non-trivial path to the files, having to always query the backend to know where the files are located?

This doesn't change any retrieval logic other than a modification of the returned triplet, so I'm not sure what you mean? i.e. The metadata is fetched regardless of this change.

> * When I first saw the name `publishStrategy`, I thought it was something related to the actual uploading of files. Do you think something like `publishLocationStrategy` or `publishLocationProvider` would be less ambigous?

Yes, that may be better. I was initially trying to mimic the `Build` Strategy shape.

**Comment by agentbellnorm** [comment]
Hey @amadkinnon, thanks for the explanation! We've discussed a bit internally and here are a couple of points that when all taken into consideration make me think that this is not a capability we should enable:
- The [search techdocs collator](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/search/DefaultTechDocsCollator.ts#L195-L200) assumes a 1:1 relationship between the entity triplet and the location of the files
- The [techdocs permission implementation](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/service/router.ts#L265-L285) assumes that the entity triplet it receives exists in the catalog
- Future implementations in other plugins cannot assume the 1:1 relationship between files and entities.
- The techdocs frontend cannot assume that the entity triplet in the metadata context exists in the catalog.

Have you considered any alternative solutions to your problem?

**Comment by amadkinnon** [comment]
> Hey @amadkinnon, thanks for the explanation! We've discussed a bit internally and here are a couple of points that when all taken into consideration make me think that this is not a capability we should enable:
> 
> * The [search techdocs collator](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/search/DefaultTechDocsCollator.ts#L195-L200) assumes a 1:1 relationship between the entity triplet and the location of the files
> * The [techdocs permission implementation](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/service/router.ts#L265-L285) assumes that the entity triplet it receives exists in the catalog
> * Future implementations in other plugins cannot assume the 1:1 relationship between files and entities.
> * The techdocs frontend cannot assume that the entity triplet in the metadata context exists in the catalog.
> 
> Have you considered any alternative solutions to your problem?

Thanks for the feedback, I missed the dependencies due to both the before and after entity name existing in my env. I'll investigate alternate solutions.

**Pull request closed without merging**
