### PR TITLE
chore: fullcreen -> fullscreen

### LINKED ISSUE #4144: Spelling mistake: Fullcreen instead of Fullscreen
I'm trying to set up an instance of Backstage, and when invoking the Job Stage, the button says "OPEN IN FULLCREEN"

## Expected Behavior

The button should rather say FULLSCREEN

## Current Behavior

currently says FULLCREEN

## Possible Solution

https://github.com/backstage/backstage/blob/060fd0a44a3d14fd1f783755dd6753c36d79f74f/plugins/scaffolder/src/components/JobStage/JobStage.tsx#L164

Quick spelling fix

## Steps to Reproduce

1. Create a new Job
2. Start Job
3. See button with wrong spelling

## Context

Just a small spelling error

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04): Windows
- Browser Information: Chrome

### PR DESCRIPTION
**Pull request by freben**
Fixes #4144

### CODE REVIEW

**Review by Fox32 — APPROVED** [review]
👍

**Comment by OrkoHunter** [comment]
💯 
I guess Vale doesn't lint language EVERYWHERE.

**Comment by OrkoHunter** [comment]
_nod nod_

**Comment by Fox32** [comment]
Looks like it's primarily designed for comment 😞 https://docs.errata.ai/vale/scoping#code-1

**Review by Rugvip — APPROVED** [review]
:shipit:

**Pull request merged**
