### PR TITLE
Migrate microsite to v3

### LINKED ISSUE #23910: 🐛 Bug Report: Microsite Not Fully Upgraded to Docusaurus v3
### 📜 Description

While working on https://github.com/backstage/backstage/issues/23891 I noticed that the microsite is not fully upgraded to Docusaurus v3

### 👍 Expected behavior

The microsite should be full upgraded to Docusaurus v3

### 👎 Actual Behavior with Screenshots

There isn't really any errors right now but I think if we tried to use new features of Docusaurus v3 like around MDX we may run into issues.

### 👟 Reproduction steps

1. Look at the `dependencies` (and `devDependencies`) here: https://github.com/backstage/backstage/blob/fa512d2eecea48a838d5e60f940e96a20c8487af/microsite/package.json#L32

Notice they don't match up with what is in the upgrade guide here: https://docusaurus.io/docs/migration/v3#upgrading-dependencies

### 📃 Provide the context for the Bug.

I'm concerned that should we want to use new features from Docusaurus v3 we may run into issues that we spin out wheels on as we haven't properly upgraded.

### 🖥️ Your Environment

This isn't environment specific but what is in the `package.json` file here: https://github.com/backstage/backstage/blob/fa512d2eecea48a838d5e60f940e96a20c8487af/microsite/package.json#L32

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by npiyush97**
## Hey, I just made a Pull Request!
closes #23910 
reference -> https://github.com/facebook/docusaurus/tree/main/examples/classic-typescript

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by npiyush97** [comment]
@awanlin if okay can you merge asap as long it get getting more and more conflicts.

**Comment by npiyush97** [comment]
@benjdlambert for codeql https://codeql.github.com/codeql-query-help/javascript/js-incomplete-multi-character-sanitization/#example

**Review by awanlin — CHANGES_REQUESTED** [review]
Hi @npiyush97, the files in this PR look good but there are some changes in the previous PR - https://github.com/backstage/backstage/pull/23988/files - that are not here. Are those changes not needed? The ones in the docs folder.

Also don't we need to delete the `microsite/docusaurus.config.js` file now that we have a TS version?

**Comment by npiyush97** [comment]
> Hi @npiyush97, the files in this PR look good but there are some changes in the previous PR - https://github.com/backstage/backstage/pull/23988/files - that are not here. Are those changes not needed? The ones in the docs folder.
> 
> Also don't we need to delete the `microsite/docusaurus.config.js` file now that we have a TS version?

those changes were not related to issue just to make things look cleaner will make pr for that later

**Comment by npiyush97** [comment]
@Rugvip request wait till merge 🥺?

**Review by awanlin — APPROVED** [review]
Thanks again for running with this @npiyush97 🚀

**Comment by npiyush97** [comment]
@benjdlambert | @tudi2d can we merge this if okay?
conflict is resolved by changing v.1.25.0 to 26 hope it's okay for releases.

**Comment by npiyush97** [comment]
bad update

**Pull request closed without merging**
