### PR TITLE
Code coverage plugin - fix explore files breadcrumbs bug

### PR DESCRIPTION
**Pull request by eoghanmcilwaine**
##  Fix for code coverage plugin "explore files" breadcrumbs bug

Fixed https://github.com/backstage/backstage/issues/7867, a UI bug from the code coverage plugin. Navigating upwards through the file tree was triggering an error which left the UI in an unusable state.

I replicated the bug as follows:
1. Import the test data from `plugins/code-coverage-backend/src/service/__fixtures__/cobertura-testdata-1.xml`
2. Under "explore files", click on "com", then "example", then "utils". This should navigate through the file tree.
3. Click on "example" in the breadcrumbs to go back up to that folder.
4. "No files found" appears, and the breadcrumbs become broken and unclickable. Refreshing the page restores correct behaviour.

After my fix, it is now possible to navigate back up the file tree (e.g. by clicking on "example" in the screenshot) without breaking the UI or causing console errors.

Screenshot 2022-02-01 at 19 41 24

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] N/A Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jeremyguarini** [comment]
I just took a look at one of our instances and can confirm that I still see the issue, though I am not running the latest code from the repo. My last update was last week. Let me pull the latest code changes, build, and verify.

**Comment by jeremyguarini** [comment]
I just checked out the latest code from master branch, then applied this PR and I can still reproduce the issue as described in the original bug report.

**Review by jhaals — APPROVED** [review]
Nice work @eoghanmcilwaine and big plus for additional tests! Looks good to me 👍

**Comment by jeremyguarini** [comment]
Not sure why this got closed as I was still able to reproduce the issue /shurg.

**Comment by eoghanmcilwaine** [comment]
Thanks for that @jeremyguarini . I imported that code coverage file and I can't replicate the bug there either, as shown on the screen recording below.

https://user-images.githubusercontent.com/1396207/152311387-34566c50-4b49-4888-96a1-bb734bc47e8f.mp4

If the bug was still present, I would expect incorrect behaviour when clicking on folder breadcrumbs to navigate back upwards (which happens if I roll back to the last commit before my PR was merged: 2e9fe70c52)

I wouldn't be surprised if there are still a few bugs in this plugin but I think I've fixed this specific one, unless there was more to it?

**Comment by jeremyguarini** [comment]
Hmm interesting. Looks to be fixed but that wasn't the experience I had when testing the PR. Maybe something is wonky with my setup. Yeh go ahead and close this out. Thanks for all the work that went into this. --Jeremy

**Pull request merged**
