### PR TITLE
[CLI] Log duplicates instead of throwing error when doing a version bump

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

When running `version:bump` it will now log duplicates instead of throwing an error

Context: we ran into issues today doing the version bump where we had duplicate packages that should be allowed, more details in this Discord thread: https://discord.com/channels/687207715902193673/1141436702787899402

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
This did affect tests!

**Comment by awanlin** [comment]
> This did affect tests!

Yes, this is the new test I added but I'm struggling with how to re-create the duplicates, any suggestions @freben ;)

**Comment by freben** [comment]
Oh hai! Just checking in on this one - no I don't know that I have some great input there, @Rugvip for ideas?

**Review by Rugvip — APPROVED** [review]
Yep looks good, thank you! 👍

**Comment by awanlin** [comment]
Thanks @freben and @Rugvip 🚀

**Pull request merged**
