### PR TITLE
new headline image for README

### PR DESCRIPTION
**Pull request by katz95**
#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by katz95** [comment]
updated logo

**Comment by stefanalund** [comment]
@katz95 maybe downsize it a bit? The new file is pretty huge in terms of MB :)

**Comment by freben** [comment]
3000+ px wide is pretty sizeable, maybe make a bit smaller in terms of pixels? Otherwise maybe even a high quality jpeg could be considered.

**Review by stefanalund — APPROVED** [review]
I resized it and pushed a new version.

**Pull request merged**
