### PR TITLE
Omit ManagedFields from the Kubernetes resource YAML display.

### LINKED ISSUE #14177: Omit managedFields from Kubernetes resource YAML
## Feature Suggestion

The Kubernetes plugin lets you see the YAML for Kubernetes resources. It would be great if the extremely verbose `managedFields` field was omitted from the YAML.

https://github.com/kubernetes/kubernetes/issues/90066

## Possible Implementation

Delete the `managedFields` key before rendereing YAML

## Context

Inspect the YAML representation of a Kubernetes resource.

### PR DESCRIPTION
**Pull request by jpeach**
## Hey, I just made a Pull Request!

The default for the Kubernetes CLI tooling is to omit the managed fields by default, since these are only present for internal machinery. For the Kubernetes resource YAML display, the managed fields take up a ton of space, but are never useful to operators who are interested in the details of their Kubernetes resources.

Screen Shot 2023-04-25 at 10 36 24 am

This fixes #14177.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jpeach** [comment]
AFAICT, test failures are unrelated.

**Comment by mclarke47** [comment]
Hey, I actually do use this :joy:. Could we have a toggle to show them set to off by default?

**Comment by jpeach** [comment]
> Hey, I actually do use this :joy:. Could we have a toggle to show them set to off by default?

Oh interesting! What's your use case?

**Comment by mclarke47** [comment]
When applying resources by server side apply I want to check the objects have the correct managed fields.

**Comment by jpeach** [comment]
> When applying resources by server side apply I want to check the objects have the correct managed fields.

OK I added a toggle (off by default). WDYT?

Screen Shot 2023-04-26 at 9 47 20 am

**Review by mclarke47 — APPROVED** [review]

**Comment by mclarke47** [comment]
Can you rebase master and see if that fixes the e2e test

**Pull request merged**
