### PR TITLE
Change the word "production" to "maintained" as a `spec.lifecycle` value

### PR DESCRIPTION
**Pull request by patricekrakow**
## Hey, I just made a Pull Request!

Using the word "production" is quite confusing, because it sounds like a (production) environment, while @freben made it clear in https://github.com/backstage/backstage/issues/16389#issuecomment-2045383992 that "a component is an abstract concept that is often represented by the source repo. No versions, no environments."
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by hudsonb** [comment]
`experimental`, `production`, and `deprecated` are well-known and common lifecycles so I don't think they should be changed.

**Comment by Parsifal-M** [comment]
Hmm the terminology used [here](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component)

Describes a component as:

A Component describes a software component. It is typically intimately linked to the source code that constitutes the component, and should be what a developer may regard a "unit of software", usually with a distinct **deployable** or **linkable artifact**.

The way I interpret that is that it would be something you deploy to an environment (like production).

**Comment by freben** [comment]
Yeah I'll disagree here too.

- The original intent wasn't necessarily meant as an environment identifier but rather "it's in production" in the sense of "actively used and functional and maintained and probably relied upon"
- This is just a free-form string - any org is free to choose (and enforce) any terminology without the default model changing
- This base recommendation has been established for several years now and probably isn't worth changing unless there's particular reason to, which I don't think there is.

Thanks for your input, but I'll close this. One of the strengths of the catalog is that it's so flexible. The default model is intentionally on the small and generic side, and adopters are actively encouraged to extend and tweak it if needed. So I think this PR isn't needed.

**Comment by patricekrakow** [comment]
@hudsonb and @freben let me have one more/last try ;-) When I see the set of values ( `experimental`, `production`, `deprecated` ), I still have the impression that `production` is an "intruder".

@hudsonb you said you have a different experience, maybe you can find back some references where the value `production` is used next to `experimental` and `deprecated`.

On my side, I have made some (anecdotal) research and found the following sets:

- `experimental`, **`standard_track`**, `deprecated` in <https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#status-information>

- `Planned`, `Experimental`, **`Regular`**, `Deprecated`, `Obsolete` in <https://docs.evolveum.com/midpoint/versioning/feature-lifecycle/>

- `Experimental`, **`General Availability (Production)`**, `Deprecated` in https://developers.miro.com/docs/lifecycle-policy

> I am being honest and also copied this one - I have been tempted to forget about it ;-) - but you can see that `Production` is not on its own.

- `experimental`, **`stable`**, `deprecated`, `removed` in <https://developers.arcgis.com/arcgis-urban-api/guides/features-lifecycle/>

- etc.

On the other hand, I do agree that if you refer to the full documentation:

```markdown
`production` - an established, owned, maintained component
```

and 

```markdown
`production` - an established, owned, maintained API
```

the reference to a lifecycle state and **not** an environment is clear. However, for a (too) quick reader, I think that using another term - `maintained`, `established`, `regular`, `standard_track`,  `general_availability`, `stable`, etc. - might be beneficial.

**Pull request closed without merging**
