### PR TITLE
Add a default edit uri config option for techdocs

### PR DESCRIPTION
**Pull request by isabeltomb**
## Hey, I just made a Pull Request!

I added an optional value `defaultEditUri` to the app-config.yaml file which can be set to a value that will be used as the `edit_uri` in the mkdocs.yml files.

Currently if edit_uri isn't provided in the mkdocs.yml backstage by default sets this value to point at a `master` branch. For organizations that don't use `master` as the name of their main branch in repositories this causes the edit button on any techdocs page to be broken unless edit_uri has specifically been set in each mkdocs.yml file.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @isabeltomb, just curious if you tested this with GitLab and Bitbucket Server as well? 

https://github.com/backstage/backstage/blob/918d273bbb843bd09bb6c80d22d87c257a7e5343/plugins/techdocs-node/src/stages/generate/helpers.ts#L108

Each of these support the `edit_url` feature but have their own way of doing this. For example GitLab:

https://github.com/backstage/backstage/blob/918d273bbb843bd09bb6c80d22d87c257a7e5343/packages/integration/src/gitlab/GitLabIntegration.ts#L63

**Comment by isabeltomb** [comment]
> Hi @isabeltomb, just curious if you tested this with GitLab and Bitbucket Server as well?
> 
> https://github.com/backstage/backstage/blob/918d273bbb843bd09bb6c80d22d87c257a7e5343/plugins/techdocs-node/src/stages/generate/helpers.ts#L108
> 
> Each of these support the `edit_url` feature but have their own way of doing this. For example GitLab:
> 
> https://github.com/backstage/backstage/blob/918d273bbb843bd09bb6c80d22d87c257a7e5343/packages/integration/src/gitlab/GitLabIntegration.ts#L63

@awanlin Ahh good question, I have only tested with github. I will test the other two and update.

**Comment by isabeltomb** [comment]
Finished testing for GitLab and the changes worked as is. I have not finished testing for bitbucketServer yet but I will update in a comment when I'm done.

Sorry if this is a lot, I just wanted to be thorough with documenting what I did for local testing in case I missed any scenarios I wasn't aware of and so someone else could reproduce the steps if needed! Below is what I did to test locally with GitLab:

following the same local testing procedure I did with github:
1. I created a test repo in gitlab with the primary branch being "main" and a mkdocs.yaml without any edit_uri value
https://gitlab.com/test1662325/test-project/-/blob/main/catalog-info.yaml?ref_type=heads

Screenshot 2024-06-18 at 4 04 34 PM

2. added gitlab to the integrations in the app-config.yaml and added a location for it
```
    - type: url
      target: https://gitlab.com/test1662325/test-project/-/blob/main/catalog-info.yaml?ref_type=heads
```

3. ran the demo site locally without the `defaultedituri` value set and navigated to the component docs which had the expected default behavior of the edit link pointing at a "master" branch:

Screenshot 2024-06-18 at 4 09 53 PM

which gives a 404 because this branch does not exist

4. then I added a `defaultedituri: 'edit/main/{docs_dir}'` to the app-config.yaml and
restarted the demo site and regenerated the docs which were then updated to have the default edit uri value: 

Screenshot 2024-06-18 at 4 15 18 PM

checked that this gave a valid edit link:

Screenshot 2024-06-18 at 4 16 03 PM

5. then I updated the name of the docs directory in the repo to ‘mydocs’ and set the `docs_dir` value in the mkdocs.yml to test the non-default `docs_dir` value
restarted the demo site and regenerated the docs and checked that the edit uri was created properly:

Screenshot 2024-06-18 at 4 20 41 PM

Screenshot 2024-06-18 at 4 21 24 PM

6. lastly I added a `edit_uri` value to the mkdocs.yml to `blob/main/mydocs/`, restarted the demo site and regenerated the docs and checked that the `defaultedituri` value from the config was not used because edit_uri was provided

Screenshot 2024-06-18 at 4 28 48 PM

**Review by camilaibs — APPROVED** [review]
Thank you for contributing with us. The configuration makes sense to me, but I'll defer to @backstage/techdocs-maintainers review the code changes 🙂 .

**Comment by awanlin** [comment]
Thanks for the deep testing on this @isabeltomb, I'll give this a review at the end of the week. I've also reached out to the TechDocs team for their review as well.

One more thing I've been thinking about - do you use a branch other than the default? I was playing around with this last week and if my repo had a default branch of either `master` or `main` that works fine. It pulls that value from the source location annotation and it's not hard coded. So going back to the start I'm wondering if there is a bug somewhere else? 🤔

**Comment by isabeltomb** [comment]
alright finally done with the bitbucket server testing, sorry for the delay I was out of town last week. The functionality is a bit different for bitbucket server because the branch name is not included in the edit uri so the proposed `defaultEditUri` config value probably wouldn't be used in this scenario however the following shows that it still works as intended:

1. got an instance of bitbucket server running locally in a docker container
2. created a repo with a component
Screenshot 2024-07-01 at 6 07 02 PM
and a mkdocs.yml
Screenshot 2024-07-01 at 6 54 06 PM
3. added bitbucket server to the app-config.yaml integrations as well as a location for the catalog-info.yaml
```
    - type: url
      target: http://localhost:7990/projects/TES/repos/test-repo/browse/catalog-info.yaml
```
3. started the demo site without `defaultEditUri` set in app-config.yaml and went to the docs, the link for the edit button was generated as expected 
Screenshot 2024-07-01 at 6 55 12 PM
4. added a `defaultEditUri` value of `defaultEditUri: '/testing/edituri/{docs_dir}'` to the app-config.yaml and regenerated the docs on the demo site and checked that the expected edit URI was created
Screenshot 2024-07-01 at 7 15 14 PM
5. updated `defaultEditUri` in app-config.yaml to just `defaultEditUri: '{docs_dir}'` and then I updated the name of the docs directory in the repo to ‘mydocs’ and set the `docs_dir` value in the mkdocs.yml to test the non-default `docs_dir` value
restarted the demo site and regenerated the docs and checked that the edit link was generated as expected
Screenshot 2024-07-02 at 9 11 34 AM
6. lastly I added a `edit_uri` value to the mkdocs.yml of `edit_uri: test/edituri/mydocs`, regenerated the docs on the demo site and checked that the `defaultEditUri` value from the app-config.yaml was not used because `edit_uri` was provided in the mkdocs.yml
Screenshot 2024-07-02 at 9 18 30 AM




let me know if there's any other scenarios that I missed in the testing or any further clarification needed, thanks!

**Comment by isabeltomb** [comment]
> Thanks for the deep testing on this @isabeltomb, I'll give this a review at the end of the week. I've also reached out to the TechDocs team for their review as well.
> 
> One more thing I've been thinking about - do you use a branch other than the default? I was playing around with this last week and if my repo had a default branch of either `master` or `main` that works fine. It pulls that value from the source location annotation and it's not hard coded. So going back to the start I'm wondering if there is a bug somewhere else? 🤔

Hi awanlin, we use main as the default branch in almost all of our repos and were still seeing "master" being automatically added to the generated edit link, this PR has been in the works on our end for a long time so there's a chance that a change was made in backstage somewhat recently to use the default branch value and we hadn't updated to get those changes yet? 

Although in my testing steps above I was testing with the demo site running the latest version of backstage and when I set up the repo in GitLab I set the default branch to main and the generated edit link was still defaulting to 'master'

**Comment by awanlin** [comment]
Thanks, I haven't been able to find anywhere that has `master` hard coded which is why I'm thinking perhaps there is a bug somewhere. It's all driven by the source `backstage.io/source-location`.

**Comment by byan1197** [comment]
Hi @isabeltomb! Throughout the life of the repos/components that you're interacting with, do they go through any main branch name changes? When switching from `master` to `main` for example, this can cause URIs to be outdated (such as the edit link misdirect you're seeing). However, if the component is unregistered and then re-registered again, the edit links should point to the right place as they are not hard coded and URIs can be found in its annotations like @awanlin has mentioned.

**Comment by isabeltomb** [comment]
@awanlin Thanks for checking! I also didn't see it hard coded anywhere, I can do some more testing with the demo site and see if I can help!

Hi @byan1197! That's a good point, but since starting our backstage instance, we have been using `main` as the default branch for our repos and haven't changed it

**Comment by awanlin** [comment]
@isabeltomb, would you be open to creating an issue around the whole "hardcoded master" bit? Personally think this PR makes sense to have and I feel like creating the issue would help us focus the conversation a bit better.

**Comment by byan1197** [comment]
hey @awanlin and @isabeltomb 👋 , my bad -- I did some digging and found [this bit in the mkdocs docuementation](https://www.mkdocs.org/user-guide/configuration/#:~:text=default%3A%20edit/master/docs/%20for%20GitHub%20and%20GitLab%20repos%20or%20src/default/docs/%20for%20a%20Bitbucket%20repo%2C%20if%20repo_url%20matches%20those%20domains%2C%20otherwise%20null) which confirms the `master` hardcoding. In most `mkdocs.yaml` files, the `repo_url` is already pre-populated, which is fine, but this shorts the `patchMkdocsYmlPrebuild(...)` function ([permalink here](https://github.com/backstage/backstage/blob/b302b097a5fd0dbc0e383f0fcaf7672657e1b39c/plugins/techdocs-node/src/stages/generate/mkdocsPatchers.ts#L111)). This causes edit_uri to default to `edit/master/docs` as specified in the docs. This behaviour is verifiable with `techdocs-cli` by viewing the contents of the effective markdown yaml too.

I'm wondering now, would it be a possible/alternate solution to modify the `patchMkdocsYmlPrebuild` function such that the `repo_url` and `edit_uri` are modified separately instead of always modifying both at once? By doing it this way, we can ensure `edit_uri` is always populated, as long as `repo_url` has a value too. This results in less conditionals in the pre generation step which is an overall benefit for maintainability too. Let me know if this can work!

**Comment by isabeltomb** [comment]
@byan1197 ahh I see, thanks for digging and figuring that out! I think it makes sense as an alternate solution to split up modifying `repo_url` and `edit_uri` in `patchMkdocsYmlPrebuild` and I'm happy to take a crack at it and test it out.

@awanlin with this discovery, do you think an issue would still be helpful for tracking this change and any further discussion around it? If so I can definitely open one, just wanted to check first

**Comment by isabeltomb** [comment]
Hi @awanlin and @byan1197 ! I created a separate PR for my attempt at implementing the alternation solution that @byan1197 proposed #25549

**Comment by benjdlambert** [comment]
Ping @backstage/techdocs-maintainers here :pray:

**Pull request closed without merging**
