### PR TITLE
Limit "View graph" depth in the Catalog Graph Card

### LINKED ISSUE #10524: Limit "View graph" depth in the Catalog Graph Card
We have a large graph of entities which takes a long time to load and is an undecipherable mess when it is loaded with an unlimited depth. We want to add a parameter to the CatalogGraphCard which will allow us to limit the depth of the graph when "View graph" is clicked from an entity page.

## Feature Suggestion
Add a parameter to the CatalogGraphCard which will allow us to limit the depth of the graph when "View graph" is clicked from an entity page.

## Possible Implementation
Add "viewGraphDepth" as an optional prop to [CatalogGraphCard](https://github.com/backstage/backstage/blob/adfe2ea2ad8c84d32dbf8e7ab572ea3882eb1825/plugins/catalog-graph/src/components/CatalogGraphCard/CatalogGraphCard.tsx#L54) which value is then embedded into the query string in the "View graph" buttons destination URL.

### PR DESCRIPTION
**Pull request by weid-h**
## Hey, I just made a Pull Request!

Closes #10524

I added "viewGraphDepth" as an optional prop to [CatalogGraphCard](https://github.com/backstage/backstage/blob/adfe2ea2ad8c84d32dbf8e7ab572ea3882eb1825/plugins/catalog-graph/src/components/CatalogGraphCard/CatalogGraphCard.tsx#L54) which value is then embedded into the query string in the "View graph" buttons destination URL.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by weid-h** [comment]
Closes #10524

**Comment by benjdlambert** [comment]
Thanks for this! Just a though on Wondering if it would be good to still support having the ability to view all, but basically limit what you can see until you click on CTA which is like `Collapsed some nodes as it looks like there's a lot, click here to view all`?

**Comment by kmikko** [comment]
Thought I would chime in as I'm working on the same team as @weid-h.

So this doesn't actually limit view depth of the graph on entity overview page but on the `CatalogGraphPage` where user is taken when "View graph" link is clicked. For limiting view depth of the graph on entity page there's already `maxDepth` prop that can be passed to `EntityCatalogGraphCard`. That being said, would it be better to use this existing prop and pass it also as a query parameter instead of creating a new prop?

What comes to displaying the full graph, `CatalogGraphPage` already provides pretty fine grained control how the graph is visualized including limiting the depth of it. Creating a CTA for expanding the graph on entity page sounds like a good addition but is out of this PR's scope in my opinion.

**Comment by freben** [comment]
Hey! This seems to have hit a conflict. Rebasing on latest master should get rid of the odd build error too.

So how do we proceed? Is the new prop needed or can the old max depth be leveraged?

**Comment by benjdlambert** [comment]
fix up conflicts?

**Review by Rugvip — COMMENTED** [review]
Ping 🏓 , this is stuck on a reply to Freben's question above

**Pull request closed without merging**
