### PR TITLE
Add Entity Validation plugin to Marketplace

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

This PR adds the Entity Validation plugin to the Plugin Marketplace. This will give it a bit more visibility!

This plugin was added in PR https://github.com/backstage/backstage/pull/16050 by @ivangonzalezacuna

Screenshot 2023-09-15 at 1 29 13 PM

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @ivangonzalezacuna, I put this under your name as it was your contribution, if this should be something else like maybe the organization you work for please let me know. 🚀

**Review by ivangonzalezacuna — CHANGES_REQUESTED** [review]
Hi @awanlin , thanks for the addition! However, even though it was completely designed by me, I think it would be better to point to my company instead. You can get the info available in one of the plugins we already added to the marketplace: https://github.com/backstage/backstage/blob/master/microsite/data/plugins/s3-viewer.yaml

**Comment by awanlin** [comment]
Hi @ivangonzalezacuna, I've updated the author based on the link you provided and also added an icon, there's a screenshot in the PR description. Does that look good to you?

**Review by ivangonzalezacuna — APPROVED** [review]
Hey @awanlin . Yes, it looks good to me! Thanks for the addition. Approving it now

**Comment by awanlin** [comment]
Thanks @freben and @ivangonzalezacuna 🚀

**Pull request merged**
