### PR TITLE
WIP: Upgrade to yarn 3

### PR DESCRIPTION
**Pull request by dschwank**
## Hey, I just made a Pull Request!

This PR upgrades the repo to `yarn 3`. The goal would be to not use new `yarn 3` features, but start with the "smallest possible" upgrade first.

**The upgrade is still work in progress.**

https://github.com/backstage/backstage/pull/9619

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by dschwank** [comment]
Thanks for bringing this up @szubster! I wasn't aware that this is still an open topic 🙄 That's some kind of a showstopper.

To discuss some options ...
(a) Stop and wait for a dependabot update (will most likely not happen soon)
(b) Add an additional github action to fix the `yarn.lock` file for dependabot PRs
(c) Switch to renovate (probably bigger discussion?)

Option (b) could be a short-term solution - and option (c) a long-term which probably needs more discussion.

What do you think @Rugvip, @freben, @benjdlambert?

**Comment by freben** [comment]
(d) switch to pnpm or so instead ;)

(b) sounds scary - how much work/complexity is that?

**Comment by szubster** [comment]
(b) - linked dependabot issue has some ready to use github actions.
e.g. https://github.com/dependabot/dependabot-core/issues/1297#issuecomment-671131912

**Comment by dschwank** [comment]
> (d) switch to pnpm or so instead ;)

That would be some more work to drop yarn completely 🙈 did you already have discussions about replacing `yarn`?

> (b) sounds scary - how much work/complexity is that?

As @szubster posted, I think for this repo it would be manageable. But my biggest concern would be the support for all other users. Most general stuff is covered by the `backstage-cli`, but we would have to make sure that the "default" generated backstage app doesn't use any yarn 3 features and we would have to add some FAQ / help to the docs, because some commands are now differently.

**Comment by freben** [comment]
> > (d) switch to pnpm or so instead ;)
> 
> That would be some more work to drop yarn completely 🙈 did you already have discussions about replacing `yarn`?

Only jokingly. :)

Yarn is fine, but perhaps the arguments for yarn instead of npm are fewer today than they were some years ago.

> > (b) sounds scary - how much work/complexity is that?
> 
> As @szubster posted, I think for this repo it would be manageable. But my biggest concern would be the support for all other users. Most general stuff is covered by the `backstage-cli`, but we would have to make sure that the "default" generated backstage app doesn't use any yarn 3 features and we would have to add some FAQ / help to the docs, because some commands are now differently.

Yeah ... that does sound a bit iffy. Having an excellent dev experience for adopters basically even trumps in-repo convenience, if one has to choose. I'll let @Rugvip and @benjdlambert weigh in on that one though

**Comment by dschwank** [comment]
> Only jokingly. :)

Haha 😆 that was my first thought, but then the "what if he is not joking" won 😆

> Yeah ... that does sound a bit iffy. Having an excellent dev experience for adopters basically even trumps in-repo convenience, if one has to choose. I'll let @Rugvip and @benjdlambert weigh in on that one though

Sounds good 👍
There are still some open topics within this PR, but will pause with that until we are clear how to continue with it in general 😉

**Comment by dschwank** [comment]
@freben, @Rugvip, @benjdlambert any update from your side?

I personally tend to skip yarn 3 for the moment and instead **discuss `dependabot` vs `renovate` first**. Waiting for `dependabot` is probably not the best option, as https://github.com/dependabot/dependabot-core/issues/1297 is already open for a while.
Having a GitHub Action would solve the issues within this repo, but not for everyone. We could add something to the `backstage-cli`, but that would be super custom & hacky.

**Comment by jhaals** [comment]
Yes, we are all aboard on giving renovate a try!

**Comment by Rugvip** [comment]
Update for this is that it looks like we now have Renovate up and running and working. Probably the main piece that is left is lockfile management and migration in the CLI. We'll need to support both the Yarn 1 and 2/3 lockfile formats in any CLI command that interacts with them. On top of that I'd say we need `1->3` and probably also `3->1` migration commands, so that everyone can migrate to Yarn 3 without having to lose their lockfile

**Comment by dschwank** [comment]
@Rugvip Nice 🥳 Thanks for the update - yeah, there is still some way to go.
Can you elaborate a little bit more on supporting yarn 1 & yarn 3? You would aim for making the CLI compatible with both, but other than that focus on yarn 3? Otherwise all docs, Dockerfiles, ... need also to support both which I would mean some headaches.

From my point of view those three

- [ ] Add backstage-cli support for yarn 1 & yarn 3
- [ ] Re-Add all lockfile checks
- [ ] Double-Check yarn commands
- [ ] Change all docs

I am currently loaded with some other topics, so I can only partly maintain this PR.

**Comment by Rugvip** [comment]
@dschwank yep totally! I think as soon as our usage of Yarn 3 looks good enough we'd completely switch over all docs and templates to support that, and possibly just have a minor section about Yarn 1

**Comment by Rugvip** [comment]
@dschwank We need to make it a soft switch imo, in that the move to Yarn 3 is independent from the `@backstage/cli` version. Whether we ever remove support for Yarn 1 I think depends on how many people stick to that release, and how much work it is to support it.

Speaking of this PR, I think the quickest way to get it shipped is to break out all of the changes that we can ship straight into master. All of the `package.json` updates are things that we can apply now for example. If you break that out into a separate PR we don't need to worry about that anymore and it's also a very quick review.

**Comment by dschwank** [comment]
> We need to make it a soft switch imo, in that the move to Yarn 3 is independent from the @backstage/cli version. Whether we ever remove support for Yarn 1 I think depends on how many people stick to that release, and how much work it is to support it.

@Rugvip agree to that - even though that could get some painful.

> Speaking of this PR, I think the quickest way to get it shipped is to break out all of the changes that we can ship straight into master. All of the package.json updates are things that we can apply now for example. If you break that out into a separate PR we don't need to worry about that anymore and it's also a very quick review.

Good point 👍 Will try to split it in the next days!

**Pull request closed without merging**
