### PR TITLE
Replaced moment and dayjs with luxon

### PR DESCRIPTION
**Pull request by vannarath-poeu**
Signed-off-by: Vannarath Poeu <vannarath.poeu@gmail.com>

#### :heavy_check_mark: Checklist

Replaced moment and dayjs date libraries with luxon. Part of https://github.com/backstage/backstage/issues/4278.

- [x ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@backstage/silver-lining can you do some verification here for this PR? 👍

**Review by bsukh — APPROVED** [review]
LGTM 👍🏼

**Comment by benjdlambert** [comment]
Looks like you'll need to regenerate and commit the `api-reports` @vannarath-poeu.

You can run `yarn build:api-reports` and then commit the changed file.

**Comment by vannarath-poeu** [comment]
Thanks @benjdlambert. Have updated the api-report as well the failing vocab check. Cheers!

**Review by OrkoHunter — APPROVED** [review]
Thanks for fixing the CI issues!

**Pull request merged**
