### PR TITLE
storybook: fix broken stories that lack a router parent

### LINKED ISSUE #3267: Storybook: all cards with deep links are broken
There seems to be a bug on the site that displays all of the Backstage Storybook examples where anything with a deep link displays:

> Something went wrong here. Please contact #backstage for help.

## Expected Behavior

Card examples that use links ("deepLink") display properly in the Backstage Storybook examples.

## Current Behavior

It seems multiple card types that include links all are broken in the Storybook display:

https://backstage.io/storybook/?path=/story/data-display-progress-card--link-in-footer

image

## Possible Solution

Not sure.  When I reproduce cards, for example an InfoCard with a deep link locally in a sample new plugin I'm testing, it works fine!

## Steps to Reproduce

Visit the following pages which seem for me to all display broken:

* https://backstage.io/storybook/?path=/story/layout-information-card--link-in-footer
* https://backstage.io/storybook/?path=/story/layout-tabbed-card--with-footer-link
* https://backstage.io/storybook/?path=/story/data-display-progress-card--link-in-footer

## Your Environment

- NodeJS Version (v12): n/a
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1901
- Browser Information: Microsoft Edge (Chrome)

### PR DESCRIPTION
**Pull request by freben**
Fixes #3267

### CODE REVIEW

**Review by Fox32 — APPROVED** [review]
👍 Looks good. I wonder if there might be cases where it is used in Backstage outside of the router? But it looks like everything is wrapped in it.

**Comment by freben** [comment]
Yeah no, it's wrapped at the very root by the app builder so it should be safe.

**Comment by freben** [comment]
I was considering making a MemoryRouter at the very root of the default wrapper in the storybook project itself - but judged against it for the time being since that instead breaks a lot of stories that DO add one, and having double routers breaks things as well. Having them part of the individual story lets the storymaker give the router an initial state etc.

**Comment by Fox32** [comment]
Btw. the chromatic integration seems still to be broken. In the Spotify org one could click here in the checks and go directly to chromatic and see the changes to storybook. That was ready useful!

**Comment by jeskosda** [comment]
Thanks @freben for fixing this 👍

**Comment by Rugvip** [comment]
Perhaps makes sense to just add `<MemoryRouter>` to the global decorators instead? https://github.com/backstage/backstage/blob/a906f20e7b8070bc58f7807e26e9f9e68753cf31/packages/storybook/.storybook/preview.js#L10

**Comment by freben** [comment]
@Rugvip I mention that above ^

**Review by Rugvip — APPROVED** [review]
Derp x) Yeah let's get this in then

**Comment by freben** [comment]
I agree though, it would be way better, let's try to get to that point later. There was some occurrence of explicitly setting the memory router state, but that can likely be removed (or made so that the state is the same well known one for everybody).

**Pull request merged**
