### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by backstage-service**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and publish to npm yourself or [setup this action to publish automatically](https://github.com/changesets/action#with-publishing). If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
### Minor Changes

-   e0bfd3d44: Refactor the `runDockerContainer(…)` function to an interface-based api.
    This gives the option to replace the docker runtime in the future.

    Packages and plugins that previously used the `dockerode` as argument should be migrated to use the new `ContainerRunner` interface instead.

    ```diff
      import {
    -   runDockerContainer,
    +   ContainerRunner,
        PluginEndpointDiscovery,
      } from '@backstage/backend-common';
    - import Docker from 'dockerode';

      type RouterOptions = {
        // ...
    -   dockerClient: Docker,
    +   containerRunner: ContainerRunner;
      };

      export async function createRouter({
        // ...
    -   dockerClient,
    +   containerRunner,
      }: RouterOptions): Promise<express.Router> {
        // ...

    +   await containerRunner.runContainer({
    -   await runDockerContainer({
          image: 'docker',
          // ...
    -     dockerClient,
        });

        // ...
      }
    ```

    To keep the `dockerode` based runtime, use the `DockerContainerRunner` implementation:

    ```diff
    + import {
    +   ContainerRunner,
    +   DockerContainerRunner
    + } from '@backstage/backend-common';
    - import { runDockerContainer } from '@backstage/backend-common';

    + const containerRunner: ContainerRunner = new DockerContainerRunner({dockerClient});
    + await containerRunner.runContainer({
    - await runDockerContainer({
        image: 'docker',
        // ...
    -   dockerClient,
      });
    ```

### Patch Changes

-   38ca05168: The default `@octokit/rest` dependency was bumped to `"^18.5.3"`.
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/integration@0.5.2
    -   @backstage/config-loader@0.6.1
    -   @backstage/config@0.1.5

 ## @backstage/techdocs-common@0.6.0

### Minor Changes

-   e0bfd3d44: Migrate the package to use the `ContainerRunner` interface instead of `runDockerContainer(…)`.
    It also no longer provides the `ContainerRunner` as an input to the `GeneratorBase#run(…)` function, but expects it as a constructor parameter instead.

    If you use the `TechdocsGenerator` you need to update the usage:

    ```diff
    + const containerRunner = new DockerContainerRunner({ dockerClient });

    - const generator = new TechdocsGenerator(logger, config);
    + const techdocsGenerator = new TechdocsGenerator({
    +   logger,
    +   containerRunner,
    +   config,
    + });

      await this.generator.run({
        inputDir: preparedDir,
        outputDir,
    -   dockerClient: this.dockerClient,
        parsedLocationAnnotation,
        etag: newEtag,
      });
    ```

### Patch Changes

-   e9e56b01a: Adding optional config to enable S3-like API for tech-docs using s3ForcePathStyle option.
    This allows providers like LocalStack, Minio and Wasabi (+possibly others) to be used to host tech docs.
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/integration@0.5.2
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/plugin-cost-insights@0.9.0

### Minor Changes

-   6f1b82b14: make change ratio optional

### Patch Changes

-   Updated dependencies [f65adcde7]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [d8b81fd28]
    -   @backstage/core@0.7.8
    -   @backstage/theme@0.2.7
    -   @backstage/config@0.1.5

 ## @backstage/plugin-scaffolder-backend@0.11.0

### Minor Changes

-   e0bfd3d44: Migrate the plugin to use the `ContainerRunner` interface instead of `runDockerContainer(…)`.
    It also provides the `ContainerRunner` to the individual templaters instead of to the `createRouter` function.

    To apply this change to an existing backend application, add the following to `src/plugins/scaffolder.ts`:

    ```diff
    - import { SingleHostDiscovery } from '@backstage/backend-common';
    + import {
    +   DockerContainerRunner,
    +   SingleHostDiscovery,
    + } from '@backstage/backend-common';
    ```

    export default async function createPlugin({
      logger,
      config,
      database,
      reader,
    }: PluginEnvironment): Promise<Router> {

-   const dockerClient = new Docker();

-   const containerRunner = new DockerContainerRunner({ dockerClient });

-   const cookiecutterTemplater = new CookieCutter({ containerRunner });

-   const cookiecutterTemplater = new CookieCutter();

-   const craTemplater = new CreateReactAppTemplater({ containerRunner });

-   const craTemplater = new CreateReactAppTemplater();
    const templaters = new Templaters();

    templaters.register('cookiecutter', cookiecutterTemplater);
    templaters.register('cra', craTemplater);

    const preparers = await Preparers.fromConfig(config, { logger });
    const publishers = await Publishers.fromConfig(config, { logger });

-   const dockerClient = new Docker();

    const discovery = SingleHostDiscovery.fromConfig(config);
    const catalogClient = new CatalogClient({ discoveryApi: discovery });

    return await createRouter({
      preparers,
      templaters,
      publishers,
      logger,
      config,

-       dockerClient,
          database,
          catalogClient,
          reader,
        });
      }
    ```

    ```

### Patch Changes

-   38ca05168: The default `@octokit/rest` dependency was bumped to `"^18.5.3"`.
-   69eefb5ae: Fix GithubPR built-in action `credentialsProvider.getCredentials` URL.
    Adding Documentation for GitHub PR built-in action.
-   75c8cec39: bump `jsonschema` from 1.2.7 to 1.4.0
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/backend-common@0.7.0
    -   @backstage/integration@0.5.2
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11

 ## @backstage/plugin-techdocs-backend@0.8.0

### Minor Changes

-   e0bfd3d44: Migrate the plugin to use the `ContainerRunner` interface instead of `runDockerContainer(…)`.
    It also provides the `ContainerRunner` to the generators instead of to the `createRouter` function.

    To apply this change to an existing backend application, add the following to `src/plugins/techdocs.ts`:

    ```diff
    + import { DockerContainerRunner } from '@backstage/backend-common';

      // ...

      export default async function createPlugin({
        logger,
        config,
        discovery,
        reader,
      }: PluginEnvironment): Promise<Router> {
        // Preparers are responsible for fetching source files for documentation.
        const preparers = await Preparers.fromConfig(config, {
          logger,
          reader,
        });

    +   // Docker client (conditionally) used by the generators, based on techdocs.generators config.
    +   const dockerClient = new Docker();
    +   const containerRunner = new DockerContainerRunner({ dockerClient });

        // Generators are used for generating documentation sites.
        const generators = await Generators.fromConfig(config, {
          logger,
    +     containerRunner,
        });

        // Publisher is used for
        // 1. Publishing generated files to storage
        // 2. Fetching files from storage and passing them to TechDocs frontend.
        const publisher = await Publisher.fromConfig(config, {
          logger,
          discovery,
        });

        // checks if the publisher is working and logs the result
        await publisher.getReadiness();

    -   // Docker client (conditionally) used by the generators, based on techdocs.generators config.
    -   const dockerClient = new Docker();

        return await createRouter({
          preparers,
          generators,
          publisher,
    -     dockerClient,
          logger,
          config,
          discovery,
        });
      }
    ```

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [e9e56b01a]
    -   @backstage/backend-common@0.7.0
    -   @backstage/techdocs-common@0.6.0
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/catalog-client@0.3.11

### Patch Changes

-   d1b1306d9: Allow `filter` parameter to be specified multiple times
-   Updated dependencies [d8b81fd28]
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/catalog-model@0.7.8

### Patch Changes

-   d8b81fd28: Bump `json-schema` dependency from `0.2.5` to `0.3.0`.
-   Updated dependencies [d8b81fd28]
    -   @backstage/config@0.1.5

 ## @backstage/cli@0.6.10

### Patch Changes

-   f65adcde7: Fix some transitive dependency warnings in yarn
-   fc79a6dd3: Added lax option to backstage-cli app:build command
-   d8b81fd28: Bump `json-schema` dependency from `0.2.5` to `0.3.0`.
-   Updated dependencies [d8b81fd28]
    -   @backstage/config-loader@0.6.1
    -   @backstage/config@0.1.5

 ## @backstage/config@0.1.5

### Patch Changes

-   d8b81fd28: Bump `json-schema` dependency from `0.2.5` to `0.3.0`.

 ## @backstage/config-loader@0.6.1

### Patch Changes

-   d8b81fd28: Bump `json-schema` dependency from `0.2.5` to `0.3.0`.
-   Updated dependencies [d8b81fd28]
    -   @backstage/config@0.1.5

 ## @backstage/core@0.7.8

### Patch Changes

-   f65adcde7: Fix some transitive dependency warnings in yarn
-   80888659b: Bump react-hook-form version to be the same for the entire project.
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [d8b81fd28]
    -   @backstage/theme@0.2.7
    -   @backstage/config@0.1.5

 ## @backstage/create-app@0.3.21

### Patch Changes

-   38ca05168: The default `@octokit/rest` dependency was bumped to `"^18.5.3"`.
-   e0bfd3d44: The `scaffolder-backend` and `techdocs-backend` plugins have been updated.
    In order to update, you need to apply the following changes to your existing backend application:

    `@backstage/plugin-techdocs-backend`:

    ```diff
    // packages/backend/src/plugin/techdocs.ts

    + import { DockerContainerRunner } from '@backstage/backend-common';

      // ...

      export default async function createPlugin({
        logger,
        config,
        discovery,
        reader,
      }: PluginEnvironment): Promise<Router> {
        // Preparers are responsible for fetching source files for documentation.
        const preparers = await Preparers.fromConfig(config, {
          logger,
          reader,
        });

    +   // Docker client (conditionally) used by the generators, based on techdocs.generators config.
    +   const dockerClient = new Docker();
    +   const containerRunner = new DockerContainerRunner({ dockerClient });

        // Generators are used for generating documentation sites.
        const generators = await Generators.fromConfig(config, {
          logger,
    +     containerRunner,
        });

        // Publisher is used for
        // 1. Publishing generated files to storage
        // 2. Fetching files from storage and passing them to TechDocs frontend.
        const publisher = await Publisher.fromConfig(config, {
          logger,
          discovery,
        });

        // checks if the publisher is working and logs the result
        await publisher.getReadiness();

    -   // Docker client (conditionally) used by the generators, based on techdocs.generators config.
    -   const dockerClient = new Docker();

        return await createRouter({
          preparers,
          generators,
          publisher,
    -     dockerClient,
          logger,
          config,
          discovery,
        });
      }
    ```

    `@backstage/plugin-scaffolder-backend`:

    ```diff
    // packages/backend/src/plugin/scaffolder.ts

    - import { SingleHostDiscovery } from '@backstage/backend-common';
    + import {
    +   DockerContainerRunner,
    +   SingleHostDiscovery,
    + } from '@backstage/backend-common';
    ```

    export default async function createPlugin({
      logger,
      config,
      database,
      reader,
    }: PluginEnvironment): Promise<Router> {

-   const dockerClient = new Docker();

-   const containerRunner = new DockerContainerRunner({ dockerClient });

-   const cookiecutterTemplater = new CookieCutter({ containerRunner });

-   const cookiecutterTemplater = new CookieCutter();

-   const craTemplater = new CreateReactAppTemplater({ containerRunner });

-   const craTemplater = new CreateReactAppTemplater();
    const templaters = new Templaters();

    templaters.register('cookiecutter', cookiecutterTemplater);
    templaters.register('cra', craTemplater);

    const preparers = await Preparers.fromConfig(config, { logger });
    const publishers = await Publishers.fromConfig(config, { logger });

-   const dockerClient = new Docker();

    const discovery = SingleHostDiscovery.fromConfig(config);
    const catalogClient = new CatalogClient({ discoveryApi: discovery });

    return await createRouter({
      preparers,
      templaters,
      publishers,
      logger,
      config,

-       dockerClient,
          database,
          catalogClient,
          reader,
        });
      }
    ```

    ```

-   Updated dependencies [e0bfd3d44]

-   Updated dependencies [e0bfd3d44]

-   Updated dependencies [e0bfd3d44]

-   Updated dependencies [38ca05168]

-   Updated dependencies [f65adcde7]

-   Updated dependencies [80888659b]

-   Updated dependencies [b219821a0]

-   Updated dependencies [7b8272fb7]

-   Updated dependencies [8aedbb4af]

-   Updated dependencies [fc79a6dd3]

-   Updated dependencies [69eefb5ae]

-   Updated dependencies [75c8cec39]

-   Updated dependencies [b2e2ec753]

-   Updated dependencies [227439a72]

-   Updated dependencies [9314a8592]

-   Updated dependencies [2e05277e0]

-   Updated dependencies [4075c6367]

-   Updated dependencies [cdb3426e5]

-   Updated dependencies [d8b81fd28]

-   Updated dependencies [d1b1306d9]
    -   @backstage/plugin-scaffolder-backend@0.11.0
    -   @backstage/backend-common@0.7.0
    -   @backstage/plugin-techdocs-backend@0.8.0
    -   @backstage/plugin-catalog-import@0.5.5
    -   @backstage/plugin-github-actions@0.4.5
    -   @backstage/cli@0.6.10
    -   @backstage/core@0.7.8
    -   @backstage/plugin-catalog-backend@0.8.2
    -   @backstage/theme@0.2.7
    -   @backstage/plugin-tech-radar@0.3.10
    -   @backstage/plugin-scaffolder@0.9.3
    -   @backstage/plugin-techdocs@0.9.1
    -   @backstage/plugin-proxy-backend@0.2.7
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11
    -   @backstage/plugin-app-backend@0.3.12
    -   @backstage/plugin-auth-backend@0.3.9
    -   @backstage/plugin-rollbar-backend@0.1.10

 ## @backstage/integration@0.5.2

### Patch Changes

-   38ca05168: The default `@octokit/rest` dependency was bumped to `"^18.5.3"`.
-   Updated dependencies [d8b81fd28]
    -   @backstage/config@0.1.5

 ## @backstage/theme@0.2.7

### Patch Changes

-   7b8272fb7: Remove extra bottom padding in InfoCard content

 ## @backstage/plugin-app-backend@0.3.12

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/config-loader@0.6.1
    -   @backstage/config@0.1.5

 ## @backstage/plugin-auth-backend@0.3.9

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/backend-common@0.7.0
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11

 ## @backstage/plugin-badges-backend@0.1.3

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/backend-common@0.7.0
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11

 ## @backstage/plugin-catalog-backend@0.8.2

### Patch Changes

-   b219821a0: Expose `BitbucketRepositoryParser` introduced in [#5295](https://github.com/backstage/backstage/pull/5295)
-   227439a72: Add support for non-organization accounts in GitHub Discovery
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/integration@0.5.2
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/plugin-catalog-graphql@0.2.8

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/plugin-catalog-import@0.5.5

### Patch Changes

-   38ca05168: The default `@octokit/rest` dependency was bumped to `"^18.5.3"`.
-   80888659b: Bump react-hook-form version to be the same for the entire project.
-   8aedbb4af: Fixes a typo and minor wording changes to the catalog import UI
-   Updated dependencies [38ca05168]
-   Updated dependencies [f65adcde7]
-   Updated dependencies [81c54d1f2]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/integration@0.5.2
    -   @backstage/core@0.7.8
    -   @backstage/plugin-catalog-react@0.1.5
    -   @backstage/theme@0.2.7
    -   @backstage/catalog-model@0.7.8
    -   @backstage/catalog-client@0.3.11

 ## @backstage/plugin-catalog-react@0.1.5

### Patch Changes

-   81c54d1f2: Fetch relations in batches in `useRelatedEntities`
-   Updated dependencies [f65adcde7]
-   Updated dependencies [80888659b]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/core@0.7.8
    -   @backstage/catalog-model@0.7.8
    -   @backstage/catalog-client@0.3.11

 ## @backstage/plugin-code-coverage-backend@0.1.4

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/backend-common@0.7.0
    -   @backstage/integration@0.5.2
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11

 ## @backstage/plugin-github-actions@0.4.5

### Patch Changes

-   38ca05168: The default `@octokit/rest` dependency was bumped to `"^18.5.3"`.
-   Updated dependencies [38ca05168]
-   Updated dependencies [f65adcde7]
-   Updated dependencies [81c54d1f2]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [d8b81fd28]
    -   @backstage/integration@0.5.2
    -   @backstage/core@0.7.8
    -   @backstage/plugin-catalog-react@0.1.5
    -   @backstage/theme@0.2.7
    -   @backstage/catalog-model@0.7.8

 ## @backstage/plugin-graphql-backend@0.1.7

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/config@0.1.5
    -   @backstage/plugin-catalog-graphql@0.2.8

 ## @backstage/plugin-kafka-backend@0.2.4

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/plugin-kubernetes@0.4.3

### Patch Changes

-   f53fba29f: Adds @backstage/plugin-kubernetes-common library to share types between kubernetes frontend and backend.
-   Updated dependencies [f65adcde7]
-   Updated dependencies [81c54d1f2]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [d8b81fd28]
    -   @backstage/core@0.7.8
    -   @backstage/plugin-catalog-react@0.1.5
    -   @backstage/theme@0.2.7
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/plugin-kubernetes-backend@0.3.6

### Patch Changes

-   f53fba29f: Adds @backstage/plugin-kubernetes-common library to share types between kubernetes frontend and backend.
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/plugin-proxy-backend@0.2.7

### Patch Changes

-   cdb3426e5: Prefix proxy routes with `/` if not present in configuration
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/config@0.1.5

 ## @backstage/plugin-rollbar-backend@0.1.10

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
    -   @backstage/backend-common@0.7.0
    -   @backstage/config@0.1.5

 ## @backstage/plugin-scaffolder@0.9.3

### Patch Changes

-   9314a8592: Close eventSource upon completion of a scaffolder task
-   d8b81fd28: Bump `json-schema` dependency from `0.2.5` to `0.3.0`.
-   Updated dependencies [38ca05168]
-   Updated dependencies [f65adcde7]
-   Updated dependencies [81c54d1f2]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/integration@0.5.2
    -   @backstage/core@0.7.8
    -   @backstage/plugin-catalog-react@0.1.5
    -   @backstage/theme@0.2.7
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11

 ## @backstage/plugin-search-backend@0.1.4

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
    -   @backstage/backend-common@0.7.0

 ## @backstage/plugin-tech-radar@0.3.10

### Patch Changes

-   b2e2ec753: Update README for composability
-   Updated dependencies [f65adcde7]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
    -   @backstage/core@0.7.8
    -   @backstage/theme@0.2.7

 ## @backstage/plugin-techdocs@0.9.1

### Patch Changes

-   2e05277e0: Fix navigation in a page using the table of contents.
-   4075c6367: Make git config optional for techdocs feedback links
-   Updated dependencies [38ca05168]
-   Updated dependencies [f65adcde7]
-   Updated dependencies [81c54d1f2]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [d8b81fd28]
    -   @backstage/integration@0.5.2
    -   @backstage/core@0.7.8
    -   @backstage/plugin-catalog-react@0.1.5
    -   @backstage/theme@0.2.7
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5

 ## @backstage/plugin-todo-backend@0.1.4

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/backend-common@0.7.0
    -   @backstage/integration@0.5.2
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11

 ## example-app@0.2.27

### Patch Changes

-   Updated dependencies [6f1b82b14]
-   Updated dependencies [38ca05168]
-   Updated dependencies [f65adcde7]
-   Updated dependencies [81c54d1f2]
-   Updated dependencies [80888659b]
-   Updated dependencies [7b8272fb7]
-   Updated dependencies [8aedbb4af]
-   Updated dependencies [fc79a6dd3]
-   Updated dependencies [f53fba29f]
-   Updated dependencies [b2e2ec753]
-   Updated dependencies [9314a8592]
-   Updated dependencies [2e05277e0]
-   Updated dependencies [4075c6367]
-   Updated dependencies [d8b81fd28]
    -   @backstage/plugin-cost-insights@0.9.0
    -   @backstage/plugin-catalog-import@0.5.5
    -   @backstage/plugin-github-actions@0.4.5
    -   @backstage/cli@0.6.10
    -   @backstage/core@0.7.8
    -   @backstage/plugin-catalog-react@0.1.5
    -   @backstage/theme@0.2.7
    -   @backstage/plugin-kubernetes@0.4.3
    -   @backstage/plugin-tech-radar@0.3.10
    -   @backstage/plugin-scaffolder@0.9.3
    -   @backstage/plugin-techdocs@0.9.1
    -   @backstage/catalog-model@0.7.8

 ## example-backend@0.2.27

### Patch Changes

-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [e0bfd3d44]
-   Updated dependencies [38ca05168]
-   Updated dependencies [b219821a0]
-   Updated dependencies [69eefb5ae]
-   Updated dependencies [f53fba29f]
-   Updated dependencies [75c8cec39]
-   Updated dependencies [227439a72]
-   Updated dependencies [cdb3426e5]
-   Updated dependencies [d8b81fd28]
-   Updated dependencies [d1b1306d9]
    -   @backstage/plugin-scaffolder-backend@0.11.0
    -   @backstage/backend-common@0.7.0
    -   @backstage/plugin-techdocs-backend@0.8.0
    -   @backstage/plugin-catalog-backend@0.8.2
    -   @backstage/plugin-kubernetes-backend@0.3.6
    -   @backstage/plugin-proxy-backend@0.2.7
    -   @backstage/catalog-model@0.7.8
    -   @backstage/config@0.1.5
    -   @backstage/catalog-client@0.3.11
    -   example-app@0.2.27
    -   @backstage/plugin-app-backend@0.3.12
    -   @backstage/plugin-auth-backend@0.3.9
    -   @backstage/plugin-badges-backend@0.1.3
    -   @backstage/plugin-code-coverage-backend@0.1.4
    -   @backstage/plugin-graphql-backend@0.1.7
    -   @backstage/plugin-kafka-backend@0.2.4
    -   @backstage/plugin-rollbar-backend@0.1.10
    -   @backstage/plugin-search-backend@0.1.4
    -   @backstage/plugin-todo-backend@0.1.4

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Review by OrkoHunter — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5533-zwvmisu84hpeeb34dotluusuwfujqjmr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608abe83a55c9a2764a4fb7f

**Review by jhaals — APPROVED** [review]

**Pull request merged**
