### PR TITLE
Upgraded microsite to Docusaurus 3.6

### PR DESCRIPTION
**Pull request by h7kanna**
## Docusaurus 3.6

New Docusaurus [release 3.6](https://docusaurus.io/blog/releases/3.6) enabled faster build mode.

Local testing shows 4x faster build

Docusaurus 3.1

``` 
[SUCCESS] Generated static files in "build".
[INFO] Use `npm run serve` command to test your build locally.
yarn build  334.31s user 18.74s system 95% cpu 6:09.22 total
```

Docusaurus 3.6

``` 
[SUCCESS] Generated static files in "build".
[INFO] Use `npm run serve` command to test your build locally.
yarn build  87.99s user 6.97s system 169% cpu 56.138 total

```

Need to test in the CI though and for regressions though.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by coreydaley** [comment]
95% cpu vs 169% cpu, I wonder if they changed something to enable multithreading?

**Comment by h7kanna** [comment]
Seems like 2x speed up compared to
https://github.com/backstage/backstage/actions/runs/11667719423/job/32485683602?pr=27390

**Review by awanlin — APPROVED** [review]
This is awesome, thanks for helping us stay on top of these changes @h7kanna 🚀

**Comment by awanlin** [comment]
> Hmm, seems like only 2x speed up (9m vs 19m) https://github.com/backstage/backstage/actions/runs/11667467502/job/32484849457?pr=27460 compared to https://github.com/backstage/backstage/actions/runs/11667719423/job/32485683602?pr=27390

That's still pretty good!

**Review by jhaals — APPROVED** [review]
Thanks a lot for taking the time to upgrade the microsite!

🚀

**Pull request merged**
