### PR TITLE
WIP: ErrorBoundary rewrite to TS

### PR DESCRIPTION
**Pull request by hooloovooo**
## Hey, I just made a Pull Request!

This is a rewrite of the ErrorBoundary to typescript

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] [CODEOWNERS](./CODEOWNERS) updated (for new stuff)
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by stefanalund** [comment]
Did you run Prettier? Some things look a bit off :)

**Comment by hooloovooo** [comment]
> Did you run Prettier? Some things look a bit off :)

I did, but i could have some issue in my prettier not reading the config. I'll investigate and see if i can find something.

**Review by freben — APPROVED** [review]
Looks good!

**Comment by hooloovooo** [comment]
Can't find anything wrong with prettify. I could be missing something, but maybe this is how it's supposed to look?

**Review by stefanalund — APPROVED** [review]

**Pull request merged**
