### PR TITLE
chore: Refactor Vale spell checking to better support local development

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

This PR refactors the Vale spell checking configuration in the project.

Currently, the config is in a subfolder which is directly referenced by a script which runs in CI.  This absolutely works.  However, it renders the local development value of the Vale config either useless, or very hard to configure (IMHO).

I just briefly noticed that my local Vale Extension in VS Code wasn't picking up spelling problems, and I discovered it's because of this config. (but it works in many other projects)  Clearly also I was not able to use the Vale CLI on the command line if I wanted to for a folder or an individual file, either. So the current config picks up errors in CI, but I would suggest to truly "shift left" we should let the devs get the value out of it locally as well to potentially avoid CI needing to catch errors at all.

This PR refactors it in the following ways:

* Moves the `.vale.ini` config back to the root.
    * The reason for this is Vale is very specific in how it works. It looks for a config file in the current working directory of any file you're trying to spell check, and then it [searches up 6 levels](https://vale.sh/docs/topics/config/#search-process). Because the config was placed in the `.github/` subfolder, it effectively will never trigger locally for any developer as it's never "upstream" of a change unless the change is made in that folder (which is rare).  (Edit: and/or the dev adds the `--config` flag themselves.)
* Adds an ignore to the check docs script for the `docs/reference/` subfolder.
    * This folder doesn't get checked in (its in the gitignore and generated at site publish runtime), so normally it's not needed in CI.
    * But I found running the command `node scripts/check-docs-quality.js` was pretty useful locally also, as a root `vale .` spell checks too much (exactly the point of the script). But I do have the reference folder locally, and so this just allows me to also run this script locally if I want to.
* I had to add an eslint ignore which may have been introduced prior to my change but the check docs script maybe hasn't been modified since an eslint rule (or config or version) was bumped?  Welcome any ideas/suggestion for how to fix that, but I believe it's definitely a devDependency as it stands today and so I didn't want to move that library to a main dependency.

#### VS Code Extension

:x: Doesn't do anything 

✅ VS Code Extension works!
image

#### CLI

❌ Current
image

✅ Current CLI works if user specifies a path; which they may rarely do? But to be fair, it does work
image

✅ CLI works!
image

#### CI

✅ CI works!
✅ CI *still* works! 😁 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by adamdmharvey** [comment]
...interesting, I don't see the verify docs workflow firing.  I know there was a legacy one which I see disabled in the Actions UI (but that workflow file doesn't exist anymore). Anyway, opening for review!

**Comment by adamdmharvey** [comment]
(oh i made no docs changes likely; lemme make a small one to see if I can fire CI to validate it catches a typo)

**Comment by adamdmharvey** [comment]
Ok awesome. At least pre-commit works. Leave it to the team if you'd have a recommendation if we want to test it a bit further or not, but would have to disable precommit hooks in Husky for that I guess?

image

**Comment by adamdmharvey** [comment]
@Rugvip Ah good catch. So actually, the main method was appending the config flag and the files, and then passing that to the runVale() method which ALSO added the config flag again (and just passed through the specified fileS). As a result, I think that was a duplicate and so removed one.

In addition, since the config is in the root now anyway, so long as the command is IN the root the config flag is no longer absolutely required, but I think it makes sense to keep it in the script for full clarity.

I made a change to remove it from the main routine, keeping it closer to the runVale routine and it remains to work locally.

Locally, I've tested with Vale v2.10.7, though I've also tested with the latest through the MacOS brew formula which is v2.21.3.  Interestingly, there's seems to be a problem after v2.10 which renders the Vale VS Code extension not to work (even though it remains working in CLI and via various CI i have internally, reference https://github.com/errata-ai/vale-vscode/issues/49), so I've kept pinned to v2.10 locally so I can keep using it on VS Code. I assume it'll be fixed upstream at some point!

**Review by Rugvip — APPROVED** [review]
Awesome! 😁 

Thank you for the extra context, sounds good, let's :shipit:

**Pull request merged**
