### PR TITLE
Move TechDocs project board

### PR DESCRIPTION
**Pull request by OrkoHunter**
## Hey, I just made a Pull Request!

Change the board URL in the GitHub workflow which adds new issues/PRs to the project.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by hooloovooo — APPROVED** [review]

**Comment by OrkoHunter** [comment]
@backstage/maintainers Do we have a `GITHUB_TOKEN` here in this repository's secrets?

**Comment by freben** [comment]
@OrkoHunter No we do not, but we didn't in the other one either. Isn't that the default-injected one that gets generated automatically?

**Review by freben — APPROVED** [review]

**Comment by OrkoHunter** [comment]
@freben Hmm, seems like things are different for an "org" project board.

Looking at https://github.com/srggrs/assign-one-project-github-action/blob/ee9e04cf29076579440cf7a149b0d5647467dc5b/README.md#organisation-or-user-project

> Generate a token from the Organisation settings or User Settings and add it as a secret in the repository secrets as MY_GITHUB_TOKEN

**Comment by OrkoHunter** [comment]
Let me try to use the default generated `GITHUB_TOKEN`. 🤞

**Comment by freben** [comment]
@OrkoHunter OK cool. I can help make a secret. But we probably should name it like `TECHDOCS_PROJECT_GITHUB_SECRET` or something if I understand it correctly? Suggestions welcome.

**Comment by OrkoHunter** [comment]
Hi @freben ! Yes, thank you! This thing needs your help. The default `GITHUB_TOKEN` that gets injected is not good enough to access an org board.

So we will need a token like `TECHDOCS_PROJECT_GITHUB_SECRET` as you mention, which has access to GitHub projects in this org.

Since we will copy this TechDocs workflow to all these TechDocs repositories, can you please add the secret to the following repo's secrets? 

- https://github.com/backstage/backstage
- https://github.com/backstage/mkdocs-monorepo-plugin
- https://github.com/backstage/techdocs-container
- https://github.com/backstage/techdocs-cli
- https://github.com/backstage/mkdocs-techdocs-core

Thank you so very much, in advance!

**Comment by OrkoHunter** [comment]
cc @Rugvip ^

**Comment by Rugvip** [comment]
@OrkoHunter secret is added at org level, called `GH_SERVICE_ACCOUNT_TOKEN`

**Comment by OrkoHunter** [comment]
It worked! :) Thank you @Rugvip @freben for the support. ❤️

**Pull request merged**
