### PR TITLE
Fixes issue #25011

### PR DESCRIPTION
**Pull request by Arup-Chauhan**
## Hey, I just made a Pull Request!

 @vinzscam @piatkiewicz , I have created this PR for working on the issue: https://github.com/backstage/backstage/issues/25011

Will fill up the details as I continue to work.
Thanks for the support so far guys!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Arup-Chauhan** [comment]
Update: found the issue in the Router component, working on resolving it soon to fix issue:
#25011

**Comment by Arup-Chauhan** [comment]
Hi!
For issue #25011  
I'm currently working on setting up routing for some components within a <MemoryRouter> tag. Specifically, I'm trying to provide the correct routing context for the AggregateMembersToggle and Default 

While it makes sense to use GroupProfileCard as an element within the route, it leads to issues with permission hooks

Any feedback or direction on:

- The appropriate routing tags and structure within <MemoryRouter> to provide context.

- Is it the right to integrate GroupProfileCard? If yes how we do it without permission issues.

- Any additional components or mock implementations needed to resolve these issues.


@Rugvip  @camilaibs @iamEAP @vinzscam , I would really appreciate any sort of help on this.

**Comment by camilaibs** [comment]
> Hi! For issue #25011 I'm currently working on setting up routing for some components within a tag. Specifically, I'm trying to provide the correct routing context for the AggregateMembersToggle and Default
> 
> While it makes sense to use GroupProfileCard as an element within the route, it leads to issues with permission hooks
> 
> Any feedback or direction on:
> 
> * The appropriate routing tags and structure within  to provide context.
> * Is it the right to integrate GroupProfileCard? If yes how we do it without permission issues.
> * Any additional components or mock implementations needed to resolve these issues.
> 
> @Rugvip @camilaibs @iamEAP @freben @vinzscam , I would really appreciate any sort of help on this.

Replied here: https://github.com/backstage/backstage/issues/25011#issuecomment-2211681184

**Comment by Arup-Chauhan** [comment]
Hi all, I am marking this PR ready for review, this fixes issue #25011 

As suggested by @camilaibs , I have added the TestApp for giving missing routing context and removed the MemoryRouter to avoid conflicts.

The issue is fixed, the Group Member List Card components are properly coming up now.

Thanks @vinzscam @piatkiewicz for help

Tagging a few maintainers for review
@Rugvip @mtlewis @benjdlambert 

Please let me know if anything else is needed to be done, cheers!



Refrence images added.

Screenshot 2024-07-21 004102
Screenshot 2024-07-21 004056
Screenshot 2024-07-21 004050

**Pull request closed without merging**
