### PR TITLE
Improve Badges Frontend README

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Added more details on how to get the Badges plugin setup

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by julioz** [comment]
Since we're here, would you mind adding a screenshot of what this plugin (and badges) are about? I find it a bit hard to see how they fit with the catalog specially for folks that haven't used badging before.

**Comment by awanlin** [comment]
@julioz for sure, it was on my mind to do the first time around but missed it as I worked on the text. I've updated it just now to add some screenshots and example badges. 

We use badges to help signal to people that there is more information in Backstage. We've added badges in various spots throughout our Wikis and SharePoint sites. This has helped raised usage of Backstage over some of the legacy tools we have and help form new habits. Hope that helps you get a better idea of how you might use them?

**Review by julioz — APPROVED** [review]
Thanks, super clear now

**Review by Rugvip — COMMENTED** [review]
Thank you, looks good! 👍 

Once thing to fix as afar as I know is to include the images in the published package, or they won't show up properly on NPM etc. Should be fine to include the entire `docs` folder in the `"files"` field in `package.json`

**Comment by awanlin** [comment]
Ok, cool. I'll do that. I looked at a few of the other plugins and it was done a little differently in each so wasn't sure the right pattern

**Comment by awanlin** [comment]
I've added the `doc` folder to the `package.json` and did a quick `npm pack` to confirm and the images are there now:

image

**Comment by Rugvip** [comment]
👍, fix for the diff check is now landed in master, so a sync should get CI green

**Comment by awanlin** [comment]
@Rugvip based on our Discord chat yesterday I added the repo details and removed `doc` from the `files` section

**Review by Rugvip — APPROVED** [review]

**Pull request merged**
