### PR TITLE
[Proxy-Backend] Feature: Revive Request Bodies

### PR DESCRIPTION
**Pull request by dhoizner**
## Hey, I just made a Pull Request!

When consuming the incoming request body via a middleware that executes prior to `http-proxy-middleware`, e.g. by including `express.json()` in the middleware chain as in the example below, the request body is not available to be proxied.
```js
apiRouter.use('/proxy', express.json(), await proxy(proxyEnv));
```
In order to support  proxying requests with bodies that have previously been consumed, the proxy config can now specify `reviveRequestBody: true` in order to propagate the previously consumed body to the proxied request.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hi! Interesting. Hm. It seems to me that this might not need to be on a per-route basis, right? Two options:

- ALWAYS revive, betting on this being the right behavior in the vast majority of cases
- Make it a static option [to the plugin creation entry point itself](https://github.com/backstage/backstage/blob/3c637aea57b54e910ec6b87cc2e8cf59542a9dac/plugins/proxy-backend/src/service/router.ts#L200) so you get to choose

Do these make sense?

**Comment by freben** [comment]
One more thing. A `patch` level changeset is enough for stuff that's not breaking, on a 0.x version package.

**Comment by dhoizner** [comment]
@freben yup, makes sense to me! i was leaning pretty heavily on keeping existing behavior, but i don't really see a reason why fixing the body would be undesirable if it were already consumed.

thanks for the clarification on `patch` v `minor` :) 

i'll work on these changes today, one more thing- i noticed that [`plugin.ts`](https://github.com/backstage/backstage/blob/3c637aea57b54e910ec6b87cc2e8cf59542a9dac/plugins/proxy-backend/src/plugin.ts) is being worked on, which i'm assuming is what will be used in the future to mount the proxy plugin once it exits alpha/beta- should i go ahead and add the flag there as well?

**Comment by dhoizner** [comment]
> Hi! Interesting. Hm. It seems to me that this might not need to be on a per-route basis, right? Two options:
> 
> * ALWAYS revive, betting on this being the right behavior in the vast majority of cases
> * Make it a static option [to the plugin creation entry point itself](https://github.com/backstage/backstage/blob/3c637aea57b54e910ec6b87cc2e8cf59542a9dac/plugins/proxy-backend/src/service/router.ts#L200) so you get to choose
> 
> Do these make sense?

@freben Pulled the configuration into the `RouterOptions` and added/cleaned up tests accordingly. Also dropped the changeset down to `patch` level. Let me know if anything else is missing!

**Review by freben — APPROVED** [review]
Nice!

**Pull request merged**
