### PR TITLE
Fix tabindex to make accessible search better

### LINKED ISSUE #17610: 🐛 Bug Report: Keyboard navigation to search filters
### 📜 Description

Using keyboard navigation, its not possible to navigate to the second filter group on the Search page and check "experimental" or "production" check boxes.

### 👍 Expected behavior

Be able to check "experimental" or "production" check boxes using keyboard navigation

### 👎 Actual Behavior with Screenshots

When navigating to search filters it skips over the second filter group and takes me to the search results directly after the select filters. 

Screenshot 2023-04-28 at 11 52 13

### 👟 Reproduction steps

Go to https://demo.backstage.io/search?query=&types%5B%5D=software-catalog

1. use your keyboard only to navigate through the page.
2. try to check the "experimental" or "production" check boxes

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by siddhant1**
Fixes #17610

### CODE REVIEW

**Comment by emmaindal** [comment]
Hello @siddhant1 thank you for the contribution 💯 

Can you look into signing off your commit ([instructions in the failed DCO check](https://github.com/backstage/backstage/pull/17897/checks?check_run_id=13657229433)) and add a changeset ([how to create a changeset](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#how-to-create-a-changeset)) to this PR as well. Thank you!

**Comment by camilaibs** [comment]
Reopening and retesting it.

**Review by camilaibs — APPROVED** [review]
Looks great to me, thank you for contributing 🎉

**Comment by camilaibs** [comment]
> Hello @siddhant1 thank you for the contribution 💯
> 
> Can you look into signing off your commit ([instructions in the failed DCO check](https://github.com/backstage/backstage/pull/17897/checks?check_run_id=13657229433)) and add a changeset ([how to create a changeset](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#how-to-create-a-changeset)) to this PR as well. Thank you!

Thank you Emma, I added the changeset and fixed the commit 🙌🏻

**Comment by camilaibs** [comment]
@backstage/maintainers do you have any clue about the E2E bugs?

**Pull request merged**
