### PR TITLE
chore(docs): Improve wording on TechDocs how to page

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

This is some minor wording improvements to the TechDocs how to page. While there, I found a few uses of TechDocs without camel case, and some dependency versions which could use a bump.

Trivial but just slightly improving the wording on the DOM library part!

Note: ideally, some of these code fences should be indented so they properly line up with their parent in an ordered list. However, looks like prettier always forces code fences back to column 1 if there's any whitespace around them. Wasn't able to work around that but something for the longer term!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by adamdmharvey** [comment]
The auto-prettier re-outdented my code fence indents because it must interpret them not to be part of the ordered lists. Hmm.... taking a quick look offline at a way to fix.

**Comment by adamdmharvey** [comment]
bump?

**Comment by adamdmharvey** [comment]
🥺 bump?

😀

**Review by freben — APPROVED** [review]
Haha, oh for sure.

**Review by agentbellnorm — APPROVED** [review]

**Pull request merged**
