### PR TITLE
Add lock:check command to ensure correct registries

### PR DESCRIPTION
**Pull request by joaomilho**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thanks! 👍, just need that DCO

Would it make sense to add the CI check to the microsite workflow as well?

**Comment by joaomilho** [comment]
> Would it make sense to add the CI check to the microsite workflow as well?

The script checks all yarn.locks from the root folder, so it's not needed.

**Comment by Rugvip** [comment]
@joaomilho The main CI isn't run for microsite changes though, so the check won't be run at all

**Comment by Rugvip** [comment]
Want to set it up for the microsite as well or should we :shipit:?

**Comment by joaomilho** [comment]
> Want to set it up for the microsite as well or should we :shipit:?

on it

**Review by freben — APPROVED** [review]
Looks good but ... now it has a yarn.lock collision again!

**Comment by freben** [comment]
and this is as needed as ever :) https://github.com/backstage/backstage/pull/5922

**Comment by freben** [comment]
aight i rebased and fixed it up, let's see if we can ship it before the weekend

**Pull request merged**
