### PR TITLE
Added docs for knex pool config

### PR DESCRIPTION
**Pull request by sharadpattanshetti**
Signed-off-by: sharadpattanshetti <43475650+sharadpattanshetti@users.noreply.github.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by sharadpattanshetti** [comment]
Hi @freben, created new PR with the changes to documentation on overriding the Knex Pool configuration. 
Please review and approve. 

FYI - @benjdlambert

**Comment by benjdlambert** [comment]
Gonna link this to #10868 also, as I think really it's pretty unfortunate that users that run things in production have to have this config in the first place. I think that the root cause is that because of how the scaffolder works, it doesn't poll the DB and the queue, it waits for a ping and a promise resolution in process when a task is created. This method, although it works, probably should be moved over to ping the DB too like the catalog, but it's also brought to the surface an underlying issue that the when the connections get killed because they're idle, they don't reconnect unless there is a pool available. The pool config is a great suggestion and we should recommend it for production, but I think that we should also be sending some keepalive / heartbeat down the connections to make sure of two things. 1) that we are able to connect to the DB, otherwise we need to be alerting the user that either out network is down, or the DB is down. 2) that we keep the connection active and fresh so that it doesn't get to this timeout limit from the cloud providers and DB hosts.

**Comment by benjdlambert** [comment]
Also just fixed up the prettier stuff that was missing to make this PR green ✅

**Comment by sharadpattanshetti** [comment]
> Also just fixed up the prettier stuff that was missing to make this PR green ✅

Thanks @benjdlambert, sorry could not recognize extra spaces. Completely agree with above 2 points mentioned by you, along with that we also need validate the connection before passing it to catalog or scaffolder tasks. 


The knex pool config that really worked for us was this : 

 database:
      client: pg
      connection:
        database: backstage_plugin_catalog
        host: <host>
        user: <user>
        port: 5432
        password: <password>
        ssl:
          rejectUnauthorized: false
          ca:
      **knexConfig:**
        pool: 
          **min: 0**
          max: 15 
          acquireTimeoutMillis: 60000
          idleTimeoutMillis: 60000

**Review by Rugvip — APPROVED** [review]
Thank you! 👍 

As @benjdlambert mentions it's an unfortunate workaround. This doc addition is pretty self contained though and gives a generic explanation of the pool configuration format, so let's :shipit:

**Comment by suuus** [comment]
Hey @sharadpattanshetti, congrats on your first merged PR 🎉 Nice work 👍 Please let me know if we can be helpful in any way.

**Comment by sharadpattanshetti** [comment]
> 

Thank you @suuus, not much as of now. Thanks @benjdlambert , @freben and @Rugvip for the guidance.

**Comment by iriswang233** [comment]
Hi @sharadpattanshetti

Does statement_timeout setup work under database.connection in app-config.yaml file? I followed this https://node-postgres.com/api/client mentioned in docs/tutorials/switching-sqlite-postgres.md
[p](https://node-postgres.com/api/client)

**Pull request merged**
