### PR TITLE
plugins: remove identity-backend

### PR DESCRIPTION
**Pull request by Rugvip**
Not used, and we're heading down the route of identities in the catalog

### CODE REVIEW

**Comment by JacobValdemar** [comment]
I don't know anything about this plugin, but to me it sounds weird that the service catalog should have the responsibility of handling identity - at least a conspicuous coupling

**Comment by Rugvip** [comment]
@JacobValdemar go more info on that here: https://github.com/spotify/backstage/issues/1401

**Comment by Rugvip** [comment]
@JacobValdemar wanna elaborate on the concern though?

**Review by freben — APPROVED** [review]
This may warrant a changelog entry :)

**Comment by Rugvip** [comment]
@freben tru dat

**Comment by JacobValdemar** [comment]
@Rugvip I will have a look at #1401 on Monday and respond then if it's okay? 🙂 Since it's closed I'll assume that you guys already have thought it through, so maybe my concern is redundant 😉

**Comment by Rugvip** [comment]
@JacobValdemar definitely! Very little of it has actually been implemented, we've mostly gotten some high-level docs and schema in place, so still plenty of time to impact things :grin:

**Pull request merged**
