### PR TITLE
[gcp-projects] fix query params for links pointing to "GCP" & "Logs" in Project Details Page

### PR DESCRIPTION
**Pull request by dimisjim**
## Hey, I just made a Pull Request!

Fixes: https://github.com/backstage/backstage/issues/21150

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — APPROVED** [review]
nice!

**Comment by dimisjim** [comment]
can we merge this?

**Comment by dimisjim** [comment]
bump @Rugvip

**Comment by dimisjim** [comment]
bump

**Review by freben — APPROVED** [review]

**Pull request merged**
