### PR TITLE
Add pattern matching support to entity search filter

### PR DESCRIPTION
**Pull request by stephenglass**
## Hey, I just made a Pull Request!

Adds a new optional `patterns` option to the entity search filter to match values on SQL pattern expression. Currently, the only option for filtering is passing in array of `values` which performs a basic equality check.

You may use `patterns` without providing `values` or you can provide both in which case you will return any values that match `values` equality check OR `values` pattern match. Pattern matching will be case insensitive.

Examples:
```typescript
// filter based on patterns only
const filter = {
  key: 'metadata.annotations.backstage.io/managed-by-location',
  // we don't care where the catalog-info.yml file is, only the repo its in
  patterns: ['url:https://github.com/x/y%', 'url:https://github.com/x/z%'],
};

// filter based on value equality or pattern matching
const filter = {
  key: 'metadata.name',
  // return values that match 'superuser-entity' or any entity that starts with 'admin-'
  values: ['superuser-entity'],
  patterns: ['admin-%'],
};
```

Motivation:
We've created a custom permission policy that allows read access to catalog entities only if a user is a member of a GitHub team that provides such access. To do this we need to map a list of GitHub repo slugs to entities using the `backstage.io/managed-by-location` annotation which is a URL pointing to `catalog-info.yml` file on GitHub. The only way we found to do this mapping is to use Catalog API to get list of all entities, iterate thru them and pattern match on the annotation. Then we can use the list of matched entities to create a conditional decision based on annotation value. Fetching every catalog entity and running this pattern matching for each policy check is not scalable.

If this PR is merged, instead of getting list of all entities and doing pattern matching, we can simply create a new permission rule that accepts an array of patterns in the `toQuery` implementation to match GitHub repos. I.e: `patterns: ['url:https://github.com/XX/YYYY%, ...]`.

Please let me know any feedback or changes requested!!! Thanks!!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — CHANGES_REQUESTED** [review]
Thank you for describing your use case, it really helps understanding the problem.

Can't you create a processor that reads `managed-by-location`, read the pattern you want, and store it in the entity? Then you could use of the existing rules such as `hasMetadata` to filter out the results

**Comment by freben** [comment]
Hi! I've added this to our board for discussion. You haven't been forgotten.

**Comment by stephenglass** [comment]
Not stale

**Comment by freben** [comment]
See [this related comment](https://github.com/backstage/backstage/pull/25419#issuecomment-2227043463). I realize this PR only targets the backend code at this point, but the follow-up question will be, how do we expose this feature to the outside world? In the catalog client / REST API, we will want to make sure to serialize queries differently before exposing more features. Marking as blocked for now, but not abandoning it.

**Review by Rugvip — CHANGES_REQUESTED** [review]
Wanted to make sure the expectations here are clear: Overall we want to make this change in some form, but it needs to consider the full e2e usage, especially what the HTTP API looks like. The behavior and syntax that we decide on in the DB querying logic will bleed out into the higher level APIs.

Unfortunately we're not currently in a position to be able to properly pick up and facilitate this work. It really does need a [BEP](https://github.com/backstage/backstage/tree/master/beps), but we are unlikely to accept that either at this point as we're focused on other parts of the project right now.

That's the current state and I expect it to remain for at least 3 months or so, after which we may be in a different position, but no guarantee that we'll be able to prioritize this work then either. I do think it's likely that we'll want to work in this area in the next 1-2 years, but that's about as much as I'm able to guess at this point 😅

Sorry to be a buzzkill 😞

**Pull request closed without merging**
