### PR TITLE
fix: Avoid infinite loop in the NotificationsSidebarItem title counter

### LINKED ISSUE #24866: 🐛 Bug Report: Notifications plugin: Slow loading of pages when unread notifications are present
### 📜 Description

All pages (not just the notifications page) seem to take much longer to load than usual when there are unread notifications, and sometimes they can get stuck loading for more than 10 seconds. The entire Backstage application may also start responding slowly (lagging).

The problem goes away when all notifications are marked as read.

### 👍 Expected behavior

The presence of unread notifications should not affect the loading times of all pages and cause the app to respond slowly.

### 👎 Actual Behavior with Screenshots

The presence of unread notifications increases the loading times of all pages and causes the app to respond slowly.

### 👟 Reproduction steps

1) Send a notification to any user.
2) Login as the above user and navigate to the Notifications page (do not mark the notification as read yet).
3) Refresh the page and navigate around the app to other pages to observe the performance.
4) Mark the notification as read, refresh the page and observe the performance again.

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

```
OS:   Linux 5.15.146.1-microsoft-standard-WSL2 - linux/x64
node: v18.19.0
yarn: 1.22.19
cli:  0.26.4 (installed)
backstage:  1.26.5

Dependencies:
  @backstage/app-defaults                                          1.5.4
  @backstage/backend-app-api                                       0.7.2
  @backstage/backend-common                                        0.21.7
  @backstage/backend-defaults                                      0.2.17
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.10
  @backstage/backend-plugin-api                                    0.6.17
  @backstage/backend-tasks                                         0.5.22
  @backstage/backend-test-utils                                    0.3.7
  @backstage/catalog-client                                        1.6.4
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.4
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.4
  @backstage/core-compat-api                                       0.2.4
  @backstage/core-components                                       0.14.6
  @backstage/core-plugin-api                                       1.9.2
  @backstage/dev-utils                                             1.0.31
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.7
  @backstage/frontend-plugin-api                                   0.6.4
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.26
  @backstage/integration                                           1.10.0
  @backstage/plugin-api-docs                                       0.11.4
  @backstage/plugin-app-backend                                    0.3.65
  @backstage/plugin-app-node                                       0.1.17
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.9
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.9
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.0
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.12
  @backstage/plugin-auth-backend-module-github-provider            0.1.14
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.14
  @backstage/plugin-auth-backend-module-google-provider            0.1.14
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.12
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.14
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.10
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.8
  @backstage/plugin-auth-backend-module-okta-provider              0.0.10
  @backstage/plugin-auth-backend                                   0.22.4
  @backstage/plugin-auth-node                                      0.4.12
  @backstage/plugin-auth-react                                     0.1.1
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.15
  @backstage/plugin-catalog-backend-module-ldap                    0.5.33
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.15
  @backstage/plugin-catalog-backend                                1.21.1
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.4
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.11.1
  @backstage/plugin-catalog-react                                  1.11.3
  @backstage/plugin-catalog                                        1.19.0
  @backstage/plugin-events-backend-module-aws-sqs                  0.3.3
  @backstage/plugin-events-backend                                 0.3.4
  @backstage/plugin-events-node                                    0.3.3
  @backstage/plugin-home-react                                     0.1.12
  @backstage/plugin-home                                           0.7.3
  @backstage/plugin-notifications-backend                          0.2.0
  @backstage/plugin-notifications-common                           0.0.3
  @backstage/plugin-notifications-node                             0.1.3
  @backstage/plugin-notifications                                  0.2.0
  @backstage/plugin-org                                            0.6.24
  @backstage/plugin-permission-backend                             0.5.41
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.28
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.15
  @backstage/plugin-scaffolder-backend-module-azure                0.1.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.7
  @backstage/plugin-scaffolder-backend-module-github               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.3
  @backstage/plugin-scaffolder-backend                             1.22.5
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.3
  @backstage/plugin-scaffolder-react                               1.8.4
  @backstage/plugin-scaffolder                                     1.19.3
  @backstage/plugin-search-backend-module-catalog                  0.1.23
  @backstage/plugin-search-backend-module-pg                       0.5.26
  @backstage/plugin-search-backend-module-techdocs                 0.1.22
  @backstage/plugin-search-backend-node                            1.2.21
  @backstage/plugin-search-backend                                 1.5.7
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.10
  @backstage/plugin-search                                         1.4.10
  @backstage/plugin-signals-node                                   0.1.3
  @backstage/plugin-signals-react                                  0.0.3
  @backstage/plugin-techdocs-backend                               1.10.4
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.9
  @backstage/plugin-techdocs-node                                  1.12.3
  @backstage/plugin-techdocs-react                                 1.2.3
  @backstage/plugin-techdocs                                       1.10.4
  @backstage/plugin-user-settings                                  0.8.5
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.8.0
  @backstage/test-utils                                            1.5.4
  @backstage/theme                                                 0.5.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by mareklibra**
## Hey, I just made a Pull Request!

Fixes #24866

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by alexef** [comment]
wrong fixes tag?

**Review by freben — COMMENTED** [review]
Does this really fix the problem? It seems to me that it would only slow things down a bit but still be in an infinite loop.

The `MutationObserver`, if I understand things correctly, will react to the `document.title` assignment, call `setTitle`, and trigger a render loop. It would seem to me that the proper fix is something that makes it so that this loop doesn't happen in the first place, making the throttle unnecessary.

Is it the case that `count` should be the only `useState`, and `title` should be in a `useRef` to move it outside of the render behaviour (and only containing the "cleaned" title)?

**Comment by freben** [comment]
And hmm - I wonder if there's actually a way of using something like a `<Helmet titleTemplate="%s"` or something like that to let Helmet manage the title instead of us poking at it.

**Comment by mareklibra** [comment]
The so far proposed "fix" breaks the infinite loop by a delayed change which prevents Helmet to reset the value.
I have tested it and it converges. However, it's nasty.

The former implementation of the Notification counter did the same, this "fix" just changes cadence and timing.

I agree the clean solution is to change either the  props of the  `<Helmet>` or it's `<title>` child. Those are referenced through the `<Header>` core component on **multiple** pages.

**Comment by mareklibra** [comment]
A proper solution can compose the title in the `<Header>` component.

@freben What do you think about introducing a new React context for page-related properties which can be set by components down in the hierarchy? So far there will be just `titlePrefix` and it's setter function, but this can grow for other use-cases.

The context would be instantiated in the `packages/core-components/src/layout/Page/Page.tsx`, so both the `<Header>` and children of `<Content>` can access it.

The `<NotificationsSidebarItem>` and its `useTitleCounter()` will set the value and just the `<Header>` will compose the text.

**Comment by freben** [comment]
@mareklibra I'm out sick - my thought here is, maybe go back to the small scoped fix only in the actual file so we can merge it before the release tomorrow. Let's worry about redesigns separately. Then maybe ping the others for review

**Comment by mareklibra** [comment]
@freben get well soon. So I will remove the later commit and keep the change isolated. I will open another PR using a React context and we can discuss that there.

**Review by Rugvip — APPROVED** [review]
Yep short-term fix for now sounds good 👍 

`Page` context approach is definitely a lot trickier and needs careful consideration, so let's get this in for today's release

**Pull request merged**
