### PR TITLE
fixing the SonarQube case in backend plugin readme

### PR DESCRIPTION
**Pull request by Ritesh007**
## Hey, I just made a Pull Request!

The SonarQube backend plugin config https://github.com/backstage/backstage/blob/bc51b8b7a0f3074bcf1cff5f8479e132727a71f6/plugins/sonarqube-backend/config.d.ts#L19 states that the SonarQube case is 'sonarQube' but the README suggests the case as 'sonarqube'. Using either of the cases didn't error out but when we tried to run the config-check with --strict it errors out for the case.

This PR is to fix the case in the README to reflect the same case from the config file. 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by adamdmharvey — APPROVED** [review]
huzzah!  excited for my Cisco colleague @Ritesh007 on his first Backstage PR 😁

**Review by jhaals — CHANGES_REQUESTED** [review]
Nice! Let's add a `patch` changeset for this package saying `Updated installation instructions`. That will make sure that the readme on NPM will contain your fixes.

**Comment by Ritesh007** [comment]
The issue here doesnt seem to be with the readme rather it's with the sonarQube case in the config.

**Comment by adamdmharvey** [comment]
Replaced with -> https://github.com/backstage/backstage/pull/18266

**Pull request closed without merging**
