### PR TITLE
sonarqube: Tweak proxy instructions

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

In a threaded discussion on #3994, some talk about what maybe the example should say to help avoid confusion.  This aligns it.

Note (almost!) all of the sample proxy configs in the default `app-config.yaml` also call their proxy paths `/product/api` so this helps drive up that consistency as well.

https://github.com/backstage/backstage/blob/master/app-config.yaml#L22

cc @dhenneke @regicsolutions

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by dhenneke** [comment]
This change would make it incompatible with the implementation (https://github.com/backstage/backstage/blob/0a7852f4e523af299b97042c68ea7ad4227b4280/plugins/sonarqube/src/api/SonarQubeClient.ts#L38). Of course, one could also change that, but it would be breaking for current users.

**Comment by adamdmharvey** [comment]
ah i see what you mean!! great catch, thank you. (don't have Sonar on my Docker instance at the moment)

**Comment by adamdmharvey** [comment]
Let's keep this to JUST the statement to avoid code change for now. I think the wording "SonarQube API end point" is what helps drive it for me (i.e., that's it's not an FQDN host it's looking for).  What do you think?

**Review by dhenneke — APPROVED** [review]
Yep thanks. Let's see if this already helps new adopters. If it comes up again, we should think again to align it.

**Comment by freben** [comment]
I was never sure about that /api convention :) Doesn't feel particularly important or useful to me, but probably just missed some discussions around it.

**Comment by dhenneke** [comment]
They are part of the proxy backend after all, so what else should they be other than api endpoints.

**Comment by freben** [comment]
@adamdmharvey Just double checking - is this the full extent of the change? That one line? I thought from the discussions that there might be more coming

**Review by freben — APPROVED** [review]
approving in case it's done :)

**Comment by adamdmharvey** [comment]
Yep, think this is is given @dhenneke 's good feedback as well. Bottom line, I think what was confusing was the user replaced with their FQDN, but in fact the config can't use FQDN and needs to point to the Api endpoint of SonarQube. So while this doesn't "fix" anything, per se, it's just a minor update to hope to make that a bit more clear to other users who may try to follow the config instructions.

**Comment by adamdmharvey** [comment]
Merging and we can ALWAYS iterate, iterate, iterate....

**Pull request merged**
