### PR TITLE
Update vale vocabulary to unify company and product names

### PR DESCRIPTION
**Pull request by dhenneke**
I unified the use of terms like "GitHub", "GitLab" or "JavaScript". Since the changelogs are fed from commit messages, I assume that this might get problematic in future releases.

Do you think this is a good or a bad idea?

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by OrkoHunter** [comment]
It might not be a bad idea to leverage Vale for always using the name of a company/product in its preferred styling. Folks who don't have Vale installed (most new contributors), will not encounter the error locally - but when the PR is created, CI will fail.

**Comment by andrewthauer** [comment]
I have noticed that the lower case variants of github are required in docs that use urls. So I'm not sure that removing those makes sense unless there is a workaround that I'm not aware of.

**Comment by freben** [comment]
Yeah the drawback is that then you would have to make sure to backtick-quote every single occurrence of the lowercase variant to get rid of the warning. Maybe that does encourage better writing practices? But I don't know how that translates to for example doc-comments inside ts code?

**Comment by freben** [comment]
That being said, looking at the change, it does improve things and obviously wasn't very dramatic to introduce even after the fact. Soooo ... leaning towards accepting this

**Comment by dhenneke** [comment]
When I understand it correctly, vale should be able to understand the semantics of something being an Url. This will get tricky when one generates the API from ts-docs (or what that is called), but then the PR doing that could take care of fixing the invalid spellings.

**Review by freben — APPROVED** [review]

**Comment by andrewthauer** [comment]
It might just be raw hyperlinks or doesn't understand. I'm pretty sure I tried back ticks and vale still complained. Maybe using a proper markdown anchor works?

**Pull request merged**
