### PR TITLE
Update template.examples.ts, typo fix on skeleton

### PR DESCRIPTION
**Pull request by ManuInNZ**
Very small typo fix.
Might not need the all rigour below  

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@ManuInNZ thanks for this, but we're going to need a `patch` changeset for this package.

See [CONTRIBUTING.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets) for more information about how to add changesets.

**Comment by ManuInNZ** [comment]
Yes boss.

Just need a bit of spare time and I will `yarn` the change set. 

Cheers
Manu

**Review by ManuInNZ — COMMENTED** [review]
Voila

**Review by tudi2d — CHANGES_REQUESTED** [review]
Thanks for fixing the typo in the example template. Please remove the `.devcontainer` folder from this commit & fix the typo in your changelog, than this should be good to go! :)

**Comment by ManuInNZ** [comment]
Well at least in the process of fixing a small typo, I learned to fix mines too and hopefully will create a better PR next time.
Cheers

**Review by awanlin — APPROVED** [review]
Awesome! Thanks for the correction @ManuInNZ 🚀

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks :tada:

**Pull request merged**
