### PR TITLE
Add info about our Artifactory plugins to the marketplace

### PR DESCRIPTION
**Pull request by antweiss**
## Hey, I just made a Pull Request!

This adds the information about the Artifactory plugin suite to the plugin marketplace.
The difference from the existing Artifactory plugins is that this is frontend+backend and the backend is using the official [Jfrog js-client](https://github.com/jfrog/jfrog-client-js)
So the plan is to evolve it to be the backend for additional Jfrog integrations

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Thanks for the contribution @antweiss, looks good to me! 🚀 

One side comment: as this is the 3rd Artifactory plugin it would be helpful to have some images in the docs to show off the features and functionality of the plugin and to help differentiate it from the others

**Comment by awanlin** [comment]
Oh, looks like you need to run prettier on this file as that's what's causing the build to fail.

Also, not sure what happened but your PR description is blank 🤔

**Comment by antweiss** [comment]
> Thanks for the contribution @antweiss, looks good to me! 🚀
> 
> One side comment: as this is the 3rd Artifactory plugin it would be helpful to have some images in the docs to show off the features and functionality of the plugin and to help differentiate it from the others

Will add images in the docs shortly.
but the main difference is this being frontend plus backend and using the jfrog-js-client for deeper integration with Jfrog.

**Comment by antweiss** [comment]
Updated the docs: https://github.com/StageCentral/backstage-artifactory-plugin/tree/main#readme

**Comment by awanlin** [comment]
Hi @benjdlambert @camilaibs this is good to go, just needs your approval and merge 🚀

**Review by freben — APPROVED** [review]
I can go!

**Comment by awanlin** [comment]
Thanks @freben! 🚀 

@antweiss just a heads up this should show up in the Plugin Marketplace in the next few hours 👍

**Pull request merged**
