### PR TITLE
docs: Fix typos in architecture-overview

### PR DESCRIPTION
**Pull request by fengypants**
## Hey, I just made a Pull Request!

Noticed a couple of minor typos/grammar issues in the new section with the package architecture diagram. (Also changed the spelling of "builtin" to "built-in" later on in the same doc.)

#### :heavy_check_mark: Checklist

- [:heavy_check_mark:] Added or updated documentation
- [:heavy_check_mark:] All your commits have a `Signed-off-by` line in the message.

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thank you! 😁 ❤️

**Comment by fengypants** [comment]
Drat. I've been having issues with Prettier over here, thought I got it sorta working. Will keep troubleshooting.

**Comment by Rugvip** [comment]
@fengypants ah shiet, I could format it for you if you like. If you're running prettier from the commandline then it'd be this:

```
yarn prettier --write docs/overview/architecture-overview.md
```

If it's in an editor I'm less sure how to fix that 😅

**Comment by fengypants** [comment]
Gave the command line a shot, that didn't work, either. Tried reinstalling some stuff, didn't work. I'm sure it's something very obvious! Anyway, will try to figure it out. But thanks for sorting this one out.

**Pull request merged**
