### PR TITLE
Handle incorrect return type from Octokit paginate plugin

### LINKED ISSUE #12761: Error reading GitHub URLs
## Expected Behavior

GitHub Discovery and URL reading should work without issue when using GitHub Apps.

## Actual Behavior

Receiving errors when trying to create Location entities.

```
[1] 2022-07-20T17:51:54.360Z catalog warn Unable to read url, TypeError: Cannot read properties of undefined (reading 'some') type=plugin entity=location:default/generated-06fa68e2c829fc2780525e800261d718fa7da58f
```

## Steps to Reproduce

1. Have Backstage configured to use GitHub Apps for GitHub integration
2. Configure a `github-discovery` Location or add a `url` location that is a GitHub URL.
3. Run Backstage
4. Error output from the catalog when it attempts to create Location entities

## Context

We didn't have an issue until we updated to 1.4.0.

- I [tracked down the commit](https://github.com/backstage/backstage/commit/9de15a41d73bba3b65318de7419bf1e43a17acfc) in Backstage that seems to have introduced this issue
- I also [found a related issue](https://github.com/octokit/plugin-paginate-rest.js/issues/350) (the type definitions appear to be off) which includes a functional workaround

image

### PR DESCRIPTION
**Pull request by ericvoshall**
## Hey, I just made a Pull Request!

Handle an issue with an incorrect return type from the Octokit paginate plugin. This fixes #12761.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Is this something to do with the code requiring a later version of octokit than what you have installed or are the types outdated? It would be interesting to know a little more what's going on here.

**Review by benjdlambert — APPROVED** [review]
Let's get this in for now, as I want to get this fixed and shipped for tomorrow at least.

**Comment by benjdlambert** [comment]
Thanks for this! :pray:

**Comment by nodify-at** [comment]
@benjdlambert do you plan to release a hotfix for this change or should we use the next version? Our catalog scanning is failing because it can not handle the repositories.

**Comment by benjdlambert** [comment]
1.5 is planned for next week, so we will release it then. If you need it sooner then feel free to jump on the `next` release train. Using `backstage-cli versions:bump --release next` should work 🤞

**Comment by mwz** [comment]
Any chance this could be released as a patch in the 1.4 series?

**Comment by nodify-at** [comment]
@mwz I didn't try it but you can force via yarn to user the older octokit version. 
`"@octokit/rest": "^18.12.0"`

**Pull request merged**
