### PR TITLE
Enable Postgres Search Module only on Supported Databases

### PR DESCRIPTION
**Pull request by szubster**
…orted databases

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by szubster** [comment]
Is there other way to enable it conditionally, like in example in [docs](https://backstage.io/docs/features/search/search-engines/#postgres)?

**Comment by szubster** [comment]
This is not at all stale. Waiting for a review, or some other way to achieve the end goal of conditionally enabling this module.

**Comment by szubster** [comment]
Please remove stale. I am waiting for review.

**Comment by freben** [comment]
Hm i see this seems to be falling between the chairs, let me see what I can do

**Comment by freben** [comment]
Initial thought: is it really in the interest of the adopter for this to silently just not happen? Don't they want the backend to throw an error and fail to start up instead? This seems like it'd just lead to some harder-to-diagnose side effect farther down the line, for what essentially could be seen as a fatal misconfiguration

**Comment by szubster** [comment]
It's a valid point.
So, how should one go when postgres is used on production, but sqlite during development (and in our case also in ephemeral per-PR deployments)?
I have not seen a way to conditionally add a module. I could steer it with env variables, but I cannot use config.
Maybe reading config in module init and adding a `search.indexer.postgres.disable` config property with default to `false`?

**Comment by freben** [comment]
Yeah first thing that comes to mind is to do

```ts
if (process.env.NODE_ENV === 'production') {
  backend.add(import(...))
```

And there's also a way to override a feature discovery service but that's getting a bit esoteric.

To be clear I'm not saying a hard no, ping @Rugvip too for feedback

**Comment by dasari008** [comment]
please re-open this PR. I'm trying to migrate to the new backend system and i'm encountering this issue while adding the `search-backend-pg-module`. 
@freben @Rugvip

**Comment by dasari008** [comment]
@freben Thanks for re-opening. The functionality of registering the `search-backend-module-pg` only when its supported seems fine. Most of the times sqlite is used in local development, however there are some scenarios when pg is also used in local development. To support this dynamic nature i think it is better to look at supported database in app-config and register that and throw some kind of warning. 

Just some thought, is it possible to expose an `extensionpoint` from this module and the user/developer can customize the functionality?

**Comment by awanlin** [comment]
Hi @szubster, any chance you can update the title of this PR to be more clear as well as putting a nice description in place? I suggested to someone on Discord to create a PR with the same changes as I missed this PR as the title is super unclear.

**Comment by freben** [comment]
All good!

**Pull request merged**
