### PR TITLE
Entra ID Rebrand

### PR DESCRIPTION
**Pull request by afscrome**
Microsoft have renamed Azure Active Directory to Entra ID.  https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/new-name .  This PR updates references to AAD to refer to Entra ID.

* On each documentation page, I include `formerly Azure Active Directory` in the first non heading reference to Entra ID.  This will help anyone unfamiliar with the  name change, and will also mean the page continues to show up in search results if people search for the old name.
* I didn't correct references in file names, as this would cause broken links.  If we have a way of redirecting those to new urls I can look at doing that, but if not, I think it's better to leave existing links working.
* There were a few references to AAD in release notes for older versions - I left these alone as the product naming was correct at the time of the release notes.
* LDAP provider still has references to "Active Directory" as these reference to the on premise Active Directory, not Azure Active Directory

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @afscrome, thanks for this! Just a couple quick items before I do a review:

- To make Vale happy you'll want to add some words - Entra, rebrand, etc. - to this file: https://github.com/backstage/backstage/blob/master/.github/vale/Vocab/Backstage/accept.txt
- You can do redirects, just add them here: https://github.com/backstage/backstage/blob/bae9015f2bdec15b586efd5275b38b2214ec4eed/microsite/docusaurus.config.js#L114

**Review by awanlin — CHANGES_REQUESTED** [review]
All the changes themselves look good to me, just need to make Vale happy

**Comment by afscrome** [comment]
Thanks @awanlin.  Vale should be happy now.

The one file we have that needs a redirect is https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/aws-alb-aad-oidc-auth.md, however that's under `contrib` rather than docs, so I don't think the redirects will work for that.

**Review by awanlin — APPROVED** [review]

**Comment by afscrome** [comment]
@awanlin Any ideas why the microsite job failed?  Do you mind triggering it for a rerun?

**Comment by awanlin** [comment]
> @awanlin Any ideas why the microsite job failed? Do you mind triggering it for a rerun?

Not really, it's been problematic lately, I'll kick it for you though 👍

**Review by benjdlambert — APPROVED** [review]
Thanks for this :tada:

**Pull request merged**
