### PR TITLE
FIX: Fixed the UI of the Community page

### PR DESCRIPTION
**Pull request by Rupsnigdha**
## Hey, I just made a Pull Request!

I fixed the Alignment Issues of the buttons in the community page.
BEFORE :
image
AFTER FIX:
image

I achieved this by seperating the content and the button by wrapping all the content inside a `<Block.Container column />` component. I then applied `align-self: "stretch"` to the parent `<Block.TextBox />` components. This approach also preserves the mobile view of the project.
image

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Awesome, thank you! 🎉

**Comment by Rupsnigdha** [comment]
Heyy, so I was hoping this would get the hacktober label so that I could get the holopin :D

**Comment by Rugvip** [comment]
Added ALL the labels, don't know if there's anything else? 😅

**Comment by Rupsnigdha** [comment]
THANK YOU SO MUCH!! ❤️

**Pull request merged**
