### PR TITLE
fix(TechDocsBuildLogs): properly render entire log

### PR DESCRIPTION
**Pull request by kuangp**
Signed-off-by: Phil Kuang <pkuang@factset.com>

| Before | After |
| - | - |
| Screen Shot 2022-11-30 at 7 46 37 PM | Screen Shot 2022-11-30 at 7 45 33 PM |

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by kuangp** [comment]
go away stalebot 😛

**Comment by kuangp** [comment]
@camilaibs mind getting some 👀 on this when you get a chance please?

**Review by agentbellnorm — APPROVED** [review]
Thanks, looks good to me!

**Comment by kuangp** [comment]
@Rugvip do you mind putting some 👀  on this and/or signing off here as a reviewer ? Looks like this may have gone overlooked due to a lack of an assignee?

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
