### PR TITLE
Support new Octokit types

### PR DESCRIPTION
**Pull request by iamrajiv**
## Hey, I just made a Pull Request!

Closes https://github.com/backstage/backstage/issues/6489
Fixes: #6374

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by OrkoHunter — COMMENTED** [review]
Hi @iamrajiv ! Thanks for working on this.

I think the issue is about bumping the version of `@octokit/rest` from 18.5.6 to 18.6.7

After you have done this and run `yarn install && yarn tsc:full`, you'll see some errors in few plugins. The error is basically that some types were previously of type `string`, but now they need to be converted to `string | undefined` because the new library has updated the type.

So, you don't need to add a `string` library anywhere. Revert this commit, bump the version of `@octokit/rest` in all the packages you find, and resolve all the TSC errors that pop up!

Happy to help further 🙂

**Comment by iamrajiv** [comment]
@OrkoHunter How I can bump the version like #6374 branch is deleted so I can pull the changes of Dependabot.

**Comment by OrkoHunter** [comment]
@iamrajiv you can update the version in package.json files manually and run the yarn commands I mentioned above.

**Comment by iamrajiv** [comment]
@OrkoHunter I tried to change `string` to `string | undefined` in files but locally also failing can you help?

**Comment by OrkoHunter** [comment]
@iamrajiv We need to update a few more places. :)

Looking at this error, we need to update the [api](https://github.com/backstage/backstage/blob/ea5631a40d41ddc1ddda96aa215c2bde29a366e6/plugins/github-actions/src/api/types.ts#L27) we have defined so that `html_url` can be `string | null` now.

Screenshot 2021-07-19 at 7 47 52 AM

**Comment by OrkoHunter** [comment]
@iamrajiv The second error

Screenshot 2021-07-19 at 7 54 50 AM

is coming due to type incompatibility for `workflowName` in a `WorkflowRun`.

> Type 'string | null | undefined' is not assignable to type 'string'.

https://github.com/backstage/backstage/blob/ea5631a40d41ddc1ddda96aa215c2bde29a366e6/plugins/github-actions/src/components/useWorkflowRuns.ts#L22

**Review by OrkoHunter — COMMENTED** [review]
There's still some errors @iamrajiv on the CI

**Comment by iamrajiv** [comment]
@OrkoHunter Yeah like locally I am trying to fix like I changed string to string | undefined still showing error when I do `yarn tsc:full` :/

**Pull request closed without merging**
