### PR TITLE
feat: scaffolder actions github:repo:create gitub:repo:push

### PR DESCRIPTION
**Pull request by crivetechie**
## Hey, I just made a Pull Request!

Added two new scaffolder actions: `github:repo:create` and `github:repo:push`

as discussed here https://discord.com/channels/687207715902193673/923143744176418836/986193717079728128

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — COMMENTED** [review]
Thanks for the PR @crivetechie!

Overall I think this makes a lot of sense! However there's currently duplications both in terms of the input schema and the actual implementation. It would be great we could share the same code for both `publish` and the new actions in order to make sure that future updates and fixes get applied to both actions as they are so alike. I'm thinking some kind of helper/library inside the github folder with the shared implementation. 

While doing this, I think it make sense to also rename/deprecate `github:webhook` in favour of `github:repo:webhook` to standardise a bit more on the naming.

What do you think? :)

**Comment by crivetechie** [comment]
> Thanks for the PR @crivetechie!
> 
> Overall I think this makes a lot of sense! However there's currently duplications both in terms of the input schema and the actual implementation. It would be great we could share the same code for both `publish` and the new actions in order to make sure that future updates and fixes get applied to both actions as they are so alike. I'm thinking some kind of helper/library inside the github folder with the shared implementation.

The suggestion from @Rugvip was to introduce these 2 new actions and deprecate `publish:github`, if we were to do so would you still recommend to remove duplication in such case?

> While doing this, I think it make sense to also rename/deprecate `github:webhook` in favour of `github:repo:webhook` to standardise a bit more on the naming.
> 
> What do you think? :)

I think it makes sense to rename it, do you have any guideline on how to deprecate an existing action?

**Comment by Rugvip** [comment]
> The suggestion from @Rugvip was to introduce these 2 new actions and deprecate `publish:github`, if we were to do so would you still recommend to remove duplication in such case?

Wait what, where? 😁

I think we want to keep `publish:github` around as the high-level option, so best figure out some nice ways to break things down for reuse.

> I think it makes sense to rename it, do you have any guideline on how to deprecate an existing action?

Think the deprecated action could be expressed in terms of the new one, but but with it logging a deprecation warning within the action handler before calling the original handler. That way end users will see the deprecation too.

**Comment by crivetechie** [comment]
> . That way end users will see the deprecation too.

I am sorry! I crossed wires! The suggestion was from blam in Discord https://discord.com/channels/687207715902193673/923143744176418836/986193717079728128

> , so I've been thinking about splitting out the publish:github action, and all of them, into seperate steps, like github:repo:create and then having git:init & git:push actions instead which I think would enable you to do what you want, but it's something I don't have time to do right now. Open for contributions though. Maybe we keep the legacy action around, also, but have the option to break down the steps.

**Review by benjdlambert — APPROVED** [review]
Thanks for this @crivetechie! Think this is looking pretty good now! :pray:

**Pull request merged**
