### PR TITLE
Add support for permission sub-policies in APIs and extension points

### PR DESCRIPTION
**Pull request by davidfestal**
## Hey, I just made a Pull Request!

- Add support for permission sub-policies in APIs and extension points
- Provide a default main policy that apply sub-policies contributed by plugins before, returning ALLOW_ALL as a fallback
- Apply that mechanism to the Playlist backend plugin whose Readme file already introduces the concept of sub-policy, but managed manually by the end-user.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation _(the Playlist backend plugin `README.md`)_
- [x] Tests for new functionality and regression tests for bug fixes _(through the change done to the Playlist plugin)_
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by davidfestal** [comment]
**Disclaimer:** Waiting for feedback about the PR before updating the docs in https://github.com/backstage/backstage/tree/master/docs/permissions

**Comment by davidfestal** [comment]
This change would enable adding support for the new `alpha` backend system in the `playlist-backend` plugin, since it would provide the required extension point mechanism to contribute the `DefaultPlaylistPermissionPolicy` as a sub-policy.

**Comment by davidfestal** [comment]
> This change would enable adding support for the new `alpha` backend system in the `playlist-backend` plugin, since it would provide the required extension point mechanism to contribute the `DefaultPlaylistPermissionPolicy` as a sub-policy.

Done in a next PR #18069 (which relies on this one)

**Review by mtlewis — COMMENTED** [review]
Thanks so much for the contribution! I think this (along with https://github.com/backstage/backstage/pull/18069) go along way towards hardening the solution for allowing plugins to contribute their own default permission policies. The key question for me is whether that's something we really want to push further towards in the permissions framework. The alternative is a separation between opinionated plugins that ship baked-in authorization rules that can't be changed, and unopinionated plugins that don't ship any baked in authorization rules but allow authorization to be performed via the permissions framework. It seems possible that the playlist plugin in particular could end up in that former bucket, where rather than using the permissions framework, authorization is baked in and not modifiable.

On that line of thinking, a couple questions come to mind:
- Are we aware of any users customizing the permissions used for the playlist plugin today, or is everyone we're aware of using the defaults? If everyone's using the defaults, perhaps it's worth considering removing this extensibility as an alternative to shipping this change.
- Are we aware of any other plugins that are in need of this capability?

**Pull request closed without merging**
