### PR TITLE
make the template cards conform to mui standard

### PR DESCRIPTION
**Pull request by freben**
Before:

Screenshot 2021-02-12 at 14 18 08

After:

Screenshot 2021-02-12 at 14 27 00

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4512-wkxr7sgjqyl7molv7kxbvbjz8w1dt4zj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60268244f285af42de8d0e23

**Comment by Fox32** [comment]
I wish scaffolder was using the `ItemCard` from `core` even though that card might look off 😆 But once we fixed that card all cards in backstage would look the same?

But I think that is something for a later refactor

**Comment by freben** [comment]
Ah yeah ... mm we are supposed to unify these sometime, while refactoring them a bit I guess.

Just doing this quickly while in a mob programming session because the button alignment was bothering me more than I care to admit ;)

**Review by benjdlambert — APPROVED** [review]

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4512-wkxr7sgjqyl7molv7kxbvbjz8w1dt4zj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60268244f285af42de8d0e23

**Pull request merged**
