### PR TITLE
Add Unity as adopter

### PR DESCRIPTION
**Pull request by OrkoHunter**
As per email conversation with Ted Cordery @TeddyBallGame

### CODE REVIEW

**Comment by teddyballgame** [comment]
LGTM, thanks for kicking this off.

**Review by benjdlambert — APPROVED** [review]

**Comment by teddyballgame** [comment]
Screen Shot 2021-11-16 at 6 47 43 AM

**Comment by teddyballgame** [comment]
Seems like there is a formatting issue

**Comment by OrkoHunter** [comment]
Thanks @teddyballgame ! I added an extra new line in between. Fixing it

**Pull request merged**
