### PR TITLE
Download tar.gz archives for Gitlab

### PR DESCRIPTION
**Pull request by Jerry4013**
Signed-off-by: Jingchao Zhang <jingchao.zhang@nuance.com>

## Hey, I just made a Pull Request!

This pull request changes the format for downloading archives for Gitlab from the zip to tar.gz to solve #5997

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jhaals** [comment]
Nice work @Jerry4013! Small typo in GitLab but looks good overall 👍

**Comment by freben** [comment]
yeah you want it to be "GitLab", and then you probably want to put ``` `readTree` ``` in backticks like that

**Comment by freben** [comment]
I made vale happy and pushed - let's just wait for green light then 🚢

**Comment by Jerry4013** [comment]
@freben Great! Thanks!

**Pull request merged**
