### PR TITLE
Tweak the identity request type

### PR DESCRIPTION
**Pull request by punkle**
## Hey, I just made a Pull Request!

I am doing this in the hope that it will fix some type validation issues when using various versions of express.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@punkle what's the error that we were getting here with different versions of express?

**Comment by punkle** [comment]
honestly I am not sure yet. I was noticing some issues, where the adr-backend was returning a different set of types from the createRouter than the backend plugin setup expected. The adr-backend seems to be the only plugin that requires a different set of express deps. I then tried to go about adding resolutions for the express deps, then I started to hit problems with this generic Request type.

Perhaps I am going about this the wrong way. Maybe I can try to resolve the differnces between the versions required by the adr-backend?

**Comment by benjdlambert** [comment]
Hmm yeah, I'd be a little cautious of merging this - even though it might be fine, would still be good to see what's causing this for reals so we can be on the lookout if this is something that's going to break something else.

**Comment by punkle** [comment]
Totally agree. Let me close this for the moment. In mean time we configured adr like this:

```
import { createRouter } from '@backstage/plugin-adr-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const router = await createRouter({
    reader: env.reader,
    cacheClient: env.cache.getClient(),
    logger: env.logger,
  });
  // TODO remove express.Router type casting
  //  We have added this type casting because adr-backend brings in a special version of
  //  the express types. We should remove this type casting when we have fixed the dependencies
  return router as unknown as Promise<Router>;
}
```

**Pull request closed without merging**
