### PR TITLE
Add Rootly plugin

### PR DESCRIPTION
**Pull request by kwent**
# Rootly plugin for Backstage

Cf. https://github.com/rootlyhq/backstage-plugin

The [Rootly](https://rootly.com) plugin is a frontend plugin that displays Rootly services, incidents in Backstage. The plugin includes three components that can be integrated into Backstage:

- The `RootlyPage` routable extension component which produces a standalone page with the following capabilities:
  - View and search a list of entities and import/link them to rootly services
  - View and search a list of services
  - View and search a list of incidents

- The `RootlyOverviewCard` component which produces a summary of your entity with incidents over last 30 days and ongoing incidents.

- The `RootlyIncidentsPage` component which produces a dedicated page within your entity with details about ongoing and past incidents.

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thank you! 👍 

To begin with I'm wondering, since this is already over at https://github.com/rootlyhq/backstage-plugin-rootly/, could you publish it from there and only add it to the [marketplace](https://backstage.io/plugins) instead? Happy to help out with directions on how to get tooling for that set up.

**Comment by kwent** [comment]
@Rugvip Done ! Also gave you write permissions in https://github.com/rootlyhq/backstage-plugin-rootly/

Few questions and help welcome:
- Should i change `@internal` reference to `@backstage` ? Will it still work for development ?
- How do i publish on `@backstage` npm ?

Regards

**Comment by Rugvip** [comment]
@kwent nice! You'll want to name the package something like `backstage-plugin-rootly`, same as the repo. Or if you have your own namespace you could also do something like `@rootly/backstage-plugin`

**Comment by kwent** [comment]
Oh packages aren't published under `@backstage` anymore ? I feel all plugins does ? `@backstage/plugin-lighthouse` etc etc.

**Comment by andrewthauer** [comment]
> Oh packages aren't published under `@backstage` anymore ? I feel all plugins does ? `@backstage/plugin-lighthouse` etc etc.

@kwent - I think what @Rugvip is referring to is the `package.json` name is currently `@internal/plugin-rootly` but should probably be something like `@rootly/backstage-plugin-rootly` (or just `@rootly/backstage-plugin`). That way when you publish to `npm` it's scoped to rootly and has a meaningful name. The `@backstage` npm scope is reserved for packages published from the `backstage` GitHub org.

**Comment by kwent** [comment]
@Rugvip I moved everything from @backstage to `@rootlyhq` (for GitHub) and `@rootly` namespace (for npm) and published `0.1.0` on npm: https://www.npmjs.com/package/@rootly/backstage-plugin. Let me know what else i should do.

**Review by jhaals — COMMENTED** [review]
That looks good!
Just one thing to fix which is that commits need to be DCO signed in order for us to merge them.
It's as simple as `git rebase HEAD~1 --signoff && git push -f` to update your existing commit.

**Comment by kwent** [comment]
@jhaals All signed ! :)

**Review by jhaals — APPROVED** [review]
Thank you 🙌

**Comment by suuus** [comment]
Thanks for your plugin contribution @kwent 🙌 Please let me know if you’d like some help to contribute further.

**Pull request merged**
