### PR TITLE
Standardize the tool cards in explore some more

### PR DESCRIPTION
**Pull request by freben**
Follow-up from #4803.

This also deprecates the `newsTag` field on tools, that wasn't even being rendered.

Screenshot 2021-03-05 at 19 34 15

### CODE REVIEW

**Comment by freben** [comment]
@Fox32 didn't need to use the ItemCardHeader since the CardMedia was perfectly capable of drawing the images as it were. but some general cleanup and using the new standard grid at least

**Review by adamdmharvey — APPROVED** [review]
🎉 🎉 🎉

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4839-smyv0q0ibabxfnfbwa2wx8gkim0pnca9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60424560f285af7938a149aa

**Comment by Fox32** [comment]
I wonder how it looks like, but beside that 👍

**Comment by freben** [comment]
Updated with a screenshot, sorry, forgot about that!

**Comment by Fox32** [comment]
Thanks 🙂 looks good

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
