### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by Fox32**
## Hey, I just made a Pull Request!

Small thing

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by stefanalund — APPROVED** [review]
Thanks 😆

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
Oh sorry, maybe you were still adding things here :octocat:

**Comment by Rugvip** [comment]
@stefanalund https://github.com/streetsidesoftware/vscode-spell-checker :grin:. I rely on that a lot :p

**Comment by Fox32** [comment]
> Oh sorry, maybe you were still adding things here :octocat:

I will just create a new one if I can improve more 😊

**Pull request merged**
