### PR TITLE
Issue #21528: Allow Setting a Callback for the onProxyReq Event

### PR DESCRIPTION
**Pull request by zeshanziya**
## Allow Setting a Callback for the onProxyReq Event

Added a privistion to set a callback for onProxyReq event. Please see Issue #21528. 

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @zeshanziya!

First off thanks for this PR!

After chatting with the other maintainers, we're kind of back tracking on some of these additions to the `proxy-backend` plugin. Ideally in a longer term solution we'd like to completely remove the `proxy-backend` plugin in favour of other `-backend` plugins or something like GraphQL, which are more specialized rather than using the `proxy-backend` as it's fundamentally insecure with allowing anyone to hit upstream services with a Token already preset in the request.

I think that unfortnately we're gonna push back on this making into the core of the plugin, and you can make the addition to a fork of the plugin locally if you wanted to get this to work, or perhaps if you're looking at solving this for `newrelic` specifically, i'd encourage you to look at implementing a `newrelic` backend that can do some of these resolutions for you.

I know there's already some prior art  for having non-sensitive tokens upstream attatched to the entity directly, and those are used for interaction with the upstream services, like the [`integration-key` in PagerDuty](https://github.com/PagerDuty/backstage-plugin/blob/9830bc5600a1c7af77cf1f816b40c6f5bc36af13/dev/mockEntity.ts#L27)

I know it's probably not the answer you're looking for right now, but we're not looking at making something that we ideally want to deprecate in the future any more capable of solving other issues or we're never gonna get to a point to move off 😅 

Does this make sense?

**Comment by zeshanziya** [comment]
Thank you, @benjdlambert, for the clarification. Does this imply that the proxy feature will be entirely removed in the near future?

**Comment by benjdlambert** [comment]
@zeshanziya yep that's the plan, but it's most probably not short term, as these backend plugins take some time to build of course, but it's the endgoal and the idea for sure.

**Comment by zeshanziya** [comment]
Thank you, @benjdlambert. Do you have any thoughts on how we can address the issue of handling multiple accounts? Even if we foresee that each frontend plugin will eventually align with a corresponding backend plugin, a fundamental challenge persists. Backend plugins may only support a single API Key/Auth Token, yet there's a requirement for managing multiple API Keys and selecting the appropriate one based on annotations at the entity level.

Are there any future plans in place to tackle this challenge? Your insights on this matter would be greatly appreciated.

**Comment by benjdlambert** [comment]
@zeshanziya sorry I totally missed this notification. 

So the backend plugins don't always only need to support 1 API key. For Github for instance we support reading from github with different authentication sources, it's just up to the backend plugin to be able to select which identification source to use and which API token is the correct one depending on the Org. 

Lets say you have a backend plugin for service B, and you add configuration for two API keys, you would just need an identifier to be able to select which API key to use for the request. This is normally done by using little bits of identifying data on entities called [annotations](https://backstage.io/docs/features/software-catalog/well-known-annotations/#annotations)

You could possibly create an annotation for your service on the entities which basically power the correct selection of the API token.

**Pull request closed without merging**
