### PR TITLE
[Draft] add ADR log to repository

### PR DESCRIPTION
**Pull request by eywoon**
## Hey, I just made a Pull Request!

Draft for adding ADR log to the app repository. 

The idea is to add a docs/ directory that could contain, amongst other documentation related to the app, an adr decision log. In this case it's named architecture/ and has one example adr.

What do you think of the placement of the log and the naming? 

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by Escalion — APPROVED** [review]
Lgtm - Although, is this in the most convenient location? How will devs find this?

**Review by stefanalund — CHANGES_REQUESTED** [review]
First off, thanks for the PR!

I agree with @Escalion that this is not the optimal location. Putting it inside the `/docs` folder makes much more sense in my view.

**Comment by freben** [comment]
Agreed here too. I don't think we are really looking to provide an internal ADR location for the people that adopt Backstage, but rather a public decision record for what applies to the open-source project right here.

**Comment by eywoon** [comment]
I updated the location to the docs/ directory 🙂

**Comment by freben** [comment]
Ok one final tweak - could you make that inside a `docs/adr` directory? There will hopefully be many to come, and they will clog up the docs dir. And secondly, remove it from the app template. Thanks!

**Comment by stefanalund** [comment]
Something went wrong in the merge I think :) Also, why nor `/docs/architecture-decisions` rather than `/docs/adr` which sort of assume that you know what an ADR is.

**Comment by eywoon** [comment]
Yes! The merge went wrong ;) 
I was a bit hasty before and didn't notice I hadn't placed the file in a directory called architecture/
Do you think the example adr (001) should stay there?

**Comment by nikek** [comment]
LGTM 👍

**Review by stefanalund — APPROVED** [review]

**Comment by stefanalund** [comment]
Happy first contribution @eywoon 🎉

**Comment by eywoon** [comment]
Woohoo 🎉Thanks @stefanalund 
Credit to @[Paul-Philip](https://github.com/Paul-Philip) as we worked on this together 👏

**Pull request merged**
