### PR TITLE
Added AWS documentation in Kubernetes Authentication Documentation

### PR DESCRIPTION
**Pull request by CarlosPet**
I included instructions on how to configure the AWS server side authentication while using the Kubernetes plug-in.

## Hey, I just made a Pull Request!

I Included a new AWS section in the documentation. It explains how to set up AWS authentication with both access keys and roles. It was missing from the examples provided as only Azure was present.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jamieklassen** [comment]
This seems like it picks up where #16753 left off and resolves #16677 -- curious about opinions from @Rugvip and @adamdmharvey who had opinions on this in the past?

**Comment by CarlosPet** [comment]
Any news on this? are any corrections needed? the bot marked it as stale already

**Review by Rugvip — APPROVED** [review]
Thank you, looks good to me! 👍 😁 

Don't know if the content is accurate though, @backstage/kubernetes-maintainers could you do final approval + merge?

**Comment by CarlosPet** [comment]
@Rugvip  I see one of the checks is marking the use of 'aws' as an error, i guess because it's not capitalized, I intended to use lowercase to use the exact spelling of field in the yaml file i was referring to, do I need to change it?

**Comment by Rugvip** [comment]
@CarlosPet use inline code blocks, `aws`, or `'aws'` for strings

**Comment by CarlosPet** [comment]
@Rugvip , understood, changed it to `aws`

**Review by mclarke47 — APPROVED** [review]

**Comment by mclarke47** [comment]
LGTM

**Pull request merged**
