### PR TITLE
add cronjobs to list of required permissions

### PR DESCRIPTION
**Pull request by punkle**
## Hey, I just made a Pull Request!
Adds reference to cronjobs access neccessary for recent backend change.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@mclarke47 for visibility.

**Review by benjdlambert — APPROVED** [review]

**Comment by punkle** [comment]
@benjdlambert Can you hold off merging this. I think I got it wrong. I am testing now, shouldnt be too long.

**Comment by benjdlambert** [comment]
Need a DCO sign off here too @punkle 👍

**Comment by benjdlambert** [comment]
@punkle is this ready to go after the DCO Signoff?

**Review by mclarke47 — APPROVED** [review]

**Comment by punkle** [comment]
@benjdlambert I think its correct, but I havent quite verified it yet. However I think this pull request will bring it closer. We can merge this and Ill follow up with a doc improvement if I am wrong.

**Comment by punkle** [comment]
Hey @benjdlambert and @mclarke47 I can confirm that adding the batch jobs and cronjobs as follows removes the following error from the kube plugin:

```
Errors:
Cluster: dev0
Error fetching Kubernetes resource: '/apis/batch/v1/jobs', error: UNKNOWN_ERROR, status code: 403
Error fetching Kubernetes resource: '/apis/batch/v1/cronjobs', error: UNKNOWN_ERROR, status code: 403
```

**Comment by punkle** [comment]
I do not have permission to merge this change.

**Pull request merged**
