### PR TITLE
Add missing res.end in scaffolder backend EventStream usage

### PR DESCRIPTION
**Pull request by devth**
## Hey, I just made a Pull Request!

This is related to [this Discord thread](https://discord.com/channels/687207715902193673/996771410359898196) with @benjdlambert on the scaffolder appearing to hang.

Observations:

1. I noticed the scaffolder backend `EventStream` logs were not showing up in my deployed (k8s with Kong ingress) environment.
2. They did however show up up in local dev
3. Our docs backend also uses `EventStream` to build/publish/serve docs on demand, and those *do* show up in the deployed environment, so I realized there must be some difference in the usage. Note: we use a custom docs backend that's essentially a fork of TechDocs.

This commit https://github.com/backstage/backstage/commit/f43192207 changeset explicitly says:

> remove usage of res.send() for use of res.json() and res.end()

yet no `res.end()` calls were actually introduced.

I tested this change which adds the missing `.end()` calls and verified that it works.

I suspect the ingress proxy does not send the response to the client until it is fully flushed, which is why it worked in local dev, where the browser client is hitting the dev server directly, and therefore streams the data even if the connection is never flushed and ended.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by benjdlambert — APPROVED** [review]
Thanks so much for looking into this and persisting! Does this work over long running tasks and getting each log line? Or does it wait until it's finished and then dump the entire log on the screen?

**Comment by devth** [comment]
My scaffolder actions are very fast so I'm not sure. Let me introduce some artificial delays with logs in-between to find out! I'm guessing it will wait until it's finished then dump the entire log, but I could be wrong.

**Comment by benjdlambert** [comment]
Hmm yeah that's disappointing as it really defeats the purpose of the EventStreams. They're supposed to stream data like websockets. There must still be an issue with the ingress' not supporting Server Sent Events, but not sure where to start i'm afraid.

**Comment by benjdlambert** [comment]
I guess this is still better than nothing though, still appreciate the PR to solve actually closing the connection once things are completed.

**Comment by devth** [comment]
I confirmed it's not streaming. It just dumps all the events at the very end, all at once:

image

I think this fix is valid regardless, but I'm going to look into ingress settings to see if I can prevent buffering the EventStream and get it to send chunks immediately.

**Comment by freben** [comment]
Does this help? https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx

**Comment by benjdlambert** [comment]
@freben - yeah I think that was the first link I send for ingress' but I think they've changed ingress' twice from Ambassador to Kong IIRC from Discord, but it's still happening. Is there something else we're missing here? Should we be sending another header or something to the `ingress` saying this is SSE or something? I don't know :shrug: But I've seen a lot of these reports that in production behind ingress it doesn't work 😢

**Comment by benjdlambert** [comment]
@devth thinking that we merge this, and if you find some more things around the ingress we can address those seperately in documentation or whatnot.

**Comment by devth** [comment]
Thanks @benjdlambert.

We tried many nginx directives (Kong is built on nginx) this morning without any luck 😔

**Comment by devth** [comment]
Update: we figured out it was the https://www.banyansecurity.io/ proxy preventing the SSE from streaming. Not sure we have a resolution yet, but at least we were able to rule out Kong/Nginx.

**Comment by benjdlambert** [comment]
Nice! Ok that's good to know then. Thanks for doing to digging! :pray:

**Pull request merged**
