### PR TITLE
Techdocs code snippets custom colors

### PR DESCRIPTION
**Pull request by luis-k0**
## Hey, I just made a Pull Request!

Custom colors for markdown/techdocs code snippets in the theme palettes.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by johnphilip283 — APPROVED** [review]

**Comment by tudi2d** [comment]
Hej Luis - thanks for raising this! My suggestion here is to close the PR to avoid the breaking change to the theme. There are other approaches to customise the the theme:

As you know we are building on MkDocs and you can checkout this section to understand how theming is enforced: https://github.com/backstage/mkdocs-techdocs-core#theme.

A different approach to modify the theme of the documentation without having to change the global the is by creating a small `customThemeAddon` for the content (https://backstage.io/docs/features/techdocs/addons#addons-in-the-content-location). This way you could access the shadow DOM, add a stylesheet, override styles of specific elements or override classes. An example for this could be the TextSize Add-on: https://github.com/backstage/backstage/blob/master/plugins/techdocs-module-addons-contrib/src/TextSize/TextSize.tsx

I hope this helps! Please feel free to raise a separate **issue** if this is not what you expected. An issue allows us to proper discuss a big change (like this one) before jumping into solution mode. Theme customisation is also not documented at the moment - we are always happy to receive contributions on documentation.

**Comment by luis-k0** [comment]
hi @tudi2d, actually we started to talk about this issue in [Discord](https://discord.com/channels/687207715902193673/714754240933003266/threads/1144610457144008764) and we opened an [issue](https://github.com/backstage/backstage/issues/21999) too.

but I get your point and I appreciate your suggestions and we will try them.

thanks.

**Comment by awanlin** [comment]
My apologies @luis-k0, some of this does fall to me as I was not aware of some of these other options and the preference for them. Sorry about that :(

**Comment by luis-k0** [comment]
No worries @awanlin, it is hard to know everything happening in a large project such as Backstage. 

Your help showed us the way to the other adjustments made in this [PR](https://github.com/backstage/backstage/pull/22155).

I appreciate your help. Thanks 😃

**Pull request closed without merging**
