### PR TITLE
scaffolder: update docs with v1beta3 syntax

### PR DESCRIPTION
**Pull request by OrkoHunter**
Used the migration guide: https://backstage.io/docs/features/software-templates/migrating-from-v1beta2-to-v1beta3

### CODE REVIEW

**Comment by jhaals** [comment]
Nice work @OrkoHunter!

**Comment by jhaals** [comment]
@benjdlambert are we ready to make beta3 the default?

**Comment by OrkoHunter** [comment]
@jhaals We do have the [migration guide](https://backstage.io/docs/features/software-templates/migrating-from-v1beta2-to-v1beta3) which can help folks see what changed and how their template is different from the current. As long as we think we're ready with beta3, IMHO we should just update the adding and writing templates pages with the recommended syntax. I feel having two syntaxes (even on pages marked as legacy) might be confusing for newcomers and bit of a pain for us to maintain. But definitely I'll leave this to your discretion. 💯

**Review by OrkoHunter — COMMENTED** [review]
Oops, just noticed that the `apiVersion` is `scaffolder.backstage.io/v1beta3` and not `backstage.io/v1beta3`.

Great move, given catalog and scaffolder are moving separately on this 💯

**Review by jhaals — APPROVED** [review]
I reached out to the lead scaffoddler and we are good @OrkoHunter! 👍 

Btw are you looking into updating the example templates? Might be good to have some migrated as the docs mention v1beta3 now

**Comment by OrkoHunter** [comment]
> lead scaffoddler

Great to hear the wizard is pleased. 😄 

Migrated the sample templates too https://github.com/backstage/software-templates/pull/9 @jhaals @benjdlambert

**Pull request merged**
