### PR TITLE
Customizable task step viewer

### PR DESCRIPTION
**Pull request by acierto**
## Hey, I just made a Pull Request!

As a developer of scaffolder templates, I would like to have a possibility to customise the step execution panel.
Like as an example we would like to achieve to have that notification message block highlighted in a red border

Screenshot 2023-01-27 at 14 55 05

Initially i tried to use `TaskPageComponent` to achieve it, but ended up with a few copy pasted folders from `scaffolder` and it was still not enough.

Having less invasive customisation is great for adding small things. 
`TaskPageComponent` is great for complete redesign.

The way to use it:
```

<Route
      path="/create"
      element={
        <ScaffolderPage
          components={{
            TaskStepViewerComponent: BolTaskStepViewer,
          }}
```

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @acierto! :wave:

First of all, thanks for this - wanna put this on pause for a little bit however, as we're currently re-implementing this page part of the scaffolder next work, and there's some other customization points that I want to round off first and then look at this. 

Basically this page is going to be completely reworked, and wondering if a component that can render a `CompletedOutputs` or something might be sufficient. 

What I'm thinking is that the scaffolder plugin will show you a simple timeline of the steps as they're executing and if they fail we will show you the logs, but once there are results for successful tasks you can provide your own component to render the outputs from the job in a particular way with some hooks to get the current template etc to make sure that you only show it on certain templates or whatever? Does this seem like it fits what you want to do and are we on the same page? 😅

**Comment by acierto** [comment]
Hey @benjdlambert!

The whole idea makes sense.
The only question is, what's the reason to wait till the end of the task, but not the end of the step? 

For example if we would like to show to the user some notification in the middle of task execution (like step 2 where task has 5 steps). At this case it won't be possible.

Even though if you refactor it completely it still will take some time, so if that's possible would be nice to have it meanwhile, but up to you to decide :)

**Comment by benjdlambert** [comment]
PR incoming that will replace this PR, will close this once the other one is made, but want to keep this around in the meantime.

**Comment by benjdlambert** [comment]
So as of the release that goes out today, you'll be able to provide a `TemplateOutputsComponent` to the `scaffolder/next` router which will allow you to totally replace the links that are already rendered with whatever you want. We've got some followup work to add some hooks to allow you to get the current template in an easier way etc, but the building blocks are in place. Hopefully from 1.11 we will have the `scaffolder/next` for public preview and some instructions that will be shipped next week to get people to try this out, with the hope that 1.12 will be `@backstage/plugin-scaffolder@2.x`.

I think that this pretty much solves this issue and we can close this PR. I'm not feeling that with the current timeline that we have proposed that it's worth us backporting this to the current implementation as it's up for deprecation pretty soon.

**Pull request closed without merging**
