### PR TITLE
Mention error handling on GitHub discovery docs

### PR DESCRIPTION
**Pull request by dtuite**
I did some testing with error handling of the GitHub discovery and it may be useful to explain the results for others who are curious.

One other question that has come up is whether or not `Location` entities are imported by the discovery importer. I'll try to test that later and may add more notes to this page.

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5527-vr9er6hvfvr6q03ql4vjc7jhicxoxywr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608a7e7f8e7af671b9cbd535

**Review by Rugvip — COMMENTED** [review]
👍, but thinking we can put this in the catalog docs instead, since this isn't really GitHub specific

**Comment by dtuite** [comment]
You mean in the core features section somewhere? Like in [Static Location Configuration](https://backstage.io/docs/features/software-catalog/configuration#static-location-configuration) for example?

I was thinking about this error handling as being GitHub Discovery specific but I guess it also applies if you add a location which points to a bunch of other `catalog-info.yaml` files which have syntax errors in them. Is that true?

**Comment by freben** [comment]
I think that sounds like the best place for it now, go ahead.

Yeah the error behavior should be same overall. We'll work on surfacing those errors better in the interface as well.

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr5527-vr9er6hvfvr6q03ql4vjc7jhicxoxywr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/608a7e7f8e7af671b9cbd535

**Review by freben — APPROVED** [review]

**Pull request merged**
