### PR TITLE
feat(catalog-backend-module-gitlab): create url location only if file exists

### PR DESCRIPTION
**Pull request by artemiyokulov**
## Hey, I just made a Pull Request!

gitlab-discovery create many url location objects, even for projects, that do not contains file with component definitions

in this PR added additional checks for file existing, and after that url location if emited

it's decrease number of 404 requests to gitlab server

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
You seem to have some odd unrelated changes in this pull request, double check what was committed.

Also note the DCO check failing - there's more details in the check itself below on how to do the signing.

**Comment by artemiyokulov** [comment]
> You seem to have some odd unrelated changes in this pull request, double check what was committed.
> 
> Also note the DCO check failing - there's more details in the check itself below on how to do the signing.

DCO fixed.

I'm not understand about "some odd unrelated changes", what do you meen?

**Comment by freben** [comment]
Check your own pull request's [changed files](https://github.com/backstage/backstage/pull/10607/files). You have stuff from the microsite and ADOPTERS.md in there, which are not related to what you wanted to do.

**Comment by artemiyokulov** [comment]
> Check your own pull request's [changed files](https://github.com/backstage/backstage/pull/10607/files). You have stuff from the microsite and ADOPTERS.md in there, which are not related to what you wanted to do.

sorry, fixed it

**Pull request closed without merging**
