### PR TITLE
Updated the accessibility document

### PR DESCRIPTION
**Pull request by AdityaK60**
Current:
image

Updated:
image

### CODE REVIEW

**Comment by AdityaK60** [comment]
@benjdlambert , @vinzscam  Please review the changes. Thank you

**Review by vinzscam — CHANGES_REQUESTED** [review]
hey, is it possible to bulk all these PRs together in a single PR? It will make it easier to review

**Comment by AdityaK60** [comment]
Can you please approve this. I will raise future PRs with bulk changes. Thank you.

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Please ensure that any changes like this are done in bulk. There's an influx of these simple PR's coming in, and whilst they are somewhat nice to have, it takes a considerable amount of review effort to do these one by one.

**Pull request merged**
