### PR TITLE
feat(tech-radar): ring descriptions

### PR DESCRIPTION
**Pull request by dbrugger**
## Hey, I just made a Pull Request!

We'd like to have a legend for the Rings in the Tech Radar plugin.
This change adds an optional `description` property, and if set, gets rendered in the footer.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

image

### CODE REVIEW

**Comment by dbrugger** [comment]
No unit tests yet - I wanted to get feedback on the interface and the UX first. I am not 100% happy with the solution myself as the legend does not work well with longer descriptions and on mobile, and the text is not selectable. Personally I feel this should be an own component, and maybe not part of the SVG, but I wanted to try add to the existing footer first before making a bigger change.

**Review by Rugvip — APPROVED** [review]
Makes sense, thank you! 👍 🎉

**Comment by Rugvip** [comment]
Good to merge if you want to since it's optional, but if you want to tweak it that's fine too, let me know.

**Comment by dbrugger** [comment]
Ok cool then let's merge @Rugvip . I can come back to it later if needed.

**Pull request merged**
