### PR TITLE
Add google analytics scripts in template for standalone app

### LINKED ISSUE #4576: GA script missing in index.html template for standalone app
## Expected Behavior

In the [observability doc about google analytics](https://backstage.io/docs/plugins/observability#google-analytics), it says I can add a tracking id enable Google Analytics integration.

## Current Behavior

When creating a new app, the configuration `app.googleAnalyticsTrackingId` has not effect.

## Possible Solution

The script is only present in the app [index.html](https://github.com/backstage/backstage/blob/release-2021-02-16/packages/app/public/index.html#L52), not in the template for new app [index.html](https://github.com/backstage/backstage/blob/release-2021-02-16/packages/create-app/templates/default-app/packages/app/public/index.html#L51).

Additionally, content security policy for script-src must be overriden to allow `www.googletagmanager.com` and `'unsafe-inline'`, this could be said in the doc.
There have been discussions about the csp issue on discord [here](https://discord.com/channels/687207715902193673/687207715902193679/808359593847160852)

## Steps to Reproduce

1. Create a new standalone app: `npx @backstage/create-app`
2. Set `app.googleAnalyticsTrackingId` in app-config.yaml
3. Start the app

## Your Environment

- NodeJS Version (v12): v14.15.1
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Firefox Developer 86.0b8
- Backstage version: [release-2021-02-16](https://github.com/backstage/backstage/releases/tag/release-2021-02-16)

### PR DESCRIPTION
**Pull request by rbideau**
Signed-off-by: r.bideau <7304827+rbideau@users.noreply.github.com>

## Hey, I just made a Pull Request!

Add the google analytics snippet in the index.html template for new app, this was present in the index.html in the app but missing in the template.

Fix #4576 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4579-wacidwutwjcijsjlcobdhnxbmtjldguh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602e9359fcb22d4bfd59742d

**Review by Rugvip — APPROVED** [review]
Looks good, thanks! 👍

**Comment by freben** [comment]
ready to leave draft state?

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4579-wacidwutwjcijsjlcobdhnxbmtjldguh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602e9359fcb22d4bfd59742d

**Comment by rbideau** [comment]
@freben,  I wanted to move some docs around, as discussed in the issue.

I'm done now, this is ready but Vale doesn't like _pageview_ in one word. This is the spelling in Google Analytics docs though, should I add it to the vocab file ?

**Comment by freben** [comment]
Cool! Looking good. Two little things - the new page needs to be added to 

https://github.com/backstage/backstage/blob/master/microsite/sidebars.json

and

https://github.com/backstage/backstage/blob/master/mkdocs.yml

**Comment by freben** [comment]
Oh and regarding pageview - sure, add it to vocab!

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4579-wacidwutwjcijsjlcobdhnxbmtjldguh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602e9359fcb22d4bfd59742d

**Comment by rbideau** [comment]
@freben, I've added pageview to the vocab and updated sideabrs.json/mkdocs.yml 👍

**Review by freben — APPROVED** [review]

**Pull request merged**
