### PR TITLE
feat: allow webpack configuration override

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

This change allows application developers to override the default webpack configuration. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by tudi2d** [comment]
@drodil this was a change on our site fixing the release - notification comming soon. not an issue on your site.

**Comment by drodil** [comment]
@tudi2d ok, I thought I really messed this stuff up :D

**Comment by tudi2d** [comment]
context: https://discord.com/channels/687207715902193673/687207715902193679/1153990360612225065

**Comment by drodil** [comment]
Had to create new PR since my fork got really messed up. #20036

**Pull request closed without merging**
