### PR TITLE
Download tar.gz archives for Bitbucket

### PR DESCRIPTION
**Pull request by goober**
Signed-off-by: Mathias Åhsberg <mathias.ahsberg@resurs.se>

## Hey, I just made a Pull Request!

This pull request changes the format for downloading archives for Bitbucket from the default `zip` to `tgz` to solve #5918

This pull request only solves the underlying issue for Bitbucket, but it should be reproducible  for both Azure and Gitlab integrations since they are also using the zip format for downloading archives.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jhaals** [comment]
Thanks for sorting this out! This looks good me me 👍  It would be fantastic to give the same treatment to the other two providers as well so that we can properly close the issue.

**Comment by goober** [comment]
What I could see it should be possible for GitLab, but I couldn't find a way through the Azure DevOps API to download a repository as a tar archive.

**Comment by jhaals** [comment]
Thanks for checking, makes sense to do it for GitLab and leave Azure for the future when/if it's supported.

**Comment by goober** [comment]
I can see if I can open a second pull request for gitlab later, so we keep the providers separate.

**Review by jhaals — APPROVED** [review]
Looks good to me.

let's keep #5918 open so we don't forget to fix address this for GitLab.

**Review by freben — APPROVED** [review]

**Pull request merged**
