### PR TITLE
Deprecate the PagerDuty plugin

### PR DESCRIPTION
**Pull request by t1agob**
## Hey, I just made a Pull Request!

According to the discussion in https://github.com/backstage/backstage/issues/19347 we're deprecating the PagerDuty plugin created by Backstage. We are redirecting users instead to https://www.npmjs.com/package/@pagerduty/backstage-plugin.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by t1agob** [comment]
Looks like all checks have passed. Can you double-check if I'm doing everything properly @Rugvip @camilaibs? Thanks!

**Review by camilaibs — COMMENTED** [review]
Hi @t1agob 👋🏻, one thing that came to mind was adding a `@deprecated` annotation to everything exported by the plugin. Is there any recommendation on doing this @Rugvip?

**Comment by t1agob** [comment]
@camilaibs I have added the deprecated annotation in the PagerDuty Entity and the cards being exported. I don't know if you want this to be placed in other locations but I believe these are the components used by developers.

**Review by freben — APPROVED** [review]
Excellent!

**Pull request merged**
