### PR TITLE
uprade yarn to latest 3.x

### PR DESCRIPTION
**Pull request by freben**
Because why not ... we haven't done any upgrade in ages, and I thought it'd be cool to have whatever the latest improvements are, possibly security related, and getting closer to what a new adopter experience might look like after migrating. And maybe it is very slightly closer in shape/behavior to 4.x!

It's a bit interesting that the patch hashes changed.

### CODE REVIEW

**Comment by kuangp** [comment]
Hm, is there any update on guidance for adopters ? The [docs](https://backstage.io/docs/tutorials/yarn-migration) still prefer we use Yarn 1:

> NOTE: We do not yet recommend all projects to migrate to Yarn 3. Only do so if you have specific reasons for it.

**Comment by freben** [comment]
No, not yet. As a matter of fact, we discussed the topic a bit internally just today. Yarn 4 got released the other day too, and there's work ongoing in #20658 to widen support for more managers such as pnpm. So while all that settles, we probably won't change the default intentionally unless some maintainer or contributor gets inspired while taking a break from other priorities :)

**Comment by Rugvip** [comment]
We should actually remove that note at this point though. Haven't had any issues with Yarn 3 for quite a while and it's quite a lot nicer than Yarn classic at this point imo.

**Comment by freben** [comment]
Right, yeah the note as such is fine to remove. I guess that's what you meant by guidance @kuangp, sorry. https://github.com/backstage/backstage/pull/20798

**Comment by freben** [comment]
Let's try 4 in a couple weeks instead!

**Pull request closed without merging**
