### PR TITLE
chore: Add Snyk to ADOPTERS.md

### PR DESCRIPTION
**Pull request by robcresswell**
o/ This patch adds Snyk as an adopter; we're using Backstage via Roadie's SaaS platform

### CODE REVIEW

**Comment by robcresswell** [comment]
I've not included the whitespace the previous adopters had; please let me know if this is required. I couldn't understand why it was needed (markdown doesn't care) and the wrapping was annoying

**Comment by freben** [comment]
Hey! So nice to have you here - you'll unfortunately have to DCO sign the commit though! See the check [details](https://github.com/backstage/backstage/pull/9951/checks?check_run_id=5408640819)

**Comment by robcresswell** [comment]
@freben Sorry about that! I signed my PR body, not the commit message, ha. My bad

**Comment by freben** [comment]
That sorted it. We'll merge in a bit, waiting for a release flow to finish first.

**Pull request merged**
