### PR TITLE
Add Harbor Plugin to Marketplace

### PR DESCRIPTION
**Pull request by wrighbr**
## Hey, I just made a Pull Request!

I created a plugin for backstage an adding it to the plugin page

image

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ x ] Screenshots attached (for UI changes)
- [ x ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by OrkoHunter — APPROVED** [review]
looks good!

**Comment by awanlin** [comment]
@wrighbr this is great, just noticed that the documentation page linked here has the wrong title, it says "Backstage GKE usage plugin" that should probably be "Backstage Harbor plugin"?

image

**Comment by awanlin** [comment]
Sorry, the URL I'm referring to is here: https://github.com/BESTSELLER/backstage-plugin-harbor/blob/master/README.md

**Comment by wrighbr** [comment]
@awanlin thanks. I've updated readme

**Comment by awanlin** [comment]
@wrighbr awesome, thanks again for the plugin, working on getting it in our Backstage instance now :)

**Comment by wrighbr** [comment]
@awanlin sweet let me know how you go.

**Pull request merged**
