### PR TITLE
docs: mention that the configuration is shared between the backend and the frontend

### LINKED ISSUE #5836: v2 template RepoUrlPicker dropdown not populated with options when frontend is built for production
We're using a built and dockerized version of the Backstage frontend and noticed that one thing wasn't working with the prod version of the frontend. There is a `RepoUrlPicker` dropdown as part of a v2 template that isn't showing any options. We can see the option under the `GET` `/api/scaffolder/v2/templates/default/template/template-name/parameter-schema` request but the dropdown isn't populated with it. It shows up and works as expected when running in dev mode (via `yarn start`).

## Expected Behavior

We'd expect the dropdown to behave the same way as it does in dev mode and be populated with the options from the template configuration.

## Current Behavior

The dropdown doesn't show the options from the template configuration.

## Possible Solution

No idea.

## Steps to Reproduce

1. Dockerize your frontend and backend separately following the instructions from here:
https://backstage.io/docs/deployment/docker
2. Create a v2 template with something like:
```yaml
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: backstage-java-api
  title: Backstage Java API
  description: Cookiecutter template for a sample Java API scaffold.
  tags:
    - java
    - cookiecutter
  spec:
    type: service
    parameters:
      - title: Choose a location
        required:
          - repoUrl
        properties:
          repoUrl:
            title: Repository Location
            type: string
            ui:field: RepoUrlPicker
            ui:options:
              allowedHosts:
                - github.com
```
3. Try to use the template from dockerized/prod Backstage instance and notice that the dropdown isn't populated with `github.com`

## Context

- Separate frontend and backend using Docker
  - Frontend setup very similar to this: [Frontend with Nginx](https://github.com/backstage/backstage/tree/master/contrib/docker/frontend-with-nginx)
  - Backend setup very similar to this: [Multi-stage Build](https://backstage.io/docs/deployment/docker#multi-stage-build)

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

NodeJS Version: v14
Operating System (backend): `node:14-buster-slim` Docker image
Operating System (frontend): MacOS Catalina 10.15.7
Browser Information: Chrome (90.0.4430.212)

### PR DESCRIPTION
**Pull request by benjdlambert**
Fixes #5836

Signed-off-by: blam <ben@blam.sh>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by ConnorDY** [comment]
I was hoping for an explanation of what keys are needed for the frontend and which are backend only.

**Review by Rugvip — APPROVED** [review]
:shipit:

**Review by freben — APPROVED** [review]
extra approved with the new addition :)

**Comment by Rugvip** [comment]
@ConnorDY I added in a paragraph explaining that bit and pointing to the CLI command for showing the config docs, which used to only be documented in the CLI docs.

**Pull request merged**
