### PR TITLE
Show a variety of Trendline components in the storybook

### LINKED ISSUE #573: Create better Storybook example for TrendLine
Our Storybook should show a more typical Story example of a TrendLine. A good example is how it is used in the [Lighthouse plugin](https://github.com/spotify/backstage/tree/master/plugins/lighthouse):

lead

## Feature Suggestion

Add additional story in `TrendLine.stories.tsx` that wraps it in a `SortableTable`.

### PR DESCRIPTION
**Pull request by OrkoHunter**
## Hey, I just made a Pull Request!

Closes #573.

Add better examples of Trendline. (Check deploy preview too.)
Screen Shot 2020-04-22 at 3 49 05

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by freben — APPROVED** [review]
Looks great!

**Review by Rugvip — APPROVED** [review]

**Comment by stefanalund** [comment]
Thanks! Would you mind wrapping the SortableTable in an InfoCard? Doesn't look right with the content on the grey background.

**Comment by OrkoHunter** [comment]
Done @stefanalund ! Looks much better now.
Screen Shot 2020-04-22 at 12 35 57
Screen Shot 2020-04-22 at 12 35 45

**Comment by freben** [comment]
At some point - maybe not this PR - we should have a global wrapper for every storybook component, that adds some padding. Now things are pressed against the edges of the view, making for example the rounded corners of the card here look odd.

**Comment by freben** [comment]
:shipit:

**Comment by stefanalund** [comment]
@OrkoHunter thanks a lot!

@freben yes I fully agree. Maybe wrap in `<Content>`?

**Pull request merged**
