### PR TITLE
Change 'Running' status to static

### LINKED ISSUE #827: Change 'Running' status to static (not animated)
Hi! If we could change the running status to a static blue dot (rather than a blinking one), that would be amazing. Thank you!

http://storybook.backstage.io/?path=/story/status--default

### PR DESCRIPTION
**Pull request by Nishikoh**
## Hey, I just made a Pull Request!
Fixes #827 
http://storybook.backstage.io/?path=/story/status--default

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

Screen-Recording-2020-05-13-at-3 28 07

### CODE REVIEW

**Review by nikek — APPROVED** [review]
Looks good, thanks for the contribution!

**Comment by Nishikoh** [comment]
@nikek 
Thank you for the review. This PR isn't passing CLI Test. Should I fix to pass?

**Comment by nikek** [comment]
If you want to look into it, that'd be great. I wonder if it really is connected to your PR though 🤔. I will have a look tomorrow unless you solve it by then 😄

**Comment by Nishikoh** [comment]
I'll try as much as possible 👍

**Comment by cheepo2109** [comment]
Looks like there's new version of react router that's breaking the CLI test.
I tried removing caret(^) from all react-router dependencies in package.json, ran cli-e2e-test locally and the problem regarding using `<Link>` outside `<Router>` disappeared. I guess that's not the best solution, trying to find the piece of code that breaks the stuff 😄

**Comment by Nishikoh** [comment]
Passed CLI Test.
The problem was fixed by #845 and #839 maybe.

**Pull request merged**
