### PR TITLE
microsite: Replacing core feature icons with PNGs

### PR DESCRIPTION
**Pull request by fengypants**
Updating the icons for the core features on the /plugins page (Catalog, Software Template, TechDocs, K8s): Replacing the SVG versions with PNG versions, since the outlines on the SVGs look too thin when scaled down. Otherwise, illustrations are exactly the same, just a different file format.

Signed-off-by: Jeff Feng <fengypants@gmail.com>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hmmmm.

If you look at the svgs in just a text editor, you'll see that their styles are very basic, and near the start of the file. Could you try to tweak the styles inside them instead, from `stroke-width:1.25px` to something like `stroke-width:1.75px;shape-rendering:crispedges` or so, and see how you like the results?

**Comment by timbonicus** [comment]
We definitely want SVGs where possible. These are images rendered with math rather than pixels, can scale to any size and look crisp on any display - yet keep a very small file size. Let me know if you'd like some help getting the SVGs fixed up!

**Comment by fengypants** [comment]
Oh, I'm totally down with the approach — I get the philosophy and very much appreciate the nudge/pointers, @freben! And I also like the idea of changing just a couple of characters to get the result I want instead of replacing/updating 12 different files. 

The delay in my response has partly been because I've been down a rabbit hole learning about and experimenting with different SVG stuff (including fiddling with the stroke width in quarter-pixel increments, comparing non-responsive vs responsive exports, trying out something called a non-scaling-stroke vector-effect, etc., etc.).

I think I have the fix — which is replacing these SVGs with non-responsive versions (because changing the stroke width of the current software catalog icon to the desired 2.5px is only fixing part of the image, for whatever reason. And also the K8s illustration is messed up, anyway).

But my real blocker is getting my local repo back into sync with my remote repo and the master, because I still get easily tripped up by GH Desktop, etc. I'm getting help with that tomorrow morning from @OrkoHunter. It was a tossup between enlisting him or you, @timbonicus!  Thanks a lot for offering to help — I still may take you up on it depending on whatever else I encounter…

**Comment by freben** [comment]
Oh interesting, I wonder if it's possible to give the stroke width then in device-independent physical units, such as a fraction of millimeters. 🤔

**Comment by fengypants** [comment]
Got my repo in order — by deleting it. So created a new PR #6404.

**Pull request closed without merging**
