### PR TITLE
[TechDocs] Bug fixes and cleanups

### LINKED ISSUE #3550: TechDocs: Nav arrows in bottom of a page trigger full page reload
The Nav arrows at the bottom of a component documentation trigger a full page reload when clicked.

## Expected Behavior
The behavior should be the same as the nav bar on the left of the docs. Trigger a reload of only the internal component and not the entire page.

## Current Behavior
Each click triggers an full reload of the page.

## Steps to Reproduce

1. Create a component (with documentation)
2. Go into the doc tab of this component
3. click on the bottom of the page on the right arrow.

## Your Environment

- NodeJS Version (v12): v12.18.3
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04
- Browser Information: Chrome Version 87.0.4280.66 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by hooloovooo**
This fixes a bug where some internal doc links would reload the page instead of just fetching the new docs content. Also removes the modifyCss transformer and moved the css done there to the injectCss transformer.

Closes #3550

### CODE REVIEW

**Review by OrkoHunter — APPROVED** [review]
🎉 Awesome!
Does this close https://github.com/backstage/backstage/issues/3550 by any chance?

**Comment by hooloovooo** [comment]
> tada Awesome!
> Does this close #3550 by any chance?

Yup! Should do. :)

**Comment by OrkoHunter** [comment]
Sweet! :shipit:

**Comment by hooloovooo** [comment]
Can we get a thumbs up from @backstage/maintainers ?

**Review by stefanalund — APPROVED** [review]

**Pull request merged**
