### PR TITLE
Techdocs: Include cookies when requesting SVGs

### PR DESCRIPTION
**Pull request by GoWind**
## Hey, I just made a Pull Request!
Refs https://github.com/backstage/backstage/issues/6222

Include credentials in fetch request for SVG from Techdocs plugin.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by iamEAP — COMMENTED** [review]
Thanks for your contribution @GoWind!

Would you mind also adding a test (or perhaps just an assertion/expectation) that ensures the `credentials: 'include'` option is passed to `fetch`?

**Comment by GoWind** [comment]
Hi @iamEAP : Added a test case for this. Let me know insufficient or if you think it can be improved !

**Review by iamEAP — APPROVED** [review]
Perfect!  Thanks again, @GoWind.

**Review by freben — APPROVED** [review]

**Comment by OrkoHunter** [comment]
@GoWind appreciate all your efforts so far of making sure Backstage works well in a secured environment. 👏

**Pull request merged**
