### PR TITLE
feat: add reviewers input for bitbucket server pr

### PR DESCRIPTION
**Pull request by RedlineTriad**
## Hey, I just made a Pull Request!

This allows for a reviewers for a PR to be added automatically from backstage.

This doesn't include default-reviewers because those require a separate semi-official API call to get, which I didn't want to implement for now.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by RedlineTriad** [comment]
I also tested it on a real bitbucket server instance and setting `reviewers` to null is valid and doesn't cause any issues.

**Review by camilaibs — APPROVED** [review]
Looks great to me 🙂

**Comment by RedlineTriad** [comment]
Can this get merged or is something still necessary?

**Review by benjdlambert — APPROVED** [review]
Nice thanks! :tada:

**Pull request merged**
