### PR TITLE
fix(scaffolder): Split single form in steps to prevent steps overwriting formState

### PR DESCRIPTION
**Pull request by jboeijenga**
## Hey, I just made a Pull Request!

This MR will close https://github.com/backstage/backstage/issues/26826

The changes in this PR split the single form that is used to cover all steps in the scaffolder template into forms specific for each step. This is needed because the onChange handler can overwrite data from other steps. F.e. While navigating back the activeStep is changed, the form triggers a change event, but the formData in that event is still for the current step. In this scenario the change handler assigns the formData to the wrong step. 
By making sure each step has it's own form this issue will no longer exist.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@jboeijenga I think that this seems to have broken the back functionality so that the form is not populated after you've filled in values. Can you take a look at this bug?

**Comment by Lionheart70** [comment]
Morning all! Is there already an ETA on when we can expect this fix to be patched/rolled out?
(It is currently blocking our update)

**Comment by benjdlambert** [comment]
@Lionheart70 there's still a bug with this unfortunately that needs fixing before we merge this :pray: @jboeijenga do you have time to take a look at https://github.com/backstage/backstage/pull/26929#issuecomment-2396031291?

**Comment by Rugvip** [comment]
@benjdlambert is this covered by #27230?

**Comment by benjdlambert** [comment]
Yes, fixed in the patch fix yesterday.

**Pull request closed without merging**
