### PR TITLE
Add system icons for the built-in entity types and use them in the entity list of the `catalog-import` plugin

### PR DESCRIPTION
**Pull request by dhenneke**
Add default system icons for the most common entity types. The `catalog-import` plugin already introduced common icons for the kinds, however they were not replaceable nor extendable with a custom kind. It now uses the system icons feature of the app.

image

Is this a good idea and do you agree with my chosen naming schema (i.e. the plain entity name as icon name)?

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
❤️

**Comment by freben** [comment]
Thoughts on naming these `catalog:api`, `catalog:location` etc? Starting to fear semantic collisions in here...

**Comment by dhenneke** [comment]
> Thoughts on naming these `catalog:api`, `catalog:location` etc? Starting to fear semantic collisions in here...

@freben Yes that is a valid point that I also thought about, and I like the `catalog:<kind>` syntax. It could also be `kind:<kind>` or `entity:<kind>`. Would you generally think a `<plugin>:<icon>` pattern would make sense? Not sure if that is actually a really common need for many plugins to use custom icons. Each individual plugin should then of course have some kind of logic to find a reasonable default. The app won't be able to be shipped with the default icons for all plugins.

**Comment by freben** [comment]
Hm no, that's a good angle, I wasn't at all thinking in general plugin terms, just threw `catalog` out there as a prefix but maybe `kind` is better. Either way it does tie catalog-isms into it, but I think we're at a point where the catalog model is so entrenched in things that it's probably fine to let it have a unique position among core things.

**Comment by dhenneke** [comment]
I changed it to `kind:<kind>`. It find this namespaced approach indeed cleaner and less overlapping.

**Comment by Rugvip** [comment]
Yep, much nicer!

**Pull request merged**
