### PR TITLE
Upgraded microsite to Docusaurus v3

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Upgraded microsite to Docusaurus v3 following: https://docusaurus.io/blog/releases/3.0

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @luchillo17, this upgrade seemed very simple, any chance you can take a look to make sure I haven't missed anything, please?

**Comment by luchillo17** [comment]
Looks to me like the deps update go from a build `0.0.0-5703` which I think it's based on version `2.4.3` (don't know why the build has all `0`, I would personally use `2.4.3-5703`, but Docusaurus for some reason has all `0` for all but the official verions), to the version `3.0.0`.

Here are the breaking changes, as well as the migration guide:
https://github.com/facebook/docusaurus/releases/tag/v3.0.0
https://docusaurus.io/docs/migration/v3

The biggest chunk of the migration guide refers to MDX version update, which I believe we only use in the blog, it also mentions breaking changes on NodeJS, React and other deps, can't go checking the full breaking changes but if anything is bound to break, it should be the blog posts that use MDX, so I would go check a few blog posts in local machine to see if it still works after the update.

**Comment by freben** [comment]
Note also that this https://github.com/backstage/backstage/pull/21207 was a small incident that we weren't able to reproduce locally at the time. If you find some way of getting additional confidence in the landing page working still, that'd be great.

**Comment by luchillo17** [comment]
I've just noticed we don't have any tests for the microsite, should we add tests to it?

**Comment by awanlin** [comment]
Thanks for the feedback @luchillo17 and @freben, I'll follow up on that later this week 👍

**Comment by awanlin** [comment]
@freben I have this as Draft as I started in in the airpot on my way home from Chicago and I know this is going to take me a while to finish up. I thought that would help me avoid the stalebot?

**Comment by awanlin** [comment]
This was completed by someone else :)

**Pull request closed without merging**
