### PR TITLE
drop support for src-relative imports

### PR DESCRIPTION
**Pull request by Rugvip**
Without sane support from the TS compiler I don't think it's worth supporting this, as it ends up causing issues in a lot of different places.

Also expecting this to speed up intellisense, e.g. https://github.com/Microsoft/TypeScript/issues/30820

### CODE REVIEW

**Review by freben — APPROVED** [review]
Cool, this was probably the right thing to do :)

**Comment by Rugvip** [comment]
Yeah latest find was bad paths in `d.ts` files, breaking types.

Tbh reading the code I don't think it's always better to use src-relative imports either. In the cli it was a bit painful to refactor some of the `'lib/paths'` imports to `'../../../lib/paths'`. But something like and import from `'commands'` can leave you a bit confused, not knowing whether it's a local module or dependency.

**Comment by freben** [comment]
Agreed. And I think if we have eight levels of dot-dot, we may need to consider refactoring or splitting anyway :)

**Comment by Rugvip** [comment]
Yeah idd, since we're already split into separate packages I'm hoping we're good

**Pull request merged**
