### PR TITLE
chore: update keyv to version 5

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

Update keyv to version 5, see https://keyv.org/docs/v4-to-v5/

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
"We have stopped testing on Nodejs 18"

^ mildly worrying, should we only do this once we no longer support 18 too?

**Comment by drodil** [comment]
@freben yeah, but on the other hand, it says "and while we do not force or require you to use Nodejs 20+ we do recommend it.". I think this should be something to Backstage move soon too as 18 is already in maintenance and the EOL is 30 Apr 2025.

**Comment by benjdlambert** [comment]
@drodil we normally stop supporting it when there's another version promoted to LTS in it's place.

> Node.js 22 will enter long-term support (LTS) in October

So when 22 goes LTS, we will remove support for 18.

**Comment by benjdlambert** [comment]
@freben thoughts on pausing this for a few months until we drop 18:?

**Comment by freben** [comment]
Sorry I didn't see the last comment - yeah sure, but happy to get this in after that! #26612 as the formal dependency then

**Pull request closed without merging**
