### PR TITLE
Fixed techdocs-cli package publish CLI command missing awsBucketRootPath option + having the gcsBucketRootPath option misconfigured

### PR DESCRIPTION
**Pull request by alphahw**
Signed-off-by: Albin Halinen Wilén <git@alphahw.eu>

## Hey, I just made a Pull Request!

Fixed techdocs-cli package publish CLI command:
- previously missing awsBucketRootPath option (#15635)
- having the gcsBucketRootPath option misconfigured, previously returning a boolean vs a string

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by stephanschielke** [comment]
Shouldn't we remove the `--awsBucketRootPath` [option](https://github.com/backstage/backstage/blob/6a53ec652487cdb6c79bc711804b7db537812416/packages/techdocs-cli/src/commands/index.ts#L104) from the `migrate` command?

**Comment by OrkoHunter** [comment]
@alphahw Oh thanks! Have you also verified that this works? Just wanted to see if the bucket root path is passed all the way to the publisher https://github.com/backstage/backstage/blob/6a53ec652487cdb6c79bc711804b7db537812416/plugins/techdocs-node/src/stages/publish/awsS3.ts#L82

**Comment by alphahw** [comment]
> @alphahw Oh thanks! Have you also verified that this works? Just wanted to see if the bucket root path is passed all the way to the publisher
> 
> https://github.com/backstage/backstage/blob/6a53ec652487cdb6c79bc711804b7db537812416/plugins/techdocs-node/src/stages/publish/awsS3.ts#L82

Thanks for the reminder! It turned out the bucket root path option was indeed getting passed, but as a boolean vs a string due to the option signature leading `commander` to parse it that way. Fixed this; also applied to the GCS bucket root path option with the same issue.

**Comment by alphahw** [comment]
Hey @Rugvip @iamEAP! Sorry to tag you but wondering who would be able to/appropriate to reach out to for reviewing this? TIA for your help!

**Comment by iamEAP** [comment]
Lemme loop in @agentbellnorm and @realandersn

**Review by agentbellnorm — APPROVED** [review]
Thanks!

**Review by stephanschielke — APPROVED** [review]

**Pull request merged**
