### PR TITLE
fix: add cy.**.should to cypress eslintrc

### PR DESCRIPTION
**Pull request by mario-mui**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Thanks @mario-mui! This is good - Needs a changeset for the two packages though please :pray:

**Comment by mario-mui** [comment]
> Thanks @mario-mui! This is good - Needs a changeset for the two packages though please 🙏

sure

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice thanks! :tada:

**Comment by mario-mui** [comment]
@benjdlambert Maybe need your retry to enable auto-merge

**Pull request merged**
