### PR TITLE
moved AwsS3DiscoveryProcessor to where it should live

### PR DESCRIPTION
**Pull request by freben**

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Maybe even remove instantly? 🤔

**Comment by freben** [comment]
Yeah ... I was tempted. You think that would be ok here?

**Comment by Rugvip** [comment]
Yeah I think so, stability index 1 and it's a fairly low impact and simple move

**Comment by freben** [comment]
Alright, updated!

**Pull request merged**
