### PR TITLE
Sort imports with Prettier

### PR DESCRIPTION
**Pull request by jluk-box**
## Hey, I just made a Pull Request!

Add prettier-plugin-organize-imports to sort imports in TS code. This removes ambiguity, eases reading source code, but is most useful for diffing code during upgrading Backstage apps to newer releases - code generated by create-app is sorted and it’s easier to spot changes and align them with local project, which has the imports sorted. For this reason, the `.prettierignore` file is also modified to allow prettifying template directories.

https://github.com/simonhaenisch/prettier-plugin-organize-imports

I know that this change can bring in a lot of diffs in every file and may be controversial, so I’m open for discussion.

There is also an alternative prettier plugin, https://github.com/trivago/prettier-plugin-sort-imports, but it turns out that it garbles TypeScript code embedded in documentation code blocks in .md files.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
So I'm a fan of this, @backstage/maintainers thoughts? I wonder if this will require a changeset for every package or not as I guess technically it changes the output bundle but maybe it doesn't if the imports are sorted or whatever with rollup etc.

**Review by Rugvip — COMMENTED** [review]
Yep, also a fan! 👍

I think the way we want to roll this out is to start applying the style changes in separate PRs without actually enforcing the prettier rules just yet. Hoping that that can lower the impact for in-flight PRs a lil bit. Is that something you want to look at as well @jluk-box?

I believe the templates in prettierignore might be a remnant either from when we had more scaffolder templates in the repo, or if the CLI templating was slightly different. Should be safe to remove either way if the build is 🟢

**Comment by jluk-box** [comment]
I can try to make it into a "enforce check only on files changed in the PR" type of rule. This will ensure that the repo is converging to a good state without a need for a massive commit that rewrites all the files and should be also bearable for PR authors.

**Comment by Rugvip** [comment]
@jluk-box I'd say we actually prefer one or a few big PRs and then enforce it for the entire repo later on. I think in the long run that produces less noise and avoids the annoyance of tiny simple changes blowing up

**Pull request closed without merging**
