### PR TITLE
Added back support for when no branch is provided

### LINKED ISSUE #12740: Failed to read response error using UrlReader with Bitbucket Server
## Expected Behavior

Reading URLs with the `UrlReader` and Bitbucket Server should continue to work without errors as it previously was

## Actual Behavior

Using the `UrlReader` with Bitbucket Server we are getting the following error: "Failed to read response from <Url that was passed to the `UrlReader`>

## Possible Solution

From debugging this the issue seems to come from the assumption that the response has an `id` property on the `commit`:

https://github.com/backstage/backstage/blob/b67946b7f03cc0a33b36f3e48ec8d4382080ba39/packages/backend-common/src/reading/BitbucketServerUrlReader.ts#L208

This was changed as part of PR #12485 

In our case the response looks like this:

```json
{
  "values": [],
  "size": 25,
  "isLastPage": false,
  "start": 0,
  "limit": 25,
  "nextPageStart": 25
}
```

No `id` so it throws the error.

What seems to be a working solution for this is to add this code before throwing the error:

```ts
if (commits && commits.values && commits.values[0]) {
  const lastCommit = commits.values[0].id.substring(0, 12);
  return lastCommit;
}
```

## Steps to Reproduce

This is pretty complex to get setup, you need to create a plugin which uses the `UrlReader`, set that up with the backend and tries to read a URL from a Bitbucket Server instance. If I get time I will create a branch with a working sample but I'd like to focus on a PR with a fix first

## Context

This has broken several of our internal plugins that need to be able to read data from our Bitbucket Server instance

## Your Environment

We are using Bitbucket Server 7.2.4, which is fairly old, but this was working before without any issues

### PR DESCRIPTION
**Pull request by awanlin**
Signed-off-by: Andre Wanlin <67169551+awanlin@users.noreply.github.com>

## Hey, I just made a Pull Request!

This adds back support for when no branch is provided to the `UrlReader` for Bitbucket Server

Closes #12740 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
@carlitose @pjungermann @dhruvaldarji could use your review on this, please.

**Review by benjdlambert — APPROVED** [review]
This looks good to me, just waiting for the other reviewer(s) to chime in.

**Comment by awanlin** [comment]
Hi @carlitose @pjungermann @dhruvaldarji, we really need to get this into the next release on Tuesday, your help with a review would be greatly appreciated

**Review by pjungermann — APPROVED** [review]

**Comment by awanlin** [comment]
Thanks a ton @pjungermann! @benjdlambert or @Rugvip can we merge this in now if it looks to good you, please?

**Comment by awanlin** [comment]
Many thanks, so many thanks @benjdlambert and @pjungermann!

**Comment by regicsolutions** [comment]
Hi @awanlin @pjungermann running into an issue where i am not able to pull in the latest commits using the `UrlReader `for example when trying using the TODO Plugin i get the following:

Error
`500: Error`

Message
Failed to read response from https://bitbucket-server.com/rest/api/1.0/projects/LIQ/repos/incomingwire/commits/

Request
`GET /api/todo/v1/todos?entity=component%3Adefault%2Fincomingwire&offset=0&limit=10`

Full Error as JSON
```
{
  "error": {
    "name": "Error",
    "message": "Failed to read response from https://bitbucket-server.com/rest/api/1.0/projects/LIQ/repos/incomingwire/commits/",
    "level": "error",
    "service": "backstage"
  },
  "request": {
    "method": "GET",
    "url": "/api/todo/v1/todos?entity=component%3Adefault%2Fincomingwire&offset=0&limit=10"
  },
  "response": {
    "statusCode": 500
  }
}
```
But i am getting a valid response when directly hitting https://bitbucket-server.com/rest/api/1.0/projects/LIQ/repos/incomingwire/commits/

I bumped my @backstage/backend-common to 0.14.1 and am running the latest 1.4.0 release wondering if you have come across this issue?

**Comment by awanlin** [comment]
@regicsolutions this PR will fix that error but has not been released yet, it should be part of the `next` release path that goes out tomorrow though

**Pull request merged**
