### PR TITLE
TechDocs: Use type EntityName from catalog-model for entities

### PR DESCRIPTION
**Pull request by OrkoHunter**
Remove duplicated `ParsedEntityId` type from techdocs to use the type from `@backstage/catalog-model`

Ref: @freben's suggestion at https://github.com/backstage/backstage/pull/3452/files#r531005916

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by freben** [comment]
Nice! 🎉

Remember to make a changeset as well with `yarn changeset` so the update gets released properly.

**Comment by OrkoHunter** [comment]
Thanks @freben! 💯

**Review by hooloovooo — APPROVED** [review]

**Comment by hooloovooo** [comment]
Nice!

**Comment by andrewthauer** [comment]
I think this fixes #2091

**Comment by OrkoHunter** [comment]
cc @backstage/maintainers

**Review by freben — APPROVED** [review]

**Pull request merged**
