### PR TITLE
Add name for BackstageTab styles

### PR DESCRIPTION
**Pull request by saan800**
## Hey, I just made a Pull Request!

Added a name to core component Tab.tsx styles so can override the css globally for the theme as per 
https://backstage.io/docs/getting-started/app-custom-theme#overriding-backstage-and-material-ui-components-styles

From discord conversation at https://discord.com/channels/687207715902193673/959109962888515664

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @saan800! Thanks for this, think you might want to follow the guide for the bot to add DCO also! :pray:

**Comment by saan800** [comment]
@benjdlambert trying to, followed the docs on how to retrospecitvely add the DCO, but didn't seem to work. Will keep trying

**Comment by saan800** [comment]
@benjdlambert fixed now

**Review by benjdlambert — APPROVED** [review]
Thanks! :pray:

**Comment by suuus** [comment]
Thanks for your contribution @saan800 🙌 Please let me know if you’d like some help to contribute further.

**Pull request merged**
