### PR TITLE
Require EntityRefLink To Have Catalog Entry

### PR DESCRIPTION
**Pull request by esciuckas-bah**
## Hey, I just made a Pull Request!

The goal of these changes is to rework EntityRefLink component to verify whether an entity actually exists in the catalog before linking to a location. This is a problem that my team has had to work around since we do have owners and systems that are not necessarily in the catalog, but do have a relation listed. This creates false links that redirect users to the 404 page when they click them. 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hm. I wonder if this one would benefit from https://github.com/backstage/backstage/pull/1747, such that it could benefit from its significant speedups and the memoization + caching that it has.

**Comment by awanlin** [comment]
Hi @esciuckas-bah, I think this should probably be something that is opt-in. We find the current implementation very helpful as it gives users feedback that something is missing. If the links are just "dead" then that's a more confusing result as there's no feedback from what I can tell. I also think having to query the catalog each time seems like a steep price to pay for this functionality but perhaps what @freben suggested would help with that.

**Comment by freben** [comment]
Yeah. Since the presentation API (in its default form) does all of the fetching and memoization anyway, it's trivial to for example return a dedicated icon that signals that the target is missing.

**Comment by esciuckas-bah** [comment]
So in light of this conversation, as well as some UX changes for my team, we are just going to go ahead and close this PR, and solve it another way for our usage. Thank you.

**Pull request closed without merging**
