### PR TITLE
feat: Throttle calls to Bitbucket Server API

### PR DESCRIPTION
**Pull request by kjjuno**
## Hey, I just made a Pull Request!

This adds some throttling to the bitbucket server api calls. This helps to avoid flooding the server with too much traffic, and potentially taking down the server.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by cal5barton** [comment]
@Rugvip as discussed in the Framework SIG these are the new proposed changes, please review and add anyone else that needs to have eyes on this so we can push this forward. Thanks!

**Review by freben — APPROVED** [review]
Sorry I rudely rebased this to try to get it in for today's release.

The two separate plimits of course means we can reach 2 rps instead of 1. But it's a start!

**Comment by goququ** [comment]
Hi all! Great news. Will be cool if something like this will be implemented in gitlab discovery process also

**Comment by webark** [comment]
Was this inteded to be eventually configurable? We handle our throttling seperatly, so adding in this in this central place kind of tanked a lot of our performance.. And it's impossible to modify this at all without just completely overwriting the whole URL reader.. :(

**Comment by freben** [comment]
@webark Sorry to hear that. And this new way of doing things is not sufficient to replace what you had there before? Alright, would you mind opening an issue and/or pr to see if we can improve on that?

**Comment by webark** [comment]
@freben No. :/ Each bitbucket server key gets its own throttle that's configurable, and we have a lower threshold for personal tokens than the backstage token. Those are still much higher. I think it's like 1000 with a refill rate of 60 per second, and personally tokens we do 100 with a refill rate of 10 per second.

For ingestion, we use the incremental, and we moved off of locations a while ago, so there are no network calls to bitbucket (or anything but our cache) during the processing loop.

We also have places where we are using the url reader to fetch things on the users behalf. So like displaying a changelog, readme, configuration, or a contributing file on an entity detail page. Here the one call a second gets very noticeable. We could move these calls off of the url reader, but then we loose the unified interface between github, bitbucket, azure, etc.

If the value was configurable, then we could just set that to be the value we need, or optionally disable it altogether.

I'll look into getting a PR up to configure this setting though.

**Comment by bforbis** [comment]
Relates to #16692. @webark would having the rate limit at the provider level be better than at the reader level? Sounds like you want different limits for user triggered traffic vs automatic discovery traffic?

**Comment by webark** [comment]
Yea. I don't think there's should be a blanket artificial throttle (one that is not driven by a 429) outside of a place like the provider or processor or somewhere that is already iterating over a dataset.

We use the "incremental ingestors" and have enjoyed the kind of mechanism that is uses. Its interface for controlling its burst length and interval is a bit confusing at first (we initially thought the interval was between bursts rather that the interval of starting bursts for example). But how it allows you flexibility in how to process through the data set. Like with bitbucket server, we have about 7000 repos in about 400 projects, so we iterate over the projects, doing a search for catalog files (or other file types you care about processing) per project, and then iterating through those responses to get the final set of entities to ingest. And we can do that due to the flexibility that is available with the cursor you can provide.

**Comment by webark** [comment]
@knowacki23 we just patched that throttle library to be a no op, and it allows up to bypass the throttle. 

All for the proposal 👍

**Comment by knowacki23** [comment]
@webark do you have a link to the patch?

**Pull request merged**
