### PR TITLE
Update docker.md

### PR DESCRIPTION
**Pull request by nikkhn**
add missing "to"

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thank you! 😁 

Needs a bit of formatting with prettier, got things set up to check this out locally and run `yarn prettier --write docs/deployment/docker.md`?

**Comment by nikkhn** [comment]
@Rugvip thanks! ran prettier, i think it should be ok now?

**Comment by timbonicus** [comment]
Thank you for the correction! You're hitting all the unfortunate PR-checking hurdles for such a simple grammar fix - sorry about that.

Contributions to Backstage need to be signed off (DCO) to acknowledge your intent to donate the change to the project. The DCO check shows how to amend your commits to add sign-off — namely, `git rebase HEAD~2 --signoff`. Should be good to merge once that's fixed! For future commits, you can also use `git commit -s` to sign-off automatically.

**Comment by nikkhn** [comment]
@timbonicus AH good to know for next time - thanks!!

**Pull request merged**
