### PR TITLE
eslint: check internal dependencies too

### PR DESCRIPTION
**Pull request by benjdlambert**
- chore: fixing the eslint rule
- chore: add changeset

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@Rugvip I added a test here which should pass, but it seems that I need to create more fixtures for the `require.resolve` to pass here 

https://github.com/backstage/backstage/pull/16413/files#diff-865299679bc48c3d4d8f38fceb85cbec55023de64ffb2a88147950cc189f3b22R186

Otherwise we don't report the error.

Is that the right solution? It feels a little strange that the dependency has to be installed somewhere in a `node_modules` for this resolution to pass otherwise it doesn't work?

Removing that resolution breaks two other tests, but maybe that's the solution? Thoughts?

**Comment by Rugvip** [comment]
The reason for the resolution check is so that we can ignore packages without or with an invalid main field. Those packages tend to be type packages which we don't care about in this rule. There are gonna be other ways to check that though, but this is a simple and pretty performant one.

I think the simplest solution is likely to add a node_modules folder to the fixture, where you list both the internal and external

**Comment by Rugvip** [comment]
...

**Comment by benjdlambert** [comment]
Sure - I can do that for now just to get this through and do a release today to fix the eslint rules for packages that have changed deps and we can fix the type deps another way later 👍

**Review by freben — APPROVED** [review]

**Review by jhaals — APPROVED** [review]

**Pull request merged**
