### PR TITLE
[Kubernetes Plugin] ability to configure refresh interval on Kubernetes tab

### PR DESCRIPTION
**Pull request by goenning**
Signed-off-by: goenning <me@goenning.net>

## Hey, I just made a Pull Request!

We have 6 clusters, so every time a user loads the Kubernetes tab, there are nearly 40 requests required to fetch all information required, which is quite a lot. On top of that, this tab currently refreshes every 10s, which might be far too often for something that doesn't change that often.

This PR introduces an optional refreshIntervalMs property to `EntityKubernetesContent` so integrators have the ability to decide how often it should refresh.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jhaals** [comment]
Thank you!


@mclarke47 could you take a little look at this? :)

**Comment by asaini11** [comment]
Hi @mclarke47 any updates on this?

**Comment by goenning** [comment]
Thanks @mclarke47 I've added some notes to the installation docs. Is that what you had in mind?

**Review by mclarke47 — APPROVED** [review]
lgtm

**Pull request merged**
