### PR TITLE
Update cli-build-system.md

### PR DESCRIPTION
**Pull request by feanil**
Fix some wording/typos.

Signed-off-by: Feanil Patel <feanil@gmail.com>

### CODE REVIEW

**Comment by freben** [comment]
Hi! CI is complaining about formatting, you may want to run `yarn prettier --write docs/local-dev/cli-build-system.md` in your project root.

**Comment by feanil** [comment]
Ah, sorry about that, did the edit in the github UI so missed that check. Should be resolved now.

**Review by freben — APPROVED** [review]
Thanks!

**Comment by suuus** [comment]
Thanks for your contribution @feanil 🙌 Please let me know if you’d like some help to contribute further.

**Pull request merged**
