### PR TITLE
update imports for deprecations

### PR DESCRIPTION
**Pull request by punkle**
## Hey, I just made a Pull Request!

update imports for deprecations

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Nice, thanks! Need to rerun the API reports it seems.

**Comment by punkle** [comment]
@freben I have been having this odd problem with api-reports for a few weeks now. It is sorting some types differently in the output, however the types are effectively the same. Ever come across this?

**Comment by freben** [comment]
Yeah the api exporter has some quirks in how it picks especially aliased / generated names. It's not always 100% stable so you get like `_2` suffixed names and similar

**Review by freben — APPROVED** [review]
Thanks for this!

**Comment by freben** [comment]
Oh regarding contrib. It's always been a best-effort type thing. Fix things in there if you feel you have the time and inclination to; we do appreciate it. But if you don't that's fine too, especially for something relatively harmless such as deprecations.

**Pull request merged**
