### PR TITLE
feat: add starred entities backend

### LINKED ISSUE #10121: Persist starred entities in database
Currently starred entities are getting stored in local storage of the browser. So if a user star an entity in one browser and opens the backstage in another browser, the starred entities does not show. It is in that browser only.

## Feature Suggestion

If we can store the starred entities in the database. So that the starred entities would be available all the time regardless of the browser.

## Possible Implementation
Maybe create a backstage backend plugin or improve existing service to store the information about starred entities in the database.

## Context
Screenshot 2022-03-11 092425

### PR DESCRIPTION
**Pull request by dschwank**
## Hey, I just made a Pull Request!

New backend to persist the starred entities in the database. This allows users to switch the browser
/ machine without loosing the starred entities.

closes #10121

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by dschwank** [comment]
Thanks for the quick feedback @freben!

Nice idea 👍 the changes might not be too big. Let's see ...

**Comment by dschwank** [comment]
@freben Looks promising, will post an update tomorrow 👍

**Comment by dschwank** [comment]
@freben used some spare time to work on it. The implementation is already done, "just" some documentation is missing. Will hopefully open a PR tomorrow. 😉 Will open it separately from this one, such that we can close either one of them 👍

**Comment by dschwank** [comment]
Just pushed the draft to https://github.com/backstage/backstage/pull/13372

**Comment by freben** [comment]
Closing since https://github.com/backstage/backstage/pull/13372 was merged!

**Pull request closed without merging**
