### PR TITLE
Improve Easy Auth Docs

### PR DESCRIPTION
**Pull request by afscrome**
## Hey, I just made a Pull Request!

(Take two at #17661 as I left it too long and it's got closed due to inactivity.  Fixed the last comment from @Rugvip so hopefully this is ready to go.)

Incorperated feedback from issues around setting up easy auth
* Added missing configuration (See #17645)
* Added a note around configuring the sign in page locally

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Nice, thank you!  :+1: 

Let's :shipit:

**Comment by Rugvip** [comment]
Ih hey, DCO :p

**Comment by afscrome** [comment]
Gah.  One day I'll learn and sign my commits off first time.

**Comment by Rugvip** [comment]
@afscrome I use the following `.husky/prepare-commit-msg` + global .gitignore of that file:

```shell
#!/bin/sh
NAME=$(git config user.name)
EMAIL=$(git config user.email)
if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi
if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi
git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"
```

We ofc can't ship that by default as it needs to be an opt-in process

**Pull request merged**
