### PR TITLE
feat: allow specifying custom title for DevToolsLayout

### PR DESCRIPTION
**Pull request by drodil**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Thanks for this contribution @drodil

**Review by Rugvip — APPROVED** [review]
Thank you!

Needs an API report update

**Comment by drodil** [comment]
Api report updated

**Comment by awanlin** [comment]
Hi @benjdlambert, this isn't stale just needs someone to merge, any chance you could do that, please?

**Comment by benjdlambert** [comment]
@awanlin I just rebased this to fix the build issue and it should auto-merge :tada:

**Pull request merged**
