### PR TITLE
Custom scrollbar for SidebarScrollWrapper

### PR DESCRIPTION
**Pull request by tudi2d**
@freben As discussed here the PR for a better scroll behaviour - always happy about feedback! :) Unfortunately it looks different for Chrome & Firefox as Firefox has pretty neat native scrollbar, which I wanted to keep while it looks weird in Chrome so I overwrote the styles using the theme. When merging this it should look similar, but I'm not sure what is better - any opinion on this? 😕  

|Chrome|Firefox|
|----|:---:|
| sidebar | firefox |

Relates to changes introduced in #6257 & #6320 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by TejasQ — APPROVED** [review]
Very nice!

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice work!

**Comment by benjdlambert** [comment]
Just a follow up - can we hide the scrollbar when the mouse is not over the section in chrome?

**Comment by benjdlambert** [comment]
Similar to the firefox behaviour?>

**Comment by tudi2d** [comment]
Sure - will give it a go :)

**Pull request merged**
