### PR TITLE
Added solo.io portal plugin information and logo.

### PR DESCRIPTION
**Pull request by Charlesthebird**
## Hey, I just made a Pull Request!

This adds a Solo.io Gloo Portal Backstage plugin to the Backstage plugin marketplace.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by benjdlambert — CHANGES_REQUESTED** [review]
Hey :wave: thanks for this!

I think that I'm missing some install instructions in the right places here, and setup about the plugin and what it does?

Think that we want to get these things in place before we're promoting the plugin.

**Review by benjdlambert — CHANGES_REQUESTED** [review]
Hey :wave: thanks for this!

I think that I'm missing some install instructions in the right places here, and setup about the plugin and what it does?

Think that we want to get these things in place before we're promoting the plugin.

**Comment by Charlesthebird** [comment]
I added documentation about the setup, including a link to a video, and screenshots [in a github repo](https://github.com/solo-io/dev-portal-backstage-public#readme) and on [the npm page](https://www.npmjs.com/package/@solo.io/dev-portal-backstage-plugin).

**Review by benjdlambert — APPROVED** [review]
Nice thanks!

**Comment by Charlesthebird** [comment]
@benjdlambert Sorry to make another PR right away, but I noticed that the icon wasn't displaying correctly on the marketplace, so I updated that [here](https://github.com/backstage/backstage/pull/17980).

[These instructions](https://backstage.io/docs/plugins/add-to-marketplace) might need to be updated - I was making the image path relative to `/static` (like `img/abc.png`), but it looks like it needed the `/` at the beginning (`/img/abc.png`).

**Pull request merged**
