### PR TITLE
Introduce Backstage Enhancement Proposals (BEPs)

### LINKED ISSUE #15318: RFC: Backstage Enhancement Proposals
## Background

This RFC was originally planned to be part of #15317, but was split out into its own RFC to allow for more focused discussions.

### 🔖 Need

Large contributions are always challenging, but can also be extremely rewarding and help drive the project forward at a much greater pace. Our current process looks something like this: “RFC -> PR”, which is far from optimal. I feel there is a need for a more guided path throughout the entire lifecycle of large contributions, where there might be an initial design phase, but also room to iterate and collaborate. This ties tightly into ownership as well as visibility. There are many situations where it is valuable for the rest of the community to be able to see what significant chunks of work are ongoing, who owns them, how they plan to be implemented, and when. There can also be small pieces of information that are valuable, like if the work is being done in a specific branch, or time zone.

There is also a gap in our processes when it comes to settling RFCs and moving on to an actual implementation. We do not record any particular decision or outcome of an RFC, or who the owner is going forward and if there's any timeline involved. This gets particularly tricky when the resulting implementation of an RFC is very large and potentially split across multiple PRs.

### 🎉 Proposal

We introduce a new process for large contributions in the form of "Backstage Enhancement Proposals" (BEPs). BEPs come in the form of a document that details the need, purpose and intended outcome of the contribution. The BEP process is optional, but encouraged for large contributions and discouraged for smaller ones. Maintainers may also request that a BEP is created for incoming contributions.

The exact format of a BEP is not part of this proposal as we wanted to gather feedback before diving in deeper. Likewise, the medium of BEPs is not part of this proposal either, but options include these being either GitHub issues, markdown documents in a repository, or separate Google Docs documents. We would also have one or more templates to provide starting points. 

Each BEP is a living document that should have a reasonably up to date representation of the current state of the contribution. It does not need to dive into technical details or otherwise be too verbose. Its main responsibility is to answer “what, why, how, and who?”, giving other members of the community insight into ongoing work. The document should contain information about what project areas the contribution is expected to affect, as well as a list of owners of the contribution. There are no requirements on the owners other than that they exist, it can be any member of the community or project area teams.

One of the main purposes of a BEP is to give an opportunity to break apart large contributions into multiple pull requests, and to give reviewers a better understanding of the end goal of individual PRs. It also serves to find an owner for any new packages that might be part of the contribution, transferring the ownership to specific project areas where it otherwise would have fallen on the project maintainers. In this case one would typically start by creating an empty package and update the code owners file accordingly, with subsequent PRs being reviewed by the project area members.

The implementation of BEPs would come as part of an updated contribution documentation with a more clearly outlined lifecycle for large contributions. In the case where there is a need for a discussion and feedback loop ahead of beginning the implementation of a contribution, one would typically start with our current RFC process. That would in turn lead into settling and closing the RFC and replacing it with a BEP. The BEP may also have a number of dates associated with it to set expectations on when it should be complete, potential alpha/beta or deprecation periods, and so on.

### Packages specs

Rather than having BEPs as an optional way to structure large contributions, we could instead have a similar process around creating new packages or repositories. This would not be an optional process, but something that is required for any new package that is created. The requirements would be similar, in that there needs to be an owner and a group of people expected to work on the package, as well as the initial design. In many ways we already have this today, with the only large gap being the expectation of ownership of new packages.

The reason I’m proposing BEPs rather than processes centered around packages is that packages are often an implementation detail and limitation. Many new large contributions often need to be implemented in existing packages, and if our only process is centered around creating new packages, that might leave a significant gap. In the end I think we might do a bit of both.

### Naming

The BEP name is inspired by similar concepts like [PEPs](https://peps.python.org/pep-0001/) and [KEPs](https://github.com/kubernetes/enhancements/tree/master/keps). The naming is still very much up for discussion though, and there may be better alternatives that set better expectations.

### PR DESCRIPTION
**Pull request by Rugvip**
This introduces BEPs, somewhat similar to what was described in #15318, although these are a lot more focused on the design iteration phase rather than the implementation phase. Of course inspired by KEPs, and PEPs. In particular this borrows a lot from KEPs but trims away a fair amount of the process and adopts things for Backstage.

I'll let `beps/README.md` speak rather than repeating things here.

I was originally going to include an actual BEP in this PR as well, but in the end figured that's gonna hurt the discussion on the process itself so doing that in a separate PR instead.

Closes #15318

### CODE REVIEW

**Review by iamEAP — COMMENTED** [review]
Couple of comments/suggestions on the BEP docs.

Another question/suggestion: given BEPs are in source code, it makes sense to piggyback on `CODEOWNERS` to control approval.  Is there a way we could structure the BEPs folder to make that more automated?  e.g. project area sub-folders that have `CODEOWNERS` pre-added.

**Comment by Rugvip** [comment]
@iamEAP yep it's a good point about the folder structure and actually how KEPs are structured. Main reason I didn't include that now was just the slightly increased overhead to the process. I figured we could start with seeing how BEPs are used and if a lot of them end up being for individual project areas or not. That's probably silly thought and we should try to keep work as cleanly separated into areas as possible from the start. I'll try to update the process to include project area folders.

**Comment by iamEAP** [comment]
@Rugvip Even just adding a manual step somewhere in the process that's like, "Be sure to add relevant project area groups as CODEOWNERS of the BEP" could suffice for now.

**Comment by Rugvip** [comment]
@iamEAP 👍 , yep opted for that instead, added as a bullet to the quick start

**Review by benjdlambert — APPROVED** [review]

**Review by freben — APPROVED** [review]

**Pull request merged**
