### PR TITLE
Organize catalog examples into sub-directories, cleanup (#2963)

### PR DESCRIPTION
**Pull request by punkle**
## Hey, I just made a Pull Request!

This commit organizes the example locations into sub-directories. refactors part of (#2963)

A later commit is going to add an "example" organization of users and
groups. Re-organizing this upfront, is going to make the follow up
commits a little tidier.

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Slight concern that this'll break some existing apps by moving the examples they depend on, but I think it's long enough since we moved over to using the all-*.yaml files

**Comment by punkle** [comment]
@Rugvip Is there anything that I can do to verify those apps will not break?

**Comment by freben** [comment]
Not really, I think. You could search around the repo for remaining usages of the old paths but I doubt there are any. Only risk here would be people that are on very old versions of our libs as dependencies, and I don't think you should worry.

**Comment by freben** [comment]
Time to make this into a PR?

**Pull request merged**
