### PR TITLE
remove some yarn.lock impurity in master by adjusting msw dep

### PR DESCRIPTION
**Pull request by freben**

### CODE REVIEW

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Closed and re-opened to sync the workflows as they weren't running :shrug:

**Comment by freben** [comment]
oh github, y u do be do

**Comment by freben** [comment]
Skipping changeset since this was just merged and not released yet

**Comment by freben** [comment]
ping @ivangonzalezacuna

**Comment by ivangonzalezacuna** [comment]
Okay, this was one of the things that you told me yesterday, right? Sorry for not doing it before, just working on other stuff first.

**Comment by freben** [comment]
perfectly fine! as maintainers we occasionally get these things happen and just take the chore of making the lockfile clean :)

**Review by jhaals — APPROVED** [review]

**Pull request merged**
