### PR TITLE
plugin-cost-insights: Adds api test

### PR DESCRIPTION
**Pull request by joaomilho**
## Hey, I just made a Pull Request!

A suggestion to help keep the exported API stable for cost insights. A simple and pragmatic test to its exports.

As an example we've been doing this in the possibly new plugin-api & app-api https://github.com/backstage/backstage/compare/mob/evolution-v2#diff-3117f9485116624c1cd97f844a7653bbb82513e7ec26fdf1b00588d5ceae3669

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
I'm not sure of the value of this test? It looks like it's asserting that 1=1 and any small change to anything in the index.ts will break this test? Maybe @timbonicus or @backstage/silver-lining think differently?

Maybe it's worth testing these modules individually rather than testing the entire things that's exported?

**Comment by ryanvazquez** [comment]
Yeah, mostly agree with @benjdlambert. This would result in a lot of duplication as well - though I see the need for some sort of sanity check.

I explored an approach that declared public exports at the submodule level using a public export file in [this PR](https://github.com/backstage/backstage/pull/4793/files) but we ultimately decided against it as it strayed too far from [ADR004](https://backstage.io/docs/architecture-decisions/adrs-adr004).

**Comment by joaomilho** [comment]
`any small change to anything in the index.ts will break this test?` No. Only if the API that's exported changes the test breaks. But yes, I wouldn't call this a unite test, but a sanity check. With it the break between 0.8.2 and 0.8.3 would not have happened.

**Comment by joaomilho** [comment]
As discussed, I concur this solution is odd, so let's discuss the underlying problem a bit more before going for a solution.

**Pull request closed without merging**
