### PR TITLE
Add lag to kafka plugin

### PR DESCRIPTION
**Pull request by ebarriosjr**
## Hey, I just made a Pull Request!

I added a lag column into the kafka plugin that just calcuate the topicOffset minus the groupOffset

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4833-ku2wuh0ttqua0hsqpux4m0axicls8rkh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60420ef0f285af6eb9a11d9b

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4833-ku2wuh0ttqua0hsqpux4m0axicls8rkh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60420ef0f285af6eb9a11d9b

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4833-ku2wuh0ttqua0hsqpux4m0axicls8rkh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60420ef0f285af6eb9a11d9b

**Comment by OrkoHunter** [comment]
This PR has 145 commits! No wonder the DCO check is having a hard time to pass. I recommend branching out fresh the master of backstage/backstage!

**Comment by OrkoHunter** [comment]
Also, I wonder if there is any chance that you are running the fork of Backstage app in production? Should [create a standalone app](https://backstage.io/docs/getting-started/#create-your-backstage-app) if yes, and use the fork only for contributing back. :)

**Comment by ebarriosjr** [comment]
It got out of hand. Will close this pull request and create a new one. Sorry

**Comment by OrkoHunter** [comment]
No worries! git is fun at times 😅 <3

**Pull request closed without merging**
