### PR TITLE
Migrate LDAP catalog module to the new backend system

### PR DESCRIPTION
**Pull request by dweber019**
## Hey, I just made a Pull Request!

Migrated the LDAP catalog backend to the new backend system.
I hope I caught all things.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by mschmermer** [comment]
Is this pull request required for using this Plugin with the new backend it works this also without?

**Comment by dweber019** [comment]
Should work with both legacy and new backend.

**Review by Rugvip — APPROVED** [review]
Awesome, thank you! 🎉 👏 

Was thinking that it's a bit unfortunate to export the new legacy methods, but on second thought we might as well. It'll all be removed in the future anyway regardless. I saw you added some deprecations there too 👍

**Comment by mschmermer** [comment]
> Should work with both legacy and new backend.

Are i sure that the legacy Plugin works with the new backend? I try it out but dont se the User only in the Plugin DB not in the catalog. With processor or providor...

**Comment by dweber019** [comment]
Just to get this right. When using the legacy backend like
image

you have to do it like this https://github.com/backstage/backstage/blob/master/docs/integrations/ldap/org--old.md.
Just tested version 0.6.0-next.1 in our legacy backend setup and works, even when it's not the newest backstage overall (1.22.0).
One thing I missed is to change the org--old.md regarding using `LdapOrgEntityProvider.fromLegacyConfig` instead of `LdapOrgEntityProvider.fromConfig`.

For the new backend like
image

you need to do it like https://github.com/backstage/backstage/blob/master/docs/integrations/ldap/org.md.
I never tested something like this `backend.add(legacyPlugin('todo', import('./plugins/todo')));` to be honest.

**Comment by dweber019** [comment]
Checked the new backend implementation and getting
`Plugin 'catalog' startup failed; caused by TypeError: Cannot use 'in' operator to search for 'cron' in PT1H`.

When I use
```
        schedule:
          frequency: { minutes: 60 }
          timeout: { minutes: 30 }
```
then it works.

**Comment by mschmermer** [comment]
> Checked the new backend implementation and getting
> 
> `Plugin 'catalog' startup failed; caused by TypeError: Cannot use 'in' operator to search for 'cron' in PT1H` when using
> 
> ```
> 
>         schedule:
> 
>           frequency: PT1H
> 
>           timeout: PT15M
> 
> ```
> 
> 
> 
> When I use
> 
> ```
> 
>         schedule:
> 
>           frequency: { minutes: 60 }
> 
>           timeout: { minutes: 30 }
> 
> ```
> 
> then it works.
> 
> 
> 
> @benjdlambert @Rugvip any idea what this could be?

Have you found a solution to the problem?

**Pull request merged**
