### PR TITLE
Devtools Plugin ReadMe Update

### PR DESCRIPTION
**Pull request by stephondoestech**
## Hey, I just made a Pull Request!

I updated the devtools backend plugin readme document to add a missing property that will cause the build to fail without it. 

#### :heavy_check_mark: Checklist

---
'@backstage/plugins/devtools-backend': patch
---

Added `discovery` property to the readme documentation to ensure that it will build when setting it up as new to a Backstage instance

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — COMMENTED** [review]
Good catch @stephondoestech! I know this is still a draft but I noticed you put the changeset in the PR description. That should actually get added as a Markdown file. From the root of the project run `yarn changeset` and follow the prompts. That will generate the file for you in the right location 👍

**Comment by stephondoestech** [comment]
Thanks @awanlin. I have a few branches open so I did that to make sure I wouldn't mix them up. This one should be ready to go now.

**Review by Rugvip — APPROVED** [review]
Thank you! 👍

**Comment by awanlin** [comment]
Thanks again @stephondoestech 🚀

**Pull request merged**
