### PR TITLE
Scaffolder: Add handlebar 'ne' helper

### PR DESCRIPTION
**Pull request by OscarDHdz**
Signed-off-by: OscarDHdz <v-ohernandez@expediagroup.com>

## Hey, I just made a Pull Request!

I've added a `eq` helper to Scaffolder:handlebars. 

```yaml
steps:
    - id: coo-id
      name: Cool Action
      if: "{{ ne parameters.name 'Hello' }}"
```

This is just a complementary `handlebars helper` as part of the `eq` introduced a few days ago with this PR: https://github.com/backstage/backstage/pull/6424 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
I think I prefer `notEq` rather than `ne` it's a little clearer of the intent.

**Comment by OscarDHdz** [comment]
> I think I prefer `notEq` rather than `ne` it's a little clearer of the intent.

Sounds good, I only used `ne` because didn't know if all they needed to be `lowercase` 😆 .
Update done 👍

**Comment by freben** [comment]
Maybe a silly question - does it support chaining? Can one make a unary `not` so that you'll write `not eq`?

**Comment by benjdlambert** [comment]
Pretty sure you could definitely do this. Much better.

**Comment by Fox32** [comment]
> Maybe a silly question - does it support chaining? Can one make a unary `not` so that you'll write `not eq`?

We already have a `not` 🎉  https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts#L58

**Comment by benjdlambert** [comment]
I thought I remember seeing that. And i'm pretty sure we can chain them together right? or least I think we can do `{{ not (eq something "something") }}`

**Comment by benjdlambert** [comment]
@OscarDHdz I'm in favour of closing this if something like the following can work for you use case. I don't really want to add too many extra helpers when we have #6437 coming up.

```yaml
steps:
    - id: coo-id
      name: Cool Action
      if: "{{ not (eq parameters.name 'Hello') }}"
```

**Comment by OscarDHdz** [comment]
🤯 Yup it works!! Thanks for the help!
Closing PR... 👍

**Comment by benjdlambert** [comment]
Sweet!

**Pull request closed without merging**
