### PR TITLE
[Techdocs] Add configurable default mkdocs file

### PR DESCRIPTION
**Pull request by Dnomyar**
## [Techdocs] add configurable default mkdocs file

hey folks, 
I'd like to propose this change to allow to have a default configurable mkdocs file. It would be used if no `mkdocs.[yaml,yml]` exists in the repository 

```
    # (Optional) techdocs.generator.defaultMkdocsFile can be used to specify a default mkdocs file to be applied when a repository does not already contains mkdocs configuration
    defaultMkdocsFile: './default-mkdocs.yml'
```

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] ~Screenshots attached (for UI changes)~
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @Dnomyar, before we dive too deep into the review I think we need to align a few things. @dschwank has PR #18699 that adds support for custom plugins that in theory would get superseded by this work. 

Also, your change doesn't seem to support the TechDocs CLI which would leave out a lot of Adopters who would want to use this feature

@camilaibs, sorry to ping you directly, just looking for some guidance for this one, please

CC @andrewthauer just wanted to loop you in seeing as you have talked about this in the past

**Comment by Dnomyar** [comment]
Hi @awanlin, thanks for getting back to me about that.
> @dschwank has PR https://github.com/backstage/backstage/pull/18699 that adds support for custom plugins that in theory would get superseded by this work.

Sorry @dschwank, I did not see your PR before starting working on that.

> Also, your change doesn't seem to support the TechDocs CLI which would leave out a lot of Adopters who would want to use this feature

I am happy to look at extending this to the CLI as well

**Comment by awanlin** [comment]
@soapraj @agentbellnorm could you provide us with some guidance on this, please?

**Comment by Dnomyar** [comment]
I updated to extend to the CLI as well

**Comment by dschwank** [comment]
@awanlin & @Dnomyar I just had a look at this PR. I would say that this PR (#18830) and [#18699](https://github.com/backstage/backstage/pull/18699) have two different purposes, which are not in conflict with each other.

1. #18830
Define a custom default `mkdocs.yaml` file, which is used _if there is no mkdocs.yaml in the repo_ - otherwise this default file is not used at all. No merge, no nothing.
So far there was only a hardcoded default file. With this PR, we add the ability to be more flexible about that default file.

2. #18699 
Define a set of default mkdocs plugins, which should be added to each `mkdocs.yaml`. It doesn't matter if a `mkdocs.yaml` file is in the repo or not, with this PR we make sure that a default set of mkdocs plugins is always added. The advantage of that is, that one does not have to add the custom plugin to all `mkdocs.yaml` files, but can define it once and for all. So far this feature was limited to adding `techdocs-core` as default. With [#18699](https://github.com/backstage/backstage/pull/18699) this list of default plugins can now be customized.
Why do we need it? We have a custom image to build techdocs, which has additional mkdocs plugins. For the sake of streamlining, we would like to use that plugin for all docs. To do so, we would have to add it either to the `techdocs-core` (which might not fit to the community) or we would have to add it manually to _ALL_ `mkdocs.yaml` files. That's a bit too much work - so with PR [#18699](https://github.com/backstage/backstage/pull/18699) we can define it once and for all.

So from my point of view the two PRs are not in conflict. They just make the hardcoded "defaults" of techdocs more flexible. For sure, we could also add a "merge" feature to the default file, but I would say that adds too much corner cases / issues.

**Comment by Dnomyar** [comment]
Thanks @dschwank for the analysis. Here is my take:

|                   | PR #18830                                                                                                                                                                                                                                  | PR #18699                                                      |
| ----------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------------------- |
| Problem           | Define multiple default properties of the mkdocs configuration (`docs_dir` and `plugins`) when no mkdocs file is defined in the repository.                                                                                                | Define a set of default `plugins` (extends `plugins` property) |
| Solution          | Default configurable mkdocs file                                                                                                                                                                                                           | Default configurable set of plugins                            |
| Solution benefits | By design, allows to configure any property when no mkdocs file is defined in the repository                                                                                                                                               | Allows to defined a set of default `plugins`                   |
| Solution limits   | The property `site_name` is required for the mkdocs to be valid. Opposite to the default (hard coded) mkdocs configuration, it does not uses the component name which forces a generic name. Duplication with the hard coded mkdcs config. | Only allows to extend the `plugins` property.                |

On one hand, the configuration file allow to have **any** property as a default but also properties that we don't want as default like `site_name`. On the other hand, the PR #18699 allows to override **only one** property (`plugins`).

I wonder if we need a mix between those two here? Would it be possible/a good idea to extend the PR #18699 to allow to override any property. For instance:

```yaml
techdocs:
  generator:
    mkdocsOverrides: # mkdocsOverrides are applied before mkdocsExtends
      plugins: [] # replaces omitTechdocsCorePlugin, comment out to keep plugins from the repository mkdocs file
      docs_dir: .
    mkdocsExtends:
      plugins: 
        - section-index
        - my-custom-plugin
```
Note that I replaced `defaultPlugins` by `plugins` to have the same key than the mkdocs file.
The `mkdocsOverrides` and `mkdocsExtends` keys being the same than the one in the mkdocs file. The keys would be dynamic (I don't know if it is possible). The `omitTechdocsCorePlugin` could then be depreciated. It might also simplify the implementation (we could use function composition). I don't know how easy would it be for the CLI to integrate this configuration.

> What are your thoughts?

So my current thinking is:
- close this PR
- update the PR #18699 to allows extensibility in the line of what I suggested above.

Any thoughts?

**Comment by agentbellnorm** [comment]
Hey @Dnomyar, Could you explain your use case for this change, and the problem it would solve?

This would only make sense for the simplest documentation sites, as it would be impossible to use the [nav](https://www.mkdocs.org/user-guide/configuration/#nav) key right?

Also, does it make sense to have static default values for `site_name` and `site_description` for multiple documentation sites?

At Spotify we don't really have a problem with components without mkdocs.yaml files as all our scaffolder templates include it.

**Comment by Dnomyar** [comment]
> Hey @Dnomyar, Could you explain your use case for this change, and the problem it would solve?
> At Spotify we don't really have a problem with components without mkdocs.yaml files as all our scaffolder templates include it.

Hey @agentbellnorm, I am looking to onboard many applications in the catalog documentation. Most of those applications don't have `mkdocs.yaml` files. So instead of asking teams to add a mkdocs.yaml, we could use a default mkdocs. Teams can create the mkdocs file down the line if they want to customise their documentation (using `nav` for instance).

The default (hard coded) mkdocs file `docs_dir` is `docs`. For many applications, the documentation is actually in the root `.` (no convention of having a `docs` folder). Setting `docs_dir` as `.` also requires the `same-dir` plugin. When the `docs` folder does not exists, the mkdocs command fails.

 I'd rather have a documentation that follows the structure of the markdowns files in the repository (not using `nav`) first, than no documentation at all.

> Also, does it make sense to have static default values for site_name and site_description for multiple documentation sites?

No, I don't think it does. Having a default mkdocs file can be a solution for having a fixed default values for `docs_dir` and `plugins` (what this PR tries to solve) but it is not optimal as `site_name` is a required value and it does not make much sense to have it as a static value. Hence, my suggestion to to close this PR and find another solution.

> This would only make sense for the simplest documentation sites, as it would be impossible to use the [nav](https://www.mkdocs.org/user-guide/configuration/#nav) key right?

Yes for onboarding purposes. To archive that (through the way of a default configuration), I'd need to have a default value for `docs_dir` and a default list of `plugins`. For the latter, the PR #18699 seems be to a solution.

---

On another note, I saw there are already some configuration like `omitTechdocsCorePlugin` already exists and the PR #18699 is going to add `defaultPlugins`. If we need to have `defaultDocsDir`, the configuration would start to look a bit messy. The `mkdocsOverrides` and `mkdocsExtends` that I suggested in the earlier message could be over-engineering but could also help to have a uniform configuration in the long term.

**Comment by squid-ney** [comment]
Hi @Dnomyar 

> I am looking to onboard many applications in the catalog documentation. Most of those applications don't have mkdocs.yaml files. So instead of asking teams to add a mkdocs.yaml, we could use a default mkdocs.

For your above use case, you mentioned that, "PR https://github.com/backstage/backstage/pull/18699 seems to be a solution".  I'm curious if extending this solution would actually resolve your use case. I believe with the solution to make the `docs_dir ` default value configurable, you would still have the task of needing to create `mkdocs.yaml` files for all of the non-onboarded repositories.

**Comment by Dnomyar** [comment]
Hey @squid-ney,

> For your above use case, you mentioned that, "PR https://github.com/backstage/backstage/pull/18699 seems to be a solution". I'm curious if extending this solution would actually resolve your use case. I believe with the solution to make the docs_dir  default value configurable, you would still have the task of needing to create mkdocs.yaml files for all of the non-onboarded repositories.

I think it would. This function already generates a default `mkdocs.yml` file (and copies it in the cloned repository) as a fallback (if there is no existing `mkdocs.yml` in the repository): https://github.com/backstage/backstage/blob/712d1118bfeb77d4a78fffd78f471320373eb742/plugins/techdocs-node/src/stages/generate/helpers.ts#L153-L185

It is called here 
https://github.com/backstage/backstage/pull/18699/files#diff-f21421000cf30c2e5550c84c1eb44c491b73158077bd11fbc99732877d7e8f1bL102-R135 before the `patchMkdocsYmlWithPlugins` function that add custom defaults plugins (https://github.com/backstage/backstage/pull/18699 's change). So looking at a glance, the  PR https://github.com/backstage/backstage/pull/18699 would resolve part of my problem (the `plugins` part)

The custom `docs_dir` problem is remaining.

**Comment by squid-ney** [comment]
@Dnomyar Gotcha! Then I think what you proposed about closing this PR and creating another PR to read in an optional `defaultDocsDir` configuration value for `docs_dir` makes sense.

**Comment by Dnomyar** [comment]
> Would you mind explaining a bit more about why both mkdocsOverrides and mkdocsExtends are needed?

For the following, let's pretend we use `defaultDocsDir` configuration key to customise the `docs_dir` value in the function that generates the mkdocs (`generateMkdocsYml`). 

In fairness, `mkdocsOverrides` and `mkdocsExtends` were just conversation starters for:
- Configuration semantics clarity. I noticed that there is a difference in the semantics between `defaultPlugins` (witch *extends* the list of plugins) and `defaultDocsDir` (that kinds of *overrides* the default hard coded value in the function `generateMkdocsYml`). I thought having that explicit would be more clear in the configuration.
- Extensibility purposes. I noticed that there already is a `omitTechdocsCorePlugin` configuration entry. The change https://github.com/backstage/backstage/pull/18699 added `defaultPlugins` and maybe a future change will add `defaultDocsDir`. Eventually, there could be many configuration entries to customise every aspect of the mkdocs.yml (exclude this, include that, replace that, etc) and bloat the `app-config.yml`. I was trying to explore a configuration approach that would allow extensibility for future configuration requirements, by providing generic operations like override and extend.

Here are the reasons why I suggested something `mkdocsOverrides` and `mkdocsExtends`. As I said, this suggestion was intended to be a conversation starter and would need to be thought through. I am conscious that my experience with using backstage and mkdocs is low so I could be over-engineering as well.

@squid-ney or others, any thoughts?

**Comment by squid-ney** [comment]
Hi @Dnomyar, thanks for providing this explanation! 
I have chatted a little bit with @agentbellnorm and the rest of our team.

We are thinking that it is not worth restructuring the `mkdocs` config because we do not see many more items being added to the `mkdocs` key. Of course this approach could always be re-evaluated in the future if our assumption is incorrect.

I think that creating a new config key for the `defaultDocsDir` would be the best approach. The `defaultDocsDir` config should also be available as a cli arg. Does this sound alright with you ?

**Comment by Dnomyar** [comment]
> Hi @Dnomyar, thanks for providing this explanation!
> I have chatted a little bit with @agentbellnorm and the rest of our team.

Hi @squid-ney, thanks folks for considering my suggestion.

> We are thinking that it is not worth restructuring the mkdocs config because we do not see many more items being added to the mkdocs key. Of course this approach could always be re-evaluated in the future if our assumption is incorrect.

That's fair enough I think

> I think that creating a new config key for the defaultDocsDir would be the best approach. The defaultDocsDir config should also be available as a cli arg. Does this sound alright with you ?

That sounds good to me!

I am closing this PR as it seems that we reached an agreement. I'll look at implementing defaultDocsDir when I have some time (unless someone else wants to do it before)

**Comment by asos-robbell** [comment]
@Dnomyar — was a separate issue created for your defaultDocsDir implementation plans? The scenario I have which I'd like to eliminate from all `mkdocs.yml` files is not just a list of plugins (as is currently implemented with `defaultPlugins: string[]`, but their configuration too, which round require `defaultPlugins: object[]`:

```
defaultPlugins:
  - techdocs-core
  - awesome-pages
  - kroki:
      FencePrefix: ''
      ServerUrl: 'https://myprivatekrokiserver.com'
```

**Pull request closed without merging**
