### PR TITLE
Fix git url parse version

### PR DESCRIPTION
**Pull request by carlo-colombo**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by OrkoHunter** [comment]
The only PR I can see corresponding to this release is https://github.com/IonicaBizau/git-url-parse/pull/128

@carlo-colombo Can you help further by reporting the issue to them, what was the error you saw, etc.?

cc @goober Since you are active in the Backstage community as well! :)

**Comment by carlo-colombo** [comment]
@OrkoHunter adding some context: it failed to load our  non-location entity that is loaded from a Bitbucket server repository with the error ` Expected object at root, got string` , this is caused by the library failing to extract the path name for the yaml file and bitbucket reporting the listing of the directory (and thus failing to parse as yaml). Did not investigate too much in the library but the differences are that the other entities loaded are `Location` and that they are in the root of the repository while the failing one was in a subfiolder and a `Template`.

I am going to report it to the library repo too.

**Comment by goober** [comment]
@carlo-colombo I was the one adding the latest patch to the git-url-parse library and I am most probably responsible for your issues. Could you please provide an example url that you are trying to use and I will make sure that the library has test-coverage for that case as well.

**Comment by carlo-colombo** [comment]
@goober the url that fails to get the filename is like `https://example.com/projects/some-project/repos/some-repo/browse/entities/filename.yaml` 

The filepath at[ this poin](https://github.com/backstage/backstage/blob/master/packages/integration/src/bitbucket/core.ts#L123)t is null/empty then the url that is fetched looks like

`https://example.com/rest/api/1.0/projects/some-project/repos/some-template/raw/entities?at=`

instead of

`https://example.com/rest/api/1.0/projects/some-project/repos/some-template/raw/entities/filename.yaml?at=`

**Comment by goober** [comment]
Thanks for the report @carlo-colombo I have provided a fix to the underlying library:
https://github.com/IonicaBizau/git-url-parse/pull/131

**Comment by freben** [comment]
@goober reviewed! :)

**Comment by freben** [comment]
So was this the fix that made things work for everybody, or did it introduce some other problem? I'd love to get a good fix in before release :)

**Comment by goober** [comment]
I suggest that you downgrade the git-url-parse library in todays release and and then hopefully my fix in the library will be released so it can be included in next week's backstage release. 

The reason I made the initial change in git-url-parse was to be able to fix the jenkins-plugin for correctly parse the build commit when you have several git repos in your build pipeline.

**Comment by benjdlambert** [comment]
@goober Ok perfect - we have a plan!

**Comment by freben** [comment]
@goober and `11.4.4` is known good? For some reason of known. At least not one of those that people have reported having additional problems with.

**Comment by goober** [comment]
@freben yes, we have been using `11.4.4` in production for several month's without problem with Bitbucket Server.
we are utilizing the catalog, tech-docs and the scaffolder

**Comment by carlo-colombo** [comment]
For us forcing resolution to 11.4.4 solved the problem we had loading the entity. And we used before accidentally updating to 11.5 for some time with bitbucket server with no issue

**Comment by freben** [comment]
Alright! Thanks all, appreciated.

We'll just have to remember to check for the next 1.5+ release in the future.

**Review by freben — APPROVED** [review]

**Review by iamEAP — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
