### PR TITLE
add names to sidebar submenu styles

### PR DESCRIPTION
**Pull request by alisaswong**
## Hey, I just made a Pull Request!

Added names to sidebar submenu styles so that they can be overwritten for custom styling

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
@alisaswong Hi, and thank you! This makes sense. However you will have to make a changeset too, so that the changes get published.

**Comment by alisaswong** [comment]
> @alisaswong Hi, and thank you! This makes sense. However you will have to make a changeset too, so that the changes get published.

@freben Thank you! I just added in the changeset

**Comment by alisaswong** [comment]
@freben Would you mind merging this in? I don't have write access

**Comment by freben** [comment]
Sure! Just had not yet gotten around to it

**Pull request merged**
