### PR TITLE
[Azure DevOps] Added `azureDevOpsAnnotatorProcessorModule`

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Added `azureDevOpsAnnotatorProcessorModule` to make using the `AzureDevOpsAnnotatorProcessor` with the new backend system easier. This is based on feedback from here: https://github.com/backstage/backstage/pull/21595#discussion_r1416955093

🎩 tip to @afscrome, this is much nicer!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by afscrome — APPROVED** [review]
IGNORE, early submission - see next approval comments

**Review by afscrome — APPROVED** [review]
Definitely an improvement, but I'd still would like to make the case for just including this in the default Azure Devops module, rather than have this be an addon thing.  I've been wanting the capabilities from the `AzureDevOpsAnnotatorProcessor` module now for a while, but didn't find out it existed until I saw your previous Pr. 

The Azure Devops UI components rely on the presence of the `dev.azure.com/project-repo` (and `dev.azure.com/host-org` for multi org configurations).  This means that by default entities won't be linked to azure devops until the user manually adds these annotations

This is where the `AzureDevOpsAnnotatorProcessor` comes in - it will attempt to auto populate those entities based on the Location related to the entity.  When this module is installed, entities will be automatically linked to the repo they came from, without users needing to manually link them.

Installing this module for users who are already manually specifying the annotations will not have any effect - the process will not override any manually provided values.

However for new users, it means that the Azure Devops integration is going to work without needing to manually add the annotation to every entity individually

There is only one situation in which I can see that installing this processor by default may cause a regression - when `catalog-info.yaml` files are in a different repo to the code. In this case, whereas previously the no azure devops integration would show up until someone manually provided the `dev.azure.com` annotations, now it would by default link to the repo where the catalog definition came from, rather than the true application repo.  This will then be fixed once the `dev.azure.com` annotations are manually provided.

Overall, I think having this pre-installed makes the experience much better for people getting started with backstage.  The only case I can think of where it would regress is an edge case, and really only trades one type of wrong for another type of wrong.  (In both cases, backstage fails to link to the correct repos until a user manually specifies the `dev.azure.com` annotations..

**Comment by awanlin** [comment]
Hi @afscrome, all your comments make sense and you are slowly winning me over. There are some things that need to be taken into consideration that aren't included in your thoughts. 

One item of concern is that it's slow with the multi-org changes, we need to rebuild the `WebApi` each time as we don't know what to use for credentials until the call is made. Now, if you don't provide the `host-org` annotation it falls back to the default from the old `azureDevOps` config. So having that annotation there when you may not need it would be a performance impact. I have a few other ideas that could help with this so that would help us resolve this.

Once the above is resolved then I'd be much more inclined to have this be added by default.

Side note: somewhat surprised you had not seen this before? https://github.com/backstage/backstage/pull/19412

**Comment by awanlin** [comment]
Oh, another option would just to make it configurable which annotations it adds. The more I think about it the more I think this would be the best direction to take. But I'd prefer to do that in a follow up PR so this can get in sooner than later

**Pull request closed without merging**
