### PR TITLE
Update and rename jira-dashboard to jira-dashboard.yaml

### PR DESCRIPTION
**Pull request by fridajac**
## Hey, I just made a Pull Request!

In the last PR, the filename extension .yaml was missing. It has been added and the "addedDate" updated.
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by fridajac** [comment]
Here it is @awanlin :+1:  Thanks!

**Review by awanlin — APPROVED** [review]
Thanks @fridajac, sorry I missed this when it first came in 😞

**Comment by fridajac** [comment]
> Thanks @fridajac, sorry I missed this when it first came in 😞

No worries, I totally missed it too . Thanks for being so fast now :smiley:

**Comment by awanlin** [comment]
To fix the build failure in the `/microsite` folder run `yarn install` and then `yarn prettier --write .`, that will fix the file. In this case it looks like there is some empty white space on the description line 👍

**Review by benjdlambert — APPROVED** [review]
Nice :tada: thanks!

**Pull request merged**
