### PR TITLE
Update dependency versions in default frontend plugin templates

### PR DESCRIPTION
**Pull request by tudi2d**
Creating a plugin using the `default-plugin` template created a change to the `yarn.lock` for me. As we stopped accepting new plugins in the main repository we probably missed this. This PR aligns the versions with the currently supported versions in the main repository.

**Unexpected `git diff` on `yarn.lock`**
Screenshot 2023-11-09 at 12 07 42
Screenshot 2023-11-09 at 12 07 48
Screenshot 2023-11-09 at 12 07 34

Screenshot 2023-11-09 at 12 07 22

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by camilaibs — APPROVED** [review]
LGTM 🌟

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
but now you need to update the tests :)

**Review by Rugvip — CHANGES_REQUESTED** [review]
We'll need to wait with this until we migrate all of create-app and plugin templates to React 18.

**Comment by solimant** [comment]
> We'll need to wait with this until we migrate all of create-app and plugin templates to React 18.

@Rugvip - what are the plans to migrate `create-app` and plugin templates to React 18? Is there an open PR for it?

**Review by Rugvip — APPROVED** [review]
Time to :shipit:

**Pull request merged**
