### PR TITLE
Add HCP Consul plugin

### PR DESCRIPTION
**Pull request by abhishek-hashicorp**
Added HCP Consul plugin which can be used as a single dashboard for viewing the current infrastructure state(powered by HCP Consul) 

The plugin uses the [HCP Consul Central Public APIs](https://developer.hashicorp.com/hcp/api-docs/consul) to show the data to the user. Currently we show cluster, service, service instance information. Refer 

Screenshots:

Related [Issue](https://github.com/backstage/backstage/issues/21027)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by abhishek-hashicorp** [comment]
Thanks @freben 
That's a bummer as we were hoping this can be included in this repo but I guess we will be happy to host the plugin ourselves as well. Is it possible for you to share a sample self maintained backstage plugin repo and related doc/steps for reference to publish this plugin? 
If you can share the microsite which has the list of plugins, that'll be helpful as well. 

Happy to contribute to Backstage 🚀

**Comment by freben** [comment]
Here's an example of a plugin being added to the microsite:

https://github.com/backstage/backstage/pull/20643

(note though that that one accidentally was missing a leading slash on `/img`)

Publishing is unfortunately outside of the scope of what we solve as a Backstage repo since that's so dependent on what people prefer. But feel free to take inspiration from our github workflows/actions in this repo, especially the CI and publishing ones. This does imply that you can't publish to the `@backstage` namespace, but that's by design; it being on your own namespaces just makes it more official and nice IMO!

**Comment by tauhid621** [comment]
⬆️ Tried to fix DTO issue. This resulted in the commits being added in the PR.

**Comment by abhishek-hashicorp** [comment]
Closing this request since new plugins cannot be accepted in this repo. We will be hosting the repo ourselves and will raise the microsite addition once that's done.

**Pull request closed without merging**
