### PR TITLE
Make EntityRelationsGraph visible without having to scroll vertically

### PR DESCRIPTION
**Pull request by vorbrodt**
## Hey, I just made a Pull Request!

This PR is related to #13897. 

As suggested in #13897 we should use the same solution as in in #11429 to fill the visible space with the graph. When applied this fix will make sure the EntityRelationsGraph only fills the visible space on the page so that the user does not have to scroll down to see the graph.

Here is how it looks with the new fix: 

https://user-images.githubusercontent.com/64839037/203619496-82c6124b-037a-4744-9eba-b30a4107f872.mp4

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by vorbrodt** [comment]
What do you think? @Rugvip

**Review by Rugvip — CHANGES_REQUESTED** [review]
Makes sense to explore, but I think it's a bit trickier given the different usage modes of this extension. Right now this change seems to break usage in standalone card mode, the card doesn't request space properly and ends up not being tall enough unless there's a neighbouring card that's making space.

**Comment by vorbrodt** [comment]
Could you give me an example of where this occurs? I would like to keep exploring a solution for this.

**Comment by Rugvip** [comment]
@vorbrodt you can see it in the example app on the entity overview page if you narrow down the horizontal screen size so that the cards fill the entire space

**Pull request closed without merging**
