### PR TITLE
keycloak OIDC provider

### PR DESCRIPTION
**Pull request by iammuho**
## Hey, I just made a Pull Request!

KeyCloak OIDC Provider is added as a sign in provider

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thank you for the PR! I want to figure out a couple of high level things first

What are the use-cases for keycloak? is it only for sign-in or do you plan to access resources owned directly by keycloak via OAuth?

The backend implementation is very similar to the OIDC one, does the following work as an option to adding a new provider?

```ts
      keycloak: providers.oidc.create({
        signIn: {
          async resolver({ result: { userinfo } }, ctx) {
            console.log(userinfo);
            return ctx.signInWithCatalogUser({
              entityRef: {
                name: userinfo.preferred_username!,
              },
            });
          },
        },
      }),
```

note that it is `providers.oidc` in the above example

**Comment by freben** [comment]
Closing because of the response above - please reopen or comment if there's more to discuss!

**Comment by sachin-khandelwal** [comment]
When can we expect this PR to be merged?

**Comment by pavshu** [comment]
This functionality would be very helpful to Keycloak users (many of us are stuck with on-prem setup for almost everything) :pray:
Meanwhile, follow up question re: @Rugvip's suggestion. What would the provider entry in App.tsx look like for keycloak with your proposed reuse of oidc for keycloak?

**Pull request closed without merging**
