### PR TITLE
Make AWS session token optional

### PR DESCRIPTION
**Pull request by lorsatti**
## Hey, I just made a Pull Request!

I removed the validation of AWS session token when reading AWS credentials. The session token is not necessary to sign the request. https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jhaals** [comment]
Sounds sane to me if it's not required 👍

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
@mclarke47 any takers or are we good to go with this? :)

**Comment by lorsatti** [comment]
> Can you check whether we need to update the config docs?

https://backstage.io/docs/features/kubernetes/configuration#clusterlocatormethods mentions AWS credentials this way:
> `clusters.\*.authProvider`
> [...]
> | Value | Description |
> |---|---|
> |...|...|
> | aws | This will use AWS credentials to access resources in EKS clusters |

So I think that we are good to go.
More about AWS credentials is explained e.g. at https://backstage.io/docs/features/techdocs/using-cloud-storage#configuring-aws-s3-bucket-with-techdocs. But don't know if it's good to cross reference the two pages.

The normal way is you don't need to provide an access token. It's an indication that your credentials are temporary (e.g. generated by STS). And it's the case when a role is assumed. But this part is already performed in `AwsIamKubernetesAuthTranslator`, so we don't need to specify it IMHO.

**Comment by jhaals** [comment]
Thanks for clarifying 👍

**Pull request merged**
