### PR TITLE
Avoid secondary rate limits during GitHub Discovery

### PR DESCRIPTION
**Pull request by zcurrent**
## Hey, I just made a Pull Request!
Hello! I work with Principal Financial Group and we were working on enabling automatic discovery of components. While enabling this feature, we ran into secondary rate limit issues for organizations with more than 1000 repositories. We pulled in the catalog-module-backend-github plugin as an internal plugin and found that when we added a 1 second delay to each request, it was able to avoid hitting the concurrency limit.

- Updated queryWithPaging to make one request per second to avoid cocurrency issues.
- Created changeset

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Do you know if there happens to actually be rate limiting information in the response body or headers, that can be leveraged to make a more precise backoff and only as needed?

**Comment by adamdmharvey** [comment]
This actually looks like one of GitHub's direct recommendations,

> "If you're making a large number of POST, PATCH, PUT, or DELETE requests for a single user or client ID, wait at least one second between each request."
> https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits

Indeed, for a 1000 repo org, this will essentially mean an ingestion will take at minimum 16 minutes.  Not ideal for sure, but may be correct if not using webhook driven/push ingestion?

The alternative might be to interpret if we've hit the secondary rate limit, and then set a timeout for the response the API gives you (the next suggestion in that section at the same link above). (maybe it ingests 500 super quickly, and then we wait 30 seconds for the rate limit to clear, and then try another 500, or whatever the maths works out to)

**Comment by zcurrent** [comment]
> This actually looks like one of GitHub's direct recommendations,
> 
> > "If you're making a large number of POST, PATCH, PUT, or DELETE requests for a single user or client ID, wait at least one second between each request."
> > https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits
> 
> Indeed, for a 1000 repo org, this will essentially mean an ingestion will take at minimum 16 minutes. Not ideal for sure, but may be correct if not using webhook driven/push ingestion?
> 
> The alternative might be to interpret if we've hit the secondary rate limit, and then set a timeout for the response the API gives you (the next suggestion in that section at the same link above). (maybe it ingests 500 super quickly, and then we wait 30 seconds for the rate limit to clear, and then try another 500, or whatever the maths works out to)

I am unsure where you were able to calculate 16 minutes from. Currently how this queryWithPaging method works is by making a graphQL query to get 100 reposiories and set a cursor. This will then process the 100 repos and call the same query again getting another 100 repositories. (waiting one second in between) So for an organization with 1000 repositories it would take 10 seconds + 10n where n is the time to process the 100 repositories.

**Comment by adamdmharvey** [comment]
Ah didn't appreciate enough about the queries to know you're collecting multiple repos *per page*? Apologies. If so then even better :)

**Review by freben — APPROVED** [review]
OK. We'll merge and try it for a bit; it'll go out with the `-next` release today and we can keep an eye out for whether people experience too much of an affected performance. Also in the long run, something even more intricate might be needed, such as having a globally coordinated rate limiter across all hosts and plugins and features. But that's of course quite some time in the future.

**Comment by zcurrent** [comment]
> OK. We'll merge and try it for a bit; it'll go out with the `-next` release today and we can keep an eye out for whether people experience too much of an affected performance. Also in the long run, something even more intricate might be needed, such as having a globally coordinated rate limiter across all hosts and plugins and features. But that's of course quite some time in the future.

@freben - Thank you for merging this. Here is what I found while researching the response from the queryWithPaging request:

Background:
We deploy our Backstage in AWS utilizing the AWS Fargate service with 2 tasks.

When testing locally, attempting to get some useful logs when failing, I found that we did not run into the secondary rate limit issues.

Upon further investigation, we are running into issues because we have 2 tasks that are essentially duplicating the backend requests.

This one second timeout helped us avoid the secondary rate limit when having both of these tasks performing these requests. However, are we implementing backstage incorrectly? Or is there a better way to store these tasks, say with a host identifier, so that way we can have a scalable backend?

I would appreciate any and all guidance!

**Pull request merged**
