### PR TITLE
chore(test): Reduce lax regexp security warnings

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

When the auth provider router was extracted via https://github.com/backstage/backstage/pull/23023, the test suite introduced mild security warnings about lax regular expressions.

This is just a quick fix to escape the relevant tests, but brings to bear that theoretically the expressions which come in from the config may not be escaped, and thus could theoretically be abused. I wonder if that means we should a) help make clear that the config router should be a regular expression fully escaped (specifically, the warning was about not escaping for example `.com` to be `\.com`), and/or prevent regexes and require a strict string match? likely not the latter, but haven't given it enough thought.

This should close four code-scanning results, including https://github.com/backstage/backstage/security/code-scanning/905 (maintainer link).

No change set since it's a test only change.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
those need to be double backslashes eh?

**Comment by adamdmharvey** [comment]
> those need to be double backslashes eh?

Yeah, the doubles cause the tests to fail (no longer matching).  Playing around with it...

**Comment by freben** [comment]
Gonna reopen this :) for stuff in tests just double backslash 'em and call it a day I'd say

**Review by Rugvip — CHANGES_REQUESTED** [review]
Hmm, I think this is just a false positive tbh. We don't to RegExp matching at all in this code because of how risky it is, and instead rely on minimatch. I guess the scanner sees a `.match(...)` method call and assumes that the argument is treated as a regex. In this case the checking is actually the other way around too.

I think we wanna mark these as false positives and move on tbh 😅

**Pull request closed without merging**
