### PR TITLE
chore: add missing indexes to search table

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

this should speed up fetching the entity facets as the original value and key are used together when fetching the facets.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Adding indices to a table that's this massive and has this much churn, is a risk and has inherent costs in terms of stitching and also on the runtime for applying the migration itself. It'd be nice to see some form of proof that this actually

- speeds up facet requests on large catalogs
- does not have an adverse performance effect on the processing loop
- runs the migration in a reasonable amount of time (maybe less than 20 seconds?) on a catalog with hundreds of thousands of entities (tens of millions of rows in the search table at the start)

Changes to the search table are risky, and has in the past led to incidents where pods failed liveness tests and didn't start up successfully because expensive long-running migrations were being done at startup.

The table also already has three indices - for the `entity_id`, `key`, and `value` columns, each on their own. Does this change mean that one or two of those should also be deleted?

In the `tests/performance` folder there are some beginnings of a harness for setting up large amounts of test data and running work against that. I'd appreciate a somewhat thorough test addition there and also wouldn't mind some findings

**Comment by drodil** [comment]
@freben Yeah makes sense to run some performance tests for this. Taking a look at the queries done against the `search` table:

- delete done by entity_id in `performStitching`
- key-value pair searches done in `DefaultEntitiesCatalog` `entities` and `queryEntities` and `facets`
- key-original_value pair search done in `DefaultEntitiesCatalog` `facets`

Based on this, the current indexes, except for the entity_id, are not optimized from the beginning. Probably the most optimized would be to have 3 indexes:

- entity_id
- key + value
- key + original_value

But as said, this would require some benchmarking. Currently, it's not very optimized, for example in our app where we have tens of thousands of entities, fetching a single facet takes up to 3 seconds.

**Comment by alde** [comment]
I'm hesitant to approve alter tables as that has big impacts on deployments for catalogs with a large (200k+ entities). I wonder if it would be possible to solve this with something like a materialized view?

**Comment by drodil** [comment]
@alde I understand. Maybe a view could be an option or changing the search to a completely new table that is re-populated?

**Comment by drodil** [comment]
Btw, there is an old discussion about Knex supporting creating indexes concurrently here https://github.com/knex/knex/issues/3913 but most likely it will not see daylight as it's almost 4 years old.

**Comment by drodil** [comment]
So applied the index to another instance. Here are the results:

# Catalog search key+value index

Query plan query used:

```sql
SELECT * FROM final_entities LEFT JOIN search ON final_entities.entity_id = search.entity_id WHERE search.key = 'kind' and search.value = 'component' AND final_entities.final_entity IS NOT NULL;
```

## Before indexing

Before adding a new index with both key and value, the results are as follows.

### Query plan

```
                                                 QUERY PLAN
------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=660.48..2073.82 rows=126 width=1306)
   ->  Bitmap Heap Scan on search  (cost=660.06..1139.63 rows=126 width=118)
         Recheck Cond: (((value)::text = 'component'::text) AND ((key)::text = 'kind'::text))
         ->  BitmapAnd  (cost=660.06..660.06 rows=126 width=0)
               ->  Bitmap Index Scan on search_value_idx  (cost=0.00..249.42 rows=8115 width=0)
                     Index Cond: ((value)::text = 'component'::text)
               ->  Bitmap Index Scan on search_key_idx  (cost=0.00..410.33 rows=18921 width=0)
                     Index Cond: ((key)::text = 'kind'::text)
   ->  Index Scan using final_entities_entity_id_idx on final_entities  (cost=0.41..7.41 rows=1 width=1188)
         Index Cond: (entity_id = search.entity_id)
         Filter: (final_entity IS NOT NULL)
(11 rows)
```

### UI Testing

| Request                                            | Total time | Entities loaded |
|----------------------------------------------------|------------|-----------------|
| Initial request with kind filter (component)       | 14.08s     | 7951            |
| Request with single type + kind filter             | 6.38s      | 6448            |
| Request with single other type + kind filter       | 1.07s      | 449             |
| Request with single annotation value + kind filter | 835ms      | 11              | 
| Change kind filter to another kind (system)        | 1.89s      | 1156            |

## After indexing

Creating index with:

```sql
CREATE INDEX CONCURRENTLY search_key_value_idx ON search (key, value);
```

### Query plan

```
                                                QUERY PLAN
------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=6.50..1666.66 rows=150 width=1306)
   ->  Bitmap Heap Scan on search  (cost=6.09..574.15 rows=150 width=118)
         Recheck Cond: (((key)::text = 'kind'::text) AND ((value)::text = 'component'::text))
         ->  Bitmap Index Scan on search_key_value_idx  (cost=0.00..6.05 rows=150 width=0)
               Index Cond: (((key)::text = 'kind'::text) AND ((value)::text = 'component'::text))
   ->  Index Scan using final_entities_entity_id_idx on final_entities  (cost=0.41..7.28 rows=1 width=1188)
         Index Cond: (entity_id = search.entity_id)
         Filter: (final_entity IS NOT NULL)
(8 rows)
```

### UI Testing


| Request                                            | Total time | Entities loaded |
|----------------------------------------------------|------------|-----------------|
| Initial request with kind filter (component)       | 5.39s      | 7951            |
| Request with single type + kind filter             | 2.33s      | 6448            |
| Request with single other type + kind filter       | 283ms      | 449             |
| Request with single annotation value + kind filter | 181ms      | 11              | 
| Change kind filter to another kind (system)        | 1.33s      | 1156            |

**Comment by drodil** [comment]
Refactored this to use `CONCURRENTLY` for creating and dropping indexes. Still need to decide if we can drop the old indexes or not.

**Comment by freben** [comment]
I vote against dropping the initial indices in the same PR. There will be a period of time where there are NO indices, which is probably unacceptable in practice.

**Comment by drodil** [comment]
@Rugvip please go ahead and test it at your instance. At our instance it already makes the catalog somewhat usable again even without pagination 😆

**Comment by drodil** [comment]
Didn't make it to release 😢 Well, next month we try again 😄

**Comment by freben** [comment]
There's always `-next` releases! :) And a thing like this doesn't hurt to have on the next train for a bit to let people react to any effects it might have in their systems

**Review by alde — APPROVED** [review]
LGTM !

**Pull request merged**
