### PR TITLE
chore(microsite): add matomo analytics plugin to microsite

### PR DESCRIPTION
**Pull request by deshmukhmayur**
## Hey, I just made a Pull Request!

Added the Analytics Module: Matomo Plugin to microsite - https://www.npmjs.com/package/@janus-idp/backstage-plugin-analytics-module-matomo

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — COMMENTED** [review]
Thanks for submitting this @deshmukhmayur, this looks good to me just want to be sure wee can use this logo. Seems it should be fine based on this: https://matomo.org/trademark/

@freben, what do you think? We good to use this logo?

**Comment by deshmukhmayur** [comment]
Hey @awanlin @freben, I used the logo from the same [trademark page](https://matomo.org/trademark/#:~:text=Logo%20usage%20guidelines). From their usage guidelines for [Permitted Use](https://matomo.org/trademark/#:~:text=Permitted%20use), it looks like it should be okay to use.

**Review by awanlin — APPROVED** [review]
Thanks again @deshmukhmayur, this is a great plugin! 🚀 

@camilaibs would you be able to take a look at this please?

**Comment by awanlin** [comment]
Shoot, I missed that the DCO check was failing. @deshmukhmayur you need to sign your commits, some links to help with that are here: [DCO section in CONTRIBUTING.md](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) and the build [DCO](https://github.com/backstage/backstage/runs/17780864255) status

**Comment by deshmukhmayur** [comment]
@awanlin My bad, I missed that. Updated the commit with signoff.

**Review by freben — APPROVED** [review]
Nice!

**Pull request merged**
