### PR TITLE
feat(catalog-backend-module-gitlab): Filter Gitlab archived projects through APIs

### PR DESCRIPTION
**Pull request by alexmanno**
## Hey, I just made a Pull Request!

Filter archived gitlab projects via api instead of in for loop

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by alexmanno** [comment]
@benjdlambert As I promised you, here is the PR for filtering gitlab projects through the api

**Comment by benjdlambert** [comment]
@alexmanno nice - this is looking good, just seems to be some unit tests that are failing unfortunately. do you wanna take a look at those?

**Comment by alexmanno** [comment]
Sorry I missed your comment. I'll fix it as soon as possible!

**Review by benjdlambert — APPROVED** [review]
Nice thanks! :tada:

**Pull request merged**
