### PR TITLE
feat(EntityListComponent): use EntityPresentationApi instead of humanizeEntityRef to display entity

### PR DESCRIPTION
**Pull request by Nikunj0601**
## Hey, I just made a Pull Request!

This PR is done to resolve the issue #20955 . I have changed the way to display the entity by using `entityPresentationApi` instead of `humanizeEntityRef`.  I have used `entityPresentationApi` here in React JSX because directly using `<EntityDisplayName />` was making ui changes which i thought should be avoided. 
Below attached screenshot shows current UI
image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Nikunj0601** [comment]
Sorry, guys I made a huge blunder in in signing off commits. I am really sorry and embarrassed about this.

**Comment by freben** [comment]
Ah absolutely no worries!

**Comment by Nikunj0601** [comment]
@freben I had one question regarding this feature is it okay to add devDependency in package.json? I need to add `"@backstage/plugin-catalog": "workspace:^",` for importing `DefaultEntityPresentationApi` in testcase. So is it okay or should i find anyother to add that in test.

**Comment by freben** [comment]
For dev it's typically okay to import other plugins. But here you mean importing from `catalog-node` right?

**Comment by freben** [comment]
Another strategy in a test could be to actually supply a mock presentation api instead of the real one.

**Comment by Nikunj0601** [comment]
No i am importing `@backstage/plugin-catalog` this. I tried mocking the entityPresentationApi but it is using catalogApi. And also I am raising the another PR this same one so it easier for us get the context.

**Comment by Nikunj0601** [comment]
New PR for the same thing with signing off commits issue resolve: #24405

**Pull request closed without merging**
