### PR TITLE
Fixed S3 path join to work under any OS

### LINKED ISSUE #7856: TechDocs fails to serve docs when using S3 (or alternatives) under Windows
## Expected Behavior

TechDocs should be able to server docs from S3 (or alternatives like minIO) when running under Windows versions

## Current Behavior

Currently if you run TechDocs on Windows using S3 (or alternatives like minIO) you will get the following error: `techdocs warn TechDocs S3 router failed to serve static files from bucket backstage-techdocs-storage at key default\component\lockbox\index.html: The specified key does not exist`

After some investigation this seems to be caused by `path.join` under Windows changing the slashes from `/` to `\\`. For example from `default/component/lockbox/index.html` to `default\\component\\lockbox\\index.html`. The line of code for this is here:

https://github.com/backstage/backstage/blob/cd646b55a92b4eefb35e25d94fab4626ed15d1c9/packages/techdocs-common/src/stages/publish/awsS3.ts#L360

## Possible Solution
If we change this to `const filePath = path.posix.join(this.bucketRootPath, filePathNoRoot);` everything starts working again. We just need to add that `posix` part.

There are other options but this seemed to be the simplest. I pulled this from the suggestions in this SO question: https://stackoverflow.com/questions/16301503/can-i-use-requirepath-join-to-safely-concatenate-urls

## Steps to Reproduce

This assumes you have a repo with documentation,  a valid `mkdocs.yml` file, a valid `catalog-info.yaml` file that's registered in Backstage, your CI/CD process has publish the documentation to S3 (or alternatives like minIO) and you have everything properly configured to access and use the S3 (or alternatives like minIO) location.

1. On a computer running Windows start up Backstage `yarn dev`
2. Navigate to your entity
3. Now click on the Docs tab
4. Notice you get the nice not found error message and if you check you logs you will see: `techdocs warn TechDocs S3 router failed to serve static files from bucket backstage-techdocs-storage at key default\component\lockbox\index.html: The specified key does not exist`

**Note:** this will also happen if you navigate to the Docs from the Docs sidebar option

## Context

This is blocking us from being able to upgrade to the latest version of Backstage as TechDocs has become a widely used feature for us

## Your Environment

The key to this issue is running under a Windows OS version

### PR DESCRIPTION
**Pull request by awanlin**
Signed-off-by: Andre Wanlin <awanlin@rapidrtc.com>

## Hey, I just made a Pull Request!

Fixed S3 path join to work under any OS, this should fix #7856 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Xantier — APPROVED** [review]

**Comment by iamEAP** [comment]
Thanks for this, @awanlin! As you may have seen, many folks at Spotify are out this week (myself included), but we'll get to this soon.

Wanted to note: I think this may be a result of a recent change that added a feature to both AWS and GCP publishers. Would you mind taking a look through the GCP publisher and seeing if it is also affected? No worries if you're not able to get to it, though.

**Comment by awanlin** [comment]
@iamEAP no worries and I'm aware you are all way on a well deserved break. I'll look at the GCP side but I have no way to test myself

**Comment by awanlin** [comment]
@iamEAP I've made the same fixes for Google Storage, I can't test these but they look pretty much identical so feel that they should not break things. Still would be nice if someone could test this

**Comment by awanlin** [comment]
@Xantier is this something you can test? Saw that you reviewed my previous change for the AWS S3 side

**Comment by Xantier** [comment]
> @Xantier is this something you can test? Saw that you reviewed my previous change for the AWS S3 side

Unfortunately AWS S3 for us as well here...

**Comment by awanlin** [comment]
> > @Xantier is this something you can test? Saw that you reviewed my previous change for the AWS S3 side
> 
> Unfortunately AWS S3 for us as well here...

Ok, thanks for letting me know 👍

**Review by iamEAP — APPROVED** [review]
Was able to boot up a little Windows VM, repro the bug connected to GCP, and confirm this branch fixes.  Thanks @awanlin!  If you prefix the changeset file with `techdocs-`, we can get this merged in sooner.  Might also be worth noting the fix is for S3 and GCP at the same time.

**Review by freben — APPROVED** [review]
Nice!

**Comment by awanlin** [comment]
@iamEAP changeset has been updated to be prefixed with `techdocs-` and to include that it also fixes GCP. Thanks for testing this, feel better knowing that was done 😄

**Pull request merged**
