### PR TITLE
Move docker into /contrib

### PR DESCRIPTION
**Pull request by stefanalund**
## Hey, I just made a Pull Request!

Does this makes sense? We had two folders called `docker`.

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by freben — APPROVED** [review]

**Comment by benjdlambert** [comment]
I think that these files are referenced somewhere else in the project no?

**Review by Rugvip — CHANGES_REQUESTED** [review]
Yeah these are used by the `Dockerfile` in the repo root. Would be up for trying to restructure that though, especially since we now have other ways to ship the frontend too

**Comment by freben** [comment]
oh derp, i should have caught that

**Comment by nikek** [comment]
I heard during sync that we should move the docker file instead.

**Comment by stefanalund** [comment]
I'll close this then.

**Pull request closed without merging**
