### PR TITLE
support negation of full text search

### PR DESCRIPTION
**Pull request by mbenson**
## Hey, I just made a Pull Request!

Support negation of full text search in `/entities/by-query` of catalog API.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by vinzscam** [comment]
Thank you! 🙏 Could you share more about the use case needed for this feature?

**Comment by mbenson** [comment]
I have a set of entities I import from an external system, and they are tagged with their location in that external system. But if I need to update them to a new instance of said system I need to be able to search for the entities with X characteristic and where a certain label value does _not_ match a LIKE pattern.

**Comment by mbenson** [comment]
@vinzscam your thoughts?

**Comment by freben** [comment]
Hi! We discussed it some time ago and I hoped to get back with a plan but then vacations started.

My take is that the current filters have some historical baggage and drawbacks that makes me hesitant to pull in any further features on top of them. Instead, we may want to start drawing up a bigger picture refactor of what the future of filtering should look like, some time down the line, allowing for improvements like this to be added on top.

We'll give it some more discussion later on and get back.

**Pull request closed without merging**
