### PR TITLE
Clarify location of where to run mock data script

### PR DESCRIPTION
**Pull request by emmaindal**
## Hey, I just made a Pull Request!

AFAIK the `yarn lerna run mock-data` should be ran from the project root.

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by emmaindal** [comment]
Never mind, just realised it could be ran from /packages/backend as well 😄

**Comment by OrkoHunter** [comment]
From https://backstage.io/docs/getting-started/running-backstage-locally
> These commands are run from the project root, not inside the backend directory.

🤔🤔🤔

**Comment by emmaindal** [comment]
ohhh interesting 👀 I gave it a try and I could actually run it from /packages/backend though

**Comment by hooloovooo** [comment]
mock-data can be run from the root or any subpackage that has the script command available. If run from the root it's going to use lerna to run the mock-data command in all packages that has it defined in it's package.json file.

**Comment by emmaindal** [comment]
> mock-data can be run from the root or any subpackage that has the script command available. If run from the root it's going to use lerna to run the mock-data command in all packages that has it defined in it's package.json file.

thanks, so `yarn mock-data` can be ran from a package that has it defined in its package.json but `yarn lerna run mock-data` can be ran in the root but also from a package that doesn't have its own mock-data command defined in the package.json since it's using lerna to run it?

**Comment by hooloovooo** [comment]
> > mock-data can be run from the root or any subpackage that has the script command available. If run from the root it's going to use lerna to run the mock-data command in all packages that has it defined in it's package.json file.
> 
> thanks, so `yarn mock-data` can be ran from a package that has it defined in its package.json but `yarn lerna run mock-data` can be ran in the root but also from a package that doesn't have its own mock-data command defined in the package.json since it's using lerna to run it?

Yes. Seems like running `yarn lerna run mock-data` from a plugin or package would basically just run it from the monorepo package since it's not usually defined in the plugins/packages.

**Comment by hooloovooo** [comment]
Might still be a good idea to suggest running it from the project root in the documentation though since in theory a plugin or package could override the lerna command.

**Pull request closed without merging**
