### PR TITLE
Add Liatrio's DORA Metrics plugin to the directory

### PR DESCRIPTION
**Pull request by MisterC500**
## Hey, I just made a Pull Request!

Hi team! For this PR I added Liatrio's DORA Metrics plugin to the directory. To view screenshots, view documentation, or have any questions on the plugin functionality please visit the [liatrio/backstage-dora-plugin](https://github.com/liatrio/backstage-dora-plugin/tree/main) public repo. If you have any questions, I am more than happy to answer!

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — COMMENTED** [review]
Nice plugin, just some minor questions! Does the plugin/DORA have a logo or is it just the company logo used here?  🤔 Is the logo okay to include from a licensing standpoint?

Cheers!

**Comment by MisterC500** [comment]
@jhaals  Thanks! We are currently looking into creating a logo for this. Hoping to get that today and then we should be good to go 👍

**Comment by MisterC500** [comment]
Morning @jhaals , We decided to go with the Liatrio logo for now.

**Comment by jhaals** [comment]
Okay no problem. Looks like there are some commits that are not DCO signed, please make sure to rebase your PR, there's instructions above.

**Comment by MisterC500** [comment]
Okay all fixed @jhaals  Thank you!

**Review by vinzscam — APPROVED** [review]

**Comment by MisterC500** [comment]
Morning @jhaals ! It looks like there are some jobs that may be stuck? They have been waiting on status for two days I think. `E2E Linux 22.x`, `Test 22.x`, `Verify 22.x`. Anything I need to do on my end?

**Comment by RobertKelly** [comment]
@jhaals @vinzscam - Anything we need to do or is it just an actions runner issue?

**Comment by freben** [comment]
@RobertKelly Could you try rebasing on the very latest master? There may be fixes to those that have happened since.

**Comment by MisterC500** [comment]
@freben Yes, just did that! Looks like those are green now 👍

**Comment by MisterC500** [comment]
Morning @vinzscam @jhaals ! Is there anything else we need to do on our end?

**Pull request merged**
