### PR TITLE
chore: add wsdl plugin

### PR DESCRIPTION
**Pull request by dweber019**
## Hey, I just made a Pull Request!

Add WSDL plugin for API docs

See https://github.com/dweber019/backstage-plugin-api-docs-module-wsdl

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Another solid plugin @dweber019 🚀

**Comment by awanlin** [comment]
@freben can you give this a quick look? I can't merge this without another approval

**Review by freben — APPROVED** [review]
Alright!

**Comment by awanlin** [comment]
Thanks @freben 🚀

**Pull request merged**
