### PR TITLE
Add 'prefix' flag to backstage-cli versions:bump

### PR DESCRIPTION
**Pull request by julioz**
## Hey, I just made a Pull Request!

Fixes https://github.com/backstage/backstage/issues/7513

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

Signed-off-by: Julio Zynger <julio.zynger@soundcloud.com>

### CODE REVIEW

**Comment by freben** [comment]
Hi! See build errors, there's some stuff left to do in tests still.

**Comment by julioz** [comment]
@freben 

> it looks like this is just plain regular code and you needed to pass another argument to the function because you changed it.

Yes, that's what I meant, the extra argument is of type `Command` (from the `commander` lib), but I do not know how to pass that in - I am not experience with jest to mock it, nor it seems possible to pass a real object (`new Command()`), as typescript complains of type mismatch.

Alternatively, I could separate the logic into another function and make that receive only the `prefix` string value as parameter, removing the `cmd` variable from the problem, although I am generally uncomfortable with changing production code for the sake of testing. WDYT?

**Comment by zgriesinger** [comment]
@julioz Are you still working on this? I'd be happy to pick this up if not.

**Comment by julioz** [comment]
@zgriesinger go ahead 👍

**Pull request closed without merging**
