### PR TITLE
fix parens as reported in #24018

### PR DESCRIPTION
**Pull request by richardjq**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thank you, makes sense!  :+1: 

We'll need DCO signed to be able to merge, explained in https://github.com/backstage/backstage/pull/24019#issuecomment-2040386903

**Comment by richardjq** [comment]
> Thank you, makes sense! 👍
> 
> We'll need DCO signed to be able to merge, explained in [#24019 (comment)](https://github.com/backstage/backstage/pull/24019#issuecomment-2040386903)

I think this should be sorted now. Thanks.

**Comment by awanlin** [comment]
Hi @richardjq, I think something unintentional happened as there seems to be more changes in this PR then what you actually changed.

**Comment by richardjq** [comment]
> Hi @richardjq, I think something unintentional happened as there seems to be more changes in this PR then what you actually changed.

I see what you mean. Not sure what's going on here. I'm going to close this out and resubmit.

**Pull request closed without merging**
