### PR TITLE
Backend builds techdocs in the background on a timer

### PR DESCRIPTION
**Pull request by hooloovooo**
This is inspired by how the catalog manages refreshing entities, but for building techdocs. This is a quick example just to try it out and get a discussion going. My main concern about this approach is that is can be a resource hog, especially without good caching.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Note that the period job should only run when `techdocs.builder` is set to `'local'`. Being introduced in https://github.com/backstage/backstage/pull/3432

**Comment by freben** [comment]
@OrkoHunter what to do about this one?

**Comment by OrkoHunter** [comment]
I am not too excited about it as of this moment. @hooloovooo also had reservations when creating the PR. He raises the concern about memory hogging.

I like the idea of updating docs if/when they are being used. With an "async build on visit" https://github.com/backstage/backstage/issues/3717 users will have a better browsing experience, without Backstage trying to build all the documentation sites periodically. Plus, our recommended approach is to build docs on CI.

This doesn't seem very beneficial, compared to the risks being introduced. 🙏

**Comment by freben** [comment]
Cool. Yeah combined with the fact that it's rapidly going stale, let's close it. Feel free to reopen if you think that's top harsh

**Pull request closed without merging**
