### PR TITLE
docs: update local install example for node v14

### PR DESCRIPTION
**Pull request by Kevin-K**
## Hey, I just made a Pull Request!

Updating getting started docs for node version consistency, [docs/getting-started/index.md](https://github.com/backstage/backstage/blob/031ead5f5a81a8004017327434ac44f4b3bc42bd/docs/getting-started/index.md) refers to v14, whereas `running-backstage-locally.md` referred to v12. 

v12 will leave Active LTS on 2020-11-30.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by benjdlambert** [comment]
Thanks for this! The idea was that we would test them both in parallel for a while to make sure they both worked without getting people to switch. I think this should be fine for us to move over to this with our next release on Thursday. Thoughts @backstage/maintainers?

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Maybe you don't have to do it part of this ticket but you can also remove the workflows in `.github` which use `v12`

**Review by Rugvip — APPROVED** [review]
Thanks!

Think we want to keep the v12 workflows for a bit longer tho @benjdlambert, for as long as we're intending to support both

**Comment by benjdlambert** [comment]
Hmm yes - I guess we have to have a chat about deprecation of that support too and how we handle that?

**Comment by benjdlambert** [comment]
@Kevin-K we just had a chat about this, we will merge this PR and then work out a plan to deprecate v12 somewhere around the time it doesn't become the active LTS.

**Comment by Kevin-K** [comment]
@benjdlambert thanks for the heads up!

**Pull request merged**
