### PR TITLE
Cost insights override default alert properties

### PR DESCRIPTION
**Pull request by ryanvazquez**
## Hey, I just made a Pull Request!

When extending default alerts, implementors may want to also override various default properties such as the title or url. These default properties are declared using accessors, which can also be overridden in the subclass using accessors.

Ex:
```ts
class MyCustomProjectGrowthAlert extends ProjectGrowthAlert {

  get url(){
    return 'path/to/my/docs'
  }

  get title(){
    return `Investigate cost growth in ${this.data.products.length) product}`;
  }
}
```

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4623-zl0ply7fokeytuw3pytk8d6kop1kvssj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6032ac01f285af55b9943d43

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4623-zl0ply7fokeytuw3pytk8d6kop1kvssj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6032ac01f285af55b9943d43

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4623-zl0ply7fokeytuw3pytk8d6kop1kvssj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6032ac01f285af55b9943d43

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4623-zl0ply7fokeytuw3pytk8d6kop1kvssj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6032ac01f285af55b9943d43

**Review by brendasukh — APPROVED** [review]
🔥

**Review by freben — APPROVED** [review]

**Pull request merged**
