### PR TITLE
Tweak dark mode colors

### PR DESCRIPTION
**Pull request by timbonicus**
We are implementing a Backstage plugin with dark mode support and noticed that some of the colors are the same as in the light theme.

I updated these following Google's guidelines on tonal [variants for dark themes](https://material.io/design/color/dark-theme.html#ui-application) (and their [color tool](https://material.io/design/color/the-color-system.html#tools-for-picking-colors)).

ProgressCard before/after:

Screen Shot 2020-09-21 at 10 34 30

Screen Shot 2020-09-21 at 10 34 46

Status before/after:

Screen Shot 2020-09-21 at 10 33 29

Screen Shot 2020-09-21 at 10 33 48

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
🎉 , happy with these colors @katz95, @nikek?

**Comment by freben** [comment]
Any before/after shots? :)

**Comment by timbonicus** [comment]
@freben Updated the PR description with some from the Storybook 👍

**Comment by freben** [comment]
on a personal note (am not designer), oof those sure have low contrast in the screen shot (along with pending and warning being super close to each other in color + lightness)

**Comment by ryanvazquez** [comment]
Some adjustments per @freben's feedback

Screen Shot 2020-09-24 at 1 17 49 PM

**Comment by katz95** [comment]
@timbonicus this is great, thank you!!

**Pull request merged**
