### PR TITLE
Add statuspage.io plugin to plugin directory

### PR DESCRIPTION
**Pull request by GLundh**
- [x] Added or updated documentation
- [x] All your commits have a `Signed-off-by` line in the message. ([more info]

### CODE REVIEW

**Comment by GLundh** [comment]
Not sure what I can do here:

```
Run yarn prettier:check
Checking formatting...
[warn] data/plugins/statuspage.yaml
[warn] Code style issues found in the above file. Forgot to run Prettier?
Error: Process completed with exit code 1.
```

I have run prettier on the files, with no changes.

**Review by Rugvip — APPROVED** [review]
Nice! 🎉 👍

**Comment by Rugvip** [comment]
Hmm, looks like there might be a bit of DCO trouble, do you have the signoff on the last commit?

**Comment by GLundh** [comment]
Wops. I had to force-push over the last commit. We should (hopefully) be good to go now.

**Comment by GLundh** [comment]
@Rugvip:  Would you mind giving it another go? :)

**Pull request merged**
