### PR TITLE
Adding Global Agent to techdocs-cli

### LINKED ISSUE #16600: 🚀 Feature: Add Global-Agent support to techdocs-cli
### 🔖 Feature description

Adds the ability to traverse the proxy when using the techdocs-cli

### 🎤 Context

Connecting to public cloud providers from within a proxied network requires the ability to traverse a proxy. By including global-agent in the dependencies, it allows the techdocs-cli to pick up the proxy configuration and successfully access the public cloud resource. 

### ✌️ Possible Implementation

Verified adding global-agent to the dependencies successfully allows connection. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by zjpersc**
## Hey, I just made a Pull Request!

Adding global-agent as a dependency to allow publishing via proxy

Fixes #16600

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by zjpersc** [comment]
@freben I believe I've made all the corrections for the checks. Please let me know if there's more I need to do. Thanks!

**Review by freben — APPROVED** [review]
Let's try it!

**Review by agentbellnorm — CHANGES_REQUESTED** [review]
Cool, thanks for the contribution! Can you also write something about this new ability in [this file](https://github.com/backstage/backstage/blob/master/docs/features/techdocs/cli.md?plain=1) so that we keep the [public documentation](https://backstage.io/docs/features/techdocs/cli/) site up to date?

**Comment by zjpersc** [comment]
@agentbellnorm Good suggestions. I included an update to the feature docs in this last commit.

**Review by agentbellnorm — APPROVED** [review]
Looks good! Thanks. Do you know why the checks are failing? I'm not sure 🤔.

**Comment by zjpersc** [comment]
> Looks good! Thanks. Do you know why the checks are failing? I'm not sure 🤔.

It looks like maybe there were some updated dependencies that were pulled in when I synched my fork and it wasn't finding them when it ran the tests. I'm looking into it.

**Comment by zjpersc** [comment]
@freben @Rugvip Is there a way to trigger the check workflow again? I don't think the failure was actually related to the change I made, but happy to remedy if it was. It looks like it may have been related to an unavailable dependency which may have been pulled in when I synched the fork.

**Comment by zjpersc** [comment]
> @freben @Rugvip Is there a way to trigger the check workflow again? I don't think the failure was actually related to the change I made, but happy to remedy if it was. It looks like it may have been related to an unavailable dependency which may have been pulled in when I synched the fork.

Nevermind - I synched with the v1.12.0 release and all checks are passing now. This should be good to go!

**Review by freben — APPROVED** [review]

**Pull request merged**
