### PR TITLE
fix: verify target plugin as aud instead of source plugin

### PR DESCRIPTION
**Pull request by oskarjiang**
## Hey, I just made a Pull Request!

For verification JWT, verify that the audience matches the one of the target plugin id instead of the current plugin's id.
Solves https://github.com/backstage/backstage/issues/26037

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you, but this should be working as intended. The "own plugin ID" at that point is the receive of the token, i.e. the intended audience

**Comment by oskarjiang** [comment]
> Thank you, but this should be working as intended. The "own plugin ID" at that point is the receive of the token, i.e. the intended audience

@Rugvip Thank you for your comment. This is an attempt to solve the following:
```
{
  name: 'AuthenticationError',
  message: 'Invalid plugin token; caused by JWTClaimValidationFailed: unexpected "aud" claim value',
  cause: {
    code: 'ERR_JWT_CLAIM_VALIDATION_FAILED',
    name: 'JWTClaimValidationFailed',
    claim: 'aud',
    reason: 'check_failed',
    payload: {
      sub: 'techdocs',
      aud: 'catalog',
      iat: 1724058624,
      exp: 1724062219,
      obo: 'ey***'
    },
    message: 'unexpected "aud" claim value',
    stack: 'JWTClaimValidationFailed: unexpected "aud" claim value\n' +
      '    at exports.default (/Users/OJIANG/Repositories/backstage/node_modules/jose/dist/node/cjs/lib/jwt_claims_set.js:57:15)\n' +
      '    at Object.jwtVerify (/Users/OJIANG/Repositories/backstage/node_modules/jose/dist/node/cjs/jwt/verify.js:12:53)\n' +
      '    at PluginTokenHandler.verifyToken (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/PluginTokenHandler.ts:99:25)\n' +
      '    at DefaultAuthService.authenticate (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:58:26)\n' +
      '    at DefaultHttpAuthService.#extractLimitedCredentialsFromRequest (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:101:14)\n' +
      '    at DefaultHttpAuthService.credentials (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:137:9)'
  },
  stack: 'AuthenticationError: Invalid plugin token; caused by JWTClaimValidationFailed: unexpected "aud" claim value\n' +
    '    at <anonymous> (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/PluginTokenHandler.ts:108:13)\n' +
    '    at PluginTokenHandler.verifyToken (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/plugin/PluginTokenHandler.ts:99:25)\n' +
    '    at DefaultAuthService.authenticate (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/auth/DefaultAuthService.ts:58:26)\n' +
    '    at DefaultHttpAuthService.#extractLimitedCredentialsFromRequest (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:101:14)\n' +
    '    at DefaultHttpAuthService.credentials (/Users/OJIANG/Repositories/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/httpAuth/httpAuthServiceFactory.ts:137:9)'
}
```
For more context: https://github.com/backstage/backstage/issues/26037

If you have time, I would love to get some feedback on what else the cause could be. Do you think the token is faulty at the time of issuing rather than the verification being wrong?

**Comment by freben** [comment]
I believe this is replaced by #26088 right?

**Comment by oskarjiang** [comment]
> I believe this is replaced by #26088 right?

Correct. I'll close this

**Comment by oskarjiang** [comment]
Replaced by https://github.com/backstage/backstage/pull/26088

**Pull request closed without merging**
