### PR TITLE
Fixed several typos in the Architecture Overview docs

### PR DESCRIPTION
**Pull request by kurtaking**
Signed-off-by: Kurt King <kurtaking@gmail.com>

#### :heavy_check_mark: Checklist

I found several typos and sentences that could be reworded in the architecture-overview.md doc.

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by kurtaking** [comment]
Are Changesets required for documentation updates? I couldn't find any guidelines around that. Thanks!

**Review by Rugvip — APPROVED** [review]
Thank you!

Nope, no need for a changeset. Guidelines are here: https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#when-to-use-a-changeset

Do need to run prettier on the file though to make sure it's formatted correctly

**Comment by kurtaking** [comment]
> 
> Do need to run prettier on the file though to make sure it's formatted correctly

I ran `yarn prettier:check` locally. Can you help me understand what I need to do to get the **CI / verify** check to pass?

```
$ yarn prettier:check
yarn run v1.22.1
$ prettier --check .
Checking formatting...
All matched files use Prettier code style!
✨  Done in 56.01s.
```

**Comment by freben** [comment]
You sure? When I run that on your branch I get the same error as the CI output.

I took the liberty of running prettier on the file while I was there and pushing it.

**Review by freben — APPROVED** [review]

**Comment by suuus** [comment]
Congrats on your first PR merged @kurtaking! Happy to count you as a contributor.

**Pull request merged**
