### PR TITLE
Update quickstart-app-auth.md

### PR DESCRIPTION
**Pull request by rvandegrift**
Step 6 of [1] did not work for me.  After logging in via the microsoft auth method, I'd get an error: `onResult is not a function`.  I compared to the example repo at [2], and was able to get it working.  Here is what I had to do instead.

I know nothing about typescript or backstage.  So while I have tested this, I have no idea if it's correct. :)

[1] - https://backstage.io/docs/tutorials/quickstart-app-auth
[2] - https://github.com/RoadieHQ/backstage-auth-example/blob/microsoft/packages/app/src/App.tsx

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hi! Contributions need a DCO signature. See the build output for more info. https://github.com/backstage/backstage/pull/5798/checks?check_run_id=2658987735

**Comment by timbonicus** [comment]
Possibly overcome by #5795 if that gets merged. Unfortunate timing, sorry about the collision. 😄  I think the [auth documentation](https://backstage.io/docs/auth/#adding-the-provider-to-the-sign-in-page) that replaces this page resolves the issue?

**Comment by rvandegrift** [comment]
@timbonicus yes, thanks for the pointer - I just tested, and that version works too.  I got the quickstart link from the console output, so I think #5795 is a better solution.

**Comment by Rugvip** [comment]
Shipping #5795 so gonna close this one, that you for checking it out!

**Pull request closed without merging**
