### PR TITLE
Fixing document for CI/CD Statistics Plugin - GitLab Module

### PR DESCRIPTION
**Pull request by NishkarshRaj**
Signed-off-by: Nishkarsh Raj <nishkarshraj000@gmail.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by NishkarshRaj** [comment]
Thank god it's not October yet, else I would've been mocked for this update 🤣

**Comment by NishkarshRaj** [comment]
@benjdlambert don't think this change requires a changeset given I've not made any changes to the plugin codebase.

**Comment by benjdlambert** [comment]
Hmm - the readme does get baked into the release on npm though. Maybe create one just to be safe? :pray:

**Comment by NishkarshRaj** [comment]
Think it is ready now 💯 

@benjdlambert over to you :shipit: 🙏

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
