### PR TITLE
Update dependecies from roadie

### PR DESCRIPTION
**Pull request by Irma12**
## Hey, I just made a Pull Request!

This PR contains updates to the latest version of Roadie plugins which are made to follow upstream package updates.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by OrkoHunter — APPROVED** [review]
Thanks!

**Comment by benjdlambert** [comment]
Hey @Irma12 is it also possible to update the `@backstage/cli` that is being used in these packages too? It looks like that's the cause of quite a lot things being duplicated for different versions in the `yarn.lock`

**Comment by Irma12** [comment]
> Hey @Irma12 is it also possible to update the `@backstage/cli` that is being used in these packages too? It looks like that's the cause of quite a lot things being duplicated for different versions in the `yarn.lock`

@benjdlambert Definitely yes, let me update the PR :)

**Comment by Irma12** [comment]
@benjdlambert Dependencies are updated and I don't see duplicate packages anymore, hope this is better :)

**Comment by benjdlambert** [comment]
Hey @Irma12 -  so I noticed that there were some other deps out of date, which is our fault, so I spent some time updating those too so we don't bring in duplicates.

https://github.com/backstage/backstage/pull/6510
https://github.com/backstage/backstage/pull/6500

I think you can pull from master and do a `yarn install` and the `yarn.lock` i think should only have the duplicated `msw` dependency which is less of a concern - that's next weeks job 😅

**Pull request merged**
