### PR TITLE
Adventures in using postgres with the backend

### PR DESCRIPTION
**Pull request by dtuite**
I've been trying to get the backend to work with PG and I thought I would document how far I have gotten so far and the issues I ran into.

# Steps to repro

Create a local PG DB

```shell
» createdb -O davidtuite -U davidtuite -w backstage_backend
```
Force the code to use postgres (this is the first commit attached).

Run the backend package, get an error because one of the migrations doesn't appear to be valid in PG. The second commit fixes this in a hacky way because I can't figure out how to use knex to add the alias which is required.

```shell
» env PGUSER=davidtuite PGDATABASE=backstage_backend yarn start
yarn run v1.22.1
$ backstage-cli backend:dev
Build succeeded
migration file "20200527114117_location_update_log_latest_view.js" failed
migration failed with error: CREATE VIEW location_update_log_latest AS select * from (select * from "location_update_log" order by "location_update_log"."created_at" desc) group by "location_id"; - subquery in FROM must have an alias
Backend failed to start up, error: CREATE VIEW location_update_log_latest AS select * from (select * from "location_update_log" order by "location_update_log"."created_at" desc) group by "location_id"; - subquery in FROM must have an alias
```

Once that is fixed, I try again and get a different error. The third commit fixes this one.

```shell
» env PGUSER=davidtuite PGDATABASE=backstage_backend yarn start
yarn run v1.22.1
$ backstage-cli backend:dev
Build succeeded
migration file "20200527114117_location_update_log_latest_view.js" failed
migration failed with error: CREATE VIEW location_update_log_latest AS select * from (select * from "location_update_log" order by "location_update_log"."created_at" desc) as myalias group by "location_id"; - column "myalias.id" must appear in the GROUP BY clause or be used in an aggregate function
Backend failed to start up, error: CREATE VIEW location_update_log_latest AS select * from (select * from "location_update_log" order by "location_update_log"."created_at" desc) as myalias group by "location_id"; - column "myalias.id" must appear in the GROUP BY clause or be used in an aggregate function
```

With all that fixed, I have a syntactically correct migration file. Let's recreate the DB to ensure that it's not in some weird state with some migrations ran and others not.

```shell
» dropdb -w backstage_backend
» createdb -O davidtuite -U davidtuite -w backstage_backend
```

Now I get a weird error saying that my migrations directory is corrupt. I don't have a fix for this one yet.

```shell
» env PGUSER=davidtuite PGDATABASE=backstage_backend yarn start                                                                                 146 ↵
yarn run v1.22.1
$ backstage-cli backend:dev
Build succeeded
info: Beginning locations refresh {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-07-05T08:41:58.326Z"}
warn: Failed to initialize Sentry backend, set SENTRY_TOKEN environment variable to start the API. {"type":"plugin","plugin":"sentry","service":"backstage","timestamp":"2020-07-05T08:41:58.357Z"}
info: Visiting 0 locations {"type":"plugin","plugin":"catalog","service":"backstage","timestamp":"2020-07-05T08:41:58.381Z"}
Backend failed to start up, Error: The migration directory is corrupt, the following files are missing: 20200511113813_init.js, 20200520140700_location_update_log_table.js, 20200527114117_location_update_log_latest_view.js
```

Oddly, If I switch into the plugins/catalog-backend directory it works fine and I can successfully query locations.

```shell
» cd ../../plugins/catalog-backend
» env PGUSER=davidtuite PGDATABASE=backstage_backend yarn start                                                                           130 ↵
yarn run v1.22.1
$ backstage-cli backend:dev
Build succeeded
info: Listening on localhost:7000 {"service":"backstage","timestamp":"2020-07-05T08:46:20.542Z"}
```

```shell
» curl http://localhost:7000/catalog/locations
[]
```

# Open questions

 1. How do I add that alias in an idiomatic knex way.
 2. Why are my migrations corrupt when run from `packages/backend` but not from `plugins/catalog-backend`? Something to do with trying to load the migrations from a known path?

# TODO

- [ ] Switch the auth backend to PG in `plugins/auth-backend/src/service/standaloneServer.ts`.

### CODE REVIEW

**Comment by dtuite** [comment]
I've traced the missing migrations exception back to the auth plugin. If I don't add the auth router to the backend then I don't get an exception.

Will do more digging later.

**Comment by freben** [comment]
Hey! Sorry you get to chase this.

https://github.com/spotify/backstage/pull/1527

**Comment by dtuite** [comment]
> Hey! Sorry you get to chase this just as somebody else seems to have fixed the same thing...
> 
> #1527

Oh cool. I missed that. I'll take a look. Thanks for letting me know.

**Comment by dtuite** [comment]
I can confirm that dariddlers patch works great if I mix it into what I was doing. Once I hack the database connections to force usage of postgres I can stop and restart the service without losing my catalog.

Thanks @dariddler!

**Pull request closed without merging**
