### PR TITLE
Expose `verifyNonce` and `readState` publicly

### PR DESCRIPTION
**Pull request by GoWind**
## Hey, I just made a Pull Request!

Expose `readState` and `verifyNonce` publicly from the `auth-backend` package.

As an application implementing a customized  `OAuthAdapter`, I would like to make use of the functions in Backstage, to encode, read and verify the state parameter during the `OAuth` flow. This way, I can ensure that all of the behaviour in my `OAuthAdapter` implementation remains correct with the rest of Backstage.

Apologies for not raising an issue for this. I felt like this was a small enough change that probably didn't need a corresponding ticket.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4896-v8npkjgb5lkqlmzoxs0cplxje1c976ea.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6047b23ff285af3bf1a4a29a

**Review by Rugvip — APPROVED** [review]
Yep, was gonna nit on the naming but given that we already have `encodeState` exported we should probably take care of that in a possible broader change.

Thanks! 👍

**Comment by GoWind** [comment]
@Rugvip  : We should refactor the names all at once, probably to `encodeStateParameter` and `decodeStateParameter`. `state` is a really overloaded term.

**Comment by Rugvip** [comment]
Yep, prolly get OAuth in there too, wanna do it as part of this change? Along with renaming the existing one but perhaps leave a deprecated alias in place for the existing one

**Comment by GoWind** [comment]
> prolly get OAuth in there too, wanna do it as part of this change? 
What changes do you mean ? 

> Along with renaming the existing one but perhaps leave a deprecated alias in place for the existing one
Will create a follow up for this.

**Comment by freben** [comment]
I think he meant to add that extra word. `encodeOauthStateParameter`

**Comment by GoWind** [comment]
Will raise a new PR for this then !

**Pull request merged**
