### PR TITLE
auth-backend: extract the cloudflare access auth provider

### PR DESCRIPTION
**Pull request by freben**
This one never got lifted over to the new backend system.

### CODE REVIEW

**Comment by freben** [comment]
@tylerd-canva @renlord are you guys around to have a look at this? I don't have a CF account myself and any help verifying whether this works well, is appreciated.

**Comment by tylerd-canva** [comment]
I'd be happy to test this but I'm not sure the easiest way to go ahead -- do you know of something simpler than running create-app from this branch and trying to get it set up that way?

**Comment by freben** [comment]
@tylerd-canva That could be one way, or if you have the ability to run this branch locally from the main repo, and configure that local setup to be the final recipient of some cloudflare connections somehow.

**Comment by freben** [comment]
@vinzscam may have some ideas too

**Review by awanlin — CHANGES_REQUESTED** [review]
Hi @freben, any chance you can also update the docs for this auth provider as part of this PR, please? They are right here: https://github.com/backstage/backstage/blob/master/docs/auth/cloudflare/access.md

**Comment by freben** [comment]
@awanlin added!

**Review by awanlin — APPROVED** [review]

**Review by Rugvip — APPROVED** [review]
Nice! 😁 👍 

Let's :shipit:

**Pull request merged**
