### PR TITLE
Fixed typo and made warning a little clearer

### PR DESCRIPTION
**Pull request by markstickley**
## Hey, I just made a Pull Request!

It's a simple typo fix and hopefully making a warning a little clearer at the same time.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by adamdmharvey — APPROVED** [review]
👍🏻 nice improvement

**Comment by adamdmharvey** [comment]
Note you'll need a changeset for this plugin (patch) and to sign your commits.  For more info, see,

https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin
https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets

**Comment by markstickley** [comment]
Apologies, I’ll sort that out on Monday morning :)

**Review by freben — APPROVED** [review]

**Comment by suuus** [comment]
Hey @markstickley, congrats on your first merged PR 🎉 Nice work 👍 Please let me know if we can be helpful in any way.

**Pull request merged**
