### PR TITLE
Add DateTime settings card with 24-hour switch

### PR DESCRIPTION
**Pull request by IlyaSavich**
Signed-off-by: Ilya Savich <isavich@box.com>

## Hey, I just made a Pull Request!

Added 24-Hour switch setting to General settings tab. So for example on home page on header clock time could be customisable.
Split `General` folder by `card`

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — CHANGES_REQUESTED** [review]
Thanks for the suggestion!
It would be great if we could base the time format on the locale instead so that we don't have to introduce too many plugin specific customisation options.

**Comment by IlyaSavich** [comment]
I guess people anyway will want to control it as someone could be used to any format regardless of their location, at least we had such a request

**Comment by IlyaSavich** [comment]
@jhaals unfortunately seems it's not possible to get hour cycle from locale at the moment. The only workable solution is not yet supported by Firefox (only newest browsers support) and even neither by typescript.

So it looks like setting is only way of controlling it

**Comment by Rugvip** [comment]
@IlyaSavich could we defer that decision to the rendering though? I.e. not specify any specific format and leave it to the browser time format to decide?

**Comment by IlyaSavich** [comment]
@Rugvip good point, I guess we can, it will lead to change the setting to have ability reset it to default

**Comment by efenner-cambia** [comment]
I would like to see this implemented!

**Comment by IlyaSavich** [comment]
I get you. I don't think I want to see that configuration btn on hover. So better to leave it as it is

**Pull request closed without merging**
