### PR TITLE
feat(backstage): remove the  type where possible

### PR DESCRIPTION
**Pull request by schultzp2020**
## Hey, I just made a Pull Request!

fixes: https://github.com/backstage/backstage/issues/19705

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hi,

See the comment on the issue, that we may want to accept usage of `ComponentType` since React 18 addresses the `children` issue. This PR also has a number of potentially breaking or unclear changes in it, such as whether the return types should be `JSX.Element` or `ReactElement`, where to allow `null` or not, etc. Happy to hear your thoughts on this though.

**Comment by schultzp2020** [comment]
not stale

**Comment by schultzp2020** [comment]
not stale

**Comment by Rugvip** [comment]
Sorry gonna close this for now to avoid the additional pings. Branch will stick around but let's settle the conversation in #19705 first

**Pull request closed without merging**
