### PR TITLE
fix: init array with another types with one item

### PR DESCRIPTION
**Pull request by Teemukoivumaa**
## Hey, I just made a Pull Request!
#20233 Update documentation so [Array with another types](https://github.com/backstage/backstage/blob/master/docs/features/software-templates/input-examples.md#array-with-another-types) will be visible by default.
Not sure if this needed a changeset :)

kuva

https://github.com/backstage/backstage/assets/35847478/1fa0edad-759d-4570-9bde-8785ef68b7a3

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by dagda1 — APPROVED** [review]
Nice catch!

Thank you

**Comment by freben** [comment]
Hm. This is an odd one. To me, the problem rather seems to be that there's no Add and Remove buttons on the array entry on the right hand side. If you say `minItems: 1` on there, indeed you happen to get that one item to see, but what if you wanted to add another one? What if the template at hand actually wanted it to be possible to have zero items in their array?

**Comment by Teemukoivumaa** [comment]
@freben I was just going with what the original example is trying to show. To me it is just trying to show that you can add multiple inputs to one field. With the options to add, order & remove objects being disabled.

If you want to add more elements to the arrayObject you can set the `ui:options: addable: true`

So my question is, what do you think this example should show the user that just copy pastes this to their own editor?

**Comment by freben** [comment]
Yeah adding those seems pretty sane right? it strikes me as maximizing the direct usefulness and level of learning, for those who copy-paste and don't know about all these settings from the start. Do you agree? Imagine going in as a completely new user, what code example is maximally usable for me?

**Comment by Teemukoivumaa** [comment]
@freben makes sense to me also.
I can update this PR so the example will show that you can add, remove or order the objects & make it start with 0 items

**Comment by Teemukoivumaa** [comment]
@freben updated the example so it starts like this: 
kuva

**Review by freben — APPROVED** [review]

**Pull request merged**
