### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by dabarbi**
## Hey, I just made a Pull Request!

Signed-off-by: Daniel Baumgartner <daniel.baumgartner@rbinternational.com>

#### :heavy_check_mark: Checklist

- [NO ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ YES ] Added or updated documentation
- [NO  ] Tests for new functionality and regression tests for bug fixes
- [NO  ] Screenshots attached (for UI changes)
- [NO ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey :wave: Welcome! :tada:

You'll need to sign off the commit with DCO, you can follow the instructions in the bot's message! 👍

**Comment by freben** [comment]
@dabarbi Hey, gentle ping - can we help out with this?

**Comment by dabarbi** [comment]
Hi,

Yes please. I just wanted to add RBI at the end of the list – but unfortunately didn’t properly comment on it -  guess that’s why it failed. What do I need to do or would you mind, as it is just a table with all users, approve it?

Thanks
Br Daniel

From: Fredrik Adelöw ***@***.***>
Date: Tuesday, 22. March 2022 at 09:41
To: backstage/backstage ***@***.***>
Cc: Daniel BAUMGARTNER ***@***.***>, Mention ***@***.***>
Subject: Re: [backstage/backstage] Update ADOPTERS.md (PR #10228)

@dabarbi<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdabarbi&data=04%7C01%7Cdaniel.baumgartner%40rbinternational.com%7Cd2ad785e21bf46a9f22608da0bdfced5%7C9b511fdaf0b143a5b06e1e720f64520a%7C0%7C0%7C637835353124747297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BIoAyBDbwBx%2FuUMcUYdPkGz0P6NfGhH8p7%2BosuZsBpQ%3D&reserved=0> Hey, gentle ping - can we help out with this?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbackstage%2Fbackstage%2Fpull%2F10228%23issuecomment-1074885147&data=04%7C01%7Cdaniel.baumgartner%40rbinternational.com%7Cd2ad785e21bf46a9f22608da0bdfced5%7C9b511fdaf0b143a5b06e1e720f64520a%7C0%7C0%7C637835353124747297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Pm5wnUERjht43ESsrvhE3higmDKWtkiVzJBr60244Sg%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVACRIRL5XIL2L6WBFOAP4DVBGBUZANCNFSM5Q3NKMTA&data=04%7C01%7Cdaniel.baumgartner%40rbinternational.com%7Cd2ad785e21bf46a9f22608da0bdfced5%7C9b511fdaf0b143a5b06e1e720f64520a%7C0%7C0%7C637835353124747297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1kOz0T0pasKPlGCYE0Cv117WWp63CGOXdadii6TUU%2BM%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

This message and any attachment ("the Message") are confidential. If you have received the Message in error, please notify the sender immediately and delete the Message from your system, any use of the Message is forbidden. Correspondence via e-mail is primarily for information purposes. RBI neither makes nor accepts legally binding statements via e-mail unless explicitly agreed otherwise. Information pursuant to § 14 Austrian Companies Code: Raiffeisen Bank International AG; Registered Office: Am Stadtpark 9, 1030 Vienna, Austria; Company Register Number: FN 122119m at the Commercial Court of Vienna (Handelsgericht Wien).

**Comment by freben** [comment]
Unfortunately we aren't permitted to override the DCO - we've asked.

What you can do is, if you edit the file in the interface, you can enter your sign-off in the commit box at the bottom before pressing the "Propose changes" button. Mind the format to be just like that, with your own name and the email you use on your github account.

Screen Shot 2022-03-24 at 15 25 59

Screen Shot 2022-03-24 at 15 27 19

Or see if it's possible to have it done on a developer machine using git instead, with the right --signoff flag.

**Comment by freben** [comment]
@dabarbi Hey, I checked with legal what the process should be here, and as a stopgap until we get some nicer automation of this in place, I made #10730 on your behalf. Would you mind just commenting on that one that it looks good to you? Closing this one in the mean time, and apologies for the trouble :)

**Pull request closed without merging**
