### PR TITLE
Add support for Cloudflare Access Tokens to `cfaccess` Auth Provider

### PR DESCRIPTION
**Pull request by tylerd-canva**
## Hey, I just made a Pull Request!

Fixes https://github.com/backstage/backstage/issues/20924

I had to add a few more test "fixtures" for the Service Token code path, but I am not really sure a cleaner way to do it without rewriting the entire test file.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by tylerd-canva** [comment]
I am of course open to concrete suggestions on how to improve anything, especially the tests. I may also come back to this later with fresh eyes and re-think it.

**Comment by tylerd-canva** [comment]
Sorry, coming back to this after looking after other things for a week -- can it be re-opened? I'm not sure what I should have done in terms of "action". I thought it was just pending a review.

**Comment by awanlin** [comment]
Hi @tylerd-canva, I think it just fell between the cracks, this was submitted right when everyone was in Chicago for BackstageCon and KubeCon. I've opened it for you 👍 

@Rugvip @camilaibs can you take a look at this please?

**Comment by tylerd-canva** [comment]
No worries at all, clearly I wasn't exactly on the ball about it either 😅

**Comment by awanlin** [comment]
Oh and I might do a rebase given the time since this was submitted

**Comment by tylerd-canva** [comment]
I'll rebase this again -- I know it can be tough to give things attention over the holidays (I myself just came back from a few weeks overseas 😅 )

**Comment by tylerd-canva** [comment]
replaced with https://github.com/backstage/backstage/pull/22211

**Pull request closed without merging**
