### PR TITLE
Update microsite's demos page to link to demo site

### PR DESCRIPTION
**Pull request by fengypants**
Updating the intro paragraph on backstage.io/demos to include a link to demo.backstage.io.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by OrkoHunter** [comment]
@fengypants Ran prettier for you.

```bash
yarn prettier --write pages/en/demos.js
```

It made the following changes (just formatting).

```
diff --git a/microsite/pages/en/demos.js b/microsite/pages/en/demos.js
index 9e53c39af..c26fc9a8e 100644
--- a/microsite/pages/en/demos.js
+++ b/microsite/pages/en/demos.js
@@ -19,17 +19,14 @@ const Background = props => {
           <Block.TextBox>
             <Block.Title>See us in action</Block.Title>
             <Block.Paragraph>
-              To explore the UI and basic features of Backstage firsthand, go to: {' '}
-              <a href="https://demo.backstage.io">
-              demo.backstage.io
-              </a>
-              .
+              To explore the UI and basic features of Backstage firsthand, go
+              to: <a href="https://demo.backstage.io">demo.backstage.io</a>.
             </Block.Paragraph>
             <Block.Paragraph>
-              Watch the videos below to get an introduction to Backstage and
-              to see how we use different plugins to customize {' '}
+              Watch the videos below to get an introduction to Backstage and to
+              see how we use different plugins to customize{' '}
               <a href="https://engineering.atspotify.com/2020/04/21/how-we-use-backstage-at-spotify/">
-              our internal version of Backstage at Spotify
+                our internal version of Backstage at Spotify
               </a>
               .
             </Block.Paragraph>
```

I wish we could run prettier write on GitHub workflows or something so that these issues get fixed automatically (at least for microsite so that people can use GitHub to edit them conveniently).

**Comment by fengypants** [comment]
Interesting. I didn't really understand the line breaks and spacing in the original, so just tried to copy it as closely as possible. I still don't know what the `{' '}` is for. Does it make sense that it left one set of those in, but removed the other?

**Comment by OrkoHunter** [comment]
@fengypants To be honest, we all just obey the linter (prettier) and its decisions on code formatting. :P

I'll try to answer some of that.

The line breaks in the `demo.js` do not exactly correspond to how it will look on the website. In the code, each line should be shorter than 100 characters or something. But on the website, line breaks are determined by CSS width styling and other properties like font size.

Same goes for spacing between words. If you write `first word <insert many spaces here> second word` with extra spacing in between the words in the code file, on the website it will still show up as `first word second word`. Unnecessary whitespaces and line breaks get ignored. The `{' '}` is a deliberate way of telling the code to add those extra spaces when rendering. Much like how `<br>` is a way of telling the code to force a line break.

---

Again, it's just easier to run a formatter/linter/prettier once we are done with changes, so that we don't have to remember the little details about how the code should be formatted.

**Comment by fengypants** [comment]
@OrkoHunter Ah, I appreciate the clarifications/explanations. Yeah, I had kinda figured that the breaks and spacing wouldn't make a difference — I was just trying to make it match for style's sake. But now I see that's what prettier is for! Good to know. Thanks again for the help.

**Review by Rugvip — APPROVED** [review]
👍

**Pull request merged**
