### PR TITLE
Microsite: Create/Manage/Explore blog image updates

### PR DESCRIPTION
**Pull request by AlleyWei**
Create/Manage/Explore Image Updates

Signed-off-by: Alexandra Wei <Alexandrawei@spotify.com>

## Hey, I just made a Pull Request!

Updated images for the blog post.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

Signed-off-by: Alexandra Wei <AlexandraWei@spotify.com>

### CODE REVIEW

**Comment by AlleyWei** [comment]
Sorry about the DCO, Can't seem to figure out where to put the signoff.

**Comment by Rugvip** [comment]
@AlleyWei It's in the correct place, but there's a capital `A` in the email, so the check doesn't accept it 😅

**Review by Rugvip — APPROVED** [review]

**Comment by Rugvip** [comment]
Set it to pass since it's close enough :grin:

Should this be merged?

**Comment by AlleyWei** [comment]
LOL darnit! So close!!!

Please merge.

**Pull request merged**
