### PR TITLE
[Scaffolder] Fix review and create dependencies

### PR DESCRIPTION
**Pull request by tritri251214**
Signed-off-by: Minh Tri <tritri251214@gmail.com>

## Hey, I just made a Pull Request!

https://user-images.githubusercontent.com/32475934/182784151-8d3be56b-c44f-42a3-87fa-696f749b5f83.mp4

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey thanks for this :pray:

Can you explain a little more the approach here with what's happening?

**Comment by benjdlambert** [comment]
I actually think that this is behaviour from the upstream library is sending us data that should be omitted. I think you can pass `liveOmit` to the `<Form />` as a prop and it might just work for your example. Can you try that and adjust the PR to add that prop if it works?

**Comment by tritri251214** [comment]
hi @benjdlambert ,
Am try `liveOmit` in `<Form />` but it didn't work.

I find 2 issues in Review and create:
1. ui:.... didn't work in dependencies.
2. Data field didn't hide in denpendencies. Related issue: [#12948](https://github.com/backstage/backstage/issues/12948)

Example template with issue 1: ui:.... not work
```yaml
parameters:
  - title: Fill in some steps
    properties:
      generation:
        type: string
        title: Generation Method
        enum:
          - Hide name
          - Display name
        default: Hide name
    dependencies:
      generation:
        oneOf:
          - properties:
              generation:
                const: 'Hide name'
          - properties:
              generation:
                const: 'Display name'
              name:
                title: name
                type: string
                ui:backstage:
                  review:
                    mask: '*-----*'
```

So, this pull request fix 2 issues in above.

**Comment by tritri251214** [comment]
@benjdlambert 
My approach:
1. When user click button Next => call to `handleNext`
2. In `handleNext` has `IChangeEvent<{ idSchema }>`
    `idSchema` has state of current form step => Save state of current form step into ReactState, I call is `renderPropertiesSteps`
3. When user go to Review and create => call to `getReviewData`
4. In `getReviewData`, I merged all `renderPropertiesSteps` into array of properties, I call is `renderProperties`
5. Finally, I will set value for review by `renderProperties`

**Comment by benjdlambert** [comment]
Can you also try #13017 to see if the behaviour is resolved in that PR too?

**Comment by tritri251214** [comment]
This issue fixed on [#13017](https://github.com/backstage/backstage/pull/13017)

**Comment by benjdlambert** [comment]
Closing this in favour of #13017 - thanks @tritri251214! :pray:

**Pull request closed without merging**
