### PR TITLE
Add ingestor for private gitlab repositories

### PR DESCRIPTION
**Pull request by forrestwaters**
## Hey, I just made a Pull Request!

This implements functionality similar to https://github.com/spotify/backstage/pull/1560 but for gitlab. 

Gitlab API reference:
https://docs.gitlab.com/ee/api/projects.html#get-single-project
https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [x] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by stefanalund** [comment]
👏🏼

**Review by marcuseide — APPROVED** [review]
Thanks a lot for this! 👍

**Review by Rugvip — APPROVED** [review]
Awesome, thanks! :grin: LGTM

So I'm assuming that an [Integration](https://docs.gitlab.com/ee/user/project/integrations/overview.html) with an implementation in https://gitlab.com/gitlab-org/gitlab/tree/master/app/models/project_services is the long-term plan. Hopefully removing the need for the access token? Either way that should wait until we've gotten further with GitHub apps and webhooks imo :>

**Comment by forrestwaters** [comment]
> Awesome, thanks! 😁 LGTM
> 
> So I'm assuming that an [Integration](https://docs.gitlab.com/ee/user/project/integrations/overview.html) with an implementation in https://gitlab.com/gitlab-org/gitlab/tree/master/app/models/project_services is the long-term plan. Hopefully removing the need for the access token? Either way that should wait until we've gotten further with GitHub apps and webhooks imo :>

Ah that does look interesting. I'd be happy work on that implementation once the path is more clear. Will keep an eye on the GitHub apps and webhooks work. Thanks for getting this merged!

**Pull request merged**
