### PR TITLE
fix(auth): race condition between loginPopup and authFlowHelpers

### PR DESCRIPTION
**Pull request by fidelcoria-aa**
Fixes https://github.com/backstage/backstage/issues/3785

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [n/a] Added or updated documentation
- [n/a] Tests for new functionality and regression tests for bug fixes
- [n/a] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by freben** [comment]
Hi! Sorry but just removing it won't work - this also handles the case where the user plain thinks "nah not gonna do this now" and closes the sign-in challenge window.

**Comment by fidelcoria-aa** [comment]
Greetings, in the case the user closes the window I don't see why the user needs to be told they closed the window...
But if the auth fails (maybe misconfigured app.origin, server down, etc.), I'm with you.
 
I think a proper fix would be to have the popup report to parent window when dom unloads/error/etc. but I'm not sure where that code would go... or if that code is even part of backstage. is it authFlowHelper.ts?
hmm.... just had this idea:
window.onbeforeunload(() => {window.parent.postMessage({'error': 'Window Closed', '//': 'error if auth message not sent and popup.closed'}, origin)})
I'll try it out later today

**Comment by freben** [comment]
Pulling in @Rugvip

**Comment by freben** [comment]
And it's not just about informing the user that it closed. There is an unknown number of consumers (in code) waiting for that auth cycle to complete, and they all need to be notified that they should unblock and give up.

**Review by Rugvip — COMMENTED** [review]
Thank you for taking a stab at this!

We do need to keep the close check, so that we don't end up with hanging authentication requests as freben pointed out. We also can't post in `onbeforeunload`, since that assumes that we actually get to the point of loading the frame handler into the popup. If the user just closes the popup straight away we'll still be on the authentication providers page, which we don't control.

It's possible that a solution is to delay the `window.close()` in the popup window, in case the cause of this is a browser quirk when sending messages just before closing a window.

**Comment by fidelcoria-aa** [comment]
actually this worked... I didn't see the race condition any more. I tried github login several times. closing the window manually still wrongly gives `Login failed, Incorrect app origin, expected` (instead of `you closed the window`) but that's a different problem.

**Review by freben — APPROVED** [review]

**Review by freben — APPROVED** [review]

**Review by Rugvip — APPROVED** [review]

**Pull request merged**
