### PR TITLE
microsite: add documentation versioning

### PR DESCRIPTION
**Pull request by Rugvip**
This adds versioning of our docs at https://backstage.io. It only uses two versions, stable and next. The stable docs are default and the docs from the most recent stable release, while the next docs are the latest version of what's in the main repo.

No automation set up around this for now, let's discuss this approach a bit first. Of course this is going to slow down our docs build considerably, but I figured it's a worthwhile tradeoff in order to reduce confusion around docs versioning. It's the reason I think a stable/next split is the way to go, rather than trying to provide a bigger history.

When arriving at the docs they now look like this:

image

Dropdown looks like this:

image

When selecting next, the docs look like this instead:

image

### CODE REVIEW

**Comment by Rugvip** [comment]
@jhaals I'm thinking next should be master, otherwise we'll need 3 copies of the docs in total. Might be that we want to use different naming for it if we think there's a risk of confusion with the next releases though

**Comment by Rugvip** [comment]
I different approach to the current implementation in this PR that I think might be better is to modify the docs build to populate the stable release instead. That was we avoid all of the extra noise in the main repo, but it does make the docs build even slower 😅 

I'll switch over the implementation to that to see what it looks like.

**Comment by jhaals** [comment]
@Rugvip yeah it make sense for next to be master given that we often make tweaks to current docs along the way. Having just one active build and having mainline being built after version packages is probably better to avoid build times(I guess that's what you mean with your second comment), you might have seen how jest does it https://github.com/jestjs/jest/blob/main/website/archivedVersions.json

**Review by jhaals — APPROVED** [review]
Lets go 👏

**Pull request merged**
