### PR TITLE
plugin-microsoft-calendar added

### PR DESCRIPTION
**Pull request by Abhay-soni-developer**
### 🔖 Summary

the plugin will give a card component where the user can see his daily calendar schedule, and switch between different calendars, if a meeting URL is mentioned, the user can directly click on it to join a meeting and cancelled meetings are stroked.

hovering over any event will pop over a card showing you the list of people invited with a badge over each showing their responses.

https://user-images.githubusercontent.com/23618736/215717491-25db5fa6-b237-487f-8c00-28f572e8da05.mp4

### ✌️ Context

Creating a plugin to achieve the following feature:
1. Select the menu to switch between calendars.
2. card showing the list of events on a selected date and of the selected calendar
3. hovering over the event will pop over a card showing the event summary message, and list of attendees.
4. attendee's chips will have a badge over them symbolizing their responses
    green --> accepted
    red --> declined
    nothing --> not responded yet

### CODE REVIEW

**Comment by Abhay-soni-developer** [comment]
This is the continuation of PR : https://github.com/backstage/backstage/pull/15896

pipeline job are running successfully now
incorporated the feedback by @benjdlambert & @benjdlambert
icons changed

please do the needful.

**Comment by Abhay-soni-developer** [comment]
i had to to run 
git rebase HEAD~5 --signoff 
as i forgot to sign my one commit . after rebasing i had to resolve some conflicts after which this branch started showing more commits in which i was not directly involved

**Comment by Abhay-soni-developer** [comment]
@samiramkr  
@Rugvip 
any updates regarding this branch

**Comment by Abhay-soni-developer** [comment]
I have closed the last PR containing the same work (as asked) and now this is the only PR raised to submit the feature mentioned here https://github.com/backstage/backstage/issues/16001 
@benjdlambert

**Comment by benjdlambert** [comment]
There's still commits in this PR that aren't related to the work that you've done. You will need to rebase this against master to fix this.

**Comment by Abhay-soni-developer** [comment]
@benjdlambert  @samiramkr  @Rugvip i have rebased now only my changes are visible on this branch.

**Comment by Abhay-soni-developer** [comment]
@benjdlambert @samiramkr @Rugvip
i am closing this PR , and here is the new pr with correct commit history
https://github.com/backstage/backstage/pull/16101

**Pull request closed without merging**
