### PR TITLE
scaffolder: Enable `omitExtraData` and `liveOmit` to trim extraneous properties from the model

### PR DESCRIPTION
**Pull request by benjdlambert**
Fixes https://github.com/backstage/backstage/issues/12948

### CODE REVIEW

**Review by vinzscam — APPROVED** [review]
🚀

**Review by acierto — APPROVED** [review]

**Comment by acierto** [comment]
@benjdlambert tests need some care 😄

**Comment by acierto** [comment]
@benjdlambert do you want to share your thoughts on other approach of handling this issue? 
Or mentioning what this fix will break? 😅

**Comment by benjdlambert** [comment]
@acierto I think that removing the `liveOmit` might help, It should now be removed on `validate` I think which might fix that test.

**Comment by benjdlambert** [comment]
These tests still need fixing somehow. Haven't had chance to look at this yet.

**Comment by benjdlambert** [comment]
Superseded by #26363

**Pull request closed without merging**
