### PR TITLE
Catalog: Add `generates` and `generatedBy` relations

### PR DESCRIPTION
**Pull request by benjdlambert**
Making crawling the chain much easier. Little unsure about doing the `generates` relation for Groups and `ldap` things it could be pretty expensive, but open to thoughts.

`generatedBy` would be enough I think anyway.

Work for #6973

### CODE REVIEW

**Comment by Rugvip** [comment]
Inspiration for continued discussion 🚲 🏚️ 😁 

image

I think it's somewhat important that it intuitively related to the catalog model itself rather than the ecosystem model. Couple of other pairs that come to mind:

- `emits` / `emittedBy`
- `spawns` / `spawnedBy`
- `produces` / `producedBy`
- `outputs` / `outputBy`
- `processingOutput` / `processingOutputOf`
- `yields` / `yieldOf`
- `processingYields` / `processingYieldOf`

**Comment by benjdlambert** [comment]
So i originally had `emits` and `emittedBy` but though that was too close to the implementation of the `emit` stuff we do internally. `producedBy` is a little too close to `producesApi` and `consumesApi` maybe? I like `outputs`?

**Comment by benjdlambert** [comment]
Also `bring to pass` :joy:

**Comment by Rugvip** [comment]
I don't think we need to disqualify `emits` because we use the same name internally tbh, but we would need to look at it with fresh eyes and see if it makes sense on its own

**Comment by benjdlambert** [comment]
Thoughts @jhaals @freben?

**Comment by jhaals** [comment]
My first thought was that emit was too internal but I'm not sure anymore.
I like produces / producedBy

**Comment by jhaals** [comment]
parent, giveBirthToo 🤓

**Comment by timbonicus** [comment]
Throwing in a vote for `originatedBy` 😄

**Comment by regicsolutions** [comment]
`entityProduced` and `entityProducedBy` maybe?

**Comment by kiranpatel11** [comment]
wondering if this `generatedBy` relationship can also be used for `components generatedBy templates` .

We are building a tab for Templates to show the compoents generated from this Template. This can help us keep track of the template's adoption/polularity, impact of template change, etc.

**Comment by benjdlambert** [comment]
Closing in favour of #7337

**Comment by benjdlambert** [comment]
@kiranpatel11 I would suggest the best way to do that would be to add an annotation in the `catalog-info.yaml` that is created by the template with some additional metadata in there saying where it came from. Something like:

`mycompany.io/scaffolded-by': 'Template:namespace/name` or something like that.

**Comment by kiranpatel11** [comment]
@benjdlambert, wouldn't it creates different inconsistent patterns ?

I thought we use annotations mostly for external integration via plugin for cataloged entity, and use relationships for entities managed in the catalog.

**Pull request closed without merging**
