### PR TITLE
Add export for LinksGridList, EntityLinksEmptyState components, and ColumnBreakpoints type

### PR DESCRIPTION
**Pull request by radoslaw-wielonski-nc**
## Hey, I just made a Pull Request!

I've added export for LinksGridList, EntityLinksEmptyState components, and ColumnBreakpoints type so it's easier to customize the EntityLinksCard component.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by andrewthauer — COMMENTED** [review]
Imo, the `LinksGridList` might be a good candidate to move to `core-components` rather then exporting directly from this `catalog` package. That way the `EntityLinksCard` uses the more general `LinksGridLista` component that is potentially useful on it's own.

**Review by Rugvip — COMMENTED** [review]
Thank you, but to be honest we'd rather maintain the flexibility to change these components without considering the API surface for now. I'd recommend simply copying the components into your own project instead for now, does that seem alright?

**Comment by andrewthauer** [comment]
> Thank you, but to be honest we'd rather maintain the flexibility to change these components without considering the API surface for now. I'd recommend simply copying the components into your own project instead for now, does that seem alright?

Funny you should say that. I recently created an internal `packages/components` package modelled off `@backstage/core-components` and ported over the `LinksGridList` component for other usage outside the `EntityLinksCard`. I was considering proposing upstreaming it myself which is why I commented here. This approach works for me at least.

**Comment by Rugvip** [comment]
Alright, will close this. Please let us know if you want us to reconsider!

**Comment by radoslaw-wielonski-nc** [comment]
Hi, I didn't have too much time in the last 2 days, but I thought that maybe we could implement it the way @andrewthauer said, what do you think? 

Right now if I want to customize just one thing in EntityLinksCard besides copy-pasting EntityLinksCard I need to create 5 or 6 additional files, correct me if I'm wrong.

**Comment by andrewthauer** [comment]
That sounds correct. You could at least combine the `LinksGridList` related code into a single file and then have a custom `EntityLinksCard` to reduce the number of files. That actually what I did.

Out of curiosity, can you share the customization you are looking at doing?

**Comment by radoslaw-wielonski-nc** [comment]
I just wanted to replace `<EntityLinksEmptyState />` with a different component. To solve this we could also add another parameter in `EntityLinksCard`, but it would be more messy than exporting a few backstage components.

**Comment by andrewthauer** [comment]
Another approach (although not the nicest) is to create an wrapper component around the entire `EntityLinksCard` and display your custom empty state or the actual card.

**Pull request closed without merging**
