### PR TITLE
Add CircleCI to the Well Known Annotations

### PR DESCRIPTION
**Pull request by dtuite**

### CODE REVIEW

**Review by freben — APPROVED** [review]
Ah, splendid.

**Comment by dtuite** [comment]
@stefanalund @freben What about TravisCI? Should I add that?

It is a well known annotation, in the sense that it will do something if you add it. However, I would probably need to explain that the plugin must be installed before it will do anything.

**Comment by dtuite** [comment]
Prettier failed. I just shipped this commit using the GitHub UI and I don't have the fork it came from cloned locally.  I'll fix it later.

**Comment by freben** [comment]
Frankly we haven't settled yet on what the per-plugin doc structure should be long term. This file is kind of a quick summary to get people started with a lot of different things in parallel. You may be right that this should perhaps only extend to in-repo plugins at this point. But I would like for there to be an entire section in the docs for each plugin eventually - how to install, how to configure, what the (frontend and/or backend) API is where applicable - what the relevant annotations are - etc.

**Comment by benjdlambert** [comment]
Think you also need to run prettier on the ammended file :)

**Comment by Rugvip** [comment]
@dtuite, `yarn prettier --write docs/features/software-catalog/well-known-annotations.md` m8!

**Comment by dtuite** [comment]
Alright alright alright. There you go.

**Review by freben — APPROVED** [review]

**Pull request merged**
