### PR TITLE
Feature/bitbucket default catalog value

### PR DESCRIPTION
**Pull request by ONordander**
## Hey, I just made a Pull Request!
This PR adds a default value of "catalog-info.yaml" to BitbucketDiscoveryProcessor that's used when no catalog path is given.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @goober, can you chime in here? I'm not 100% what this is doing and i'm don't have the most context here.

**Comment by goober** [comment]
Sure thing @benjdlambert, just want to clarify that @ONordander is a colleague of mine.

Some context for other reviewers. [The documentation](https://backstage.io/docs/integrations/bitbucket/discovery) states that you should define a pattern for matching repositories while crawling the Bitbucket instance. e.g. by defining the path https://bitbucket.mycompany.com/projects/<regex>/repos/<regex>/<filepath>

However, if you leave out the filepath part, it will be empty when the parser is called. By defaulting to `catalog-info.yaml` in the case when the filepath is left out we are a little bit more forgiving on how the adopter configure the discovery-reader

**Review by goober — APPROVED** [review]

**Comment by benjdlambert** [comment]
OK sweet - make sense to me!

**Comment by benjdlambert** [comment]
@goober @ONordander just to clarify though this change isn't breaking right? It should be `patch` in this case whilst we are `<1.0.0`

**Comment by ONordander** [comment]
> @goober @ONordander just to clarify though this change isn't breaking right? It should be `patch` in this case whilst we are `<1.0.0`

Correct me if I'm wrong but I think it is breaking, since we are changing default functionality.
If a user has has written a custom parser that overrides https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/bitbucket/BitbucketRepositoryParser.ts
the input to the parser will change.
_If_ they have built logic around getting empty catalogPaths as input it could affect them (the 'target' input here https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/bitbucket/BitbucketRepositoryParser.ts).

**Comment by benjdlambert** [comment]
@ONordander in that case - do we need to add more to the changeset suggesting how to migrate to the later version if that's possible?

**Comment by ONordander** [comment]
> @ONordander in that case - do we need to add more to the changeset suggesting how to migrate to the later version if that's possible?

That sounds like a good idea, I'll get on it!

**Comment by benjdlambert** [comment]
Perfect - I wonder if it also (not in this PR, perhaps a follow up PR) it would be good to move some of the bitbucket parts into their own `module` instead similar to the `LDAP` module. Means it can be versioned seperately from the `catalog-backend` plugin :)

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
