### PR TITLE
CreateApp: Allow specification of name and dbtype from command line

### PR DESCRIPTION
**Pull request by GLundh**
Allowing automation of new sites.

Signed-off-by: Gustaf Lundh <gustaflh@axis.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
While this might be a valid thing to support (we'll review later) as such, I just want to reiterate that it's _not_ an intended workflow to automate calling this script. We expect that in general, an org would call this roughly once for the entire lifetime of the company.

**Comment by GLundh** [comment]
> While this might be a valid thing to support (we'll review later) as such, I just want to reiterate that it's _not_ an intended workflow to automate calling this script. We expect that in general, an org would call this roughly once for the entire lifetime of the company.

I hear you. The main issue for us is to find a way to work that fulfils the following needs:

1. Be able to easily spawn new (close-to-production) sites for verifying / staging.
2. Allow us to track and apply changes made in the backstage repo to our local sites/portals. 

Since we are modifying a bunch of pages (typically App.tsx, Root.tsx, EntityPage.tsx etc), creating a site once, and only once, makes it is very hard to track and apply new Backstage changes to our backstage instances. And (as you know :)) the Backstage code is moving *very* quickly.

While their are some tools to help update packages and find diffs, it is *really* cumbersome to apply changes without being able to cherry-pick / rebase our changes on-top of the source-code tree.

Our plan (please note that we are still experimenting a lot in regards to how we want to work), was to update the create-app templates/ files in our fork of the backstage repo. And when it is time to roll out a new staging-site (or update the production instance), we can just run create-app and get a perfectly setup & clean site. Then we can Helm to modify some values and deploy into Kubernetes.

By modifying the create-app templates, we are allowed some very easy rebasing of our changes to new releases of backstage.

We are still trying to find our way so if there is a way to work, with less friction, when when it comes to spawning new sites and rebasing changes, I would love to hear it. 

I have been in contact with another company in the region that is investigating Backstage, and they were struggling  in the exactly same way we did, when it came to updating and maintaining a "run create-app once" site.

**Review by freben — COMMENTED** [review]
Hey again! You'll see that the end-to-end tests that interact with the installation process of this are affected. So some things left to make green!

**Comment by GLundh** [comment]
Thanks. I'll fix. Any more thoughts about our intended workflow (of using create-app + templates to allow easier rebasing + cherry picking of internal changes)? We are working hard on how we want to set-up our dev workflow for backstage, and if you can hinder us from making a huge mistake, that would be appreciated :)

**Comment by benjdlambert** [comment]
Maybe you've already seen this, but https://backstage.github.io/upgrade-helper/ displays the differences between the create-app versions outputs. Not sure if this helps you, but all the diffs are also generated automatically after every release. It's what powers that UI.

**Comment by GLundh** [comment]
Thanks for the comments! We are re-evaluating our ways of working with Backstage. Not sure this will be needed. Closing until (it is actually needed)

**Pull request closed without merging**
