### PR TITLE
Update EntityTagFilter to use 'some' instead of 'every'

### PR DESCRIPTION
**Pull request by ltdonner**
Signed-off-by: Donner, Lauren [USA] <Donner_Lauren@bah.com>

## Hey, I just made a Pull Request!

This PR changes the behavior of the EntityTagFilter to include all components that match any of the tags chosen.

Because tags can be used to classify catalog entries in various ways, when filtering on multiple tags it stands to reason we would want to find any component that contains any one of those tags, to cast a wide net to discover what we’re looking for. 

If, for example, a user is searching for a component related to artificial intelligence, I would expect the user to be able to find my component by checking both “ai” and “artificial-intelligence” in the tag filters even if my component only has the “ai” tag or only has the “artificial-intelligence” tag, but not both. 

Or, if a user selects 4 tags and a component has 3/4 of those tags, I would think that component would still be relevant to what they’re searching for.
 This would also be more consistent with how filters work when using them in /entities, which uses an “or” relationship for filters.
 If a user is searching for something using tags, I think it makes more sense for it to match any of the tags selected, not just components with every single tag in the list.

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — COMMENTED** [review]
Thanks for the PR!

It's debatable if the tag filter should match `every` or `some`. I _think_ I'm in the `some` camp when it comes to tags but I feel we need to at least discuss it in a larger group in case there are other views or opinions. We have a [catalog SIG](https://github.com/backstage/community/blob/main/sigs/sig-catalog/README.md) on Tuesday next week, I've added this PR as a topic so that we can discuss it there or in this PR beforehand if others from the community have opinions.

**Comment by ltdonner** [comment]
Thank you for taking a look and for adding it to the docket! :)

**Review by jhaals — CHANGES_REQUESTED** [review]
Thanks for waiting! We discussed this in the catalog SIG yesterday and concluded that it might be problematic to change the default for users. This change is potentially a welcome change for a smaller catalog but makes filtering in very hard in larger installations with thousands of Entities, in those cases you might actually prefer it to be exclusive.

One suggestion was to potentially add an optional prop to the filter making it be "OR"(`some`) instead. If you want to go the extra mile it would be pretty cool to have a new filter with a toggle depending on if you want OR/AND.

**Comment by ltdonner** [comment]
Thank you for bringing it up for discussion! Yeah something like that was our plan "b" - I'm gonna be pretty swamped for the next sprint or so but I think the plan is to go for something like this if changing the default isn't an option.

image

Might be a little time before I can get to that, though - should I just close this PR and open another one later or can I leave this one alone for now and come back to it later?

**Comment by jhaals** [comment]
@ltdonner your plan B sounds good and the mockup is in line with what I'm thinking as well 👍
Our stalebot is likely going to poke and close this PR if we leave it open so I'll close it for now but feel free to reopen or just open a new PR referring to this one when you've got some capacity to work on this. Thanks!

**Pull request closed without merging**
