### PR TITLE
Fix host for AWS Code Commit integration and add region

### PR DESCRIPTION
**Pull request by stijnbrouwers**
## Hey, I just made a Pull Request!
This PR fixes the AWS CodeCommit integration by allow to change the host and adding a region to the config.
Fixes issues:
#24824 
#24763 

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Kang3498** [comment]
I hope this PR gets merged quickly. 
It's now impossible to use AWS Code Commit in Backstage without this..

**Comment by benjdlambert** [comment]
@niallthomson sorry to pull you in here, but do you think that this makes sense? My AWS CodeCommit knowledge is pretty limited and wanted a second pair of eyes. 👍

**Comment by stijnbrouwers** [comment]
@niallthomson , no worries!

Yes, I require region to be set.
Instead of parsing the region from the host, I construct the host from the region.

The reasoning behind this, was that it is easier to remember the region (eu-west-1) than the host (eu-west-1.console.aws.amazon.com). However, it is still possible to manually overwrite the host, should this every be required.

**Comment by niallthomson** [comment]
And am I right in thinking that `ScmIntegration` uses the host to map to a specific integration so you couldn't have one integration entry cater for every region in a single AWS account?

**Comment by stijnbrouwers** [comment]
That's correct.
For example:
A repository created in region "eu-west-1" (host= eu-west-1.console.aws.amazon.com) is not accessible from a url for region "us-east-1" (host= us-east-1.console.aws.amazon.com).

**Comment by niallthomson** [comment]
Ok I think I follow with that context. It makes this configuration a bit more complex than would be ideally but seems necessary.

I'd say the `locations.md` page is lacking a basic example of a location. After reading that documentation I don't actually know what URL I'm supposed to use, and I think with the addition of the region config value it would perhaps be a good idea to reinforce you also need the region in the URL, and probably also where you source that URL from in the AWS console.

**Comment by stijnbrouwers** [comment]
OK, thank you for your input!
I have updated the locations.md with some extra information as requested.

**Comment by Kang3498** [comment]
After seeing this thread, I need to re-open the PR I made in the sense of a Hotfix. ([PR#24771](https://github.com/backstage/backstage/pull/24771)) Currently, projects created through AWS Code Commit do not work at all.

**Comment by stijnbrouwers** [comment]
@niallthomson After making changes to the documentation, the "CI / Test 20.x (pull_request)" task is failing.
I think it's a global issue since I see it in other tickets as well.
Does this stand in the way of merging?

**Comment by niallthomson** [comment]
I can't speak to that. @benjdlambert ?

**Pull request merged**
