### PR TITLE
Enable 'email' field population when using github app for Org Data

### PR DESCRIPTION
**Pull request by cgiraldo**
We want to be able to access 'email' field at Users ingested from github organization using a github app (not only github token).

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — COMMENTED** [review]
Hi @cgiraldo, thanks for this, I do think this may not be that simple, I feel like this has come up in the past. This was added as part of this PR: https://github.com/backstage/backstage/pull/13640.

Note: you also need to add a changeset, details on that are here: https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets

**Comment by awanlin** [comment]
Hi @ScottGuymer, as you were the one who added this code could you give us some feedback on this change? My memory wants to say there's more to it than just this 🤔

**Comment by ScottGuymer** [comment]
Yeah we do load in emails from the org.

But they are not in the standard email field, that is only for public emails.

You need to use the org verified email property, and that is only if the user has chosen to setup an email on their account with a domain that is validated on your org.

Your app also needs the permissions to real all member data.

I would have to check but we also use the user transformer for enriching the user further and it works fine.

**Comment by cgiraldo** [comment]
Thanks for your prompt response.

I have tried using the organizationverifiedmails field but It is always empty for my org users. My organization domain is verified and I have configured and verified emails within that domain in my organization users. I supposed is empty because we  have the github "team" plan, no the "enterpise" plan.

I suppose we have to go to a token based integration in our case.

**Comment by awanlin** [comment]
@cgiraldo sorry, guess that's what I'm trying to figure out, does using an app with this change work or are there other things that need to be done? Like have you tested this change against your GitHub Org(s)?

@ScottGuymer, thanks for the reply, are you using a GitHub App? I'm assuming no given what you said but just want to confirm.

**Comment by ScottGuymer** [comment]
Yes we are using a GitHub app.

It needs to have member read permissions on the org you are trying to read from

**Comment by cgiraldo** [comment]
Hi, just to provide some light in my current environment:

- Backstage version: 1.30.0
- Github Integration through a Github App in my organization (gradiant).
- 'gradiant.org' domain verified in Gradiant Org.
- I am member of the organization with a verified email in the domain (cgiraldo@gradiant.org).

Using gh api graphql with an [installation access token](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app):

```
 gh api graphql --paginate -f query='query {
  organization(login: "gradiant") {
    membersWithRole (first: 100){
      edges {
          node {
            login
            organizationVerifiedDomainEmails(login: "gradiant")
          }
        }
    }
  }
}' | jq | grep -C2 'cgiraldo'
          {
            "node": {
              "login": "cgiraldo",
              "organizationVerifiedDomainEmails": []
            }
```

Also all other users in the respose has an empty "organizationVerifiedDomainEmails".

I suspect that the `organizationVerifiedDomainEmails` is for organizations in the "Enterprise Plan". We are in the "Team Plan".

So If that is the case, Do I have to move to a token based github integration? 
I would like to be able to use github app integration but to have the public 'email' of users to use in my `UserTransformer`

**Comment by planeiii-te** [comment]
@awanlin Why'd this get closed?

**Comment by awanlin** [comment]
Hi @planeiii-te, it went stale, seems pretty clear from the message history from the bots.

**Comment by cgiraldo** [comment]
However, our use case make sense?

Some of us does not have a github "enterprise plan" but a "team plan" and relay on the public email published by our organization members.

If It is the case, should I reopen a new pull request?

We are currently patching our backstage instance to have this feature enable.

**Pull request closed without merging**
