### PR TITLE
Fix controlled Select keyboard open/close behavior

### PR DESCRIPTION
**Pull request by luchillo17**
## Hey, I just made a Pull Request!

[Keyboard Navigation - Home - Side Panel] the "Type" and "Kind" select components were not getting activated through keyboard.

This should fix tab navigation enter/space interactions with said selects, this affected all selects based on @backstage/core-components Select component.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by luchillo17** [comment]
Seems @octokit stuff still broken eh?

**Comment by benjdlambert** [comment]
@luchillo17 I merged #17545 for now to work around the octokit failures.

**Comment by luchillo17** [comment]
All checks are passing, can I get a review?

**Comment by luchillo17** [comment]
Ping @Rugvip

**Review by Rugvip — APPROVED** [review]
Awesome, thank you! 👍 🎉 

There's still an extra tab entry for each dropdown, is that intended? It's the form control, which has the aria label with the current value. Next element is the button used to open the dropdown.

That's there before and after this change, so shipping this either way 😁

**Pull request merged**
