### PR TITLE
fix(docs): Improve Splunk image background color

### LINKED ISSUE #4550: Splunk On-Call plugin: Marketplace icon
It seams that the Splunk On-Call plugin icon is too dark to display it correctly in the Marketplace.

## Expected Behavior

The Splunk On-Call icon must be correctly displayed and visible to the user.

## Current Behavior

Capture d’écran 2021-02-16 à 16 33 02

## Possible Solution

We should provide a lighter version of the icon.

In `microsite/data/plugins/splunk-on-call.yaml`:

```yaml
---
title: Splunk On-Call
author: Spotify
authorUrl: https://github.com/spotify
category: Monitoring
description: Splunk On-Call offers a simple way to identify incidents and escalation policies.
documentation: https://github.com/backstage/backstage/tree/master/plugins/splunk-on-call
iconUrl: # Provide another icon
npmPackageName: '@backstage/plugin-splunk-on-call'
```

## Steps to Reproduce

Go to https://backstage.io/plugins and scroll down to the Splunk On-Call plugin.

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

Fixes #4550 via https://www.splunk.com/en_us/newsroom/media-kit.html.

image

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4667-vrc0zsvw5g18kggzr1nhek1pmpeov1md.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60356b03f285af457c964bff

**Comment by adamdmharvey** [comment]
Note @ayshiff it's not an On-Call specific logo, but the Splunk corporate one. Open to your feelings on it.

**Review by freben — APPROVED** [review]

**Comment by ayshiff** [comment]
@adamdmharvey I think we can use this logo.

The transition from VictorOps to Splunk On-Call is still a bit unclear (the portal url is `portal.victorops.com`, the logo used remains the one of VictorOps...)

I don't know if they plan to change the logo in the future but I think the easiest way is to use the Splunk corporate logo as you did.

**Comment by adamdmharvey** [comment]
:shipit:

**Pull request merged**
