### PR TITLE
Feat: bump GitHub Insights Plugin version

### PR DESCRIPTION
**Pull request by lewtakm**
## GitHub Insights Plugin
Hello,
this PR bump plugin version to the latest one. Plugin is of course backward compatible.
 
Changes:
- replace ReactMarkdown component to the one from Backstage core adopting those changes https://github.com/backstage/backstage/pull/3157
- resolve issues with fetching contributors avatars for GitHub Enterprise setup

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
:shipit:

**Comment by dtuite** [comment]
The build failures for this PR will be fixed by: https://github.com/backstage/backstage/pull/3328

**Comment by freben** [comment]
OK, the other one is merged.

**Review by freben — APPROVED** [review]

**Comment by benjdlambert** [comment]
:( conflcts in `yarn.lock` 🐈

**Comment by lewtakm** [comment]
@benjdlambert conflicts resolved, hopefully test will pass now 👍

**Pull request merged**
