### PR TITLE
fix: change kind:resource icon

### PR DESCRIPTION
**Pull request by dweber019**
## Hey, I just made a Pull Request!

Changing the kind:resource default icon to the storage icon.
Screen Shot 2023-12-16 at 23 26 17 PM
Screen Shot 2023-12-16 at 23 27 08 PM

Input from https://github.com/backstage/backstage/pull/21443

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by dweber019** [comment]
The work icon is still the default icon if no icon can be found under the system provided icon.
See https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/InspectEntityDialog/components/EntityKindIcon.tsx#L22 but there are other implementations.

Would it make sense to replace this icon. I'm thinking about the BugReport icon, as not finding a icon is a bug 😉 
Screen Shot 2023-12-16 at 23 30 12 PM

**Comment by dweber019** [comment]
@benjdlambert @freben

**Comment by dweber019** [comment]
So removing the icon would look like this
Screen Shot 2023-12-18 at 19 28 08 PM
Screen Shot 2023-12-18 at 19 28 18 PM

I'm actual think the help icon would be the best option, what do you think?
Additional, if we remove the icon, should we keep the spacing, like on the screenshots?

**Comment by alde** [comment]
I really like this, but I agree with @benjdlambert

**Comment by dweber019** [comment]
Created a separate change for the default icons as there was more to change as initially thought.
Changes are now here https://github.com/backstage/backstage/pull/21967

**Comment by dweber019** [comment]
I think this PR can be merged as it only changes the default icon for resource entities 😉

**Comment by dweber019** [comment]
Unstale

**Comment by awanlin** [comment]
@dweber019, just a quick tip that I find helps with the stale bot: rebase. Also, in your case it will also get the build green 🚀

**Pull request merged**
