### PR TITLE
fix api base url usage in gitlab integration

### PR DESCRIPTION
**Pull request by jeffersongirao**
Signed-off-by: Jefferson Girao <jefferson@girao.net>

## Hey, I just made a Pull Request!

* whenever `apiBaseUrl` is specified then ensure it is used for all API calls.

* make `baseUrl` and `apiBaseUrl` optional in the configuration where a default for `apiBaseUrl` is derived from `baseUrl` and a `baseUrl` can be derived from `host`.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jeffersongirao** [comment]
Hello there @Rugvip 🙌 . Just noticed E2E check has failed here, wondering if it is some flakiness or related to my changes somehow. Any tips on how to figure that out? 🙇‍♂️

**Comment by awanlin** [comment]
FYI @jeffersongirao the E2E failures are related to this: https://github.com/remix-run/react-router/issues/10566

**Comment by jeffersongirao** [comment]
Hello there! Is there anything I could act upon in order to get this reviewed/merged? Thanks in advance! cc/ @freben @Rugvip

**Review by Rugvip — COMMENTED** [review]
Hello there! :grin: Sorry we're both out on vacation :sweat_smile: 

I'll post the one comment I found before but it might not be a complete review

**Pull request closed without merging**
