### PR TITLE
[Plugin] Cloud Carbon Footprint

### PR DESCRIPTION
**Pull request by austin-garrard**
# Cloud Carbon Footprint Plugin

## ThoughtWork's Cloud Carbon Emissions Measurement and Analysis Tool

Understand how your cloud usage impacts our environment and what you can do about it. This plugin brings the functionallity of the open source project [Cloud Carbon Footprint](https://www.cloudcarbonfootprint.org/) into Backstage.

|Estimates | Forecast |
|---|---|
| Screenshot 2022-04-01 at 17 07 07 | Screenshot 2022-04-01 at 17 07 24 |

| Recommendations | Carbon Intensity Map |
|---|---|
| Screenshot 2022-04-01 at 17 07 35 | Screenshot 2022-04-01 at 17 07 45 |

### [Checkout the Cloud Carbon Footprint Demo to get a gasp of the possible capabilities of this plugin](https://demo.cloudcarbonfootprint.org/)
[_From the project documentation:_](https://www.cloudcarbonfootprint.org/docs/overview)

### [Vision](https://www.cloudcarbonfootprint.org/docs/overview#vision)
The vision for this product is to be a trusted tool for its accuracy and comprehensiveness, and aids organizations to take tangible steps towards reducing their cloud emissions. In its future, we see built-in intelligence to make recommendations on actions that can be taken and what impact they will have.

As an open source project, we hope that its evolution and direction is community driven and meets the needs and use cases identified. We welcome all feedback and input on how this product can grow, in terms of directions, features, methodology changes, and code updates.
For more visibility into the work planned and happening, please visit the [project board](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/projects/1) or [create an issue.](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/new/choose)
For feedback, questions, or if you’d like to collaborate on shaping the product direction, please reach out to [green-cloud@thoughtworks.com](mailto:green-cloud@thoughtworks.com).

### [How it works](https://www.cloudcarbonfootprint.org/docs/overview#how-it-works)
Cloud Carbon Footprint works by taking your cloud provider usage data, converting it into energy, and then taking into account the power usage effectiveness of the cloud provider’s data centers and the carbon intensity of the region where the data center pulls power from.
For a more detailed and in depth explanation into the approach and methodology, please reference the [Methodology Page.](https://www.cloudcarbonfootprint.org/docs/methodology)

----

## How does it integrate into Backstage:

We will provide 2 new plugins:

**Cloud Carbon Footprint Plugin:** Add a frontend plugin to display a Cloud Carbon Footprint Plugin. This page relies heavily on components from the `@cloud-carbon-footprint/client` & will try to display the same information as the standalone application.

**Cloud Carbon Footprint Backend Plugin:** Add a backend plugin for querying the emissions through the API. This plugin is just a small wrapper around the `@cloud-carbon-footprint/api`. It will create & use an instance of the `@cloud-carbon-footprint/api` express router by importing it from the project.

For using the plugin you need to define several variables in your `app-config.yaml`. The plugin requires separate configuration for each cloud provider. It also requires specific permissions and billing exports to be configured.

The [CCF docs](https://www.cloudcarbonfootprint.org/docs/introduction) are the source of truth for CCF configuration. This readme aims to guide users how to inject relevant configuration into Backstage using its [static configuration mechanism](https://backstage.io/docs/conf/).

To see data, set follow the setup for one or more of the cloud providers.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by austin-garrard** [comment]
@tudi2d hej, i've made some additional changes to the backend allowing minimal config for GCP to be plugged in via backstage config. i used that code to read actual data from my own GCP account!

I wonder if we should try to fill that out for all the cloud providers. CCF requires auth tokens for AWS and Azure so we would need to inject some of them as secrets. What do you think?

we almost have the client libraries published, after which i can plug it in here and try to resolve the merge conflicts.

**Comment by freben** [comment]
We'd love to get this one in!

**Comment by austin-garrard** [comment]
Had to rebase for the DCO.

It should now be possible to set all the CCF config through app-config. I've tested it on my GCP account and we have some folks trying it out on TW resources in AWS. Hopefully with the updated readme and comments in the config schema, anyone should be able to try it out. let me know if you find anything or see anything else we should address!

**Comment by tudi2d** [comment]
ok - something broke our Git history here. I tried to fix it & it should be ok-ish now, but rebasing is not fun anymore...

Anyway - there is a blocking thing breaking tsc right now:

Screenshot 2022-04-01 at 17 51 33

CCF overrides the types for MUI theming - not sure how to avoid this, but yeah - we can't bring this in 😕 

Also I was wondering if there is a better way to express the conditionals in `convertConfig.ts`. I bet we find a way to make this shorter & more intuitive.

**Comment by austin-garrard** [comment]
Alright, I'll catch up with the CCF folks about the theme. Is your feeling that if we can sort out the theme and simplify the config conversion, that would put us in a good place? Or is the impact on lockfile still concerning?

**Comment by tudi2d** [comment]
@austin-garrard so I was wondering about 2 thinks atm:

- Is there are a reason for the following versions to be fixed or can we add a `^...`?
```json
    "@material-ui/lab": "4.0.0-alpha.57",
    "moment": "2.29.1",
    "react-router-dom": "6.0.0-beta.0",
```
- We briefly talked about the cache files. They are not visible in the review so I want to mention it. Is there anyway such that they are not injected in the `packages/backend` of the whole project but just into the backend plugin folder? 😕

**Comment by austin-garrard** [comment]
changing the version specifier to compatible should be fine.

there might be some work planned around the cache file so i'll get back to you on that. generally it should be possible to make its placement configurable

**Comment by Rugvip** [comment]
Wanna check in on this one, we discussed adding it to a separate repo because of the large number of deps. Is that still where we're headed and should we then close this?

**Comment by austin-garrard** [comment]
Hey @Rugvip, yes we are in the process of creating a separate repo for the plugin https://github.com/cloud-carbon-footprint/ccf-backstage-plugin. 

still working through a few issues & docs but we are hoping to make a PR into your microsite soon! Please let us know if you have any feedback or suggestions.

**Pull request closed without merging**
