### PR TITLE
fix [Techdoc]btoa encoding

### PR DESCRIPTION
**Pull request by kim5566**
## Hey, I just made a Pull Request!

Related issue: https://github.com/backstage/backstage/issues/11015

- btoa is known to not support extended characters https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa

- SVG files could contain utf8 characters.

-  [MDN recommends a solution to escape the string before encoding it](https://developer.mozilla.org/en-US/docs/Glossary/Base64#solution_1_%E2%80%93_escaping_the_string_before_encoding_it)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by kim5566** [comment]
hi @backstage/techdocs-core would you be able to review the pr please?

**Comment by kim5566** [comment]
hi @backstage/reviewers @backstage/techdocs-core , would you be able to review the pr please?

**Review by iamEAP — APPROVED** [review]
Thanks for your patience @kim5566! Change makes sense and looks good to me. If you rename the changeset so that it's prefixed with `techdocs-`, we can avoid having to wait on the core reviewers' approval.

**Comment by iamEAP** [comment]
Thanks!

Gonna merge this in; noting for future code spelunkers that `unescape` is technically deprecated (though _very_ widely still supported). If folks run into problems, we can fix it then!

**Pull request merged**
