### PR TITLE
Updated to use default import

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Updated New Backend System instructions to use default import

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Ran into this with the Azure DevOps plugin helping someone on Discord here: https://discord.com/channels/687207715902193673/1207114617952673932. Tried to find all the ones like this and fixed them too.

**Review by kuangp — APPROVED** [review]
Looks good for ADR and Entity Feedback - thanks!

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks @awanlin!

**Comment by awanlin** [comment]
Thanks for the quick reviews and merge @kuangp and @benjdlambert 🚀

**Pull request merged**
