### PR TITLE
[Bugfix] Adding logic to consider if locations match based on glob pattern

### PR DESCRIPTION
**Pull request by heatheralee**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thanks!

I'm a bit concerned this is a bit too custom logic deep into the catalog implementation. Could you provide some more background on the issue and how to reproduce?

**Comment by benjdlambert** [comment]
ping @heatheralee

**Comment by Rugvip** [comment]
We're working to remove the code that this is modifying, and this has a different solution in the new version of the catalog. Is it alright to close?

**Comment by heatheralee** [comment]
Hi @Rugvip AND @benjdlambert! Apologies for the late response. This can be closed out, thanks!

**Pull request closed without merging**
