### PR TITLE
updating dockerfile and creating task to build the image from the host

### PR DESCRIPTION
**Pull request by tarcinil**
## Hey, I just made a Pull Request!

This removes the nodejs builder from the image.  This copies the build from the host building the image directly into the nginx mainline.

I also created a `yarn docker-build` which will allows the build to be ran on the host and then copied into the docker image.

Once we have stabilized the image, will this be going to the hub?

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [X] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] [CODEOWNERS](./CODEOWNERS) updated (for new stuff)
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by tarcinil** [comment]
I am planning on finishing a doc but my Mac battery ran low.

**Review by Rugvip — DISMISSED** [review]
Thanks!

Fixes #436 and #443

**Comment by stefanalund** [comment]
@tarcinil thanks. Please rebase and we will merge!

**Review by Rugvip — DISMISSED** [review]
Fixed conflict with GitHub web gui ¯\_(ツ)_/¯

**Review by Rugvip — APPROVED** [review]

**Pull request merged**
