### PR TITLE
permissions: change permission integration route to use /.well-known prefix

### PR DESCRIPTION
**Pull request by mtlewis**
## Hey, I just made a Pull Request!

Adjusts the route used by the permission integration system to use a [`/.well-known` prefix](https://www.keycdn.com/support/well-known#what-is-the-well-known-path-prefix), in the hope that this reduces the chance that the route conflicts with other routes in plugin backends.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
Of course I like it :) (i'm not the goalie tho)

**Review by jhaals — APPROVED** [review]
I think this is a great idea!

Do we really need backstage in the path? I vote for making `/.well-known/backstage/apply-conditions` into 
`/.well-known/apply-conditions`?

I'm thinking the urls are likely to be `https://backstage.example.com/catalog/.well-known/backstage/apply-conditions`

**Comment by mtlewis** [comment]
> Do we really need backstage in the path? I vote for making /.well-known/backstage/apply-conditions into
/.well-known/apply-conditions?
> 
> I'm thinking the urls are likely to be https://backstage.example.com/catalog/.well-known/backstage/apply-conditions

Great question! For a bit more bike-shed fun, I'm also wondering whether it would be nice to consider including "permission" in the route to make it clear that these are _permission_ conditions. Perhaps we can consider `/.well-known/permissions/apply-conditions` too? Or even `/.well-known/backstage/permissions/apply-conditions`. 😅

**Comment by Joonpark13** [comment]
> Great question! For a bit more bike-shed fun, I'm also wondering whether it would be nice to consider including "permission" in the route to make it clear that these are _permission_ conditions. Perhaps we can consider `/.well-known/permissions/apply-conditions` too? Or even `/.well-known/backstage/permissions/apply-conditions`. 😅

My vote's for `/.well-known/permissions/apply-conditions`

**Comment by freben** [comment]
The reason I voted for a `backstage` at the root is, we may want to put more things in here and this entire `.well-known` hierarchy is actually backed by an [official IANA list](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) that you're supposed to formally register yourself on. Essentially, the next path part after `.well-known` is a truly globally (across the world...) unique resource, which is _way worse_ to clobber than the individual backend routers 😅 

`.well-known/backstage/permission-apply-conditions` perhaps. And then we might consider registering the `backstage` space with the IANA some day :P

**Comment by mtlewis** [comment]
The logic of introducing a backstage/ space under .well-known makes sense to me. How about `.well-known/backstage/apply-permission-conditions`? It's a nit, but putting `permission` before `apply` implies to me that we're applying conditions to a permission, but actually we're applying conditions to a resource - this work is _related_ to the permissions system, but permissions themselves actually don't come into it - there's nothing in the request to indicate the permission the request corresponds to.

To try to sum up a bit and edge closer to a conclusion, I think the current options that have been proposed are:

### Prefixes:
1. `/.well-known` prefix
2. `/.well-known/backstage` prefix
3. `/.backstage` prefix

### Paths:
1. `<prefix>/apply-conditions`
2. `<prefix>/permissions/apply-conditions`
3. `<prefix>/permission-apply-conditions`
4. `<prefix>/apply-permission-conditions`

I guess my feelings are as follows:
* I'm really on the fence about the prefix. I don't think the `/.well-known` prefix _quite_ captures what we're doing here -- it feels a bit broad. 2 and 3 both mitigate that, but at the cost of including "backstage" multiple times in the URL, as @jhaals said.
* Of the paths, I'm happy enough with 2 or 4, while I feel 1 is missing some context and 3 implies an incorrect relationship between "permission" and "apply".

**Comment by jhaals** [comment]
So after some offline bike shedding I'd say go with prefix 2 and path 2. Long URLs but properly segmented and it allows for Joe to completely rewire his API rotes to start with / so `https://catalog.corp/.well-known/backstage/permissions/apply-conditions` would be his URL 😅

**Comment by mtlewis** [comment]
Done!

**Review by Rugvip — APPROVED** [review]
Good stuff 💯  :shipit:

**Review by joeporpeglia — APPROVED** [review]

**Pull request merged**
