### PR TITLE
fix command  to yarn create-plugin in create-a-plugin

### PR DESCRIPTION
**Pull request by kjuulh**
Signed-off-by: Kasper Juul Hermansen <contact@kjuulh.io>

## Hey, I just made a Pull Request!

Fixed a small typo / change in command

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — COMMENTED** [review]
See https://github.com/backstage/backstage/pull/15107 - we are going _away_ from `create-plugin` actually. The `new` entry to package.json was added in https://github.com/backstage/backstage/pull/13460 . If you are missing it in your root package.json, you can add it by hand as

```diff
 scripts: {
+  "new": "backstage-cli new --scope internal"
```

**Comment by kjuulh** [comment]
It wasn't in base template, which was why I thought it was the other way around.

Feel free to close xD

**Comment by freben** [comment]
Alright, sure!

**Comment by diggyk** [comment]
Thanks for heads up.  I'll update my packages.json

**Pull request closed without merging**
