### PR TITLE
Upgrade @rollup/plugin-node-resolve to 13.0.6

### PR DESCRIPTION
**Pull request by julioz**
Signed-off-by: Julio Zynger <julio.zynger@soundcloud.com>

## Hey, I just made a Pull Request!

Fixes https://github.com/backstage/backstage/issues/12219

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thanks! 👍

**Comment by julioz** [comment]
@Rugvip Fixed, thanks for the comment.

Would we be able to ship a `1.3.1` release including this patch?

**Review by Rugvip — APPROVED** [review]
Thanks! 👍 

There will be a prerelease on Tuesday, but won't cut a patch release as this doesn't affect newly created projects and can be worked around in existing projects.

**Comment by julioz** [comment]
> There will be a prerelease on Tuesday, but won't cut a patch release as this doesn't affect newly created projects and can be worked around in existing projects.

@Rugvip Can you please describe exactly what the workaround is? We have held on to the 1.3.0 bump and now tried the 1.4.0 release just to hit the same wall. We're running `@backstage/cli` `0.18.0` but still see the following error when running `yarn run build`:

```
Error: (plugin commonjs) Error: Insufficient @rollup/plugin-node-resolve version: "@rollup/plugin-commonjs" requires at least @rollup/plugin-node-resolve@13.0.6.
```

**Comment by brja** [comment]
> > There will be a prerelease on Tuesday, but won't cut a patch release as this doesn't affect newly created projects and can be worked around in existing projects.
> 
> @Rugvip Can you please describe exactly what the workaround is? We have held on to the 1.3.0 bump and now tried the 1.4.0 release just to hit the same wall. We're running `@backstage/cli` `0.18.0` but still see the following error when running `yarn run build`:
> 
> ```
> Error: (plugin commonjs) Error: Insufficient @rollup/plugin-node-resolve version: "@rollup/plugin-commonjs" requires at least @rollup/plugin-node-resolve@13.0.6.
> ```
> 
> Setting a package resolution in the root `package.json` did not help:
> 
> ```
>   "resolutions": {
>     "react": "^17",
>     "react-dom": "^17",
>     "@rollup/plugin-node-resolve": "13.0.6",
>     "@hot-loader/react-dom": "^17",
>     "@types/react": "^17",
>     "@types/react-dom": "^17"
>   },
> ```

@julioz we faced the same issue as well still in `@backstage/cli` `0.18.0` whereas on a fresh `npx @backstage/create-app` it works fine.

Executing
```
rm -rf node_modules
rm yarn.lock
yarn install
```
solved the issue.

**Comment by julioz** [comment]
We've spent significant amount of time debugging the issue, and indeed tried setting up a new app with `@backstage/create-app`; that also works fine.

We finally figured out what the issue was in our setup; here we use `npm` instead of `yarn` but backstage heavily relies on the latter. We've been referencing two lockfiles (`package-lock.json` and `yarn.lock`) for some time, and the issue was arising from a circular dependency between the two. When `yarn install` ran, it would update one of the lockfiles but not the other and `npm install` would do the opposite. The solution was to rework our setup to get rid of the `npm` dependency altogether and rely fully on `yarn` (to follow Backstage's setup) even though that means getting out of our company 'golden path' for web development.

**Pull request merged**
