### PR TITLE
Added Inmetrics to ADOPTERS.md

### PR DESCRIPTION
**Pull request by joel-vasiliev**
Added Inmetrics to ADOPTERS.md

### CODE REVIEW

**Comment by freben** [comment]
@joel-vasiliev Hi! Glad to have you here! Note that as the bot message says above, we need DCO signatures on all commits to this repo - including to this file. Check out what the message says to see if it makes sense, and let us know if you want us to help out making this addition.

**Comment by freben** [comment]
Hey again! I added https://github.com/backstage/backstage/pull/11966 to try to help address this, I hope that's OK. I'll just need your thumbs up on it to be allowed to merge it :)

**Review by jhaals — COMMENTED** [review]
The commits need to signed with the `-s` flag when running `git commit`. The quickest thing is probably to give a 👍 to the #11966 which freben created for you

**Comment by benjdlambert** [comment]
Closing as stale, reach out if you want to pick this work back up! :thanks:

**Pull request closed without merging**
