### PR TITLE
[PRFC][WIP] Remove react from cost-insights api and recharts module from initial bundle

### PR DESCRIPTION
**Pull request by szubster**
Signed-off-by: Tomasz Szuba <tszuba@box.com>

## Hey, I just made a Pull Request!

When addind cost-insights plugin to our instance, we realized our initial bundle grow quite a bit and unexpected module `recharts` appeared in it.
We realized this happens because `cost-insights` api is loaded synchronously and exposes react components also in synchronous way.
This PR is not complete. We want to show benefits of removing react components from PR. To have it merged we would need to rewrite the plugin with custom extensions (similar to scaffolder) so that react is not part of api. 
We just wanted to quickly check, whether community and maintainers are interested in such effort.
If this is something desired, maybe we should add ADR (even lints?) that would prohibit react usage inside API layer.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by szubster** [comment]
Difference in produced bundle on `packages/app` (visualized using https://statoscope.tech/):
before:
image
after:
image
diff:
image
image

**Comment by freben** [comment]
Indeed it is very highly desirable to lazy load components like these!

**Comment by szubster** [comment]
Have you thought about writing some rules (ADR) or maybe even some linter (is something like archunit for TS?)?
I had an idea that maybe frontend API should be in a separate module with react blocked as dependency?

**Comment by szubster** [comment]
Also more documentation around composability system would be awesome. It's sometimes hard to wrap head around this.
https://backstage.io/docs/plugins/composability
I tried to understand how extensions in scaffolder work and how to port it to cost-insights and use it in alerts but I couldn't add 2 + 2 
https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/extensions/index.tsx

**Comment by andrewthauer** [comment]
For slightly different reasons, we also noticed the `CostInsightsApi` interface contains react types which seems problematic. We have been building out a backend plugin that serves as both the collector of costing data + a router that returns the aggregated data to service the frontend `CostInsightsApi` implementation.

I published PR #12298 a while back to move some of the types into an new `@backstage/plugin-cost-insights-common` isomorphic package. However, I had to stop short for some of the types that were either a bit more coupled to the UI or React components. It would be ideal if the `CostInsightsApi` was a bit easier to adapt into a backend API.

At a high level I think the `CostInsightsApi` needs to be split up and/or refactored to avoid using React types. It seems the `Alert` type and the `getAlerts` method would need to change. The `getAlerts` imo should probably use a `AlertData` type and then on the frontend it can compose the data and react components together as needed.

NOTE: I'm not entirely sure this would address the same issue or perhaps they are both just indications of the issue of react types being part of the API interface.

**Comment by szubster** [comment]
@andrewthauer We have exactly same journey. Currently I am thinking about something similar to `EntitySwitch`. I am not sure how to make types safe and whether I will have enough time and knowledge to implement it.

**Comment by andrewthauer** [comment]
> @andrewthauer We have exactly same journey. Currently I am thinking about something similar to `EntitySwitch`. I am not sure how to make types safe and whether I will have enough time and knowledge to implement it.

It sounds like we are on a similar course. Can you elaborate on your idea of the `EntitySwitch`?

**Comment by szubster** [comment]
> > @andrewthauer We have exactly same journey. Currently I am thinking about something similar to `EntitySwitch`. I am not sure how to make types safe and whether I will have enough time and knowledge to implement it.
> 
> It sounds like we are on a similar course. Can you elaborate on your idea of the `EntitySwitch`?

If you look at [EntitySwitch](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntitySwitch/EntitySwitch.tsx) you could implement something similar called `AlarmSwitch` that would handle rendering an alarm, without changing API surface.
Another possibility is implementing it as extension, similar to how you can extend [scaffolder](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/extensions/index.tsx). At least those are directions my mind goes to.

**Review by Rugvip — COMMENTED** [review]
Very much worth exploring! 👍 

I've pushed proper lazy loading of all content forward a bit as we've been focused in other areas lately. Very much aware that there are some troublesome patterns in places that we need to untangle. ADR would be nice, and I'm also feeling that we need to establish clear patterns and core APIs that easily help you avoid eagerly loaded content. In particular locally customized components are always quite tricky at the moment, and would want to figure something out for that.

When it comes to matter in this PR, I'm thinking scaffolder-like extensions should make sense. We'd ofc need to still be careful to make sure they are lazy-loaded too, eitherwise we haven't gained much. It's also possible to add lazy-loading to the API, but somehow that feels a bit more involved and less clean. The costs insights API was designed before we had established the extension pattern after all.

**Pull request closed without merging**
