### PR TITLE
Remove implementsApis

### PR DESCRIPTION
**Pull request by Fox32**
This was deprecated in #3449. This should not be merged sooner then Dec 14th, 2020!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]

**Review by stefanalund — APPROVED** [review]

**Comment by Fox32** [comment]
I think this could be merged now, but I'm not sure if I should pull the trigger myself

**Comment by freben** [comment]
@Rugvip - you were suggesting we count time between releases, not time since announcement, right? As in, if we announce on the 1st, and release on the 5th, then time starts counting on the 5th and only after the closest release AFTER 5th + N days do we merge.

Is that what we should go by, or should that be like a "from here on out" thing?

**Comment by Rugvip** [comment]
In the end we concluded that we wanna avoid merging pending PRs too soon after a release in case we wanna do an emergency release right?

Maybe we can make that more concrete and settle on merging any pending PRs the day before the release they're supposed to go out in? Meaning we'll merge this one Wednesday

**Comment by freben** [comment]
OK. Hm we should set up some kind of calendar for these things, so that not just us but also consumers can see a timeline of significant changes that are coming up.

**Comment by Fox32** [comment]
> Meaning we'll merge this one Wednesday

Sounds reasonable. I guess you (the core team) takes care of this?

**Comment by freben** [comment]
Yep we'll be happy to

**Pull request merged**
