### PR TITLE
Add examples for publish:azure scaffolder action

### PR DESCRIPTION
**Pull request by MarcBuch**
## Hey, I just made a Pull Request!

I've seen issue #18832 and wanted to add examples for `publish:azure`.

Screenshot 2023-10-06 at 13 53 25

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by MarcBuch** [comment]
Question: Do I need to write tests for this? I've seen some scaffolder examples with tests while others have no tests.

**Comment by awanlin** [comment]
> Question: Do I need to write tests for this? I've seen some scaffolder examples with tests while others have no tests.

Hi @MarcBuch, tests would be awesome to have, they would help validate the action works with the given parameters. There are already some tests you can build off from so you won't have to start from scratch 👍

**Comment by MarcBuch** [comment]
@awanlin done

**Review by awanlin — APPROVED** [review]
Thanks for the contribution @MarcBuch! 🚀 

Just need a review and approval from @vinzscam or @Rugvip now

**Review by Rugvip — APPROVED** [review]
Nice, thank you! 🎉 

Let's :shipit:

**Comment by awanlin** [comment]
Thanks again @MarcBuch and @Rugvip for the review and merge 🚀

**Pull request merged**
