### PR TITLE
Add Just Eat Takeaway to adopters list

### PR DESCRIPTION
**Pull request by DRoystonSmith**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Welcome to the community!

**Comment by jhaals** [comment]
Welcome! And it looks like I merged another adopter PR in between 😅 Would you be able to rebase this PR @DRoystonSmith?

**Comment by benjdlambert** [comment]
I went ahead and fixed it up 👍

**Review by jhaals — APPROVED** [review]
Thanks Ben ⚡ 🧙

**Pull request merged**
