### PR TITLE
Make the host of AWS Code Commit changeable

### PR DESCRIPTION
**Pull request by Kang3498**
## Hey, I just made a Pull Request!

As-Is : The catalog:register action does not work when using AWS Code Commit.

In the link below, config.host is forced to console.aws.amazon.com, so, If I set repoContentsUrl to {region}.console.aws.amazon.com in the catalog:register action, No Integration error occurs.
https://github.com/backstage/backstage/blob/master/packages/integration/src/awsCodeCommit/config.ts#L67

Instead, if I remove the region from the url, an error occurs due to the link below.
https://github.com/backstage/backstage/blob/master/packages/backend-common/src/reading/AwsCodeCommitUrlReader.ts#L70

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by stijnbrouwers** [comment]
@Kang3498 
I had a fix ready for #24824 for which I had a fix similar to this one which you can view here:
https://github.com/stijnbrouwers/backstage/pull/1
(it's a pull request to my own master branch just for you to have an easy view on my code)

I did the same as you did and allowed the user to be able to set the host manually.
I also introduced a mandatory "region" property to the awsCodeCommit config. This would allow the user to set only a region and the system would determine the correct host URL from that.

Since I require the region, I am not adding a default entry in ```readAwsCodeCommitIntegrationConfigs``` This prevents the scenario where, for example, we default to region "us-east-1" and the user would get a message like "no integration found for url...". In this scenario, they might not really knows what's going on without having to debug the code...

**Comment by Kang3498** [comment]
@stijnbrouwers 
That's a good suggestion. If you create a new PR with that suggestion, I will close this PR.

**Comment by stijnbrouwers** [comment]
@Kang3498 
I just created the PR #24843

Feel free to tag me in the future when you find an issue regarding AWS CodeCommit integration. Should I have the time, I will definitely take a look.

**Comment by Kang3498** [comment]
This will be replaced with the PR https://github.com/backstage/backstage/pull/24843

**Comment by Kang3498** [comment]
I decided to reopen this PR. 
There is a problem with the PR I was trying to replace, and it is expected to take some time.
The project currently working on with Code Commit is not working at all.

**Comment by Kang3498** [comment]
@freben I want this PR to be reviewed. Code Commit is still not working in the current version. I hope it merges into the next version quickly.
It looks like the PR (#24843) that was being replaced will take some time to be resolved.

**Comment by Kang3498** [comment]
Since that [PR](https://github.com/backstage/backstage/pull/24843) has been merged, I will close this PR.

**Pull request closed without merging**
