### PR TITLE
create-app/e2e: default app template fixes related to prettier and tsc

### PR DESCRIPTION
**Pull request by OrkoHunter**
Created a new app and found out that prettier and tsc experience needed some work like updates to few files and a version bump of prettier itself.

Co-authored-by: Mike Lewis <mtlewis@users.noreply.github.com>
Signed-off-by: Himanshu Mishra <himanshu@orkohunter.net>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Expecting E2E to fail since we are now checking for prettier in newly created app.

**Comment by OrkoHunter** [comment]
This PR is currently stuck since we're running `yarn tsc:full` on newly created app, and it fails because there are two versions of `@types/react` package (both 16 and 17). (There could be more issues with other packages as well)

**Comment by benjdlambert** [comment]
Does the new prettier install cause this issue with types?

**Comment by OrkoHunter** [comment]
@benjdlambert Just verified - No, this is an existing issue - create a new backstage app and run `yarn tsc:full` and it fails.

**Comment by benjdlambert** [comment]
Hmm so that means that the e2e tests should be failing on master then right? I just had the same failure when doing some work on roadie PR. I think we need to add a resolution in create-app to force `@types/react` to resolve to `16.9` as there's an issue that `react@*` brings in the latest.

**Comment by OrkoHunter** [comment]
> Hmm so that means that the e2e tests should be failing on master then right?

Yep they should! The reason why they aren't right now, is that we aren't running `yarn tsc:full` on create-app template, only `yarn tsc`. This PR updates the E2E tests, hence it's failing right now.

**Comment by benjdlambert** [comment]
AHHH. OK. Well, in that case, we probably need to add the resolutions then in the `create-app` template.

**Comment by benjdlambert** [comment]
Or I mean, playing devil's advocate a little bit, what's the reasoning for using `tsc:full`? This is going to cause a lot of friction when we don't ship a `yarn.lock`, things are going to be broken a lot more often than normal, and maybe people won't care about having `skipLibCheck` off for their own instance of Backstage

**Comment by OrkoHunter** [comment]
Yeah, it looks like prettier on windows is expecting a different new line character. This is helpful https://prettier.io/docs/en/options.html#end-of-line

**Comment by Rugvip** [comment]
🟢 🟢 🟢 🟢 🟢 🟢 🟢 🟢 🟢 🟢 🟢

**Comment by Rugvip** [comment]
Added changesets as well, so hoping this is good to go now

**Review by benjdlambert — APPROVED** [review]

**Review by iamEAP — APPROVED** [review]

**Pull request merged**
