### PR TITLE
Change create-app yarn test to use `--since`

### PR DESCRIPTION
**Pull request by tylerd-canva**
## Hey, I just made a Pull Request!

Just a proposal. IMHO the behaviour of `yarn test` should match `yarn lint`.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by tylerd-canva** [comment]
Actually based on https://github.com/backstage/backstage/blob/3371d2023135da1d50ac4c1a77cfe1eb58cac5f4/CONTRIBUTING.md?plain=1#L143 I think this change is correct and should be applied here as well perhaps https://github.com/backstage/backstage/blob/ecdb1ce0b66149a7051cd6635153ab0070494994/package.json#L52

**Comment by tylerd-canva** [comment]
On second thought... I don't think this is working properly. Is there a known issue here? I made a trivial change in one of my packages locally and it claims there are no changes.

**Review by Rugvip — CHANGES_REQUESTED** [review]
The `test` and `lint` scripts are primarily intended for local development. The `test` script already has "since"-like behavior built-in via Jest, which `lint` doesn't have and why we use `--since` there.

Not opposed to adding something for CI though, could for example be `:changed` scripts for both?

**Comment by Rugvip** [comment]
Oh and yep the docs aren't really accurate, `yarn test` tests pending changes that are not yet committed, rather than changes since master

**Comment by tylerd-canva** [comment]
@Rugvip thank you for the explanation! I will rework this.

**Pull request closed without merging**
