### PR TITLE
feat(EntityPlaylistDialog): use EntityPresentationApi instead of humanizeEntityRef to display entity

### PR DESCRIPTION
**Pull request by Nikunj0601**
## Hey, I just made a Pull Request!

This PR is done to resolve the issue #20955 . I have changed the way to display the entity by using `entityPresentationApi` instead of `humanizeEntityRef`. I have used `entityPresentationApi` here in React JSX because directly using `<EntityDisplayName />` was making ui changes which i thought should be avoided.
Below attached screenshot shows current UI
image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by kuangp — CHANGES_REQUESTED** [review]
Hi @Nikunj0601 - thanks for this change but can you open this in https://github.com/backstage/community-plugins/tree/main/workspaces/playlist/plugins/playlist ? This plugin has been migrated to this new repo and the one that exists here is now deprecated.

**Comment by Nikunj0601** [comment]
@kuangp sure will do that. But I also think that we add changes here too cause this also being used currently.

**Comment by kuangp** [comment]
> @kuangp sure will do that. But I also think that we add changes here too cause this also being used currently.

I don't believe we will be releasing any more updates to plugins in this repo that have migrated to the new community-plugins repo cc:  @Rugvip to confirm

**Comment by Nikunj0601** [comment]
@kuangp i was trying to create changeset in community-plugin repo but couldn’t find yarn changeset script cmd anywhere. Is there any other to generate changeset?

**Comment by kuangp** [comment]
> @kuangp i was trying to create changeset in community-plugin repo but couldn’t find yarn changeset script cmd anywhere. Is there any other to generate changeset?

You should be able to generate a changeset by running `yarn changeset` in the root of the plugin workspace: https://github.com/backstage/community-plugins/tree/main/workspaces/playlist

**Comment by Nikunj0601** [comment]
@kuangp yes i did that but still it is saying script not found.
image
am I doing something wrong or missing some configuration to do?

**Comment by kuangp** [comment]
did you run `yarn install` within the playlist workspace?

**Comment by Nikunj0601** [comment]
yes i did that.

**Comment by Nikunj0601** [comment]
Okay its working i uninstalled my yarn version and re-installed again.

**Comment by Nikunj0601** [comment]
@kuangp I just raised the PR in `community-plugin` repo. 
https://github.com/backstage/community-plugins/pull/184

**Comment by benjdlambert** [comment]
@Nikunj0601 thanks for your patience whilst we go through this migration period and moving plugins.

@kuangp thanks for the help!

Gonna close this issue and let's carry on the conversation in the other repo :pray:

**Pull request closed without merging**
