### PR TITLE
[NBS Docs] Updated GitHub Integrations Docs

### LINKED ISSUE #24576: 🚀 Feature: Clarity on GitHub Org Provider Single Org vs. Multi Org
### 🔖 Feature description

It would be great to have some clarity around the recommend path for using GitHub Org Data in Single and Multi Org contexts. 

### 🎤 Context

Currently with the new backend system being the default you can only setup the Single Org provider following the easy install path with a single line. If you want to use the Multi Org provider there's a lot more steps involved. 

I ran into this while trying to update the [GitHub Org Integration documentation](https://github.com/backstage/backstage/pull/24573) to better reflect the new backend system.

### ✌️ Possible Implementation

Would it make sense to merge these and have a single provider that handles both via configuration? As I'm not a user of these I'm unsure of the best solution.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Updated GitHub Integrations Docs with details on how to uses it with the new backend system

Closes #24576 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by ManuInNZ** [comment]
Great content and a way cleaner management of the transformers.

**Comment by ManuInNZ** [comment]
Silly me maybe but don't you need still to specify the schedule ?
Unless I missed it you do not have it in the org.md.
```yaml
catalog:
  providers: 
    githubOrg:
      id: production
      githubUrl: https://github.com
      orgs: ['Org1', 'Org2']
      schedule:
        frequency: PT1H
        timeout: PT50M
```

**Comment by ManuInNZ** [comment]
In addition, is there value to demonstrate multiple GH Apps usage?
e.g.:
```yaml
integrations: 
  github:
    - host: github.com
      apps:
        - appId: ${AUTH_ORG1_APP_ID}
          clientId: ${AUTH_ORG1_CLIENT_ID}
          clientSecret: ${AUTH_ORG1_CLIENT_SECRET}
          privateKey: ${AUTH_ORG1_PRIVATE_KEY}
          webhookSecret: ${AUTH_ORG1_WEBHOOK_SECRET}
        - appId: ${AUTH_ORG2_APP_ID}
          clientId: ${AUTH_ORG2_CLIENT_ID}
          clientSecret: ${AUTH_ORG2_CLIENT_SECRET}
          privateKey: ${AUTH_ORG2_PRIVATE_KEY}
          webhookSecret: ${AUTH_ORG2_WEBHOOK_SECRET}
```

**Comment by awanlin** [comment]
Thanks for the feedback @ManuInNZ, going to address both comments here:

- Yes, I totally missed adding the schedule, thanks for pointing that out, I've added that 
- For multiple GitHub Apps it wasn't the focus of this PR but it did point out some other changes. I did add something for that though I kept it simple to minimize that amount of change as I really want to see these docs updated quickly

**Comment by ManuInNZ** [comment]
Wonderful 😃

**Review by benjdlambert — APPROVED** [review]
Nice! Good stuff! :tada:

**Comment by awanlin** [comment]
Many, many, many thanks @benjdlambert, this should help a lot of people!!!!

**Pull request merged**
