### PR TITLE
Bye bye 👋

### PR DESCRIPTION
**Pull request by stefanalund**
Signed-off-by: Stefan Ålund <stefan.alund@gmail.com>

### CODE REVIEW

**Comment by stefanalund** [comment]
> 👋 Bye Stefan, was nice to work together with you. Thank you for supporting this project.

> Btw dco is missing 😆

@Fox32 thanks!

> 👋 Thank you for your support and huge contribution to the project Stefan.

@leemills83 thanks!

**Comment by dtuite** [comment]
All the best for the future and it was very nice to meet you.

**Review by freben — APPROVED** [review]
Thanks for everything! You were instrumental in getting us to where we are.

**Comment by timbonicus** [comment]
Signed-off-by indeed, oof. Best wishes @stefanalund, you deserve all the praise in the world for your work on Backstage.

**Comment by ryanvazquez** [comment]
Best of luck! @stefanalund

**Comment by stefanalund** [comment]
It's been a thrill to work with all of you. Take care of Backstage ❤️

**Pull request merged**
