### PR TITLE
[NBS Docs] Updated the AWS S3 integration docs

### PR DESCRIPTION
**Pull request by Maetis**
## Hey, I just made a Pull Request!

Updated the AWS S3 Integration Documentation with example using the new backend system. (#24195)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@camilaibs what do you think is best for these docs updates? With the NBS getting to 1.x very soon, does it make sense to just remove the old documentation entirely, duplicate like this PR, or just have a smaller section inline in the same docs for now?

**Review by awanlin — APPROVED** [review]
This looks pretty great to me, thanks @Maetis 🚀

**Comment by mrod23** [comment]
Hi are there any additional steps to get this working?
Testing this out with the new backend..

In my logs I'm seeing
```
[1] 2024-06-29T14:12:55.726Z catalog info Discovered 2 AWS S3 objects target=awsS3-provider:default class=AwsS3EntityProvider taskId=awsS3-provider:default:refresh taskInstanceId=7bb0e993-4872-404e-bb2f-7e336c70f0f6
[1] 2024-06-29T14:12:55.727Z catalog info Committed 2 Locations for AWS S3 objects target=awsS3-provider:default class=AwsS3EntityProvider taskId=awsS3-provider:default:refresh taskInstanceId=7bb0e993-4872-404e-bb2f-7e336c70f0f6
```

But I'm not seeing the new entities in Backstage. 
To test I'm using the latest version of Backstage. 

My test entity looks like this 
```
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: mike
spec:
  owner: guests

```

**Review by camilaibs — APPROVED** [review]
Thanks 🎉

**Comment by camilaibs** [comment]
> @camilaibs what do you think is best for these docs updates? With the NBS getting to 1.x very soon, does it make sense to just remove the old documentation entirely, duplicate like this PR, or just have a smaller section inline in the same docs for now?

We are following the `--old` pattern suggested be @freben here 🙂: https://github.com/backstage/backstage/issues/24195#issuecomment-2052223183

**Pull request merged**
