### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by backstage-service**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and publish to npm yourself or [setup this action to publish automatically](https://github.com/changesets/action#with-publishing). If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
### Minor Changes

-   12a56cdfe: We've bumped the `@eslint-typescript` packages to the latest, which now add some additional rules that might cause lint failures.
    The main one which could become an issue is the [no-use-before-define](https://eslint.org/docs/rules/no-use-before-define) rule.

    Every plugin and app has the ability to override these rules if you want to ignore them for now.

    You can reset back to the default behaviour by using the following in your own `.eslint.js`

    ```js
    rules: {
      'no-use-before-define': 'off'
    }
    ```

    Because of the nature of this change, we're unable to provide a grace period for the update :(

### Patch Changes

-   ef7957be4: Add `--lax` option to `config:print` and `config:check`, which causes all environment variables to be assumed to be set.
-   Updated dependencies [ef7957be4]
-   Updated dependencies [ef7957be4]
-   Updated dependencies [ef7957be4]
    -   @backstage/config-loader@0.5.0

 ## @backstage/config-loader@0.5.0

### Minor Changes

-   ef7957be4: Removed support for the deprecated `$data` placeholder.
-   ef7957be4: Enable further processing of configuration files included using the `$include` placeholder. Meaning that for example for example `$env` includes will be processed as usual in included files.

### Patch Changes

-   ef7957be4: Added support for environment variable substitutions in string configuration values using a `${VAR}` placeholder. All environment variables must be available, or the entire expression will be evaluated to `undefined`. To escape a substitution, use `${...}`, which will end up as `${...}`.

    For example:

    ```yaml
    app:
      baseUrl: https://${BASE_HOST}
    ```

 ## @backstage/plugin-cost-insights@0.6.0

### Minor Changes

-   fac91bcc5: Add support for additional breakdowns of daily cost data.
    This changes the type of Cost.groupedCosts returned by CostInsightsApi.getGroupDailyCost.

### Patch Changes

-   8b7ef9f8b: Allow expand functionality to top panel product chart tooltip.

 ## @backstage/plugin-kafka@0.2.0

### Minor Changes

-   234e7d985: Added support for multiple Kafka clusters and multiple consumers per component.
    Note that this introduces several breaking changes.

    1.  Configuration in `app-config.yaml` has changed to support the ability to configure multiple clusters. This means you are required to update the configs in the following way:

    ```diff
    kafka:
       clientId: backstage
    -  brokers:
    -    - localhost:9092
    +  clusters:
    +    - name: prod
    +      brokers:
    +        - localhost:9092
    ```

    2.  Configuration of services has changed as well to support multiple clusters:

    ```diff
      annotations:
    -    kafka.apache.org/consumer-groups: consumer
    +    kafka.apache.org/consumer-groups: prod/consumer
    ```

    3.  Kafka Backend API has changed, so querying offsets of a consumer group is now done with the following query path:
        `/consumers/${clusterId}/${consumerGroup}/offsets`

### Patch Changes

-   Updated dependencies [9dd057662]
-   Updated dependencies [0b1182346]
    -   @backstage/plugin-catalog@0.2.14

 ## @backstage/plugin-kafka-backend@0.2.0

### Minor Changes

-   234e7d985: Added support for multiple Kafka clusters and multiple consumers per component.
    Note that this introduces several breaking changes.

    1.  Configuration in `app-config.yaml` has changed to support the ability to configure multiple clusters. This means you are required to update the configs in the following way:

    ```diff
    kafka:
       clientId: backstage
    -  brokers:
    -    - localhost:9092
    +  clusters:
    +    - name: prod
    +      brokers:
    +        - localhost:9092
    ```

    2.  Configuration of services has changed as well to support multiple clusters:

    ```diff
      annotations:
    -    kafka.apache.org/consumer-groups: consumer
    +    kafka.apache.org/consumer-groups: prod/consumer
    ```

    3.  Kafka Backend API has changed, so querying offsets of a consumer group is now done with the following query path:
        `/consumers/${clusterId}/${consumerGroup}/offsets`

### Patch Changes

-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [9dd057662]
    -   @backstage/backend-common@0.5.1

 ## @backstage/backend-common@0.5.1

### Patch Changes

-   26a3a6cf0: Honor the branch ref in the url when cloning.

    This fixes a bug in the scaffolder prepare stage where a non-default branch
    was specified in the scaffolder URL but the default branch was cloned.
    For example, even though the `other` branch is specified in this example, the
    `master` branch was actually cloned:

    ```yaml
    catalog:
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/other/plugins/scaffolder-backend/sample-templates/docs-template/template.yaml
    ```

    This also fixes a 404 in the prepare stage for GitLab URLs.

-   664dd08c9: URL Reader's readTree: Fix bug with github.com URLs.

-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.

-   Updated dependencies [6800da78d]

-   Updated dependencies [9dd057662]

-   Updated dependencies [ef7957be4]

-   Updated dependencies [ef7957be4]

-   Updated dependencies [ef7957be4]
    -   @backstage/integration@0.3.1
    -   @backstage/config-loader@0.5.0

 ## @backstage/create-app@0.3.7

### Patch Changes

-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [12a56cdfe]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [9dd057662]
-   Updated dependencies [ef7957be4]
-   Updated dependencies [0b1182346]
-   Updated dependencies [d7b1d317f]
-   Updated dependencies [a91aa6bf2]
-   Updated dependencies [39b05b9ae]
-   Updated dependencies [4eaa06057]
    -   @backstage/backend-common@0.5.1
    -   @backstage/plugin-scaffolder-backend@0.5.2
    -   @backstage/cli@0.5.0
    -   @backstage/plugin-catalog@0.2.14
    -   @backstage/plugin-catalog-backend@0.5.5
    -   @backstage/plugin-catalog-import@0.3.6
    -   @backstage/plugin-scaffolder@0.4.1
    -   @backstage/plugin-auth-backend@0.2.12
    -   @backstage/catalog-model@0.7.0
    -   @backstage/core@0.5.0
    -   @backstage/test-utils@0.1.6
    -   @backstage/theme@0.2.2
    -   @backstage/plugin-api-docs@0.4.3
    -   @backstage/plugin-app-backend@0.3.5
    -   @backstage/plugin-circleci@0.2.6
    -   @backstage/plugin-explore@0.2.3
    -   @backstage/plugin-github-actions@0.3.0
    -   @backstage/plugin-lighthouse@0.2.8
    -   @backstage/plugin-proxy-backend@0.2.4
    -   @backstage/plugin-rollbar-backend@0.1.7
    -   @backstage/plugin-search@0.2.6
    -   @backstage/plugin-tech-radar@0.3.3
    -   @backstage/plugin-techdocs@0.5.4
    -   @backstage/plugin-techdocs-backend@0.5.4
    -   @backstage/plugin-user-settings@0.2.4

 ## @backstage/integration@0.3.1

### Patch Changes

-   6800da78d: Fix default branch API url for custom hosted Bitbucket server
-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.

 ## @backstage/techdocs-common@0.3.6

### Patch Changes

-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.
-   db2328c88: Add rate limiter for concurrent execution of file uploads in AWS and Google publishers
-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [6800da78d]
-   Updated dependencies [9dd057662]
    -   @backstage/backend-common@0.5.1
    -   @backstage/integration@0.3.1

 ## @backstage/plugin-app-backend@0.3.5

### Patch Changes

-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [9dd057662]
-   Updated dependencies [ef7957be4]
-   Updated dependencies [ef7957be4]
-   Updated dependencies [ef7957be4]
    -   @backstage/backend-common@0.5.1
    -   @backstage/config-loader@0.5.0

 ## @backstage/plugin-auth-backend@0.2.12

### Patch Changes

-   d7b1d317f: Fixed serialization issue with caching of public keys in AWS ALB auth provider
-   39b05b9ae: Use .text instead of .json for ALB key response
-   4eaa06057: Fix AWS ALB issuer check
-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [9dd057662]
    -   @backstage/backend-common@0.5.1

 ## @backstage/plugin-catalog@0.2.14

### Patch Changes

-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.

-   0b1182346: Add `EntityRefLinks` that shows one or multiple entity ref links.

    Change the about card and catalog table to use `EntityRefLinks` due to the
    nature of relations to support multiple relations per type.

-   Updated dependencies [9dd057662]
    -   @backstage/plugin-scaffolder@0.4.1

 ## @backstage/plugin-catalog-backend@0.5.5

### Patch Changes

-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.
-   a91aa6bf2: Support supplying a custom catalog descriptor file parser
-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [9dd057662]
    -   @backstage/backend-common@0.5.1

 ## @backstage/plugin-catalog-import@0.3.6

### Patch Changes

-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.
-   Updated dependencies [6800da78d]
-   Updated dependencies [9dd057662]
-   Updated dependencies [0b1182346]
    -   @backstage/integration@0.3.1
    -   @backstage/plugin-catalog@0.2.14

 ## @backstage/plugin-kubernetes@0.3.7

### Patch Changes

-   681111228: Add AWS auth provider for Kubernetes
-   a6e3b9596: Improve error reporting for plugin misconfiguration.
-   Updated dependencies [681111228]
    -   @backstage/plugin-kubernetes-backend@0.2.6

 ## @backstage/plugin-kubernetes-backend@0.2.6

### Patch Changes

-   681111228: Add AWS auth provider for Kubernetes
-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [9dd057662]
    -   @backstage/backend-common@0.5.1

 ## @backstage/plugin-scaffolder@0.4.1

### Patch Changes

-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.
-   Updated dependencies [9dd057662]
-   Updated dependencies [0b1182346]
    -   @backstage/plugin-catalog@0.2.14

 ## @backstage/plugin-scaffolder-backend@0.5.2

### Patch Changes

-   26a3a6cf0: Honor the branch ref in the url when cloning.

    This fixes a bug in the scaffolder prepare stage where a non-default branch
    was specified in the scaffolder URL but the default branch was cloned.
    For example, even though the `other` branch is specified in this example, the
    `master` branch was actually cloned:

    ```yaml
    catalog:
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/other/plugins/scaffolder-backend/sample-templates/docs-template/template.yaml
    ```

    This also fixes a 404 in the prepare stage for GitLab URLs.

-   9dd057662: Upgrade [git-url-parse](https://www.npmjs.com/package/git-url-parse) to [v11.4.4](https://github.com/IonicaBizau/git-url-parse/pull/125) which fixes parsing an Azure DevOps branch ref.

-   Updated dependencies [26a3a6cf0]

-   Updated dependencies [664dd08c9]

-   Updated dependencies [6800da78d]

-   Updated dependencies [9dd057662]
    -   @backstage/backend-common@0.5.1
    -   @backstage/integration@0.3.1

 ## @backstage/plugin-sonarqube@0.1.9

### Patch Changes

-   49a67732f: Ask the SonarQube server for all support metrics prior to querying them for a project.

 ## example-app@0.2.13

### Patch Changes

-   Updated dependencies [681111228]
-   Updated dependencies [12a56cdfe]
-   Updated dependencies [8b7ef9f8b]
-   Updated dependencies [fac91bcc5]
-   Updated dependencies [9dd057662]
-   Updated dependencies [234e7d985]
-   Updated dependencies [ef7957be4]
-   Updated dependencies [0b1182346]
-   Updated dependencies [a6e3b9596]
    -   @backstage/plugin-kubernetes@0.3.7
    -   @backstage/cli@0.5.0
    -   @backstage/plugin-cost-insights@0.6.0
    -   @backstage/plugin-catalog@0.2.14
    -   @backstage/plugin-catalog-import@0.3.6
    -   @backstage/plugin-scaffolder@0.4.1
    -   @backstage/plugin-kafka@0.2.0

 ## example-backend@0.2.13

### Patch Changes

-   Updated dependencies [26a3a6cf0]
-   Updated dependencies [681111228]
-   Updated dependencies [664dd08c9]
-   Updated dependencies [9dd057662]
-   Updated dependencies [234e7d985]
-   Updated dependencies [d7b1d317f]
-   Updated dependencies [a91aa6bf2]
-   Updated dependencies [39b05b9ae]
-   Updated dependencies [4eaa06057]
    -   @backstage/backend-common@0.5.1
    -   @backstage/plugin-scaffolder-backend@0.5.2
    -   @backstage/plugin-kubernetes-backend@0.2.6
    -   @backstage/plugin-catalog-backend@0.5.5
    -   @backstage/plugin-kafka-backend@0.2.0
    -   @backstage/plugin-auth-backend@0.2.12
    -   example-app@0.2.13
    -   @backstage/plugin-app-backend@0.3.5

### CODE REVIEW

**Review by timbonicus — APPROVED** [review]

**Review by OrkoHunter — CHANGES_REQUESTED** [review]
@backstage/maintainers Noticed that this PR will once again create version `1.0.0` of create-app without any "major" changeset. It happened last time with us as well.

We should investigate what's going on here before the release! :)

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4220-rogx0nkjjh0g3gk1iapcrcjkfevcckjz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60128f7d98552d14ad50f01a

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4220-rogx0nkjjh0g3gk1iapcrcjkfevcckjz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60128f7d98552d14ad50f01a

**Review by benjdlambert — APPROVED** [review]

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4220-rogx0nkjjh0g3gk1iapcrcjkfevcckjz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60128f7d98552d14ad50f01a

**Review by OrkoHunter — APPROVED** [review]
Thanks for fixing!

**Review by Rugvip — APPROVED** [review]

**Pull request merged**
