### PR TITLE
fix: added `eventsServiceFactory` to `defaultServiceFactories`

### PR DESCRIPTION
**Pull request by marleypowell**
## Hey, I just made a Pull Request!

added `eventsServiceFactory` to `defaultServiceFactories` to resolve issue where different instances of the EventsServices could be used

related to #24319 
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@marleypowell sorry it's taken a while to get round to this -  can you rebase this :pray:

**Comment by marleypowell** [comment]
> @marleypowell sorry it's taken a while to get round to this - can you rebase this 🙏

got there eventually. I think that's done 🙂

**Comment by benjdlambert** [comment]
@marleypowell think that you'll need to regenerate the `api-reports` in order to get this passing.

`yarn build:api-reports` in the root and commit the changes should do it :tada:

**Review by Rugvip — APPROVED** [review]
Thank you! 👍 :shipit:

**Comment by marleypowell** [comment]
@benjdlambert thanks for getting this merged for me 🙂

**Pull request merged**
