### PR TITLE
Upgrade typescript-eslint to 6.7.x.

### PR DESCRIPTION
**Pull request by Pike**
## Hey, I just made a Pull Request!

There are breaking changes listed in https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/, as we are upgrading from 5.9.x.

This adds support for TypeScript 5.2 via 6.5.0.

Drafting this for now to see what the linter actually says across the board.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hey this was going pretty well right? I see the old e2e errors in there but apart from that, it validated right?

**Comment by Pike** [comment]
Yeah, but much of the backstage config goes back to https://github.com/spotify/web-scripts/tree/master/packages. That claims to be OK with >=v5, but I have no idea how honest that assessment is.

Marking this ready for review, as yes, it passed on the backstage codebase.

**Review by tudi2d — APPROVED** [review]
I think this definitly make sense. Looking at our customisation & [`web-scripts`](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#updated-configuration-rules) it seems like the breaking changes do not affect the configuration (neither here nor in `web-scripts`). Still we might be affected by [changed default rules](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/#updated-configuration-rules).

Agree with @Pike that I'm not totally confident this does not have any unintended side effects, but it is also super hard to test (especially when nothing is failing). If this unblocks bugs like [this one](https://github.com/backstage/backstage/issues/20144) it might be worth a try.

**Review by freben — APPROVED** [review]
Thanks!

**Pull request merged**
