### PR TITLE
chore(microsite): Simplify and standardize plugin categories

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

After the plugin categories list was introduced in https://github.com/backstage/backstage/pull/17559 ( 🎉  ) , it helped elevate this metadata of the plugin categories more.

This PR now takes an opinionated approach to reduce the number of categories to better simplify them. Some vendors may feel they fit into other categories, and over time it may make sense to align these to something like [Digital.ai's Periodic Table of DevOps Tools](https://digital.ai/learn/devops-periodic-table/), but for now this is my stab at reducing their complexity.

| Before | After |
| --- | --- |
|  image | image |

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — APPROVED** [review]
Love this! 👏

**Comment by efenner-cambia** [comment]
Should there be an addition to the [documentation for adding a plugin to the marketplace](https://backstage.io/docs/plugins/add-to-marketplace) outlining the new categories to help guide new plugin additions to sick to this standard?

**Comment by adamdmharvey** [comment]
@efenner-cambia Makes a lot of good sense!  In some way, over time I feel like it should almost be a lint rule because expecting the open source community to all read the instructions and follow a manual list of categories might be tough, but it would be a great start!  Would you be willing to add that?  Not sure there even *is* a defined list yet, but it could be a chance to better structure it.

**Comment by efenner-cambia** [comment]
@adamdmharvey I don't know how one would go about adding a lint rule, but I could raise a PR to update docs

**Pull request merged**
