### PR TITLE
integrations,backend-common: Fix azure URL parsing and readTree/search

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

This fixes a couple of issues with our Azure integration:

* Repo URLs can be both on the form owner/project/_git/repo and owner/_git/project, we typically only supported the former
* Our generated API URLs didn't pin the api-version, leading to possible breakages in the future
* We used `parseGitUrl` in many places, which doesn't handle Azure DevOps Server (on-prem)
* When downloading a zip archive with readTree while using a subpath the zip archive would contain an extra directory that needs to be stripped away

For now the `AzureUrl` utility class isn't exported, but we could consider doing that in the future.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Nice work! Was gonna take a look at this in the afternoon, just got filled in on the details from yesterday. Is there something wrong with the transformer in `jest` not using the right version of typescript or something here?

**Comment by Rugvip** [comment]
@benjdlambert ah yeah needs a workaround I think 😅

**Comment by benjdlambert** [comment]
Does this still need the changes from #7086?

**Comment by benjdlambert** [comment]
Nevermind sorry was at the top of the PR https://github.com/backstage/backstage/pull/7134/files#diff-b693fd64d0142735a5fe5d0fd9cbd4f1aa652e7360203cee80de8c9e2a04c584R143

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
