### PR TITLE
forward classes rules to card header

### PR DESCRIPTION
**Pull request by ryanvazquez**
## Hey, I just made a Pull Request!

`InfoCard` accepts a `headerProps` prop, which it forwards to the underlying MUI `CardHeader` component via the `withStyles` HOC.

In order to apply custom styles to underlying MUI CardHeader component from a component using `InfoCard`, a `class` prop needs to be defined with custom rules.

However using `makeStyles` to generate the `classes` prop generates the following error when it is passed via `headerProps`: 

`react_devtools_backend.js:2273 Material-UI: the key `action` provided to the classes prop is not implemented in WithStyles(ForwardRef(CardHeader)).
You can only override one of the following: title,subheader.`

Example:

```
 const useStyles = makeStyles(() =>
  createStyles({
    action: {
      margin: 0
    }
  })
)

 const classes = useStyles();

  const headerProps = {
    classes: classes, 
    action: <Component />
  };

  return (
    <InfoCard headerProps={headerProps}>
    [...]
    </InfoCard>
```

The `withStyles` HOC sets default rules for `title` and `subtitle`, however, additional rules specified on the `classes` prop are not recognized by MUI, which triggers the error.

This PR removes the HOC and applies default css rules to `BoldHeader` using `makeStyles` and optional rules on the `classes` prop, if it exists.

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by Nek — APPROVED** [review]
👍 great fix!

**Review by freben — APPROVED** [review]

**Comment by ryanvazquez** [comment]
Implemented some changes based on @Rugvip's feedback.

Note I added some additional fields to the classes prop, which should allow users to override these fields without generating MUI errors.

```
const useBoldHeaderStyles = makeStyles(theme =>
  createStyles({
    title: {
      fontWeight: 700,
    },
    subheader: {
      paddingTop: theme.spacing(1),
    },
    root: {},
    avatar: {},
    action: {},
    content: {},
  })
);
```


I encountered a strange TS bug where the MUI CardHeader component would not accept its own props.

The `title` prop on `InfoCard` is declared with the `ReactNode` type, which matches its corresponding type on `CardHeaderProps`, however this generates an inline TS error. The error disappears when this type is picked directly from `CardHeaderProps`

For example:

```
// InfoCard.ts
import { CardHeaderProps } from '@material-ui/core';

type Props = {
  title?: ReactNode; 
  subheader?: ReactNode;
  headerProps?: CardHeaderProps;
  headerStyle?: object;
  ...
}:

[...]

<BoldHeader
  className={classes.header}
  title={title} // TS will generate an error stating "number" is not assignable to ReactNode
  subheader={subheader}
  style={{ display: 'inline-block', ...headerStyle }}
  {...headerProps}
/>
```

**Comment by Nek** [comment]
@Rugvip Hey. We definitely need your help on this one. Some weird sorcery is going on here. Or maybe someone else with deeper knowledge of TS can help. I couldn't fix it on the level of backstage code and thinks it is either but in TS itself or messed up material-ui typings (though I didn't see anything suspicious).

**Comment by Rugvip** [comment]
Pushed a possible fix. It also rewires how classes are forwarded to the header, and allows you to override header styles straight through the `classes` prop.

It still doesn't behave correctly if you try to pass a title through the `headerProps`, and probably some of the other generic stuff there. For that level of customization it's better to just wire up a custom card though tbh.

**Review by stefanalund — APPROVED** [review]

**Comment by stefanalund** [comment]
There seems to be an interesting side-effect (?) to how an InfoCard is laid out in a grid:

Now (distance between cards in the left column):

Screenshot 2020-09-08 at 16 39 38

Before: https://backstage.io/storybook/?path=/story/example-plugin--plugin-with-data

**Comment by Rugvip** [comment]
Yeah seeing some weird issues too, gonna merge in master to investigate, branch is gonna get messy :p

**Comment by Rugvip** [comment]
Hmm, looks identical before and after this change locally, might be some weirdness with this branch being old. Pushed the merge and letting it rebuild to see

**Comment by freben** [comment]
@stefanalund is the spacing really different? i thought maybe it was a matter of (1) different screen sizes, and (2) the new storybook having more text content in the right side which pushes down the gauge cards that are "centered" in their space?

**Comment by stefanalund** [comment]
Now Chromatic (UI tests) seems happy...hmm, not sure I fully trust that service just yet. Anyway, this seems good to go! Thanks @ryanvazquez for your patience 😏

**Comment by freben** [comment]
@Rugvip is right, that the branch was old and the storybooks had been changed in master since this PR was made

**Comment by Rugvip** [comment]
@stefanalund I think it's (incorrectly?) comparing the root where this branch and master intersects, with the PR build, which is this branch merged into master. Basically it seems to leave out all changes that were added to master since this PR was opened.

**Pull request merged**
