### PR TITLE
docs(tech-insights-backend): fix CHANGELOG.md typo

### PR DESCRIPTION
**Pull request by colinrymer**
## Hey, I just made a Pull Request!

This fixes a simple typo in the `tech-insights-backend` CHANGELOG.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
@colinrymer this needs a changeset in order for the Readme to be updated on npm.

**Review by Rugvip — APPROVED** [review]
Thanks! 👍

**Comment by Rugvip** [comment]
Ah, figure it's alright to ship this without changeset because github is the place you see changelogs anyway

**Comment by jhaals** [comment]
> Ah, figure it's alright to ship this without changeset because github is the place you see changelogs anyway

Oh yes I confused it with the Readme. My bad :)

**Pull request merged**
