### PR TITLE
Update wording in user-settings README to clarify example location

### PR DESCRIPTION
**Pull request by darylgraham**
## Hey, I just made a Pull Request!

The README for the `user-settings` plugin referenced an example screen in the Demo app, where it was linking to the example app in the main Backstage repository.

Discord link for more details: https://discord.com/channels/687207715902193673/1279569368875008176/1280616399256948971 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@darylgraham this needs a changeset too, you can fix by running `yarn changeset` and selecting the correct package and `patch` bump :tada:

**Review by camilaibs — APPROVED** [review]
🙏🏻

**Comment by darylgraham** [comment]
> @darylgraham this needs a changeset too, you can fix by running `yarn changeset` and selecting the correct package and `patch` bump 🎉

@benjdlambert is a change set needed for this? The contributing guide says they aren’t needed for changes that do not affect code.

> Changesets are also not needed for changes that do not affect the published version of each package, for example changes to tests or in-line source code comments.

Happy to create one, just wanted to be sure of the process.

**Comment by benjdlambert** [comment]
Yeah, in order to update the readme in places like https://npmjs.com/package/@backstage/plugin-user-settings then it needs a release to be triggered.

**Comment by darylgraham** [comment]
Thanks @benjdlambert now I understand. Changeset added.

**Comment by benjdlambert** [comment]
@darylgraham sorry, also need to DCO sign that last commit too. [some more info here](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin)

**Comment by darylgraham** [comment]
Sorry, I thought I had all of my commits being signed off. Not sure how that one got through.

**Comment by awanlin** [comment]
> > @darylgraham this needs a changeset too, you can fix by running `yarn changeset` and selecting the correct package and `patch` bump 🎉
> 
> @benjdlambert is a change set needed for this? The contributing guide says they aren’t needed for changes that do not affect code.
> 
> > Changesets are also not needed for changes that do not affect the published version of each package, for example changes to tests or in-line source code comments.
> 
> Happy to create one, just wanted to be sure of the process.

@darylgraham this made me LOL as this is mentioned in the paragraph just below the one you quoted here 🤣

**Review by awanlin — APPROVED** [review]
Thanks for clarify this @darylgraham, much better! 🚀

**Comment by darylgraham** [comment]
> > > @darylgraham this needs a changeset too, you can fix by running `yarn changeset` and selecting the correct package and `patch` bump 🎉
> > 
> > 
> > @benjdlambert is a change set needed for this? The contributing guide says they aren’t needed for changes that do not affect code.
> > > Changesets are also not needed for changes that do not affect the published version of each package, for example changes to tests or in-line source code comments.
> > 
> > 
> > Happy to create one, just wanted to be sure of the process.
> 
> @darylgraham this made me LOL as this is mentioned in the paragraph just below the one you quoted here 🤣

Argh! I just went back to check - sure enough, I had read the first part of the next paragraph and just blanked on the sentence that specifically mentions the readme file. Gah! Thankfully you guys are here to pick up my mistakes while I’m learning all this stuff 😂

**Pull request merged**
