### PR TITLE
chore: update git-url-parse dependency

### PR DESCRIPTION
**Pull request by benjdlambert**
Update dependency in the project as follow on from: #3609

### CODE REVIEW

**Comment by freben** [comment]
he mentioned wanting to rewrite that test mentioned in the previous PR using a full URL instead, could we do that at the same time?

**Comment by lykims** [comment]
Hi @benjdlambert !

Could you:
- fix this TODO: https://github.com/backstage/backstage/blob/master/packages/integration/src/bitbucket/core.test.ts#L147;
- replace the four lines at https://github.com/backstage/backstage/blob/master/packages/integration/src/bitbucket/core.test.ts#L165 for 
```
expect(result).toEqual(
  'https://api.bitbucket.mycompany.net/rest/api/1.0/projects/backstage/repos/mock/archive?format=zip&at=main&prefix=backstage-mock',
);
```
- remove `?at=main` (I accidentally slipped it in there) at https://github.com/backstage/backstage/blob/master/packages/integration/src/bitbucket/core.test.ts#L162?

**Comment by benjdlambert** [comment]
Yep sure - got a few meetings at the min but will get round to it today!

**Comment by benjdlambert** [comment]
@lykims care to 👍 ?

**Review by lykims — APPROVED** [review]
looks good to me! 👏

**Review by Rugvip — APPROVED** [review]

**Review by OrkoHunter — APPROVED** [review]

**Review by freben — APPROVED** [review]

**Pull request merged**
