### PR TITLE
changed svgIcon to JSX.element to accept both icons and avatar

### PR DESCRIPTION
**Pull request by majd-asab**
## Hey, I just made a Pull Request!

Changed the SvgIcon type to JSX.Element to allow instantiation of either Icon or Avatar
  
#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by stefanalund** [comment]
Fails with the following error:
```
/home/runner/work/backstage/backstage/packages/app/src/components/Root/Root.tsx
69
[yarn start].out: TypeScript error in /home/runner/work/backstage/backstage/packages/app/src/components/Root/Root.tsx(81,25):
70
[yarn start].out: Type 'OverridableComponent<SvgIconTypeMap<{}, "svg">>' is not assignable to type 'Element'.  TS2322
71
[yarn start].out: 
72
[yarn start].out:     79 |       <SidebarSpacer />
73
[yarn start].out:     80 |       <SidebarDivider />
74
[yarn start].out:   > 81 |       <SidebarItem icon={HomeIcon} to="/" text="Home" />
75
[yarn start].out:        |                         ^
76
[yarn start].out:     82 |       <SidebarItem icon={AccountCircle} to="/login" text="Login" />
77
[yarn start].out:     83 |       <SidebarDivider />
78
[yarn start].out:     84 |       <SidebarSpace />
```

**Comment by Rugvip** [comment]
Discussed this a bit more today, along with the initial approach in https://github.com/spotify/backstage/pull/538. I'm thinking it's best we allow the consumers of icons to be responsible for the styling / layout of them.

We discussed the possibility of converting avatar urls into icon-compatible components on the fly with a function, which could be interesting to explore.

Another approach that I think would be a bit quicker and unblock you is to create a `SidebarAvatarItem` component for use with avatars.

**Review by Rugvip — COMMENTED** [review]
Discussed this a bit more today, along with the initial approach in https://github.com/spotify/backstage/pull/538. I'm thinking it's best we allow the consumers of icons to be responsible for the styling / layout of them.

We discussed the possibility of converting avatar urls into icon-compatible components on the fly with a function, which could be interesting to explore.

Another approach that I think would be a bit quicker and unblock you is to create a `SidebarAvatarItem` component for use with avatars.

**Comment by majd-asab** [comment]
> Discussed this a bit more today, along with the initial approach in #538. I'm thinking it's best we allow the consumers of icons to be responsible for the styling / layout of them.
> 
> We discussed the possibility of converting avatar urls into icon-compatible components on the fly with a function, which could be interesting to explore.
> 
> Another approach that I think would be a bit quicker and unblock you is to create a `SidebarAvatarItem` component for use with avatars.

Speaking explicitly regarding having an avatar for authentication, a whole component just for the having a picture instead of a "user icon" seems a bit of an over kill? especially when there is a  by simply passing a url which would act as a flag to override the user icon, and replace it with the user avatar. Unless there is more to it?

**Comment by Rugvip** [comment]
@majd-asab The profile item is likely gonna be expanded to support multiple oauth providers, and settings/help/about menus. Having a separate component for that is gonna be needed anyway.

**Comment by freben** [comment]
Hi! What's the status of this? Could we help you in any way?

**Comment by stefanalund** [comment]
Maybe this PR is replaced by https://github.com/spotify/backstage/pull/589 

Should we close?

**Comment by stefanalund** [comment]
Closing for now. Let us know if you disagree 😏

**Pull request closed without merging**
