### PR TITLE
Update PagerDuty Plugin Doc

### LINKED ISSUE #5510: pagerduty: Add screenshots to documentation
## Summary

It would be great to add some screenshots of the current PagerDuty plugin to its README here:

https://github.com/backstage/backstage/blob/master/plugins/pagerduty/README.md

Specifically, it says it has three features.  Would be awesome to have one screen shot of each to better understand how it can be used.

### PR DESCRIPTION
**Pull request by jamesrenaud**
## Hey, I just made a Pull Request!

Added screenshots to the PagerDuty plugin documentation.

Fixes #5510

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by adamdmharvey — APPROVED** [review]
Looks awesome; thx!

Note: your inclusion of what I guess are tool tips (i.e., 'title=' values?) inside of markdown link parenthesis seems to be throwing off the CI check of valid links.

Is that valid Markdown, or maybe a specific flavor of  Markdown?  Not something I've seen before, but thinking either they should be removed or we may have to re-write the link checker to support this type of inclusion.... hmm.

**Comment by jamesrenaud** [comment]
@adamdmharvey it is valid markdown for Github (see https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images), it shows in tooltips and as the alternate text for an image if the image can't load. Works well for accessibility for screenreaders. I can remove it for now, but would be good to support the accessibility aspect of alt-text for the images.

**Comment by freben** [comment]
@jamesrenaud Hmm isn't the link text itself (`[View Open Incidents]` for example) already used as the alt text?

**Comment by freben** [comment]
Yeah at least the `alt` attribute does get populated this way. https://guides.github.com/features/mastering-markdown/ You can see it in action in the image example

**Comment by adamdmharvey** [comment]
I think title is different than alt txt, no?  alt text shows when the image can't display, vs. title shows on tool tip hover when the image DOES display.  I think bottom line is the current link checker seems to not support it :) so either it gets removed, or the link checker maybe needs refactoring.

Maybe here?

https://github.com/backstage/backstage/blob/a9697e61073b32bde50a6b6adc13c5295f4a39b3/scripts/verify-links.js#L111-L122

**Comment by jamesrenaud** [comment]
@freben is right, the alt text for accessibility is populated from the title as opposed to the tooltip text. I think it's fair to remove it as it's not serving any useful purpose.

It may be worth based on this still being valid Github flavoured markdown to modify the link parser, but it can be a low priority backlog item.

**Comment by freben** [comment]
Looking good! I just slapped a changeset on it as well since the readme affects the published package on npm. Waiting for it to go green and then we're good to go 👍

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
