### PR TITLE
CLI: have module federation settings take in account all the exports defined in the `package.json`

### PR DESCRIPTION
**Pull request by davidfestal**
## Hey, I just made a Pull Request!

This PR enhances the behavior of the experimental support for module federation in the backstage CLI:
Until now exposed modules are a fixed value set to `src/index`.
With this PR, in the case of a remote container (not the main application), would add also look into the `package.json` of the built package, for an `exports` entry and, if it exists, use it to include alternate imports (like `./alpha`) into the  module federation exposed modules.
The change is compatible with the existing behavior, but only fixes the existing limitation that, for example, prevented accessing the `alpha` definitions in the module federation scenario.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by davidfestal** [comment]
Any idea whether this pretty simple and straightforward PR could get some review soon ?
cc @christophe-f

**Review by freben — APPROVED** [review]
Looks good to me - @Rugvip for final check?

**Review by Rugvip — CHANGES_REQUESTED** [review]
Hmm, is it specifically things like `/alpha` that you're looking to make available? As in additional entry points that have features we'd want to load.

I think it's best to rely on the feature discovery for this, see https://github.com/backstage/backstage/blob/d849865b6fafdf7d7c8eb5b96e7d5fd933105e16/packages/cli/src/lib/packager/productionPack.ts#L177-L193. That way we can make sure we only include actual features in the remote bundle, rather than entry points like `/testUtils` or `/package.json`.

**Comment by davidfestal** [comment]
> Hmm, is it specifically things like `/alpha` that you're looking to make available? As in additional entry points that have features we'd want to load.
> 
> I think it's best to rely on the feature discovery for this, see
> 
> https://github.com/backstage/backstage/blob/d849865b6fafdf7d7c8eb5b96e7d5fd933105e16/packages/cli/src/lib/packager/productionPack.ts#L177-L193
> 
> . That way we can make sure we only include actual features in the remote bundle, rather than entry points like `/testUtils` or `/package.json`.

Thanks for the pointer, I'm looking into it.

**Comment by davidfestal** [comment]
> > Hmm, is it specifically things like `/alpha` that you're looking to make available? As in additional entry points that have features we'd want to load.
> > I think it's best to rely on the feature discovery for this, see
> > https://github.com/backstage/backstage/blob/d849865b6fafdf7d7c8eb5b96e7d5fd933105e16/packages/cli/src/lib/packager/productionPack.ts#L177-L193
> > 
> > . That way we can make sure we only include actual features in the remote bundle, rather than entry points like `/testUtils` or `/package.json`.
> 
> Thanks for the pointer, I'm looking into it.

@Rugvip I added commit c8dbf11b814a8286a2576d0bcd9e602212125c6d? Is it what you were expecting ?

**Comment by davidfestal** [comment]
@Rugvip Any other review comment apart from the one I fixed ? The merging is still blocked by requested changes.

**Pull request merged**
