### PR TITLE
[GitlabDiscoveryEntityProvider] - entityFilename wildcard support

### PR DESCRIPTION
**Pull request by goququ**
## Hey, I just made a Pull Request!

Now it's mandatory to pass existing file to provider config, it would be nice if we can pass pattern with wildcard to match entities with UrlLoader for a more efficient discovery process. ([according this advice](https://github.com/backstage/backstage/issues/8232#issuecomment-980128488))

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by goququ** [comment]
@Rugvip hello, could you help me, what's wrong with docs quality check?

**Review by Rugvip — CHANGES_REQUESTED** [review]
Nice, thank you! 👍

**Comment by benjdlambert** [comment]
@nlamirault this was closed as no response from author. Would you like to pick up the rest of the comments here maybe? 🙏

**Comment by armindocachada** [comment]
What Happened to this changed? It seems like it was never merged. 
I am trying to use Gitlab Discovery and having the wildcards working is needed since we have more than one component in the same repo.

**Pull request closed without merging**
