### PR TITLE
fix: remove async imports

### PR DESCRIPTION
**Pull request by marcpalm**
## Hey, I just made a Pull Request!

Proposed solution for https://github.com/backstage/backstage/issues/24864

How to test:

1. add to `packages/app/package.json` in devDependencies
```json
    "@vitejs/plugin-react": "^4.0.4",
    "cross-env": "^7.0.0",
    "vite": "^4.4.9",
    "vite-plugin-html": "^3.2.0",
    "vite-plugin-node-polyfills": "^0.21.0"
```
2. Run `yarn` from the root
3. Run `EXPERIMENTAL_VITE=true yarn workspace example-app start`

The error is only reproducible in https://github.com/backstage/demo

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
I'm not sure we want to do this yet. Would mean that we would have to ship the `vite` dependencies with the CLI even if you're not using it which is not a great experience when it duplicates a lot of versions.

It could be the actual fix for this error message might be something like this: https://github.com/remix-run/remix/pull/6562

**Comment by marcpalm** [comment]
> I'm not sure we want to do this yet. Would mean that we would have to ship the `vite` dependencies with the CLI even if you're not using it which is not a great experience when it duplicates a lot of versions.
> 
> It could be the actual fix for this error message might be something like this: [remix-run/remix#6562](https://github.com/remix-run/remix/pull/6562)

Not this is a conditional import, not an unconditional import like top level.

**Comment by marcpalm** [comment]
> I'm not sure we want to do this yet. Would mean that we would have to ship the `vite` dependencies with the CLI even if you're not using it which is not a great experience when it duplicates a lot of versions. 

No, this is a conditional import, not an unconditional import like at the top level of a file.


> I'm also not sure how this would actually even fix the issue.

The problem is that `import(...)` does not correctly resolve (my guess). This fixes this. 

> It could be the actual fix for this error message might be something like this: [remix-run/remix#6562](https://github.com/remix-run/remix/pull/6562)

I would be surprised. Vite was working before for us, we upgraded to the new backend system, and it stopped working for us.

**Comment by marcpalm** [comment]
I added a description how to test, but the error is not reproducible here, only in https://github.com/backstage/demo.

Can somebody please trigger a nightly build, then I can test this with the demo-site? I have only tested this with dist folder in the node_modules yet ;-)

**Comment by benjdlambert** [comment]
Backing up a bit here, I guess I wanna work out why this doesn't work in the demo site when you add the `vite` dependencies, but the same code works in this repo. My guess is that it's something to do with some dependencies in `packages/app` that are being loaded in the demo site but not in the main repo, or it's some mismatch in the `vite` packages?

`@asyncapi/parser` seems to be a dependency on `@backstage/plugin-api-docs`, but that seems to be used in both places, so it's all very strange.

```
[0] Loaded config from app-config.yaml
[0]
[0]  WARN  files in the public directory are served at the root path.
[0] Instead of /public/index.html, use /index.html.
[0]
[0] ✘ [ERROR] No matching export in "../../node_modules/node-stdlib-browser/esm/mock/empty.js" for import "readFile"
[0]
[0]     ../../node_modules/@asyncapi/parser/esm/from.js:10:9:
[0]       10 │ import { readFile } from 'fs';
[0]          ╵          ~~~~~~~~
```

I put together a fix for the demo site without using `require`, which happens to be pretty similar to the code we're using internally as we had some problems with the polyfills before. You might be able to use the same `yarn patch` method to test your changes there too, but to be honest I don't understand how that even fixes it. `await import` and `require` should load the same code that gets executed, and the problem is in the produced code that `vite` produces, nothing to do with the imports before `vite` is even run, so that's got me confused.

**Comment by marcpalm** [comment]
> Backing up a bit here, I guess I wanna work out why this doesn't work in the demo site when you add the `vite` dependencies, but the same code works in this repo. My guess is that it's something to do with some dependencies in `packages/app` that are being loaded in the demo site but not in the main repo, or it's some mismatch in the `vite` packages?
> 
> `@asyncapi/parser` seems to be a dependency on `@backstage/plugin-api-docs`, but that seems to be used in both places, so it's all very strange.
> 
> ```
> [0] Loaded config from app-config.yaml
> [0]
> [0]  WARN  files in the public directory are served at the root path.
> [0] Instead of /public/index.html, use /index.html.
> [0]
> [0] ✘ [ERROR] No matching export in "../../node_modules/node-stdlib-browser/esm/mock/empty.js" for import "readFile"
> [0]
> [0]     ../../node_modules/@asyncapi/parser/esm/from.js:10:9:
> [0]       10 │ import { readFile } from 'fs';
> [0]          ╵          ~~~~~~~~
> ```
> 
> I [put together a fix for the demo site](https://github.com/backstage/demo/compare/blam/test-vite-fix?expand=1#diff-6de0e011d48e4378489674ffc5726276f9bf56c6f6b8f6d2455c05f6d9655f64R285-R306) without using `require`, which happens to be pretty similar to the code we're using internally as we had some problems with the polyfills before. You might be able to use the same `yarn patch` method to test your changes there too, but to be honest I don't understand how that even fixes it.
> 
> EDIT: I've just had a thought looking at the stack trace that it's loading the `esm` exports for the `stdlib-browser` polyfill. I wonder if that's different between the demo site and this repo.

This does not quick work and results in 

```sh
╭─... ~/repos/backstage/demo ‹blam/test-vite-fix●› 
╰─$ EXPERIMENTAL_VITE=true yarn workspace app start
Loaded config from app-config.yaml

 WARN  files in the public directory are served at the root path.                               13:16:10
Instead of /public/index.html, use /index.html.

 WARN  1:16:10 PM [vite] Failed to load source map for /@fs/Users/palm/repos/backstage/demo/node_modules/graphiql/graphiql.css.
```

**Comment by marcpalm** [comment]
> > Backing up a bit here, I guess I wanna work out why this doesn't work in the demo site when you add the `vite` dependencies, but the same code works in this repo. My guess is that it's something to do with some dependencies in `packages/app` that are being loaded in the demo site but not in the main repo, or it's some mismatch in the `vite` packages?
> > `@asyncapi/parser` seems to be a dependency on `@backstage/plugin-api-docs`, but that seems to be used in both places, so it's all very strange.
> > ```
> > [0] Loaded config from app-config.yaml
> > [0]
> > [0]  WARN  files in the public directory are served at the root path.
> > [0] Instead of /public/index.html, use /index.html.
> > [0]
> > [0] ✘ [ERROR] No matching export in "../../node_modules/node-stdlib-browser/esm/mock/empty.js" for import "readFile"
> > [0]
> > [0]     ../../node_modules/@asyncapi/parser/esm/from.js:10:9:
> > [0]       10 │ import { readFile } from 'fs';
> > [0]          ╵          ~~~~~~~~
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I [put together a fix for the demo site](https://github.com/backstage/demo/compare/blam/test-vite-fix?expand=1#diff-6de0e011d48e4378489674ffc5726276f9bf56c6f6b8f6d2455c05f6d9655f64R285-R306) without using `require`, which happens to be pretty similar to the code we're using internally as we had some problems with the polyfills before. You might be able to use the same `yarn patch` method to test your changes there too, but to be honest I don't understand how that even fixes it.
> > EDIT: I've just had a thought looking at the stack trace that it's loading the `esm` exports for the `stdlib-browser` polyfill. I wonder if that's different between the demo site and this repo.
> 
> This does not quick work and results in
> 
> ```shell
> ╭─... ~/repos/backstage/demo ‹blam/test-vite-fix●› 
> ╰─$ EXPERIMENTAL_VITE=true yarn workspace app start
> Loaded config from app-config.yaml
> 
>  WARN  files in the public directory are served at the root path.                               13:16:10
> Instead of /public/index.html, use /index.html.
> 
>  WARN  1:16:10 PM [vite] Failed to load source map for /@fs/Users/palm/repos/backstage/demo/node_modules/graphiql/graphiql.css.
> ```

**Comment by marcpalm** [comment]
Edit: Both patches - yours and mine - seem to work, the above warning can be ignored.

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
