### PR TITLE
Seems that the cypress tests does not work correctly

### PR DESCRIPTION
**Pull request by pbnPierre**
## Hey, I just made a Pull Request!

It seems that when the upgrade to cypress 10 were made the config files were not updated

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by djamaile** [comment]
Hi! @pbnPierre seems there was a issue with the changeset bot. Can you rebase from master so that the bot will spamming your PR? 🙏

**Comment by pbnPierre** [comment]
Yes I will thanks

**Comment by djamaile** [comment]
It seems good now, thanks! @pbnPierre

**Comment by pbnPierre** [comment]
Seems my linter issue also

**Comment by pbnPierre** [comment]
Not really sure what i should put in the changeset to be honnest

**Comment by jhaals** [comment]
Thanks for the PR!
I was not aware that we had cypress tests being broken, where/how are they failing currently?

**Comment by pbnPierre** [comment]
I think they even are note launched because it did not failed. But Cypress > 10.x does not support cypress.json configuration files anymore. We have tu use a `cypress.config.ts`
I saw this here

https://docs.cypress.io/guides/references/configuration

seems that there is one also on the root of the folder i forgot.

**Comment by pbnPierre** [comment]
Seems that the `integrationFolder` is legacy configuration also.
I'm wondering now are they actually runned ?

**Comment by pbnPierre** [comment]
I tried to update also the cypress/cypress.json also let's see what it does

**Comment by pbnPierre** [comment]
If i'm not mistaken, I dont see the command `"test:cypress": "cypress open"` used in CI

**Comment by pbnPierre** [comment]
Oh there are three more
```find . -name "cypress.json"
./packages/techdocs-cli-embedded-app/cypress.json
./packages/techdocs-cli/cypress.json
./packages/create-app/templates/default-app/packages/app/cypress.json```

**Comment by pbnPierre** [comment]
Seems that someone is also on it https://github.com/backstage/backstage/pull/15368

**Comment by pbnPierre** [comment]
`./packages/create-app/templates/default-app/packages/app/cypress.json` this one is in a template with cypress 9.7 so seems ok

**Comment by pbnPierre** [comment]
the last one is more touchy `./packages/techdocs-cli/cypress.json`

**Comment by pbnPierre** [comment]
@jhaals could i have some advice to what i should do with this ? Do you have inputs

I see some cypress refrences in github actions yaml 
```
      - name: cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_baseUrl: ${{steps.get-status-env.outputs.result}}
        with:
          config-file: ./cypress.json
          working-directory: ./cypress
          browser: chrome
          install: false
          headless: true
```

but nor reat `cy:run` executed elsewhere and the config-file seems not good though

**Comment by jhaals** [comment]
I don't think cypress is used any longer for app(packages/app). The only references I can find only point to https://github.com/backstage/backstage/blob/master/.github/workflows/verify_e2e-tugboat.yml which is no longer in use and should probably be removed. I know @benjdlambert worked on this previously and might be able to speak to the usage of the cypress today

**Comment by pbnPierre** [comment]
I can remove all trace of cypress everywhere if you want in this PR.

**Comment by pbnPierre** [comment]
Seems a lot of work though. I can leave it to you also. Shame i could not officially contritube to backstage using my professionnal mail @deezer.com :D

**Comment by jhaals** [comment]
There's clearly some overlap with https://github.com/backstage/backstage/pull/15368 currently. I'd suggest we make sure that we separate the techdocs related tests from the other cypress tests. I was not able to run the tests from the cypress folder checking out the branch

```
CYPRESS_baseUrl="http://demo.backstage.io" yarn cypress run                                                                                                                       1s [11:33:32] 

Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
There were multiple support files found matching your supportFile pattern.

Your supportFile is set to: ./src/support

We found the following files:

 - /Users/jhaals/src/backstage/cypress/src/support/commands.ts
 - /Users/jhaals/src/backstage/cypress/src/support/index.ts

Please remove or combine the support files into a single file.
```

**Pull request closed without merging**
