### PR TITLE
Add missing commas to app-custom-theme docs

### PR DESCRIPTION
**Pull request by vicsufer**
Signed-off-by: Víctor Suárez Fernández <vicsufer@gmail.com>

## Hey, I just made a Pull Request!

Just add missing commas to the example which I noticed while copy-pasting.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Fox32** [comment]
Haha, thanks that was on my todo list!

**Review by freben — APPROVED** [review]

**Review by Rugvip — APPROVED** [review]
:grin: 👍

**Comment by vicsufer** [comment]
Running `prettier` locally I get the following diff in the same file, however they seem to be not related with the content of this PR, should I commit this change too?
It seems to be the classic tabs vs spaces :smile: 
```
@@ -123,15 +123,15 @@ const themeOptions = createThemeOptions({
   fontFamily: 'Comic Sans',
   /* below drives the header colors */
   pageTheme: {
-    home: genPageTheme(['#123456','#123456'], shapes.wave),
-    documentation: genPageTheme(['#123456','#123456'], shapes.wave2),
-    tool: genPageTheme(['#123456','#123456'], shapes.round),
-    service: genPageTheme(['#123456','#123456'], shapes.wave),
-    website: genPageTheme(['#123456','#123456'], shapes.wave),
-    library: genPageTheme(['#123456','#123456'], shapes.wave),
-    other: genPageTheme(['#123456','#123456'], shapes.wave),
-    app: genPageTheme(['#123456','#123456'], shapes.wave),
-    apis: genPageTheme(['#123456','#123456'], shapes.wave),
+    home: genPageTheme(['#123456', '#123456'], shapes.wave),
+    documentation: genPageTheme(['#123456', '#123456'], shapes.wave2),
+    tool: genPageTheme(['#123456', '#123456'], shapes.round),
+    service: genPageTheme(['#123456', '#123456'], shapes.wave),
+    website: genPageTheme(['#123456', '#123456'], shapes.wave),
+    library: genPageTheme(['#123456', '#123456'], shapes.wave),
+    other: genPageTheme(['#123456', '#123456'], shapes.wave),
+    app: genPageTheme(['#123456', '#123456'], shapes.wave),
+    apis: genPageTheme(['#123456', '#123456'], shapes.wave),
   },
 });
 ```

```

**Comment by freben** [comment]
Sounds good to me :)

**Pull request merged**
