### PR TITLE
expose Content of EntityValidationPage.tsx in new Component EntityVal…

### PR DESCRIPTION
**Pull request by julianEbenhoferDyna**
## Hey, I just made a Pull Request!

Added a new component EntityValidationContent to expose the content of the EntityValidationPage

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by julianEbenhoferDyna** [comment]
Hey @camilaibs @freben, 
I noticed that 4 checks for my pull request have failed due to a 503 Service unavailable error:
```
 - Verify 16.x
 - Verify 18.x
 - Test 16.x
 - Test 18.x
```

Would a re-run fix these checks? If yes, could you please re-run the workflow?
Thanks! 👍

**Comment by freben** [comment]
Hey! What was the end goal here? Did you just want to change the title of the page or something like that?

**Comment by julianEbenhoferDyna** [comment]
Hey @freben, we would like to add additional content to the page.

**Comment by freben** [comment]
Hm OK. This one is not super nicely composable in the first place, but I guess this isn't all too controversial. Note though that we generally don't review until the submitter has cleaned up the PR and the builds are overall green etc. You'll see that your CI is red.

**Pull request closed without merging**
