### PR TITLE
Add Search bar to TechDocs when displayed in the entity tab

### PR DESCRIPTION
**Pull request by grantila**
## Add the TechDocs search bar to the "Docs" entity page tab

This PR fixes the issue #23004.

The search bar inside TechDocs is only rendered when viewing docs in `/docs/x/y/z/*`, not when viewing the same docs in `/catalog/x/y/z/docs/*`. The reasoning is likely what's written in #23004 i.e. that the search results locations go to `/docs/*` which would be a surprising result to users (being routed to a completely different view/part of Backstage).

This PR adds the search bar, and re-routes the locations when displayed in the entity page, from `/docs/x/y/z/*` to `/catalog/x/y/z/docs/*`. The logic is a bit cumbersome, as one needs to use the route refs for both the root docs and the catalog docs pages, and figure out how to re-route based on that. `useRouteRef` will throw when used in a component from where the ref isn't mounted, so this needs conditional hooks, which is generally a bad idea. However, these two pages (and their components) have totally different parent hierarchy, so they won't (from what I can tell after some manual testing) re-render with a different prop (`reRouteToCatalog`) and cause hook order mismatch. The solution works well from what I can tell.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by grantila** [comment]
Would anyone working on TechDocs be able to take a look at this? 🙏

**Comment by alexlorenzi** [comment]
Hey @grantila - Thanks for the PR, this is a great addition... In regards to the conditional hook, my only thought would be to update the [TechDocsSearchBar component](https://github.com/backstage/backstage/blob/55cd2fba0ba23585558e44dce1da020286f39b8f/plugins/techdocs/src/search/components/TechDocsSearch.tsx#L62) to instead take the location function (either the identity or the redirect one) and then create a new `TechDocsSearchWithRedirect` component below the existing [TechDocsSearch](https://github.com/backstage/backstage/blob/55cd2fba0ba23585558e44dce1da020286f39b8f/plugins/techdocs/src/search/components/TechDocsSearch.tsx#L161) component that passes in your new redirect function (without the try-catch now). Then update the [TechDocsReaderPageContent](https://github.com/backstage/backstage/pull/26706/files#diff-5a756e3ad25e8bb77aa1073db80056666c7fc500df1da463e2bef5db38bb53c4R69) to instead optionally take the Search Bar component as a parameter instead of the `redirectToEntityPage` boolean (and default it to the existing `TechDocsSearch` component)  and pass the new `TechDocsSearchWithRedirect` on the `EntityPageDocs`.

I know this introduces a new component into the wild, but it makes it should remove the hook confusion and also make it clearer if you add the wrong search bar to the wrong page. But interested to hear your thoughts on it too

**Review by alexlorenzi — COMMENTED** [review]
See note above

**Comment by grantila** [comment]
Sometimes you get lost in a new code base, you're absolutely right @alexlorenzi that hoisting the logic to the 
`EntityPageDocs` makes sense.

However, a custom component is tricky, as it needs props from within `TechDocsSearchBar` as well as the redirect function.

I solved it by allowing a custom `redirectUrl` prop, injected from `EntityPageDocs`, otherwise left `undefined`. It resolves the issue with conditional hooks and is a lot cleaner than before. Tested locally and search works fine, both from the entity page and the global `/docs` page.

**Comment by grantila** [comment]
@alexlorenzi please take a second look at this, it's working fine on my side. It's also rebased on latest master.

**Comment by squid-ney** [comment]
Hi @grantila, these updates look good! One small note, the team has some concerns with the variable name, `redirectUrl`. This could be confused with the `mkdocs-redirect` plugin functionality and the name implies a `string` type, but it is a function. For clarity, we were thinking something like `searchResultUrlMapper`, but open to suggestions.

**Comment by grantila** [comment]
Glad to be able to help @squid-ney. I see there are some error in the release process: https://github.com/procore-oss/backstage-plugin-announcements/actions/runs/12002387031/job/33454275718 making the publishing fail 🤔

**Pull request merged**
