### PR TITLE
Added description for each member in MembersListCard

### PR DESCRIPTION
**Pull request by awanlin**
Signed-off-by: Andre Wanlin <awanlin@rapidrtc.com>

## Hey, I just made a Pull Request!

Added the `metadata.description` to the bottom of each member on the MembersListCard. Here's what that looks like:

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
@AndyMcKenna FYI

**Comment by AndyMcKenna** [comment]
Awesome!

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks for this! :tada:

**Comment by awanlin** [comment]
@benjdlambert thanks for the review, approval, and merge. This will make a few people happy where I work :)

**Pull request merged**
