### PR TITLE
Recoverable tasks

### PR DESCRIPTION
**Pull request by acierto**
## Hey, I just made a Pull Request!

I would love to make Backstage less sensible for deployment restarts in terms of in-progress tasks. 
At the moment at every production redeployment I have to check that no user runs the template and only after that to proceed. 

"Luckily" there is not so many users running long-running templates at the moment, but with growing a user base and adding more automated templates which lessen the cognitive load of feature teams there can be a situation when some template is in progress, what makes us hinder to do deployment less often or after working hours. 
Therefore, having a mean which can restore the in-progress task automatically without any manual intervention will be an awesome help.

Of course, that some pre-conditions have to be made by template creators to achieve it. 
By default this feature is off and can be enabled per template and in different modes of recovery.

For the examples you can have a look at:

* https://github.com/acierto/software-templates/blob/main/scaffolder-templates/docs-mocks-template/template.yaml
* https://github.com/acierto/software-templates/blob/main/scaffolder-templates/docs-mocks-idempotent-template/template.yaml 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by andrewthauer** [comment]
TBH - This is also applicable to the `backend-tasks` service as well. There was a discussion in #6816 about having a more feature rich Background Jobs service in backstage that could handle queues, retries, etc. but this never really got anywhere.

We've internally needed to reach for this sort of thing a few times and I really feel that Backstage could benefit from something native that supports queues, retries, etc. as this is lacking in the built in TaskScheduler. The Catalog and Scaffolder also do similar things, but are not generalized to re-use.

I'm wondering if this should be hoisted up a level to a more general purpose problem then specific to the Scaffolder.

**Comment by acierto** [comment]
> TBH - This is also applicable to the `backend-tasks` service as well. There was discussion in #6816 about having a more feature rich Background Jobs service in backstage that could handle queues, retries, etc. but this never really got anywhere.
> 
> We've internally needed to reach for this sort of thing a few times and I really feel that Backstage could benefit from something native that supports queues, retries, etc. as this is lacking in the built in TaskScheduler. The Catalog and Scaffolder also do similar things, but are not generalized to re-use.
> 
> I'm wondering if this should be hoisted up a level to a more general purpose problem then specific to the Scaffolder.

Indeed, these features are really useful to have and the scaffolder is most visible to the users. 
https://github.com/backstage/backstage/issues/6816 - looks like an elephant in a room and initially addressed to solve slightly different problem by making the workers more scalable and spread the load.

What would be nice to help to push the train forward is to split the task to very small increments. 
Making tasks resilient can be a good step forward.

My solution is based on task/step idempotency and auto-retrying method. 
It doesn't introduce any complexity or magic.

If hoisting up the resiliency can help moving the fix further I can help with that.

**Comment by freben** [comment]
A central concern for the scaffolder in this regard is that it doesn't have a distributed workspace store. I.e., interrupting between two steps, the actual (disk) workspace contents vanish because they only existed ephemerally on the host that executed the template. Maybe that's obvious, but I thought I'd put it in writing still. So yeah moving toward a solution probably indeed involves targeting replayability/indepotency so it's safer to _re-run_ templates rather than resuming them.

Unless we try to work on a distributed store layer. But that's  more involved and less likely to happen short term.

The backend-tasks scheduling system also has no knowledge of the type of work that the task performs so it can't make assumptions. But it could be considered to add finer control to the schedule parameters, such as what to do when encountering errors or timeouts (perhaps try again very quickly, with exponential backoff, instead of waiting to the next scheduled slot?)

**Comment by acierto** [comment]
> A central concern for the scaffolder in this regard is that it doesn't have a distributed workspace store. I.e., interrupting between two steps, the actual (disk) workspace contents vanish because they only existed ephemerally on the host that executed the template. Maybe that's obvious, but I thought I'd put it in writing still. So yeah moving toward a solution probably indeed involves targeting replayability/indepotency so it's safer to _re-run_ templates rather than resuming them.
> 
> Unless we try to work on a distributed store layer. But that's more involved and less likely to happen short term.
> 
> The backend-tasks scheduling system also has no knowledge of the type of work that the task performs so it can't make assumptions. But it could be considered to add finer control to the schedule parameters, such as what to do when encountering errors or timeouts (perhaps try again very quickly, with exponential backoff, instead of waiting to the next scheduled slot?)

That does make sense to do quick retries. In terms of scaffolder tasks, it can be done in custom actions, so it's already can be tackled by the end user. Though it makes. to do retries, it also depends what kind of error was there. For some cases you would like to show the error to the user as fast as possible. It makes it tricker to do it for all backend tasks, some context had to be provided what to do where.

For example, with a scaffolder template, we don't use any standard steps provided by Backstage. I see a lot of flakiness with Gitlab, so each call to Gitlab is wrapped in retry and some actions are made to make the steps idempotent, if repository exists, it will not bork, but skip the creation, and so on.

**Comment by andrewthauer** [comment]
I agree that idempotency is a must for all tasks in the context we are talking. It gets tricky with many scaffolder tasks that do things with 3rd party APIs that are inherently not idempotent though. We currently don't use the scaffolder too much, but do use the scheduled tasks for a lot of custom things, so my perspective is coming from the direction of what it lacks. I understand that catalog and scaffolder have unique concerns, but it would be awesome if there were some lower level primitives they built off that handled some of these cases a bit better.

I recently took a stab at creating a `backend-jobs` package that wraps [pgboss](https://github.com/timgit/pg-boss) into a similar API as to `TaskScheduler`. Haven't used it too much, but it seems to solve some of the pain points we've had with just scheduled tasks. For one you can queue jobs which allows you to distribute work if needed. Secondly it can handle retries and exponential backoffs. Idempotentency however, needs to be an case by case consideration as always though so it can't solve that by itself.

I do think keeping the scope of this to a minimum make sense. Are any of these changes applicable to all scheduled tasks? As with the `backend-jobs`, I would be open to contributing this upstream, but it's just a wrapper and not sure it makes sense. I also felt that it would be hard to add these features into the schedule tasks API as is, but you could achieve scheduled tasks (crons) with background jobs, so 🤷

**Comment by benjdlambert** [comment]
Wanna pick this up on friday for a mob review?

**Comment by acierto** [comment]
Yeah, that would be nice. 
I went through a cycle of real testing on production (GKE, 3 pods). 
Would be nice to go together through code

**Comment by benjdlambert** [comment]
Do you wanna rebase this to remove the other commits? There's a load in here which aren't related

**Comment by acierto** [comment]
I'll create a new PR, these unrelated stuff is due to rebasing, as I missed a sign-off in one of commits 😅

**Comment by acierto** [comment]
https://github.com/backstage/backstage/pull/21299

**Pull request closed without merging**
