### PR TITLE
[TechInsights] Modify queries to perform better by filtering on subqueries as well

### PR DESCRIPTION
**Pull request by Xantier**
14 s 155 ms -> 1 s 78 ms for ~6 million rows on a DB that has teeny-tiny resources.

Signed-off-by: Jussi Hallila <jussi@hallila.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [n/a] Added or updated documentation
- [n/a] Tests for new functionality and regression tests for bug fixes
- [n/a] Screenshots attached (for UI changes)
- [n/a] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Xantier** [comment]
Vale is angry at an unrelated file.

**Comment by goenning** [comment]
Not part of this PR, but just thinking out loud:

should we also have some fact purging process? something configurable to:

- keep only up to X facts for each entity
- remove duplicate facts

Or even when we're storing facts, if the current value is the same as the latest value, is there any benefit in storing it at all?

**Comment by Xantier** [comment]
> Not part of this PR, but just thinking out loud:
> 
> should we also have some fact purging process? something configurable to:
> 
>     * keep only up to X facts for each entity
> 
>     * remove duplicate facts
> 
> 
> Or even when we're storing facts, if the current value is the same as the latest value, is there any benefit in storing it at all?

A day late: https://github.com/backstage/backstage/pull/8845 ;)

**Comment by goenning** [comment]
Aww, nice! We'll definitely use once it's merged! For the dupes, it could make it configurable because there'll be use cases for both as you say.

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice work!

**Pull request merged**
