### PR TITLE
Catalog-backend- need for optimizing the ingestion loop #3534

### PR DESCRIPTION
**Pull request by SuganJoe**
## Optimization in catalog backend ingestion loop
**Why?**
During location refresh in catalog backend, there is a comparison between old entities and new entities in  _entityHasChanges()_ function. In that method, _relations_ in the existing entity from DB (e1) is not removed causing lodash.IsEqual() to always returns false and entities always end up in _toUpdate_ list instead of ideally going to _toIgnore_ list. Due to this, there is a high latency especially if the entities count is large though those entities exist in DB already.

Note : 

1. _relations_ don't exist in incoming entity, but exist only in existing entity in DB
2. For 13K entities, it took around 60 seconds for first write to DB and successive updates took 1000 seconds. 

**What?**
Removed relations in the existing entity from DB (e1) before performing lodash.IsEqual(), and this helps successive updates to complete within 100 seconds.

**Tracking GitHub bug :** https://github.com/backstage/backstage/issues/3534 - Catalog-backend- need for optimizing the ingestion loop

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thanks! Seems like this is indeed an issue, but perhaps not the correct fix? We still want to check whether the relations have changed, and I'm assuming this would end up ignoring any changes to the relations?

**Comment by SuganJoe** [comment]
@Rugvip With the limited time I spent on the ingestion loop, relations seems to be a read only field. So, the new entities which are incoming doesn't have this field. Once it is decided, where to add or to update, then this field is appended to an entity.

**Comment by Rugvip** [comment]
@SuganJoe The relations are written separately from the entity itself, so incoming entities won't have relations added to them until you read them back from the database after having written all relations. The `.relation`s of an entity really should be involved in the comparison of two entities, so it's probably best not to apply this change to `@backstage/backend-common` but to the catalog backend itself.

Without having looked too much at the existing code in the catalog backend, I'm thinking that it might make sense to delete the relations before comparison there, but then to always write all relations to the DB? While it's not a complete fix it might alleviate the issue a bit until we can get something proper in place?

**Comment by Rugvip** [comment]
By proper I mean most likely doing a bit of complete restructuring of how we write to the db 😅

**Comment by SuganJoe** [comment]
Thanks for the clarification! It does make sense to make this changes specific to catalog-backend before comparison. I will update the PR with changes.

**Comment by freben** [comment]
Hey again - I had a hack day and was poking around the backend and actually ended up doing essentially what you had from the start, but for both sides and with a comment clarifying the purpose of the function. So, you really had the right idea. Sorry for the back-and-forth on this ...  but thank you very much for the contribution, because it's bitten me as well now and the change really makes things better.

https://github.com/backstage/backstage/pull/3666

**Pull request closed without merging**
