### PR TITLE
[GitHub Issue Templates] Removed placeholder and moved text to description

### PR DESCRIPTION
**Pull request by awanlin**
## Hey, I just made a Pull Request!

Currently when you create any issue due to a new feature GitHub rolled out the placeholder text gets mangled with some text being added by the new MarkDown box like this:

image

There aren't any clear directions as to the best way to fix this. I've removed the placeholder text and where it made sense moved it up into the description as a workaround.

One other idea I'd like to try and I left it in place for the `bug.yaml` is to see if we can use the `\n` to put the place holder below the text we don't control. I'm not aware how to test these changes without them being committed though. This will need to be merged and then a follow up for further adjustments may be needed.

Open to other solutions or ideas. 🤔 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hmm this definitely looks like a bug on the GitHub side to be honest, but happy to get this change in for now and see what else we can do in the future!

**Comment by benjdlambert** [comment]
Actually, on second glance does your templates not look like this:

**Comment by awanlin** [comment]
@benjdlambert it shows up once you click inside the text area

**Comment by benjdlambert** [comment]
Oh now I see it - bah that's unfortunte.

**Comment by awanlin** [comment]
Hi @benjdlambert, I'd like to merge this and I'll also log an issue, just need to figure out where that would be 🤔

**Comment by benjdlambert** [comment]
https://github.com/orgs/community/discussions/76763

**Comment by awanlin** [comment]
What should we do then? Hold off for GitHub to fix it? I'll be honest it's been like this for about a month now and I might be the only one to "complain" about it so might not be a big deal to most people? 🤷

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Lets see if the new line stuff fixes it :)

**Comment by awanlin** [comment]
OK, so now with the new line in place and I've clicked inside the text box it looks like this:

image

What do you think? Should I do a follow up PR to move them back but with new lines added?

**Comment by benjdlambert** [comment]
@awanlin yeah I think so right? It's a shame to loose that context for now I think. You could also suggest that in the discussion for other people running into this I guess and let them know how we're working around it :)

**Pull request merged**
