### PR TITLE
Add Status and SortableTable to Storybook

### PR DESCRIPTION
**Pull request by stefanalund**
## Hey, I just made a Pull Request!

Screenshot 2020-04-13 at 11 27 29

@mikqi any idea why this happens ^

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by mikqi** [comment]
I try to debug it in storybook and i found that `theme.palette.status` is not exist.
image

but if i try to debug it in example-app and it has `status` props in `palette`.
image

**Comment by stefanalund** [comment]
@mikqi right, it exists in the main app but not in the Storybook.

**Comment by stefanalund** [comment]
Looks like you have to do some extra work https://medium.com/encode/setting-up-storybook-with-material-ui-and-styled-components-5bdacb6db866

**Comment by freben** [comment]
I just want to note that SortableTable may not be a great component to establish too much. I'm hoping we'll get a better overall data grid component in place and then it'll just be a matter of setting a sortable flag on that - as well as filterable etc etc.

**Comment by stefanalund** [comment]
@freben this will give us a nudge to replace it faster 😬

**Review by Rugvip — APPROVED** [review]
👍 once storybook issues are fixed

**Pull request merged**
