### PR TITLE
docs: :memo: Adding MusicTribe to adopters

### PR DESCRIPTION
**Pull request by Herbievorious**
Signed-off-by: Alex Ford <alex.j.ford@gmail.com>

## Hey, I just made a Pull Request!

Adding MusicTribe to ADOPTERS.md

### CODE REVIEW

**Comment by Herbievorious** [comment]
Amended the commit with a sign-off to adhere to DCO status check

**Comment by Rugvip** [comment]
@Herbievorious it looks like you used a different email to sign off compared to the one registered to your GitHub account :sweat_smile:

**Comment by Herbievorious** [comment]
> @Herbievorious it looks like you used a different email to sign off compared to the one registered to your GitHub account 😅

Ah sorry about that - I've updated the commit now with the correct email address for the author

**Review by Rugvip — APPROVED** [review]
Thank you, and welcome! 😁 🎉

**Pull request merged**
