### PR TITLE
Make it possible to manually retry the scaffolder template from the failed step (based on checkpoints)

### PR DESCRIPTION
**Pull request by acierto**
## Hey, I just made a Pull Request!

As a continuation of the work on BEP https://github.com/acierto/backstage/tree/master/beps/0004-scaffolder-task-idempotency. This functionality covers the possibility to "Retry" the scaffolder's task again not from the beginning but rather from the last failed step. 

For that you should have your actions using checkpoints.

Screenshot 2024-09-10 at 21 26 57

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by acierto** [comment]
@benjdlambert 

Please take a peek at it. 
If it looks okay, I'll add unit tests on top of it.

To maximise the value of this manual "Retry" with minimal effort from end users, we need to establish "auto-checkpoints" for each action. I have not yet examined the variety of built-in actions to determine whether we will encounter any potential pitfalls with this approach. Alternatively, we could implement checkpoints for all built-in actions and encourage contributors to adhere to the same strategy.

**Comment by benjdlambert** [comment]
@acierto think this is looking good!

yeah I think that of course we should add as many checkpoints as we can for the actions that we can, and encourage people to start adding them too with some good docs around it.

In terms of `auto-checkpoints` thinking that there could be a checkpoint right at the start of every action, so when you click retry, it will retry from the beginning of the action that it failed on by default right? Or is that not what you meant?

**Comment by acierto** [comment]
@benjdlambert Right now it plays all actions from the beginning and will skip all executed checkpoints.

To be able to skip all already executed steps, we have to store the output of each successful executed step, so it's the same what we do with checkpoints, that what i meant with `auto-checkpoint`. Right now we are storing only explicitly called checkpoints.

You can also see from the screenshot I attached "Template Docs Skeleton" took 1 sec, so it was executed again. But the second action "I'll fail few times" took 0 sec, cause I wrapped it in the checkpoint, the execution was skipped, the output was taken from the database.

**Comment by benjdlambert** [comment]
Will probably merge this after the mainline release goes out today if that's ok @acierto? Unless there's some other things that you want to add to this PR? :pray:

**Comment by acierto** [comment]
@benjdlambert Sounds good to me. This is all under a feature flag, so won't affect anyone who didn't enable it.

**Review by benjdlambert — APPROVED** [review]
Let's get this in and test! :tada:

**Pull request merged**
