### PR TITLE
Add titles to codeblocks and switch from diff codeblock to language codeblock

### PR DESCRIPTION
**Pull request by schultzp2020**
#### :heavy_check_mark: Checklist

fixes https://github.com/backstage/backstage/issues/16160

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by schultzp2020** [comment]
@jhaals @freben 
Any ideas why I can't run `yarn --cwd microsite-next/ start` on Windows 10 or Fedora through WSL? Here's my error.

```log
Error: Can't resolve '/img/logo.svg' in 'C:\backstage\microsite-next\src\css'
Error: Can't resolve '/img/logo.svg' in 'C:\backstage\microsite-next\src\css'
-- inner error --
Error: Can't resolve '/img/logo.svg' in 'C:\backstage\microsite-next\src\css'
Generated code for C:\backstage\microsite-next\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[6].use[1]!C:\backstage\microsite-next\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[6].use[2]!C:\backstage\microsite-next\src\css\customTheme.css
client (webpack 5.75.0) compiled with 2 errors
Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir 'C:\backstage\microsite-next\static'
```

**Comment by schultzp2020** [comment]
@benjdlambert @jhaals @freben

**Comment by benjdlambert** [comment]
@schultzp2020 I think  a merge conflict has crept in here, and you'll also need to run `yarn prettier ./ --write` in the docs directory too to tidy up the formatting.

**Comment by schultzp2020** [comment]
@benjdlambert I fixed the merge conflict and formatted the docs. However, I am still getting the same error as [before](https://github.com/backstage/backstage/pull/16664#issuecomment-1450739793). Any idea why?

**Comment by benjdlambert** [comment]
@schultzp2020 ah sorry, my recommendation was for the build not for your local machine. It looks like you're on windows and we have some resolution that for images that doesn't get translated very well to windows paths. Not really sure of a good fix, as I thought it would get transpiled away somehow and converted.

I wonder if you could run `WSL` and build this in a container? Happy for contributions to fix it on windows too, but not sure what to suggest.

**Comment by schultzp2020** [comment]
@benjdlambert Using WSL with Fedora does not work either.

**Comment by freben** [comment]
The `static` entry is a soft link to `microsite/static` - maybe that's why. You could temporarily copy over that folder replacing the soft link, and see if that works

**Comment by jhaals** [comment]
> The `static` entry is a soft link to `microsite/static` - maybe that's why. You could temporarily copy over that folder replacing the soft link, and see if that works

That might be the reason! But that will probably be fixed by #16790 where I move the static folder

**Review by jhaals — APPROVED** [review]

**Pull request merged**
