### PR TITLE
fix: Send fewer files as base64 encoded for githubPullRequest

### PR DESCRIPTION
**Pull request by rmartine-ias**
## Hey, I just made a Pull Request!

Closes https://github.com/backstage/backstage/issues/17188

WIP, still need to:

* test in an actual Backstage instance
* generate changeset & API report
* figure out if there's a way to do this without breaking API changes if it's reverted
  * We can do this on the integration config, so it's set in one place, and that way there's less code churn when undoing. 
* write real commit message & PR description

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by rmartine-ias** [comment]
still in progress; on PTO right now

**Comment by rmartine-ias** [comment]
WIP

**Comment by freben** [comment]
@rmartine-ias Do you think you'll get an opportunity to finish off this one? Looks like a worthwhile addition!

**Comment by rmartine-ias** [comment]
Been out with covid. Will try and pull some time this week.

**Comment by freben** [comment]
Get better!

The maintainers are out this week too.

**Pull request closed without merging**
