### PR TITLE
Kubernetes: add option to fetch additional objectTypes which are not present in DEFAULT_OBJECTS

### LINKED ISSUE #25751: 🚀 Feature: Secrets as part of Kubernetes core resources
### 🔖 Feature description

Similar to #20937, we need Secrets to be an additional resource fetched by Backstage. I'm unsure if special requirements are necessary for fetching secrets, but we can follow a process similar to #20951.

### 🎤 Context

We want to give our users the possibility to obtain secrets/ApiToken directly in backstage without using an third party tool like Headlamp

### ✌️ Possible Implementation

See #20951 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by derbauer97**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

Fixes #25751

### CODE REVIEW

**Review by mclarke47 — CHANGES_REQUESTED** [review]
Hi, it was an intentional decision to not include secrets in the default objects to fetch since it could cause security issues for adopters be default. Instead you can specify the default list of objects to fetch through configuration ([docs link](https://backstage.io/docs/features/kubernetes/configuration#objecttypes-optional)).

**Comment by derbauer97** [comment]
Hey @mclarke47, fully understand but the documenation mentions:

```
You may use this config to override the default object types if you only want a subset of the default ones. However, it's currently not supported to fetch object types other than the ones specified in the default types.
```

is it possible to add secrets without adding it to the default types?

**Comment by derbauer97** [comment]
Hey @mclarke47,

I've updated the scope of this MR. I introduced a new ALL_OBJECTS array that includes additional Kubernetes object types. This allows fetching secrets by specifying them in the objectTypes config without fetching them by default.

Let me know what you think!

**Comment by derbauer97** [comment]
still relevant!

**Comment by derbauer97** [comment]
Hey @mclarke47,

sorry maybe i missed something but i already outlined the relevanr documentation: https://github.com/backstage/backstage/pull/25760#issuecomment-2249568613

which says it is not possible to use types not included in the default types. As you already mentionef secrets is not in the default types!

i also tested adding secrets to the config but they are not returned without my changes. Which makes sense cause there is no code which would do that currently

**Comment by derbauer97** [comment]
Hey @mclarke47,

I hope you're doing well! Just wanted to check in and see if you had a chance to take a look at this yet?

**Comment by mclarke47** [comment]
Hey, sorry about the slow reply. I've been at full capacity. I'll look this afternoon EST.

**Review by mclarke47 — APPROVED** [review]
I think this is ok since it shouldn't expose these by default, only if explicitly configured, still feels not quite right though.

**Comment by mclarke47** [comment]
WDYT @Rugvip

**Comment by elaine-mattos** [comment]
Hi! Any activity here? This PR would help my team a lot! :)

**Comment by mclarke47** [comment]
Can you rebase this? @derbauer97

**Pull request closed without merging**
