### PR TITLE
Fix alpha imports in permission docs

### PR DESCRIPTION
**Pull request by joeporpeglia**
Signed-off-by: Joe Porpeglia <josephp@spotify.com>

## Hey, I just made a Pull Request!

Adds the missing `/alpha` path to `@backstage/plugin-catalog-backend` imports in the permission docs example snippets.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]

**Comment by asaini11** [comment]
Hi @joeporpeglia I had the same issue with `import { catalogEntityReadPermission } from '@backstage/plugin-catalog-common';` where it was saying `has no exported member` so I added `/alpha` at the end here too to make it work. Is it worth updating the docs for this in a new PR too?

**Comment by joeporpeglia** [comment]
Hey @asaini11, yes let's update that! Do you want to create the PR?

**Comment by asaini11** [comment]
Hi @joeporpeglia ah I'm currently in the middle of another PR for backstage so is it easier if you do it this time please?

**Comment by joeporpeglia** [comment]
Sure, no worries 🙂

**Comment by joeporpeglia** [comment]
Opened https://github.com/backstage/backstage/pull/11594. Let me know if there are others I missed @asaini11

**Pull request merged**
