### PR TITLE
Add supprt to enable LFS for hosted Bitbucket

### PR DESCRIPTION
**Pull request by carlo-colombo**
Signed-off-by: Carlo Colombo <carlo.colombo@klarna.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — COMMENTED** [review]
I think this looks good 👍

I wonder if we should be super duper clear and log that enableLFS is skipped for bitbucket.org if you try to enable it.

**Comment by carlo-colombo** [comment]
So I excluded it from the implementation because from the docs it seems that it always enabled (as for Github), so I thought it was enough to warn that is only for hosted instances in the input field description. But of you prefer I can add a log message, would somehtting like `ctx.logger.warn("Enbable LFS is skipped for cloud Bitbucket repositories")` would be ok?

**Comment by jhaals** [comment]
Ah then I misunderstood you initially, I was about confused logging in to bitbucket.com and seeing LFS.
In that case no need to warn!

**Review by jhaals — APPROVED** [review]
Looks good to me!

**Comment by carlo-colombo** [comment]
Nice! thanks!

**Comment by carlo-colombo** [comment]
Hi @jhaals, do I need to complete some additional action to have this merged?

**Pull request merged**
