### PR TITLE
Pass NavLinkProps to SidebarItem

### PR DESCRIPTION
**Pull request by ilyamkin**
## Hey, I just made a Pull Request!

Allow passing NavLinkProps to SidebarItem to be able to customize its behavior.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by timbonicus — APPROVED** [review]

**Comment by ilyamkin** [comment]
@timbonicus It says I still need one more approval

**Comment by jhaals** [comment]
Are there any specific props that you're interested in for this? Not sure we want to add a lot of props if only a few are needed.

**Comment by ilyamkin** [comment]
@jhaals SidebarItem is essentially wrapping NavLink. My thinking was instead of adding or removing properties one by one (and breaking stuff by it https://github.com/backstage/backstage/pull/4427), we make sure that SidebarItem is just adding styles and not limiting react-router props, so devs can make a choice for their use cases

**Comment by ilyamkin** [comment]
@jhaals do you have any other questions?

**Review by Rugvip — APPROVED** [review]
Thanks! :shipit: 

Thinking that if we end up wanting to rework this we probably just end up with a completely new component instead, so no need to be too careful about API surface here

**Pull request merged**
