### PR TITLE
Move over collectLegacyRoutes to core-compat-api

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

This PR moves over `collectLegacyRoutes` from `core-plugin-api` to `core-compat-api`, removing `frontend-plugin-api` as dependency. Work towards #18372

All the references have been updated. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by emmaindal — APPROVED** [review]
approving files owned by @backstage/discoverability-maintainers

**Review by tudi2d — APPROVED** [review]
lgtm - only impact on `alpha` versions

**Review by Rugvip — CHANGES_REQUESTED** [review]
Nice! 👍 Just a few tweaks

**Review by Rugvip — APPROVED** [review]
🎉 :shipit:

**Pull request merged**
