### PR TITLE
updated the knip rules a bit

### PR DESCRIPTION
**Pull request by freben**
@drodil 

Now there are drastically fewer false positives! Actually a ton of report files are completely empty.

No changeset since it'll be covered by #21963 which is not yet released

### CODE REVIEW

**Comment by drodil** [comment]
@freben awesome, looks great! I also did some minor updates to knip here https://github.com/webpro/knip/pull/502 so it will also evolve when new version is released.

**Comment by drodil** [comment]
> @freben awesome, looks great! I also did some minor updates to knip here [webpro/knip#502](https://github.com/webpro/knip/pull/502) so it will also evolve when new version is released.

Apparently, this improvement was released in knip 4.5.0 just some time ago, have to update it at some point

**Comment by drodil** [comment]
@freben Other thing to consider is to add more issue types to reports at some point, now it only handles dependencies and unlisted (https://knip.dev/reference/cli#--include)

**Review by Rugvip — APPROVED** [review]
:shipit:

**Pull request merged**
