### PR TITLE
Swapping Red Hat partner logo for all white version

### PR DESCRIPTION
**Pull request by coreydaley**
## Hey, I just made a Pull Request!
Swapping the red/black Red Hat partner logo for a solid white logo that fits better with the page aesthetic. Logo provided is an official Red Hat logo from the brand website.
Screenshot from 2024-02-05 09-18-19

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by tudi2d — APPROVED** [review]
thanks! still has less "padding" then the others & the row break is not optimal with 5 logos, but a good improvement!!

**Comment by coreydaley** [comment]
@tudi2d I added some padding around the logo, hopefully that looks better.

**Comment by tudi2d** [comment]
nice - thanks corey! lgtm - let's give it a go.

**Comment by coreydaley** [comment]
Thank you! Just for reference, how often does the site get republished?

**Comment by awanlin** [comment]
On merge but it's a bit slow and can get reset when other changes get merged: https://github.com/backstage/backstage/actions/workflows/deploy_microsite.yml

Looks to be updated though: https://backstage.io/community

**Comment by coreydaley** [comment]
Got it, thanks @awanlin

**Pull request merged**
