### PR TITLE
Expose SonarQube API and helpers

### PR DESCRIPTION
**Pull request by magnusp**
Signed-off-by: Magnus Persson <magnus.persson@fortnox.se>

## Hey, I just made a Pull Request!

We are in need of creating some UI elements that consume sonarqube metrics. This PR intends to export the API/client so that we don't have to reimplement it for our instance. I've made a best effort of adding exports and annotations for the api report, but I'm not sure that it should be marked as public. It might even be that we dont intend on exposing the API just yet. But I needed to start somewhere :)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by magnusp** [comment]
@dhenneke @scthi @Neemys any feedback on this? Is there a reason why we shouldn't expose the API?

**Comment by magnusp** [comment]
We find that the provided `SonarQubeCard` is much too visual and thus had to resort to copying the plugin to our instance. This gave us access to some necessary hooks and types:
```
...
const { entity } = useEntity();
const sonarQubeApi = useApi(sonarQubeApiRef);

const projectTitle = useProjectKey(entity);
...
```
And with that we created our own CompactSonarQubeCard:
image

In the future we will look at [Tech Insights](https://roadie.io/backstage/plugins/tech-insights/) and creating facts from sonarqube metrics. Facts are materialized on the backend so being able to import and use [SonarQubeClient](https://github.com/backstage/backstage/blob/master/plugins/sonarqube/src/api/SonarQubeClient.ts) would be awesome.

**Comment by magnusp** [comment]
> @magnusp - I'm curious how you are intending to use these types? Any chance you can provide an abbreviated example?

We find that the provided `SonarQubeCard` is much too visual and thus had to resort to copying the plugin to our instance. This gave us access to some necessary hooks and types:
```
...
const { entity } = useEntity();
const sonarQubeApi = useApi(sonarQubeApiRef);

const projectTitle = useProjectKey(entity);
...
```
And with that we created our own CompactSonarQubeCard:
image

In the future we will look at [Tech Insights](https://roadie.io/backstage/plugins/tech-insights/) and creating facts from sonarqube metrics. Facts are materialized on the backend so being able to import and use [SonarQubeClient](https://github.com/backstage/backstage/blob/master/plugins/sonarqube/src/api/SonarQubeClient.ts) would be awesome.

**Comment by andrewthauer** [comment]
Thanks for the context. I can't see a huge harm in exporting these, but I will point out a couple alternative approaches:

- Provide your textual view as an alternative view in the open source version.
- Consider moving the public types, etc to a `@backstage/plugin-sonarqube-react` package.

That said, the plugin is pre v1, so any future breaking changes to these types should be expected. Probably best for @backstage/maintainers to chime in.

**Comment by freben** [comment]
I see this is still a draft and some conflicts crept in. Gentle ping here, how are you feeling about the PR?

**Comment by magnusp** [comment]
Since Im not seeing anything stoppning the export of these types I will go
over the changes again and keeping it as a draft as of now. Introducing a
-react package seems to make sense so I will explore that route.

Den mån 14 nov. 2022 16:15Fredrik Adelöw ***@***.***> skrev:

**Comment by magnusp** [comment]
So I separated parts of plugin-sonarqube to plugin-sonarqube-react with the expectation that we should now be able to use `useProjectInfo` and `useApi(sonarQubeApiRef)` externally. I'm not feeling very confident in what types got moved, nor the annotations for `@alpha`. I used a package.json from a neighbouring package, and did my best on filling in the dependencies. If everything looks good to the parties involved so far I'm ready to move out of the draft.

**Comment by magnusp** [comment]
I see that @manusant recently did some work on the packages. Got any input on these changes?

**Review by freben — COMMENTED** [review]
Sure, looks good. Maybe the changeset could list the types that were moved. A very defensive thing to do is to keep exporting them from the original package too, but marked as deprecated. Like [here for example](https://github.com/backstage/backstage/blob/2b8d1d37f041d40ef81cfbb13f5692c33663882f/plugins/catalog-backend/src/index.ts#L65). That way you don't have to do the breakage right away

**Comment by freben** [comment]
@magnusp A gentle ping here!

**Comment by magnusp** [comment]
> Sure, looks good. Maybe the changeset could list the types that were moved. A very defensive thing to do is to keep exporting them from the original package too, but marked as deprecated. Like [here for example](https://github.com/backstage/backstage/blob/2b8d1d37f041d40ef81cfbb13f5692c33663882f/plugins/catalog-backend/src/index.ts#L65). That way you don't have to do the breakage right away

If I'm understanding this correctly the types were never exported outside of `@backstage/plugin-sonarqube` and I believe that the API report reaffirms that. That being said we could more specific on what was previous internal to `@backstage/plugin-sonarqube` and henceforth public via `@backstage/plugin-sonarqube` and `@backstage/plugin-sonarqube-react`.

**Review by freben — APPROVED** [review]
Let's :shipit: !

**Pull request merged**
