### PR TITLE
fix: upgrade graphql-voyager dep to fix listeners bug

### PR DESCRIPTION
**Pull request by MitchWijt**
## Hey, I just made a Pull Request!

This PR fixes the following bug issue https://github.com/backstage/backstage/issues/18736#issuecomment-1670807876 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hi! You'll see that vale wants a small spelling fix, and you'll also want to run `yarn install` and commit the resulting `yarn.lock` changes with the PR.

**Comment by freben** [comment]
Also do note the [breaking changes](https://github.com/graphql-kit/graphql-voyager/releases/tag/v2.0.0) in the 2.0 release and give the plugin some manual testing to see that it still runs fine

**Comment by MitchWijt** [comment]
> Also do note the [breaking changes](https://github.com/graphql-kit/graphql-voyager/releases/tag/v2.0.0) in the 2.0 release and give the plugin some manual testing to see that it still runs fine

I did that indeed :) All works as expected in the manual test

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you! 👍 

Please run `yarn install` and commit the changes to `yarn.lock`

**Pull request closed without merging**
