### PR TITLE
Make identity optional in the scaffolder dry-run API.

### PR DESCRIPTION
**Pull request by Pike**
Signed-off-by: Axel Hecht <axel@pike.org>

## Hey, I just made a Pull Request!

Let's make the identity optional when trying to get the token.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

CC @Rugvip @benjdlambert

### CODE REVIEW

**Comment by freben** [comment]
This doesn't really make it optional, does it? It just makes it accept malformed or even malicious tokens. What are you trying to achieve here?

**Comment by Pike** [comment]
> This doesn't really make it optional, does it? It just makes it accept malformed or even malicious tokens. What are you trying to achieve here?

What I'm trying to achieve here is replicating what https://github.com/backstage/backstage/blob/7035be58ba761f64f4dd21ba8c32affb38dc877f/plugins/scaffolder-backend/src/service/router.ts#L94 does with less code.

What that code does (in my understanding) is that it validates that a token is valid, and if it is, it passes it down to the dry-run to be used. And I think my code does that same thing, that is, if there are errors in getting the identity (which would happen on a bad token), I drop the token.

If you're passing in the server token, the old code hits this when it tries to `parseEntityRef(sub)`.

**Comment by Pike** [comment]
Yes, this is to support server tokens.

**Comment by freben** [comment]
OK, that clarifies things to me. So that's actually a use case I've been pondering lately, that we don't have any explicit way to either support both types of token in one interface, or to have a standard way of discerning between the two. That should be addressed one way or the other.

What you can do is to add a `TokenManager` (probably as optional, so as not to cause a breaking change) in the `RouterOptions`. Then your code here could do essentially

```ts
if (request.headers.authorization) {
  try {
    // Try to treat it as a user token
  } catch (e1) {
    try {
      // Try to treat it as a server token using tokenManager
    } catch (e2) {
      // Finally give up and throw an error saying that it was neither a valid server token nor user token
    }
  }
} else {
  // What to do here? Allow or reject?
}
```

Ping @Rugvip @benjdlambert

**Comment by freben** [comment]
@Pike would you mind changing the code as suggested above? Does it sound like it makes sense to you and the proposed use case?

**Comment by Pike** [comment]
> @Pike would you mind changing the code as suggested above? Does it sound like it makes sense to you and the proposed use case?

Yeah. I'll do that in a new PR, though. I'll take that opportunity to reset my fork to one w/out all the old branches ;-)

**Pull request closed without merging**
