### PR TITLE
Fix the missing filter in the toolbar when passing a custom component in the core-components Table

### PR DESCRIPTION
**Pull request by danangarbansa**
## Hey, I just made a Pull Request!

This is the fix for the https://github.com/backstage/backstage/issues/11791.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — COMMENTED** [review]
Thanks for looking at this, it looks like a typescript issue crept in.

**Comment by danangarbansa** [comment]
> Thanks for looking at this, it looks like a typescript issue crept in.

No problem, I'll take a look into it tomorrow.

**Comment by tylerd-canva** [comment]
@jhaals Anything else you think is needed to get this merged?

**Review by freben — APPROVED** [review]
Nice!

**Pull request merged**
