### PR TITLE
feat: add external auth service

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

this allows external services to get authentication token for plugin APIs.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hi! Hm was this preceded by some design discussions somewhere? Just checking if there's context. We've been wanting to tackle improving how external callers can use backstage services, but thought it would need some careful design considerations so it was pushed until after the auth/httpAuth services and functionality has been put in place.

As we settle how the cookie auth improvements are designed, we're leaning towards making every plugin its own issuer, decentralising things. It's not a huge leap from there to think that maybe you'd call that same token endpoint to get external caller tokens per plugin, instead of some central backend. Also we haven't yet decided on the best end to end flows for this. For example, should admins actually have a frontend interface where they can create and remove completely _static_ tokens that they hand out? Which kind of overlaps a bit with the api keys in this PR.

**Comment by drodil** [comment]
@freben well, it's shortly discussed in #23441 as it does not make much sense to create a new backend just for that. Maybe this would require some BEP? I think having such a frontend interface would be a good idea though I don't know if it actually collides with this but could be accompanied later on.

**Comment by freben** [comment]
Mm. This is effectively a new security mechanism so is worth some upfront scrutiny and design. But I'll bring it up at the maintainers sync, and get back to you

**Comment by drodil** [comment]
@freben absolutely! Consider this as a conversation starter PR, not necessarily the one to be chosen 👍

**Comment by freben** [comment]
Oh and one more thing. `getPluginRequestToken` is called on the plugin scoped auth service. We're making it so that the SOURCE issuing plugin ID will be recorded, not just the target. You can't issue tokens on behalf of another backend with this mechanism. The token will look like it came from the auth-external backend, and will lead to problems.

**Comment by drodil** [comment]
Hmm, okay, what kind of problems will this lead to? I think there is a need for a new mechanism for external callers as they are not representing any plugin but instead some external service.

**Comment by mareklibra** [comment]
I like the idea of having an option to call APIs externally.
However, it opens both security and maintenance issues (surface for attackers and backwards compatibility/stability of the API).

**Comment by drodil** [comment]
Not stale, needs discussion

**Pull request closed without merging**
