### PR TITLE
fix: make docs table font color white

### PR DESCRIPTION
**Pull request by Nek**
Makes docs tables' font color white.

### CODE REVIEW

**Comment by stefanalund** [comment]
This doesn't really help :)

Screenshot 2020-08-20 at 08 06 51

**Comment by Nek** [comment]
Thanks for the example. 😅 I'll fix it ASAP.

**Comment by Nek** [comment]
@stefanalund should be good now
image

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
then we want things to not be 100% white, but let's make that change for all elements at the same time later

**Pull request merged**
