### PR TITLE
[catalog-lap] Add concept of group ownership

### PR DESCRIPTION
**Pull request by alde**
A user or group can own another group in a hierarchy setting. These are currently not represented in the catalog.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by alde** [comment]
This is a suggestion on tracking ldap group ownership in catalog.

**Comment by alde** [comment]
@awanlin interesting, I must have missed that whole discussion

**Comment by awanlin** [comment]
Sorry @alde, my intention wasn't for you to have to close your PR. Personally I wonder if we just need to revisit the conversation, maybe we should support this. Maybe in the next Catalog SIG would be a good opportunity?

**Comment by alde** [comment]
no worries, @awanlin, I probably closed it a bit prematurely. Will add a topic to the SIG

**Comment by benjdlambert** [comment]
Gonna close this as waiting results from the RFC and don't want stalebot ping pong whilst that settles. We can of course re-open when we have a solution :tada:

**Pull request closed without merging**
