### PR TITLE
docs(ADOPTERS.md): update list.

### PR DESCRIPTION
**Pull request by padupe**
## Hey, I just made a Pull Request!

Update the list of "Adopters" in the Backstage.
- Inclusion of [Raízen](https://raizen.com/). :brazil:
> Completed [Adopter form](https://info.backstage.spotify.com/public-adopter-hand-raiser-form).

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thank you, and welcome! 😁 🎉

**Comment by Rugvip** [comment]
Would need DCO sign off before we can merge though btw

**Comment by padupe** [comment]
Ready @Rugvip! Thank you for the welcome! :heavy_check_mark:
Hey @rayleshh, we are now officially 'adopters'. :partying_face:

**Comment by padupe** [comment]
Ready @Rugvip! Thank you for the welcome! :heavy_check_mark:
Hey @rayleshh, we are now officially 'adopters'. :partying_face:

**Comment by padupe** [comment]
@Rugvip I don't know what's missing

**Comment by Rugvip** [comment]
@padupe just me hitting the merge button 😁

**Pull request merged**
