### PR TITLE
Allow url with extension .yml in gitlab processor

### PR DESCRIPTION
**Pull request by dehamzah**
## Hey, I just made a Pull Request!

Allow yaml file url with extension .yml in gitlab processor

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
Ok, thanks!

**Comment by freben** [comment]
Oh I see vale is giving you errors. In your changeset file, write "GitHub" instead of "github", and put the word "yml" in backticks like ``` `yml` ``` which will make it ignore that word

**Comment by freben** [comment]
got inspired and did a fixup commit for that - sorry for the noise - will merge when green

**Comment by dehamzah** [comment]
ah thanks, haven't looked at this notification yet back then.

**Pull request merged**
