### PR TITLE
Align TechDocs (`mkdocs.yml`) navigation with microsite

### PR DESCRIPTION
**Pull request by onematchfox**
## Hey, I just made a Pull Request!

Fixes broken navigation under the `Tutorials` subsection of Backstage's own techdocs. Should now match https://backstage.io/docs

#### :heavy_check_mark: Checklist

- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by adamdmharvey — COMMENTED** [review]
Oh wow - nice catch!

I actually hadn't considered before the overlap between the `mkdocs.yml` and the `microsite/sitebars.json` file before.  Going a quick look, there are a few other discrepancies.

Any chance you'd be willing in this PR to take a stab at even further alignment, @onematchfox ?  If not, no prob keeping this to just fixing the tutorials.  But seems a few quick tweaks could align the full thing.

image

Longer term, could be useful to figure out how to avoid this duplication so both the published site and the generated version for TechDocs aligns better. (backstage.io doesn't use mkdocs for generation, so it's only for the TechDocs annotation I believe)

**Comment by onematchfox** [comment]
> I actually hadn't considered before the overlap between the `mkdocs.yml` and the `microsoft/sitebars.json` file before. Going a quick look, there are a few other discrepancies.
> 
> Any chance you'd be willing in this PR to take a stab at even further alignment, @onematchfox ? If not, no prob keeping this to just fixing the tutorials. But seems a few quick tweaks could align the full thin

Sure thing. Wasn't aware of `microsoft/sitebars.json` but had been wandering about why there was a difference. Will take a look at some point and try align everything for the time being.

> Longer term, could be useful to figure out how to avoid this duplication so both the published site and the generated version for TechDocs aligns better. (backstage.io doesn't use mkdocs for generation, so it's only for the TechDocs annotation I believe)

Agreed. Drift is guaranteed if two files need to be maintained manually. I'll leave the solution to that to someone else though :smile:

**Comment by timbonicus** [comment]
> I actually hadn't considered before the overlap between the mkdocs.yml and the microsite/sitebars.json file before.

Ah, I wasn't aware of that either 🤦  a bunch of the mismatches are probably my doing. Happy to clean up the rest if you don't get to it, @onematchfox

**Comment by onematchfox** [comment]
@adamdmharvey I think I have now aligned the nav in `mkdocs.yml` with `microsite/sidebars.json`. Hopefully I didn't miss anything :) 

Whilst going though this I did consider how I might script this but it ended up being a manual process. As a reflection, it may be easier to script this process if a pattern is established between the `microsite`  ids and the markdown filenames. Currently there are inconsistencies which make scripting this a bit more difficult. E.g. `- Overview: 'features/software-catalog/index.md'`  vs `"ids": [ "features/software-catalog/software-catalog-overview",...`. To be able to find the correct markdown page using the `id` one would need to parse all markdown files to find the correct annotation `id: software-catalog-overview`. 

Then, on a more general note, there may be a need for a discussion amongst the maintainers about whether or not _you_ want to dogfood the `techdocs` plugin using Backstage's own documentation. I would imagine there probably was some form of discussion when the decision to not use `mkdocs` for the published site was actually made. Anyway, in going through all the documentation it seems like there are a number of incompatibilities between the generators that lead to differences/issues between the version. Here are a couple examples of issues I spotted based on the differing functionality:
- the images in https://backstage.io/docs/features/techdocs/architecture make use of a `zoom` feature added in https://github.com/backstage/backstage/pull/3488. This is not supported in the `mkdocs` version and thus the images are broken there. 
- there are also differences in the way headers are handled, so these are not appearing on some pages in the `mkdocs` version - see https://backstage.io/docs/features/techdocs/architecture, or https://backstage.io/docs/features/search/architecture for duplicate headers, or the the `mkdocs` version of https://backstage.io/docs/features/techdocs/how-to-guides for some more weirdness

**Review by Rugvip — APPROVED** [review]
Nice, thanks! 👍

**Pull request merged**
