### PR TITLE
Update provider.md

### PR DESCRIPTION
**Pull request by jolies93**
Corrected the Callback URL since we encountered this when implementing.  Also removed the scopes config item - including this resulted in errors for us.

I had submitted a PR before, and I addressed two feedback items - one was wording and the other was a request to include the optional configurations in the instructions.  Both are addressed.  Apologize I had to make a new PR because I had issues with the other being open so long and I didn't rebase it correctly - better to start fresh.

## Hey, I just made a Pull Request!

Changes to documentation to include configuration corrections

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Parsifal-M — COMMENTED** [review]
Hey! 👋 

I think it looks good and its clear, I do not however use this provider...

Just out of curiosity which was the original PR? Just for some added context 😅

**Comment by jolies93** [comment]
> Hey! 👋
> 
> I think it looks good and its clear, I do not however use this provider...
> 
> Just out of curiosity which was the original PR? Just for some added context 😅

Hello and thanks for the review - the original PR is here (closed): https://github.com/backstage/backstage/pull/28012

I had moved the definitions and descriptions for those elements from being on the same line as the example to below so that it matched the general format - I figured perhaps that's what prettier didn't like.

**Review by awanlin — APPROVED** [review]
Thanks for the follow up on this @jolies93 🚀

**Review by awanlin — CHANGES_REQUESTED** [review]
Ah, looks like Prettier isn't happy, can you take a look at that, please?

**Review by awanlin — APPROVED** [review]

**Pull request merged**
