### PR TITLE
feat(catalog-import): Add instructions to Pull Request description when registering a new component

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

Enhances the pull request description to guide the recipient for when a new pull request is added to GitHub.

image

NB: I added the name of their backstage instance and a link to get straight to the Backstage Base URL. When using GitHub.com, I suppose there could be a scenario where users might not want to expose the name of their catalog even if their components are open source, but I'd consider that an edge case because if their code is truly open source, the info about them having a named catalog or it's URL may be as well? I believe having that info would make it a lot easier to proceed with the next step. Open to opinions on it.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by Fox32** [comment]
I think this is quite specific for every adopter. Maybe we should make the summary and body configurable from the outside? I also think that the generated YAML file itself should be passend in as a template from the outside. We for example would like to introduce some comments that give custom instructions (like where our documentation is) and pre fill some fields. That could solve topics like #3678 too.

**Comment by adamdmharvey** [comment]
@Fox32 I do like that idea.  I wonder if we take step steps,

1. A more simple version of what I put here just to get SOMETHING into the PR text for now, and then
2. Spin out a new issue to externalize/template the content?  e.g., it could pull from a URL or something like that, or even just make it pull in something from the deployed app which can be customized on each instance, but identifying the mechanics of that potentially pulled separately?

If you agree, we could either merge this as is and spint out the new issue, or simplify this say by removing the last sentence just to say,

> This pull request adds a **Backstage entity metadata file** \
> to this repository so that the component can be added to the \
> software [${appTitle} software catalog](${appBaseUrl}).
>
>After this pull request is merged, the component will become available.

Thoughts?

**Comment by andrewthauer** [comment]
I'd say this is a good start and can be iterated on. Definitely better then a blank PR with no description.

Longer term I could also see this perhaps pulling in an appropriate PR template from the target repo (if found).

**Review by freben — APPROVED** [review]
I like it!

**Pull request merged**
