### PR TITLE
Add metrics to catalog backend

### PR DESCRIPTION
**Pull request by Fox32**
Add metrics around catalog refresh. This adds the following metrics:

```
# HELP backstage_catalog_entities_total Count of entities in the catalog
# TYPE backstage_catalog_entities_total gauge
backstage_catalog_entities_total 185
# HELP backstage_catalog_locations_total Count of locations in the catalog
# TYPE backstage_catalog_locations_total gauge
backstage_catalog_locations_total 1
# HELP backstage_catalog_refresh_duration_seconds Duration of a catalog refresh in seconds
# TYPE backstage_catalog_refresh_duration_seconds gauge
backstage_catalog_refresh_duration_seconds 25.251336767
# HELP backstage_catalog_locations_refreshed_total Total amount of refreshed locations
# TYPE backstage_catalog_locations_refreshed_total counter
backstage_catalog_locations_refreshed_total 1
# HELP backstage_catalog_entities_refreshed_total Total amount of refreshed entities
# TYPE backstage_catalog_entities_refreshed_total counter
backstage_catalog_entities_refreshed_total 185
# HELP backstage_catalog_locations_refresh_failures_total Total amount of location refresh failures
# TYPE backstage_catalog_locations_refresh_failures_total counter
backstage_catalog_locations_refresh_failures_total 0
# HELP backstage_catalog_entities_refresh_failures_total Total amount of entity refresh failures
# TYPE backstage_catalog_entities_refresh_failures_total counter
backstage_catalog_entities_refresh_failures_total 0
```

In addition this fixes handling of previous prom-client metrics on hot restart. Previously the
metrics registry was cleared too later and might have deleted metrics that were already registered after restart.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by Rugvip** [comment]
@Fox32 Thanks! We discussed this a bit and are thinking it's too all-in prometheus and doesn't leave room to use any other kind of monitoring. Our initial thought is to have another interface with one or more implementations exported from `@backstage/backend-common`, allowing for other monitoring solutions to be plugged in, but sticking to pretty simple constructs and probably silently ignoring any metric types that the implementation can't support.

I think it would be fine to have it be any kind of experimental and unstable API to begin with, just to unblock. One option could be to define a set of metric types that the plugin can expect to have passed in, something like

```ts
interface Gauge {
  set(n: number)
  inc(n?: number)
  dec(n?: number)
}
```

And then provide some backend API for creating the things, e.g.

```ts
const prometheusMetrics = new PrometheusMetricsFactory(promClient)

const catalogRouter = createRouter({
  ...,
  metrics: {
    catalogEntityTotal: prometheusMetrics.createGauge({
      name: 'backstage_catalog_entities_total',
      help: 'Count of entities in the catalog',
    })
  }
})
```

Some thing I'm trying to achieve here:

- Avoid making `prom-client` a dependency in `@backstage/backend-common`, let the dependency be in the backend package instead.
- Let the backend decide the name and description of the metrics to allow orgs to use their existing naming scheme. The name here isn't perhaps too important and it could be nice to find a way for the plugin to be able to provide default names, but providing custom labels could be a bit more important.

**Comment by freben** [comment]
+1 to the above. It will be important for the backend to be the initiator and creator of the metrics "IDs" (the label space). For example, internally, we'd want to use https://github.com/spotify/semantic-metrics and tag each metrics both on a per-metric basis and with application-specific labels. We'd then want to emit this through https://github.com/spotify/ffwd to our time series ingestion that lands it in https://github.com/spotify/heroic.

**Comment by Fox32** [comment]
> @Fox32 Thanks! We discussed this a bit and are thinking it's too all-in prometheus and doesn't leave room to use any other kind of monitoring. Our initial thought is to have another interface with one or more implementations exported from `@backstage/backend-common`, allowing for other monitoring solutions to be plugged in, but sticking to pretty simple constructs and probably silently ignoring any metric types that the implementation can't support.
> 
> I think it would be fine to have it be any kind of experimental and unstable API to begin with, just to unblock. One option could be to define a set of metric types that the plugin can expect to have passed in, something like
> 
> ```ts
> interface Gauge {
>   set(n: number)
>   inc(n?: number)
>   dec(n?: number)
> }
> ```
> 
> And then provide some backend API for creating the things, e.g.
> 
> ```ts
> const prometheusMetrics = new PrometheusMetricsFactory(promClient)
> 
> const catalogRouter = createRouter({
>   ...,
>   metrics: {
>     catalogEntityTotal: prometheusMetrics.createGauge({
>       name: 'backstage_catalog_entities_total',
>       help: 'Count of entities in the catalog',
>     })
>   }
> })
> ```
> 
> Some thing I'm trying to achieve here:
> 
> * Avoid making `prom-client` a dependency in `@backstage/backend-common`, let the dependency be in the backend package instead.
> * Let the backend decide the name and description of the metrics to allow orgs to use their existing naming scheme. The name here isn't perhaps too important and it could be nice to find a way for the plugin to be able to provide default names, but providing custom labels could be a bit more important. 

Prometheus (or OpenMetrics) is the de facto standard for metrics in the CNCF landscape, so I think it shouldn't be a problem with exposing metrics in the Prometheus text format. Most of the available metric processing tools are compatible with the format.

Abstracting away metrics handling is a common approach. Doing it ourself can become quite a big layer of abstraction. I would also have to rewrite the existing metrics for http requests, so we need more than gauge metrics. Here comes the question on what types of metrics we want to settle. The way histograms, gauges, counters and labels work is quite specific to how Prometheus works. If you plan to have an abstraction here instead of using a concrete technology, I would suggest to go with existing libraries. For example OpenTelemetry. It has the same goal of abstracting the technology away, but also the same disadvantages. I also think that implementing/configuring all the possible metrics in the backstage backend might be a little bit too much work for most adopters and won't be used. However this approach would allow us to continue to work with metrics.

As I think it's not worth the effort right now, I would close this PR and build a simple solution that directly scrapes the postgres DB.

**Comment by Fox32** [comment]
@Rugvip Then I guess it's better if we remove the usage of Prometheus completely. Each integrator can add his own monitoring in his backend. I create #3575 for that.

**Comment by Rugvip** [comment]
@Fox32 Yep, had a look at existing metric packages but couldn't find anything interesting. Also looked at OpenTelemetry, but it's not quite ready of metrics yet.

I'm indeed worried about having to maintain an abstraction, would be lovely if we could pick something off the shelf 😅 . That's why I was thinking a starting point could be something experimental and unstable, just to get started. Agree that having to set it up manually is also not ideal, and having some form of default + override is probably better.

A bit of a separate issue but still related is that I'm imagining using prom-client like this is a bit scary, we'd prolly have to make it a peer dependency to ensure that we're not ending up with duplicates, which is probably something to go back and explore a bit more in general.

One slightly different approach would be to have all metrics act on the method calls of the interfaces that the plugin exposes, so you'd decorate the implementations with something that adds metrics. This is in many ways much cleaner, but can't really be used to measure internal pieces like how long it takes to do a single entity refresh.

**Comment by Rugvip** [comment]
@Fox32 Regarding prometheus being de-facto standard in CNCF space, yup. I think it would be fine to either by default or through very some very simple switch enable prometheus metrics, but doing the collection through a prometheus client and make that the way to collect metrics in all plugins is perhaps a bit too inflexible. We should keep our eyes on OpenTelemetry or someone could take a stab at a very lightweight metrics collection interface in the future.

**Comment by Fox32** [comment]
@Rugvip While OpenTelemetry might be promising on the long term, I also don't think that the metrics part is ready yet.

We decided to implement the `backstage_catalog_entities_total`, `backstage_catalog_locations_total` and `backstage_catalog_refresh_duration_seconds` in our backend for now. I skipped the other four as they are quite complicated to implement from the outside. But I don't think they are reasonable to expose right now, so for me it's fine to go without an experimental API. Better would be a return value on the `refreshAllLocations()` call providing details about the errors. Maybe something we can do in #2876.

**Comment by Rugvip** [comment]
@Fox32 FWIW Q1 2021 is prolly gonna have quite a lot of focus on getting this catalog up and running at full scale internally, and as part of that we really have to add metrics :grin: . As freben mentioned above we don't use prometheus much, so would have to have some kind of initial abstraction in place too

**Comment by weyert** [comment]
Would it be possible to use `opentelemetry-js` and let the users decide which exporter they want to use; e.g. send it to Prometheus, Google Cloud Monitoring etc. 

https://opentelemetry.io

**Pull request closed without merging**
