### PR TITLE
user-settings: restore route ref path to fix sidebar item

### LINKED ISSUE #4362: user-settings: Link to settings in side bar does not work
## Expected Behavior

When clicking "Settings" at the bottom left of Backstage, the user should be taken to the user settings page.

## Current Behavior

From latest code on master on 2 Feb 2021, I've found a few weird situations where the routing to the settings doesn't quite work.  However, if I manually change my URL to force the route `/settings`, the settings page loads up fine. There seems to be some situation where some aspect of the catalog "breaks" my catalog route, as off a fresh install I'm able to get to the settings from clicking it. But not once clicking around in the catalog itself.

## Steps to Reproduce

1. Open Backstage
2. Open a SPECIFIC entity (not the catalog main page)
3. Click Settings at bottom left
4. Get routed to catalog homepage

Also, ONCE on this "catalog" page after being redirected from Settings, you can not get to settings anymore. The route to it seems to have been broken somehow.

## Context

Two recent PRs in this space that might possibly be at play, though I'm not sure:

https://github.com/backstage/backstage/pull/4341 - new composability routing
https://github.com/backstage/backstage/pull/4348 - user settings Pin sidebar panel fix

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

### PR DESCRIPTION
**Pull request by Rugvip**
Fixes #4362

Change is still pending release, so no changeset

### CODE REVIEW

**Comment by adamdmharvey** [comment]
Tested this branch locally and this does indeed fix my reported issue in #4362. woohoo! thanks Rugvip! 🎉

**Review by adamdmharvey — APPROVED** [review]
Tested this branch locally and this does indeed fix my reported issue in #4362. woohoo! thanks Rugvip! 🎉

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4363-zbofg8d8bk3bg0sppp3ps78alcgb4lfq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6019c8f498552d691454cc81

**Review by freben — APPROVED** [review]
Oof

**Pull request merged**
