### PR TITLE
cli: move common utilities into new cli-node package

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

I've been wanting to use some of the utilities in the main CLI in other places, which so for has mostly been done via copy-paste. It's been alright, but some of the new utilities are to large to copy, in particular the package graph git diffing with lockfile analysis. This separates out a bunch of those utilities for broader use in a new `@backstage/cli-node` package.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by ahhhndre** [comment]
Hi @Rugvip, does this mean I could use the `Lockfile.ts` from this new `@backstage/cli-node` package in my DevTools' backend plugin? Right now I have an exact copy and this always felt a bit wrong to me. Do you have an ETA for this to get merged in?

**Review by ahhhndre — APPROVED** [review]
LGTM! 🚀

**Review by benjdlambert — APPROVED** [review]

**Comment by Rugvip** [comment]
@ahhhndre ah, I don't think it'll help you right now, but we could get there. I only brought over the lockfile diffing, it doesn't expose the data itself. That's because it wasn't as useful outside of the CLI right now, and I didn't want to add to the public API at this point. Happy to add that in the future though

**Comment by ahhhndre** [comment]
OK, thanks @Rugvip, I'll keep an eye on this then for the future 👍

**Pull request merged**
