### PR TITLE
Allow paths with dots

### PR DESCRIPTION
**Pull request by ilyamkin**
## Hey, I just made a Pull Request!

We should allow the usage of paths with dots.
Ref.: https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by shmidt-i** [comment]
Could you please elaborate on your use case?

**Comment by ilyamkin** [comment]
Sure, we use dotted paths in the internal plugin like `/plugin/view/test@gmail.com`.
Also, the dotted path works in the production build but crashes in the dev environment, so it's a bit inconsistent.

**Review by Rugvip — APPROVED** [review]
Yep 👍

**Comment by ilyamkin** [comment]
@Rugvip Build is failing on Windows. 🤔  Could you please restart it?

**Pull request merged**
