### PR TITLE
feat: implemented devcontainers support for developing in the backstage repository

### PR DESCRIPTION
**Pull request by sonikro**
This relates to issue #14916

## Hey, I just made a Pull Request!

Implements DevContainer support in the repository, so developers can start working right away, without having to have dependencies installed on their laptops, other than Docker and VSCode.

This should also work with Github Codespaces, so people can work on the project without even having to clone the repo locally

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by sonikro** [comment]
> Thanks for the suggestion.
> 
> I'm not sure we want to promote devcontainers that much as adding it to the readme and have vscode pick it up right away. I did give it a try on my new Macbook Pro but I had trouble getting a decent performance. This might be something that we can add under our `contrib/` folder instead? We have something similar described at https://github.com/backstage/backstage/blob/master/contrib/docker/devops/README.md

I've been working with Backstage using solely devcontainers for a couple of weeks now. The performance is definitely not as fast as running everything natively on your machine, but the portability that this allows for me outweighs the cons. I've been using this devcontainer in both MacOS (Macbook Pro M1 16gb ram) and Windows 10 (I7 vpro 32gb ram). 

About the existing Dockerfile in the contrib/docker/devops folder, I think we could reuse that same Dockerfile for creating the devcontainer environment, so we don't need more than one. 

About the Readme, I'm fine removing that badge from the Readme, it's not a necessity, it's just a shortcut. 

I could add the .devcontainer folder inside the contrib/docker folder, but VSCode will only detect the configuration if it resides in the .devcontainer folder in the root of the directory.

What do you think we should do, in order to incorporate DevContainers into this repo ? Let me know so I can help.

**Review by jhaals — CHANGES_REQUESTED** [review]
I think it's completely fine for those that want portability to promote and configure devcontainers in their own installation of Backstage but I don't think we want it by default for the core repository as vscode ask if you want to use it and the speeds aren't comparable to bare metal. I suggest we move the `.devcontainer` folder into a subfolder of contrib alongside some documentation for how to use it in your own project for those interested.

**Comment by sonikro** [comment]
> I think it's completely fine for those that want portability to promote and configure devcontainers in their own installation of Backstage but I don't think we want it by default for the core repository as vscode ask if you want to use it and the speeds aren't comparable to bare metal. I suggest we move the `.devcontainer` folder into a subfolder of contrib alongside some documentation for how to use it in your own project for those interested.

I moved the folder to the **contrib** folder, and added a README explaining how to use, the benefits and known issues. I also removed the Badge from the main README file

**Review by jhaals — APPROVED** [review]
Thank you! 👍

**Pull request merged**
