### PR TITLE
Expose the list of default catalog processors

### LINKED ISSUE #5388: [Catalog] Expose default processors
## Feature Suggestion
Today when you need to configure a default CatalogProcessor with code you are left with the only option to use the
`builder.replaceProcessors`, which forces you to manually create all other processors that you want to use in your instance of backstage.

Our use case is that we want to use a custom repository parser implemented in https://github.com/backstage/backstage/pull/5295, but keep all other default processors as is.

## Possible Implementation

I suggest that the creation of the default processors is exposed so you can manipulate it as you wish before you call `builder.replaceProcessors` with the list of processors to enable.
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/service/CatalogBuilder.ts#L306-L317

### PR DESCRIPTION
**Pull request by goober**
Signed-off-by: Mathias Åhsberg <mathias.ahsberg@resurs.se>

## Hey, I just made a Pull Request!
This pull request exposes the list of default catalog processors for further fine-grained configuration.

```typescript
const builder = new CatalogBuilder(env);
const processors = defaultProcessors(env);

// Replace or change one or several of the default processors

builder.replaceProcessors(processors);
// ...
const {
  entitiesCatalog,
  locationsCatalog,
  higherOrderOperation,
} = await builder.build();
```

Fixes #5388

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jhaals** [comment]
This looks good to me. @freben do you have any feedback?

**Review by Rugvip — COMMENTED** [review]
Looks good, but I'm a bit worried about patterns that this would encourage. How would you for example remove a given built-in processor? Doing it by index would not be a great idea as that's prolly gonna break in the future. Doing it by filtering and checking `.constructor.name` or something like that kinda works, but is pretty awkward.

How would you use this yourselves if this was added?

**Comment by goober** [comment]
I agree with your concerns @Rugvip and it is not the best solution, I am happy to reconsider how we can improve it to cover our use case. However, now when I have started to use the parser configuration introduced in #5295 it is not too hard to explicitly define the processors that you want and call `replaceProcessors`. 

An alternative is to introduce a method to the builder e.g. `replaceProcessor`, that takes a single instance of a processor and only replace the one matching `.constructor.name` internally in the builder. That way you can keep the logic hidden to the user.

**Comment by freben** [comment]
I've been wanting replacement for a while, if you can add that it would be nice.

As a side note, it's been feeling less and less valuable to have these "implicit" things being added automatically for the user in the builder. I'm wondering if it isn't actually better to just hard-code the list of processors in a default scaffolded `packages/backend/src/plugins/catalog.ts` using `addProcessor`. Then the user can choose themselves what to add, what to replace, and how to order things, over time.

**Comment by goober** [comment]
Closing this since it is not too much effort to use the `replaceProcessors` and add the processors that are relevant for you

**Pull request closed without merging**
