### PR TITLE
Fix link in README

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

Architecture link was broken. Also tweaked the copyright year... it's 2021, the fuuuuuture 🚀 🤖 :hourglass_flowing_sand:

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by adamdmharvey** [comment]
...and btw, my 2020 search reminded, every single code header across the codebase with Spotify AB copyright has only 2020 in it. Haven't ever considered that in a large scale project, but expecting they may need a 2020-2021 update, and maybe just a one line tweak every year? wonder what other project do, never looked at the Linux headers 😁

**Comment by OrkoHunter** [comment]
I thought about looking at Kubernetes license for inspiration. All I got was a set of mixed feelings

https://github.com/kubernetes/kubernetes/blob/21971cd3092817617d204dc5e6742f41ee03fc48/LICENSE#L190

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
> ...and btw, my 2020 search reminded, every single code header across the codebase with Spotify AB copyright has only 2020 in it. Haven't ever considered that in a large scale project, but expecting they may need a 2020-2021 update, and maybe just a one line tweak every year? wonder what other projects do, never looked at the Linux headers 😁

Thanks for the reminder! We briefly talked about updating the headers in a big PR and possibly enforcing 2021 with some linter. I took a peak at some other files in kubernetes/kubernetes and their license headers date back to 2014 😅

**Comment by freben** [comment]
Yeah I'm not a lawyer, but one wonders, can it really be meant that one has to update the year over and over again in the header? Or is that year the year that the copyright was _established_ so to speak

**Comment by jhaals** [comment]
Oh yes that would make perfect sense, fingers crossed that it is the case.

**Review by Rugvip — APPROVED** [review]

**Pull request merged**
