### PR TITLE
Setup Gitpod

### PR DESCRIPTION
**Pull request by bih**
[Gitpod](https://gitpod.io) is an online IDE playground for playing about with the `master` branch as well as a speedy review deployment. It's powered by [Theia](https://theia-ide.org/) which is using the same technology as Visual Studio Code.

I think it's worth trying given that it:
- Significantly lowers the barrier to entry for engineers to play / contribute with Backstage
- If adopted by core team, a smoother review process
- An opportunity to improve the contribution experience for core team and contributors
- Does everything that a review deployment tool would do!

I'm typically a huge fan of the tool. Accompanying this PR you'll **need to install** [the Gitpod GitHub app](https://github.com/apps/gitpod-io) so it can do the following:
- On git push, prebuild deployments (aka `yarn install`) to speed up using Gitpod
- On git push, comment on the PR when the deployment is ready

Not sure if this is on your roadmap, but I'm sure anything that improves contributions would be welcomed with open arms :-)

### CODE REVIEW

**Comment by Rugvip** [comment]
What do you think about adding this to https://github.com/gitpod-io/definitely-gp instead? Not keep on polluting the repo too much, especially with this being a paid service.

**Comment by bih** [comment]
@Rugvip Yep that's fine by me. Can move it over tomorrow or when I next get the chance :)

**Comment by svenefftinge** [comment]
Hi @rugvip, I was about to create a similar PR, when I saw this one 😄 
Just wanted to make sure you are aware that Gitpod is 100% free for open-source.
Also, configuration in definitely-gp doesn't allow to fully leverage the value, as you cannot enable prebuilds. They shave off ~3min waiting time on every start.

Would be great if you could reconsider your decision, as I really like what you are doing here and think that Gitpod and Backstage are very similar and complementary in their mission. ❤️ 

@bih I have splitted the `yarn start` into its two parts, to be able to run the first in the prebuild (`init`) and second on every start.

https://gitpod.io/#https://github.com/svenefftinge/backstage

**Comment by bih** [comment]
@spotify/backstage-core Can you share some more of your thinking? I would suggest trying it and if we don't find it valuable, we can remove it later. It'd just be one file, right?

**Comment by freben** [comment]
@bih Hey, we talked about this at standup today. We'd prefer it if you added the gitpod file if it helps, but do not mention it in the README. Does that sound OK?

**Comment by bih** [comment]
I think it's best actually then if we leave it - maybe it's better after all as it might be introducing too many changes at once. I think it's important for the core team to be sold on it (given it's pointless without the README mention or installing the relevant GitHub app).

Feel free to revisit this later if/when it makes sense 👍

**Comment by freben** [comment]
We thought it better if it did unlock use cases for you and others, but not promoting it. We would not have been against adding the github app, but would perhaps have had to look more at gitpod and get a feel for it before actively using it ourselves.

**Comment by bih** [comment]
@freben That's fair, in that case I would encourage you to give it a try and see if it helps out with your workflow when you get a chance. I'm happy to wait until it's something you'd like to more officially get behind :)

**Pull request closed without merging**
