### PR TITLE
new tutorials

### PR DESCRIPTION
**Pull request by johnson-jesse**
## New Tutorial - Quickstart

Guide for new adopters quickly get up to speed with a standalone app with integrated GitHub authorization and a custom plugin to explore a few API's utilizing GitHub GraphQL work.

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by Rugvip** [comment]
Thanks! Wanna let you know that the core team is away on an off-site (from home), so reviews are gonna be a bit slow.

This one is a bit trickier because of the interaction with https://github.com/spotify/backstage/issues/2243. In general, would you be alright by making this the starting point for #2243 (and the app-variant), but possibly removing some of the emphasis on docker-compose and moving Postgres to be part of the deployment setup instead of local development?

**Comment by johnson-jesse** [comment]
I think I can do that. Sounds like I should break this into two separate parts. Both of the app-variant type. With the first part concerning initial setup and auth integration. The second, (separate document), part would be custom plugin creation and configuration. Will these documents both live in `backstage > docs > tutorials > xxx`? Preference on document naming and titling? There is actually a third part that I didn't cover according to #2243, catalog & publishing.

**Comment by johnson-jesse** [comment]
@Rugvip Please see the changes. Now as two different, hopefully, golden paths. The first, setting up an App from the ground up and configuring GitHub auth provider. The second builds on the first (but still stands on its own) with details on adding a custom plugin and working with various APIs.

**Review by Rugvip — APPROVED** [review]
Looks awesome, and a great starting point for the full https://github.com/spotify/backstage/issues/2243 flow as well! 👍

**Review by stefanalund — APPROVED** [review]
These needs to be hooked up to the `microsite/sidebar.json` and `mkdocs.yml` as well. Otherwise 👍

**Comment by johnson-jesse** [comment]
Updated sidebar.json as requested. Skipping mkdocs.yml @stefanalund ok'ed.

**Pull request merged**
