### PR TITLE
120 characters max allowed

### PR DESCRIPTION
**Pull request by GunnerStraiker1**
## Hey, I just made a Pull Request!

- Backstage will able to load apps with names no longer than 120 characters
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Rugvip** [comment]
Why 120? :grin:

**Comment by freben** [comment]
You probably shouldn't change this in the main project, but rather in your private app.

**Comment by GunnerStraiker1** [comment]
@Rugvip Because there are some apps that are written with that amount of characters, because

**Comment by Rugvip** [comment]
Afaik 63 is taken from https://datatracker.ietf.org/doc/html/rfc1123, so the next logical step is prolly 255. Although as freben mentioned this is something you can configure in your own local deployment with a custom validator

**Pull request closed without merging**
