### PR TITLE
Microsite: a11y fixes

### PR DESCRIPTION
**Pull request by npiyush97**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [X] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
prev blog
blog
now blog
localblog
prev plugins
plugins
now plugins
localplugin
prev docs
dcos
now docs
localdocs

### CODE REVIEW

**Comment by npiyush97** [comment]
96 because of search box in nav

**Comment by npiyush97** [comment]
question not related to this but why we using canary version of docurarus for docs?
i think not a big issue but lighthouse is not happy with algolia docsearch aria-label = "search" 
axetool is happy lighthouse score -4 for that.

**Comment by npiyush97** [comment]
@freben although im not color blind but still white over salmon color is very hard to see here are my suggestion love to here your thoughts.
prev
button
select
new
new

**Comment by npiyush97** [comment]
additional fixes related to #22406

**Comment by freben** [comment]
Yeah we have been saying for some time that we need to get off of the canary.

This looks good I think, but the community and plugin page fixes with underline, could you post screenshot of what those do? And also, remember to DCO sign all of your commits, without that we aren't allowed to merge.

**Comment by npiyush97** [comment]
shifted to #22518

**Pull request closed without merging**
