### PR TITLE
feat: add support for HTTPS proxy for AWS S3 requests in Techdocs

### PR DESCRIPTION
**Pull request by JosiahCraw**
## Hey, I just made a Pull Request!

Sorry for the duplicate, had to fix some branches - And its getting a little late here 😄 

I've added the ability to provide a HTTPS_PROXY URL for Techdocs S3, either as config or via a CLI flag. I debated with myself about the CLI if it would be best to just pull from the environment, please let me know any thoughts. The code added basically just aligns with [AWS documentation for proxies](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-proxies.html). I've excluded HTTP proxy for now but it could be added if required

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]
Looks good to me! Let's see what techdocs-core think.

**Review by agentbellnorm — CHANGES_REQUESTED** [review]
Changes look good! Can you also update this documentation file so that it will show on the website? https://github.com/backstage/backstage/blob/794a87c36c00954fb52a5c96aa5c3065f96333b1/docs/features/techdocs/cli.md

Site: https://backstage.io/docs/features/techdocs/cli/#publish-generated-techdocs-sites

**Comment by JosiahCraw** [comment]
I've updated the CLI reference also including Openstack Swift options

**Comment by JosiahCraw** [comment]
Build failures seem to be due to #16589

**Review by agentbellnorm — APPROVED** [review]
Thanks!

**Pull request merged**
