### PR TITLE
Install TravisCI plugin

### PR DESCRIPTION
**Pull request by dtuite**
As per https://github.com/spotify/backstage/issues/674

### CODE REVIEW

**Comment by freben** [comment]
hey @dtuite sorry i was too slow - there's a conflict to resolve - wanna rebase so we can get this in?

**Comment by dtuite** [comment]
@freben I'm on it. Will need a few mins

**Comment by dtuite** [comment]
@freben rebased

**Comment by dtuite** [comment]
Build failed with

```
Error: Cannot find module 'fs-extra'
Require stack:
- /home/runner/work/backstage/backstage/docs/verify-links.js
```

Which seems unrelated. Any advice?

**Comment by freben** [comment]
Yeah I just got that for a different one too - this happened as part of the big documentation push happening yesterday and today, we're on it

**Comment by freben** [comment]
https://github.com/spotify/backstage/pull/1920

**Comment by freben** [comment]
Done, please try again :)

**Comment by Rugvip** [comment]
And https://github.com/spotify/backstage/pull/1921 :grin:

**Comment by dtuite** [comment]
🚢

**Review by freben — APPROVED** [review]

**Pull request merged**
