### PR TITLE
provide text encoder/decoder automatically

### LINKED ISSUE #19925: 🐛 Bug Report: TextEncoder is not defined error when running `App.test.tsx` and using Kubernetes plugin
### 📜 Description

When we upgraded to the latest next release - `1.18.0-next.3` in we started to get the following error when running the `App.test.tsx` test: 

```shell
FAIL  src/App.test.tsx
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      14 | } from '@backstage/plugin-catalog';
      15 | import {
    > 16 |   EntityKubernetesContent,
         |                           ^
      17 |   isKubernetesAvailable,
      18 | } from '@backstage/plugin-kubernetes';
      19 |
```

We found that the solution was to add the following to our `packages/app/src/setupTests.ts` file: 

https://github.com/backstage/backstage/blob/5f7ce0d289505e26488afbee20d1446a40513ab4/packages/app/src/setupTests.ts#L25C1-L27C34

### 👍 Expected behavior

The test should pass without any errors

### 👎 Actual Behavior with Screenshots

The test fails with the following error:

```shell
FAIL  src/App.test.tsx
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

      14 | } from '@backstage/plugin-catalog';
      15 | import {
    > 16 |   EntityKubernetesContent,
         |                           ^
      17 |   isKubernetesAvailable,
      18 | } from '@backstage/plugin-kubernetes';
      19 |
```

### 👟 Reproduction steps

1. Create a Backstage instance using the `1.18.0-next.3` next release version
2. Setup the Kubernetes plugin, only the frontend steps for this particular bug are needed but make sure to use the `0.10.3-next.3` version of the `@backstage/plugin-kubernetes` package
3. Run `yarn test`

Notice: that the `App.test.tsx` fails with the error: TextEncoder is not defined

### 📃 Provide the context for the Bug.

We were just doing our normal weekly upgrade process when the PR failed due to this test failing.

### 🖥️ Your Environment

This isn't an environment specific problem but the use of the `0.10.3-next.3` version of the `@backstage/plugin-kubernetes` package and running the `App.test.tsx` test

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by freben**
Fixes #19925

### CODE REVIEW

**Comment by awanlin** [comment]
So @Rugvip the thing is that all the users of the Kubernetes plugin that run tests will have their `App.test.tsx` fail without this. More details in this issue: https://github.com/backstage/backstage/issues/19925. I do have a more manual fix in this PR: https://github.com/backstage/backstage/pull/19927

**Review by Rugvip — CHANGES_REQUESTED** [review]
Discussed this some more and tl;dr: it's a very slippery slope that is hard to climb back up

Perhaps #19953 instead?

**Comment by luchillo17** [comment]
The changes look nice, not too sure about using `Object.assign` though, guess it's alright if the 16.x CI tests passes.

**Comment by freben** [comment]
@luchillo17 We're leaning toward https://github.com/backstage/backstage/pull/19953 instead now after some discussions!

**Pull request closed without merging**
