### PR TITLE
Bitbucket cloud discovery support

### PR DESCRIPTION
**Pull request by barticus**
## Hey, I just made a Pull Request!

Bitbucket Cloud discovery support.

When bitbucket.org is discovered as the target for the bitbucket-discovery catalog processor, a scan is performed in a workspace and finds repositories matching the any project and repository regexes in line with the existing bitbucket server implementation.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [n/a] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by barticus** [comment]
Hi,

The Bitbucket API version used for the self hosted bitbucket integration was 1.0, [which is now deprecated for bitbucket cloud](https://support.atlassian.com/bitbucket-cloud/docs/use-bitbucket-rest-api-version-1/).

This meant there were a few type mismatches that needed resolving, and the code got a little bit more verbose in areas to keep it type safe.
For clarity (in this PR at least) i've tried to keep to the following:

1. Specifying "BitbucketCloud" where the functionality was specifically for bitbucket cloud
2. Specifying "20" at the end of type names to indicate they are APIv2 models

If you have a preferred way of doing this, please let me know and I can update the names.

**Comment by freben** [comment]
Oh, seems this one fell between the cracks over summer - sorry about that - would you mind rebasing this and fixing the conflict?

**Comment by barticus** [comment]
hey @freben , funnily enough i just came to prompt about this one!
Merge is all done, let me know if theres anything more needed.

**Comment by barticus** [comment]
Hey @freben , I've fixed the prettier error, please approve the pipeline again and it should be g2g

**Comment by barticus** [comment]
Hey @freben , was there anything more that needed to be done for this? I know there is some improvements (e.g. customize polling length, or better store the last date processed and then only process repo's changed since that date), but they feel like they could be done as a separate PR.

**Comment by freben** [comment]
Yep I am the current goalie again, I'll take a look

**Review by freben — APPROVED** [review]
Alright, this looks good now. The comments below are all optional and could very well be postponed or skipped.

My main question before merging though, is whether you have thoroughly tested this on both the cloud and on-prem versions. I am probably in a worse position than you are for doing those tests so I'd appreciate some feedback on what's been done so far. Just so I get some confidence in not degrading other users' experience :)

**Comment by barticus** [comment]
Hey @freben , thanks, I'll review the comments.

RE testing, this doesn't change the flow for BitBucket on prem, and so I haven't manually tested it. The existing unit tests for BitBucket self hosted/on prem has been left as is to show that they still run as expected.
I have tested it with my work's BitBucket cloud instance though, which is where I found a few issues and also a few optimizations, like being able to send a full search query.

Thanks 😊

**Comment by barticus** [comment]
Hey @freben , I've addressed all PR feedback :) Thanks for the tips!

**Review by freben — APPROVED** [review]
Let's go!

**Pull request merged**
