### PR TITLE
Add acast to adopters

### PR DESCRIPTION
**Pull request by lndbrg**
## Hey, I just made a Pull Request!

Add acast to adopters

### CODE REVIEW

**Comment by lndbrg** [comment]
```
[ { path: 'ADOPTERS.md',
    start_line: 22,
    end_line: 22,
    start_column: 50,
    end_column: 53,
    annotation_level: 'failure',
    title: '[error] Vale.Spelling',
    message: 'Did you really mean \'Olle\'?' },
  { path: 'ADOPTERS.md',
    start_line: 22,
    end_line: 22,
    start_column: 55,
    end_column: 62,
    annotation_level: 'failure',
    title: '[error] Vale.Spelling',
    message: 'Did you really mean \'Lundberg\'?' } ]
```
😒 yes i did

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4598-oietvpvqldqqffcsysfrmb47r1la5f7y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602f9b42fcb22d21ed5a79b5

**Comment by freben** [comment]
Haha! Oh Vale, you're such a nuisance sometimes.

Add to https://github.com/backstage/backstage/blob/master/.github/styles/vocab.txt

**Comment by lndbrg** [comment]
I took the liberty of sorting the vocab file before adding myself, if you don't want that change I can remove it

**Comment by freben** [comment]
That's fine, keeping things neat

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4598-oietvpvqldqqffcsysfrmb47r1la5f7y.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602f9b42fcb22d21ed5a79b5

**Review by freben — APPROVED** [review]

**Pull request merged**
