### PR TITLE
Update nginx deployment to use 1.19 features

### PR DESCRIPTION
**Pull request by onematchfox**
## Hey, I just made a Pull Request!

Given that the nginx frontend example makes use of `nginx:mainline` I thought I'd update it to use some of the newer _features_  available. 

- There is no need to override the `CMD` on the base image to get the custom scripts to run. This can be done simply by adding the custom configuration script to the `/docker-entrypoint.d` folder. See https://github.com/nginxinc/docker-nginx/blob/master/mainline/debian/docker-entrypoint.sh.
- With the above change made, we can now also reap the benefit of support for `envsubst` having been added in 1.19 -  as long as the config is placed in the folder `/etc/nginx/templates/`. See https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119 and https://github.com/nginxinc/docker-nginx/blob/master/mainline/debian/20-envsubst-on-templates.sh for more info.

#### :heavy_check_mark: Checklist

- [x] All your commits have a `Signed-off-by` line in the message. ([more info]())

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thanks! 👍 

I like the changes, but I'm torn on the portability of them. Relying on features in this particular base image will make it harder for people that have their own base images that aren't compatible with this one.

Wondering if there's any input from the community here, do you run with your own nginx base images, and in that case, would it be compatible with these changes? If they're not, do you think it'd be a big deal to port them over?

**Comment by freben** [comment]
Any pointers on how long ago these features were added? If it's on the order of a year or so, it would feel safer to accept :)

**Comment by onematchfox** [comment]
> I like the changes, but I'm torn on the portability of them. Relying on features in this particular base image will make it harder for people that have their own base images that aren't compatible with this one.

Totally appreciate your point. If that's the case then perhaps we should consider setting the base image tag to something other than `mainline`. Running `latest` probably isn't the best idea anyway :wink:  

https://github.com/backstage/backstage/blob/8bd92cff3f0c9c5d794252bb51dda4859829d8bf/contrib/docker/frontend-with-nginx/Dockerfile.dockerbuild#L49 

> Any pointers on how long ago these features were added?

The features were added as part of Nginx `1.19.0` which was released on 26 May 2020 (~11 months ago). See 
https://github.com/nginxinc/docker-nginx/commit/e36b4f57b77618787caae825a72b93f8f40a8f74 and https://github.com/nginxinc/docker-nginx/commit/cd98e75ce640e77633cd79035e41c9a122897fdf

**Review by Rugvip — APPROVED** [review]
Let's :shipit:, it's much cleaner and builds on top of relatively standard stuff. If we end up with a lot of support questions about how to set up custom nginx images we can backtrack or do something else.

**Comment by onematchfox** [comment]
> Let's :shipit:, it's much cleaner and builds on top of relatively standard stuff. If we end up with a lot of support questions about how to set up custom nginx images we can backtrack or do something else.

:shipit: 

Feel free to @ me here or on Discord if questions do come up. Happy to help out.

**Pull request merged**
