### PR TITLE
cli: grab the needed e2e test package dependencies from the create-app template

### PR DESCRIPTION
**Pull request by Rugvip**

### CODE REVIEW

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
@Rugvip i suppose this is to unbreak it :)

**Comment by freben** [comment]
So merge?

**Comment by Rugvip** [comment]
Pushed the wrong commit x)

Yeah this is to unbreak the e2e test for new versions. If it builds, we merge :p

**Comment by freben** [comment]
There we go. Thanks a lot.

**Pull request merged**
