### PR TITLE
Renamed ProgressBar components to *Gauge

### LINKED ISSUE #2227: Rename ProgressBar components to *Gauge
https://github.com/spotify/backstage/blob/1812fd05e6cc27cb1c845020b422d6e82b330183/packages/core/src/components/ProgressBars/CircleProgress.tsx#L80 to `Gauge`

https://github.com/spotify/backstage/blob/1812fd05e6cc27cb1c845020b422d6e82b330183/packages/core/src/components/ProgressBars/HorizontalProgress.tsx#L31 to `LinearGauge`

https://github.com/spotify/backstage/blob/1812fd05e6cc27cb1c845020b422d6e82b330183/packages/core/src/components/ProgressBars/ProgressCard.tsx#L39 to `GaugeCard`

Always get them confused with the `Progress` component and don't remember what they're for until I actually look at them in storybook :p

### PR DESCRIPTION
**Pull request by iamrajiv**
## Hey, I just made a Pull Request!

Fixed: #2227

#### :heavy_check_mark: Checklist

- [X] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [X] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by stefanalund — CHANGES_REQUESTED** [review]
Thanks! You need to also go over the codebase and change imports in all the places where these components are used. Please also change the folder name to `gauges` or similar.

**Comment by stefanalund** [comment]
Any update on this?

**Comment by iamrajiv** [comment]
Sorry for inconvenience @stefanalund, I forgot to update the requested changes before. I have updated now please take a look.

**Review by Rugvip — APPROVED** [review]
Looks good, thanks! 😄

**Review by stefanalund — APPROVED** [review]
Thanks a lot

**Pull request merged**
