### PR TITLE
Included step name and step id into check point key.

### PR DESCRIPTION
**Pull request by acierto**
## Hey, I just made a Pull Request!

Implemented the proposal https://github.com/backstage/backstage/issues/26771 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jvmdc** [comment]
My idea was to just expose the step ID and/or name information in the context, so template creators can add it to their checkpoint key suffix as they see fit. 

If it is always included, it is important that the documentation on checkpoints (https://backstage.io/docs/features/software-templates/writing-custom-actions/#using-checkpoints-in-custom-actions-experimental) indicate that it is (step & action)-specific idempotency rather than just action-specific idempotency as someone else may have a use-case where the step doesn't matter, just that the action is idempotent - I do not have an example on hand however for that.

**Comment by benjdlambert** [comment]
Is the `stepId` not unique enough here? Aren't they unique across all steps? :pray:

**Comment by jvmdc** [comment]
> Is the `stepId` not unique enough here? Aren't they unique across all steps? 🙏

I would hope so :)

My point above was simply that this change enables the behaviour I want, but not necessarily the behaviour someone else may want:
Checkpoint before this PR: Checkpoint key is unique across pipeline -> You can utilize checkpoints to skip code in different steps (even across different actions)
Checkpoint after this PR: Checkpoint key is always step-specific -> Any key suffix only concerns the current step, you can never have cross-step checkpoint keys

I can't really think of a use case for it at present, just something to be aware of for people using checkpoints in the future - It is a step-specific checkpoint

**Comment by acierto** [comment]
`stepId` is unique, I would include `stepName` only to make it human readable, otherwise with many steps, the manual correlation, what step 16 out of 25 can lead to some increased troubleshooting time :)

**Comment by benjdlambert** [comment]
@jvmdc yeah I appreciate your use case - I wonder if there's another way we can do that though. Thinking something like:

`ctx.checkpoint({ key: 'asd', global: true }, () => ...)` or something instead. I'd rather have the ease of creating local checkpoints for the template run and have your use case as something special that we wouldn't recommend unless you needed it.

@acierto thoughts?

**Comment by jvmdc** [comment]
> @jvmdc yeah I appreciate your use case - I wonder if there's another way we can do that though. Thinking something like:
> 
> `ctx.checkpoint({ key: 'asd', global: true }, () => ...)` or something instead. I'd rather have the ease of creating local checkpoints for the template run and have your use case as something special that we wouldn't recommend unless you needed it.

Yeah, I thought your comment related to my original comment, hadn't seen you weren't the PR creator - Sorry! As mentioned, I don't have a concrete use case for a global checkpoint, but someone else might have (especially since that is how checkpoints work currently)

**Comment by benjdlambert** [comment]
> stepId is unique, I would include stepName only to make it human readable, otherwise with many steps, the manual correlation, what step 16 out of 25 can lead to some increased troubleshooting time :)

Hmm, I'm wondering if we should store the `title` for debug data in the checkpoint instead, or do a reverse lookup with the ID. I think the ID's should be human readable already somewhat right? `fetchBase` `publish` etc?

**Comment by acierto** [comment]
@benjdlambert Oh yeah, indeed, id is already humanized, then we can exclude step name, i'll change it.

`ctx.checkpoint({ key: 'asd', global: true }, () => ...)` - maybe let's not do it? 😅 

The case pointed by @jvmdc makes sense, if I would like to have some repetitive action in the same template, I would never want to have it idempotent.

Pushing to repo is a good example btw.

In our case we have also the template where we have to push the code twice, as after the first commit, we should wait for GitLab pipeline to be executed to get the stuff generated and take from there the generated project IDs, which we use to inject as variables to placeholders. 

We don't do very granular steps though, that's why I missed this scenario.

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Let's go with this :tada:

**Pull request merged**
