### PR TITLE
emptystates: add transparent versions

### PR DESCRIPTION
**Pull request by stefanalund**
## Hey, I just made a Pull Request!

Screenshot 2020-10-07 at 08 36 59
Screenshot 2020-10-07 at 08 37 08

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by benjdlambert** [comment]
@stefanalund can we have screenshots 🙏

**Comment by stefanalund** [comment]
Updated @benjdlambert

**Review by marcuseide — APPROVED** [review]
In dark mode, the background (or what used to be the background image) is hardly visible. Is that intended?

**Comment by benjdlambert** [comment]
One for @katz95 I think? Will merge this anyway.

**Pull request merged**
