### PR TITLE
Storybook Integration

### PR DESCRIPTION
**Pull request by mikqi**
## Hey, I just made a Pull Request!

This PR is for integration with storybook #255 
I've just add it at @core package

image

#### :heavy_check_mark: Checklist
- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] [CODEOWNERS](./CODEOWNERS) updated (for new stuff)
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by stefanalund — COMMENTED** [review]
This is awesome! Thanks a lot. 

What would it take to have the Storybook published to e.g. storybook.backstage.io ?

@rugvip @freben @nikek

**Comment by Rugvip** [comment]
@stefanalund Should probably deploy it with GH pages in this or a separate repo. I've pointed storybook.backstage.io to GH pages.

**Comment by stefanalund** [comment]
Since the components live in this repo I think it makes sense to publish to the GitHub Pages on this repo. 

Could definitely be a separate PR though.

**Comment by stefanalund** [comment]
Sorry, needs rebasing.

**Review by stefanalund — COMMENTED** [review]
Getting the following error when I run `yarn build-storybook`:

```
=> Loading create-react-app config.
info => Compiling preview..
ERR! => Failed to build the preview
ERR! TypeScript error in undefined(undefined,undefined):
ERR! No inputs were found in config file '/Users/stefan/code/github/backstage/tsconfig.json'. Specified 'include' paths were '["node_modules/@spotify/web-scripts/config/src"]' and 'exclude' paths were '["**/*.test.*"]'.  TS18003
ERR! 
ERR! 
ERR! asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
ERR! This can impact web performance.
ERR! Assets: 
ERR!   vendors~main.5e551cd26b56e666a7d5.bundle.js (274 KiB)
ERR! entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
ERR! Entrypoints:
ERR!   main (277 KiB)
ERR!       runtime~main.5e551cd26b56e666a7d5.bundle.js
ERR!       vendors~main.5e551cd26b56e666a7d5.bundle.js
ERR!       main.5e551cd26b56e666a7d5.bundle.js
ERR! 
ERR! webpack performance recommendations: 
ERR! You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
ERR! For more info visit https://webpack.js.org/guides/code-splitting/
(node:97190) UnhandledPromiseRejectionWarning: [object Object]
(node:97190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:97190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mikqi** [comment]
> Sorry, needs rebasing.

Done. 👍🏻

> Getting the following error when I run `yarn build-storybook`:
> 
> ```
> => Loading create-react-app config.
> info => Compiling preview..
> ERR! => Failed to build the preview
> ERR! TypeScript error in undefined(undefined,undefined):
> ERR! No inputs were found in config file '/Users/stefan/code/github/backstage/tsconfig.json'. Specified 'include' paths were '["node_modules/@spotify/web-scripts/config/src"]' and 'exclude' paths were '["**/*.test.*"]'.  TS18003
> ERR! 
> ERR! 
> ERR! asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> ERR! This can impact web performance.
> ERR! Assets: 
> ERR!   vendors~main.5e551cd26b56e666a7d5.bundle.js (274 KiB)
> ERR! entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> ERR! Entrypoints:
> ERR!   main (277 KiB)
> ERR!       runtime~main.5e551cd26b56e666a7d5.bundle.js
> ERR!       vendors~main.5e551cd26b56e666a7d5.bundle.js
> ERR!       main.5e551cd26b56e666a7d5.bundle.js
> ERR! 
> ERR! webpack performance recommendations: 
> ERR! You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> ERR! For more info visit https://webpack.js.org/guides/code-splitting/
> (node:97190) UnhandledPromiseRejectionWarning: [object Object]
> (node:97190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:97190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

I think you try build storybook from root project, i've added script e29f550, so you can build it from root project. But it will generate `storybook-static` folder in folder `packages/core`.

**Review by stefanalund — APPROVED** [review]
👏

**Pull request merged**
