### PR TITLE
feat: Moving away from spotify/web-scripts

### LINKED ISSUE #23277: 🚀 Feature: Moving away from `spotify/web-scripts`
### 🔖 Feature description

Move away from the dependecy on `spotify/web-scripts` in the CLI & Microsite for Prettier & ESLint config.

### 🎤 Context

[`spotify/web-scripts`](https://github.com/spotify/web-scripts) is deprecated since December 2023. We depend on it for our Prettier config with `"@spotify/prettier-config"` in the Microsite. In the main workspace we depend on it for the Prettier config as well as using the ESLint Plugin with `"@spotify/eslint-plugin"`. 

Reminded about this by dependabot: https://github.com/backstage/backstage/pull/23259

### ✌️ Possible Implementation

**Prettier:** This should be straigthforward. The current dependency only exports the following config values ([source](https://github.com/spotify/web-scripts/blob/master/packages/prettier-config/index.js)): 
```js
module.exports = {
  singleQuote: true,
  trailingComma: 'all',
  arrowParens: 'avoid',
};
```
Let's check if this isn't enforced already & adjust the current configs if needed.

**ESLint Plugin:** I'm actually not sure if we need this at all. The plugins allows to discourage the use of certain words. Haven't looked into our configs, but if we haven't configured it with custom words it probably does not bring a benefit at the moment. For more context checkout [the code here](https://github.com/spotify/web-scripts/blob/master/packages/eslint-plugin/src/rules/best-practices/no-discouraged-words.ts).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by santoshyadavdev**
## Hey, I just made a Pull Request!

The PR contains change to remove "@spotify/prettier-config" package and add a new `prettierrc.json` to adopt changes related to prettier.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

closes #23277

### CODE REVIEW

**Comment by freben** [comment]
Hey! I noticed that there's a conflict.

**Comment by santoshyadavdev** [comment]
Hey @freben I am on vacation, I will take care of conflict next week. Hope that's ok.

**Comment by santoshyadavdev** [comment]
oops conflict again, I will resolve it soon

**Comment by santoshyadavdev** [comment]
@freben updated the branch again, let me know if you get time to review.

**Comment by santoshyadavdev** [comment]
Hey folks, can you check whats this windows error, this worked in last push

**Comment by santoshyadavdev** [comment]
Closing the PR since no one is ready to review it.

**Pull request closed without merging**
