### PR TITLE
storybook: Upgrade Storybook to version 6

### LINKED ISSUE #2233: Upgrade Storybook to version 6
We are currently on 5.x.: https://github.com/spotify/backstage/tree/master/packages/storybook

https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5

### PR DESCRIPTION
**Pull request by o-farooq**
## Hey, I just made a Pull Request!

upgrade Storybook to version 6
this fixes #2233 

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by Rugvip** [comment]
Thanks!

It looks like all of the stories have more padding around them than before. Do you know if this is an expected change when moving to v6?

**Comment by o-farooq** [comment]
> Thanks!
> 
> It looks like all of the stories have more padding around them than before. Do you know if this is an expected change when moving to v6?

@Rugvip the default story renderer layout is [padded](https://github.com/storybookjs/storybook/blob/6ecfd495763d6c014598b2915946b6d52e5ec6f7/lib/core/src/client/preview/StoryRenderer.tsx) in v6 which adds a 1rem padding. i have updated the `preview.js` to use `fullscreen` which would be same behavior as of 5.x .

**Review by Rugvip — APPROVED** [review]
Looks good!

**Review by freben — APPROVED** [review]
Thanks!

**Pull request merged**
