### PR TITLE
Add Lunar as adopter

### PR DESCRIPTION
**Pull request by JacobValdemar**
Been on this journey with you guys since September 2020

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4696-5wywqebk8yhfcyhpqrgwymsq3aew9aej.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037845bf285af2d8d9839f8

**Comment by benjdlambert** [comment]
@JacobValdemar thanks for this! although you need to run prettier on the `ADOPTERS.md` file 🙈

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4696-5wywqebk8yhfcyhpqrgwymsq3aew9aej.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037845bf285af2d8d9839f8

**Comment by Rugvip** [comment]
Welcome! (?) 😁 

Needs a bit of this, or permission to push to your fork :<

```diff
diff --git a/.github/styles/vocab.txt b/.github/styles/vocab.txt
index 831df202e..b672405d1 100644
--- a/.github/styles/vocab.txt
+++ b/.github/styles/vocab.txt
@@ -272,6 +272,7 @@ untracked
 upvote
 url
 utils
+Valdemar
 validators
 varchar
 winston
```

**Comment by JacobValdemar** [comment]
Thanks 😁 So many checks 🙈

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4696-5wywqebk8yhfcyhpqrgwymsq3aew9aej.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037845bf285af2d8d9839f8

**Review by Rugvip — APPROVED** [review]
And another one: ✔️

**Pull request merged**
