### PR TITLE
Added PlantUML diagrams in backstage.io docs

### LINKED ISSUE #2043: PlantUML diagrams do not appear on backstage.io docs
UML diagrams that appear [on GitHub](https://github.com/spotify/backstage/blob/master/docs/auth/oauth.md) do not appear [in the backstage.io docs](https://backstage.io/docs/auth/oauth#sequence-diagram).

### PR DESCRIPTION
**Pull request by iamrajiv**
## Hey, I just made a Pull Request!

Fixes: #2043

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by Rugvip** [comment]
Thanks!

How was the diagram created? Wanna make sure it's reproducible. Did you see the existing script to generate diagrams?

**Comment by iamrajiv** [comment]
@Rugvip Diagram was already created but was in the wrong folder. I just moved the diagram to correct folder i.e. `assets/auth` and updated the link in `oauth.md`.

**Comment by Rugvip** [comment]
Alright, ok with updating https://github.com/spotify/backstage/blob/master/docs/generate-uml.sh to generate the files to the correct location?

**Comment by iamrajiv** [comment]
@Rugvip I did not run  https://github.com/spotify/backstage/blob/master/docs/generate-uml.sh. Do I have to run this and generate the diagram?

**Comment by Rugvip** [comment]
The existing diagram was generated using that script, and we want that to be reproducible. Since it generates the diagrams to the wrong location, the next person to create a diagram will also end up with a broken one, as well as a duplicate of this one.

Looking closer it might not actually be that the script needs updating at all, perhaps we can leave the existing diagram in place and tweak the link to it instead?

**Comment by iamrajiv** [comment]
@Rugvip Ok, I got it means I have to update https://github.com/spotify/backstage/blob/master/docs/generate-uml.sh  so that whenever we run this script it generates the diagram at the correct location am I correct?

**Comment by iamrajiv** [comment]
@Rugvip I tried to update the image link in but it did not work. It might be a problem with docusaurus build. I think we should generate the diagram in the `assets` folder because all the images are in that only. Can you help me how to run the script and generate the diagram?

**Comment by Rugvip** [comment]
@iamrajiv How to run the script should be described in the script itself. If you're on linux/osx it should be straightforward. If you're on windows you may need GitBash/WSL to execute the script and install plantuml separately.

Regarding generating the script into assets, that should be fine too, given some modifications to the script

**Comment by iamrajiv** [comment]
@Rugvip Please review.

**Review by Rugvip — APPROVED** [review]
Yep, that works too, thanks! 👍

**Review by stefanalund — APPROVED** [review]

**Pull request merged**
