### PR TITLE
fixed issue where scroll position was not reset

### PR DESCRIPTION
**Pull request by PatAKnight**
Signed-off-by: Patrick Knight <pknight@redhat.com>

## Hey, I just made a Pull Request!
Fixes: #15356 

This PR fixes the issue of when navigating to another page in techdocs via link, the new page will retain the vertical position of the old page instead of going to the top. In this PR, I updated the window.scroll({ top: 0}) to document.querySelector('[class^=BackstageHeader]')?.scrollIntoView(). My reasoning was to grab the header and scroll it into view since the window is already classified as at the top of the screen.

Before:
before-scroll-fix

After:
after-scroll-fix

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by agentbellnorm** [comment]
@PatAKnight Thanks for the PR! This has been on our radar, but we haven't had time to look in to it. Really appreciate it!

I think your approach is good, all I'd add is that maybe we should use an "anchor" that is less likely to change. I tried this and it seems to work:
```js
document.querySelector('main')?.scroll({top: 0});
```
This grabs the `<main>...</main>` element which I think is more stable than the class in your suggestion. What do you think?

**Comment by PatAKnight** [comment]
@agentbellnorm I agree that your anchor point is much better than mine.

One thing that I am noticing is some test failures with the output being: 
`document.querySelector(...)?.scrollIntoView is not a function`

I found this [issue](https://github.com/vuejs/vue-test-utils/issues/319) that was fairly similar and had some success implementing this [suggestion](https://github.com/vuejs/vue-test-utils/issues/319#issuecomment-354667621). What I did was added
```
beforeEach(() => {
    Element.prototype.scroll = () => {};
});
```
to [TextSize.test.tsx](https://github.com/backstage/backstage/blob/master/plugins/techdocs-module-addons-contrib/src/TextSize/TextSize.test.tsx) and [ExpandableNavigation.test.tsx](https://github.com/backstage/backstage/blob/master/plugins/techdocs-module-addons-contrib/src/ExpandableNavigation/ExpandableNavigation.test.tsx). There was already a `beforeEach` in [ReportIssue.test.tsx](https://github.com/backstage/backstage/blob/master/plugins/techdocs-module-addons-contrib/src/ReportIssue/ReportIssue.test.tsx#L55). 

What do you think about this solution?

**Comment by agentbellnorm** [comment]
@PatAKnight Ah I see.

I think we want to minimize the risk of future tests breaking, and if we have to add this "polyfil" to each test I think it could be easily missed and confusing.

Usually I have put stuff like this in `setupTests.js`, but I don't know if this will solve the issue for other modules that depend on this package.

I think the safest solution is to just do 
```
const mainElement = document.querySelector('main');
if (mainElement?.scroll) {
    mainElement.scroll({top: 0});
}
```
Even though it's not ideal to adopt the code for tests.

**Comment by PatAKnight** [comment]
@agentbellnorm 
I agree that the suggestion that I brought up could be confusing to someone that does not know the circumstances that led up to the changes. I have went it and updated the PR with your suggestions and it is passing all the tests now. Thanks for the help!

**Pull request closed without merging**
