### PR TITLE
Switch to using Yarn 3

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Thanks to the prep work by @webark in #11374 and initial work by @dschwank in #9619 we can now start using Yarn 3. This PR migrates this main repo to use Yarn 3, and adds a migration guide for apps. It does not switch the `create-app` template to use Yarn 3 since there are some tradeoffs and unknowns with Yarn 3, so I figure we hold off on recommending migration just yet.

A huge benefit of switching to Yarn 3 in this repo is that it'll let us use the `workspace:` version queries, which will reduce the number of merge conflicts significantly. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by marcus-crane** [comment]
I haven't even started using Yarn 2.x 😅

**Comment by webark** [comment]
We switched to yarn 3 about a month ago and have had success. It's plugin system in nice. I don't think it supports the "zero install" feature, but is a nicer experience than yarn 1.

**Comment by webark** [comment]
Oh. one thing tangentially i ran into was that I tried switching all of our internal dependencies to using the "workspace:*", and it all worked, except lerna doesn't know how to handle that url type yet, and we use lerna during the backend build.

https://github.com/lerna/lerna/issues/2564

Is the relevant lerna issue, and they are actively working on it.

The related issue at the end of that also mentions they are adding pnpm support, which we could add in the future, as a side note

**Review by jhaals — APPROVED** [review]
Tiny and digestible 😅

**Review by freben — APPROVED** [review]

**Pull request merged**
