### PR TITLE
roku has a strict policy against its name/logo being used anywhere 

### PR DESCRIPTION
**Pull request by ldemailly**
without a lot of legal paper work

**please also remove from https://backstage.spotify.com/ list** asap

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by ldemailly** [comment]
I realize this was added nearly 3 years ago, but it was a mistake, please remove it from the web page at least, roku doesn't endorse anything without lengthy legal review

**Comment by Rugvip** [comment]
Just to be clear, do you want to keep the early entry in the adopters list or do you want us to merge this PR?

This isn't really the place for requests for https://backstage.spotify.com/, but I'll forward it to the correct people and figure out how we ended up here.

**Comment by jenjamall** [comment]
Hi @ldemailly Can you email me directly (jkelly@spotify.com) and we can resolve the Roku logo issue on backstage.spotify.com? I have a confirmation from Tim Urista granting permission on May 25, 2021 but we're happy to take it down if it violates your policy.

**Comment by ldemailly** [comment]
Done (direct email to @jenjamall ) and yes let's merge this for now too. We may return to Backstage but haven't yet (and again Roku is very specific about what may look like endorsments etc)

**Review by Rugvip — APPROVED** [review]
Alright!

**Pull request merged**
