### PR TITLE
await response errors

### PR DESCRIPTION
**Pull request by freben**
It may be the case that the default error middleware could be rebuilt to support promises too. Don't have time for that right now though

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Good catch!

Lemme see if we can get a lint rule going for that

**Comment by Rugvip** [comment]
Thinking a bit more about it, is this fix actually needed? 🤔

Feels like this should be equivalent to `await Promise.reject(Promise.resolve('nope')).catch(e => e)`, or for a more precise example:

```ts
p = await (async () => { throw Promise.resolve('nope') })().catch(e => e)
```

**Comment by freben** [comment]
I mean the end game is that we give synchronous values to the constructor of the error so they can be read synchronously by consumers. https://github.com/backstage/backstage/blob/7c116bcac7fcb93f86c381ac744fe694a81db03b/packages/errors/src/errors/ResponseError.ts#L82

**Comment by freben** [comment]
Screenshot 2023-05-12 at 11 25 47

**Review by vinzscam — APPROVED** [review]

**Pull request merged**
