### PR TITLE
Setup user agent header for AWS sdk client

### PR DESCRIPTION
**Pull request by yayfeng**
## Hey, I just made a Pull Request!

Adding customUserAgent header in all AWS sdk clients, like here:
https://github.com/backstage/backstage/blob/dadc9960f9ac1e894080992d809df31bd9d350e1/plugins/techdocs-node/src/stages/publish/awsS3.ts#L167
This is to enable users to better track API calls made from Backstage to AWS APIs through things like CloudTrail.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — APPROVED** [review]
nice, thank you!

**Comment by yayfeng** [comment]
Hey @vinzscam Thanks for the review. 

I mis-clicked the close PR button (trying to find the option to merge, then I realize we require two reviewers), it seems the CI process got triggered again and this time the built failed. I don't believe the error is due to my change. Is there a way to re-run the failed job or do you have any suggestions to fix it?

**Comment by yayfeng** [comment]
Unsure what I should do in order to get this PR merged? 

Thanks. 


> This PR has been automatically marked as stale because it has not had recent activity from the author. It will be closed if no further activity occurs. If the PR was closed and you want it re-opened, let us know and we'll re-open the PR so that you can continue the contribution!

**Comment by niallthomson** [comment]
Can this be re-opened?

**Comment by yayfeng** [comment]
@vinzscam @benjdlambert  Can someone please help with re-open this PR pls?

Thanks and have a great summer :)

**Review by benjdlambert — APPROVED** [review]
Nice, thanks :tada:

**Comment by benjdlambert** [comment]
Ah @yayfeng, looks like there's a few conflicts that have crept in here, could you fix those up? :pray:

**Comment by yayfeng** [comment]
@benjdlambert Cheers!

**Pull request merged**
