### PR TITLE
Fix remaining test issues on Windows

### PR DESCRIPTION
**Pull request by Fox32**
#3459 was on the right way but missed some places. Luckily I have a Windows machine at home :laughing: One good thing about home office 😉 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by Fox32** [comment]
@Rugvip is it possible that the e2e test failures comes from #3469?

**Comment by Rugvip** [comment]
@Fox32 in combination with something else then perhaps, #3469 ran e2e tests without any issues

**Comment by Rugvip** [comment]
Prolly is that one though, but not sure how 😁 , will dig a bit

**Comment by Rugvip** [comment]
@Fox32 #3475

**Comment by Fox32** [comment]
@Rugvip Thanks for looking at it! Rebased this one

**Review by freben — APPROVED** [review]

**Comment by Fox32** [comment]
Ah crap, I just tested it for the config-loader package... Looks like there are still more issues...

**Pull request merged**
