### PR TITLE
techdocs-backend: Enhance example documented-component

### PR DESCRIPTION
**Pull request by adamdmharvey**
Signed-off-by: Adam Harvey <adam.harvey@dxc.com>

## Hey, I just made a Pull Request!

Updates the example documented-component which is includes as a showcase for TechDocs features. Supports #4237.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4821-eaxq8xr9hftxirqb9upo4coyjsu9aob5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60414bf4fcb22d7fc1689a0b

**Comment by adamdmharvey** [comment]
Tried to view this in Tugboat, but interesting the documented component is ALWAYS broken it looks like, so can't use that to preview it.

But it looks like this for me in sample:

image

image

**Review by OrkoHunter — APPROVED** [review]
❤️

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4821-eaxq8xr9hftxirqb9upo4coyjsu9aob5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60414bf4fcb22d7fc1689a0b

**Pull request merged**
