### PR TITLE
Create `scaffolder` Incubating Project Area

### PR DESCRIPTION
**Pull request by benjdlambert**
Hey :wave:

So this has been a long time in the making, but we think we're ready to start moving the `scaffolder` to it's own dedicated project area.  Right now, we're looking to start it off as an incubating project area, supported initially by the @backstage/maintainers, with the intention to share some of the reviewing load and ownership of the scaffolder and related plugins.

We're looking to add some more people to this group too, so feel free to reach out here or on Discord if you're interested in becoming a project area maintainer! :pray:

~Welcome to the first member @dagda1 :tada:~

Welcome to the first two members @dagda1 and @acierto :tada:

### CODE REVIEW

**Review by tudi2d — APPROVED** [review]
nice 🎉

**Review by freben — APPROVED** [review]
🥳

**Comment by acierto** [comment]
@benjdlambert Sure, you can include me too. Discord is `bogdan_haarlem`

**Review by dagda1 — APPROVED** [review]

**Review by acierto — APPROVED** [review]

**Review by acierto — APPROVED** [review]

**Review by Rugvip — APPROVED** [review]
:shipit: 🎉

**Pull request merged**
