### PR TITLE
docs: minor typo correction

### PR DESCRIPTION
**Pull request by davidamitchell**
## Hey, I just made a Pull Request!

Minor doco correction

### CODE REVIEW

**Review by freben — APPROVED** [review]
Thanks!

**Comment by freben** [comment]
Hey, I see that we had an underlying Prettier error. I made a PR to fix it, would you mind rebasing on that after it is merged? https://github.com/spotify/backstage/pull/2308

**Comment by davidamitchell** [comment]
@freben sure thing, no worries

**Comment by stefanalund** [comment]
Welcome to Backstage @davidamitchell 🎉

**Pull request merged**
