### PR TITLE
Use cookie cutter installed on host if available

### LINKED ISSUE #2103: Run cookiecutter template without docker
## Feature Suggestion

It would be good to be able to run cookiecutter without requiring that the app has access to the docker socket.

We're running in Kubernetes and mounting the docker socket is:
1. not recommended
2. doesn't work for alternative container runtimes like containerd.

## Possible Implementation

Check if cookiecutter is installed first and use that instead

or

Use a Kubernetes job instead of docker if running in Kubernetes

## Context

Template a repository  without having to have access to a docker socket

image

### PR DESCRIPTION
**Pull request by timja**
## Hey, I just made a Pull Request!

Fixes https://github.com/spotify/backstage/issues/2103

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality - not currently, if this is required I might need some guidance, on how best to pass a mock implementation in a clean way for spawn.
- [x] Regression tests added for bug fixes

### CODE REVIEW

**Review by marcuseide — APPROVED** [review]
Hey @timja, looks good to me!  I'll approve but will wait for more 👀  from the rest of the team before merging.

**Review by freben — APPROVED** [review]
Agreed, looks good. Only concern is that it's a bit "magic" (hidden) that it sometimes picks one runner and sometimes the other. Another solution would have been to add a configuration parameter

```
scaffolder:
  cookiecutter:
    runner: local  # or docker
```

then you would be at liberty to add a local config file (or per env etc) that chooses the local runner if you prefer that.

We would appreciate it if you had the time to make it work like that. If you don't, or prefer to do it separately at a later time, just let us know and we'll merge this to unblock in the meantime.

**Comment by timja** [comment]
> Agreed, looks good. Only concern is that it's a bit "magic" (hidden) that it sometimes picks one runner and sometimes the other. Another solution would have been to add a configuration parameter
> 
> ```
> scaffolder:
>   cookiecutter:
>     runner: local  # or docker
> ```
> 
> then you would be at liberty to add a local config file (or per env etc) that chooses the local runner if you prefer that.
> 
> We would appreciate it if you had the time to make it work like that. If you don't, or prefer to do it separately at a later time, just let us know and we'll merge this to unblock in the meantime.

I'm about to go on holiday for a week, so don't have time right now but, I can hopefully take a look when I get back.

**Comment by freben** [comment]
Then I say we merge and tweak later!

**Comment by mithunkrb** [comment]
Hi @timja , Thank you for implementing this feature. It would be very helpful if you can point me to some docs mentioning the usage steps for the same?

**Pull request merged**
