### PR TITLE
`skip to content` accessibility fix

### PR DESCRIPTION
**Pull request by snehaljos**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by snehaljos** [comment]
Fix for issue #18042

**Comment by snehaljos** [comment]
Hi @benjdlambert , Please review this PR.

**Comment by benjdlambert** [comment]
@backstage/discoverability-maintainers can I get a review on this please? It's an accessibility change that I'm not 100% sure on.

**Comment by aitherios** [comment]
Hi @snehaljos, thank you for your contribution! It might take me a bit longer to be able to take a look into it, I will contact another maintainer if I'm unable to return in a resonable time.
For the moment it took a look into the CI and it's failing with `Namespace 'React' has no exported member 'JSX'.` on a couple of checks.

**Comment by benjdlambert** [comment]
@aitherios I think a rebase will fix those issues, was a problem in the main branch.

**Comment by snehaljos** [comment]
Anything to do from my side?

**Comment by benjdlambert** [comment]
@snehaljos yeah you will need to rebase this branch in order to make the build green.

**Comment by snehaljos** [comment]
@benjdlambert How to do that ?

**Comment by benjdlambert** [comment]
On the branch, you can do `git pull origin/master --rebase && git push --force-with-lease`

**Comment by snehaljos** [comment]
@benjdlambert Rebasing is done.

**Comment by snehaljos** [comment]
Hi @aitherios , Any update on this PR.

**Comment by aitherios** [comment]
@snehaljos, I've just reviewed the PR. Thanks again for the fix.
@tikabom, wdyt?

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
