### PR TITLE
Updated Playlist docs

### PR DESCRIPTION
**Pull request by awanlin**
Signed-off-by: Andre Wanlin <67169551+awanlin@users.noreply.github.com>

## Hey, I just made a Pull Request!

Updated Playlist plugin docs:

- Updated `playlist` plugin README to include note about installing backend plugin and added images for the various features
- Updated `playlist-backend` plugin README to remove `IdentityClient` import in example as it is not used and made minor change to headings

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @kuangp, seems like we are doing a lot of chatting today. I setup the Playlist plugin the other day and ran into a few things, nothing major but figured I'd help get it up to date. If you could give this a review when you have time that would be great. Thanks in advance!

**Review by kuangp — APPROVED** [review]
LGTM! Thanks for updating the docs!

**Review by Rugvip — APPROVED** [review]
Nice, thank you! 👍 🎉

**Comment by awanlin** [comment]
@Rugvip thanks 😄

**Pull request merged**
