### PR TITLE
Add examples for github:deployKey:create scaffolder actions

### PR DESCRIPTION
**Pull request by parmar-abhinav**
## Hey, I just made a Pull Request!

Contribution of github:deployKey:create examples as part of https://github.com/backstage/backstage/issues/18832

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by parmar-abhinav** [comment]
Hi @Rugvip, @tudi2d

I am participating in the ongoing Hacktoberfest event, and the deadline for the event is quickly approaching.

Could you please spare a few moments to review my submission and please provide feedback if some changes are needed. It will help in ensuring the success of my participation.

Thank you.

**Review by acierto — APPROVED** [review]

**Comment by parmar-abhinav** [comment]
Thank you for reviewing this PR. @benjdlambert Can you please check this.

**Comment by parmar-abhinav** [comment]
@benjdlambert Can this PR be merged.

**Comment by parmar-abhinav** [comment]
Hi @dagda1 

Can you please check if this PR can be merged.

**Review by dagda1 — APPROVED** [review]
👍

**Pull request merged**
