### PR TITLE
feat(CostInsights): support a display friendly name prop for projects

### PR DESCRIPTION
**Pull request by kuangp**
Signed-off-by: Phil Kuang <pkuang@factset.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by ryanvazquez — CHANGES_REQUESTED** [review]
👋 @kuangp Nice addition! Thanks for the PR!

One minor change - The [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) is preferred instead of logical OR operator when testing for falsey values.

**Comment by kuangp** [comment]
> 👋 @kuangp Nice addition! Thanks for the PR!
> 
> One minor change - The [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) is preferred instead of logical OR operator when testing for falsey values.

@ryanmvazquez thanks for the tip! Updated my change per your suggestion.

**Review by ryanvazquez — APPROVED** [review]

**Comment by ryanvazquez** [comment]
Ah, one more thing. Prefix the changeset filename with `cost-insights` so it will appear in our changelog.

`.changeset/gorgeous-dancers-hope.md ` -> `.changeset/cost-insights-gorgeous-dancers-hope.md`

**Comment by kuangp** [comment]
> Ah, one more thing. Prefix the changeset filename with `cost-insights` so it will appear in our changelog.
> 
> `.changeset/gorgeous-dancers-hope.md ` -> `.changeset/cost-insights-gorgeous-dancers-hope.md`

@ryanmvazquez done.

**Pull request merged**
