### PR TITLE
feat: initiate EventBroker as service instead extension

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

this allows to use eventbroker as a dependency in plugins like signals. also having it as an extension is dangerous as it might be overwritten by different plugins; instead if an application wants to use different broker, it can replace the default service factory.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by pjungermann** [comment]
@drodil I have already worked on PR #22344

**Comment by drodil** [comment]
> @drodil I have already worked on PR #22344

Hah, great 👍 Didn't see that, just wanted to fill in the cap with the signals service so made this 😆

**Comment by pjungermann** [comment]
Yes, I had the signals plugin also on my radar. We need to add event support to other event users like some catalog modules as well. I've planned to work on this as a follow-up whenever that PR is settled. 👍 

Would be great if you could share your thoughts and feedback at the other PR, too.

**Comment by drodil** [comment]
> Yes, I had the signals plugin also on my radar. We need to add event support to other event users like some catalog modules as well. I've planned to work on this as a follow-up whenever that PR is settled. 👍
> 
> Would be great if you could share your thoughts and feedback at the other PR, too.

Awesome! I will check the other PR. This PR is on the other hand, backward compatible with the previous EventBroker implementation so external plugins would not need to migrate. But if it's in the plans, then those plugins just have to live with it.

**Pull request closed without merging**
