### PR TITLE
Fix blinking animation bug for Status Running component

### LINKED ISSUE #704: Status Running should blink
## Expected Behavior

Status Running should blink. CSS seems to be there but is not working:

```
running: {
    animation: 'blink 0.8s step-start 0s infinite',
    backgroundColor: theme.palette.status.running,
  },
  '@keyframes blink': {
    '50%': {
      backgroundColor: theme.palette.status.background,
    },
  },
```

## Current Behavior

Screenshot 2020-05-02 at 15 17 39

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes #704

Reference documentation https://material-ui.com/guides/migration-v3/#styles

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
🎉

**Comment by OrkoHunter** [comment]
I didn't expect GitHub to render GIF too. Very neat 😄 

animation-gif

**Comment by stefanalund** [comment]
Doesn’t look like it’s using the (dark) background though 😅

**Comment by OrkoHunter** [comment]
@stefanalund Yes! New bug discovered :D

**Comment by OrkoHunter** [comment]
Looks good in light mode.

chrome-capture

**Comment by OrkoHunter** [comment]
Umm, even in light mode, the "background color" is actually white and not the background color of the theme. 🤔

**Review by freben — APPROVED** [review]

**Comment by stefanalund** [comment]
Want to see if you can fix that or should we be happy with this improvement?

**Comment by OrkoHunter** [comment]
@stefanalund I think this looks good now 😄

dark
light

**Review by stefanalund — APPROVED** [review]
👏🏼

**Pull request merged**
