### PR TITLE
Updating techdocs-cli to fully facilitate a Backstage like environment using the `--preview-app-bundle-path` flag

### PR DESCRIPTION
**Pull request by sqsp-rwatkins**
## Hey, I just made a Pull Request!

I discovered some issues when running `techdocs-cli serve` and using our Backstage app and the upstream Backstage app using the `--preview-app-bundle-path` flag.
The issues boiled down to a few things:
1. The HttpServer not proxying requests to
    1. `*/static/docs/default/component/local/`
    2. `*/metadata/entity/default/component/local`
    3. `*/metadata/techdocs/default/component/local`
    4. `*/sync/default/component/local`
2. The `entity_metadata.json` file was not created. This is requested by the request to `*/metadata/entity/default/component/local`.
I have added the `--catalog-file` flag to the generate command. It will use the catalog file to generate the `entity_metadata.json` file and place it in the `site` folder

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by sqsp-rwatkins** [comment]
Just waiting on a review

**Comment by sqsp-rwatkins** [comment]
Bump. Waiting on a review

**Comment by sqsp-rwatkins** [comment]
Not stale. Waiting on a review from techdocs maintainers.
@Rugvip is there any way I can get this looked at? I've added an issue to describe the issue: https://github.com/backstage/backstage/issues/18180

**Comment by anthr76** [comment]
I'm facing this issue as well :(

**Pull request closed without merging**
