### PR TITLE
catalog-backend: read all relations at once

### PR DESCRIPTION
**Pull request by freben**
Make sure to batch read relations instead of one by one.

This is not addressing the heart of the issue of #3534, but is a related improvement nonetheless.

### CODE REVIEW

**Comment by freben** [comment]
This currently has no changeset since it is completely internal and just an optimization. Should it have one anyway?

**Comment by Rugvip** [comment]
Best to add a `patch` changeset just to get this shipped to people? :grin:

What kinda speedup does this give?

**Comment by freben** [comment]
Ok I'll add a patch later then.

Haven't clocked it yet honestly more than to the extent that the entire spotify org gets read in ~300 ms all things included (using curl), on sqlite, on dev. The diff will probably be highly dependent on the database and latency to it and the amount of  congestion on the connection pool etc. I can try it out on a local pg as well, but I'm not sure we can glean much of batching benefits under those unrealistic circumstances (no load, no delay, and on the other hand, dockerised db, on a laptop, ...)

**Comment by Rugvip** [comment]
@freben Thinking we wanna make sure that this is a decent improvement at least, since it makes the code a bit more complex. Batching things into single transactions wouldn't necessarily guarantee a speedup either right? It may speed up the individual operations, but reduce overall throughput due to increased contention.

**Comment by freben** [comment]
Not sure about that. It was the sheer insanity of "makes tens of thousands of individual db requests for a simple list request" that made me tweak this. Where a single ms extra delay to the db leads to multiple seconds longer runtime.

**Comment by freben** [comment]
Of course, the ACTUAL fix is probably to instead make a big join with the entities table, based on the filter conditions. This is a stop gap until we restructure a bit, since the old way felt unworkable for databases of any significant size.

**Review by Rugvip — APPROVED** [review]
Realized both the old and new solutions are within a single transaction anyway, so having that execute quicker is gonna be better regardless. Stuff I was talking about would need a different kind of refactor 😅

**Comment by freben** [comment]
Gotta say I do appreciate the question though. We should set up at least a basic mock data generator so we're able to get some level of reproducible performance testing going. Could run it and paste into PRs as a basic proof that it doesn't massively worsen or break things. Could also be awesome to run nightly and track the output - after all, it seems the current performance level is a regression.

**Pull request merged**
