### PR TITLE
New scaffolder backend module for Nasti templating engine

### PR DESCRIPTION
**Pull request by adamrdrew**
## Hey, I just made a Pull Request!

Hello Backstage team! This PR adds a new scaffolding plugin to use the [Nasti template engine](https://github.com/adamrdrew/nasti). I'm the developer and maintainer for Nasti and I'd be really excited to get support for it into Backstage to hopefully expose more people to it and drive adoption. Nasti is different from engines like cookiecutter because it leaves the template project as valid source code, making the lives better of developers who have to maintain complex templates with lots of change. Nasti also offers powerful validation and scope features that traditional templating systems can't.

The patch I'm submitting here basically takes the fetch:cookiecutter plugin you already ship and modifies it to work with nasty. It passes tests and I have used it locally to generate projects and it works. This is my first time working with the Backstage codebase - and I'm not a TS / JS dev so I probably made boneheaded mistakes. Let me know what I need to improve.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ x] Added or updated documentation
- [ x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin)) (trying to figure this out)

### CODE REVIEW

**Comment by adamrdrew** [comment]
I don't know why that check failed. It doesn't seem to be anything related to my contribution and when I run the failed step locally it works fine:

```
$ {
    [[ "$(yarn --version)" =~ "1.*" ]] && yarn install --frozen-lockfile || yarn install --immutable
} > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo "Command succeeded"
else
    echo "Command failed"
fi
Command succeeded
```

I tried to retest but I don't think your bot responds to `/retest` or it wont list to me :) any input is appreciated.

**Comment by adamrdrew** [comment]
hello! just checking in and seeing if there's anything I need to do or I can do to help. contributing to a large project for the first time is tough because every project has different rituals and requirements and checks and its hard to sort it all out. if there's anything yall need me to do I'm very happy to do it. I'd love to see this contribution accepted!

**Comment by freben** [comment]
Hey, everyone's away at the moment - check the readme. We'll be back in a bit

**Comment by benjdlambert** [comment]
Hey apologies :wave:

We've been slammed a little bit recently so this has been on my list for a while to reply back to, so thanks for the patience!

We're actually exploring the possibility of moving some of the things out of the main repo, so would it be possible for you to host this under your own org and publish to your own namespace in NPM? There's some discussion ongoing in this thread too #20266 

We'd be happy to accept a contribution to add your plugin to the `plugins` page though https://backstage.io/plugins.

Does this seem OK? :pray:

**Comment by camilaibs** [comment]
Hi @adamrdrew , just a 

> Hey apologies 👋
> 
> We've been slammed a little bit recently so this has been on my list for a while to reply back to, so thanks for the patience!
> 
> We're actually exploring the possibility of moving some of the things out of the main repo, so would it be possible for you to host this under your own org and publish to your own namespace in NPM? There's some discussion ongoing in this thread too #20266
> 
> We'd be happy to accept a contribution to add your plugin to the `plugins` page though https://backstage.io/plugins.
> 
> Does this seem OK? 🙏

Hi @adamrdrew 👋🏻 I hope you've had a chance to see Ben's comments, let us know if there's anything we can support you with this 🙂

**Comment by adamrdrew** [comment]
Hello! Sorry I was away for a while but getting caught back up on this. I'd be happy to host this as my own plugin, I'd just need some guidance on how to do that. I was able to figure out how to develop and test this in situ in the app. Is there a guide for how to publish a plugin and consume it in backstage? Thanks!

**Comment by adamrdrew** [comment]
I found this so I will go through it https://backstage.io/docs/plugins

**Comment by camilaibs** [comment]
> Hello! Sorry I was away for a while but getting caught back up on this. I'd be happy to host this as my own plugin, I'd just need some guidance on how to do that. I was able to figure out how to develop and test this in situ in the app. Is there a guide for how to publish a plugin and consume it in backstage? Thanks!

Hi @tudi2d would you have any recommendations?

**Pull request closed without merging**
