### PR TITLE
Fixing Snyk vulnerability SNYK-JS-ZOD-5925617 by upgrading zod packages to latest

### PR DESCRIPTION
**Pull request by Thutm**
## Hey, I just made a Pull Request!

Addressing SNYK-JS-ZOD-5925617 by upgrading zod to latest in packages found with depends. Relied on yarn why for depends list. Will resolve issue #21777 

ref: 
https://security.snyk.io/vuln/SNYK-JS-ZOD-5925617
https://github.com/backstage/backstage/issues/21777

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Thutm** [comment]
Didn't squash my commits or sign them all. Will fix.

**Comment by Thutm** [comment]
Test case failing on depends. emotion may need to lock/rollback versions on csstype for now? https://github.com/frenic/csstype/issues/189

**Comment by freben** [comment]
This doesn't fix the problem right? The lockfile doesn't remove any vulnerable resolutions.

**Comment by freben** [comment]
To be clear, I don't mind this fix - but just noting that we already resolved to a fixed version (it was already in-range of the previous range as well), and so could anyone adopting Backstage too. However we _also_ have a transitive dep on `zod@npm:~3.18.0` which ultimately [gets pulled in by `@oriflame/backstage-plugin-score-card@npm:^0.7.0`](https://github.com/backstage/backstage/blob/c6c6be1e35e83785cb751081d61629c6ca0b9da9/yarn.lock#L14411). And THAT does not have a fix in-range, and there's no new release of that plugin that bumps to a newer `core-components` to circumvent it.

So I'm wondering if the actual fix is to remove the dependency on that plugin, or contact their author to see if they can address it.

**Review by freben — APPROVED** [review]
I'll merge this since it still moves us somewhat forward, but let's also consider the other zod depencency branch that lingers behind as per the above

**Comment by raphaelbp12** [comment]
> Test case failing on depends. emotion may need to lock/rollback versions on csstype for now? [frenic/csstype#189](https://github.com/frenic/csstype/issues/189)

Will this PR fix this issue?

**Comment by freben** [comment]
No, that's unrelated.

**Pull request merged**
