### PR TITLE
Added optional color to TrendLines

### PR DESCRIPTION
**Pull request by inrumi**
## Hey, I just made a Pull Request!

Added the color prop to TrendLine from the Sparklines props types.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

image

image

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4699-ird6d7coyotm2wdztodhjyzgd3d4wva2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037d081fcb22d7002606f5a

**Comment by Fox32** [comment]
👍 

Can you please provide a changeset for the core package?

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4699-ird6d7coyotm2wdztodhjyzgd3d4wva2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037d081fcb22d7002606f5a

**Comment by inrumi** [comment]
> 👍
> 
> Can you please provide a changeset for the core package?

I added the changeset, it was supposed to be patch instead of minor? or what's the reason FOSSA failed?

**Comment by Fox32** [comment]
It should be patch, as we are below version 1.0.0.

The failing fossa check is unrelated, you can ignore it.

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4699-ird6d7coyotm2wdztodhjyzgd3d4wva2.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6037d081fcb22d7002606f5a

**Review by Rugvip — APPROVED** [review]
Thanks! and yep, very much a why not :grin:

If we want to support a custom color function in the future we can do that too on top of this

**Pull request merged**
