### PR TITLE
fix: load k8s info with only label selector query

### PR DESCRIPTION
**Pull request by fidelcoria-aa**
[Docs](https://backstage.io/docs/features/kubernetes/configuration#surfacing-your-kubernetes-components-as-part-of-an-entity) say `label selector takes precedence over the annotation/service id.` but 
```
annotations:
  'backstage.io/kubernetes-id': dice-roller
```
is always required. updated logic to allow for only label selector (without backstage.io/kubernetes-id)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [n/a] Added or updated documentation
- [n/a] Tests for new functionality and regression tests for bug fixes
- [n/a] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by fidelcoria-aa** [comment]
fyi @karlhaworth

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4612-dxtylagvydvkovxlzmxkncvdwyw1zhjl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6030465e65f817ab14f58bdf

**Comment by freben** [comment]
Hi! Can you check if this was covered by #4469 and close yours if it was? Sorry that it took some time for that to get merged.

**Comment by adamdmharvey** [comment]
A good suggested PR. I think for me it also brings up some further clarifications.

* Kuberentes can be surfaced as a tab on an entity.  Generally at the moment, tabs are always shown.
* Theoretically, though not yet, it could also be exposed as a card on an entity. (e.g., showing only errors? this doesn't exist yet)
* Most plugins have a const like `isFooAvailable` which is triggered by the existance of an annotation in the entity meta data file.  I don't think this plugin does this yet?
* The lack of this also triggers the missing annotation display in a card, but this plugin already does this on the tab.
* However, the missing annotation ONLY tells you to use the exact ID, it does not suggest you can use the label selector (as you're helping clarify with this PR):
  image
* So I wonder if either this PR< or another, should clarify the annotation section in alignment with this same PR?
* And/or also to add some sort of boolean flag to know whether an entity has (or SHOULD have) any K8S components.

**Comment by fidelcoria-aa** [comment]
> Hi! Can you check if this was covered by #4469 and close yours if it was? Sorry that it took some time for that to get merged.

I looked through the code on that pr but it seems to have the same problem.

@adamdmharvey those sound like good improvements. for this Pr I will focus on aligning to the documentation. how's this for clarifying the `missing annotation` section?

image

**Comment by freben** [comment]
ok maybe I misunderstood then. I thought this was for the same purpose

https://github.com/backstage/backstage/pull/4469/files#diff-e46e11cc4e2a093354006c505b48334e264fcf534a454a16658c0b1c90b85108R83

**Review by freben — COMMENTED** [review]
Hey @fidelcoria-aa - I think we're ready to merge this, but could you just remove the yarn changes first?

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4612-dxtylagvydvkovxlzmxkncvdwyw1zhjl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6030465e65f817ab14f58bdf

**Comment by fidelcoria-aa** [comment]
do you mean resolve the merge conflicts? Done :tada:!
or would you like me to manually revert the yarn.lock? I ran `git checkout upstream/master -- yarn.lock`

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4612-dxtylagvydvkovxlzmxkncvdwyw1zhjl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6030465e65f817ab14f58bdf

**Review by freben — APPROVED** [review]

**Pull request merged**
