### PR TITLE
feat: Make okta scopes configurable

### PR DESCRIPTION
**Pull request by alldoami**
Right now, there's a default list of scopes available, but we want to make it configurable for users to add scopes if wanted.
Related to this comment: https://github.com/backstage/backstage/pull/12359#issuecomment-1183826172

To add your own scopes, add a list of `scopes` to your `app-config.yaml`. Users cannot add scopes that are not a part of this list: https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/implementations/auth/okta/OktaAuth.ts#L27-L35.

Example of `app-config` dict:
```
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    okta:
      development:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_AUDIENCE}
        scopes: ['openid', 'email', 'profile', 'offline_access', 'groups']
```

For those needing `prettier` instructions (this is my first time contributing to backstage):
1. Run `yarn install` at the root directory `backstage/`
2. Run `yarn prettier --write .` in the directory of where your changed files are, or you can run at root and fix globally (will take some time but fool proof).

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by DavidZemon** [comment]
@alldoami, this looks perfect, thank you. Can the property be added to https://backstage.io/docs/auth/okta/provider?

**Comment by alldoami** [comment]
Hmm do I need to create a `docs` PR? Checks don't look like they will run with the `documentation` tag.

**Review by Rugvip — COMMENTED** [review]
Thank you for the PR!

You can actually already do this in your own app by passing a custom API factory to createApp, see for example https://github.com/backstage/backstage/blob/master/packages/app/src/apis.ts. Any API that you pass to createApp will override the ones defined in app-defaults

**Comment by Rugvip** [comment]
Although it might make sense to tweak the default scopes though, perhaps you could repurpose this PR for that?

**Comment by DavidZemon** [comment]
> Although it might make sense to tweak the default scopes though, perhaps you could repurpose this PR for that?

@Rugvip, that's exactly how I would describe what this PR already does.

**Comment by benjdlambert** [comment]
I think what @Rugvip is saying is that you can already do this with code, so what's the benefit of doing this in config instead? 

You can achieve this today by doing something like this:

```ts
// packages/app/src/apis.ts
export const apis: AnyApiFactory[] = [
  createApiFactory({
    api: oktaAuthApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      oauthRequestApi: oauthRequestApiRef,
    },
    factory: ({ discoveryApi, oauthRequestApi }) => {
      // you can even load them from config here if you wanted to yourself?
      return OktaAuth.create({
        discoveryApi,
        oauthRequestApi,
        environment,
        defaultScopes: ['my scopes here']
      });
    },
  }),
]
```

**Comment by alldoami** [comment]
@benjdlambert I guess that is harder to figure out how to do rather than adding a small line in the config

**Comment by DavidZemon** [comment]
@benjdlambert , thank you posting that. Somehow I missed that `defaultScopes` was a property on that constructor param and thought I had to copy the entire `OAuth2.create()` call, not `OktaAuth.create()`. Given the shorter answer now available, I'm not sure it's worth adding a new config option.

But, I'm quite happy going either way. If this PR gets merged, we'll use the config to configure scopes. If not, we'll use `OktaAuth.create()`.

**Comment by alldoami** [comment]
I figured it out! It turns out that you can be assigned to too many okta groups 😅, we had to include a better regex expression (https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_oauth#value - we use terraform to manage our okta apps). We also need to include the `groups` scope. I can close this PR for now, as it looks like the above comment solves this without adding new configuration.

**Pull request closed without merging**
