### PR TITLE
feat(scaffolder): use virtualization with MultiEntityPicker

### PR DESCRIPTION
**Pull request by kmikko**
## Hey, I just made a Pull Request!

Use [virtualization](https://v4.mui.com/components/autocomplete/#virtualization) with MultiEntityPicker. This fixes performance issues with large data sets. Fixes https://github.com/backstage/backstage/issues/25243.

### Testing
Not sure how you would test this with `testing-library` as the issue manifests itself only in real browser environment. However have tested this locally by comparing behaviour between `master` branch and this as follows:

- Generate `catalog-info.yaml` containing a large number (~5k will do it) of entities using a script like so:
```sh
#!/bin/bash

# Check if exactly one argument is passed
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <number_of_entries>"
  exit 1
fi

# Check if the argument is a positive integer
if ! [[ "$1" =~ ^[0-9]+$ ]]; then
  echo "Error: Argument must be a positive integer."
  exit 1
fi

# Number of entries to generate
NUM_ENTRIES=$1

# Output file
OUTPUT_FILE="generated-$NUM_ENTRIES.yaml"

# Create or clear the output file
>"$OUTPUT_FILE"

# Generate YAML entries
for ((i = 1; i <= NUM_ENTRIES; i++)); do
  cat <<EOL >>"$OUTPUT_FILE"
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-app-$i
  title: example-app-$i
spec:
  lifecycle: experimental
  type: backstage-frontend
  owner: maintainers
---
EOL
done

echo "Generated $NUM_ENTRIES entries in $OUTPUT_FILE"
```
- Include entities in app config
```yaml
# app-config.yaml
...
catalog:
    ...
    - type: file
      target: ../../generated-10000.yaml
      rules:
        - allow: [Component]
```
- Start the app with `yarn dev` and wait until all entities have been ingested
- Open `Custom Field Explorer` from http://localhost:3000/create/edit and select `MultiEntityPicker`
- Open dropdown menu. Scrolling, searching and selecting items should work as expected without lag. Whereas compared to `master` branch browser (tested with latest Chrome) quickly becomes unresponsive and finally hangs:
 
Screenshot 2024-06-19 at 9 16 51

I have tested this with 5k, 10k and 100k entities and in all cases the input remains responsive. Here's demo with 100k entities

https://github.com/backstage/backstage/assets/2776729/d5307928-d66d-4fd2-8fe0-c2a2705ede16

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by benjdlambert — APPROVED** [review]
Nice! Let's go with this! :tada:

**Comment by ionition** [comment]
Hi @kmikko, you used these calculations to specify the height of the "VirtualizedListbox", why do you need this calculation: "Math.max(itemSize, itemsToShow * itemSize - **0.5 * itemSize**)" (bold part) ?
This makes the last element only half displayed. If this part is deleted, the elements fit in the box.
annotely_image
annotely_image (1)

**Comment by kmikko** [comment]
> Hi @kmikko, you used these calculations to specify the height of the "VirtualizedListbox", why do you need this calculation: "Math.max(itemSize, itemsToShow * itemSize - **0.5 * itemSize**)" (bold part) ? This makes the last element only half displayed. If this part is deleted, the elements fit in the box. annotely_image annotely_image (1)

Hey @ionition! So the idea was to give user a visual feedback if the list contains more items than are being displayed. So something like this:
Screenshot 2024-08-08 at 20 09 58
With hindsight I should have also tested this with a small number of items. Good catch anyway, definitely not working as intended. Should be rather easily fixed though.

**Comment by ionition** [comment]
Thank you!

**Pull request merged**
