### PR TITLE
catalog-backend: relax validation of full text query field

### LINKED ISSUE #19499: 🐛 Bug Report: Calls to CatalogApi.queryEntities results in 400 (fullTextFilterFields must be url encoded)
### 📜 Description

With the following call (in my own code, but very similar to https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityOwnerPicker/useQueryEntities.ts#L48):
```
      const response = await catalogApi.queryEntities({
        fullTextFilter: {
          term: initialRequest.text || '',
          fields: [
            'metadata.name',
            'kind',
            'spec.profile.displayname',
            'metadata.title',
          ],
        },
        filter: { kind: ['User'] },
        orderFields: [{ field: 'metadata.name', order: 'asc' }],
        limit,
      });
```
I get a 400 error with the following response body:
```
{
    "error": {
        "name": "InputError",
        "message": "Parameter 'fullTextFilterFields' must be url encoded. Its value may not contain reserved characters.",
        "stack": "InputError: Parameter 'fullTextFilterFields' must be url encoded. Its value may not contain reserved characters"
    },
    "request": {
        "method": "GET",
        "url": "/entities/by-query?filter=kind=User&limit=20&orderField=metadata.name,asc&fullTextFilterFields=metadata.name,kind,spec.profile.displayname,metadata.title"
    },
    "response": {
        "statusCode": 400
    }
}
```

### 👍 Expected behavior

This API call should return a successful response.

### 👎 Actual Behavior with Screenshots

The API call returned a 400, see error response above.

### 👟 Reproduction steps

Invoke the API call above from client code.

### 📃 Provide the context for the Bug.

I first saw this bug in 1.17.0 (upgrading from 1.15.0), but it also exists in 1.17.2.

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by Rugvip**
🧹 @sennyeya, right? 😅 

Fixes #19499

### CODE REVIEW

**Comment by sennyeya** [comment]
@Rugvip Can we add `allowReserved:true` to all items under a `parameters:` key? That way we're defaulting to the old parsing for every param.

Going forwards, I think I can add this to the OpenAPI linting command so it continues to be enforced.

**Review by sennyeya — APPROVED** [review]
Thanks for the quick turnaround! LGTM 🎉

**Comment by Rugvip** [comment]
x-all-the-parameters

**Review by freben — APPROVED** [review]

**Comment by jslott2sigma** [comment]
@Rugvip Thanks for the quick fix, much appreciated! I see that the fix will be released in about a month or so, for those of us who have already upgraded to 1.17.2, any suggestions on how to proceed? Downgrade to either 1.15.x or 1.16.x? Or are you considering cutting a bug fix release that include this? Thanks!

**Pull request merged**
