### PR TITLE
chore: migrate all rjsf packages to v5 only

### PR DESCRIPTION
**Pull request by JounQin**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @JounQin, just a heads up that there might be changes needed for this as I'm not sure this version of RJSF v5 is intended to be supported by the Scaffolder and the `scaffolder/next` is what will support it and be the future path forward, more details here: https://backstage.io/docs/features/software-templates/testing-scaffolder-alpha

CC @benjdlambert would be good to get your eyes on this one 👀

**Comment by benjdlambert** [comment]
Hey :wave: thanks for this!

The problem that we have is that we can't do this just yet without a breaking release of the scaffolder as we depend on the types from react-jsonschema-form for custom field extensions.

We're planning remove the old versions in a very soon upcoming release which will do exactly what this PR does by removing the old components and replacing them with the new things under the `next` folder.

**Comment by JounQin** [comment]
The problem I'm meeting is that, when I install `@rjsf/core` manually in my plugin, it is actually `v5` by default which will be conflict with backstage's plugins, and results a lot of duplicate rjsf packages. And I've used [`patch-package`](https://github.com/ds300/patch-package) to replace all rjsf packages to v5 in our own code bases which works just fine.

> We're planning remove the old versions in a very soon upcoming release

Glad to hear, is there any schedule for doing this? Or is this PR a good start to go?

**Comment by benjdlambert** [comment]
@JounQin what's the use case for installing `@rjsf/core` in a plugin? What are you trying to do?

We will probably merge the removal of the older method after the next mainline release which is next Tuesday, which means it will then sit in the `-next` release for some time before being promoted to the mainline release 1.16 I think.

**Comment by JounQin** [comment]
> what's the use case for installing @rjsf/core in a plugin? What are you trying to do?

We are just using `rjsf` to build dynamic forms in our own plugins. Something like here

https://github.com/backstage/backstage/blob/0407eca01db456ba60b81ab7b8315c0a463e30ea/plugins/home/src/components/CustomHomepage/WidgetSettingsOverlay.tsx#L80

**Comment by benjdlambert** [comment]
Ah, but you're saying that you get weird typescript issues or something when you use the local dependencies?

I think in the meantime you can include the latest dependencies in the same way that we currently do for the `@backstage/plugin-home` plugin 

https://github.com/backstage/backstage/blob/8ab52c27914a96591b47b23476f482ee681b06cf/plugins/home/package.json#L46-L49

I created #18251 as the ticket to track the work to make `scaffolder/next` the default.

**Comment by JounQin** [comment]
> Ah, but you're saying that you get weird typescript issues or something when you use the local dependencies?

Yep, when we install `@rjsf/core` as `v5` (by `yarn --cwd xxx add @rjsf/core`), I don't know why some versions are incorrect causing typing issues. But never mind, we've just bypass this issue by patching.

> I created https://github.com/backstage/backstage/issues/18251 as the ticket to track the work to make scaffolder/next the default.

Great! Should I keep this PR open, or just close it then?

**Comment by benjdlambert** [comment]
I think we can close this PR as it will be taken care of with the ticket itself if that's OK? :pray:

**Pull request closed without merging**
