### PR TITLE
Update `@material-ui/lab` to `4.0.0-alpha.61`.

### PR DESCRIPTION
**Pull request by timbonicus**
It seems that checks passed in #13866, giving this upgrade another go. All tests pass locally.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hmmmm. This library scares me a bit. Anything in particular that made you want to do the upgrade?

Looking in the main repo, I see that packages apparently have a mixture of exact and `^`, and 57 and 61. And it's a bit telling that the yarn.lock file doesn't have any changes to the actual lab block as such... We were already _mostly_ on 61.

Did you run it locally as well to go around at least in the default experience to see if there's anything apparently amiss?

**Comment by freben** [comment]
I'll also note - there's a strong desire to get the MUI5 migration going, which would mean replacing this library entirely with `@mui/lab` instead. Maybe it's risky to do this migration at this time, when the MUI5 move would render it moot anyway?

**Comment by timbonicus** [comment]
@freben No compelling reason for the upgrade, certainly might make sense to skip it and close this in favor of MUI5 work if that's moving forward.

**Comment by freben** [comment]
Alright, let's close for now then. Getting a bit nervous about the version ranges instead of fixed version as well... Thanks though! Hope the MUI5 thing gets going asap.

**Pull request closed without merging**
