### PR TITLE
Feature flag for experimental templates

### PR DESCRIPTION
**Pull request by acierto**
## Hey, I just made a Pull Request!

We would like to have a possibility to hide "experimental" templates under a feature flag. 
The template could be good enough to start testing it, but keeping it visible for all users is a bit too early. 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @acierto :wave:

Thanks for this! So we had a chat amongst ourselves, and I think that we might want to tackle this in a slightly different way.

I think that the addition of the lifecycle to the spec is fine, but I wonder if we can take a slightly different approach for the filtering. We can either drop the feature flag entirely, and it just be an option to filter on like the `/catalog` page with the `namespace` dropdown so that it doesn't even show unless you do have templates in the `catalog` with different `lifecycle` properties, or we back up a little bit and provide a `filter` function to the router that can filter them client side before they get put into the `TemplateGroups`. And in that we can provide a function which checks the feature flags, allowing you to provide an feature flag or key or any condition in there?

Does one of these sound like a reasonable approach?

**Comment by acierto** [comment]
> Hey @acierto 👋
> 
> Thanks for this! So we had a chat amongst ourselves, and I think that we might want to tackle this in a slightly different way.
> 
> I think that the addition of the lifecycle to the spec is fine, but I wonder if we can take a slightly different approach for the filtering. We can either drop the feature flag entirely, and it just be an option to filter on like the `/catalog` page with the `namespace` dropdown so that it doesn't even show unless you do have templates in the `catalog` with different `lifecycle` properties, or we back up a little bit and provide a `filter` function to the router that can filter them client side before they get put into the `TemplateGroups`. And in that we can provide a function which checks the feature flags, allowing you to provide an feature flag or key or any condition in there?
> 
> Does one of these sound like a reasonable approach?

Filtering out is I think a good one. I was preparing yet another PR to be able to hide templates on some other conditions 🤣 
As right now all templates are visible, and we have the cases when we want to not show templates in TemplateList. So I vote for option 2 😄

**Comment by acierto** [comment]
@benjdlambert What kind of contract do you see to implement it? I was thinking to do it like this (where **hideWhen**)

Screenshot 2023-03-08 at 09 28 12

**Comment by benjdlambert** [comment]
I think something like `templateFilter` is probably the most sane, that gets given a `TemplateEntity` or whatever :()

**Comment by acierto** [comment]
> I think something like `templateFilter` is probably the most sane, that gets given a `TemplateEntity` or whatever .

Can you please elaborate a bit more? You mean same as above but renamed to `templateFilter`?

**Comment by benjdlambert** [comment]
Yep exactly :)

**Pull request closed without merging**
