### PR TITLE
docs(adr): Created an ADR for MSW

### PR DESCRIPTION
**Pull request by benjdlambert**
## Hey, I just made a Pull Request!
- Here's the ADR that closes this RFC: #1205 

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by freben — APPROVED** [review]
Only thing I'm missing then, is a way to ensure that no accidentally unmocked calls get sent through. Does the library guarantee that, or should we establish such a guard in some other way?

**Comment by stefanalund** [comment]
@benjaminr please add this to the rest of the docs and nav before merging.

**Comment by benjdlambert** [comment]
@freben - not sure if it will mock by default, I can investigate. Otherwise a simple handler in the jest setup of `server.use('*')` should suffice.

**Comment by freben** [comment]
Cool. Then maybe we can put that in the setupTests file in the plugin template

**Comment by Fox32** [comment]
Maybe it is important to mention, that MSW doesn't work together with `require('jest-fetch-mock').enableMocks();` that is in multiple `setupTests.ts` files. I had a bit trouble adding tests with MSW to backstage because of mocking twice 😆

**Review by stefanalund — APPROVED** [review]

**Comment by stefanalund** [comment]
Please also add to docs TOC in /docs/README.md

**Review by Rugvip — APPROVED** [review]
👍 , just need to

> also add to docs TOC in /docs/README.md

**Comment by Rugvip** [comment]
Oh and 👍  to never allowing any unmocked calls through, those should always just make the test explode, maybe segfault and burn the rack too. No manual step should be involved in setting that up either :p

**Comment by benjdlambert** [comment]
@Rugvip created https://github.com/spotify/backstage/issues/1755 to cover the `create-plugin` boilerplate

**Pull request merged**
