### PR TITLE
added type predicates for entities

### PR DESCRIPTION
**Pull request by alexrybch**
Signed-off-by: Alex Rybchenko <arybchenko@box.com>

## Hey, I just made a Pull Request!
These type predicates are already used in couple plugins, maybe we could just add single source of truth (maybe `catalog-common` will be a better place).
I will also add tests if you approve this idea :)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Hmm, how come you want this rather than `isKind('Component')`, etc? :grin:

**Review by Rugvip — COMMENTED** [review]
Ah, I realized these are not related to the entity switch conditions and should go somewhere else. Perhaps in the `catalog-model` package?

**Comment by alexrybch** [comment]
> Ah, I realized these are not related to the entity switch conditions and should go somewhere else. Perhaps in the `catalog-model` package?

Yeah, those are more typescript related :)
 I will move them to `catalog-model`.

**Review by benjdlambert — APPROVED** [review]
Thanks for this 🙏

**Pull request merged**
