### PR TITLE
Bump git-url-parse to 11.4.4

### PR DESCRIPTION
**Pull request by n2ygk**
## Hey, I just made a Pull Request!

Bumps version of git-url-parse. See #4148 where this is used.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thanks! 👍

**Comment by n2ygk** [comment]
@Rugvip Is there an easier way to do this than what I used?
```
yarn lerna exec 'sed -i.bak -e "s/\"git-url-parse\": \"^11.4.3\",/\"git-url-parse\": \"^11.4.4\",/" package.json'
```

**Review by OrkoHunter — APPROVED** [review]
I wonder why the `yarn.lock` hasn't been updated. Did you run `yarn` or `yarn install` after the change?

**Comment by n2ygk** [comment]
> I wonder why the `yarn.lock` hasn't been updated. Did you run `yarn` or `yarn install` after the change?

Oops. Here it is.

**Comment by OrkoHunter** [comment]
Awesome, thanks! 😁

**Pull request merged**
