### PR TITLE
feat(scaffolder-backend): add more config options for github repos (WIP)

### PR DESCRIPTION
**Pull request by wejendorp**
To use the scaffolder plugin internally we need to set up the repo to
our conventions.  This change allows us to specify default behaviors for
signed commits, security fixes, read/write permissions and branch
protection options.

New configuration options:

```yaml
scaffolder:
  github:
    # Customize created repos:
    readers:
      - 'myorg/developers'
    writers:
      - 'myorg/ci'
    enableAutomatedSecurityFixes: true
    enableVulnerabilityAlerts: true
    branchConfig:
      # key/value for each branch to configure
      master:
        allowForcePush: false
        allowDeletions: false
        requireSignedCommits: true
        enforceAdmins: true
        # requirePRReviews must be enabled when setting dismissStaleReviews,
        #  requireCodeOwnerReviews or requiredApprovingReviewCount
        requirePRReview: true
        dismissStaleReviews: false
        requireCodeOwnerReviews: true
        requiredApprovingReviewCount: 1
        # Enforce status checks.
        #  Must be enabled to enforce requiredUpToDateBeforeMerging or requiredContexts
        requireStatusChecksBeforeMerging: true
        requireUpToDateBeforeMerge: false
        requiredContexts:
          - 'tests'
```

#### Docs

Question: is more docs needed than adding the above example config?

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by freben** [comment]
Hi! Thanks for this.

Sorry to be a downer, but I think it would be best to hold off with this change. There's a lot of work being done on the fundamentals of the scaffolder right now, and in the new solution there is likely to be a lot clearer room for how to do what you are looking to achieve.

Until that gets in, to get you unblocked, would it make sense for you to replace the GitHub Publisher with your own tweaked implementation instead during backend init?

**Comment by wejendorp** [comment]
Hi @freben 

No worries, I'll find a way to use these configs without adding it to the official plugin.

I suppose now is not the time to suggest adding the publisher as a plugin either? I mean if the fundamentals are being reworked. It seems like you are already building towards the community being able to do something like:

```yaml
scaffolder:
	publishers:
		- '@myorg/github-publisher'
		# or
		- './src/publisher.js'
```

```js
// publisher.js
export class GithubPublisher implements PublisherBase {
	// ...
}
```

Is that a correct understanding (roughly?).

---

As for what to do right now, do you mean fork the scaffolder-backend, or are you saying there is a way to load a custom publisher without doing that?

**Comment by freben** [comment]
The new system is still taking form, but it would probably rather be on the form of a builder class being used [here](https://github.com/backstage/backstage/blob/master/packages/backend/src/plugins/scaffolder.ts#L34), onto which you can do like `builder.addAction(id, impl)` to build up a little library of actions. Then you can reference those actions in your templates in a generic way. So you could add your entirely own kind of publish or anything else. But again, to be determined. Soon. :)

That link above, is also where you find the current code for where the different more fixed stages get defined and injected.

**Comment by wejendorp** [comment]
Oh awesome, thanks for the references. I'll close this PR then. :+1:

**Pull request closed without merging**
