### PR TITLE
Make it possible to enable useLongPollingLogs in scaffolder plugin

### PR DESCRIPTION
**Pull request by acierto**
Signed-off-by: bnechyporenko <bnechyporenko@bol.com>

## Hey, I just made a Pull Request!

To prevent this problem (https://github.com/backstage/backstage/issues/5535) I'd like to use long polling instead.
Currently there is no way to enable it.
Suggesting to use a configuration with the same approach how it is done for airflow           [airflow plugin](https://github.com/backstage/backstage/blob/d4a8c683bebcdc2914c94eaf59ebab10faff3007/plugins/apache-airflow/src/plugin.ts#L41)

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
So there is a way, it's just not documented I believe. It's basically enabled by doing this following for the `scaffolderApiRef` and providing the `useLongPollingLogs` to the constructor when providing the instance to use.

I'd much rather like to keep it this way rather than growing the config for now, could we perhaps change this PR so that we can provide explicit code for local overrides of the API instead as documentation rather than updating the config?

**Comment by acierto** [comment]
@benjdlambert can you give an example how to achieve it? As I still didn't get it from the reply how you can affect `ScaffolderClient` constructor via `scaffolderApiRef`

**Comment by benjdlambert** [comment]
In `packages/app/src/apis.ts` you might do something like this:

```ts
 createApiFactory({
    api: scaffolderApiRef,
    deps: {
      discoveryApi: discoveryApiRef,
      identityApi: identityApiRef,
      scmIntegrationsApi: scmIntegrationsApiRef,
      fetchApi: fetchApiRef,
    },
    factory: ({ scmIntegrationsApi, discoveryApi, identityApi, fetchApi }) =>
      new ScaffolderClient({
        discoveryApi,
        identityApi,
        scmIntegrationsApi,
        fetchApi,
        useLongPollingLogs: true,
      }),
  }),
  ```

**Comment by freben** [comment]
> Ehm, that's a backstage codebase :) I don't want to copy paste full scaffolder module in our codebase to do the one line change.

That's absolutely not what he's suggesting though. This is about pasting a few lines in your own project, that give custom constructor arguments to the regular open source client library. This is _the_ way that one customizes APIs in Backstage.

**Comment by acierto** [comment]
Ok, I see now, it works based on api registry approach. 
Not very obvious from the first glance. 

It's possible to work with that for now.
But for maintainability it can be a nightmare when you have many overridden plugins. 
At some point you'll change/add/remove something from default factory.

Having some configurations as a meta-programming to switch on/off is a better alternative. 
Same as you did for [airflow plugin](https://github.com/backstage/backstage/blob/d4a8c683bebcdc2914c94eaf59ebab10faff3007/plugins/apache-airflow/src/plugin.ts#L41), users don't override factory there, but could base url via configuration

**Comment by freben** [comment]
Strengths and drawbacks - migrating config based things is also hard and implies customer manual intervention too, when things change drastically later down the line. And these factories are meant to always be very plain constructor calls without logic or significant injection of default values or so; all of the work should happen in the constructor, and the factory should only do wiring.

Is it OK if we close this one for now as per benjdlambert's recommendation?

**Comment by benjdlambert** [comment]
To be clear, I think there's still some value in this PR, but it would be in the form of documentation referencing how you can do it in your own installation for now rather than adding a config value to override it if that's OK? :pray:

**Comment by acierto** [comment]
Hey @benjdlambert @freben ! Please have a look at the updated documentation for this scenario.

**Pull request merged**
