### PR TITLE
Move `catalog` and `scaffolder` installation instructions to READMEs

### PR DESCRIPTION
**Pull request by timbonicus**
Featured prominently in the Backstage docs are installation instructions for the `catalog` and `scaffolder` plugins (and related backends), which come **pre-installed** by default with `npx @backstage/create-app`. The only reason you'd need these docs is if you previously _removed_ some of the default plugins.

Since this is much more of a corner case than expected usage, we can make these instructions much less prominent. This makes getting started a bit more clear for the average adopter.

This PR moves installation instructions for these packages to the README files instead of the main docs. I cleaned up and standardized these instructions as well. The `scaffolder` installation doc had a few more minor configuration points, so I renamed that doc and shortened it.

TechDocs could use the [same treatment](https://backstage.io/docs/features/techdocs/getting-started#adding-techdocs-frontend-plugin), but I grew weary after the first two.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Yup, I think this makes sense, thanks!

+1/2/3 @backstage/maintainers? :shipit:?

**Review by Rugvip — COMMENTED** [review]
Oh right, changesets are needed for the README updates to be released 😅

**Comment by freben** [comment]
Yeah I'm thinking that this is generally what we want to do. Perhaps even for all plugins, not just the ones that are already in the create-app skeleton already

**Comment by freben** [comment]
I guess the drawback being that if you want some overarching installation docs that touch on frontend, backend and proximity and third party system configuration etc... Then the instructions get fragmented

**Comment by timbonicus** [comment]
@freben Hmm yeah, non-core plugins don't have a great spot in general to add nice documentation. There's some sparse READMEs, but would be nice to have `plugins.backstage.io/kafka` or similar where each plugin could have a dedicated docs site. Then READMEs can link to that where appropriate, and leave the README for more dev-oriented details.

**Review by benjdlambert — APPROVED** [review]

**Review by OrkoHunter — APPROVED** [review]

**Review by iamEAP — APPROVED** [review]

**Review by jhaals — APPROVED** [review]

**Pull request merged**
