### PR TITLE
TechDocs: Disallow style tags in techdocs documentation pages

### LINKED ISSUE #2323: TechDocs triggers vulnerable tags warnings in browser console
## Expected Behavior

No browser warnings

## Current Behavior

Browser console when viewing techdocs shows:

> Your `allowedTags` option includes, `style`, which is inherently
vulnerable to XSS attacks. Please remove it from `allowedTags`.
Or, to disable this warning, add the `allowVulnerableTags` option
and ensure you are accounting for this risk.

<details>
<summary>Stacktrace</summary>

    at Reader (webpack-internal:///../../plugins/techdocs/src/reader/components/Reader.tsx:43:19)
    at article
    at Content (webpack-internal:///../core/src/layout/Content/Content.tsx:53:3)
    at div
    at Page (webpack-internal:///../core/src/layout/Page/Page.tsx:45:17)
    at TechDocsPageWrapper (webpack-internal:///../../plugins/techdocs/src/reader/components/TechDocsPageWrapper.tsx:32:3)
    at TechDocsPage (webpack-internal:///../../plugins/techdocs/src/reader/components/TechDocsPage.tsx:31:90)
    at Route (webpack-internal:///../../node_modules/react-router/index.js:34:673)
    at Routes (webpack-internal:///../../node_modules/react-router/index.js:37:804)
    at AppRoutes
    at div
    at SidebarPage (webpack-internal:///../core/src/layout/Sidebar/Page.tsx:56:89)
    at Root (webpack-internal:///./src/components/Root/Root.tsx:100:17)
    at Route (webpack-internal:///../../node_modules/react-router/index.js:34:673)
    at Routes (webpack-internal:///../../node_modules/react-router/index.js:37:804)
    at SignInPageWrapper (webpack-internal:///../core-api/src/app/App.tsx:245:18)
    at Router (webpack-internal:///../../node_modules/react-router/index.js:36:23)
    at BrowserRouter (webpack-internal:///../../node_modules/react-router-dom/index.js:63:23)
    at AppRouter (webpack-internal:///../core-api/src/app/App.tsx:256:26)
    at CssBaseline (webpack-internal:///../../node_modules/@material-ui/core/esm/CssBaseline/CssBaseline.js:65:31)
    at WithStyles (webpack-internal:///../../node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)
    at AppThemeProvider (webpack-internal:///../core-api/src/app/AppThemeProvider.tsx:78:29)
    at AppContextProvider (webpack-internal:///../core-api/src/app/AppContext.tsx:31:31)
    at ApiProvider (webpack-internal:///../core-api/src/apis/ApiProvider.tsx:40:24)
    at Provider (webpack-internal:///../core-api/src/app/App.tsx:191:25)
    at App
    at AppContainer (eval at ES6ProxyComponentFactory (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)
    at HotExportedApp (eval at ES6ProxyComponentFactory (webpack-internal:///../../node_modules/react-hot-loader/dist/react-hot-loader.development.js), <anonymous>:14:7)

</details>

## Steps to Reproduce

Start example app up and click view techdocs.
you don't need to actually have it configured

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

### PR DESCRIPTION
**Pull request by hooloovooo**
## Hey, I just made a Pull Request!

Allow vulnerable tags in techdocs. Currently we need to allow script tags in techdocs. This removes the warning we're getting in console.

Closes  #2323 

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by Rugvip** [comment]
@hooloovooo what's the security implication of this?

If it enables XSS, is it possible to make XSS an opt-in?

**Comment by emmaindal** [comment]
@hooloovooo can we only allow the style in the allowVulnerableTags config? That was what the warning was about if I remember correctly. And if not, have you looked into other sanitizers we could use?

**Comment by hooloovooo** [comment]
> @hooloovooo what's the security implication of this?
> 
> If it enables XSS, is it possible to make XSS an opt-in?

I've been thinking about this for a bit, and the way i see it not allowing script tags is a second line defense. If your storage is compromised people could but bad javascript in docs.

Disabling scripts would break the techdocs page right now. I think we could remove the need for it down the line by building techdocs with a mkdocs theme that doesn't require javascript.

**Comment by hooloovooo** [comment]
> @hooloovooo can we only allow the style in the allowVulnerableTags config? That was what the warning was about if I remember correctly. And if not, have you looked into other sanitizers we could use?

Ohh, never mind. I'm certain i got complaints about script being allowed, but i'm not getting it now. Will see if we can deal with `style` tags in a better way.

**Comment by Rugvip** [comment]
@hooloovooo Alright, so script tags are stripped out from markdown in mkdocs before this then?

**Comment by hooloovooo** [comment]
> @hooloovooo Alright, so script tags are stripped out from markdown in mkdocs before this then?

Yea seems like it. This is only CSS, which could also be an issue. Looking around to see if there's any good ways to sanitize linked css files. Still shouldn't be an issue if you keep your storage safe, but extra security is always a good thing.

**Comment by hooloovooo** [comment]
Ok, new potential fix. Seems like it's only inline style tags that are discouraged by sanitize-html. Not sure why linked stylesheets are find, but inline is bad. Removing those seems to have a minimal impact on the rendering so i'm opting for just washing away style tags.

**Review by emmaindal — APPROVED** [review]

**Comment by emmaindal** [comment]
@hooloovooo approved, you could add a test in https://github.com/spotify/backstage/blob/master/plugins/techdocs/src/reader/transformers/sanitizeDOM/index.test.ts if you want to make sure the stylesheets are kept after sanitizing

**Review by emmaindal — APPROVED** [review]

**Comment by emmaindal** [comment]
@hooloovooo maybe just edit the title and description to this PR to avoid confusions in the future!

**Pull request merged**
