### PR TITLE
storybook: switch to Webpack 5 and fix yarn-path in .yarnrc

### PR DESCRIPTION
**Pull request by Rugvip**
Fixes the yarn install in `storybook/`

### CODE REVIEW

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Hmm I wonder if this bump broke webpack4 in storybook? https://github.com/backstage/backstage/pull/12483

**Comment by benjdlambert** [comment]
Yep, looks like we might have to rollback the yaml PR, or roll storybooks webpack forward to support the `?.` syntax. https://github.com/eemeli/yaml/issues/397

**Comment by benjdlambert** [comment]
This is probably the better issue https://github.com/eemeli/yaml/issues/394

**Comment by Rugvip** [comment]
Oh fml, nah tbh I'll try to give Webpack 5 bump another go, being on v4 is bringing a bit too many headaches

**Pull request merged**
