### PR TITLE
feat: support fetching tags in git client

### PR DESCRIPTION
**Pull request by mspiegel31**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

## Description

For scaffolder actions that would like to make decisions based on the tag history of a git repo, it's useful to be able to fetch the tags!

### CODE REVIEW

**Comment by mspiegel31** [comment]
I'm not quite sure why these E2E tests are failing;  at a quick glance they look like timeouts.  I don't have permissions in github, but maybe they could just be run again?

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
@mspiegel31 you'll need to run prettier on the edited files to get the build to pass, but this is looking good :tada:

**Comment by mspiegel31** [comment]
@benjdlambert sorry to bug you, but I'm a little stumped about these `Test 20.x` CI failures.  I've tried the following steps to get them to pass:
1. run `prettier` on changed files
2. generate a new api report for `packages/backend`: `yarn build:api-reports packages/backend-common`
3. sync my fork with the latest `master` changes and rebased this branch on top of it.

I can't really understand why these changes would cause failures in `plugins/kubernetes-backend/src/service/KubernetesFetcher.test.ts`, but I'm fairly sure they're unrelated to the changes I've made.  Would you have a sec to look at this PR or the state of `master` and give me some guidance?

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks for this! :tada:

**Pull request merged**
