### PR TITLE
[TechDocs] Refactor the techdocs transformers to return `Promise`s and await all transformations

### PR DESCRIPTION
**Pull request by dhenneke**
Some of the transformations in the Reader are async, but the component doesn't await them. This sometimes lead to the issue that the content is added to the shadow dom, even though the transformations weren't fully executed yet. This might also mean that the sanitisation hasn't been completed yet.

Example: One issue is that the browser might look for assets (css files or images) in the wrong location and only gets the correct url in the next update:

image

(the correct url is `http://localhost:7000/api/techdocs/static/docs/default/Component/backstage/assets/stylesheets/main.fe0cca5b.min.css` but it tries `http://localhost:3000/docs/default/Component/backstage/assets/stylesheets/main.fe0cca5b.min.css` first)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by OrkoHunter — APPROVED** [review]
Wohooo! I think this will close https://github.com/backstage/backstage/issues/6015 🙂

**Comment by dhenneke** [comment]
@OrkoHunter Do you await another review or can I merge it?

**Comment by OrkoHunter** [comment]
Looks like @iamEAP moved it to in review column on the board.

**Comment by iamEAP** [comment]
Hey @dhenneke,

I tried pulling this down locally and experimenting, but I'm noticing that navigation within a TechDocs site (using the left-hand nav) seems to be broken on the `documented-component` for example.  Any idea why?

**Comment by dhenneke** [comment]
> I tried pulling this down locally and experimenting, but I'm noticing that navigation within a TechDocs site (using the left-hand nav) seems to be broken on the `documented-component` for example. Any idea why?

@iamEAP what do you mean with "broken"? It works on my machine™️, at least mostly.

I think I know what you mean; do you get a white page when you navigate too fast? I primarily tested it in combination with #6491, but it seems there is a race-condition if the hook is triggered too often. Whenever a dependency of the `useAsync` hook is updated, it restarts the rendering, but doesn't cancel any previous renderings. This wasn't very different before, but I never seen that happening, yet.

What happens is the following:

1. Only `path` is updated, but the `content` is still old -> The base url doesn't match the path that mkdocs assumed, so the relative css files are not rewritten correctly. This leads to the `cssPage.addEventListener('load', ...` never being called and the thus the opacity never being reset.
2. `content` is updated -> The base url now matches the expected state of mkdocs and the `load` event is triggered. However, for some reason, _1._ was slower than _2._, and we get the content of _1._. But that content can never finish and we are stuck on a white page 😞. Note that this will also happen if the docs page links to a non-existing CSS file for whatever reason.

I get errors like this which confirm this hypothesis in my opinion:
```
Refused to apply style from 'http://localhost:7000/api/techdocs/static/docs/default/Component/assets/stylesheets/main.fe0cca5b.min.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

---

I would prefer to have #6491 merged first. But this is still a problem because a user that navigates very fast, could still trigger it  even with the debounced `path`&`content` update timing.

**Comment by dhenneke** [comment]
I refactored the transformation orchestration a bit. I used `useEffect` like before and made sure that any prior execution is cancelled correctly. This makes the PR independent of #6491, although they now have conflicting changes. But that should be solvable after one is merged.

**Review by iamEAP — APPROVED** [review]
Excellent!  Thanks @dhenneke.

**Pull request merged**
