### PR TITLE
Reset permission to default after mkdtemp command

### PR DESCRIPTION
**Pull request by dweber019**
## Hey, I just made a Pull Request!
Reset permission to default after mkdtemp command.
You can see the background in Discord https://discord.com/channels/687207715902193673/714754240933003266/924606903122792469

In short: I found that by using mkdtemp the permission is set to 700. This blocks the copy process if you build the docs locally. If I chmod to 777 or 755 in the container at the right time (just before copying) if works for me.

You can experience this if you run backstage in a docker file like this with all techdocs settings set to local:

The base node:16-alpine3.14-mkdocs image we build as a starting point.
```
FROM docker.io/node:16-alpine3.14

RUN apk --no-cache update \
    && apk --no-cache upgrade \
    && apk --no-cache add python3 py3-pip \
    && apk --no-cache add gcc musl-dev openjdk11-jdk curl graphviz ttf-dejavu fontconfig \
    && rm -rf /var/cache/apk/*

# Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.12.jar/download && echo "a3d10c17ab1158843a7a7120dd064ba2eda4363f  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar

RUN pip install --upgrade pip && pip install mkdocs-techdocs-core==0.2.1

# Create script to call plantuml.jar from a location in path
#   When adding TechDocs to the Backstage Backend container, avoid this
#   error (OSError: [Errno 8] Exec format error: 'plantuml') by using the
#   following RUN command instead:
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
# RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

ENV NODE_TLS_REJECT_UNAUTHORIZED=1 \
    CYPRESS_DOWNLOAD_MIRROR=https://xxx/cypress-mirror/ \
    NG_CLI_ANALYTICS=ci

COPY .npmrc /root/
```

And the backstage image we build:
```
# Stage 1 - Create yarn install skeleton layer
FROM base-images/node:16-alpine3.14-mkdocs AS packages

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages
# Comment this out if you don't have any internal plugins
# COPY plugins plugins

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM base-images/node:16-alpine3.14-mkdocs AS build

WORKDIR /app
COPY --from=packages /app .

RUN yarn install --frozen-lockfile --network-timeout 600000 && rm -rf "$(yarn cache dir)"

COPY . .

RUN yarn tsc
RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies

# Stage 3 - Build the actual backend image and install production dependencies
FROM base-images/node:16-alpine3.14-mkdocs

WORKDIR /app

# Copy the install dependencies from the build stage and context
COPY --from=build /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 600000 && rm -rf "$(yarn cache dir)"

# Copy the built packages from the build stage
COPY --from=build /app/packages/backend/dist/bundle.tar.gz .
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

# Copy any other files that we need at runtime
COPY app-config.yaml ./

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Hi! Could you provide a bit more context to this change. Why is it needed?

**Review by iamEAP — COMMENTED** [review]
It's hard to say what unintended consequences this change could have.

Given this is seemingly not a problem with other base distros, I wonder if this is to do with how the alpine base image is set up (perhaps related to permissions tied to the user/group running the process or the initial permissions on the `/tmp` directory, or...?)

**Comment by dweber019** [comment]
Tested the same behavior with a Debian (https://hub.docker.com/layers/node/library/node/16-buster/images/sha256-9627b22e9e2e13ee0dbe692d85f3350c082c2b085e4e53114a016143dbc472f2?context=explore).
If I have a look at https://backstage.io/docs/deployment/docker#multi-stage-build the same distros are used.

If I switch the generator to run in docker everything works, hat least locally on my Windows&Mac.
Should I base my deployment image on https://hub.docker.com/r/spotify/techdocs instead of the one above?

Is there a test which validated that techdocs works set to local?

**Comment by benjdlambert** [comment]
@dweber019 is this something to do with the `uid` or the user being wrong in the container? Is it possible to switch the user to something that we don't need to do this? It seems weird that `alpine` and `debian` require different `chmod` permissions.

**Comment by camilaibs** [comment]
> @dweber019 is this something to do with the `uid` or the user being wrong in the container? Is it possible to switch the user to something that we don't need to do this? It seems weird that `alpine` and `debian` require different `chmod` permissions.

Hi @dweber 👋🏻 , did you have time to look into this?

**Comment by dweber019** [comment]
> @dweber019 is this something to do with the `uid` or the user being wrong in the container? Is it possible to switch the user to something that we don't need to do this? It seems weird that `alpine` and `debian` require different `chmod` permissions.

Actually used the same docker instructions in both images but only in Debian it worked. In the end I ended up using Debian for now. Yes IMHO it should make no difference but as I proceeded and tries my final step, by deploying on OpenShift, I had anyway to change the user to e.g. `node:node` (no root user on OpenShift possible in our setup) and `chmod` all files.

**Comment by freben** [comment]
@dweber019 Hey, I just wanted to check, are you unblocked at this point? If you're good for now, we may consider closing this if that's OK with you. We aren't sure that the proposed widening of perms is the right way to go from a security standpoint, and would need to give it a deeper consideration if so

**Comment by dweber019** [comment]
Yes you can close. I'm unblocked.

**Comment by cinlysobin** [comment]
Hi @dweber019,
I am also facing the issue with techdocs and I am deploying the docker in openshift. Can you please specify which base image u used to unblocked the issue?

**Comment by dweber019** [comment]
Hi @cinlysobin 
I ended up using the following image build. Only buster worked for me.
Also be aware that `RUN chmod -R 777 /app` isn't the best option.

```
FROM docker.io/node:16-buster

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y python3-pip \
 && apt-get install -y gcc musl-dev openjdk-11-jdk curl graphviz fonts-dejavu fontconfig \
 && rm -rf /var/lib/apt/lists/*

# Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.12.jar/download && echo "a3d10c17ab1158843a7a7120dd064ba2eda4363f  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar

RUN pip3 install --upgrade pip && pip install mkdocs-techdocs-core==1.0.2

# Create script to call plantuml.jar from a location in path
#   When adding TechDocs to the Backstage Backend container, avoid this
#   error (OSError: [Errno 8] Exec format error: 'plantuml') by using the
#   following RUN command instead:
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
# RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml
```
for the base image named `node:16-buster-mkdocs` form now on.

```
# Stage 1 - Create yarn install skeleton layer
FROM <our-registry>/node:16-buster-mkdocs AS packages

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages
# Comment this out if you don't have any internal plugins
# COPY plugins plugins

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM <our-registry>/node:16-buster-mkdocs AS build

WORKDIR /app
COPY --from=packages /app .

# install sqlite3 dependencies
# RUN apt-get update && apt-get install -y libsqlite3-dev python3 cmake g++ && \
#     yarn config set python /usr/bin/python3

RUN yarn install --frozen-lockfile --network-timeout 600000 && rm -rf "$(yarn cache dir)"

COPY . .

RUN yarn tsc
RUN yarn --cwd packages/backend build
# If you have not yet migrated to package roles, use the following command instead:
# RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies

# Stage 3 - Build the actual backend image and install production dependencies
FROM <our-registry>/node:16-buster-mkdocs

WORKDIR /app
RUN chown node:node /app
RUN chown -R node:node /app
USER node

# Copy the install dependencies from the build stage and context
COPY --chown=node:node --from=build /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

# install sqlite3 dependencies
# RUN apt-get update && \
#     apt-get install -y libsqlite3-dev python3 cmake g++ && \
#     rm -rf /var/lib/apt/lists/* && \
#     yarn config set python /usr/bin/python3

RUN yarn install --frozen-lockfile --production --network-timeout 600000 && rm -rf "$(yarn cache dir)"

# Copy the built packages from the build stage
COPY --chown=node:node --from=build /app/packages/backend/dist/bundle.tar.gz .
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

# Copy any other files that we need at runtime
COPY --chown=node:node app-config.yaml ./

# Use none root
RUN chown -R node:node /app
RUN chmod -R 777 /app

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

**Pull request closed without merging**
