### PR TITLE
fix(msgraph): add missing docs for config options

### PR DESCRIPTION
**Pull request by pjungermann**
Adds documentation for the recently introduced
config options

- userGroupMemberSearch
- groupSearch

Closes: #9819

Signed-off-by: Patrick Jungermann <Patrick.Jungermann@gmail.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by pjungermann** [comment]
> No Changeset found
I believe no release/version bump needed for the README change. But let me know if I'm wrong about that.

**Comment by pjungermann** [comment]
just realized that `userExpand` introduced recently was never read from the config and passed to the `MicrosoftGraphProviderConfig`.

I will fix this as part of the work for issue #9795.

**Comment by pjungermann** [comment]
I've removed `userExpand` as it is not functioning anyways. So it would more confusing to expose it at the docs now.

**Comment by freben** [comment]
Readme actually needs a changeset! It gets shipped with the package to npm

**Comment by pjungermann** [comment]
@freben alright! Let me fix this quickly

**Comment by pjungermann** [comment]
@freben maybe you can give it another look. Thanks!

**Review by Rugvip — APPROVED** [review]
Great, thank you! 👍

**Pull request merged**
