### PR TITLE
Increase content pane techdocs

### PR DESCRIPTION
**Pull request by Irma12**
## Hey, I just made a Pull Request!

MkDocs in Tech Docs are rendered with right sidebar which contains ToC. However, in cases when there is no ToC, it seems natural to use full width to show documents, and currently that is not the case. This has been reported as a bug by some users so we thought we might suggest a small change :) 

I have also added background color in footer in order to avoid text overlapping.

Here is the current state:
Screenshot 2022-02-15 at 22 46 38

My suggestion is to have full width in this case
Screenshot 2022-02-15 at 22 47 16

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
🟢 to unblock the changeset, but PTAL @backstage/techdocs-core

**Review by iamEAP — COMMENTED** [review]
Thanks for the contrib @Irma12!  We have received the exact same feedback internally; happy to get this in.

Couple of thoughts:
- The search bar feels kind of strange in this scenario, floating in the middle .  How difficult would it be to stretch it too, in this case?
- I have a feeling this could collide slightly with #9493 -- mostly just a heads up.

**Comment by iamEAP** [comment]
Heeey again @Irma12 -- we had a little bit deeper of a discussion about this today internally, and a few folks on the team brought up concerns that might warrant second thought: although we have received feedback from our internal customers about the oddity of the content not flowing to the right when there's no TOC, we've _also_ received conflicting feedback that the width of TechDocs content is unreadably wide on sufficiently large displays, which could be exacerbated by this change.

We're wondering if this _kind_ of customization is better left to adopters vs. baking it in to the core.

With _that_ in mind!  We're wondering if this, or perhaps a related augmentation of the TechDocs experience, could better be achieved with the proposed Addon framework.  We'd love for you to take a look and provide any thoughts/feedback here: #9636

**Comment by Irma12** [comment]
> Heeey again @Irma12 -- we had a little bit deeper of a discussion about this today internally, and a few folks on the team brought up concerns that might warrant second thought: although we have received feedback from our internal customers about the oddity of the content not flowing to the right when there's no TOC, we've _also_ received conflicting feedback that the width of TechDocs content is unreadably wide on sufficiently large displays, which could be exacerbated by this change.
> 
> We're wondering if this _kind_ of customization is better left to adopters vs. baking it in to the core.
> 
> With _that_ in mind! We're wondering if this, or perhaps a related augmentation of the TechDocs experience, could better be achieved with the proposed Addon framework. We'd love for you to take a look and provide any thoughts/feedback here: #9636

Hey @iamEAP thanks for looking into this. Addon framework would definitely make this 'cleaner' and more customizable, but  we don't know how long could it take until it is implemented. I feel, what I raised here, could be quick solution (at least until we get to the point of having Addon implemented). Some styling concerns could probably be also tackled quite fast

**Comment by Irma12** [comment]
Hey @iamEAP do you have any thoughts on this? I am eager to use Addon, but as I mentioned there is no strong timeline about when could we see it in action and I am thinking if we could tackle upon these issues make them work for now.

**Comment by dtuite** [comment]
@iamEAP Regarding this concern....

> we've also received conflicting feedback that the width of TechDocs content is unreadably wide on sufficiently large displays

I agree this is legitimate. Perhaps the right sidebar should be hidden, as per this PR, but there should also be a max width on the column of text so it doesn't become unreadably wide. We do something like this on the [roadie docs](https://roadie.io/docs/getting-started/getting-started-for-admins/) already. If you make the page super wide, the text stays narrow.

Would that be enough to get this merged before the Addons framework. "No" is a perfectly reasonable answer by the way! We'd love to either work it through or close it one way or another.

**Comment by iamEAP** [comment]
Hey David & Irma!  Sorry for letting this drop--as you may be aware, many folks here are taking part in hack week.

Love the max width on the content pane in the Roadie docs!  We've had something similar in the past on TechDocs internally (where, if a user chose, we'd still allow the content to grow in width, but we'd try and scale the font size so that it maintained approximately 80ch).

But that's also maybe good illustration of our hesitation: it's a small UX deficiency with a wide variety of possible improvements that may or may not be appropriate based on the context or the user.  I think the spirit of the transformers in TechDocs is "fix all of the basic mkdocs-material functionality we broke in order to render it within the chrome of a different web app," but this change is more of a deviation (compare with [this page on the mkdocs-material site](https://squidfunk.github.io/mkdocs-material/license/)).

Totally understand the desire to fix, though.  I can think of some...  Maybe ill-advisable hacks to get the fix in place for y'all without the addon framework in place (e.g. by auto-injecting some extra_css in your sites' mkdocs.yml configs -- or even more questionably, by writing an express middleware in the TechDocs backend that intercepts HTML files being delivered to clients and injects extra CSS inline in the response)

But for what it's worth!  The addon framework is a big priority for us, and our aim is to ship at least the frontend portion of it this month.

**Comment by dtuite** [comment]
@iamEAP Apologies! I forgot about hack week.

Sounds like the correct course of action is to close this and wait for add-ons.

**Comment by iamEAP** [comment]
Yes. But stay tuned for addon-related PRs soon!

Thanks for the understanding.

**Pull request closed without merging**
