### PR TITLE
Adds complete package metadata

### PR DESCRIPTION
**Pull request by vergilfromadyen**
## Hey, I just made a Pull Request!

This adds a repository reference to all Backstage packages. This makes it easier to trace their origin when browsing through the NPM registry or using the `npm docs` command.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — CHANGES_REQUESTED** [review]
Thanks for the contribution @vergilfromadyen! 🚀 

This looks good to me but you will need to add a changeset for this, without it the release process won't create a packages which means NPM won't get updated thus we won't get the benefits of your work here. There are some docs on changesets here: https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets

Also, I think it's important to note that this won't fix the problem - the templates that are used to create plugins need to be updated somehow - but I'm not sure what the right solution is. Would you be willing to log an issue for this?

**Comment by vergilfromadyen** [comment]
> Thanks for the contribution @vergilfromadyen! 🚀

Sure thing, thanks for the quick response!

> without it the release process won't create a packages which means NPM won't get updated thus we won't get the benefits of your work here

Seems in line with the intentions actually, this PR is updating meta data and not introducing any functional changes. I'm not fixing bugs or adding new features, let alone introduce breaking API changes. It would make sense to me if this is shipped with any other change that justifies a version bump. Or do you see this as a functional change?

> the templates that are used to create plugins need to be updated somehow

I see some Yeoman generators in this repo, are those responsible for the templates (and if so, could you point me to where I can find the templates)? If so, I could update the templates as well and then it's starting to look like a patch version bump.

**Comment by benjdlambert** [comment]
> Seems in line with the intentions actually, this PR is updating meta data and not introducing any functional changes. 

Whilst they're not introducing functional changes, in order to get this metadata published to sources like NPM each package will need a patch changeset.

> I see some Yeoman generators in this repo, are those responsible for the templates

So yes, basically, you can run `yarn backstage-cli new` in any backstage installation and it will create a new package for you. I think that we've probably got some other things to think about here like how do we make the scm URL etc as for end users it's not going to always be `github.com/backstage/backsage`, thinking that we can probably read the `{root}/package.json` and copy that one and assume that it's set or if not maybe we just don't add that metadata if we can't.

You can see the templates here: https://github.com/backstage/backstage/blob/b5344d21db5ec259a1a13982afeca69e767cb0f5/packages/cli/templates

And the templating is done in this `new` command here: 
https://github.com/backstage/backstage/blob/73537f9cff8bb6fcdbbea3950b231a1a9e1e1d04/packages/cli/src/commands/new/new.ts#L75-L85

**Comment by vergilfromadyen** [comment]
Unfortunately I cannot run `npm install` or `yarn install` so I cannot generate a changeset or test any changes. Attached a screenshot from a Docker container.  
This blocks me from completing the changes you've suggested. I'll give it another go in a few days but for now I've opened #18639 instead.

Screenshot 2023-07-11 at 13 19 45

**Comment by benjdlambert** [comment]
@vergilfromadyen sorry for the delay here, it looks like you're using npm to install here. Try using `yarn` instead.

**Comment by benjdlambert** [comment]
That should fix the `workspaces:^` error at least - not sure what the problem was when you tried to use `yarn`

**Review by freben — APPROVED** [review]
Alright I rebased and added a changeset.

**Comment by freben** [comment]
@awanlin feel free to give it a look again!

**Review by awanlin — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
