### PR TITLE
fix: authorized search engine to return approximate amount of results

### LINKED ISSUE #23086: 🐛 Bug Report: Search does not return totalNumberOfItems with permissions
### 📜 Description

If permissions are enabled, the search does not return totalNumberOfItems for the frontend. The proposal is to change the documentation so that the `numberOfItems` is approximate of the total found items.

### 👍 Expected behavior

It should return at least an educated guess of how many items are found

### 👎 Actual Behavior with Screenshots

It returns undefined

### 👟 Reproduction steps

1. Enable permissions
2. Search for catalog items

### 📃 Provide the context for the Bug.

https://github.com/backstage/backstage/blob/b018060fe133cc1916786b71564a458f99ea5d73/plugins/search-backend/src/service/AuthorizedSearchEngine.ts#L208

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

This does not guarantee that user can see all results, thus using cursors is still required

Closes #23086

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by emmaindal** [comment]
Hi @drodil, thanks, I'll discuss this with the team. Would you be able to add screenshots of before / after this change so that I can get better input from design/product - I believe the UI will change now that total number of results (the approximate number) is available. I feel like we might need to in some way inform the user that it is an approximate number if we want to get this in - but need input here before I can give any recommendations there!

**Comment by drodil** [comment]
Hi, thanks for the comment @emmaindal ! I checked the default `SearchPage` and all components and none of them show the number of results by default. So if this affects UI, it's then the user app with a customized search page that changes.

**Comment by emmaindal** [comment]
> Hi, thanks for the comment @emmaindal ! I checked the default `SearchPage` and all components and none of them show the number of results by default. So if this affects UI, it's then the user app with a customized search page that changes.

@drodil got it ok, so in that case, just to make sure I understand the need here, the current state is:

1. if you don't have the permission framework enabled - you will see total number of results if you have a custom search page enabling it. 
2. if you have the permission framework enabled - you won't see any total number of results, even if you use a custom search page enabling that

with these changes - it will keep an total number of results for #1 above, but show an approximate number of results for #2 above, however show up with the same design to the user. In that case we will end up with a UX where total number of results is actually not the total and in that case I'm not sure how much it will help the user in their search experience but rather hurt if the data thats displayed is false. 

Edit:
I've been running this with product and design on our side and we lean towards keeping it as it is with not displaying number of results when the permission framework is enabled as we believe its better to not display the number of results if its not accurate. 

We really appreciate that you lifted this up and let us know if you disagree!

**Comment by drodil** [comment]
Thanks for the comment @emmaindal ! Just wondering if it would make sense to introduce a new variable to the response `approximateNumberOfItems` besides the `numberOfItems`? Eeven Google just gives an approximate amount of results instead exact number. Also, ElasticSearch can return the approximate or exact amount in the response as shown in the screenshots:

image
image

Would this kind of change make more sense? I think the `approximateNumberOfItems` could be also used for Elastic responses where the `relation` field does not equal to `eq`.

**Comment by emmaindal** [comment]
@drodil thank you for presenting the alternative of approx total issues, and yes that makes more sense to me. Would you be able to present that alternative as part of the original issue and we can discuss it more there? And I’ll bring it back to our teams for input too?

**Comment by vinzscam** [comment]
mmm I'm not sure about this feature as the `approximateNumberOfResults` might not be approximate at all in certain conditions. In your example above, the search engine is telling you that the number of results is going to be greater than a certain value, which makes the number approximate.
Here we have no way to give such information.

**Comment by drodil** [comment]
Not stale, waiting for input

**Pull request closed without merging**
