### PR TITLE
Added rootRouteRef to fix link

### PR DESCRIPTION
**Pull request by aakankshabhende**
## Hey, I just made a Pull Request!

Fixed the delete entity button link

Fixes https://github.com/backstage/backstage/issues/18436

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by aakankshabhende** [comment]
@freben I checked [this](https://github.com/backstage/backstage/issues/10321).
But I'm unsure why my test cases are failing. Could you please guide me?

**Review by Rugvip — APPROVED** [review]
Thank you, looks good! 👍 

You'll need to update the test to mount the `rootRouteRef` on a mock route, you can see some existing usage of that with the `mountedRoutes` in the tests.

**Comment by aakankshabhende** [comment]
Yes I'll fix the test

**Comment by aakankshabhende** [comment]
@Rugvip I see this file is already using mountedRoutes. Could you please guide me?

https://github.com/backstage/backstage/blob/0870577bd4ac6922ff999a0207c2aed71512d499/plugins/catalog/src/components/EntityLayout/EntityLayout.test.tsx

**Comment by Rugvip** [comment]
@aakankshabhende, right it has a mocked route for the `entityRouteRef`, but not the `rootRouteRef` which is the one you're adding usage of there. That one will need to be added as well

**Comment by benjdlambert** [comment]
Hey :wave: I wonder if it's possible that we could configure this to be an `externalRouteRef` and default to the `catalogRouteRef` is one is not provided? Just thinking for the use case that not all end users use the `/catalog` page at all, so this would be an unexpected change if it was to link back there?

**Comment by aakankshabhende** [comment]
Yes I'll look into it

**Comment by benjdlambert** [comment]
Hey @aakankshabhende, is there anything we can help with here?

**Pull request closed without merging**
