### PR TITLE
email field and external uid annotation for GitlabOrgDiscoveryEntityProvider Enterprise users

### PR DESCRIPTION
**Pull request by matteosilv**
client was using commitEmail that is visible only for self-managed GitLab admins. publicEmail is visible, but only if the user explicitly enable the corresponding setting on GitLab.

### CODE REVIEW

**Comment by freben** [comment]
Note that this was fixed the other way around in https://github.com/backstage/backstage/pull/18889 just a few weeks ago.

Might it be worth supporting BOTH and picking whichever one of them was set?

**Comment by matteosilv** [comment]
Yeah I know but I checked as much as possible and commit email is never gonna be readable for SaaS. It's only available for self hosted admins @sbarrypoppulo

**Comment by sbarrypoppulo** [comment]
> Yeah I know but I checked as much as possible and commit email is never gonna be readable for SaaS. It's only available for self hosted admins @sbarrypoppulo

The behaviour is summarised in this snippet from GitLab Support - https://github.com/backstage/backstage/pull/18889#discussion_r1313026717

I don't feel strongly either way on this, as in our Org we don't particularly care about the email being populated or not, as we're using the sign-in-resolver with username.

**Comment by matteosilv** [comment]
> @sbarrypoppulo how are you configuring the signin resolver with just the username?

nevermind I figured it out.

Anyway both commitEmail, and publicEmail will be empty if there is no user action

**Comment by freben** [comment]
You can put code identifiers such as commitEmail in ``` `backticks` ``` to get the spell checker to ignore them.

**Comment by sbarrypoppulo** [comment]
Perhaps the fetching of users should be switched from GraphQL to the `/users` REST endpoint [1], scoped at the configured root organization group [2]? If we feel like email population is a must-have.

I'm afraid it will be a least a couple of weeks before I could take a look at this personally, as about to head off on some extended leave.

[1] - https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-gitlab/src/lib/client.ts#L84
[2] - https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-gitlab/src/providers/GitlabOrgDiscoveryEntityProvider.ts#L197

**Comment by matteosilv** [comment]
No there is NO way of using `/api/v4/users` in SaaS for this purpose. 

We need to keep this behavior:

https://docs.gitlab.com/ee/user/enterprise_user/#get-users-email-addresses-through-the-api
https://docs.gitlab.com/ee/api/members.html#limitations

I will have an ultimate SaaS license in a few days and I will configure it with Saml and single sign-on, and I'll later update this MR.

But for this to work, as explained in the doc, it seems that you need to have SAML SSO (plus optional provisioning via SCIM) and it's only visible to a Group owner access token

**Comment by matteosilv** [comment]
So I tested it. It only works if the user is enterprise (fully managed by gitlab sso confiuration via SAML or SCIM and showing the enterprise badge) and only by using the REST group members API (GraphQL is not showing the same email field).

So we would need to switch to the REST API and use the email field

**Comment by matteosilv** [comment]
Another reason why we should switch to the REST API is that it can let you easily filter over bot users (created by group or project access tokens) if you are using an enterprise license:

```
https://gitlab.com/api/v4/groups/<your-group>/members?show_seat_info=true
```

```json
[
{
"access_level": 50,
"created_at": "2023-07-17T08:58:34.984Z",
"expires_at": null,
"id": ...,
"username": "john.doe,
"name": "John Doe",
"state": "active",
...
"is_using_seat": true,
"membership_state": "active"
},
]

```

bots will have is using seat to false. However in the free tier you will have always false

**Comment by matteosilv** [comment]
I pushed a commit that should work for everyone. I still need to fix some tests.

I am assuming that everybody using GitLab in this context is using a paid subscription. If you want me to change this behavior let me know. The only difference is that I am filtering out users with a `is_using_seat = false`. For free subscription with a max of 5 users for root group all users show the `false` value

**Comment by matteosilv** [comment]
I think I fixed and tested it all.
I kept using a mixture of Grapql and rest API. We can eventually switch back to graphql as soon as GitLab adds missing fields.

Could you please review guys?

**Review by freben — APPROVED** [review]
Alright thanks for your efforts - let's try it out in the `-next` release tomorrow.

**Comment by pushit-tech** [comment]
Hello team,

I've been reviewing the process of querying users from the GitLab catalog and have some observations and proposals:

1. **Issue with `<rootGroup>/members/all` Endpoint**: It appears that using the `/members/all` endpoint does not return all users from inherited groups in GitLab. This could lead to incomplete user data in our catalog.

2. **Mapping Users in `GitlabOrgDiscoveryEntityProvider.ts` `refresh` Function**: We're currently mapping users in a group from the GraphQL `client.getGroupMembers` and REST API `listSaaSUsers`. This approach has a couple of challenges:
   - Points to review
     - GraphQL: 
       - Returns all expected users but also retrieves bot users.
       - Provides the `publicEmail`, wich is usefull
     - REST API: 
       - With a single group, it does not return all the inherited members of the group but allows us to get the users without bots or invited members.
       - Only provides the email if the user is an enterprise member.
   - Facts: 
     - We are querying both GraphQL and REST API but are ignoring the information from the GraphQL response.
     - The `publicEmail` from `getGroupMembers` is not being utilized.
     - `<rootGroup>/members/all` does not fetch all users within each group, which leads to an incomplete user list.

**Short-Term Proposals**:
- **Nested Users List**: Fetch the users list by nesting users of each group matching the `groupPattern`. This would require making individual API calls to `members/all` for each group.
- **Data Merging**: Combine user data from the GraphQL query and the REST API to include public emails.

**Long-Term Proposal**:
- **Function Refactoring**: Consider refactoring the `refresh` function to better separate its responsibilities. This might involve rethinking how we handle data fetching and mapping, and finding a good approach for using GraphQL and/or REST API endpoints.

I'd like to hear your thoughts on these proposals and how I can contribute to implementing them.

Thank you.

**Pull request merged**
