### PR TITLE
backend: Gitlab URL Reader to throw error when apiBaseUrl is missing

### PR DESCRIPTION
**Pull request by OrkoHunter**
Lesson after spending quite some time on Hosted GitLab issue https://github.com/backstage/backstage/issues/4303

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4308-euy2ocvwmizloisivyoivcqefk6q9gjb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/601433ae14dc5817e3be8797

**Comment by benjdlambert** [comment]
I think we should have some form of documentation here for each provider to find out how to get the `apiBaseUrl` for each provider

**Comment by OrkoHunter** [comment]
> I think we should have some form of documentation here to follow to find out how to get the `apiBaseUrl` for each provider

Indeed. Shall we tackle this as part of https://github.com/backstage/backstage/issues/4310 ?

**Comment by benjdlambert** [comment]
I think if we're going to make this a breaking change that this is now required, we should document this sooner than that issue. Also wondering if we need to make `config.d.ts` reflect this required url now?

**Comment by OrkoHunter** [comment]
We are already throwing the error in other providers e.g. GitHub
https://github.com/backstage/backstage/blob/435972704c9acf85fda79e28c9556482780c801d/packages/backend-common/src/reading/GithubUrlReader.ts#L62-L66

This PR improves the error in GitLab and adds tests.

The config update and docs can be addressed separately, IMHO. 🙇

**Comment by benjdlambert** [comment]
aha - sorry, I thought I also so saw the throw code for bitbucket too but just realised it was tests too.

**Review by benjdlambert — APPROVED** [review]

**Comment by freben** [comment]
it can't be required in the config.d.ts as long as we have the feature to deduce it automatically for `github.com`

**Comment by freben** [comment]
i see there was a message `apiBaseUrl and rawBaseUrl` - that's not really true is it? at least in terms of url reader needs, it should be enough to configure ONE of them and it'll try to use either method

**Comment by OrkoHunter** [comment]
> it can't be required in the config.d.ts as long as we have the feature to deduce it automatically for `github.com`

Yes, good point!

> i see there was a message `apiBaseUrl and rawBaseUrl` - that's not really true is it? at least in terms of url reader needs, it should be enough to configure ONE of them and it'll try to use either method

I guess you are right. Looking at 
https://github.com/backstage/backstage/blob/fc3e09e1bba9221be2e843ea797c3671f11b0f4c/packages/integration/src/github/core.ts#L77-L82

If `apiBaseUrl` is present, the raw base URL should not be required.

**Comment by OrkoHunter** [comment]
Merging this but happy to continue our discussion on existing implementations.

**Comment by freben** [comment]
@OrkoHunter Yeah this is an improvement either way. But I'm thinking that when loading the config, there should be actual validation [here](https://github.com/backstage/backstage/blob/master/packages/integration/src/gitlab/config.ts#L83). Like actually checking that it us URL parseable.

**Comment by OrkoHunter** [comment]
Right, agreed. `apiBaseUrl` should not be `undefined` when being returned from `readGitLabIntegrationConfig`.

**Pull request merged**
