### PR TITLE
bump better-sqlite3 from  9.0.0 to  11.0.0

### PR DESCRIPTION
**Pull request by karlhaworth**
## Hey, I just made a Pull Request!

bump better-sqlite3 from  9.0.0 to  11.0.0

Based on [release notes](https://github.com/WiseLibs/better-sqlite3/releases) from v10.0.0 and v11.0.0 this is compatible with the stated Backstage node engines -> https://github.com/backstage/backstage/blob/master/package.json#L136.

This updates to the latest version of better-sqlite3 to keep things up to date.

Tested on our instance of backstage and no issues.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
@karlhaworth FYI we've been using v11 for the Demo site for 2 weeks now without any issues: https://github.com/backstage/demo/pull/447. I'm not sure why Renovate hasn't created a PR for this to be honest 🤔

**Comment by karlhaworth** [comment]
@awanlin must have clicked close on accident when I was working on updating the PR. Not sure why it didn't either but this should be good to go!

**Review by awanlin — APPROVED** [review]
Thanks for this contribution @karlhaworth 🚀

**Comment by awanlin** [comment]
It is on the [Renovate Dependency Dashboard](https://github.com/backstage/backstage/issues/22682#:~:text=chore(deps)%3A%20update%20dependency%20better%2Dsqlite3%20to%20v11) but there's a lot of items maybe it's really behind?

**Comment by benjdlambert** [comment]
@awanlin @karlhaworth it's under the rate limited section, which means that Renovate won't open those PR's as there's already too many open PR's with dependency bumps so that we don't get swarmed. I think it's a possibility that the ones that are open are either failing, or just not going to be merged and are waiting for code fixes, so maybe it makes sense to start cleaning up some of those old PR's either by merging, or closing and creating a followup ticket to work on the migration to later versions.

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
