### PR TITLE
Fix healthcheck for the example-backend

### PR DESCRIPTION
**Pull request by minkimcello**
## Hey, I just made a Pull Request!

I was adding a healthcheck to @thefrontside's instance of Backstage and noticed the example provided [here](https://github.com/backstage/backstage/blob/master/packages/backend/src/index.ts#L159) returns a false positive because of its 404 page:

Screen Shot 2022-05-09 at 11 16 48 AM

If you create a new backstage app, build the image without actually adding a health check, and deploy it to a local cluster with the startup probe configured:

```yaml
...
spec:
  containers:
    - name: backstage
      image: backstage:x
      imagePullPolicy: Never
      startupProbe:
        httpGet:
          path: /healthcheck
          port: http
```

You should be able to see that the probe succeeds despite there not being a `/healthcheck` route. Then if you update the deployment so that the probe's path is `/api/whatever`, the probe will then correctly fail.

### Approach

- I replaced the current healthcheck route to use the `apiRouter` instead
- Changed the default path of `createStatusCheckRouter()` from `/healthcheck` to `/` (otherwise the default path would end up being `/api/healthcheck/healthcheck`)
- Updated the documentation in `Deploying with Kubernetes` and `Observability`

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Hm wait, are you saying that DESPITE the health check plugin being in place, you can get a false positive? Or does this problem only happen if you explicitly do not have the health check plugin added in your backend at all?

**Comment by Rugvip** [comment]
Looking forward a bit I think we'll encourage some of these internal endpoints to be exposed through separate listeners, so I actually think it makes sense to keep it at the root for now tbh. Health checks doesn't quite feel like `/api` level functionality.

I'm struggling a bit to understand the actual issue here tbh, is the confusion arising from setting up health checks towards an instance that does not have health checks installed, or something else?

As a side note I'd always encourage health check clients to check more than just the status code, preferably even that it's hitting the expected service.

**Comment by Rugvip** [comment]
I'm feeling that the documentation is quite clear that you need to add the health check yourself. I guess something we could consider here is whether we should add the health check to the `@backstage/create-app` template?

Just to clarify as well, what you end up getting without a health check endpoint installed is `index.html`, due to the HTML5 mode routing.

I'm still not entirely clear on the issue here though tbh, because the default health check behaves pretty much exactly like `index.html` anyway? Was the issue that you configured a custom health check but you had forgot to register the health check router in the top-level router?

**Comment by minkimcello** [comment]
> I'm still not entirely clear on the issue here though tbh, because the default health check behaves pretty much exactly like index.html anyway? Was the issue that you configured a custom health check but you had forgot to register the health check router in the top-level router?

My concern is that the default behaviour of a probe automatically succeeds with or without a health check route. Whether or not someone implements their own health check logic, shouldn't a health probe fail unless the status is explicitly successful?

So instead of:

- Deploy Backstage and assume a "successful deployment" is fine unless **_if and when_** there's a health check that tells us otherwise

It should be:

- Deploy Backstage _only_ when a healthcheck is successful; otherwise assume something is wrong

That way if probes are configured on a deployment and someone _does_ forget to register their healthcheck plugin, they won't mistake the default success as their own health check working properly.

**Comment by minkimcello** [comment]
I made diagrams.

Currently:

Screen Shot 2022-05-12 at 11 08 06 AM

What I'm proposing:

Screen Shot 2022-05-12 at 11 06 24 AM

**Pull request closed without merging**
