### PR TITLE
Change hardcoded master to $defaultBranch

### PR DESCRIPTION
**Pull request by simonstamm**
Since we pass over the defaultBranch argument in our templates, this seems to break because of the hardcoded master values. Probably this affects other providers as well.

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @simonstamm this needs a changeset and a dco signoff. Check this for info https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md

**Review by Rugvip — APPROVED** [review]
Other than ^ it looks good tho! 👍

**Comment by simonstamm** [comment]
Makes sense, signed and added the changeset. :)

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
Seems you need to add the word `hardcoded` to `.github/styles/vocab.txt`, and to run prettier on your changeset.

**Pull request merged**
