### PR TITLE
ci: upgrade uffizzi workflow to use clusters

### PR DESCRIPTION
**Pull request by waveywaves**
### Description

This PR upgrades the existing preview environment solution for backstage to support creating virtual clusters for every pull request opened in this repo. After this PR is merged, all subsequent PRs created will each have a virtual cluster spun up and a backstage deployment done in the cluster. The backstage image running in the deployment would be built from the changes in the pull request. 

### The uffizzi cluster lifecycle and ingress creation

When the uffizzi cluster creation workflow succeeds in the PR, a comment, similar to the one below will be posted. The comment will also contains a link to to the ingress for the instance of backstage running in the cluster 

https://github.com/waveywaves/backstage/pull/20#issuecomment-1746528145

https://backstage-default-pr-20-c918.uclusters.app.uffizzi.com
The above is an example of what the url to the backstage instance will look like. Here, `backstage` is the ingress name, `default` is the namespace where backstage was deployed `pr-20` is the cluster name which can be accessed by the user. 

Once the PR is closed, the cluster and therefore the resources within will be purged. The ingress will also not work thereafter. 

Creation of Uffizzi Clusters is quick and easy. The clusters will be accessible to the developer opening the PR and the admins of the project. These will improve collaboration through a singular ephemeral environment which can be shared between developers and other stakeholders.

closes https://github.com/backstage/backstage/issues/19655

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

cc @Rugvip @benjdlambert

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Thank you, let's try it out! :tada: :+1: 

Sorry for the slow review, is this ready to be merged?

**Comment by waveywaves** [comment]
@rugvip I just updated the preview so you can see the PR got closed because it was open on my fork for too long. Anyways, this is the instance https://backstage-default-pr-20-c918.uclusters.app.uffizzi.com/ is there anything you wish to see that we aren't seeing. 

image


I am seeing the above error and am not sure how to resolve it, any insights would be helpful

**Comment by waveywaves** [comment]
@Rugvip I figured out the necessary solution for this issue, shall update it in a bit

**Comment by waveywaves** [comment]
@Rugvip I made the necessary changes and this is what the deployment looks like right now and not sure why the entities are still not being returned on the frontend. Does this deployment look right to you ?
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backstage","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"backstage"}},"template":{"metadata":{"labels":{"app":"backstage"}},"spec":{"containers":[{"args":["-c","APP_CONFIG_app_baseUrl=$$UFFIZZI_URL APP_CONFIG_backend_baseUrl=$$UFFIZZI_URL APP_CONFIG_auth_environment='production' node packages/backend --config app-config.yaml"],"command":["/bin/sh"],"env":[{"name":"POSTGRES_PORT","value":"5432"},{"name":"POSTGRES_HOST","value":"postgres.default.svc.cluster.local"},{"name":"NODE_ENV","value":"production"}],"envFrom":[{"secretRef":{"name":"postgres-secrets"}},{"secretRef":{"name":"backstage-secrets"}}],"image":"registry.uffizzi.com/d1572751-c440-45c1-896c-15997e0b5f09:60d","imagePullPolicy":"IfNotPresent","name":"backstage","ports":[{"containerPort":7007,"name":"http"}]}],"serviceAccountName":"backstage-service-account"}}}}
  creationTimestamp: "2023-10-04T09:52:33Z"
  generation: 4
  name: backstage
  namespace: default
  resourceVersion: "82507"
  uid: ad5c1042-2d9f-467b-b90d-7489c71d42c5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backstage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backstage
    spec:
      containers:
      - args:
        - -c
        - APP_CONFIG_app_baseUrl=https://backstage-default-pr-20-c918.uclusters.app.uffizzi.com
          APP_CONFIG_backend_baseUrl=https://backstage-default-pr-20-c918.uclusters.app.uffizzi.com
          APP_CONFIG_auth_environment='production' node packages/backend --config
          app-config.yaml
        command:
        - /bin/sh
        env:
        - name: UFFIZZI_URL
          value: https://backstage-default-pr-20-c918.uclusters.app.uffizzi.com
        - name: REF_NAME
          value: 100841d3ae46a92c3c71319f66c19c6193c73479
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_HOST
          value: postgres.default.svc.cluster.local
        - name: NODE_ENV
          value: production
        envFrom:
        - secretRef:
            name: postgres-secrets
        - secretRef:
            name: backstage-secrets
        image: registry.uffizzi.com/d1572751-c440-45c1-896c-15997e0b5f09:60d
        imagePullPolicy: IfNotPresent
        name: backstage
        ports:
        - containerPort: 7007
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: backstage-service-account
      serviceAccountName: backstage-service-account
      terminationGracePeriodSeconds: 30
```

**Comment by jpthurman** [comment]
Hi @Rugvip @benjdlambert can we get this prioritized?  cc @waveywaves

**Comment by Rugvip** [comment]
It's ready to go assuming it's working and the build is green. Don't have enough bandwidth to help out debugging this atm though, sorry. @waveywaves can't see anything obviously wrong with the config, do we actually expect playlists to work though? is the catalog index page working?

**Comment by waveywaves** [comment]
@Rugvip Everything works really well now https://backstage-default-pr-21-c1176.uclusters.app.uffizzi.com/ 
The PR is also ready to be merged

**Comment by Rugvip** [comment]
@waveywaves nice! :+1: just needs formatting of the new files to make the verify check pass

**Comment by waveywaves** [comment]
@Rugvip done ! ran a `yarn prettier:fix` the CI should pass now

**Comment by waveywaves** [comment]
@Rugvip the CI has passed successfully ! 🎈 :')

**Review by Rugvip — APPROVED** [review]
:tada: :shipit:

**Pull request merged**
