### PR TITLE
[repo-tools] moved to peerDeps to match version w/api-extractor

### PR DESCRIPTION
**Pull request by Sarabadu**
## Hey, I just made a Pull Request!
For this packages we need the same version used on api-extractor and api-documenter
when we update uno of those version as in https://github.com/backstage/backstage/pull/15346, bring errors because `api-exporter` use fixed version.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
👍 , only thing that could go wrong here I think is if the project already installs a different version of these dependencies. Let's leave it up to those projects to keep the versions in sync in that case, feeling that would be rare.

**Review by jhaals — CHANGES_REQUESTED** [review]
Also needs a patch changeset :)

**Comment by Sarabadu** [comment]
> Also needs a patch changeset :)

2023 year resolution list:
- config the auto signoff
- add a changeset to my PRs

**Comment by Sarabadu** [comment]
we can safely close [this PR ](https://github.com/backstage/backstage/pull/15346) after merge this

**Comment by jhaals** [comment]
All I want for christmas is changesets in the PRs 🎄

**Review by jhaals — APPROVED** [review]

**Pull request merged**
