### PR TITLE
Upgrade Backstage to React 18

### LINKED ISSUE #12252: Upgrade to React 18
There are a few places in code where React 17 is explicitly required, like this. 

```ts
  if (reactDomVersion.startsWith('16.')) {
      resolveAliases['react-dom'] = '@hot-loader/react-dom-v16';
    } else {
      resolveAliases['react-dom'] = '@hot-loader/react-dom-v17';
    }
```

## Feature Suggestion

Be able to upgrade to React 18.

## Possible Implementation

TBD, but we could start by capturing what is breaking in React 18. 

## Context

I don't actually have a reason to do this other than "being up-to-date for being up-to-date sake", but I couldn't find an issue that explains the current situation. I found a [PR that says there are breaking changes in React 18](https://github.com/backstage/backstage/pull/10711) but it doesn't reference what they are. Also #10711 and #11461 which close PRs that attempt to upgrade dependencies.

### LINKED ISSUE #18714: 🐛 Bug Report: Sidebar Items and React 18
### 📜 Description

When upgrading the `@backstage/core-components` package to React 18, there is a problem where the props for WorkaroundNavLink as well as the Sidebar items don't align with what is expected in React 18. 

Since React 18 updated its types, the `Link` component from `react-router-dom` expects `children` to be of type `ReactNode`. Whereas `NavLinkProps` specifies `children` as being:

```ts
export interface NavLinkProps extends Omit<LinkProps, "className" | "style" | "children"> {
    children?: React.ReactNode | ((props: {
        isActive: boolean;
        isPending: boolean;
    }) => React.ReactNode);
    caseSensitive?: boolean;
    className?: string | ((props: {
        isActive: boolean;
        isPending: boolean;
    }) => string | undefined);
    end?: boolean;
    style?: React.CSSProperties | ((props: {
        isActive: boolean;
        isPending: boolean;
    }) => React.CSSProperties | undefined);
}
```

To handle this condition, one can check to see whether or not `children` is of type function and then apply the appropriate logic. One unknown here though, is how do we handle the case when `children` is actually a function type? 
Should we invoke it and pass the `ReactNode` result into the link, or do we need to modify the code somehow so that any components consuming it can invoke it when needed? 

Another issue is that `SidebarItem` also gets this `children` prop as a type of either ReactNode or function. The definition is as follows:
```tsx
/**
 * Creates a `SidebarItem`
 *
 * @remarks
 * If children contain a `SidebarSubmenu` component the `SidebarItem` will have a expandable submenu
 */
export const SidebarItem = forwardRef<any, SidebarItemProps>((props, ref) => {
  // Filter children for SidebarSubmenu components
  const [submenu] = useElementFilter(props.children, elements =>
    // Directly comparing child.type with SidebarSubmenu will not work with in
    // combination with react-hot-loader
    //
    // https://github.com/gaearon/react-hot-loader/issues/304#issuecomment-456569720
    elements.getElements().filter(child => child.type === sidebarSubmenuType),
  );

  if (submenu) {
    return (
      <SidebarItemWithSubmenu {...props}>
        {submenu as React.ReactElement<SidebarSubmenuProps>}
      </SidebarItemWithSubmenu>
    );
  }

  return <SidebarItemBase {...props} ref={ref} />;
}) as (props: SidebarItemProps) => JSX.Element;
```

The `useElementFilter` hook only accepts types of ReactNode, and not the function that is being passed. 

### 👍 Expected behavior

n/a

### 👎 Actual Behavior with Screenshots

n/a

### 👟 Reproduction steps

n/a

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

n/a

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by RobotSail**
- update dependencies to react 18
- add PropsWithChildren to testutils
- update components to use PropsWithChildren
- update react hooks
- drop @testing-library/react-hooks
- fix updateImportState tests
- update dependencies

## Hey, I just made a Pull Request!

This pull-request updates the dependencies in Backstage from React `17` to `17 || 18`.

Fixes #18714
Fixes #12252 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by RobotSail** [comment]
This PR is a duplicate of #17414 since the previous PR was closed out of being stale.

**Comment by RobotSail** [comment]
So it looks like the best way forward for the React 18 upgrade in this repository will be to break the version window policy for React. I've written [an RFC](https://github.com/backstage/backstage/issues/18625) for the matter in #18625. 

The gist is that it will take an enormous effort to maintain compatibility (particularly in testing) of both React 17 and 18. Doing so would introduce a lot of complexity into the codebase, increasing the amount of work for both maintainers and contributors/developers.

**Comment by RobotSail** [comment]
#18714 Is another one that will need to get addressed before this can merge

**Comment by RobotSail** [comment]
not stale

**Comment by RobotSail** [comment]
not stale

**Comment by RobotSail** [comment]
not stale

**Comment by freben** [comment]
Replaced by https://github.com/backstage/backstage/pull/20598 and others leading up to it

**Pull request closed without merging**
