### PR TITLE
Scaffolder template. Added a missing validator check for items in an array

### PR DESCRIPTION
**Pull request by acierto**
Signed-off-by: bnechyporenko <bnechyporenko@bol.com>

## Hey, I just made a Pull Request!

Scaffolder template doesn't trigger the validator if custom extension is defined in an array. 

Test case

```
     tags:
          title: Tags
          description: '(Optional) Application keywords'
          type: array
          items:
            type: string
            ui:field: TagExtension
```

Where TagExtension checks that valid symbols are used for each tag. 

Example of it:
Screenshot 2023-02-06 at 13 44 41

 Right now the validation check is not performed.

How it looks with this change:

Screenshot 2023-02-06 at 13 50 46

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hmm - higher level comment here is would it be better to pass the entire array into the validator rather than the individual items. Thinking that it probably would be better to do it this way, especially for things like async validators so that you can do batch requests etc, and make sure that there's no duplicates in the array etc. Seems a little more powerful to me? What do you think?

**Comment by acierto** [comment]
> Hmm - higher level comment here is would it be better to pass the entire array into the validator rather than the individual items. Thinking that it probably would be better to do it this way, especially for things like async validators so that you can do batch requests etc, and make sure that there's no duplicates in the array etc. Seems a little more powerful to me? What do you think?

Make sense. I was thinking to preserve the same contract.
What about then to add an example somewhere here regarding the array validation? https://backstage.io/docs/features/software-templates/writing-custom-field-extensions#creating-a-field-extension

**Comment by benjdlambert** [comment]
Ah ok - so I think there's actually 2 use cases here. When the `ui:field` is on the `type: array` property, and when it's on the `items` part. I think that when it's on the `item` it would run validation for that single value, but if it's on the `type: array` it would call for all values. Sorry I misread your description.

Does that make sense?

**Comment by acierto** [comment]
> Ah ok - so I think there's actually 2 use cases here. When the `ui:field` is on the `type: array` property, and when it's on the `items` part. I think that when it's on the `item` it would run validation for that single value, but if it's on the `type: array` it would call for all values. Sorry I misread your description.
> 
> Does that make sense?

Yeah, here 2 cases. I'm not interested in cases where it `type:array`, as at this case I need to create my custom array of strings component. It way less invasive to add a validation on `items` part. I don't see a big deal if there a validator will get an array of values. 

My suggestion here is only to add an extra documentation for this scenario.

**Comment by benjdlambert** [comment]
I think this is also going to need to be ported over to the `scaffolder/next` work too. If you take a look at `src/next` and mainly `createAsyncValidators` i'd recommend writing a similar test there too to confirm that it works there?

**Comment by acierto** [comment]
@benjdlambert ported over to the `scaffolder/next`

**Review by benjdlambert — APPROVED** [review]
Thanks for this! :pray:

**Pull request merged**
