### PR TITLE
fix: field extensions with correct CSS and HTML

### LINKED ISSUE #15870: 🐛 Bug Report: HTML and CSS differences when using field extensions in scaffolder
### 📜 Description

I have noticed that the field extensions like `EntityPicker` causes the HTML and CSS of that field to be slightly different. I have been testing this on the example app that comes with backstage. I tried editing the spring boot template and there is a slight but sureshot difference between when we are using a custom field and a vanilla field. Hopefully I made my thoughts clear but here are some screenshots.

As you can see that the custom fields is taller and also has an additional class in an inner div (the one with `MuiFormControl-marginNormal-4513` class). It also has the helper text in a `<p>` tag whereas the vanilla ones helper text is inside a `<span>`.
image
image

I realise that this might be a bit nitpicky but I feel like things like these are a sign of something wrong happening.

### 👍 Expected behavior

I expect for the field extensions to have the same or almost the same CSS and HTML when compared to the inbuilt fields of rjsf.

### 👎 Actual Behavior with Screenshots

Hopefully I made my thoughts clear but here are some screenshots.

As you can see that the custom field is taller and also has an additional class in an inner div (the one with `MuiFormControl-marginNormal-4513` class). It also has the helper text in a `<p>` tag whereas the vanilla ones helper text is inside a `<span>`.
image
image

### 👟 Reproduction steps

1. Run the example app from the backstage repo
2. Go to the `Create` scaffolder section and choose an existing scaffolder, say spring boot.
3. Inspect the field of the first input and see the CSS and HTML
4. inspect the field of the second input and see the CSS a

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

This issue happens in the current master at 974e5f28645cda7943355936e2291e732ba3908f

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by SayakMukhopadhyay**
Signed-off-by: Sayak Mukhopadhyay <mukhopadhyaysayak@gmail.com>

## Hey, I just made a Pull Request!
Closes #15870 

This PR fixes the 2 issues in the linked issue:

1. an inner div is having an extra css class with additional margin. The reason for this is the presence of `margin="normal"`  prop on all the custom fields. For eg. https://github.com/backstage/backstage/blob/2694cbba0591416bb38c1132e259d3ba85de6b75/plugins/scaffolder/src/components/fields/EntityNamePicker/EntityNamePicker.tsx#L46
You can check other custom fields, and all of them have that line. It adds an additional css class with margins that is not present when using the vanilla fields as shown in above screenshots. Removing this prop, renders the component exactly the same as the vanilla fields.

2. The second one is trickier. The vanilla fields have the helper text rendered in a `<span>` whereas the custom fields are getting rendered in `<p>`. That is because, rjfs is not using the `<FormHelperText>` that comes with the `<TextField>` in material ui 4. Instead rjfs is using a `<Typography>` element that sits within a `<FormControl>` (not within `<TextField>`) to render the helper.  Most of the custom fields by backstage have a `<FormControl>` except `EntityNamePicker`. Wrapping it with a `<FormControl>` and `<Typography>` renders the helper text exactly how rjfs itself renders.

~~The PR doesnt include the repo related field extensions yet as they are a bit tricker. I will be adding them shortly.~~ In the meantime, I need some feedback on this.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by SayakMukhopadhyay** [comment]
Hmm...dunno why the E2Es are failing. Locally, I have 3 failed tests in my project but all of them are in other packages. Looking at the failed E2E tests, it seems like they are unrelated to scaffold.

**Comment by SayakMukhopadhyay** [comment]
Hmmm...I have found some design issues. I mean, things would _look_ fine but sine I am reworking this, I might as well do it in a way that makes sense. Right now, in `EntityNamePicker` for eg, I am using the `TextField` inside a `FormControl`, which is unnecessary as the `TextPicker` generates its own `FormControl`.

If I go full rjfs, I probably replace the `TextField` with `Input` and `InputLabel`s.

**Comment by benjdlambert** [comment]
So I wonder if it makes sense for us to abstract this part away https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx#L45-L67 into a component that we can re-use for simple input fields etc for the scaffolder to remove some of the complexity.

I think that we provide our own `ui:field` we basically replace the implementation of https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx entirely, so we need to reproduce its behaviour somehow and maybe creating our own component is easiest.

One other thing i've noticed is that I think we need to apply these too https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx#L36 to the wrapper so that we carry through some other styling that might be relevant.

Does this make sense or am I missing something else?

**Comment by SayakMukhopadhyay** [comment]
Implementing an accurate abstraction would certainly be the way forward. But its a bit challenging for me to figure out the point of abstraction.
Let me provide a screenshot of the component tree of 2 fields, the upper one is the `EntityNamePicker` and the lower one is a rjfs inbuilt.

image

Note, that both of them are using the `FieldTemplate` and the `WrapIfAdditional` components which are rjfs internal. So, when we are providing our component, we are probably not replacing the entire `FieldTemplate`. Also note that the `FieldTemplate` is a sub component of `SchemaField` which looks to me to be referrenced at https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/core/src/components/fields/SchemaField.js#L354-L403.

What do you think? I hope I am not missing something.

**Comment by SayakMukhopadhyay** [comment]
@benjdlambert Also note that since we are using the existing `SchemaField` some assumptions in it is affecting how the component tree is generated. For eg. in the component tree screenshot, the `Typography` label is a child of the `FormControl` in the inbuilt field but not so in the custom field. That is because, the `Typography` in https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx#L51 is getting hidden by the `displayLabel` being false in the previous line which is handled by https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/core/src/utils.js#L405.

This makes me think that your are probably correct in thinking that we should replace the `FieldTemplate` by using https://react-jsonschema-form.readthedocs.io/en/v4.2.2/advanced-customization/custom-templates/#fieldtemplate

**Comment by benjdlambert** [comment]
@SayakMukhopadhyay do you want to experiment providing a default `FieldTemplate` to see if it helps simplify the logic a little bit? From what I understand there's a few options to fix this, and I want to see what it would look like a few ways and we can pro/con them and see what the implications are.

**Comment by SayakMukhopadhyay** [comment]
> @SayakMukhopadhyay do you want to experiment providing a default `FieldTemplate` to see if it helps simplify the logic a little bit? From what I understand there's a few options to fix this, and I want to see what it would look like a few ways and we can pro/con them and see what the implications are.

Yeah, that's what I am thinking of doing. What I am planning on starting with is by making a full copy of https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx, the only change being making `displayLabel` set to true.

I want to apply the field template globally which will ensure that we have total control over the UX of the fields. That will ensure that whether we use field extensions or inbuilt fields, they all look the same.

**Comment by SayakMukhopadhyay** [comment]
I have pushed a commit which creates a custom field template which is mostly a duplicate of https://github.com/rjsf-team/react-jsonschema-form/blob/v3.2.1/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx along with a couple other components that it depends on. The only change made was that the description is no longer dependendant on the `displayLabel` boolean.

Also do note that the `CustomFieldTemplate` has been applied globally.

The other way to something similar would be to use the existing `FieldTemplate` more directly like making the `CustomFieldTemplate.tsx` like:

```tsx
import React from 'react';

import { FieldTemplateProps } from '@rjsf/core';
import { FieldTemplate } from '@rjsf/material-ui';

const CustomFieldTemplate = (props: FieldTemplateProps) => {
  return <FieldTemplate {...props} displayLabel />;
};

export default CustomFieldTemplate;
```

The above code is enough to ensure that the labels have the same styles. Note that the PR as it is right will show 2 labels for `EntityNamePicker` custom field as that field definition also defines its label.

**Comment by SayakMukhopadhyay** [comment]
not stale

**Comment by benjdlambert** [comment]
Sorry it's taken so long to get round to this, I've been focused on the release this week and getting the alpha stuff for the scaffolder ready to ship for testing. Hopefully will get chance to get round to have a deeper dive into this later on this week. :pray:

**Comment by benjdlambert** [comment]
Going to close this as we think we've worked out how to do it in the linked PR! :tada:

**Pull request closed without merging**
