### PR TITLE
docs: fix a link to the frontend Backstage plugin

### PR DESCRIPTION
**Pull request by fevrin**
This just fixes a link to the frontend Backstage plugin.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by awanlin — CHANGES_REQUESTED** [review]
Thanks for the contribution @fevrin, in this case we will need a changeset as that will trigger a release to NPM so that the docs get updated there as well 👍

**Comment by adamdmharvey** [comment]
@fevrin if it helps, there are some instructions here:
https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets

It's pretty straightforward, just `yarn changeset` from your branch, and follow the instructions to generate a patch!

**Comment by fevrin** [comment]
Done!

By the way, should I open a separate PR for another minor change or add it to this one with its own changeset file?

**Comment by freben** [comment]
I don't mind either way! Feel free to make a single "fixed some docs"-type of PR or several, whichever is more convenient to you.

You've hit one more technicality as you may see above: all individual commits to the project need to be DCO signed. The build details at the bottom, or the DCO bot comment above, have some more details.

**Review by awanlin — APPROVED** [review]
Looks good, thanks again @fevrin 🚀

**Comment by fevrin** [comment]
No problem, and thank you!

Would you be able to confirm if this needs another approving review?

I see these messages:
> Code owner review required
> Waiting on code owner review from backstage/catalog-maintainers and/or backstage/maintainers.

> Merging is blocked
> Merging can be performed automatically with 1 approving review.

**Review by freben — APPROVED** [review]
Reviews happen on-demand but can sometimes take a bit of time depending on our workload. Either way, no action needed on the submitter's part, and the maintainers are the only ones who can press merge afterwards either way. Thanks!

**Pull request merged**
