### PR TITLE
Disable zooming for the CatalogGraphCard

### PR DESCRIPTION
**Pull request by Fox32**
@freben suggested to disable it for the graph card as it interacts with the zooming on the entity page.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Fox32** [comment]
I'm a bit confused that the `core-components` API report isn't updated.

**Review by freben — APPROVED** [review]
Looks great! Yeah but hmmmm what's up with the apis...

**Comment by freben** [comment]
@Fox32 Oh I see what's up - the `DependencyGraphProps` type isn't exported, you can see a warning about that in the api report actually. You might want to add that to the public API while you are at it

**Comment by Fox32** [comment]
> @Fox32 Oh I see what's up - the `DependencyGraphProps` type isn't exported, you can see a warning about that in the api report actually. You might want to add that to the public API while you are at it

Oh yeah, thanks!

**Pull request merged**
