### PR TITLE
Define FOSSA config statically in repo

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

The current FOSSA workflow dynamically generates a config file (`init`) for what packages to search file by inspecting the repo.  This causes a few challenges with the Backstage repo it seems, and results in intermittent 502 Bad Gateway errors (#4240) when doing the analyze. This is an attempt at moving this forward, reducing some noise of PR and master merge failures, and still gaining from the FOSSA value (and aligning to CNCF).

This PR avoids the regeneration each time and stores the FOSSA config statically in the repo via `.fossa.yml`.  This is a common pattern according to https://github.com/fossas/fossa-cli and other sources. It also includes some hardcoded definitions made.

**Pros**

* Avoids error from the generated init where fake "cookiecutter" repos are included in the output
* Avoids a few packages which lack dependencies (e.g., asset-types and cli-common)
* Avoids duplicates (microsite and the monorepo of `.` get picked up twice, though I'm not sure why)
* Allows to define a name which may make more sense to the project; e.g., in this case rather than a package being called "kubernetes" it can be defined it as "plugin-kubernetes" which better aligns to it's resulting published npm name
* Allows continual tweaks. For e.g., right now fossa is still warning on the monorepo root and microsite, so we might be able to manually tweak the options, strategy, etc, to get those to pull out better. (since microsite for example has no deps, but it uses devDeps, etc.)

**Cons**

* Requires manual changes each time a new package, like a new plugin, is contributed.

The original workflow did some `yq` commands to try to clean it up, and we could go back to that so long as some of the warnings/nuances we may want to tweak are dynamically updated.

Since we're not sure what's causing the gateway errors, if a hypothesis is there are too many, this may NOT fix it and we may instead need to do something like run it twice (once for all packages, and a second time for all plugins). But since it removes some oddly formatted packages, it may help.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by adamdmharvey** [comment]
It ran cleanly in about 1/3 the time, but I don't have access to see the results:

https://app.fossa.com/projects/custom+162%2Fgit@github.com:backstage%2Fbackstage/refs/branch/refs%2Fpull%2F4253%2Fmerge/a876e40828b7c1075d3f0c196083e5dc73dd7e5e

I was able to see results for another public project, so not sure if there's a flag in the FOSSA config somewhere to allow the data to be public? Unless the goal is NOT to in case it exposes some security or legal issue, I'm not sure?  Anyway, just noting I can't see it. :grin:

**Comment by Fox32** [comment]
I would vote against a static file, if fossa init isn't sufficient enough we could still generate the file ourself in the pipeline?

**Comment by adamdmharvey** [comment]
@Fox32 indeed!  Could dynamically generate it, just would be a wee bit more complex.  Some notes I had written re that:

* after fossa init
* remove two different cookiecutters which represent fake packages which don't exist
* remove duplicate microsite
* remove duplicate "." with same name target and path just a period
* tweak the names of the packages to potentially more friendly names (e.g., rename "jenkins" to "plugin-jenkins" or whatever might look good and be understandable to the Backstage community in the FOSSA GUI)
* cli-common has no dependencies; only devDeps, so fossa warns on it, maybe convert devDeps to deps since the package is only USED for dev? (the main purpose of the package, versus only being used to BUILD the package?)
* microsite has no deps, only devDeps, so fossa warns on it; maybe remove or convert devDeps to deps?
* asset-types isn't a real repo, it's a subdirectory of cli, and has no deps, so FOSSA warns on it; maybe remove

e.g.,
```shell
WARNINGS
⣷ Analyzing module (1/62): microsite WARNING Could not determine deps from npm ls
⣽ Analyzing module (2/62): . WARNING Could not determine deps from npm ls
⣾ Analyzing module (8/62): asset-types WARNING Could not determine deps from npm ls
⣷ Analyzing module (10/62): cli-common WARNING Could not determine deps from npm ls
```

And the raw run:

```
$ ./fossa/fossa init
⢿ Initializing... WARNING Filtering out suspicious module: zenorocha/clipboardjs (microsite/node_modules/clipboard/composer.json)
WARNING Filtering out suspicious module: zenorocha/clipboardjs (node_modules/@storybook/react/node_modules/clipboard/composer.json)
WARNING Filtering out suspicious module: zenorocha/clipboardjs (node_modules/clipboard/composer.json)
WARNING Filtering out suspicious module: android (:)
WARNING Filtering out suspicious module: e2e-test (packages/e2e-test)
WARNING Filtering out suspicious module: test-utils (packages/test-utils)
WARNING Filtering out suspicious module: test-utils-core (packages/test-utils-core)
WARNING Filtering out suspicious module: gyp (node_modules/node-gyp/gyp)
WARNING Filtering out suspicious module: gyp (node_modules/npm-lifecycle/node_modules/node-gyp/gyp)
```

And some output examples:

`.fossa.yml`:

```yaml
- name: '{{cookiecutter.artifact_id}}'
    type: mvn
    target: pom.xml
    path: plugins/scaffolder-backend/sample-templates/springboot-grpc-template/{{cookiecutter.component_id}}
  - name: microsite
    type: npm
    target: microsite
    path: microsite
  - name: microsite
    type: npm
    target: microsite
    path: microsite
  - name: .
    type: npm
    target: .
    path: .
  - name: '{{cookiecutter.component_id}}'
    type: npm
    target: plugins/scaffolder-backend/sample-templates/react-ssr-template/{{cookiecutter.component_id}}
    path: plugins/scaffolder-backend/sample-templates/react-ssr-template/{{cookiecutter.component_id}}
```
```

**Comment by freben** [comment]
Hey! Thanks for looking at this annoying issue. We talked a bit about this and feel that static config may not be what we'd want to do after all. And is it really the cause of the 502s? We'll experiment with maybe making the dynamic part more robust.

**Comment by freben** [comment]
(or of course - if you find a way it'd be more than welcome too!)

**Comment by adamdmharvey** [comment]
Sounds good.

Btw, I did some testing on my own, and I would agree with the feedback the gentleman from CNCF had.  When running yq del transforms locally, what I thought should have been deleted, wasn't, and I had to run a few multiple times.  Interestingly, there are numerous similarly named `yq` libraries out there, so maybe others would be better. Or maybe even doing it wrapped in Node code or some such, rather than just command line.

So yeah the config CAN be built dynamically, but would need a bit otweaking for sure.

Will close this experiment out - onward and upward! :arrow_upper_right:

**Pull request closed without merging**
