### PR TITLE
chore(catalog): remove the now redundant Entity type copy

### PR DESCRIPTION
**Pull request by freben**

### CODE REVIEW

**Review by nikek — APPROVED** [review]

**Review by Nek — APPROVED** [review]
🔥

**Comment by freben** [comment]
@stefanalund Again, this was not with master as a base, so when you merge these you make them pollute another pull request, making it bigger and harder to review :) When moving fast and wanting to break things up into smaller pieces to make them easier to review, we do this pretty often.

**Comment by freben** [comment]
We usually want to merge things in a certain order. The parent PR to this is not approved yet.

**Comment by stefanalund** [comment]
@freben sorry about that 😔  I will hold my trigger finger in the future.

**Pull request merged**
