### PR TITLE
Add Microsoft Azure AD Auth Provider + Add to Example App

### LINKED ISSUE #348: Add Azure (AAD) auth

### PR DESCRIPTION
**Pull request by ekkohnet**
## Hey, I just made a Pull Request!

Closes #348.
This replaces #1990.

This adds an auth provider for logging in with Azure AD identities and getting tokens from the Microsoft Graph API, using `passport-microsoft`. It retrieves the user's profile photo if it exists, and supports refresh tokens.

Takes `AUTH_MICROSOFT_CLIENT_ID`, `AUTH_MICROSOFT_CLIENT_SECRET` and `AUTH_MICROSOFT_TENANT_ID` as environment variables.

The README for `plugins/auth-backend` has been updated with steps on how to register the required Azure AD App Registration.

Sign In Page...

sign-in-page

If the user only has a single active session for the tenant they will be signed in without prompt.
If the user has multiple or no active sessions, they'll be prompted...

account-select

The user will be prompted for consent on first sign in, or with additional scopes...

consent-prompt

Backstage user ID is using local part of email for now, like the Google implementation...

welcome-header

Added to user settings menu...

user-settings

Default scopes are set to...

```
defaultScopes: new Set([
  'openid',              // Get ID token
  'offline_access',      // Get refresh token
  'profile',             // Read basic profile
  'email',              // Read primary email address
  'User.Read',          // Get user photo
]),
```

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [x] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by timja — APPROVED** [review]
I tested this following the docs and was able to authenticate:

image

Any chance we can get this in the next release @soapraj

Thanks!

**Review by soapraj — APPROVED** [review]

**Comment by soapraj** [comment]
sure @timja 

@ContrarianChris Would you be able to rebase on the latest master and resolve conflicts?

**Comment by timja** [comment]
@soapraj it's 3am for him according to GitHub, would you be able to do it you should have access as a maintainer 😄

**Comment by javaniecampbell** [comment]
@ContrarianChris thank you for this will be integrating into my azure-pipelines plugin, you saved me some time, been on vacation will be returning to development this week hopefully a PR for azure-pipeline plugin

**Pull request merged**
