### PR TITLE
Use navigation handler in onClick to view full results

### PR DESCRIPTION
**Pull request by ciprianna**
## Hey, I just made a Pull Request!
Full results button in searchModal was not correctly navigating onClick. This switches the onClick to the correct handler function to navigate.

Fixes bug described in https://github.com/backstage/backstage/issues/18381, where clicking the link does not navigate to the full results page.

#### :heavy_check_mark: Checklist

- [✔️ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [✔️  ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [✔️  ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by ciprianna** [comment]
@camilaibs  - this is related to your change [here](https://github.com/backstage/backstage/pull/18236). It looks like this was just a typo, but please let me know if this is different from what you were expecting.

**Review by awanlin — APPROVED** [review]
Thanks for running with a fix for this @ciprianna, this looks good to me 🚀

**Comment by awanlin** [comment]
FYI @ciprianna the E2E test failing are not related to your changes so don't worry about them for now

**Comment by ciprianna** [comment]
okay, thanks @awanlin. Was just looking into that 😅

**Comment by ciprianna** [comment]
re-open - I think this is good, just needs the codeowners approval.

**Comment by awanlin** [comment]
Hi @aitherios, @soapraj, any chance you can review this? It's a fairly impactful issue as it means you can't get to the search results without some poor workarounds.

@benjdlambert just adding this to your radar as well, would be great to get into the next release!

@ciprianna re-opened this for you, sorry I lost track of it and we didn't get this pushed forward

**Comment by awanlin** [comment]
Sadly it looks like we might also hit some build issue that are not related to this change again :(

**Review by tikabom — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]

**Comment by awanlin** [comment]
Many thanks for the contribution @ciprianna! Thanks for the reviews @tikabom and @benjdlambert 🚀

**Pull request merged**
