### PR TITLE
fix the wrong command

### PR DESCRIPTION
**Pull request by chanwit**
Here's a quick fix for a small typo please.

### CODE REVIEW

**Comment by freben** [comment]
Hi! This is actually correct now. https://github.com/spotify/backstage/pull/1745

**Comment by chanwit** [comment]
Thank you for you response, @freben 

Our team is just trying the command `npx @backstage/create-app` a couple hours ago but it failed. Could you please confirm that it's working?

**Comment by freben** [comment]
Yes, I tried it again just now and it went through correctly.

In what way did it fail for you, what was the output? And did the other command that you suggested in this change work better?

**Comment by chanwit** [comment]
Thank you @freben 
It seems to be broken on a Windows 10 machine, when there's a space in the path.

**Comment by freben** [comment]
Could you provide any additional details? Exactly how does it fail, what is the terminal output?

**Comment by chanwit** [comment]
Or perhaps my team member, they did it in a non-empty directory. could that be the case?

**Comment by chanwit** [comment]
Confirmed that it's the mistake from misuse. 

For the improvement, it would be great to add an error message saying that the directory is not empty.
Thank you @freben 
I'm closing this issue.

**Pull request closed without merging**
