### PR TITLE
Scaffold template card

### LINKED ISSUE #1298: Scaffold Component Template List
## Feature Suggestion

Screenshot 2020-06-15 at 13 40 49

Should be update to look something more like the designs.

- Update the card listings with the new waves/headers defined by component type (Service, Website, etc)
- Render the real life data from the backend rather than stubbed data.

### PR DESCRIPTION
**Pull request by wesleyyee**
## Hey, I just made a Pull Request!

**Hold for:**
* svg assets
* scaffolder client

Screen Shot 2020-06-16 at 1 54 16 PM

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by stefanalund** [comment]
Would love a screenshot 😬

**Comment by wesleyyee** [comment]
@stefanalund sure, not much to show tho without the assets :)

**Comment by stefanalund** [comment]
Can’t you use the Wave component inside the Header?

**Comment by wesleyyee** [comment]
@stefanalund yea we could adapt it to work, but the requirements here talked about switching between different svgs for different types

**Comment by stefanalund** [comment]
I think that might have been a misunderstanding, the open source “bursts” don’t use svgs. They are implemented using CSS. There are pageTheme variants for all the different component types (services, websites, ...) that should be possible to use as-is here as well.

**Comment by wesleyyee** [comment]
i think i'm a little confused by `the open source “bursts” don’t use svgs` so the 'bursts' are just gradients (which is what is in the linked theme)

**Comment by stefanalund** [comment]
The page themes are a combination between gradients and wave patterns. I was hoping the same could be used here.

**Review by stefanalund — APPROVED** [review]
Let's ship this out now and improve the UI later on.

**Pull request merged**
