### PR TITLE
Fix typo for UnprocessedEntitiesModule

### PR DESCRIPTION
**Pull request by velocibear**
## Hey, I just made a Pull Request!

Fix typo for UnprocessedEntitiesModule.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Oh woops! This will need a `minor` changeset for this package as it's a breaking change. Do you think you can add one by following `yarn changeset` in the root of the repo.

**Comment by velocibear** [comment]
> Oh woops! This will need a `minor` changeset for this package as it's a breaking change. Do you think you can add one by following `yarn changeset` in the root of the repo.

Yeah, added this changeset.

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks for this @velocibear! I've updated the changeset a little bit to reflect what the end user has to do too 👍

**Comment by webark** [comment]
Do you think this should be a patch so that people aren't importing the wrong import for a time? I know pathing individual plugins within the backstage repo can be annoying.. but just thought I suggest it to see if it's what people would want.

**Pull request merged**
