### PR TITLE
fix: draw only what is in the system

### PR DESCRIPTION
**Pull request by erkanzileli**
Signed-off-by: Erkan Zileli <erkan.zileli@trendyol.com>

## Hey, I just made a Pull Request!

System diagrams are not working right IMO. There are nodeless arrows. It is drawing an arrow for each relation of the system's parts but not drawing any node because the parts are not actually part of the system. Nodeless arrows are just related to a specific part of the system.

For example, when you have multiple APIs but they are not part of the system, the diagram is like below.

image

What the diagram should be is below

image

Waiting for your responses.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
I can see both system-exclusive and non-system-exclusive graphs being useful. Could it be made an option? I expect it to be very common to have significant (important to the viewer) relations to out-of-system entities.

There are several options for how to best achieve it. There could for example be a grouping box around the in-system entities (like a dotted/dashed border thing or so) and then the out-of-system entities could be collapsed into just one node that you can click on to explode. Or something like that. It's open for discussion I'd say :)

**Comment by erkanzileli** [comment]
Thanks for such a nice comment @freben. I like your idea but it is another feature I guess. My purpose here is fixing the nodeless arrows. We might open an issue for the feature you said or this PR gets bigger.
WDYT?

**Comment by erkanzileli** [comment]
@freben @Rugvip I am waiting for your thoughts guys. Do you think this is OK for merging?

**Comment by freben** [comment]
@Rugvip as new goalie -

I had a discussion elsewhere with the author about this. While the outcome does look better in the image, I'm not sure that it is the right fix.

- Seeing cross-system relations, perhaps grouped up or whatnot, but still seeing them, will be an important use case
- For those that have incomplete system models that aren't perfectly set up yet etc, hiding information may be confusing and less helpful in driving people to change and improve their metadata

Having an option to toggle between showing only in-system things would be useful, sure. Then as a separate effort one could later tackle how to nicely display in-system things vs out-of-system things (perhaps grouped by a dashed-line rectangle or similar?).

**Comment by Rugvip** [comment]
I've been looking at reproducing this and I haven't been able to O_o. Wondering if I'm missing something here or what's up :grin:

I tried adding the following to our `artist-lookup` example component:

```diff
-  dependsOn: ['resource:artists-db']
+  dependsOn: ['resource:artists-db', 'api:petstore', 'api:streetlights', 'component:playback-sdk']
+  providesApis:
+    - petstore
+    - streetlights
+    - hello-world
```

And it seems to render alright?

image

Or from the system's point of view:

image

**Comment by benjdlambert** [comment]
@erkanzileli I think that the issue here is that you are using the `EntitySystemDiagramCard` not the new `EntityCatalogGraphCard` which might solve some of these issues you're facing. Wondering if it makes sense for us to deprecate the older one. Could you give it a try with the new component something similar to here: https://github.com/backstage/backstage/blob/e29fb1a5d0993e954a3d49e294d6aceb04f89668/packages/app/src/components/catalog/EntityPage.tsx#L582-L597 and see what happens for you?

**Pull request closed without merging**
