### PR TITLE
feat: add option to not protect the default branch

### PR DESCRIPTION
**Pull request by leodag**
## Hey, I just made a Pull Request!

This PR adds a new parameter `protectDefaultBranch`, defaulting to `true`, to the `publish:github` action. This allows projects to be published without branch protection.

The need for this has arisen from some old projects we have created templates for, which need the default branch not to be protected.

This is my first PR to the project, so all feedback is welcome :)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] N/A Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] N/A Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Nice, looks good 👍 Thank you! 🎉

**Review by jhaals — COMMENTED** [review]
Nice work!

You also need to commit the updated api report, it can be generated with `yarn build:api-reports`

**Comment by benjdlambert** [comment]
I went ahead and fixed up the API reports, so this should be good to go when it's all green! ✅

**Comment by suuus** [comment]
Hey @leodag, congrats on your first merged PR 🎉 Nice work 👍 Please let me know if we can be helpful in any way.

**Pull request merged**
