### PR TITLE
Azure Spring Apps Plugin

### PR DESCRIPTION
**Pull request by ch-enfuse**
Changed icon to be shown in plugin's marketplace card.

Signed-off-by: ch-enfuse <chr@enfuse.io>

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thanks! Just to double check, do you have right/permission to use icon?

**Comment by awanlin** [comment]
Based on my experience for the Azure DevOps plugin it's pretty hard to get permissions to use their icons

https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks

**Comment by Rugvip** [comment]
@awanlin thank you for the context! What does the existing icon represent @ch-enfuse, your own org's logo? Perhaps a simple text-based logo could do for now?

**Comment by ch-enfuse** [comment]
Thank you for that @awanlin ! @Rugvip We're going to go with our organization's logo (enfuse.png) I pushed new changes to fix the iconUrl that was broken before

**Review by Rugvip — APPROVED** [review]
Alright, thanks! 👍

**Pull request merged**
