### PR TITLE
explicit types and remove cypress resolution override

### PR DESCRIPTION
**Pull request by Rugvip**
Explicitly list types used by each package. Without this anything inside `@types` dirs are included.

Each plugin can override the types used in their `tsconfig.json`, but tbh I don't know how that will affect the package and availability of types when importing the plugin in an app later.

I'm imagining this could increase build speed, but not seeing any big difference, at most a few % if anything.

The main reason for making this change was so that we can get rid of the version override of cypress, since the reason we had to do that was clashing types between jest and mocha. Now that we have to include types explicitly that's no longer an issue.

### CODE REVIEW

**Review by freben — APPROVED** [review]
What was the effect if you skip these tsconfig changes?

Will we make these changes on all public packages that don't inherit from the cli config dir? (Like the backend)

**Comment by Rugvip** [comment]
@freben omitting would give you the default behaviour, which is that all type definitions that can be found will be used. More info here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

Backend package was supposed to have the change, removed it by mistake :grin: Added back now though.

**Comment by freben** [comment]
Would have been nice to blacklist mocha instead of whitelisting these, but I guess that isn't possible :/

**Comment by Rugvip** [comment]
@freben, indeed... here's a thread on that: https://github.com/microsoft/TypeScript/issues/18588

**Comment by Rugvip** [comment]
Build issues were because we ended up bringing in 2 versions of cypress, issue is being tracked here: https://github.com/cypress-io/cypress/issues/4595

Fixed by making sure we're only installing one version, but it could pop up again.

**Pull request merged**
