### PR TITLE
feat(scaffolder): add EntityFilterQuery support on Entity and Owner Picker components

### PR DESCRIPTION
**Pull request by rikez**
## Hey, I just made a Pull Request!

Solves: https://github.com/backstage/backstage/issues/14979 

- Added `catalogFilter` prop of type [`EntityFilterQuery`](https://github.com/backstage/backstage/blob/774c42003782121d3d6b2aa5f2865d53370c160e/packages/catalog-client/src/types/api.ts#L74) to the `EntityPicker` schema to allow users to filter entities as they want.
-  Updated `EntityPicker`'s dependent component `OwnerPicker` to also include the `catalogFilter` prop.
- Retro compatible with existing implementations. The `catalogFilter` prop only takes precedence over `allowedKinds` when provided. The below example results in a list of entities of `kind: Group` and `spec.type: team`
  ```yaml
    owner:
      title: Owner
      type: string
      description: Owner of the component
      ui:field: OwnerPicker
      ui:options:
        allowedKinds: 
          - User
        catalogFilter:
          - kind: Group
            spec.type: team
  ```

#### Open Questions

- Should we remove the `allowedKinds` prop?
- When and where are the components' schema being validated?

#### Testing

<details>
<summary>with allowedKinds</summary>

</details>

<details>
<summary>with catalogFilter - list of filter expressions</summary>

</details>

<details>
<summary>with catalogFilter - single filter expression</summary>

</details>

<details>
<summary>catalogFilter takes precedence over allowedKinds</summary>

</details>

<details>
<summary>with empty catalogFilter (filters by default Group and User kind)</summary>

</details>

<details>
<summary>with catalogFilter (filtering by annotations)</summary>
Screen Shot 2022-12-07 at 1 32 36 PM
Screen Shot 2022-12-07 at 1 33 18 PM
Screen Shot 2022-12-07 at 1 33 26 PM
Screen Shot 2022-12-07 at 1 33 40 PM
</details>

<details>
<summary>with catalogFilter (filtering by tags)</summary>
Screen Shot 2022-12-07 at 1 35 09 PM
Screen Shot 2022-12-07 at 1 33 26 PM
Screen Shot 2022-12-07 at 1 33 52 PM
Screen Shot 2022-12-07 at 1 35 00 PM
</details>
      

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by regicsolutions** [comment]
Great work on this @rikez 

Question: Does the filter work for all entity metadata including labels and annotations?

**Comment by rikez** [comment]
Hi @benjdlambert, wondering when it would be possible to take a look at this. Thank you!

**Review by benjdlambert — APPROVED** [review]
Nice work on this! Think this is looking pretty good, apologies for the delay! 👍

**Comment by benjdlambert** [comment]
I wonder if we want to deprecate the other `allowedKinds` way, and warn if it is provided to the `EntityPickers` and tell people to use the `catalogFIlter` option instead?

**Comment by rikez** [comment]
@benjdlambert Makes sense to me. Is there a standard in he project for deprecating/warning developers?

**Comment by jhaals** [comment]
> @benjdlambert Makes sense to me. Is there a standard in he project for deprecating/warning developers?

Fields/exports can be marked `@deprecated` TSDoc and we sometimes also log deprecation messages to notify users that their using deprecated APIs, not sure we want/need a log message in this case?

```ts
/** @deprecated This const has been replaced but the superior foobar **/
export const Foo = 1
```

It's worth making sure that it's clear in the changelog what's deprecated and perhaps a small example on how to migrate in the most common case :)

**Comment by rikez** [comment]
@jhaals @benjdlambert I marked the `allowedKinds` field as deprecated in both `EntityPicker` and `OwnerPicker`, updated the changeset to include a more descriptive message and examples, and updated all docs and templates that were referencing `allowedKinds`.

**Comment by regicsolutions** [comment]
@rikez i have a use case where I was looking to show `metadata.title` in the drop down given its a friendly name but looking to use the `metadata.name` value for that entity in my action wondering if this is possible with these changes?

**Comment by benjdlambert** [comment]
@regicsolutions not this change no, but it's probably going to be possible once we move all these pickers to `Autocomplete` components rather than selects. https://github.com/backstage/backstage/issues/15007

**Review by benjdlambert — APPROVED** [review]
OK Nice, let's go with this!

I'm in two minds to deprecate the `OwnerPicker` entirely if we're being pretty non opinionated about it. It's just a thin wrapper around the `EntityPicker` but I think we can hold off on that conversation for another time. 👍

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
🎉

**Comment by madianas21** [comment]
Question, will it be possible to filter to Groups the user is a member of? Such as:
```
  owner:
    title: Owner
    type: string
    description: Owner of the component
    ui:field: OwnerPicker
    ui:options:
      catalogFilter:
        kind: Group
        spec.members:
            - ${{ user.entity.metadata.name }}
```

**Comment by rikez** [comment]
@madianas21 You should be able to filter by any field present in the entity, but I think the dynamic variables like `${{ user.entity.metadata.name }}` are only available at the scaffolder `steps` stage. Correct me if I'm wrong @benjdlambert / @jhaals.

**Comment by benjdlambert** [comment]
@madianas21 @rikez that's correct - the dynamic values are only for server side steps. 

If you want to list all the Groups that the user is part of, then you'll be best off creating a `Custom Field Extension` that uses the `catalog` API to recursively look up all groups that have the Signed in users ref in them as a member, and then maybe any groups which have those groups as children for transitive group ownership.

We'd be open to having that Field extension in the core offering too I believe if it's something you want to contribute @rikez or @madianas21?

[these docs](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions) should help you create some extensions and happy to talk through some more implementation detail if either of you are up for it? :pray:

**Comment by rikez** [comment]
@benjdlambert I'm up for it. I'm going to create an issue (if there isn't one) to keep track of that.

**Pull request merged**
