### PR TITLE
Jenkins: enable integration with multiple instances, based on the path defined in the catalog entity

### PR DESCRIPTION
**Pull request by jot-hub**
## Hey, I just made a Pull Request!

Different catalog entities *may* be built in different `jenkins` instances.
It will be great to be able to choose a particular `jenkins` instance to scrape based on where the component is built.
The component could refer to the `jenkins` path in its `catalog-info.yaml`.

Potential annotations for 2 components in their respective `catalog-info.yaml`:
component 1:
```yaml
metadata:
  annotations:
    jenkins.io/github-folder: 'org1/job1'
    backstage.io/jenkins-proxy-path: '/jenkins/instance1'
```

component 2:
```yaml
metadata:
  annotations:
    jenkins.io/github-folder: 'org2/job1'
    backstage.io/jenkins-proxy-path: '/jenkins/instance2'
```

corresponding `app-config.yaml`:
```yaml
proxy:
  '/jenkins/instance1':
    target: 'https://instance1.blah'
    headers:
      Authorization:
        $env: JENKINS_INSTANCE1_BASICAUTH_HEADER
  '/jenkins/instance2':
    target: 'https://instance2.blah'
    headers:
      Authorization:
        $env: JENKINS_INSTANCE2_BASICAUTH_HEADER
```

Similar change in `@roadiehq/backstage-plugin-argo-cd`: https://github.com/RoadieHQ/backstage-plugin-argo-cd/pull/27/files

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Fox32** [comment]
I think the new annotation is a bit to technical for the users, I would prefer to have something like "jenkins instance".

@freben I wonder if this is the place where we should start to have a backend for he jenkins plugin?

**Comment by jot-hub** [comment]
Thanks for the feedback! 😸 
I thought `backstage.io/jenkins-proxy-path` captures what it means, in detail - maybe too much detail.

some alternatives?
`backstage.io/jenkins-proxy`
`backstage.io/jenkins-config-name`
`backstage.io/jenkins-config-id`

**Comment by freben** [comment]
Yeah maybe it's time to consider having a backend plugin that can hold several different configurations... Just short answer, due to Friday and all :)

**Comment by regicsolutions** [comment]
Did we ever come to an agreement on deprecating the 'jenkins.io/github-folder' annotation name now that it's been proven to support just about all scm providers? 

Think it makes sense to make it more generic to something like:

jenkins.io/project-folder

or

jenkins.io/org-folder

**Comment by benjdlambert** [comment]
Following on from @freben's comment.

I think we should avoid having multiple routes in proxy to solve this issue. I think that we should be moving this logic into a backend plugin for Backstage that can take into account some annotation that can identify the Jenkins instance if specified. If not maybe it can do a best guess and list the projects in each instance?

The backend plugin would be initialized with the jenkins instance available, and the frontend plugin would call the backend service rather than jenkins directly.

This also gives the added benefit that we can add features to the backend plugin to help with the frontend. Easier pagination etc or whatnot.

Does this sound like something that you could take on @jot-hub?

**Comment by regicsolutions** [comment]
Think it would make sense to start them both with jenkins.io to alleviate any confusion across teams.

Maybe each proxy instance can have a label and that label could be used in the annotation? 

For example: `https://app-supportJenkins:8080` with a label called `app-support-org` would be `jenkins.io/app-support-org:`

**Comment by ConnorDY** [comment]
Any updates on this?

**Comment by jot-hub** [comment]
I took a quick dab at handling multiple Jenkins instances with least change possible - based on previous work with argocd plugin 
> Similar change in @roadiehq/backstage-plugin-argo-cd: https://github.com/RoadieHQ/backstage-plugin-argo-cd/pull/27/files

I understand the feedback here and it sure makes sense. 
How can I start a backend plugin? are there pointers?

I will close the PR and start a new one based on the feedback I get here with starting a backend plugin.

However, if someone wants to jump on this, am more than happy. Cause, I won't be able to work on this as much as I would like in the short-term.

**Comment by benjdlambert** [comment]
You can use `yarn backstage-cli create-plugin --backend` to get started with a backend plugin and that should get you setup with something that you can run at least.

Then I guess it's just about tweaking the config schema and creating some REST API that will allow you call the API given an entity identifier like `/kind/:kind/namespace/:namespace/name/:name` and then grab the annotation to find out where it is.

Then use the config schema to make a request to that Jenkins instance and create the response for you.

I haven't digged into the Jenkins plugin to much i'm afraid, so I don't know the scope too much but this sounds like a good start.

**Comment by freben** [comment]
closing in favour of #5642

**Pull request closed without merging**
