### PR TITLE
Implement "Branch protection rules" support for "publish:github" action

### PR DESCRIPTION
**Pull request by TomBalt**
Signed-off-by: Tomas Baltusis <baltusis.t@gmail.com>

## Hey, I just made a Pull Request!

Small change in the built-in "publish:github" action.
Expanded action with "Branch protection rules" support capabilities.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by TomBalt** [comment]
Hi @freben could you have a look quickly and approve the change? 
Thanks

**Comment by TomBalt** [comment]
Stale? :D Common...

**Comment by Rugvip** [comment]
@TomBalt sorry, we've had BackstageCon + KubeCon + a week off, hang tight x)

**Comment by TomBalt** [comment]
> @TomBalt sorry, we've had BackstageCon + KubeCon + a week off, hang tight x)

I am scared that this PR will be closed automatically and forgot :D

**Comment by Rugvip** [comment]
👍 , even if it gets closed automatically they're visible to us and we'll re-open any that got closed without review etc.

**Review by freben — APPROVED** [review]
Thanks!

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻

**Pull request merged**
