### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by ajbw**
Adjust Expedia Group contact list.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
@ajbw Hi and welcome! See the DCO message above - remember to sign commits!

**Review by jhaals — COMMENTED** [review]
Thanks for the contribution!
Commits need to be DCO signed in order for us to merge them.
It's as simple as `git rebase HEAD~1 --signoff && git push -f` to update your existing commit.

**Comment by benjdlambert** [comment]
Ping @ajbw

**Comment by ajbw** [comment]
Yikes; sorry folks, I've been out and completely missed this.  Thank you for creating the replacement PR @freben.

**Pull request closed without merging**
