### PR TITLE
Add ProjectID to the output for #10907

### PR DESCRIPTION
**Pull request by Parsifal-M**
Signed-off-by: Peter Macdonald <macdonald.peter90@gmail.com>

## Hey, I just made a Pull Request!

Added `projectId` field in the gitlab action and added it to the output under the `jsonschema`

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — CHANGES_REQUESTED** [review]
Thanks! A tiny tweak to the changeset will make Vale happy :)

**Comment by benjdlambert** [comment]
Would also like to see a test in here if possible too :pray:

**Comment by Parsifal-M** [comment]
> Would also like to see a test in here if possible too pray

Would this be in the `gitlab.tests.ts` file? Might take me some time to add it there as I've not done that before. Do you have any pointers?

**Comment by benjdlambert** [comment]
Yep indeed.

So you could either add it to another tests suite which makes sense, or create a one separately. Really doesn't matter. But you probably want to check that `mockContext.output` has been called with the right params.

**Comment by benjdlambert** [comment]
If you take a look through some of the tests you should see how it works a little better.

**Review by jhaals — APPROVED** [review]
Looking good 👍

**Comment by suuus** [comment]
Hey @Parsifal-M, congrats on your first merged PR 🎉 Nice work 👍 Please let me know if we can be helpful in any way.

**Pull request merged**
