### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ivan-burazin**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Hey @ivan-burazin, can we get some context on this PR please? :pray:

**Comment by ivan-burazin** [comment]
Please close this, as need to work on this some more. Thanks for replying

**Comment by benjdlambert** [comment]
OK thanks!

**Comment by awanlin** [comment]
Hi @ivan-burazin, just wanted to shared that we do have this in the `/contrib` folder: https://github.com/backstage/backstage/tree/master/contrib/.devcontainer. This is the PR that added it: https://github.com/backstage/backstage/pull/14917. There's some comments in that PR as to why it wasn't added at the root but it might be worth reconsidering that or at least having a conversation about it.

**Pull request closed without merging**
