### PR TITLE
feat(auth-backend): Allow passing keyDurationSeconds as input to createRouter function

### PR DESCRIPTION
**Pull request by antoniomuso**
Signed-off-by: Antonio Musolino <antoniomusolino007@gmail.com>

## Hey, I just made a Pull Request!

Hi, I need to increase the tokens expiring time, what do you think about allowing the passing of keyDurationSeconds as input? 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by jhaals — CHANGES_REQUESTED** [review]
Thanks for the proposal. It's probably a good place to put it. We had some build issues earlier and had to do some trickery to the master branch. Could you please rebase your PR again please :)

**Comment by antoniomuso** [comment]
Done!

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you! 👍 

This is a lil bit tricky, because the expiration time that we communicate to the frontend is completely based on the session we receive from the upstream provider. Our own backstage session is ignored. This means that if you use something like GitHub App auth that uses 8h tokens, then our own tokens will expire after just 1h and users need to refresh the page.

We happen to have a [workaround](https://github.com/backstage/backstage/blob/35865c1d77fcb707463bffb92d5d09376c1dc829/plugins/auth-backend/src/providers/github/provider.ts#L210-L213) for the expiration issue in the GitHub provider, but iirc it's not present anywhere else. What provider are you using where you're facing this issue? What expiration time does the token have?

Similarly, if we add this configuration and one would set a shorter key duration than what the provider uses, you'd run into the above issue as well. That means that this configuration in its current form is pretty much just a foot gun, and I feel we need to fix the underlying issue instead.

What I'm thinking we could do is to extract the `BACKSTAGE_SESSION_EXPIRATION` constant, or even better, pass it as input to the providers. Then we apply the GitHub provider fix of `expiration = Math.min(providerExp, backstageExp)` to all providers.

What do you think? Is this something you're happy to work on? Otherwise we can open it up for contributions or put it in the backlog with somewhat high priority.

**Comment by antoniomuso** [comment]
I understand, but for my use case, this change is enough because I'm using the [ldap-auth-plugin](https://github.com/immobiliare/backstage-plugin-ldap-auth); it uses the token expiration time.

**Review by Rugvip — COMMENTED** [review]
Ah, the `ldap-auth-plugin` really shouldn't be using the Backstage tokens as its main sessions store to be honest. By allowing session refreshes using the existing token, token expiration is effectively removed, which I really don't want to encourage. It would be better if the `ldap-auth-plugin` would switch to using a secure session store to store sessions instead, and be able to handle refreshes through that instead.

Overall I feel that a global configuration of the token expiration doesn't make sense right now or in the future. It's a very simple change, but a dangerous one for the reasons mentioned above, and one that we would want to remove in the future. I do think that it would make sense for individual auth providers to control the expiration though, it makes a bit more sense at that level. The default would be that the expiration is inaccessible from the outside, to avoid the footgun, but some providers might expose it as an option where it makes sense.

Adding expiration configuration at the provider level seems a bit tricky though, but ofc not impossible. Would you want to give it a shot? I could give a couple of pointers

**Comment by antoniomuso** [comment]
Ok, I answer separately:
1. `ldap-auth-plugin` uses only the generation token functions given by Backstage to generate the token and identify the user it, doesn't store anything else, the plugin is thought only to identify the user in a secure internal VPN.
2. I understand, thank you. I will do it, like you said, at the provider level. I think having a contract between client and server where token expiration time is increased by a constant value can be a solution, not at all clean but it is a solution.

**Pull request closed without merging**
