### PR TITLE
Narrow Types for React 18

### PR DESCRIPTION
**Pull request by RobotSail**
## Hey, I just made a Pull Request!

The goal of this pull request is to narrow the types used in the current repo with what React 18 and its related libraries expect.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Still working on this one?

`major` change is a definite no-go.

The changes in catalog-model should be reverted.

Not sure about the `const element` changes, those were testing components in the first place, not nodes, so wasn't it just the name of the variable that was confusing?

**Comment by RobotSail** [comment]
Thanks for taking a look at this @freben. I'm welcome to any suggestions on how to evolve this PR, but the changes you mentioned are a prerequisite to types working properly in React 18. 

Here's a breakdown of each:

> major change is a definite no-go.

This change is due to how react-router defines types in React 18. There's a requirement to distinguish between whether a route is an index or a child. At the moment this PR solves it in the same way that the upstream types handle it - which is by splitting the definition of the two (`BackstageIndexRouteObject` and `BackstageNonIndexRouteObject`) and defining the base type `BackstageRouteObject` as a union of the two. 

> The changes in catalog-model should be reverted.

The reason for these changes is that [`AddEntitiesDrawer`](https://github.com/backstage/backstage/blob/5f7ce0d289505e26488afbee20d1446a40513ab4/plugins/playlist/src/components/PlaylistPage/AddEntitiesDrawer.tsx#L140) passes a result from a regex match into a function which expects an entityRef object. In React 18, for whatever reason, the compiler now complains about not being able to cast the return from regex matches into the entityRef. 

To fix this, I added a type assertion function; however, in order for this to work, the type being asserted needs to be defined somewhere explicitly. 

When I looked at the type definitions in catalog-model, I saw that most of them were just variations of the EntityRef type with different fields being marked as optional. So to fix two birds with one stone, I created a utility type which allows us to selectively set fields to be optional. 

This allows both the type assertion function to be written where it was needed, as well as having consistent typings for the other types in catalog-model.

I'm open to suggestions on how this should be changed or adjusted, but the type assertion needs to happen somehow. 

> Not sure about the const element changes, those were testing components in the first place, not nodes, so wasn't it just the name of the variable that was confusing?

`element` was previously a type of ReactNode, but this is narrowed in React 18 so that its usage as is isn't compatible. Since it was previously being set as an empty returning function, I changed it to null to be more explicit about its behavior.

**Comment by freben** [comment]
What I mean is, a `major` bump is basically unheard of and we'd like for that not to happen at all if possible.

By the way, did you run `yarn build:api-reports` and commit that with your PR? That would give visibility into what the user-affecting surface changes are.

I'd like to understand what it is about the `for whatever reason` part that made the types not align. What was the exact error? What is is about the `Partial<Pick` dance that makes the result any different? Would a `?: string | undefined` have sufficed?

Note also that the tests are red in a bunch of places, especially after the route related changes.

**Comment by RobotSail** [comment]
Thanks for following up on this @freben. I can change it to be a `minor` bump if you'd like, I was just trying to follow semver. Since the type definitions will change, I figured it makes sense to be `major`. 

> By the way, did you run yarn build:api-reports and commit that with your PR? That would give visibility into what the user-affecting surface changes are.

Just ran it and updated the PR, thank you for pointing that out.


> I'd like to understand what it is about the for whatever reason part that made the types not align. What was the exact error? What is is about the Partial<Pick dance that makes the result any different? Would a ?: string | undefined have sufficed?

The reason was that all of the types in the callback were typed as any, so there was no TypeScript error since type checking was disabled entirely. 

The `SelectPartial` utility type just allows you to express that certain functions return various fields as potentially undefined, which is what I observed when I investigated its usages. If you prefer, I can change it to be an in-line definition, you would just run the problem of needing to update the same type in multiple places if it needs to change or be refactored at some point down the line.

**Pull request closed without merging**
