### PR TITLE
Add a lint rule to avoid using __dirname

### LINKED ISSUE #2244: Add a lint rule to avoid using __dirname
## Feature Suggestion

It is recommended to use the `resolvePackagePath` in `@backstage/backend-common` package instead of doing a custom path resolution using `__dirname`. See https://github.com/spotify/backstage/pull/2237 for example.

## Possible Implementation

Add an ESLint rule which disallows using `__dirname`. (Maybe give a warning with the message about `resolvePackagePath`?)

### PR DESCRIPTION
**Pull request by themousepotato**
## Hey, I just made a Pull Request!

Fixes #2244 

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
Thanks! I wonder if https://eslint.org/docs/rules/no-restricted-globals works as an alternative? Might be a bit less cryptic than matching AST nodes. If that doesn't work this is fine though!

I'd mention that `resolvePackagePath` is exported from `@backstage/backend-common` too, something like "... try `resolvePackagePath()` from `@backstage/backend-common` instead."

**Comment by themousepotato** [comment]
Thanks for the quick review @Rugvip! I'd tried `no-restricted-globals` before but didn't get that to work. I've updated the message as you suggested in the latest commit.

**Review by Rugvip — APPROVED** [review]
@themousepotato alright, let's go with this then!

Tbh you could just disable the rule in the CLI to get this through, as it doesn't use winston and is allowed to use `__dirname`.

**Comment by marcuseide** [comment]
@themousepotato Hey, any updates here? You might want to try to disable the rule in the CLI as mentioned to get this pass CI.

**Comment by themousepotato** [comment]
Hey @marcuseide, thanks for reminding. I thought no changes were required for this PR. I tried disabling the rule in two of the occurences in the initial failing ci. Should I do this for all occurences of `__dirname` ?

**Comment by benjdlambert** [comment]
@themousepotato yeah, if you just ignore the rule in the places to get it through this PR would be great!

**Review by OrkoHunter — APPROVED** [review]

**Comment by themousepotato** [comment]
@Rugvip @marcuseide Is this good to go? Let me know if I need to change something.

**Comment by Rugvip** [comment]
@themousepotato probably, will see what CI says :p

**Pull request merged**
