### PR TITLE
Docs: Remove markdown version constraint for mkdocs-techdocs-core

### PR DESCRIPTION
**Pull request by iswariyam**
## Hey, I just made a Pull Request!

* The latest version of [mkdocs-techdocs-core](https://github.com/backstage/mkdocs-techdocs-core) (1.1.4) support markdown version >=3.2, <4.0 as this [PR](https://github.com/backstage/mkdocs-techdocs-core/pull/74) has been merged
* Backstage techdocs documentation has been modified to reflect this change

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by iswariyam** [comment]
Tagging @camilaibs who merged my [PR](https://github.com/backstage/mkdocs-techdocs-core/pull/74) in mkdocs-techdocs-core to support markdown >=3.2

**Comment by camilaibs** [comment]
> Tagging @camilaibs who merged my [PR](https://github.com/backstage/mkdocs-techdocs-core/pull/74) in mkdocs-techdocs-core to support markdown >=3.2

Hi @iswariyam 👋🏻 ,
Nice to see you around again!
Could you sign off your commit?

**Comment by iswariyam** [comment]
> 

Done :-)

**Review by camilaibs — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]
Thanks :pray:

**Pull request merged**
