### PR TITLE
Update !url.startsWith condition in file.ts

### LINKED ISSUE #5236: Error during Prepare stage while creation of a new Component from a Template
An error is generated while I'm trying to create a new Component from any of the example Templates provided.
## Expected Behavior
Prepare stage should be completed without any errors and flow should pass to the next stage.

## Current Behavior
Error is getting thrown.
```
2021-04-06T13:35:28.000Z Beginning step Prepare
2021-04-06T13:35:28.000Z info: Preparing the skeleton {"timestamp":"2021-04-06T13:35:28.793Z"}
2021-04-06T13:35:28.000Z InputError: Wrong location protocol, should be 'file', file://C:\Users\MYUSERNAME\MYFOLDERNAME\Repos\Backstage\backstage\plugins\scaffolder-backend\sample-templates\springboot-grpc-template
    at FilePreparer.prepare (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/prepare/file.ts:34:13)
    at Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/stages/legacy.ts:48:24)
    at TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:147:24)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:58:9)
```

## Possible Solution
There is a bug in FilePreparer.

## Steps to Reproduce

1. Click on Create a new Component
2. Select a Template
3. Error is thrown

## Context
I'm trying to create a new Component from one of the Templates.

## Your Environment

- NodeJS Version: 14.15.1
- Operating System and Version: Windows 10 (1904) Enterprise
- Browser Information: Chrome Version 89.0.4389.90

### PR DESCRIPTION
**Pull request by lancelot1337**
Signed-off-by: lancelot <sudhanshusah2001@gmail.com>

## Hey, I just made a Pull Request!
Fixes #5236

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ :heavy_check_mark:] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
@rugvip i seem to remember you mentioning something that was caused by this somewhere, can you remember what it was? 

@lancelot1337 looks like theres some tests failing though 👍

**Comment by Rugvip** [comment]
Ah sorry, I actually ended up looking at this but didn't get around to trying out the tests on Windows. Tests were a bit tricky to fix, so pushed it up straight to this PR branch.

**Review by Rugvip — APPROVED** [review]
:shipit: ? :D

**Comment by lancelot1337** [comment]
Thanks for quickly reviewing the PR! :smiley:

**Pull request merged**
