### PR TITLE
Microsite: a11y fixes

### PR DESCRIPTION
**Pull request by npiyush97**
#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

plugin
new
Screenshot from 2024-01-25 21-50-15
old
Screenshot from 2024-01-25 21-59-35

Screenshot from 2024-01-25 22-55-52

hubspot 
old 
Screenshot from 2024-01-25 23-15-41
new
newhub

### CODE REVIEW

**Comment by npiyush97** [comment]
@freben moved here branch got messed up add more images.

**Comment by npiyush97** [comment]
these fixes push home and others score to 96.

**Comment by npiyush97** [comment]
explanation why the plugin color change and hubspot button color change
(context)
light over light => ❌ 
light over dark => ✅
dark over light => ✅

**Comment by emmaindal** [comment]
Thank you again for contributing these fixes, the one thing I've some input around is the heading now being underlined for the blog post previews. 

Screenshot 2024-01-26 at 08 41 41

After discussing a bit with one of our accessibility engineers I wonder if it makes sense to 

1. change the heading to not be a link (since its a duplicate of the "read more" action anyways)
2. check that the "read more" has a aria-label including the full title of the blog so that its clear where it takes the user. 
3. Also increase the color contrast of the links color (since this will most likely be applied across the microsite I'd recommend open a separate issue for this that we can discuss with our designers first)

would love @freben and @camilaibs's perspective here as maintainers as well in case there is a historical reason for keeping headings as links!

**Comment by freben** [comment]
@npiyush97 What's your feedback on the comment above?

**Comment by npiyush97** [comment]
> @npiyush97 What's your feedback on the comment above?

yeah can fix this with something like this make it like previous only underline paragraph anchors.
underline is only needed because of text size so only anchor tags in paragraphs need that. heading and read more not because of their size and heading as link is okay with me.

```
#__docusaurus {
  .row {
    .col {
      div[class^='markdown'] {
        p{
          a {
            text-decoration: underline;
          }
        }
      }
    }
  }
}
```
if happy with this I can make these changes.

**Comment by npiyush97** [comment]
Screenshot from 2024-01-30 14-26-08
look like this

**Review by freben — APPROVED** [review]
I'd say let's merge and tweak ... feel free to address the title underlines separately

**Pull request merged**
