### PR TITLE
Revert of #26430

### PR DESCRIPTION
**Pull request by swnia**
## Hey, I just made a Pull Request!

The change caused issues and is therefore reverted. The updated documentation reflects the actual permissions required

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
What issues? Under what circumstances, and onto what version of gitlab? Would be good with some details referenced

**Comment by swnia** [comment]
> What issues? Under what circumstances, and onto what version of gitlab? Would be good with some details referenced

Creating a merge request now creates a 403. The `write_repository` permission does not work on the API itself but rather only when working with git over HTTPS...
Therefore, the documentation was updated to mention the `api` permission as necessary

**Comment by elaine-mattos** [comment]
Is also an issue with our installation. The `api` scope is needed to create new branches and merge/pull requests. 
We have added a yarn patch for the moment while we wait for this fix/revert to be merged. 
Thanks @jboeijenga for pointing this out and @swnia for the quick response!

**Review by benjdlambert — APPROVED** [review]
Woops! Ok, will try and get a patch release out for this too. :tada:

**Pull request merged**
