### PR TITLE
mpsanchis/add migration to gitlab scaffolder

### PR DESCRIPTION
**Pull request by mpsanchis**
## Hey, I just made a Pull Request!

     
 Two things are modified in `scaffolder-backend-module-gitlab`:
 1. (Enabler) Upgrade gitbeaker to `^40.3.0`. This required a few modifications in the plugin.
 2. (New feature) Use the [Group and project migration by direct transfer API](https://docs.gitlab.com/ee/api/bulk_imports.html) to enable project migration. This API could be used for groups, but I haven't tested the functionality, so I haven't exposed the feature in the plugin's API.
 
 Looking forward to my first PR review in Backstage 🎉 

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [X] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by jbadeau** [comment]
👍

**Comment by mpsanchis** [comment]
I have opened an issue in Gitbeaker so that type definition for `DeployToken.create` matches Gitlab's REST API, and we can delete the `ts-ignore` comment:

https://github.com/jdalrymple/gitbeaker/issues/3648

**Comment by benjdlambert** [comment]
Can we split up this PR into two PR's, one for the Gitbeaker bump and one for the new project migration actions? :pray:

**Comment by mpsanchis** [comment]
@benjdlambert sure thing, will split it now and close this PR.

However, I can't have two parallel MRs, since the new action (branch2) depends on the gitbeaker bump (branch1)...

Should I wait for branch1 to be merged, before opening the PR for branch2?

**Pull request closed without merging**
