### PR TITLE
Feature: Add README translated into Korean

### PR DESCRIPTION
**Pull request by yj-yoo**
issue : https://github.com/backstage/backstage/issues/21860

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Joonpark13 — APPROVED** [review]
My Korean is pretty rusty but this looks great! 감사합니다 🙏

**Comment by yj-yoo** [comment]
@Joonpark13 Thank you. I hope it merges quickly, but it doesn't. What more should I do?

**Comment by freben** [comment]
There's no automatic merging, a maintainer does that.

**Comment by yj-yoo** [comment]
@freben Oh.... I see. Thank you. Actually, this is my first time participating in open source... If you tell me what to do additionally, I will work on it(Any advice is welcome).

**Pull request merged**
