### PR TITLE
allow setting token subject on server token manager

### PR DESCRIPTION
**Pull request by punkle**
## Hey, I just made a Pull Request!

allow setting token subject on server token manager

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — COMMENTED** [review]
What's your plan for how this would be used?

Tbh we want to reserve the subject to properly implement backend service identities in a secure way. We'd like to do it in a what where backends can't easily spoof their identity too, so that it can be used to properly limit access across different backend deployments.

If that's the direction you're going with this I think it's all good, but I think it's best to explore a bit further how that would work in practice, so that we don't end up painting ourselves into a corner.

**Comment by punkle** [comment]
This is intended to address SPBS-CR-22-02 of the X41 report. We host multiple backstage backends that are completely independent of one another, we want tokens issued by one backend to be rejected by another. It is an additional validation along with signatures.

**Comment by Rugvip** [comment]
@punkle ah. There's nothing preventing a backend for simply spoofing their identity though, which is why we haven't done this yet. I feel there's a risk that it's just going to provide a false sense of security without improving things much in practice.

Right now it's looking like this is something we'll dive into early/mid Q4, but would gladly get it going earlier if it's something you want to drive!

Couple of high-level requirements for backend identities, off the top of my head:

- It should not be possible to spoof identities in a way that elevates access. As described in the [threat model](https://backstage.io/docs/overview/threat-model), plugins that are deployed together are considered to have full access to each other. It should however be possible to restrict access between plugins that are deployed separately in a way that cannot be bypassed.
- It should be easy for integrations to restrict service-level access between plugins, and they should be provided with a clear overview of the current configuration. For example it should be easy to configure that the search backend has service-level access to the catalog, but no other plugins do. This is important for hardening the permissions system. By service-level access we mean the use of a service token, as opposed to user-level access with a user token.
- Given a service token, it should be easy to identity its source.
- It should be easy to integrate service tokens with external systems in both directions. That is it should be easy for an external backend to validate a incoming call from a backstage backend. And it should be possible for an external backend to issue a token that can be used in a call to a backstage backend.
- The system should rely on existing technologies and standards as much as possible, without sacrificing on any of the points above.

**Comment by punkle** [comment]
@Rugvip Im not sure if we will be able to address this larger piece in the short term. It sounds promising and I think it is something we would like to be part of.

In the meantime though, I think adding the subject is beneficial regardless of the ability of the backend to spoof the identity. If a third party gets hold of the token, without compromising any backend, the sub claim adds an additional level of scoping to the token, along with the signature and the expiry.

**Comment by Rugvip** [comment]
@punkle there's not validation of the subject in the other end yet though, and I'm feeling it's a bit risky to start building out too much of this based on the assumption of any particular token format just yet.

Perhaps it's best you use a custom TokenManager implementation for now? One where you and a plugin-specific implementation too.

**Comment by punkle** [comment]
Sure, Ill implement on our side. Thanks @Rugvip 

What do you mean about the "other end"? I understood that the TokenManager both generated and authenticated the tokens? Is there another piece?

**Comment by Rugvip** [comment]
@punkle if the subject claim in a leaked token is going to have any security benefit in practice then that means that the backend plugins actually reject tokens that don't have the correct subject, whatever that means.

It's actually not clear to me in this PR which direction your where aiming for though tbh. For example, say the search backend is making a request to the catalog backend. Does the search backend request a token with a subject like `plugin:search`, which the catalog plugin is configured to accept? Or does the search backend request a token with subject `plugin:catalog`, which would be the only subject that the catalog accepts. The latter is ofc easier right now but really doesn't make much sense long-term.

**Comment by punkle** [comment]
Ah ok. I think, I expected that the ServerTokenManager would be created upfront and passed to the search backend with the subject already set to "production-stack" or "development-stack"; or whatever the backstage stacks are called.

Then all of the plugins in a single deployment stack would have the same subject.

**Comment by Rugvip** [comment]
@punkle ah, don't re-use the signing keys for different environments. That'll have the same effect. It's ofc a lot more tricky to identify the source of a given token, but that's something we ofc plan to tackle

**Comment by punkle** [comment]
Thanks @Rugvip

**Pull request closed without merging**
