### PR TITLE
Time saver plugin

### PR DESCRIPTION
**Pull request by tduniec**
## Hey, I just made a Pull Request!

Introducing timeSaver plugin. It does some analysis graphs and charts that helping your management and team how using scaffolder templates can bring value and savings to the onboarded Teams!!!

It is declarative so it requires to put some savings data for each template execution into the template definition.  [Checkout README](./time-saver-backend/README.md)

byTemplate
tsAllStats
tsAllStats2
tsByTeam
tsByTeam2

#### :heavy_check_mark: Checklist

- ➖  A changeset describing the change and affected packages. ([more info](git)) // **please let me know if this is needed on plugin init**
- ✔️  Added or updated documentation
- ✔️  Tests for new functionality and regression tests for bug fixes
- ✔️  Screenshots attached (for UI changes)
- ✔️ All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

Please let me know if any changes are needed and what else should be accomplished moving forward publishing this plugin.

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @tduniec, this looks pretty awesome! 

Just wanted to give you a heads up that there is currently a freeze on accepting new plugins while the Community repo is setup for them, more details here: https://github.com/backstage/backstage/issues/20266. You could host this on a public GitHub repo and publish it to NPM in the mean time? Then add it to the Plugin Directory by following the instructions here: https://backstage.io/docs/plugins/add-to-directory

**Review by awanlin — CHANGES_REQUESTED** [review]
Hi @tduniec, not sure if you saw my comment - https://github.com/backstage/backstage/pull/22582#issuecomment-1914662027 - worried you are putting in work that will be potentially lost.

**Comment by toma2395** [comment]
Hi @awanlin, 

yes I have seen your comment. 
So it means I should close the PR and keep it under my repo right ? 
How then we can run all the pipelines to validate the code ?

**Comment by awanlin** [comment]
Yes, for the time being it would be best to close the PR and create this in a public repo. You would then have your own CI/CD pipeline that would handle validation etc.

The work to create a Community is just starting so I don't have any ETA yet on that

**Pull request closed without merging**
