### PR TITLE
Scaffolder: Cleanup

### PR DESCRIPTION
**Pull request by OscarDHdz**
## Hey, I just made a Pull Request!

Just doing some cleanup as suggested/requested in the previously merged PR #4479 

### Changes
* Moved `useStarredEntities` to `plugin-catalog-react` and updated imports from `plugin-catalog` and `plugin-scaffolder`
* Mostly Code cleanup

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by OscarDHdz** [comment]
@freben PR with your PR feedback 😃

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4609-6pxbhidmtu4md6ibphp5egsdwqkewfr5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60302a8af285afdfd99398e0

**Comment by freben** [comment]
@OscarDHdz what happened? :)

**Comment by OscarDHdz** [comment]
oh! Might have hit Close by mistake. Let me Open it again 😮

**Comment by OscarDHdz** [comment]
@freben 😮 I'm not sure How I closed it  😆 I just re-opened it, sorry for the confusion 😆

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4609-6pxbhidmtu4md6ibphp5egsdwqkewfr5.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60302a8af285afdfd99398e0

**Review by freben — APPROVED** [review]

**Pull request merged**
