### PR TITLE
fix: add horizontal slider if stepper overflows

### LINKED ISSUE #21578: 🐛 Bug Report: Scaffolder steps view doesn't show all steps
### 📜 Description

The steps that are rendered after starting a job gets cut off if the template contains too many steps.

### 👍 Expected behavior

This view should support any number of steps.

### 👎 Actual Behavior with Screenshots

When you start a template the steps are horizontally next to each other, this view does not support overflow and if you run a template with a lot of steps after they reach the end of the box they will end up being clipped. 

See screenshot. In this example I added 32 steps into my template but this box only shows 23.

image

### 👟 Reproduction steps

Register a template with a lot of steps and run this template.

Example template
```apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: now-times-32-filter-1
  description: test the now filter
spec:
  type: service
  owner: user:guest
  steps:
    - id: debug-filter
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-1
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-2
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-3
      name: debug-filter
      action: debug:log
      input:
        message: Some log line 
    - id: debug-filter
      name: debug-filter-4
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter
      name: debug-filter-5
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-6
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-7
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-8
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-9
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-10
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-11
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-12
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-13
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-14
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-15
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-16
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-17
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-18
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-19
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-20
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-21
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-22
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-23
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-24
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-25
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-26
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-27
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-28
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-29
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-30
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-31
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
    - id: debug-filter-32
      name: debug-filter
      action: debug:log
      input:
        message: Some log line
```

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by fedy97**
## Hey, I just made a Pull Request!

- Add horizontal slider if stepper overflows

Screenshot 2023-11-27 at 16 17 31

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### Related Issue

Closes #21578

### CODE REVIEW

**Review by tudi2d — COMMENTED** [review]
Thanks for raising this issue! This is unfortunate - at the same time I really hope this doesn't happen for too many people as it would require many steps..

I'm leaving this to Ben if you wan to merge it in. Could not find any helpfull resources in [Material Design](https://m1.material.io/components/steppers.html) nor Material UI for this use case. I guess it is not expected to happen. As an alternative to merging this in you could also just override it on your theme by adding the style to `MuiStepper` `root`.

**Comment by fedy97** [comment]
> Thanks for raising this issue! This is unfortunate - at the same time I really hope this doesn't happen for too many people as it would require many steps..
> 
> I'm leaving this to Ben if you wan to merge it in. Could not find any helpfull resources in [Material Design](https://m1.material.io/components/steppers.html) nor Material UI for this use case. I guess it is not expected to happen. As an alternative to merging this in you could also just override it on your theme by adding the style to `MuiStepper` `root`.

yes, I think it is cleaner to do that way

**Comment by benjdlambert** [comment]
@fedy97 apologies, But I think what @tudi2d was mentioning is to apply the current fix to only your instance of Backstage and not contribute it that way. 

I'd like to suggest that we rollback to the CSS inline changes instead for the purposes of this PR, as we don't know what other knock on effects that this change could do to other instances of backstage using the MUI stepper at all.

**Comment by fedy97** [comment]
> @fedy97 apologies, But I think what @tudi2d was mentioning is to apply the current fix to only your instance of Backstage and not contribute it that way.
> 
> I'd like to suggest that we rollback to the CSS inline changes instead for the purposes of this PR, as we don't know what other knock on effects that this change could do to other instances of backstage using the MUI stepper at all.

ops @benjdlambert , reverted the commit

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice - let's get this in :tada:

**Pull request merged**
