### PR TITLE
fix the opentelemetry setup

### PR DESCRIPTION
**Pull request by freben**
Had to try this out as part of reviewing #22648.

See the changeset - this adds a `--require` flag to the `package start` CLI command. This is basically passed directly through to node at startup. This enables having otel enabled in local dev just like in production.

### CODE REVIEW

**Review by vinzscam — APPROVED** [review]

**Review by Rugvip — CHANGES_REQUESTED** [review]
This is still in a tricky state right? i.e. transpilation not working properly

**Comment by freben** [comment]
I think so. Are you thinking that at least `--import` should be shipped for now as we can't promise that it works?

**Comment by freben** [comment]
Alright, removed `--import` entirely.

**Review by Rugvip — APPROVED** [review]
Let's :shipit: :+1:

**Pull request merged**
