### PR TITLE
Adding a new plugin entry to the microsite for "Backchat"

### PR DESCRIPTION
**Pull request by benwilcock**
## Hey, I just made a Pull Request!

I added an entry to `/microsite/data/plugins` for the plugin "Backchat" which I introduced at BackstageCon 2023 in Chicago.  There are two files. `backchat.yaml` contains the plugin metadata required for a listing in the microsite. `backchat-logo.png` is the icon to use with the listing in the microsite. Sorry it took so long to add it! This plugin allows for the use of miltiple open source genrative AU GUIs within Backstage - so that developers don't have to leave the portal quite so often. For more information, see: [https://github.com/benwilcock/backstage-plugin-backchat](https://github.com/benwilcock/backstage-plugin-backchat)

#### :heavy_check_mark: Checklist

I'm almost sure most of these checks are not applicable for a plugin page entry on the microsite, but please let me know if I missed something. Thanks!

- [x ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x ] Added or updated documentation
- [x ] Tests for new functionality and regression tests for bug fixes
- [ x] Screenshots attached (for UI changes)
- [x ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — CHANGES_REQUESTED** [review]
Nice @benwilcock! 👏 Just some DCO is missing on your commits once fixed we are ready to go 🚀

**Review by vinzscam — CHANGES_REQUESTED** [review]
Nice @benwilcock! 👏 Just some DCO is missing on your commits once fixed we are ready to go 🚀

**Comment by benwilcock** [comment]
Sorry for the slow reply. I used the "append" method to add the sign-off to my commit. I hope this is acceptable for you! Thanks. Ben.

**Comment by benjdlambert** [comment]
@benwilcock I think you'll need to rebase the PR. You can `git rebase HEAD~5 --signoff` and then force push back should fix it :)

**Comment by benwilcock** [comment]
It got very complicated. I'll make a fresh fork and recommit.

**Pull request closed without merging**
