### PR TITLE
Support Apple silicon (Mac M1)

### PR DESCRIPTION
**Pull request by dtuite**
With three changes in place I can perform the following Backstage actions:

```shell
yarn install
yarn tsc
yarn build
yarn dev
```

Some notes

1. The minimum NodeJS version required is `15.9.0`. I would get out-of-memory errors with anything less.
2. Esbuild needs to be built with Go 1.16 in order to support apple silicon. Thus the minimum esbuild version required is 0.8.47.
3. The canvas package needs [some dependencies installed with homebrew](https://github.com/Automattic/node-canvas/issues/789#issuecomment-229038369). It also needs the `CPLUS_INCLUDE_PATH` to be set to the new homebrew location ie. `CPLUS_INCLUDE_PATH=/opt/homebrew/include yarn install --ignore-engines`. Here's [the issue for that](https://github.com/Automattic/node-canvas/issues/1733#issuecomment-762659473).

With the above changes in place I can successfully run Backstage on an M1 MacBook Air. TechDocs works with the latest Docker Preview. Scaffolder also works.

Let me know what you'd like me to do with this PR please. I can test more potential failure modes if required.

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4851-yayrja1w9hqut7kvyxc1vztxfp7bqnpe.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604371f9f285af1989a25289

**Comment by dtuite** [comment]
Could this build failure be unrelated?

```
Summary of all failing tests
FAIL reading/integration.test.ts (5.222 s)
  ● UrlReaders › should read data from azure

    https://dev.azure.com/backstage-verification/test-templates/_git/test-templates?path=%2Ftemplate.yaml could not be read as https://dev.azure.com/backstage-verification/test-templates/_apis/git/repositories/test-templates/items?path=/template.yaml, 401 Unauthorized

      76 |       throw new NotFounderror Command failed with exit code 1.
lerna ERR! yarn run test --coverage exited 1 in '@backstage/backend-common'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by dtuite** [comment]
The latest version of the `@azure/msal-node` package, version `1.0.1`, has specified `"engines": "10 || 12 || 14"`. This library is a dependency of the `catalog-backend` plugin.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/package.json#L75

It looks like this is blocking the tests from passing locally. 

They fail with this error:

```
PASS src/database/connection.test.ts
  ● Console

    console.log
      Knex: run
      $ npm install mysql --save
      Cannot find module 'mysql' from '../../../node_modules/knex/lib/dialects/mysql/index.js'
      Error: Cannot find module 'mysql' from '../../../node_modules/knex/lib/dialects/mysql/index.js'
          at Resolver.resolveModule (/Users/davidtuite/dev/roadiehq/backstage/node_modules/jest-resolve/build/index.js:306:11)
          at Resolver._getVirtualMockPath (/Users/davidtuite/dev/roadiehq/backstage/node_modules/jest-resolve/build/index.js:445:14)
          at Resolver._getAbsolutePath (/Users/davidtuite/dev/roadiehq/backstage/node_modules/jest-resolve/build/index.js:431:14)
          at Resolver.getModuleID (/Users/davidtuite/dev/roadiehq/backstage/node_modules/jest-resolve/build/index.js:404:31)
          at Runtime._shouldMock (/Users/davidtuite/dev/roadiehq/backstage/node_modules/jest-runtime/build/index.js:1521:37)
          at Runtime.requireModuleOrMock (/Users/davidtuite/dev/roadiehq/backstage/node_modules/jest-runtime/build/index.js:916:16)
          at Client_MySQL._driver (/Users/davidtuite/dev/roadiehq/backstage/node_modules/knex/lib/dialects/mysql/index.js:31:12)
          at Client_MySQL.initializeDriver (/Users/davidtuite/dev/roadiehq/backstage/node_modules/knex/lib/client.js:231:26)
          at Client_MySQL.Client (/Users/davidtuite/dev/roadiehq/backstage/node_modules/knex/lib/client.js:69:10)
          at new Client_MySQL (/Users/davidtuite/dev/roadiehq/backstage/node_modules/knex/lib/dialects/mysql/index.js:20:10)

      at Logger._log (../../../node_modules/knex/lib/logger.js:42:13)
```

When I try to manually run `npm install mysql --save` I see:

```
» npm install mysql --save                                                                                                                                                                                                                                                                                                                                                      130 ↵
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @azure/msal-node@1.0.1
npm ERR! notsup Not compatible with your version of node/npm: @azure/msal-node@1.0.1
npm ERR! notsup Required: {"node":"10 || 12 || 14"}
npm ERR! notsup Actual:   {"npm":"7.6.0","node":"v15.11.0"}
```

If I manually modify `node_modules/@azure/msal-node/package.json` and add `|| 15` to the engines then I can successfully install mysql locally but the tests still fail with the same error.

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4851-yayrja1w9hqut7kvyxc1vztxfp7bqnpe.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604371f9f285af1989a25289

**Comment by freben** [comment]
Hm. We were intending to support the LTS version of node, i.e. 14. Haven't looked into it yet, but I presume there's a way - or there will be a way soon - for 14 to get up and running on Apple silicon too.

**Comment by freben** [comment]
Hmm https://github.com/nodejs/node/issues/37309

**Comment by freben** [comment]
Is it possible to run your terminal with Rosetta enabled? Maybe you'll need to clear your yarn cache and wipe node_modules and go again.

**Comment by dtuite** [comment]
@freben Yeah I have tried that and there be dragons down that path also. 😄  I'll give it another go and comment my findings down below. I didn't spend too much time with it since it feels like going backwards with respect to my own local setup.

Even if this PR never gets merged it will be good info to have for anyone trying to get this running themselves.

**Comment by freben** [comment]
Appreciate you digging into it!

**Review by Rugvip — COMMENTED** [review]
Let's merge the version bumps of the dependencies! I think those make sense either way.

Then we can handle the debate over whether we need the `engine` version spec in a separate PR :>

**Comment by freben** [comment]
Oh I saw now that the yarn.lock diff was 9000+ lines, probably need to go on a clean master?

**Comment by dtuite** [comment]
@freben I wouldn't attempt to merge this I'm still hacking around to get a sense of the changes required to make it work. 

I'll split the esbuild and @azure/msal-node version bumps into a separate PR.

**Comment by Rugvip** [comment]
@dtuite ended up hijacking the `esbuild` bump in #4853 for TypeScript 4.1 reasons.

Btw, don't forget that version bumps in deps need changesets!

**Comment by freben** [comment]
Hey, the esbuild pr is merged, what's next here? I see the yarn.lock changes are massive still.

**Comment by dtuite** [comment]
@freben I don't have much time to work on this. Is it ok to have a long running PR or would you prefer I close it until there's an end in sight?

**Comment by freben** [comment]
No worries, just checking in. Let's keep it open and searchable, we can refer to it if we get questions

**Comment by dtuite** [comment]
Cool. I only get a few hours a week to hack on some code so it'll be slow but not forgotten.

**Comment by adamdmharvey** [comment]
LTS 16 officially went live last week.  Wonder if, in lieu of a PR to support Apple Silicon specifically, we get a PR to officially start trying the support for LTS 16 which covers both bases?  (As M1 was officially supported in 16 now: https://github.com/nodejs/node/issues/37309)

Can open an issue and maybe we use it to track, e.g. some non impacting CI stuff to spin out 16 testing in parallel? then other changes as necessary? What do you guys think?

**Comment by dtuite** [comment]
@adamdmharvey 16 is out, but afaik it doesn't become LTS until October.

**Comment by adamdmharvey** [comment]
@dtuite Ah, thanks for the clarification.  Yes, 16 LTS is "active" but not "current" - does Backstage intend to defer only to "current"?

image

**Comment by leemills83** [comment]
Been able to install and build backstage from clean on an M1 mac with node v14.17.1 without rosetta. Catalog and scaffolder all seem to be working and I'm able to create components and create a new plugin. Closing this PR for now, please feel free to test and re-open if required.

**Comment by eoghanmcilwaine** [comment]
Just to help with searchability: I came across this issue when it prevented backstage tests from running due to problems with the node-canvas package.

The fix was as described above. Basically:
1. Install the suggested dependencies: https://github.com/Automattic/node-canvas#compiling
2. Re-run `yarn install`

This is what the test failures looked like:
```
FAIL @backstage/package-name path/to/src/of/Component.test.tsx
- Test suite failed to run

  Cannot find module '..build/Release/canvas.node'
  Require stack:
  - /path/to/backstage/node_modules/canvas/lib/bindings.js
  - /path/to/backstage/node_modules/canvas/lib/canvas.js
  - /path/to/backstage/node_modules/canvas/index.js
  - /path/to/backstage/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/utils.js
  - ...
  - ...
  - ...etc
```

**Comment by jrusso1020** [comment]
```
In file included from /Users/XXX/src/backstage-app/node_modules/cpu-features/deps/cpu_features/src/cpuinfo_arm.c:15:
/Users/XXX/src/backstage-app/node_modules/cpu-features/deps/cpu_features/include/cpuinfo_arm.h:118:2: error: \"Including cpuinfo_arm.h from a non-arm target.\"
#error \"Including cpuinfo_arm.h from a non-arm target.\"
 ^
1 error generated.
make[3]: *** [CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o] Error 1
make[2]: *** [CMakeFiles/cpu_features.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [/Users/jrusso/src/backstage-app/node_modules/cpu-features/deps/cpu_features/build/libcpu_features.a] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jrusso/src/backstage-app/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.3.0
gyp ERR! command \"/Users/jrusso/.asdf/installs/nodejs/16.12.0/bin/node\" \"/Users/jrusso/src/backstage-app/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/jrusso/src/backstage-app/node_modules/cpu-features
gyp ERR! node -v v16.12.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

I get the above error output when running yarn install on an m1 machine, but non blocking as stated the module is optional. Just thought I'd service for visibility and if anyone has a fix let me know

**Pull request closed without merging**
