### PR TITLE
Export permission criteria utilities

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

Just exporting a few utility functions useful for plugin authors for creating permission filters.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by mtlewis — APPROVED** [review]
Nice!

**Review by joeporpeglia — APPROVED** [review]

**Comment by Joonpark13** [comment]
Sorry if I missed the context - can we include the use case in the PR too? Or is that coming up?

**Comment by vinzscam** [comment]
> Sorry if I missed the context - can we include the use case in the PR too? Or is that coming up?

the use case is going to be included in the permission docs for plugin authors :)

**Review by Rugvip — APPROVED** [review]
:shipit:

**Pull request merged**
