### PR TITLE
catalog: use LoggerService instead of winston Logger in ldap module

### PR DESCRIPTION
**Pull request by Roshick**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
Note that you'll need to run `yarn build:api-reports` and commit the results of that too.

Hm this is breaking, isn't it. Then you'll have to bump the changeset to `minor`. Or alternatively, change the code to accept EITHER a logger service or a winston logger, and it somehow converting it internally if needed.

**Comment by Roshick** [comment]
@freben as far as I can see this should not be breaking as the new LoggerService is a subset of the old Logger, so for the consumer it shouldn't matter which one they insert as a dependency.

**Comment by freben** [comment]
Try it in a test. Not sure they're type compatible even if the names are the same. Try to pass in `(null as unknown) as WinstonLogger)` and see if your editor or typescript complains. I'm not at the computer to check atm

**Comment by Roshick** [comment]
I'll try it on monday when I'm on my company computer via local linking in our backstage instance.

**Review by Rugvip — APPROVED** [review]
Thank you! 🎉 

This is indeed not breaking since `LoggerService` is a subset of the winston `Logger` 👍

**Pull request merged**
