### PR TITLE
vacation over :-/ 

### PR DESCRIPTION
**Pull request by brucearctor**
## Hey, I just made a Pull Request!

Removed the note about Summer Vacations, since is past 8 August.  

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by brucearctor** [comment]
:-/ Vacation over :-/ 

🏖️

**Comment by kuangp** [comment]
image

**Review by Rugvip — APPROVED** [review]
Indeed, thanks 😁

**Comment by brucearctor** [comment]
Actually, LOL!

**Pull request merged**
