### PR TITLE
🧹  Align on usage of `cross-fetch` vs `node-fetch` in frontend vs backend packages

### PR DESCRIPTION
**Pull request by freben**
We actually would like to bump node-fetch to version 3.x, but since it's ESM it'll have to be deferred a little bit longer.

### CODE REVIEW

**Comment by benjdlambert** [comment]
Maybe let's create an ADR for this too.

**Comment by freben** [comment]
@benjdlambert Agreed. I'll write one tomorrow to follow up.

**Comment by jhaals** [comment]
lint it!

**Comment by freben** [comment]
Pending ESM compat in backstage-cli, we'll have one or two usages still in there perhaps ... but soon we can lint!

**Review by camilaibs — APPROVED** [review]

**Review by jhaals — APPROVED** [review]

**Comment by jhaals** [comment]
no linting?

**Pull request merged**
