### PR TITLE
Fix broken link for kubernetes documentation

### PR DESCRIPTION
**Pull request by gowthamshankar99**
The current k8s documentation is broken. updating it to point to the correct URL

## Hey, I just made a Pull Request!

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
I think that it might be best to add a redirect to this list here: https://github.com/backstage/backstage/blob/24e91ed76dbac2f19f2d704dd94a2f5c984c41c4/microsite/docusaurus.config.js#L127 so that anyone with bookmarks will get redirected to the right place. This link exists in a few places unfortunately, so thinking that it might be best to do both?

**Comment by gowthamshankar99** [comment]
> I think that it might be best to add a redirect to this list here:
> 
> https://github.com/backstage/backstage/blob/24e91ed76dbac2f19f2d704dd94a2f5c984c41c4/microsite/docusaurus.config.js#L127
> 
> so that anyone with bookmarks will get redirected to the right place. This link exists in a few places unfortunately, so thinking that it might be best to do both?

that makes sense - working on it.

**Comment by gowthamshankar99** [comment]
@benjdlambert  - all set

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Thanks! :tada:

**Pull request merged**
