### PR TITLE
fix(create-app): sync scaffolded backend with example

### LINKED ISSUE #2608: [bug] starting the backend fails after creating a new App
I'm on https://backstage.io/docs/getting-started/create-an-app trying to create a new App. The frontend starts, but not the backend:

```
**yarn workspace backend start**

yarn workspace v1.21.1
yarn run v1.21.1
$ backstage-cli backend:dev
Build succeeded
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
2020-09-25T12:16:44.834Z catalog info Beginning locations refresh
Backend failed to start up, Error: Missing required config value at 'scaffolder.github.token'
```

### PR DESCRIPTION
**Pull request by shmidt-i**
Fixes #2608 
Syncing the template for the backend package with the one we have as example-backend in regards of instantiation of the scaffolder-backend plugin

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Alright, but should refactor this asap imo. Really awkward to have this much logic in the backend itself. Better have the plugin provide a utility to load things from config instead.

**Comment by benjdlambert** [comment]
@Rugvip it's linked to this https://github.com/spotify/backstage/issues/1503

**Comment by benjdlambert** [comment]
@Rugvip what do you think that API looks like? It's a lot of config, but moving this logic somewhere else doesn't seem the best choice either for something that's flexible like the scaffolder?

**Comment by benjdlambert** [comment]
Maybe it doesn't need both github and gitlab? Maybe it doesn't need anything. Just some info on how to configure them?

**Comment by shmidt-i** [comment]
Will merge it as is and then let's come up with a longer term strategy ;)

**Pull request merged**
