### PR TITLE
[Search] Clarify search architecture

### LINKED ISSUE #4436: [Search] Improve Architecture according to feedback
* Text to the architecture documentation around relationships. 
* No 1-to-1 relationship to entities but set conventions on attributes/fields.
* Add text to indicate no event-driven index updates for now.
* Split out search backend and search indexer into separate plugins.
* Clarify direction of communication between search-backend and other plugin backends.

### PR DESCRIPTION
**Pull request by iamEAP**
## Hey, I just made a Pull Request!

Making a few clarifications to the Search architecture, based on feedback and discussion collected in #4078

Closes #4436 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4472-dwr1qroa9m7xdliyvhndbt9nfzhrzqri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6023e2cb14dc5851a7c82090

**Review by OrkoHunter — APPROVED** [review]
Cool!

**Review by emmaindal — APPROVED** [review]
Nice!

**Comment by emmaindal** [comment]
could probably add us as codeowners to docs/assets/search/* as well if we're not already

**Review by realandersn — APPROVED** [review]

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4472-dwr1qroa9m7xdliyvhndbt9nfzhrzqri.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6023e2cb14dc5851a7c82090

**Review by soapraj — APPROVED** [review]

**Comment by adamdmharvey** [comment]
❤️ this commit msg 😄 

image

**Review by Rugvip — APPROVED** [review]
:shipit:

**Pull request merged**
