### PR TITLE
Don't allow users to delete an entity in RO mode

### PR DESCRIPTION
**Pull request by asselin**
When the catalog is in read-only mode, don't allow a user to delete an entity.

### CODE REVIEW

**Comment by adamdmharvey** [comment]
Welcome to the project @asselin !! Thanks for the contrib.

I see you signed your commits for DCO, which is great. One more thing you'll need is to add a changeset to this PR which indicates what the change is and the semver level - major, minor, or patch - that you've supplied.

More info is here:

https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets

Do you mind taking at stab at that?  And with that, the core project reviewers would then give it a review.   Thanks!

**Comment by benjdlambert** [comment]
@asselin we need to have a little bit of a chat about this internally to work out what we really want to do with the read only mode and orphans. We will get together early next week to chat about it if that's ok!

**Comment by asselin** [comment]
@benjdlambert Sure, no problem.  My reasoning here is that if we're going to deploy this in read-only mode, I expect github to be the source of truth, and want to disable people from making any manual changes through the UI.  Right now, a user is allowed to remove a component through the UI, and Backstage will not re-add it if it exists in github.  IMO, if a component should be removed, it should be removed in github, and Backstage should detect the 404.

**Comment by Rugvip** [comment]
Just to clarify, the tricky bit is that right now entities will become orphaned if they are deleted from the source, e.g. GitHub, and then you have to manually delete them. So if we disallowed deletions right now there would be no way to remove entities from the catalog

**Review by Rugvip — COMMENTED** [review]
Discussed this a bit more and we arrived at wanting to simply disallow deletion of non-orphaned entities instead. Even if the catalog is running in read-only mode it's important to be able to delete entities.

Is that something you want to take a stab at @asselin? It would likely be implemented over [here](https://github.com/backstage/backstage/blob/1acea028440d586f15028e032e3fda8d3a1654a8/plugins/catalog-backend/src/service/NextEntitiesCatalog.ts#L206), by reading out and parsing the existing entity and only allowing it to be deleted if there's an orphan annotation.

If not we can move it to an issue instead

**Comment by asselin** [comment]
@Rugvip Thank you for having the conversation.  Sorry, but I'm not able to invest the time at this point-- I submitted this PR because it looked like it'd be low effort to correct this issue.

IMO, short term, for people who want to run in RO mode (such as my org), it'd be better to prevent deletions with the known issue that the DB can get orphans.  Practically speaking, it's not going to be a big deal-- the number of artifacts that are removed after being published IMO is likely a small number.  And in RO mode, there's always the option to drop the DB and have it rediscover everything.

If you guys agree, I'll put in the work to finish out this PR to disallow deletions in RO mode.  In either case, I think opening an issue for the orphan check is the right thing to do.

**Comment by Rugvip** [comment]
@asselin no worries! Will create an issue to track the work.

Regarding shipping this as is I think we'd rather avoid that. One workaround for now is to register a `/entities/by-uid/:ui` route on your catalog router to block the request, something like this:

```ts
const { processingEngine, router } = await builder.build();
await processingEngine.start();

const outerRouter = Router()

outerRouter.delete('/entities/by-uid/:ui', () => {
  throw new NotAllowedError('Entity deletion is not allowed');
})
outerRouter.use(router)

return outerRouter
```

(not tested)

**Pull request closed without merging**
