### PR TITLE
[Search] Export to CSV results inside search page

### PR DESCRIPTION
**Pull request by GaboFrontDev**
## Hey, I just made a Pull Request!

It's a simple button that helps us to export all the search results to a CSV file
This PR refers to https://github.com/backstage/backstage/issues/5499

New export button 
image

Results exported
image

It works for all the actual data inside the table element

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by emmaindal** [comment]
Hi @GaboFrontDev, thanks for the contribution. We are currently in the process of refactoring the search components see #4445 which means that the search result component most likely will not be a `Table` in the future. This can of course be added anyways, but I wonder if we could break it out to its own component that can be added to other components out of the box, instead of being tightly coupled to this specific search result component. That would give us the option to use it for our new Search Result component which in turn also will support the option of compose how the search result view would look for different search pages (and therefore also we could make it an option to decide to use the `SearchResultExport` component or not. Does that makes sense?

**Comment by GaboFrontDev** [comment]
Hi @emmaindal Now, I converted my solution to a generic component that exports any kind of information with customizable headers!
Let me know what do you think about those changes 👍🏼

**Review by freben — APPROVED** [review]

**Comment by andrewthauer** [comment]
Is custom code needed for this? I noticed the other day the table components options has some built in export options which will export the current filtered dataset to CSV or PDF. Unless this is something different that I'm missing.

**Comment by emmaindal** [comment]
great catch @andrewthauer seems like we are using https://material-table.com under the hood, which let's us use their https://material-table.com/#/docs/features/export feature as well! Let's go with that for now @GaboFrontDev if it sounds like it solves the initial use case you had in mind!

**Comment by GaboFrontDev** [comment]
> Is custom code needed for this? I noticed the other day the Table components options has some built in export options which will export the current filtered dataset to CSV or PDF. Unless this is something different that I'm missing.
> 
> ```tsx
> <Table
>   options={{ exportButton: true, exportAllData: true, exportFileName: 'search-results' }}
>   ...
> />
> ```

oh sorry, you are talking about ```Datagrid```component right? Because the ```Table```component doesn't include any reference to that on the docs https://material-ui.com/components/tables/
Here you can see what you are talking about: https://material-ui.com/es/components/data-grid/export/

But changing it to Datagrid may cause some miss compatibilities :/

**Comment by andrewthauer** [comment]
@GaboFrontDev - The export feature is also supported on the `Table` component (not just the datagrid). I literally used it on the backstage core table component a couple of days ago.

**Comment by emmaindal** [comment]
The `Table` component used is not the one from Material UI, instead its the custom one from the [backstage/core package](https://github.com/backstage/backstage/blob/master/packages/core/src/components/Table/Table.tsx) which uses [Material Table](https://material-table.com) so it has a bit more than the [Material UI Table](https://material-ui.com/components/tables/)

**Comment by GaboFrontDev** [comment]
> @GaboFrontDev The `Table` component used is not the plain one from Material UI, instead its the custom one from the [backstage/core package](https://github.com/backstage/backstage/blob/master/packages/core/src/components/Table/Table.tsx) which seems to use [Material Table](https://material-table.com) so it has a bit more than the [Material UI Table](https://material-ui.com/components/tables/)
> 
> Edit: It also seems to use the Material UI Table under the hood but just with some additional features. Found this - "material-table is a simple and powerful Datatable for React based on Material-UI Table with some additional features." ([ref](https://material-table.com/#/docs/get-started))

Totally understandable! But now this component works as a standalone. It doesn't require any table component to be rendered nor used. You can simply add the object and the headers you want in your CSV file for download

**Comment by emmaindal** [comment]
> > @GaboFrontDev The `Table` component used is not the plain one from Material UI, instead its the custom one from the [backstage/core package](https://github.com/backstage/backstage/blob/master/packages/core/src/components/Table/Table.tsx) which seems to use [Material Table](https://material-table.com) so it has a bit more than the [Material UI Table](https://material-ui.com/components/tables/)
> > Edit: It also seems to use the Material UI Table under the hood but just with some additional features. Found this - "material-table is a simple and powerful Datatable for React based on Material-UI Table with some additional features." ([ref](https://material-table.com/#/docs/get-started))
> 
> Totally understandable! But now this component works as a standalone. It doesn't require any table component to be rendered nor used. You can simply add the object and the headers you want in your CSV file for download

Yes I think the standalone component can be useful in our next iteration of the search result component (which we currently working on) as it will not be a Table but instead a List, so lets keep the standalone SearchExport component but switch to use the export option that we have access to out of the box from the Table component for now! Does makes sense?

**Comment by regicsolutions** [comment]
@GaboFrontDev given this PR is a year old figured I would check in to see if there is an alternative/out of the box method to be able to export catalog data to csv?

**Pull request closed without merging**
