### PR TITLE
implements edit link for workflow template

### PR DESCRIPTION
**Pull request by kosukeKK**
## Hey, I just made a Pull Request!

I have implemented the edit link on the template page.

I did this to resolve this issue.
https://github.com/backstage/backstage/issues/17986

before
スクリーンショット 2023-12-30 22 00 56
after
スクリーンショット 2023-12-30 21 53 32

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by benjdlambert** [comment]
Think that we should move this to the header, similar to how we display additional information a links in entity pages:

Screenshot 2024-01-02 at 13 31 08

Do you think that it would be possible?

**Comment by kosukeKK** [comment]
I understand your point, but I based my implementation on the 'about' section of the entity.

Placing it in the header options also seems like a good idea.

> Do you think that it would be possible?

Currently, implementations that utilize the Header component, as seen [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/next/TemplateWizardPage/TemplateWizardPage.tsx#L91-L96), are unable to call the edit URL. However, the Workflow component, shown [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-react/src/next/components/Workflow/Workflow.tsx#L83-L85), does have a response from the API.

Given this, I suggest moving the API call implementation, which is currently part of the Workflow component ([source](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-react/src/next/components/Workflow/Workflow.tsx#L83-L85)), to the TemplateWizardPage component ([source](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/next/TemplateWizardPage/TemplateWizardPage.tsx))

**Comment by benjdlambert** [comment]
@kosukeKK - give it a go and see what feels best.

If we can avoid breaking the API contract for public components that would be best.

You can also use that hook in multiple places too, so don't feel like that's not an option. It's designed to be re-usable.

**Comment by kosukeKK** [comment]
@benjdlambert
Sorry, I am too late to response to your question so this PR was closed.
I create new PR. can you review PR https://github.com/backstage/backstage/pull/23363

**Pull request closed without merging**
