### PR TITLE
Custom error page 404

### PR DESCRIPTION
**Pull request by akmarif**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by akmarif** [comment]
https://github.com/backstage/backstage/issues/22738

**Comment by akmarif** [comment]
Hello @freben and @tudi2d, could you please review the changes? :)

**Comment by akmarif** [comment]
Hello @freben and @tudi2d, please let me know if any changes is required :)

**Comment by akmarif** [comment]
> #22738

Hello @tudi2d, I appreciate your feedback regarding this pull request. I've experimented with the option component of createApp, but it seems to only address issues related to incorrect routing and missing components. We aim to display our customized 404/500 error page rather than the default mic drop versions when encountering missing or unavailable techdocs (specifically at https:///docs/default/component/<component_name> and https:///catalog/default/component/<component_name>/docs) as well. This customization is similar to the creation of an app using components#NotFoundErrorPage: DefaultNotFoundPage.

**Comment by akmarif** [comment]
Hello, my understanding is that backstage won't utilize the NotFoundError page from appCreate for techdocs, and instead, the MicDrop error page will be consistently used. Does the information provided in https://github.com/backstage/backstage/issues/22738 sufficiently articulate our requirements? I will close the PR if it does not meets the requirements.

**Comment by dasari008** [comment]
@akmarif I want to achieve the same usecase where we would like to customize the default error page show when techdocs is not found. Your PR seems good to me, i have read the conversation above and i did not quite understand why you closed this PR. Is there someother better solution? If not can we reopen this PR and discuss more?

Moreover, what @tudi2d mentioned cannot be achieved as the TechdocsNotFound component [here](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsNotFound.tsx#L51) is using the ErrorPage which cannot be overrided by passing a custom component to createApp.

**Comment by akmarif** [comment]
Hi @dasari008,
My PR doesn't alter any default behavior unless a user registers their own custom component. Also, you're correct—solution provided by @tudi2d does not fulfill our requirements since the ErrorPage component is hard-coded in techdocs. I have created a new bug issue based on @awanlin's suggestion.

https://github.com/backstage/backstage/issues/23704 is also ok to me as long as I can get rid of the mic drop image.

**Comment by farn-dawg** [comment]
I would like the ability to create a custom 404 for my organization.  I think it's a very common use case.

**Pull request closed without merging**
