### PR TITLE
Added Digital.ai Release plugin to the microsite

### PR DESCRIPTION
**Pull request by nelson-digi**
## Hey, I just made a Pull Request!

This PR updates the Plugin microsite to list the new dai-release Backstage plugin.

An itemized list of changes
Added digital.ai-release.yaml to /microsite/data/plugins/ and added a corresponding icon to /microsite/static/img
Screenshots were taken by building and running the microsite locally.

image

#### :heavy_check_mark: Checklist

- [x] Added documentation for Digital-ai Release plugin ([more info](https://docs.digital.ai/bundle/devops-release-version-v.24.1/page/release/concept/release-backstage-overview.html))
- [x] Tests for new functionality
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — CHANGES_REQUESTED** [review]
Thank you! Is it possible to know where the source code of the plugin is? Ideally it would be great if you can specify the repository to the `package.json` of the plugins

**Comment by nelson-digi** [comment]
> Thank you! Is it possible to know where the source code of the plugin is? Ideally it would be great if you can specify the repository in the `package.json` of the plugins

@vinzscam Thanks for your feedback. I have updated the package.json and published the packages.

**Comment by vinzscam** [comment]
> > Thank you! Is it possible to know where the source code of the plugin is? Ideally it would be great if you can specify the repository in the `package.json` of the plugins
> 
> @vinzscam Thanks for your feedback. I have updated the package.json and published the packages.

thank you! Is the repository private or perhaps the link to the repository is not correct? 🤔 https://github.com/digital-ai/backstage-release

**Review by Rugvip — CHANGES_REQUESTED** [review]
Sorry we only accept open source plugins to this listing, as mentioned up top at https://backstage.io/plugins

**Comment by vinzscam** [comment]
> Sorry we only accept open source plugins to this listing, as mentioned up top at https://backstage.io/plugins

Also your library is released on npm and is licensed under Apache 2.0 license, so the source code of the library should be made available to anyone who uses it. I don't think you can close the source code of an Apache-licensed library.
Let us now if you can fix this, otherwise we are forced to rollback https://github.com/backstage/backstage/pull/24642 as well.

**Comment by nelson-digi** [comment]
> > Sorry we only accept open source plugins to this listing, as mentioned up top at https://backstage.io/plugins
> 
> Also your library is released on npm and is licensed under Apache 2.0 license, so the source code of the library should be made available to anyone who uses it. I don't think you can close the source code of an Apache-licensed library. Let us now if you can fix this, otherwise we are forced to rollback #24642 as well.

Thanks. We will work on the fix.

**Comment by nelson-digi** [comment]
> > > Sorry we only accept open source plugins to this listing, as mentioned up top at https://backstage.io/plugins
> > 
> > 
> > Also your library is released on npm and is licensed under Apache 2.0 license, so the source code of the library should be made available to anyone who uses it. I don't think you can close the source code of an Apache-licensed library. Let us now if you can fix this, otherwise we are forced to rollback #24642 as well.
> 
> Thanks for your feedback. We will work on the license fix.

@vinzscam @Rugvip Fixed the issues. This repositories are currently public.

**Comment by nelson-digi** [comment]
Hi @vinzscam @Rugvip @freben Fixed the review comments and now our plugins are open source. Could you please review and let us know if there is anything we have to do from our end.

**Comment by nelson-digi** [comment]
Hi @vinzscam @Rugvip @freben @camilaibs Could you please approve if its all good. Let us know if there is anything we have to do from our end.

**Review by vinzscam — CHANGES_REQUESTED** [review]

**Comment by nelson-digi** [comment]
@vinzscam Fixed the review comment. Thanks for your feedback. Kindly approve our request.

**Review by vinzscam — APPROVED** [review]

**Review by freben — APPROVED** [review]

**Pull request merged**
