### PR TITLE
Make kind configurable in linguist backend plugin

### LINKED ISSUE #16379: 🚀 Feature: Allow for entity kind selection when using the Linguist plugin
### 🔖 Feature description

At the moment, the Linguist plugin [retrieves entities](https://github.com/backstage/backstage/blob/e86c47d3b5087bafd87fcbc52692fe3a4a19f519/plugins/linguist-backend/src/api/LinguistBackendApi.ts#L93-L99) of kinds `API`, `Component`, and `Template` for language processing. 

Adding the ability to specify the kinds for which the Linguist plugin processes would be a great feature.

### 🎤 Context

We are mainly interested in having the Linguist plugin process `Component` entities. Additionally, we might be interested in rolling up the Linguist plugin information to the `System` kind level.

### ✌️ Possible Implementation

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ThomasAwesome**
## Hey, I just made a Pull Request!
resolves #16379 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by ahhhndre — APPROVED** [review]
Thanks for this contribution @ThomasAwesome, LGTM

Bonus: if you could include an example in the changeset that would be, well, awesome! 🚀

**Comment by ahhhndre** [comment]
If you regenerate the API Report that will fix the CI errors. On my phone so don’t have the command, I think it’s yarn build:api-reports

**Comment by ThomasAwesome** [comment]
> Thanks for this contribution @ThomasAwesome, LGTM
> 
> Bonus: if you could include an example in the changeset that would be, well, awesome! 🚀

I can update the changeset to include that.

**Comment by ThomasAwesome** [comment]
Updated the changeset and api-report

**Comment by ahhhndre** [comment]
Thanks @ThomasAwesome 

This is good for review and approval @benjdlambert

**Comment by benjdlambert** [comment]
Just made this a `patch` release as the package is still <1.0.0, but looks good! Thanks both! :pray:

**Review by benjdlambert — APPROVED** [review]

**Pull request merged**
