### PR TITLE
Revert "Upgraded microsite to Docusaurus 3.6"

### PR DESCRIPTION
**Pull request by vinzscam**
This reverts commit 93a091cdf8aba795b9446034f673f8d2e517a2cd.

## Hey, I just made a Pull Request!

I think timeline matches as [deploy_microsite.yml](https://github.com/backstage/backstage/actions/workflows/deploy_microsite.yml) is broken for some reason since then :(

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by freben** [comment]
@h7kanna if you have any ideas

**Comment by h7kanna** [comment]
Oh, I did not check the deploy step. only the build [step](https://github.com/backstage/backstage/actions/runs/11667467502/job/32484849457?pr=27460) which passed successfully.
I am suspecting CPU starvation indicated `The hosted runner: GitHub Actions 611 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.` as Docusaurus 3.6 does multithreading.

**Review by awanlin — APPROVED** [review]
Let's roll this back then 👍

**Review by Rugvip — APPROVED** [review]
:shipit:

**Review by jhaals — APPROVED** [review]

**Pull request merged**
